### ISSUE TITLE
LLVMX86CodeGen not linking correctly (cmake/MSVC)

### ISSUE THREAD

**Issue by benvanik** [google/iree#1080]
Library is not found during linking of any iree_cc_binary that transitively depends on the llvmjit_driver_module. May be a bad LLVM configuration in our options (not telling the x86 codegen backend to build?)

**Comment by marbre** [comment]
Checking locally, my Linux build only provides a `libLLVMCodeGen.a`. I think we need to expand
https://github.com/google/iree/blob/458eadc75d6359b29d29298e7e8d7d81dcf8708d/build_tools/cmake/iree_copts.cmake#L129

by `;X86`.
