### ISSUE TITLE
Missing BUILD file for thirdparty//llvm/llvm

### ISSUE THREAD

**Issue by harsh-nod** [google/iree#109]
~/bin/bazel test -k iree/...
fails with 
iree/iree/compiler/IR/BUILD:15:1: no such package 'third_party/llvm/llvm': BUILD file not found in any of the following directories.
iree/iree/compiler/Utils/BUILD:8:1: no such package 'third_party/llvm/llvm': BUILD file not found in any of the following directories.

**Comment by GMNGeoffrey** [comment]
Hmm I get the same error. Weird, I'm pretty sure this worked previously and I'm not sure what would've changed to produce that (those files have been depending on llvm for a while)

**Comment by GMNGeoffrey** [comment]
I think this might be https://github.com/google/iree/commit/aba395397a20f76dae8eb807ac65a56aed8f1392

which created references to the build file in iree_setup_lit, instead of using the @llvm bazel alias

**Comment by GMNGeoffrey** [comment]
That change actually should have been unrelated. It just happened to pick up some changes to the tooling that mirrors things on github. I believe I've identified the culprit internally and will see if we can't get things working again

**Comment by GMNGeoffrey** [comment]
Well I think I fixed that particular issue, but looks like there are more. I'll fiddle with it some more

**Comment by stellaraccident** [comment]
I'm looking too. We really need to prioritize getting the bots setup properly. Geoffrey, can you check with Ben on where he left off on that?

**Comment by stellaraccident** [comment]
FYI - this specific issue is fixed now but we also have some additional LLVM header issues (apologies -- there was a big LLVM move upstream and we're still adapting)

**Comment by stellaraccident** [comment]
As of 2082d028c30220fa43f06f2e5b80e70203f32e75, iree builds for me. Failing tests related to #111.

**Comment by harsh-nod** [comment]
Thanks for fixing this so soon guys! I can confirm I have been able to build iree as of [2082d02](https://github.com/google/iree/commit/2082d028c30220fa43f06f2e5b80e70203f32e75) with the exception of the failing test mentioned in [111](https://github.com/google/iree/issues/111).
