### ISSUE TITLE
integrations/tensorflow/bindings/python/pyiree/xla/compiler/BUILD:83:1: no such package 'third_party/py/pyiree/xla/compiler'

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#1090]
It looks like a bad dependency path has snuck into integrations/tensorflow/bindings/python/pyiree/xla/compiler/BUILD:83:1: no such package 'third_party/py/pyiree/xla/compiler'

This looks suspiciously like an upstream path that should not have come over (and does not exist on the OSS side).

Comes up if trying to do a `bazel test integrations/tensorflow/...`. Individual, non-affected test packages work.

**Comment by marbre** [comment]
Seems to be fixed by @GMNGeoffrey with commit 6c15ae5.
