### ISSUE TITLE
Warning: iree/compiler/Translation/Sequencer/SequencerModuleTranslation.cpp:248:1: warning: control reaches end of non-void function [-Wreturn-type] }

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#111]
iree/compiler/Translation/Sequencer/SequencerModuleTranslation.cpp:248:1: warning: control reaches end of non-void function [-Wreturn-type]
}

**Comment by stellaraccident** [comment]
There is a suspiciously failing test that might be related:

ERROR: /usr/local/google/home/laurenzo/ireepub/iree/iree/samples/rt/BUILD:10:1: Compiling IREE module simple_module_test_bytecode_module... //iree/samples/rt:simple_module_test_byt
ecode_module failed (Segmentation fault): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
                                                                               
Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
                                                                               
Use --sandbox_debug to see verbose messages from the sandbox                   
Stack dump:                                                                    
0.      Program arguments: bazel-out/host/bin/iree/tools/iree-translate -mlir-to-iree-module -o bazel-out/k8-opt/bin/iree/samples/rt/simple_module_test_bytecode_module.emod iree/sa
mples/rt/simple_module_test.mlir                                               
#0 0x0000000000af025d llvm::sys::PrintStackTrace(llvm::raw_ostream&) (bazel-out/host/bin/iree/tools/iree-translate+0xaf025d)
#1 0x0000000000aee2b5 llvm::sys::RunSignalHandlers() (bazel-out/host/bin/iree/tools/iree-translate+0xaee2b5)
#2 0x0000000000af0646 SignalHandler(int) (bazel-out/host/bin/iree/tools/iree-translate+0xaf0646)
#3 0x00007f06a0ca63a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x123a0)
#4 0x000000000059bad4 mlir::iree_compiler::translateMlirToIreeSequencerModuleFile(mlir::ModuleOp, llvm::raw_ostream&) (bazel-out/host/bin/iree/tools/iree-translate+0x59bad4)
#5 0x0000000000949d1b std::_Function_handler<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&, mlir::MLIRConte
xt*), mlir::TranslationParser::TranslationParser(llvm::cl::Option&)::$_1>::_M_invoke(std::_Any_data const&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuff
er> >&&, llvm::raw_ostream&, mlir::MLIRContext*&&) (bazel-out/host/bin/iree/tools/iree-translate+0x949d1b)
#6 0x0000000000413aa7 main (bazel-out/host/bin/iree/tools/iree-translate+0x413aa7)
#7 0x00007f06a08f852b __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2352b)
#8 0x00000000004132aa _start (bazel-out/host/bin/iree/tools/iree-translate+0x4132aa)
/bin/bash: line 1:     3 Segmentation fault      bazel-out/host/bin/iree/tools/iree-translate -mlir-to-iree-module -o bazel-out/k8-opt/bin/iree/samples/rt/simple_module_test_byteco
de_module.emod iree/samples/rt/simple_module_test.mlir

**Comment by benvanik** [comment]
wow, an actual time that -Werror would be useful :P

**Comment by GMNGeoffrey** [comment]
I think I'm actually getting segfaults caused by this issue. I've submitted a quick fix
