### ISSUE TITLE
[HLO2Linalg] Pad Op

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#1121]
Loweing Pad Op from XLA - HLO to Linalg op.

There are two possibilities here
1) Lower it to an indexed generic op on tensors and enhance fusion to handle indexed generic ops as well
2) Lower it to linalg on buffers by using a slice and copy, creating an intermediate buffer that gets fused away.

**Comment by antiagainst** [comment]
Is this accidentally closed?

**Comment by hanhanW** [comment]
Yes, it's accidentally closed.

**Comment by hanhanW** [comment]
The idea now is folding the pad op into following ops, i.e., conv op and reduce_window op. This is the exact pattern in ResNet and MobileNet.

WIP

**Comment by hanhanW** [comment]
Just a note -- a temp general solution is landed: https://github.com/google/iree/pull/1584
