### ISSUE TITLE
Use hal.buffer_view for tensor types on exported functions.

### ISSUE THREAD

**Issue by benvanik** [google/iree#1140]
Or some other way to move across shapes. The benefit of buffer_view is that when we add stride information we'll be able to tack it on there (even in the case of static shapes). The runtime `iree_hal_buffer_view_t` type is lightweight (as it just references a buffer) and is probably fine to materialize on demand for invocations.

**Comment by stellaraccident** [comment]
The downside (that I'm trying to decide if we care about) is that you need to bring all shape dims, not just the dynamic ones, which is not strictly necessary and just overhead.

**Comment by benvanik** [comment]
I think that's ok at the invocation level - it's a relatively costly operation compared to internal calls, where what the IR would likely do is extract the dynamic shape dims and continue without the buffer view wrapper. This can also give us better error messages (if not coming through python) as we can assert shape correctness for the dimensions that were known during compilation.

**Comment by benvanik** [comment]
(for example, [hal.buffer_view.buffer](https://github.com/google/iree/blob/master/iree/compiler/Dialect/HAL/IR/HALOps.td#L764) gets the buffer, and though it doesn't exist a `hal.buffer_view.shape` could return a ranked shape)

**Comment by stellaraccident** [comment]
sgtm. this will probably take me the day to wire through.

**Comment by stellaraccident** [comment]
Closing as this is done and integrated in the python bindings now (although there is further optimization work that could be done).
