### ISSUE TITLE
Add github actions for cmake builds on tons of platforms

### ISSUE THREAD

**Issue by benvanik** [google/iree#1156]
Similar to what's done here: https://github.com/Tencent/ncnn/tree/master/.github/workflows
Ignore bazel and tensorflow, cmake is good enough.

**Comment by kalcohol** [comment]
donot forget lighting up the building status matrix
ref: https://github.com/Tencent/ncnn/pull/1564
good luck~

**Comment by chitrak7** [comment]
Hi @ScottTodd  @benvanik  I would like to try this issue. Is this still open?

**Comment by ScottTodd** [comment]
@benvanik has been making progress on this on the `benvanik-ci` branch here: https://github.com/google/iree/commit/efa2f214ca1ae9691424a9c2ad630fb768be680d . There's also been some discussion in the `#builds` channel on IREE's Discord server. I'd wait to see how far Ben gets in the first pass before trying to help out.

A few areas that will probably benefit from some attention:

* Expanding build/test coverage (turning on more parts of the build, setting up more configurations)
* Displaying build status somewhere
* Improving build/test time through tweaking build settings and caching behavior
* Usability improvements such as improving logging (fixing / silencing warnings, making sure CMake tests produce useful logs, organizing test suite outputs so they're useful at a glance)
* Removing the `vulkan_extensionlayer` and `swiftshader` submodules + build files, changing helper scripts to download as needed, and updating user docs to mention downloading from the cache used on the CI.

**Comment by benvanik** [comment]
(dupe with #1818, whoops)
