### ISSUE TITLE
Standard dialect/HLO canonicalization and folding improvements

### ISSUE THREAD

**Issue by benvanik** [google/iree#1163]
There's a decent number of low-hanging canonicalizations and folders that are missing from the MLIR standard dialect and HLO. Some of these have larger impacts than others, but all reduce the IR complexity and runtime cost.

This tracking issue can be used to note potential improvements and issues can be sliced off or linked to the upstream projects (as the work would need to be done there).

If there are situations where upstream does not want the folder due to policy decisions we can have them in IREE however it's worth upstreaming to keep things together and help others benefit. A particular area in the past that caused friction was around what to do when folding caused overflow/NaN/etc, which for IREE is not an issue as we make no guarantees about exact bit matches between IREE backends or with other ML projects.

**Comment by benvanik** [comment]
Here's one example demonstrating that sequences of standard ops aren't folding in cases they could. These two muli ops should fold into a single op:

```mlir
  func @muls(%arg0 : index) -> index {
    %c7 = constant 7 : index
    %c10 = constant 10 : index
    %0 = muli %arg0, %c7 : index
    %1 = muli %0, %c10 : index
    return %1 : index
  }
```

This should be:
```mlir
  func @muls(%arg0 : index) -> index {
    %c70 = constant 70 : index
    %0 = muli %arg0, %c70 : index
    return %0 : index
  }
```

(these kinds of sequences are very common in shape and buffer offset/length calculations, so simplifying them would really clean up the IR)

**Comment by benvanik** [comment]
Here's another fun two: ((x + 1) -1) and (x/1)

```
  %c1 = constant 1 : index
  %20 = addi %19, %c1 : index
  %21 = subi %20, %c1 : index
  %22 = divi_unsigned %21, %c1 : index
```

**Comment by benvanik** [comment]
There doesn't appear to be any CFG simplification going on. I see things like this:
```
    cond_br %2, ^bb1, ^bb2
  ^bb1:	// pred: ^bb0
    call @simple_mul_switch_0_0(%c4, %cmd, %0) : (index, !hal.command_buffer, !hal.executable) -> ()
    br ^bb3
  ^bb2:	// pred: ^bb0
    br ^bb3
  ^bb3:	// 2 preds: ^bb1, ^bb2
```

Here, this should elide `^bb2` and rewrite the `cond_br` to jump right to `^bb3` in the case of failure. I may be missing a pass that does this, but I would have expected canonicalization to do it.

**Comment by benvanik** [comment]
This is a good set of IR to look through, as it contains many of the above examples:
https://gist.github.com/benvanik/cc49403752e2002b872b7d3a17df3cc0

For example, all this shape/workgroup math:
https://gist.github.com/benvanik/cc49403752e2002b872b7d3a17df3cc0#file-4-hal-output-mlir-L87-L104

And this region of the CFG:
https://gist.github.com/benvanik/cc49403752e2002b872b7d3a17df3cc0#file-4-hal-output-mlir-L67-L79

**Comment by benvanik** [comment]
Another example of a CFG simplification:

```mlir
  cond_br %0, ^bb1, ^bb2
^bb1:
  br ^bb5(%c1_i32 : i32)
```

Here, the cond_br could be changed to `cond_br %0, ^bb5(%c1_i32 : i32), ^bb2` and `^bb1` can later be dropped as unreachable.

**Comment by benvanik** [comment]
This case turning into a select would be cool, as then we can remove the branching behavior entirely:

```mlir
  cond_br %eqz, ^bb4, ^bb5
^bb4:
  br ^bb7(%c3 : i32)
^bb5:
  br ^bb7(%c4 : i32)
```

Could be:

```mlir
  %0 = select %eqz, %c3, %c4 : i32
  br ^bb7(%0 : i32)
```

This kind of case will show up a lot in code generated to switch between device parameters (alignments/strides/etc); in other words: per-dispatch overhead.

**Comment by benvanik** [comment]
(for those previous two, a combination of the first (br/cond_br folding) and the second (cond_br to the same target with different args to select canonicalization) would compose well)

**Comment by phoenix-meadowlark** [comment]
I submitted a change for review that adds in folders for division by one in `divi_signed` and `divi_unsigned`. I looked into some of the other other folds, but they're a bit out of scope for what I can do right now. I'm not currently planning on addressing them – should I unassign myself from the issue?

**Comment by River707** [comment]
I can take care of adding the control flow simplifications.

**Comment by benvanik** [comment]
Update: I've moved the CFG stuff over to the LLVM bug tracker: https://bugs.llvm.org/show_bug.cgi?id=45641

@phoenix-meadowlark Thanks for doing those! You can unassign if you think you're done for now. I'll go through and see if any more of these still remain and then file more targeted issues so it's easier to track.

**Comment by hanhanW** [comment]
> Here's one example demonstrating that sequences of standard ops aren't folding in cases they could. These two muli ops should fold into a single op:
> 
> ```mlir
>   func @muls(%arg0 : index) -> index {
>     %c7 = constant 7 : index
>     %c10 = constant 10 : index
>     %0 = muli %arg0, %c7 : index
>     %1 = muli %0, %c10 : index
>     return %1 : index
>   }
> ```
> 
> This should be:
> 
> ```mlir
>   func @muls(%arg0 : index) -> index {
>     %c70 = constant 70 : index
>     %0 = muli %arg0, %c70 : index
>     return %0 : index
>   }
> ```
> 
> (these kinds of sequences are very common in shape and buffer offset/length calculations, so simplifying them would really clean up the IR)

We do have this pattern in bert encoder.

Dispatch function:

```mlir
  func @foo(%arg0: tensor<1x384xf32>) -> tensor<1x1x384x384xf32> {
    %cst = constant dense<-1.000000e+04> : tensor<1x1x384x384xf32>
    %cst_0 = constant dense<1.000000e+04> : tensor<1x1x384x384xf32>
    %cst_1 = constant dense<1.000000e+00> : tensor<1x384x384xf32>
    %0 = "mhlo.reshape"(%arg0) : (tensor<1x384xf32>) -> tensor<1x1x384xf32>
    %1 = "mhlo.broadcast_in_dim"(%0) {broadcast_dimensions = dense<[0, 1, 2]> : tensor<3xi64>} : (tensor<1x1x384xf32>) -> tensor<1x384x384xf32>
    %2 = mhlo.multiply %1, %cst_1 : tensor<1x384x384xf32>
    %3 = "mhlo.reshape"(%2) : (tensor<1x384x384xf32>) -> tensor<1x1x384x384xf32>
    %4 = mhlo.multiply %3, %cst_0 : tensor<1x1x384x384xf32>
    %5 = mhlo.add %4, %cst : tensor<1x1x384x384xf32>
    return %5 : tensor<1x1x384x384xf32>
  }
```

which is lowered to Linalg on Tensors (fused):

```mlir
    %cst = constant 1.000000e+00 : f32
    %cst_0 = constant 1.000000e+04 : f32
    %cst_1 = constant -1.000000e+04 : f32
    %1 = linalg.generic { ...}
    ^bb0(%arg0: f32):  // no predecessors
      %2 = mulf %arg0, %cst : f32
      %3 = mulf %2, %cst_0 : f32
      %4 = addf %3, %cst_1 : f32
      linalg.yield %4 : f32
    } -> tensor<384x384xf32>
```

The `%2` and `%3` can be folded into a single `mulf` op.

Although it seems possible to fix in MHLO level, but the case is a bit complicated because the reshape op get involved. The simplest way is to add the pattern to std dialect.

**Comment by benvanik** [comment]
I'm doing a few of these in the VM dialect; they should be upstreamed to std though.

**Comment by benvanik** [comment]
Closing this as these should happen upstream in either std or mhlo - and hopefully we aren't the only people asking for them and wanting to fix them.
