### ISSUE TITLE
OSS bazel build broken on missing dependency

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#117]
ERROR: /usr/local/google/home/laurenzo/.cache/bazel/_bazel_laurenzo/aeb2f2bb7cbc4eb68307c702c2306745/external/zlib_archive/BUILD.bazel:5:1: undeclared inclusion(s) in rule '@zlib_archive//:zlib':
this rule is missing dependency declarations for the following files included by 'external/zlib_archive/gzclose.c':
  '/usr/lib/clang/8.0.1/include/stddef.h'
  '/usr/lib/clang/8.0.1/include/stdarg.h'
  '/usr/lib/clang/8.0.1/include/__stddef_max_align_t.h'
  '/usr/lib/clang/8.0.1/include/limits.h'

**Comment by stellaraccident** [comment]
"bazel clean --expunge" seems to have cleaned it up.

I've got a bug with the bazel team about this.

**Comment by GMNGeoffrey** [comment]
This happened to me once but I think referencing different libraries. expunge also fixed it then and I forgot about it
