### ISSUE TITLE
Compiler Errors in SPIR-V when building on MacOS with bazel.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#1188]
Running `bazel -k iree/...` on my laptop gives the following switch case error in SPIR-V.
```
ERROR: /private/var/tmp/_bazel_phoenix/8088abbe653bd92ed8e2cf7b8e2d77d0/external/spirv_tools/BUILD.bazel:133:1: Couldn't build file external/spirv_tools/_objs/spirv_tools/spirv_target_env.o: C++ compilation of rule '@spirv_tools//:spirv_tools' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 58 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/spirv_tools/source/spirv_target_env.cpp:24:11: error: enumeration value 'SPV_ENV_VULKAN_1_2' not handled in switch [-Werror,-Wswitch]
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:24:11: note: add missing switch cases
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:76:11: error: enumeration value 'SPV_ENV_VULKAN_1_2' not handled in switch [-Werror,-Wswitch]
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:76:11: note: add missing switch cases
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:153:11: error: enumeration value 'SPV_ENV_VULKAN_1_2' not handled in switch [-Werror,-Wswitch]
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:153:11: note: add missing switch cases
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:184:11: error: enumeration value 'SPV_ENV_VULKAN_1_2' not handled in switch [-Werror,-Wswitch]
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:184:11: note: add missing switch cases
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:215:11: error: enumeration value 'SPV_ENV_VULKAN_1_2' not handled in switch [-Werror,-Wswitch]
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:215:11: note: add missing switch cases
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:246:11: error: enumeration value 'SPV_ENV_VULKAN_1_2' not handled in switch [-Werror,-Wswitch]
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:246:11: note: add missing switch cases
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:281:11: error: enumeration value 'SPV_ENV_VULKAN_1_2' not handled in switch [-Werror,-Wswitch]
  switch (env) {
          ^
external/spirv_tools/source/spirv_target_env.cpp:281:11: note: add missing switch cases
  switch (env) {
```

**Comment by ScottTodd** [comment]
Looks like we should bump our https://github.com/KhronosGroup/SPIRV-Tools submodule (iree/third_party/spirv_tools) for Vulkan 1.2 support (check that repo for recent changes to that file, this particular error seems to be fixed upstream there already).

Updating submodules looks roughly like

```
$ cd third_party/spirv_tools
$ git pull
$ cd ../..
$ ./scripts/git/submodule_versions.py export
```

The script updates the `SUBMODULE_VERSIONS` file, which is used by some repository automation (see docs [here](https://github.com/google/iree/blob/master/docs/repository_management.md)).

Then send a pull request with the updated submodule and file.

Do you want to try that, Phoenix, or want someone else to?

**Comment by GMNGeoffrey** [comment]
I thought the submodule update should fix it but I'm confused because at the commit we're referencing for spirv_tools the enum doesn't have the field either.

https://sourcegraph.com/github.com/KhronosGroup/SPIRV-Tools/-/blob/include/spirv-tools/libspirv.h#L459

Also interesting that this is happening on mac but not on linux. Seems we should have less strict warnings/errors for third party dependencies.

**Comment by GMNGeoffrey** [comment]
> Updating submodules looks roughly like
> 
> ```
> $ cd third_party/spirv_tools
> $ git pull
> $ cd ../..
> $ ./scripts/git/submodule_versions.py export
> ```

The last time I tried this flow, the export (import?) was broken. Meant to file an issue after getting a proper reproduction.

**Comment by ScottTodd** [comment]
> > Updating submodules looks roughly like
> > ```
> > $ cd third_party/spirv_tools
> > $ git pull
> > $ cd ../..
> > $ ./scripts/git/submodule_versions.py export
> > ```
> 
> The last time I tried this flow, the export (import?) was broken. Meant to file an issue after getting a proper reproduction.

I might be missing a `git add -A` (staging the changes in the submodule for commit) in there before running the script (submodules are weird).

**Comment by phoenix-meadowlark** [comment]
I tried updating to a newer version of spirv_tools – that fixed this problem but also introduced a lot of new errors into the build.

**Comment by GMNGeoffrey** [comment]
> I tried updating to a newer version of spirv_tools – that fixed this problem but also introduced a lot of new errors into the build.

Let's have someone who currently has a functioning build update the submodule then. It will be hard to diagnose what errors are coming from random environment issues and what are "real".

**Comment by ScottTodd** [comment]
I see some errors after updating it as well.

**Comment by ScottTodd** [comment]
Looks like spirv_headers also needed to be updated. PR coming soon, then can someone test on macOS?

**Comment by ScottTodd** [comment]
Sent https://github.com/google/iree/pull/1241, after some local testing. I also discovered https://github.com/google/iree/issues/1244 during that, which appears to be unrelated/pre-existing.

**Comment by ScottTodd** [comment]
Also note that we don't expect Vulkan to work on macOS without something like https://github.com/KhronosGroup/MoltenVK set up. It could build though.

**Comment by ScottTodd** [comment]
Phoenix, can you give this another try?

**Comment by phoenix-meadowlark** [comment]
It's hard for me to say if this has been fixed or not because there is a new error coming from `spirv_tools` now. I'm not sure what the problem is, as `spvOpcodeString` is defined in `spirv_tools/source/opcode.cpp`. I'm pretty sure it was defined in the header file too when I was first seeing this this weekend, but I don't see it there anymore. This error repeats it self a couple hundred times for each call of `spvOpcodeString`.

```
ERROR: /private/var/tmp/_bazel_phoenix/842e823fca51e8fa41696d80600a8d91/external/spirv_tools/BUILD.bazel:131:1: Couldn't build file external/spirv_tools/_objs/spirv_tools/validate_logicals.o: C++ compilation of rule '@spirv_tools//:spirv_tools' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 58 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/spirv_tools/source/val/validate_logicals.cpp:38:19: error: use of undeclared identifier 'spvOpcodeString'
               << spvOpcodeString(opcode);
```

**Comment by MaheshRavishankar** [comment]
Is this still an issue? Could we close this if not?

**Comment by phoenix-meadowlark** [comment]
I didn't run into it when I wrote the macOS documentation, so I think that it's likely safe to say that it was fixed at some point.
