### ISSUE TITLE
submodule management script does not allow adding a new submodule

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#1189]
Trying to add a new submodule from upstream results in an error even if you add it to .gitmodules and SUBMODULE_VERSIONS. The intent is clear here. It should be able to handle this.

https://source.cloud.google.com/results/invocations/977ed471-0553-4489-af44-5808def417e5/targets/iree%2Fgcp_ubuntu%2Fcmake%2Fpresubmit/log

For this particular case I'll just add the submodule from the github side.

**Comment by benvanik** [comment]
Would prefer to have a note in the .gitmodules and SUBMODULE_VERSIONS about how to add a submodule ("run git status and copy the revision") rather than a script. Submodule additions should have a bit of friction and not require scripts.
