### ISSUE TITLE
Clang 9.0.1 fails when building absl due to unsupported debug levels

### ISSUE THREAD

**Issue by rsuderman** [google/iree#1216]
absl appears to have issues building at head with clang 9.0.1.

This doesn't occur if the user has Clang6.0.1.

**Comment by marbre** [comment]
Hm, I am using clang 9.0.1 by default, not a problem here.

**Comment by rsuderman** [comment]
It is strange. When I first built with 9.0.1 the build was failing. Switching away from 9.0.1 actually fixed the build. It's possible its an interop issue between the link and specific version of clang. I am hesitant to just mark as fixed and re-encounter the issue when someone else sets up another dev machine.

**Comment by benvanik** [comment]
Closing as this isn't reproducible. Please reopen if you have more issues.
