### ISSUE TITLE
Remove sidechannel dispatchability state and use the MLIR analysis cache

### ISSUE THREAD

**Issue by benvanik** [google/iree#1233]
The current flow dispatchability analysis pokes its data through to the later outlining phase as dispatchability must be computed prior to the intermediate transforms:
https://github.com/google/iree/blob/7a4a852b53b4fc196e48d641646bf90a8b407ed4/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L96-L117

River added a magic method to let us fix this by hooking into the cache invalidation logic so we can prevent the dispatchability analysis from being dropped:

 `bool isInvalidated(const AnalysisManager::PreservedAnalyses &)`

This would let us remove this nasty hack.

**Comment by qqsun8819** [comment]
@benvanik  I'm working on it ^_^

**Comment by qqsun8819** [comment]
https://github.com/google/iree/pull/1267 fix this issue
(I can not find a way to link this issue to pr ,maybe still the github  security stuff again, @benvanik please help me with that)
