### ISSUE TITLE
File not found during #include statement in non-parallel cmake build on MacOS.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#1236]
While running the cmake build on MacOS I get the following error:

```
[ 80%] Building CXX object build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/CMakeFiles/tensorflow_mlir_xla.dir/__/__/__/__/__/__/__/third_party/tensorflow/tensorflow/compiler/mlir/xla/transforms/xla_legalize_to_linalg.cc.o
In file included from /Users/phoenix/iree/third_party/tensorflow/tensorflow/compiler/mlir/xla/transforms/xla_legalize_to_linalg.cc:20:
In file included from /Users/phoenix/iree/third_party/llvm-project/mlir/include/mlir/Dialect/Linalg/IR/LinalgOps.h:12:
In file included from /Users/phoenix/iree/third_party/llvm-project/mlir/include/mlir/Dialect/Linalg/IR/LinalgTraits.h:12:
/Users/phoenix/iree/third_party/llvm-project/mlir/include/mlir/Dialect/Linalg/IR/LinalgTypes.h:24:10: fatal error: 'mlir/Dialect/Linalg/IR/LinalgOpsDialect.h.inc' file not found
#include "mlir/Dialect/Linalg/IR/LinalgOpsDialect.h.inc"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/CMakeFiles/tensorflow_mlir_xla.dir/__/__/__/__/__/__/__/third_party/tensorflow/tensorflow/compiler/mlir/xla/transforms/xla_legalize_to_linalg.cc.o] Error 1
make[1]: *** [build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/CMakeFiles/tensorflow_mlir_xla.dir/all] Error 2
```

Here is [that line in the code](https://sourcegraph.com/github.com/llvm/llvm-project@a711a3a46039154c38eade8bef1138b77fdb05ee/-/blob/mlir/include/mlir/Dialect/Linalg/IR/LinalgTypes.h#L24:16), and the corresponding [CMakeLists.txt](https://sourcegraph.com/github.com/llvm/llvm-project@a711a3a46039154c38eade8bef1138b77fdb05ee/-/blob/mlir/include/mlir/Dialect/Linalg/IR/CMakeLists.txt) file. I talked with Geoffrey, and it looks like the Bazel build generates this file [here](https://sourcegraph.com/github.com/google/iree/-/blob/build_tools/bazel/third_party_import/llvm-project/overlay/mlir/BUILD.bazel#L2697:34), however there's no corresponding line in the CMakeLists.txt file.

This doesn't happen when I run cmake in parallel, so it seems to be generated somewhere, but I don't know how to diagnose this problem. It appears to be working when I build it in parallel now after pulling from the repo today.

**Comment by benvanik** [comment]
Assuming this is obsolete since lei was building on mac between march and today.
