### ISSUE TITLE
Add an HLO->HLO conversion pass at the front of the IREE input pipeline

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1242]
Right now we add some random XLA HLO->HLO conversion patterns during the hlo->flow lowering.
It'd be better to run them as their own pass very early in the pipeline:
https://github.com/google/iree/blob/b877bbc0447bf64f1597c798f98054eb7ddb481c/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L36

We could then remove our calls here:
https://github.com/google/iree/blob/master/iree/compiler/Dialect/Flow/Transforms/PrePostPartitioningConversion.cpp#L56-L64

**Comment by hanhanW** [comment]
The test is located at: https://github.com/google/iree/blob/master/test/e2e/xla/batch_norm_inference.mlir

**Comment by stellaraccident** [comment]
Note that there is a conversion pass which expands to the fundamental ops. If you just add that, it should work (versus implementing a dedicated op).
