### ISSUE TITLE
vulkan_inference_gui is crashing (have hal.buffer but expected hal.buffer_view)

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#1244]
Seen on Windows as of https://github.com/google/iree/commit/49180e006478b3ca0d1210f4bd3ef8352d8040f7

> I ..\iree\samples\vulkan\vulkan_inference_gui.cc:547] IREE runtime API version 0
I ..\iree\samples\vulkan\vulkan_inference_gui.cc:558] Creating Vulkan driver/device
I ..\iree\hal\vulkan\api.cc:311] Creating VulkanDevice...
[vk_mem_alloc.h : 15777] RAW: vmaCreateAllocator
I ..\iree\hal\vulkan\api.cc:321] Successfully created device 'GeForce GTX 980 Ti'
I ..\iree\samples\vulkan\vulkan_inference_gui.cc:589] Loading simple_mul.mlir...
I ..\iree\samples\vulkan\vulkan_inference_gui.cc:605] Module loaded and context is ready for use
I ..\iree\samples\vulkan\vulkan_inference_gui.cc:689] Creating I/O buffers...
[vk_mem_alloc.h : 16824] RAW: vmaCreateBuffer
[vk_mem_alloc.h : 14433] RAW:   AllocateMemory: MemoryTypeIndex=10, AllocationCount=1, Size=256
[vk_mem_alloc.h : 11744] RAW:     Created new block Size=8388608
[vk_mem_alloc.h : 16824] RAW: vmaCreateBuffer
[vk_mem_alloc.h : 14433] RAW:   AllocateMemory: MemoryTypeIndex=10, AllocationCount=1, Size=256
[vk_mem_alloc.h : 11648] RAW:     Returned from existing block #0
E C:\dev\iree\iree/base/api_util.h:30] INVALID_ARGUMENT: Parameter 0 contains a reference to the wrong type; have hal.buffer but expected hal.buffer_view (class iree::vm::ref<struct iree_hal_buffer_view>); while executing hal.buffer_view.buffer
F ..\iree\samples\vulkan\vulkan_inference_gui.cc:732] Check failed: IREE_STATUS_OK == (iree_vm_invoke(iree_context, main_function, nullptr, input_list, output_list, { 0, iree_allocator_system_allocate, iree_allocator_system_free })) (0 vs. 3)
Debug Error!

Probably needs code changes following recent commits.

**Comment by GMNGeoffrey** [comment]
Oooh I ran into something like this when doing the check dialect. I think sometimes lowerings implicitly convert things to hal buffers instead of hal buffer views

**Comment by ScottTodd** [comment]
This started with https://github.com/google/iree/commit/7a4a852b53b4fc196e48d641646bf90a8b407ed4 . Verified that the program works without errors before that commit and crashes at that commit.

cc @stellaraccident 

The code that needs updating is probably in this block: https://github.com/google/iree/blob/476031aa2070702c4b731e1dd31e013f62bb9c59/iree/samples/vulkan/vulkan_inference_gui.cc#L688-L733

**Comment by stellaraccident** [comment]
Sorry - I had no way to verify things that aren't in the CI.

The default functions you call now take a buffer_view vs a buffer, as the error says. You can either:

1. Explicitly pack/unpack from a buffer_view (see vm_util.cc in that commit for an example). The nice thing about doing this "right" is that you'll get dynamic shape support.
1. We also export every function with a "$raw" suffix which operates purely on buffer as before (unchecked, type/shape erased, yolo). If you add a "$raw" suffix to your function name, it will use this and it should work as originally (might still want to do as above, but will unbreak you for now).

**Comment by ScottTodd** [comment]
👍 no problem, thanks for the pointers.
