### ISSUE TITLE
Bazel build support

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#13]
Need to migrate BUILD files from upstream and make compatible with OSS release.

This partially works now, with iree/base and iree/hal/vulkan building. Will iterate on the rest.

**Comment by ScottTodd** [comment]
I think we can call this generally done now:

* The full project builds with Bazel on Linux
* Most of the project builds with Bazel on Windows
* Most of the project is built and tested with Bazel on CI (Linux)
