### ISSUE TITLE
IREE module test runner

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#1308]
We've encountered a number of issues using lit + FileCheck for our IREE e2e tests. In particular:
1. The whole module goes through the same run block, which means any functions run have to take the same arguments and run on the same backends.
2. The compilation and the running all happen as part of a single binary, which means it doesn't support platforms on which we can't run the compiler (e.g. android).
3. FileCheck sucks for matching large shaped float literals, which is most of what we're doing.
4. FileCheck sucks at doing float fuzzy matching.
5. FileCheck isn't good at matching the same thing across a number of backends (need multiple run blocks).
6. Inputs can't be specified as constants because they'll get folded away.
7. split-input-file is error prone and isn't respected by FileCheck

I've been working on addressing this off and on for a bit (delayed by various code migrations and such). [`iree.do_not_optimize` and `iree.unfoldable_constant`](https://sourcegraph.com/github.com/google/iree@52a790bae2256b5bdee582127b26a8a97ab77481/-/blob/iree/compiler/Dialect/IREE/IR/IREEOps.td#L56) were a quick win that mostly handle (6).

We want to preserve the nice properties of lit tests though:
1. Source and test assertions sit together in the same file. No separate files pulled in so you have to go look at them when reading tests.
2. Making a change to the test does not require re-linking a C++ binary.
3. MLIR source is just source, not giant C++ string literals

We've now got an iree custom [module](https://sourcegraph.com/github.com/google/iree/-/tree/iree/modules/check) and [dialect](https://sourcegraph.com/github.com/google/iree/-/tree/iree/compiler/Dialect/Modules/Check) that contains test assertions. These can be compiled into an IREE module and used to make test assertions. Critically, the compilation and test runner are separate and the tests will run anywhere IREE can run.

Some previous discussion
https://groups.google.com/a/tensorflow.org/d/topic/mlir/hik5GKd4jsw/discussion

I'd like to roll this out to all our e2e tests. Currently pulling together the details on CMake test rules and making sure we're able to exclude easily certain test drivers (e.g. vulkan in builds that don't support it).

**Comment by benvanik** [comment]
iree-check-module needs some cleanup along with the other iree-*-module tools; going to fold those together.
