### ISSUE TITLE
Building docs requires enabling tests in the CMake configuration

### ISSUE THREAD

**Issue by antiagainst** [google/iree#1330]
At the moment one cannot just set `IREE_BUILD_DOCS` to `ON` without setting `IREE_BUILD_TESTS` to `ON`. There will be configuration errors for missing targets. I think it's because of how `TESTONLY` are handled in the configuration. Specifically, https://github.com/google/iree/blob/master/build_tools/cmake/iree_cc_embed_data.cmake#L88 and https://github.com/google/iree/blob/master/build_tools/cmake/iree_spirv_kernel_cc_library.cmake#L61. TESTONLY should be an option taking no parameters; so effectively we are marking all `iree_cc_embed_data` and `iree_spirv_kernel_cc_library` as test only.

**Comment by marbre** [comment]
@antiagainst Can you please try if this fixes your issue?

**Comment by antiagainst** [comment]
Yes #1340 should fix this. Thanks! :)
