### ISSUE TITLE
Update CI Kokoro VMs to run python tests

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#1346]
Currently the Kokoro VMs can't run the python binding tests because they don't have absl and they use Python 3.5. We need to update them to use Python 3.7, but we ran into issues doing so and had to roll back. See some discussion in https://github.com/google/iree/pull/837.

For Googlers, this is tracked internally in http://b/151445957 with links to Kokoro documentation and such.

**Comment by marbre** [comment]
Any update on this?

**Comment by GMNGeoffrey** [comment]
@phoenix-meadowlark is investigating putting everything in docker images so that updating the VMs isn't absolutely awful. I'm trying to get some help from the Kokoro team on this. That may end just being for Bazel though. Ben wants to move all our CMake CI to GitHub actions and has something partially setup which may make this not required for CMake.

**Comment by GMNGeoffrey** [comment]
@benvanik do you already have a docker image where we can run the IREE cmake build (without any of the other fancy stuff). The Kokoro docker image stuff is working pretty well and we could probably stick the current cmake build in docker image
