### ISSUE TITLE
When specifying explicit ModuleTranslationOptions.target_backends and one doesn't match, should warn/fail

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#135]
Currently, it silently does nothing, which cost me a fair bit of time to track down (i.e. was setting target_backends = ["interpreter", "vulkan"] but it should have been ["interpreter-*", "vulkan-*"]).

**Comment by benvanik** [comment]
Fixed: https://github.com/google/iree/blob/07b33a4c027540f578ee724ff18b918e25af8802/iree%2Fcompiler%2FDialect%2FHAL%2FTransforms%2FMaterializeInterfaces.cpp#L298-L316
