### ISSUE TITLE
Building the samples under Linux fails due to -SUBSYSTEM:WINDOWS linkopts

### ISSUE THREAD

**Issue by marbre** [google/iree#1359]
Building the samples, which are excluded in the CI (@GMNGeoffrey is there a specific reason?), fails with

```
[100%] Linking CXX executable vulkan_inference_gui
clang-9: error: unknown argument: '-SUBSYSTEM:WINDOWS'
make[2]: *** [iree/samples/vulkan/CMakeFiles/iree_samples_vulkan_vulkan_inference_gui.dir/build.make:261: iree/samples/vulkan/vulkan_inference_gui] Error 1
make[1]: *** [CMakeFiles/Makefile2:51840: iree/samples/vulkan/CMakeFiles/iree_samples_vulkan_vulkan_inference_gui.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```
due to

https://github.com/google/iree/blob/b3a420eb7b78f2c75d3d9a79ee9db4ece3bc5d81/iree/samples/vulkan/CMakeLists.txt#L57-L58

I think there was a discussion if this get's ignored under Linux (@ScottTodd ?), but it doesn't seems so.

**Comment by ScottTodd** [comment]
Thought I tested that :( oh well - need a platform switch to only include that option on Windows.

We can try including the build on the CI. I'm pretty sure it should build (but not run) without the Vulkan SDK configured.
