### ISSUE TITLE
Failed to execute linalg.fill + linalg.conv on vulkan-spirv

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1368]
After we have support for tiling and fusing Linalg ops, I tried it on linalg.fill + linalg.conv. It does succeed in #1356 . However, It fails when execute in e2e test.

I think the reason might be the serialization in SPIR-V or the lowering from GPU.

I would suspect SPIR-V more because it can't pass `mlir-translate -test-spirv-roundtrip z.mlir`. It crashes in Deserializer::structurizeControlFlow().

We can serialize it to a binary, and run `spirv-dis` on it. It fails in `spirv-val`:

```
error: line 177: OpPhi's incoming basic block <id> 73[%73] is not a predecessor of <id> 123[%123].
  %125 = OpPhi %uint %194 %126 %47 %73
```

Log: [fill_conv.txt](https://github.com/google/iree/files/4423743/fill_conv.txt)

To repro:
Download the log, and take the last spv code.
compile `mlir-translate`, `spirv-dis` and `spirv-val`.

$ mlir-translate -split-input-file -serialize-spirv z.mlir > z.binary
$ mlir-translate -split-input-file -test-spirv-roundtrip z.mlir
$ spirv-dis z.binary
$ spirv-val z.binary

**Comment by antiagainst** [comment]
Oops. Let me take a look.

**Comment by antiagainst** [comment]
This should be fixed by https://reviews.llvm.org/D77543.

**Comment by antiagainst** [comment]
Fix landed in upstream as https://github.com/llvm/llvm-project/commit/47b234944dc063daf61d3e72e6b603ba9615baf0. I'll close this. Let me know if you still have problems after the fix.

**Comment by hanhanW** [comment]
Thanks for fixing it, I'll verify it.
