### ISSUE TITLE
Create op coverage table

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1369]
Want a simple dashboard (or table) to see what XLA ops are supported in backends. The table should be updated automatically and maybe put a link in `Current Status`.

Now we only have a manually maintained [spreadsheet](https://docs.google.com/spreadsheets/d/15sjSnrINRQQuBK6RTFXUay-RC-ZrCT-u4oLLhmFc0xE/edit?usp=sharing), and everything is mixed together.

**Comment by bhack** [comment]
Where Is the list of updated XLA ops in TF?
Is It still in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/tf2xla/g3doc?

**Comment by antiagainst** [comment]
Hi @bhack, I'm not exactly sure what do you mean by "updated XLA ops in TF"? Do you mean XLA HLO ops supported in MLIR at the moment? Then you probably want to check the HLO's ODS [definitions](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/xla/ir/hlo_ops.td). 

This issue is to track IREE's supported list of XLA HLO ops and their status on each IREE backend.

**Comment by bhack** [comment]
I meant XLA/HLO in TF repo. I think that TF repo Is the only source of the XLA/HLO ops list. I don't know if you wiil list all in the coverage table to have an overview of the missing ops (no backend) other than ops with a One or more backends.

**Comment by antiagainst** [comment]
Got it. I think we will start with those ops with at least one IREE backend support. This is easier for us to derive from the repo in an automated way. We'd like to expand op support gradually with a model driven approach. There aren't many HLO ops anyway so hopefully a few common models can cover a large portion of them.

**Comment by bhack** [comment]
Do you will go to emit a full list of missing ops when you will try to "import" a new Model? It could be more useful to estimate the amount of work needed than fail fast on the frist missing op.

**Comment by hanhanW** [comment]
Yes, it's on our plate. I have a doc/script to do it manually, but it's not integrated into any tools yet.

**Comment by hanhanW** [comment]
The op coverage table can be found at https://google.github.io/iree/HLOOpCoverage
It will be updated automatically.
