### ISSUE TITLE
keras_vision_model_ResNet50_test produce wrong output

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1387]
With a tensorflow patch (sorry I don't know how to post it) and #1381, we are able to run ResNet50 on llvm-ir backend. However, the result is wrong, see below log: 

```
ERROR: test_application (__main__.AppTest)
test_application (__main__.AppTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iree/integrations/tensorflow/e2e/keras_vision_model_test.py", line 99, in test_application
    self.modules.applications.all.predict(input_data).print().assert_all_close()
  File ".../iree/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 297, in __call__
    for backend, f in self._backend_function_dict.items()
  File ".../iree/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 297, in <dictcomp>
    for backend, f in self._backend_function_dict.items()
  File ".../iree/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 256, in __call__
    return self._f(*args)
  File ".../iree/bindings/python/pyiree/rt/system_api.py", line 127, in __call__
    inputs = self._abi.raw_pack_inputs(args)
ValueError: Mismatched buffer item size (received: 8, expected: 4): For argument = [[[[0.18463433 0.77481092 0.59018217]
   [0.11772865 0.39442706 0.14569714]
   [0.02296862 0.19299344 0.80632011]
   ...
   [0.49450603 0.37142472 0.20792341]
   [0.24976105 0.27502322 0.10587285]
   [0.51371542 0.82016089 0.02980433]]
...

  [[0.98354535 0.96695961 0.68807856]
   [0.07782425 0.32245818 0.15561508]
   [0.97274008 0.51398169 0.64785209]
   ...
   [0.11817514 0.85816603 0.29659644]
   [0.72573277 0.80120776 0.77142597]
   [0.33097728 0.460969   0.97101945]]]] (expected Buffer<float32[1x32x32x3]>)
```

Instruction to run the model:
$ bazel test -c opt iree/integrations/tensorflow/e2e:keras_vision_model_ResNet50_test

**Comment by hanhanW** [comment]
With #1454 we can compile the model to VMLA backend. However, I got the same issue here.

I guess the error is because we are using float64 as input (py_view), and we allocate float32 in RawSignatureParser::Description. https://github.com/google/iree/blob/master/bindings/python/pyiree/rt/function_abi.cc#L137

A quick workaround is using float32 as input:
https://github.com/google/iree/blob/master/integrations/tensorflow/e2e/keras_vision_model_test.py#L98

`input_data = input_data.reshape(INPUT_SHAPE).astype(np.float32)`

After bypassing the error, it fails in https://github.com/google/iree/blob/master/iree/vm/module_abi_packing.h#L168:
```
E0408 18:11:52.660891  244606 api_util.h:30] INVALID_ARGUMENT: Parameter 0 contains a reference to the wrong type; have hal.executable_layout but expected hal.buffer (N4iree2vm3refI15iree_h
al_bufferEE); while executing hal.buffer.allocator
```

It seems that there are some issues in binding stuff? Any thoughts to fix it? @benvanik @stellaraccident @silvasean 

Instruction to repro:
patch #1454 
Replace l.98 in keras_vision_model_test.py with
`input_data = input_data.reshape(INPUT_SHAPE).astype(np.float32)`.
Run the model.

**Comment by hanhanW** [comment]
Update: Now #1454 and #1474 have been landed, we don't need any patch or modification to reproduce the issue.

It seems that there is a bug in HAL. The model is compiled without errors, but fails in predict function. We can get the mlir input file after running the test, i.e. it's located at `~/tmp/keras_vision_model_ResNet50_test/AppTest/input_vmla.mlir`.

The model takes a 1x32x32x3xf32 input, and it can be generated by following python script:

```python
import numpy as np
INPUT_SHAPE = [1, 32, 32, 3]
x = np.random.rand(np.prod(np.array(INPUT_SHAPE)))
x = x.reshape(INPUT_SHAPE).astype(np.float32)
np.savetxt('input.txt', x, fmt='%.3f', delimiter=' ', newline=' ')
```

Instruction to repro:
build keras_vision_model_ResNet50_test
./keras_vision_model_ResNet50_test --override_backends=iree_vmla

**Comment by hanhanW** [comment]
@benvanik Could you take a look at the error or give me some guidance so I can try to fix it?

**Comment by asaadaldien** [comment]
I ran iree-run-mlir with the saved iree input mlir file and hitting: 
`Parameter 0(N4iree2vm3refI15iree_hal_bufferEE) must not be null; while executing hal.buffer.allocator` from here:
https://github.com/google/iree/blob/master/iree/vm/module_abi_packing.h#L144

**Comment by stellaraccident** [comment]
I asked Ben directly on discord if he can help debug.

**Comment by asaadaldien** [comment]
mlir_file:
https://drive.google.com/file/d/1g7ZXnf44CvLmb27Xv6FdPcm_A7noyQDh/view?usp=sharing
