### ISSUE TITLE
Refresh Python API

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#14]
There is the beginning of Python bindings for the compiler and vm in the upstream repo. Need to integrate into the OSS repo and work out dependencies.

As a followon, the Python API should align with the upcoming C API.

**Comment by benvanik** [comment]
The current API is relatively out of date and could use an owner. Things like the signature mangling can be moved up into integrations/tensorflow/ and simplify the API usage which should assume that users can construct their invocations directly based on their particular frontend.

**Comment by ScottTodd** [comment]
This issue is very old. Let's close it and reopen more specific issues for future work?
