### ISSUE TITLE
Refresh project logistics and status documentation

### ISSUE THREAD

**Issue by antiagainst** [google/iree#1448]
- [ ] Document IREE architecture and component relationship
- [ ] Document IREE dependencies requirement
- [ ] Document IREE hardware support
- [ ] Collect and display IREE platform status
- [ ] Collect and display IREE op/model coverage status
- [ ] Provide development tips/guides

**Comment by ScottTodd** [comment]
This issue is stale and most of these have some related docs written already. Let's close?
