### ISSUE TITLE
Build Tracy profiler on the CI

### ISSUE THREAD

**Issue by benvanik** [google/iree#1478]
Just as we are building swiftshader it'd be nice to build and cache tracy binaries so that we can easily point people at host executables.

**Comment by benvanik** [comment]
Windows builds of the tracy profiler are available from the main repo, though on a big release delay: https://github.com/wolfpld/tracy/releases

**Comment by benvanik** [comment]
We should build this as a vcpkg feature (`iree[tracy-profiler]`) so that we always have a synced version available.

**Comment by ScottTodd** [comment]
Doesn't seem to me like we'd really need to own this? If Tracy's releases are infrequent or are missing platforms, wouldn't that be better solved on the main repo? I do see the benefit of a vcpkg feature though...

**Comment by benvanik** [comment]
Depends on whether we are always pinned to a major release - if we bump forwards then users need to build themselves. I'm fine with that but I've been asked for the binary a lot. We haven't been at anything but a major release in awhile so it may be fine to have temporary periods of "build it yourself" if it means less work for us.

**Comment by benvanik** [comment]
This got done in #7382 and #9596 has updated docs for using it.
