### ISSUE TITLE
Add tracy Vulkan support

### ISSUE THREAD

**Issue by benvanik** [google/iree#1481]
Tracy's [TracyVulkan.hpp](https://bitbucket.org/wolfpld/tracy/src/master/TracyVulkan.hpp) has a bunch of good helpers that look like would slot in well with the Vulkan HAL (reuse existing device/queue/etc, insert collection of queries into an existing command buffer, etc).

In theory this is all we need to get the traces, however unfortunately it looks like the header only works with statically linked Vulkan. It's a pretty small amount of code, though, and uses the core tracy APIs, so forking it and integrating it into our VulkanDevice may make the most sense.

**Comment by antiagainst** [comment]
Oh cool! Didn't know about this tool previously!

**Comment by benvanik** [comment]
Dupe of #1937.
