### ISSUE TITLE
CMake build of mlir/xla fails

### ISSUE THREAD

**Issue by marbre** [google/iree#149]
I am working on the CMake configuration, to solve #90. To solve the issue, `iree-translate` needs to be compiled, generally done by enabiling `IREE_BUILD_COMPILER`. This adds the subdirectory `build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla` to the targets, however the build currently fails.

First of all the two directories
- _build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/ir_ and
- _build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/transforms_

do not exist. This can be easily fixed by adding
```
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/ir")
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/transforms")
```
to the appropriate `CMakeLists.txt` (pull request will follow). This finally enables the generation of ir files and `generated_legalize_to_standard.inc` in the transforms directory. Anyway, the build still fails with:
```
[ 87%] Building CXX object third_party/llvm-project/llvm/tools/MLIR/lib/Transforms/CMakeFiles/MLIRTransforms.dir/AffineDataCopyGeneration.cpp.o
/home/mbrehler/repos/iree/iree/samples/hal/simple_compute_test.cc:36:10: fatal error: 'iree/samples/hal/simple_compute_test_module.h' file not found
#include "iree/samples/hal/simple_compute_test_module.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [iree/samples/hal/CMakeFiles/iree_samples_hal_simple_compute_test.dir/build.make:63: iree/samples/hal/CMakeFiles/iree_samples_hal_simple_compute_test.dir/simple_compute_test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:36790: iree/samples/hal/CMakeFiles/iree_samples_hal_simple_compute_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 87%] Building CXX object build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/CMakeFiles/tensorflow_mlir_xla.dir/__/__/__/__/__/__/__/third_party/tensorflow/tensorflow/compiler/mlir/xla/transforms/legalize_control_flow.cc.o
/home/mbrehler/repos/iree/third_party/tensorflow/tensorflow/compiler/mlir/xla/ir/hlo_ops.cc:113:10: fatal error: 'tensorflow/compiler/mlir/xla/transforms/generated_canonicalize.inc' file not
      found
#include "tensorflow/compiler/mlir/xla/transforms/generated_canonicalize.inc"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
As mentioned the file is present in _**build_tools**/third_party/tensorflow/tensorflow/compiler/mlir/xla/transforms_, but not in _third_party/tensorflow/tensorflow/compiler/mlir/xla/transforms_. So somehow the include paths seem to be messed up. As I am a little bit stuck here, maybe somebody has a hint.

**Comment by ScottTodd** [comment]
The include for `generated_canonicalize.inc` is missing an `external_tablegen_library` entry in `iree/build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/CMakeLists.txt`:

```
external_tablegen_library(
  PACKAGE
    tensorflow
  NAME
    mlir_xla_canonicalize_gen
  TBLGEN
    MLIR
  ROOT
    ${TF_MLIR_XLA_SRC_ROOT}
  SRCS
    "transforms/canonicalize.td"
  OUTS
    -gen-rewriters transforms/generated_canonicalize.inc
)
```

(then add to `DEPS` above)

After the `MAKE_DIRECTORY` changes you described and that change, I'm able to build the `tensorflow_mlir_xla` CMake target on Linux (though `iree_tools_iree_translate` still fails).

**Comment by ScottTodd** [comment]
Feel free to include those changes in your own PR.

We're hoping to exercise the CMake build in our continuous integration on GitHub soon, at which point we'll be able to list explicitly which targets aren't able to build yet and can enable them as they start to work.

**Comment by GMNGeoffrey** [comment]
FYI we now have a cmake CI, although it excludes the compiler portion of IREE (and therefore the MLIR dependencies). When we do get them working, I can change the option to add these to the CI.
