### ISSUE TITLE
Initialization issue in convolution test

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1493]
@GMNGeoffrey and I hit a bug in conv.test when we are moving the test to the check framework. This issue is for tracking initialization problem of convolution op.

**Comment by GMNGeoffrey** [comment]
You want a repro or do you already have one?

**Comment by hanhanW** [comment]
I already have one, thank you!

**Comment by asaadaldien** [comment]
Do you mean initializing output buffer of cov? If yes that will works fine by adding just adding linalg.fill(0) before conv. My understanding is that will not work for Vulkan

**Comment by hanhanW** [comment]
Some update.

I found that it's working on llvm-ir.

I hit the same issue when merging dot related test files. It seems that it reuses the same buffer. I don't know why this doesn't happen on llvm-ir. This only happens on vulkan.
