### ISSUE TITLE
TensorFlow colab integration

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#15]
We should add plumbing to launch a Colab kernel that pulls TensorFlow and the IREE Python API together. This will make it easy to interactively exercise the system, author models, etc.

The dependencies are fairly intricate to get right, which should be the main work that needs to be done. Once the build support is in place, we should publish a Docker image so anyone can experiment easily.

**Comment by ScottTodd** [comment]
Done a while ago (https://github.com/google/iree/blob/main/colab/start_colab_kernel.py)
