### ISSUE TITLE
Trouble getting swiftshader/timeline semaphore layer working on Debian/Buster

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#1576]
Following a variant of instructions here, I'm running into problems: https://google.github.io/iree/GetStarted/LinuxVulkan

Note that I am using the vulkan loader from the Debian Buster repo (using this or another doesn't seem to make a difference):

```shell
$ apt search libvulkan1
libvulkan1/stable,now 1.1.97-2 amd64 [installed,automatic]
  Vulkan loader library
```

The main variation I did was to create a ~/bin/swiftshader directory and copy libs into it:

```shell
$ ls -l ~/bin/swiftshader/
total 24616
-rwxr-xr-x 1 stella stella 25199256 Apr 19 18:32 libvk_swiftshader.so
-rw-r--r-- 1 stella stella      126 Apr 19 18:32 vk_swiftshader_icd.json
```

And then also a ~/bin/vulkan_layers:

```shell
$ ls -l ~/bin/vulkan_layers/
total 328
-rwxr-xr-x 1 stella stella 328728 Apr 19 18:34 libVkLayer_khronos_timeline_semaphore.so
-rw-r--r-- 1 stella stella    504 Apr 19 18:44 VkLayer_khronos_timeline_semaphore.json
```

Then set env vars:
```shell
$ echo $VK_LOADER_DEBUG
all
$ echo $VK_ICD_FILENAMES 
/home/stella/bin/swiftshader/vk_swiftshader_icd.json
$ echo $VK_LAYER_PATH 
/home/stella/bin/vulkan_layers
```

Then I run the device creation test:

```shell
$ ./iree/hal/cts/iree_hal_cts_device_creation_test
(log file attached)
```
[creation.log](https://github.com/google/iree/files/4500807/creation.log)

It looks like it is finding the layer but the error seems to imply not. Any ideas? Prior to us requiring this layer, I used a variation of this procedure on my dev VM to get Vulkan support for testing (since it has no GPU).

**Comment by ScottTodd** [comment]
That Vulkan loader (`1.1.97-2`) is too old to pick up the timeline semaphore functions from the extension layer. We should add `1.1.124` as the min version of the loader to the docs - you can get more recent versions by installing the Vulkan SDK or building the Vulkan loader from source.

We're expecting our current use of the extension layer to be similarly blocked on Android, and have ideas on how to directly embed it or polyfill support for timeline semaphores without going through the loader / layers / extensions interfaces.

**Comment by ScottTodd** [comment]
The extension layer is no longer required and we emulate timeline semaphore support internally as needed. I think this issue as stated is fixed.
