### ISSUE TITLE
[HLO2Linalg] Clamp op lowering

### ISSUE THREAD

**Issue by antiagainst** [google/iree#1582]
This is the last op pattern missing for compiling Keras MobileNet.

**Comment by antiagainst** [comment]
Sorry for the confusion. This is meant to be for Clamp op.

**Comment by hanhanW** [comment]
I looked into the MobileNet model, and I don't find any clamp op. How do you hit the error?

The way I tested is:
1) build integrations/tensorflow/e2e:keras_vision_model_MobileNet_test
2) Run the model with command `keras_vision_model_MobileNet_test --override_backends=tf,iree_vulkan`

A mlir filed can be found from a log: `Saving IREE input MLIR to: ...`. If you grep the file, you won't see clamp op.

**Comment by antiagainst** [comment]
Is `override_backends=iree_vulkan` using the structured ops path by default? I manually run `iree-opt` over the input MLIR by specifying `--iree-use-linalg-to-spirv-path`.

**Comment by hanhanW** [comment]
Oh I forgot to specify `--model=` in the command... Sorry about that.

**Comment by hanhanW** [comment]
> Is `override_backends=iree_vulkan` using the structured ops path by default? I manually run `iree-opt` over the input MLIR by specifying `--iree-use-linalg-to-spirv-path`.

It's using the direct path by default.

**Comment by MaheshRavishankar** [comment]
Clamp must be supported now. Closing
