### ISSUE TITLE
Support for runtime testing with dynamic shapes

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#1601]
We currently have limited support for testing with dynamic shapes because it's difficult to declare a constant with a dynamic shape (the compiler always actually knows the shape). We need something similar to iree.unfoldable_constant for dynamic shapes (or extend that to support them). Current reference example that makes use of iree-run-mlir passing input args is https://sourcegraph.com/github.com/google/iree/-/blob/iree/test/e2e/regression/dynamic_abs.mlir

I'll try to port that to something that doesn't require input arguments in some format outside of the mlir source.

**Comment by GMNGeoffrey** [comment]
A couple of ideas here (based on some discussions):

1. Use a tensor_cast of a constant to make it dynamic. Problem: the lowering pipeline doesn't currently support tensor_cast https://github.com/google/iree/issues/1643. There's some concern that this doesn't exercise the same flows as the normal dynamic shape handling with function calls and so requires building out things we won't otherwise need for a while.
2. Lower an op to a HAL BufferViewConstOp

One of the things I like about `unfoldable_constant`/`do_not_optimize` is that they're simple and actually pretty independent of iree. I don't love that (2) requires building this testing infra into the core compiler more deeply. It really seems like

```mlir
func @dynamic_tensor() -> tensor<?x?xf32> attributes { iree.module.export } {                                                                                 
  %c = constant dense<[[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]]> : tensor<2x3xf32>
  %c_unf = iree.do_not_optimize(%c) : tensor<2x3xf32>
  %c_dyn = tensor_cast %c_unf : tensor<2x3xf32> to tensor<?x?xf32>
  %c_dyn_unf = iree.do_not_optimize(%c_dyn) : tensor<?x?xf32>
  %result = "xla_hlo.abs"(%c_dyn) : (tensor<?x?xf32>) -> tensor<?x?xf32>                                                                                           
  return %result : tensor<?x?xf32>                                                                                                                                 
}
```

Should just work. With syntactic sugar it could be

```mlir
func @dynamic_tensor() -> tensor<?x?xf32> attributes { iree.module.export } {                                                                                 
  %c = iree.dynamic_constant dense<[[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]]> : tensor<2x3xf32> -> tensor<?x?xf32>
  %result = "xla_hlo.abs"(%c) : (tensor<?x?xf32>) -> tensor<?x?xf32>                                                                                           
  return %result : tensor<?x?xf32>                                                                                                                                 
}
```

**Comment by GMNGeoffrey** [comment]
@benvanik @stellaraccident 

It seemed like you had concerns about the tensor_cast approach. It seems like this is something that IREE should be able to support anyway (opaque op produces dynamic shape), but when I try I get a message like `remark: unable to materialize shape calculation (unsupported op 'std
.tensor_cast'?): falling back to runtime resolution` followed by https://github.com/google/iree/issues/1643. Stella, I'm guessing this was the sort of thing you were worried about tripping over earlier than necessary if we went this path? So if this seems not worth pursuing right now, I'll look into a new op with a direct lowering, but I want to double check because this seems like the cleanest approach from my vantage and it doesn't require doing anything special in the heart of the compiler to support this.

**Comment by benvanik** [comment]
tensor_cast is fragile, in that we should be trying hard to eliminate them by propagating shape information to everywhere we can (including cross-function). We don't want to rely on something we are explicitly trying to remove :) Same with a chain of DNO ops - requiring no changes to the IR structure (after CSE and canonicalization and inlining all the other things we do) won't work in more complex cases - it should only be used to ensure a value is not removed and not enforce the type of the value doesn't change (as say we are running on a device without float32 support, or performing quantization, etc - how do we DNO that constant? what's "optimize" mean here?)

There'd be nothing special "built into the compiler" about an iree.dynamic_constant -> hal.buffer_view.const - the alternative is to have tensor_cast support in the HAL layer and all that entails and that feels even more invasive (and again, fragile).

**Comment by GMNGeoffrey** [comment]
Couldn't we write a folder for that somewhere down the road though? I think we still need to hide it behind something that will not propagate shape information.

**Comment by benvanik** [comment]
yeah, and I guess what I'm saying is that we absolutely don't want tensor_cast to not propagate shape information :)

Anyway, one new op (or making the current unfoldable constant be able to cast implicitly) with one new rewrite pattern seems like an easy solution and minimally invasive. We need to support getting shape information dynamically at runtime from buffer_view, so any machinery we add will be getting tested by the buffer_view path. Arguments/results to functions passed in/out by the application come in as buffer_views, so using that as the base type makes sense and should be isomorphic to taking the value as an argument to the function. In other words, I don't see any reason not to use buffer_view, and a bunch of reasons not to :)

**Comment by GMNGeoffrey** [comment]
> yeah, and I guess what I'm saying is that we absolutely don't want tensor_cast to not propagate shape information :)
Yeah agreed. I was thinking of do_not_optimize being the thing that didn't propagate it. It's basically a barrier for compiler analysis. Unless we use this kind of explicit barrier, I think we're always going to be fighting ourselves as we invent more intelligent compiler passes.

> Anyway, one new op (or making the current unfoldable constant be able to cast implicitly) with one new rewrite pattern seems like an easy solution and minimally invasive. We need to support getting shape information dynamically at runtime from buffer_view, so any machinery we add will be getting tested by the buffer_view path. Arguments/results to functions passed in/out by the application come in as buffer_views, so using that as the base type makes sense and should be isomorphic to taking the value as an argument to the function. In other words, I don't see any reason not to use buffer_view, and a bunch of reasons not to :)

Yeah I'm fine using buffer_view, but we still need to hide the shape from the rest of the compiler. It can't know that it's just a buffer view of something static, which means that we have to be able to support unknown (not like unregistered, just unknown to shape inference) ops. It seems like there is a fallback path there, but I can't tell if it's working because then it blows up for (other?) reasons.

As a short-term workaround we could just rely on not having that particular folder, but I'm worried that will just come back to bite us later.

**Comment by GMNGeoffrey** [comment]
Got pulled aside by build copping and https://github.com/google/iree/issues/1754 last week, but back to looking at this. Ben and I discussed and came up with some ideas.

Short term, I think we'll just lower something to a buffer constant and rely on the lack of folding. I'll add a few tests to ensure that this doesn't get folded, so we don't inadvertently break things later on.

Longer term, we were thinking about providing what amounts to decorators that get converted into check functions. This would also help with #1538 and non-dynamic tests. This is similar to something Sean suggested at some point. Something like

```mlir
func @add(%lhs : tensor<?xi32>, %rhs : tensor<?xi32>) -> tensor<?xi32>
    attributes {
         args = [dense<1> : tensor<2xi32>, dense<2> : tensor<i32>],
         results = [dense<3> : tensor<2xi32>],
    } {
  %res = "xla_hlo.add"(%lhs, %rhs) : (tensor<?xi32>, tensor<?xi32>) -> tensor<?xi32>
  return %res : tensor<?xi32>
```

For normal compilation, these would just be opaque attributes, but we could have a late-stage pass that uses them to generate another function:

```mlir
func @add$test() {
  // pseudo-IR because there's also allocators and such
  %0 = hal.buffer_view.const(dense<1> : tensor<2xi32>) : hal.buffer_view
  %1 = hal.buffer_view.const(dense<2> : tensor<2xi32>) : hal.buffer_view
  %3 = hal.buffer_view.const(dense<3> : tensor<2xi32>) : hal.buffer_view
  %2 = vm.call @test(%0, %1) : (hal.buffer_view, hal.buffer_view) -> hal.buffer_view
  check.expect_eq(%2, %3) : hal.buffer_view
  return
```

**Comment by GMNGeoffrey** [comment]
Ok I have an op. Need to figure out how to make the dynamic shape lowerings work with it though. For some reason dim ops aren't being converted to shapex.ranked_dim ops

**Comment by GMNGeoffrey** [comment]
So the [ExpandFunctionDynamicDimsPass](https://sourcegraph.com/github.com/google/iree/-/blob/iree/compiler/Dialect/Shape/Transforms/FunctionSignatureExpansionPass.cpp) is where the ranked_shape arguments to functions appear from. I guess what I need to do is have something create such a value from unfoldable index dims and tie_shape to the result of the dynamic constant op.

**Comment by GMNGeoffrey** [comment]
Whelp no that doesn't seem to work.

```mlir
func @dynamic_tensor() -> tensor<?x?xf32> attributes { iree.module.export } {
  %input = iree.dynamic_shape_constant dense<[[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]]> : tensor<2x3xf32> -> tensor<?x?xf32>
  %shape = shapex.get_ranked_shape %input : tensor<?x?xf32> -> !shapex.ranked_shape<[?,?]>
  %tie = shapex.tie_shape %input, %shape : tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>
  %res = "xla_hlo.abs"(%tie) : (tensor<?x?xf32>) -> tensor<?x?xf32>
  return %res : tensor<?x?xf32>
}
```

Makes no difference at all. Exactly the same IR before iree-convert-flow-to-hal. I get a remark "unable to materialize shape calculation (unsupported op 'iree.dynamic_shape_constant'?): falling back to runtime resolution", which is fine. I want runtime resolution, but is runtime resolution actually implemented?

**Comment by GMNGeoffrey** [comment]
I've gotten to a new error!

```mlir
func @dynamic_tensor() -> tensor<?x?xf32> attributes { iree.module.export } {
  %input = iree.dynamic_shape_constant dense<[[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]]> : tensor<2x3xf32> -> tensor<?x?xf32>
  %dim0 = constant 2 : index
  %dim1 = constant 3 : index
  %shape = shapex.make_ranked_shape %dim0, %dim1 : (index, index) -> !shapex.ranked_shape<[?,?]>
  %tie = shapex.tie_shape %input, %shape : tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>
  %res = "xla_hlo.abs"(%tie) : (tensor<?x?xf32>) -> tensor<?x?xf32>
  return %res : tensor<?x?xf32>
}
```

->

```mlir
// *** IR Dump Before mlir::iree_compiler::(anonymous namespace)::ConvertFlowToHALPass ***
module {
  hal.executable @dynamic_tensor_ex_dispatch_0 attributes {sym_visibility = "private"} {
    hal.interface @legacy_io attributes {push_constants = 2 : i32} {
      hal.interface.binding @arg0, set=0, binding=0, type="StorageBuffer", access="Read"
      hal.interface.binding @ret0, set=0, binding=1, type="StorageBuffer", access="Write|Discard"
    }
    hal.executable.entry_point @dynamic_tensor_ex_dispatch_0 attributes {interface = @legacy_io, ordinal = 0 : i32, signature = (tensor<?x?xf32>, index, index) -> tensor<?x?xf32>}
    hal.executable.target "vmla" {
      module {
        vm.module @module {
          vm.func @dynamic_tensor_ex_dispatch_0(%arg0: !vm.ref<!vmla.interface>) {
            %zero = vm.const.i32.zero : i32
            %c4 = vm.const.i32 4 : i32
            %c1 = vm.const.i32 1 : i32
            %0 = vm.call @vmla.interface.const(%arg0, %c1) : (!vm.ref<!vmla.interface>, i32) -> i32
            %1 = vm.call @vmla.interface.const(%arg0, %zero) : (!vm.ref<!vmla.interface>, i32) -> i32
            %ref = vm.call @vmla.interface.binding(%arg0, %zero, %zero) : (!vm.ref<!vmla.interface>, i32, i32) -> !vm.ref<!vmla.buffer>
            %2 = vm.mul.i32 %1, %c4 : i32
            %3 = vm.mul.i32 %2, %0 : i32
            %ref_0 = vm.call @vmla.buffer.view(%ref, %zero, %3) : (!vm.ref<!vmla.buffer>, i32, i32) -> !vm.ref<!vmla.buffer>
            %ref_1 = vm.call @vmla.buffer.alloc(%3) : (i32) -> !vm.ref<!vmla.buffer>
            vm.call @vmla.abs.f32(%ref_0, %ref_1) : (!vm.ref<!vmla.buffer>, !vm.ref<!vmla.buffer>) -> ()
            %ref_2 = vm.call @vmla.interface.binding(%arg0, %zero, %c1) : (!vm.ref<!vmla.interface>, i32, i32) -> !vm.ref<!vmla.buffer>
            vm.call @vmla.buffer.copy(%ref_1, %zero, %ref_2, %zero, %3) : (!vm.ref<!vmla.buffer>, i32, !vm.ref<!vmla.buffer>, i32, i32) -> ()
            vm.return
          }
          vm.export @dynamic_tensor_ex_dispatch_0
          vm.import @vmla.interface.const(%interface : !vm.ref<!vmla.interface>, %offset : i32) -> i32 attributes {nosideeffects, sym_visibility = "private"}
          vm.import @vmla.interface.binding(%interface : !vm.ref<!vmla.interface>, %set : i32, %binding : i32) -> !vm.ref<!vmla.buffer> attributes {nosideeffects, sym_visibility = "private"}
          vm.import @vmla.buffer.alloc(%byte_length : i32) -> !vm.ref<!vmla.buffer> attributes {nosideeffects, sym_visibility = "private"}
          vm.import @vmla.buffer.view(%src : !vm.ref<!vmla.buffer>, %byte_offset : i32, %byte_length : i32) -> !vm.ref<!vmla.buffer> attributes {nosideeffects, sym_visibility = "private"}
          vm.import @vmla.buffer.copy(%src : !vm.ref<!vmla.buffer>, %src_byte_offset : i32, %dst : !vm.ref<!vmla.buffer>, %dst_byte_offset : i32, %byte_length : i32) attributes {sym_visibility = "private"}
          vm.import @vmla.abs.f32(%src : !vm.ref<!vmla.buffer>, %dst : !vm.ref<!vmla.buffer>) attributes {sym_visibility = "private"}
        }
      }
    }
  }
  func @dynamic_tensor() -> (tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>) attributes {iree.module.export, iree.reflection = {f = "I1!R10!B7!d-1d-1", fv = "1"}} {
    %c6 = constant 6 : index
    %c2 = constant 2 : index
    %c3 = constant 3 : index
    %0 = shapex.make_ranked_shape %c2, %c3 : (index, index) -> !shapex.ranked_shape<[?,?]>
    %1 = iree.dynamic_shape_constant dense<[[-1.000000e+00, 2.000000e+00, -3.000000e+00], [4.000000e+00, -5.000000e+00, 6.000000e+00]]> : tensor<2x3xf32> -> tensor<?x?xf32>
    %2 = flow.ex.stream.fragment(%arg0 = %1 : tensor<?x?xf32>, %arg1 = %c2 : index, %arg2 = %c3 : index, %arg3 = %c6 : index) -> tensor<?x?xf32> {
      %3 = shapex.make_ranked_shape %arg1, %arg2 : (index, index) -> !shapex.ranked_shape<[?,?]>
      %4 = shapex.tie_shape %arg0, %3 : tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>
      %5 = flow.dispatch @dynamic_tensor_ex_dispatch_0::@dynamic_tensor_ex_dispatch_0[%arg3 : index](%4, %arg1, %arg2) : (tensor<?x?xf32>, index, index) -> tensor<?x?xf32>
      %6 = shapex.tie_shape %5, %3 : tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>
      flow.return %6 : tensor<?x?xf32>
    }
    return %2, %0 : tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>
  }
}
```

->

[`buffer not preallocated`](https://sourcegraph.com/github.com/google/iree@cb864d6e237c338cf2c599b2749d20eacc6c9ded/-/blob/iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp#L279)

**Comment by GMNGeoffrey** [comment]
Regardless of anything else, that indicates a bug in that pass. Verifier-valid IR shouldn't be able to trigger an assert.

**Comment by GMNGeoffrey** [comment]
I think the issue is that I've lowered `dynamic_shape_constant` to a buffer view as part of flow-to-hal, but the stream fragment lowering wants all the arguments to be tensors or buffers.

**Comment by GMNGeoffrey** [comment]
Yup that was it. So I've got something working, but it requires a lot of manual crap in the starting IR:

```mlir
func @dynamic_tensor() -> tensor<?x?xf32> attributes { iree.module.export } {
  %input = iree.dynamic_shape_constant dense<[[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]]> : tensor<2x3xf32> -> tensor<?x?xf32>
  %dim0 = iree.unfoldable_constant 2 : index
  %dim1 = iree.unfoldable_constant 3 : index
  %shape = shapex.make_ranked_shape %dim0, %dim1 : (index, index) -> !shapex.ranked_shape<[?,?]>
  %tie = shapex.tie_shape %input, %shape : tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>
  %res = "xla_hlo.abs"(%tie) : (tensor<?x?xf32>) -> tensor<?x?xf32>
  return %res : tensor<?x?xf32>
}
```

As far as I can tell, there is no runtime shape resolution, atm. So we'll need a pass to add shape information for a bare `dynamic_shape_constant dense`. Canonicalization would be easiest, but need to ensure that it doesn't already have a shape associated so it doesn't get applied a bunch. I guess look for a `tie_shape` in the users and if there isn't one, generate it.

**Comment by GMNGeoffrey** [comment]
Whelp that's causing problems because the Shape dialect is dependent on the IREE dialect, so if I try to create Shape dialect op in the canonicalizer I create a circular dependency. Moving the op to the shape dialect causes something weird to happen that breaks VMLA lowering. Maybe because something checks the dialect and moves shape ops into the executable?

**Comment by benvanik** [comment]
I am unable to follow what you're doing but I feel like you may have wandered off the path. Maybe work on something else for a bit to give your brain a chance to digest things?

**Comment by GMNGeoffrey** [comment]
I should probably stop to allow my stomach to digest some things anyway. We can chat tomorrow. Basically, just creating a buffer_view during `flow -> hal` is not enough (and actually doesn't work at all because the types get mixed up). To get the shape calculation stuff we need additional buffer lowering + something to provide the shape info. Then trying to actually write that lead to annoying issues that depend on the dialect this op is in.

**Comment by GMNGeoffrey** [comment]
So chatting with Ben, lowering to a buffer view during conversion without any manual shape specification *is* supposed to work. I'm going to go back to trying that and seeing what breaks. The dim op lowering isn't getting triggered, but apparently it's supposed to be.

**Comment by GMNGeoffrey** [comment]
This is the error I'm seeing

```mlir
// *** IR Dump Before mlir::iree_compiler::(anonymous namespace)::ConvertFlowToHALPass ***                                                                    
                                                                                                                                                              
                                                                                                                                                              
module {                                                                                                                                                      
  hal.executable @dynamic_tensor_ex_dispatch_0 attributes {sym_visibility = "private"} {                                                                      
    hal.interface @legacy_io attributes {push_constants = 2 : i32} {                                                                                          
      hal.interface.binding @arg0, set=0, binding=0, type="StorageBuffer", access="Read"                                                                      
      hal.interface.binding @ret0, set=0, binding=1, type="StorageBuffer", access="Write|Discard"                                                             
    }                                                                                                                                                         
    hal.executable.entry_point @dynamic_tensor_ex_dispatch_0 attributes {interface = @legacy_io, ordinal = 0 : i32, signature = (tensor<?x?xf32>, index, index
) -> tensor<?x?xf32>}                                                                                                                                         
    hal.executable.target "vmla" {                                                                                                                            
      module {                                                                                                                                                
        vm.module @module {                                                                                                                                   
          vm.func @dynamic_tensor_ex_dispatch_0(%arg0: !vm.ref<!vmla.interface>) {                                                                            
            %zero = vm.const.i32.zero : i32                                                                                                                   
            %c4 = vm.const.i32 4 : i32
            %c1 = vm.const.i32 1 : i32
            %0 = vm.call @vmla.interface.const(%arg0, %c1) : (!vm.ref<!vmla.interface>, i32) -> i32
            %1 = vm.call @vmla.interface.const(%arg0, %zero) : (!vm.ref<!vmla.interface>, i32) -> i32
            %ref = vm.call @vmla.interface.binding(%arg0, %zero, %zero) : (!vm.ref<!vmla.interface>, i32, i32) -> !vm.ref<!vmla.buffer>
            %2 = vm.mul.i32 %1, %c4 : i32
            %3 = vm.mul.i32 %2, %0 : i32
            %ref_0 = vm.call @vmla.buffer.view(%ref, %zero, %3) : (!vm.ref<!vmla.buffer>, i32, i32) -> !vm.ref<!vmla.buffer>
            %ref_1 = vm.call @vmla.buffer.alloc(%3) : (i32) -> !vm.ref<!vmla.buffer>
            vm.call @vmla.abs.f32(%ref_0, %ref_1) : (!vm.ref<!vmla.buffer>, !vm.ref<!vmla.buffer>) -> ()
            %ref_2 = vm.call @vmla.interface.binding(%arg0, %zero, %c1) : (!vm.ref<!vmla.interface>, i32, i32) -> !vm.ref<!vmla.buffer>
            vm.call @vmla.buffer.copy(%ref_1, %zero, %ref_2, %zero, %3) : (!vm.ref<!vmla.buffer>, i32, !vm.ref<!vmla.buffer>, i32, i32) -> ()
            vm.return
          }
          vm.export @dynamic_tensor_ex_dispatch_0
          vm.import @vmla.interface.const(%interface : !vm.ref<!vmla.interface>, %offset : i32) -> i32 attributes {nosideeffects, sym_visibility = "private"}
          vm.import @vmla.interface.binding(%interface : !vm.ref<!vmla.interface>, %set : i32, %binding : i32) -> !vm.ref<!vmla.buffer> attributes {nosideeffects, sym_visibility = "private"}
          vm.import @vmla.buffer.alloc(%byte_length : i32) -> !vm.ref<!vmla.buffer> attributes {nosideeffects, sym_visibility = "private"}
          vm.import @vmla.buffer.view(%src : !vm.ref<!vmla.buffer>, %byte_offset : i32, %byte_length : i32) -> !vm.ref<!vmla.buffer> attributes {nosideeffects, sym_visibility = "private"}
          vm.import @vmla.buffer.copy(%src : !vm.ref<!vmla.buffer>, %src_byte_offset : i32, %dst : !vm.ref<!vmla.buffer>, %dst_byte_offset : i32, %byte_length : i32) attributes {sym_visibility = "private"}
          vm.import @vmla.abs.f32(%src : !vm.ref<!vmla.buffer>, %dst : !vm.ref<!vmla.buffer>) attributes {sym_visibility = "private"}
        }
      }
    }
  }
  func @dynamic_tensor() -> (tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>) attributes {iree.module.export, iree.reflection = {f = "I1!R10!B7!d-1d-1", fv = "1"}} {
    %0 = iree.dynamic_shape_constant dense<[[-1.000000e+00, 2.000000e+00, -3.000000e+00], [4.000000e+00, -5.000000e+00, 6.000000e+00]]> : tensor<2x3xf32> -> tensor<?x?xf32>
    %1 = dim %0, 1 : tensor<?x?xf32>
    %2 = dim %0, 0 : tensor<?x?xf32>
    %3 = muli %2, %1 : index
    %4 = shapex.make_ranked_shape %2, %1 : (index, index) -> !shapex.ranked_shape<[?,?]>
    %5 = flow.ex.stream.fragment(%arg0 = %0 : tensor<?x?xf32>, %arg1 = %2 : index, %arg2 = %1 : index, %arg3 = %3 : index) -> tensor<?x?xf32> {
      %6 = shapex.make_ranked_shape %arg1, %arg2 : (index, index) -> !shapex.ranked_shape<[?,?]>
      %7 = shapex.tie_shape %arg0, %6 : tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>
      %8 = flow.dispatch @dynamic_tensor_ex_dispatch_0::@dynamic_tensor_ex_dispatch_0[%arg3 : index](%7, %arg1, %arg2) : (tensor<?x?xf32>, index, index) -> tensor<?x?xf32>
      %9 = shapex.tie_shape %8, %6 : tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>
      flow.return %9 : tensor<?x?xf32>
    }
    return %5, %4 : tensor<?x?xf32>, !shapex.ranked_shape<[?,?]>
  }
}
iree/test/e2e/regression/dynamic_abs.mlir:5:12: error: failed to legalize operation 'std.dim' that was explicitly marked illegal
  %input = iree.dynamic_shape_constant dense<[[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]]> : tensor<2x3xf32> -> tensor<?x?xf32>
```

I had earlier assumed that this was the category of "things Stella didn't want to have to fix yet", but apparently this should be working when the operand of the dim op is lowered to a buffer view, so I'll dig deeper on this.

**Comment by GMNGeoffrey** [comment]
Yeah the issue is that the convert shape query ops looks specifically for a "BufferViewBufferOp", but this is a BufferViewConstOp, which is a pseudo op. The canonicalization to get it to a proper op probably isn't being run. Marking BufferViewConstOp illegal just makes my pattern lowering to it fail. Marking DynamicShapeConstOp as illegal moves the failure earlier. I thought dialect conversion was supposed to automatically register canonicalization patterns. So either need to do figure that out or manually expand it in the lowering.

**Comment by GMNGeoffrey** [comment]
Yeah it appears dialect conversion doesn't invoke canonicalizers. Inlining the canonicalization in my pattern still doesn't work because the `DimOp` lowering expects a `BufferViewBufferOp`, not a `BufferViewCreateOp`. It seems like that is excessively rigid and it should be fine with a buffer view as well.

**Comment by GMNGeoffrey** [comment]
```mlir
func @dynamic_tensor() -> tensor<?x?xf32> attributes { iree.module.export } {
  %input = iree.dynamic_shape_constant dense<[[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]]> : tensor<2x3xf32> -> tensor<?x?xf32>
  %res = "xla_hlo.abs"(%input) : (tensor<?x?xf32>) -> tensor<?x?xf32>
  return %res : tensor<?x?xf32>
}
```
->
```
EXEC @dynamic_tensor
2x3xf32=[1 2 3][4 5 6]
```

**Comment by GMNGeoffrey** [comment]
Now trying to make the check ops support dynamic shapes. This has the unfortunate side effect that I have to drop most of the type constraints from them, which also means the IR can't be as pretty using the declarative assembly format :-(

Also running into more places where the logic for finding the shapes is falling flat. I think tie_shape ops are getting sucked into stream fragments and then getting lost for anything that uses the shape outside the fragment

**Comment by benvanik** [comment]
You solved this I'm pretty sure.
