### ISSUE TITLE
keras_lstm_static_test fails on Bazel build after a0ffa61a

### ISSUE THREAD

**Issue by antiagainst** [google/iree#1620]
```
git checkout 9b47a6ceeed3d8dcbe74f1e041227fb05d3ea225
git cherry pick b5beff559cc72203913825a42f4b2d15c8d098bf // Fix dependency
git submodule update
bazel run //integrations/tensorflow/e2e:keras_lstm_static_test
```
The test pass. Bump to include a0ffa61a:

```
git checkout a0ffa61ad8c55cd76b7c3d4449ea909a71529ee3
git cherry pick b5beff559cc72203913825a42f4b2d15c8d098bf // Fix dependency
git submodule update
bazel run //integrations/tensorflow/e2e:keras_lstm_static_test
```

The test fail with
```
[ RUN      ] LstmTest.test_lstm
E ./iree/base/api_util.h:30] INVALID_ARGUMENT: Parameter 0 contains a reference to the wrong type; have hal.buffer but expected tensorlist.list (N4iree2vm3refINS_12_GLOBAL__N_110TensorListEEE); while executing tensorlist.set_item
```

**Comment by antiagainst** [comment]
Diff'ed bazel-generated VM module IR and blaze-generated ones; same. Suspect things went wrong in the VM runner. Attached the VM module's IR.

[vm-module.txt](https://github.com/google/iree/files/4519567/vm-module.txt)

**Comment by benvanik** [comment]
```
iree-opt -split-input-file -pass-pipeline='vm.module(test-iree-vm-register-allocation)' D:/Dev/iree/iree/compiler/Dialect/VM/Analysis/test/lei.mlir | IreeFileCheck D:/Dev/iree/iree/compiler/Dialect/VM/Analysis/test/lei.mlir
Assertion failed: feedbackArcSet.feedbackEdges.size() == 1 && "liveness tracking of scratch registers not yet implemented", file D:\Dev\iree\iree\compiler\Dialect\VM\Analysis\RegisterAllocation.cpp, line 522
```

We should be running with assertions enabled :)

Will fix.

**Comment by antiagainst** [comment]
LOL. That again confirms the first step of debugging: pass in `-log-level=∞`. Thanks Ben for spotting the issue!

Still wondering the internal vs external differences though: is it because we have some internal magic that just happens to remedy the issue and avoids triggering the assertion? Waiting for the pull request now. :)

**Comment by benvanik** [comment]
I think I have a fix but now need to setup bazel to test. Here if you want to give it a shot while I eat lunch: https://github.com/google/iree/pull/1662

**Comment by benvanik** [comment]
nevermind, still needs work

**Comment by GMNGeoffrey** [comment]
> We should be running with assertions enabled :)

#1664
