### ISSUE TITLE
Libs linked into iree-tblgen as whole archive

### ISSUE THREAD

**Issue by marbre** [google/iree#1627]
The targets `iree::compiler::Dialect::IREE::Tools` and `iree::compiler::Dialect::VM::Tools` or rather `//iree/compiler/Dialect/IREE/Tools` and `//iree/compiler/Dialect/VM/Tools` are linked as whole archive into `iree-tblgen.` It would be nice to get rid of alwayslink. For the CMake build it is sufficient to just drop the `ALWAYSLINK` flags and `iree-tblgen` is build as expected. Building with Bazel the symbols not explicitly used get stripped and thus the build fails as `iree-tblgen` with the additional command line options is required within a clean build. Thus the first approach in #1613 does not work out and if we want to get rid of alwayslink, we need to look for another solution.

**Comment by ScottTodd** [comment]
Removing from CMake but keeping in Bazel is an option, if the CMake build still works reliably without it. Since Bazel has native support for `alwayslink`, it seems fine (though not ideal) to keep a few uses in there. We could add a way for `bazel_to_cmake` to omit it when converting.

**Comment by marbre** [comment]
I would rather like to avoid a diverge between Bazel and CMake. I think this could also be closed as `wontfix`, but opened the issue to discuss on how to handle it.

**Comment by GMNGeoffrey** [comment]
Building with CMake doesn't strip unused symbols? :eyes:

I think removing this would require work upstream to tablegen. Maybe @antiagainst has more thoughts on whether/why tablegen requires static initializers?

**Comment by marbre** [comment]
The difference might be that we build LLVM with RTTI in the CMake world. No idea what is happening in Bazel, but for sure this is related to some compile options.

**Comment by benvanik** [comment]
#3874 killed alwayslink!
