### ISSUE TITLE
HAL driver modules linked as whole archive

### ISSUE THREAD

**Issue by marbre** [google/iree#1630]
Several HAL driver modules are marked alwayslink, also see:
https://github.com/google/iree/blob/ace19e886efe3702bfe7b17185a5daaa20808e82/iree/hal/driver_registry.h#L37-L44
If the desired the drivers can be explicitly registered, which would affect the following targets:

- [ ] `iree::hal::llvmjit::llvmjit_driver_module`
       CMake and Bazel
- [ ] `iree::hal::vmla::vmla_driver_module`
       CMake and Bazel
- [ ] `iree/hal/vulkan/vulkan_driver_module`
       CMake and Bazel
- [ ] `iree/hal/dawn/dawn_driver_module`
       Only exists in the Bazel world.

Seems that the alwayslink flags can be dropped in the CMake build without an impact on the test coverage, but this does not holds for Bazel, see #1629.

**Comment by marbre** [comment]
@benvanik You commited the comment cited above. Is it desirable to explicitly register the driver modules?

**Comment by benvanik** [comment]
Fixed as part of #3874!
