### ISSUE TITLE
Dialect in custom_modules samples linked as whole archive

### ISSUE THREAD

**Issue by marbre** [google/iree#1636]
The dialect `iree::samples::custom_modules::dialect` is not explicitly registered. Instead the dialect is marked alwayslink and linked as whole archive into `custom-opt` and `custom-translate.` If possible the dialect should be explicitly registered, but the dialect is only extending an existing dialect and not a whole dialect on its own. Also affects the forked sample https://github.com/iml130/iree-template-cpp/tree/master/custom_modules.

**Comment by marbre** [comment]
Surprisingly, just dropping alwayslink works with CMake, but is does not with Bazel. To get rid of linking in the whole archive, a helper function that explicitly registers the dialect is necessary. Such a function needs to be called within the main function, implemented in `iree_opt_main` and `iree_translate_main`. However, with does not work out for *external* dialects, which are not known to iree.
One possible solution would be to "fork" the source files "opt_main.cc" and "translate_main.cc" and extend them by the call of a registration function (implemented in an addition header, "init_custom_dialect.h"). This is also the way used in MLIR's out-of-tree example and I will probably choose it for the *iree-template-cpp* out-of-tree example. Do we further want to choose this solution for the in-tree example?

**Comment by ScottTodd** [comment]
Following the same conventions as out-of-tree examples for the in-tree samples seems good. If maintenance gets annoying we could keep `alwayslink` but add comments about alternatives.

**Comment by marbre** [comment]
Will solve this out-of-tree and get to the in-tree sample afterwards.
