### ISSUE TITLE
Base targets are linked as whole archive

### ISSUE THREAD

**Issue by marbre** [google/iree#1637]
The components
- [x] `iree::base::localfile`
- [ ] `iree::base::tracing_enabled`
- [ ] `iree::base::tracing_disabled`
are marked alwayslink and are thus linked as whole archive. If possible we would like to avoid this.

**Comment by ScottTodd** [comment]
I think we could remove `alwayslink` from `iree/base:localfile`. The `platform_trampoline_deps` implementations can set `alwayslink` themselves as needed, and that only matters right now in Google's Bazel build.

Tracing is different, and currently relies on `alwayslink` for this setup: https://github.com/google/iree/blob/ace19e886efe3702bfe7b17185a5daaa20808e82/iree/base/tracing.cc#L221-L223

**Comment by marbre** [comment]
Without having looked deeper into iree_tracing, is there a realistic option to get rid of alwayslink at all?

**Comment by ScottTodd** [comment]
> Without having looked deeper into iree_tracing, is there a realistic option to get rid of alwayslink at all?

Some ideas for alternatives to using `alwayslink` for tracing:

1. If we consider tracing on/off to be part of the program environment, we could depend on `iree/base:tracing` in `iree/base/internal:init_internal` and call `::iree::InitializeTracing()` somewhere in `InitializeEnvironment`: https://github.com/google/iree/blob/a970162d8efaad05f2093755da1258d58493a62f/iree/base/internal/init_internal.cc#L26-L40

2. Add explicit calls to `::iree::InitializeTracing()` to each binary (`gtest_main_internal.cc`, `benchmark_main.cc`, etc.)

**Comment by GMNGeoffrey** [comment]
The nice thing about having tracing be a link-time dep is that it's easy to control with config settings. To achieve the same result without that I think we'd need ifdef guards around it as well.

**Comment by ScottTodd** [comment]
`alwayslink` removed from tracing targets in https://github.com/google/iree/pull/1936
