### ISSUE TITLE
MobileNet doesn't work on VMLA backend 

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1651]
The compilation is done with #1650 . However, it produces wrong output. All the values are "nan".

Instruction to repro:
(1)
$ build keras_vision_model_MobileNet_test
$ keras_vision_model_MobileNet_test --model=MobileNet --override_backends=iree_vmla

(2)
1) Download the mlir file: https://drive.google.com/file/d/1Zi_7U4jxh0DrzPgJVqAQRNIk0CRivXcI/view?usp=sharing
2) build iree-run-mlir
3) generate a 1x32x32x3xf32 input
4) Run command `iree-run-mlir -iree-hal-target-backends=vmla MobileNet.mlir -input-value="1x32x32x3xf32=..."`

**Comment by hanhanW** [comment]
I got the reason, there is an ASAN error during the execution.

If there is a DepthConv2D, tf2xla will lower the op to xla_hlo.reshape op + xla_hlo.conv op. @asaadaldien had a fix to remove the reshape op in HLOToHLOPreprocessing. E.g.,

```
%275 = "xla_hlo.reshape"(%166) : (tensor<3x3x32x1xf32>) -> tensor<3x3x1x32xf32>
%276 = "xla_hlo.convolution"(%274, %275) { ... } : (tensor<1x16x16x32xf32>, tensor<3x3x1x32xf32>) -> tensor<1x16x16x32xf32>
```

will be rewritten to

```
%276 = "xla_hlo.convolution"(%274, %166) { ... } : (tensor<1x16x16x32xf32>, tensor<3x3x32x1xf32>) -> tensor<1x16x16x32xf32>
```

In this case, the shape of the filter is different.

However, in the beginning of the processing, we run a canonicalize pass. The reshape op has been folded into the previous op, and it becomes a xla_hlo.constant op after the pass. In this case, we failed to identify that this conv op is a depth conv op so the filter is not reshaped. Thus, in VMLA implementation, there is an out-of-bound accessing (because we didn't reshape the filter back). (@benvanik please correct me if the folding stuff is not the case)

@asaadaldien any ideas to fix it?

Before canonicalize pass:
```
%5 = flow.variable.address @"__iree_flow___sm_node116__m.layer-5.depthwise_kernel" : !iree.ptr<tensor<3x3x32x1xf32>>
%166 = flow.variable.load.indirect %5 : !iree.ptr<tensor<3x3x32x1xf32>> -> tensor<3x3x32x1xf32>
%275 = "xla_hlo.reshape"(%166) : (tensor<3x3x32x1xf32>) -> tensor<3x3x1x32xf32> 
%276 = "xla_hlo.convolution"(%274, %275) {batch_group_count = 1 : i64, dimension_numbers = {input_batch_dimension = 0 : i64, input_feature_dimension = 3 : i64, input_spatial_dimensions =
dense<[1, 2]> : tensor<2xi64>, kernel_input_feature_dimension = 2 : i64, kernel_output_feature_dimension = 3 : i64, kernel_spatial_dimensions = dense<[0, 1]> : tensor<2xi64>, output_batch_dimension = 0 : i64, output_feature_dimension = 3 : i64, output_spatial_dimensions = dense<[1, 2]> : tensor<2xi64>}, feature_group_count = 32 : i64, padding = dense<1> : tensor<2x2xi64>, rhs_dil
ation = dense<1> : tensor<2xi64>, window_strides = dense<1> : tensor<2xi64>} : (tensor<1x16x16x32xf32>, tensor<3x3x1x32xf32>) -> tensor<1x16x16x32xf32>
```

After canonicalize pass:
```
%6 = xla_hlo.constant dense<...> : tensor<3x3x1x32xf32>
%18 = "xla_hlo.convolution"(%17, %6) {batch_group_count = 1 : i64, dimension_numbers = {input_batch_dimension = 0 : i64, input_feature_dimension = 3 : i64, input_spatial_dimensions = dense<[1, 2]> : tensor<2xi64>, kernel_input_feature_dimension = 2 : i64, kernel_output_feature_dimension = 3 : i64, kernel_spatial_dimensions = dense<[0, 1]> : tensor<2xi64>, output_batch_dimension = 0 : i64, output_feature_dimension = 3 : i64, output_spatial_dimensions = dense<[1, 2]> : tensor<2xi64>}, feature_group_count = 32 : i64, padding = dense<1> : tensor<2x2xi64>, rhs_dilation = dense<1> : tensor<2xi64>, window_strides = dense<1> : tensor<2xi64>} : (tensor<1x16x16x32xf32>, tensor<3x3x1x32xf32>) -> tensor<1x16x16x32xf32>
```

**Comment by hanhanW** [comment]
Update: A quick workaround is to comment out the reshape op in [legalize_tf.cc](
https://github.com/tensorflow/tensorflow/blob/7ebd41b86871ee5ff5221fe31ae2571fb8e96ef5/tensorflow/compiler/mlir/xla/transforms/legalize_tf.cc#L1022-L1033). Then there is no issue to run the model on VMLA.

btw I'm not sure if the result is correct because all the values are less than 1e-10... @rybakov do we need a more robust input test data for this model?

**Comment by asaadaldien** [comment]
Thanks @hanhanW for digging for the reason, Yeah xla insisted to add the resahpe and consistent with xla client so we have to keep the reshape in the xla side.
From our side we can fix this by constructing  the reshape from `feature_group_count` parameter and filter shape.

**Comment by hanhanW** [comment]
> Thanks @hanhanW for digging for the reason, Yeah xla insisted to add the resahpe to be consistent with xla client so we have to keep the reshape in the xla side.
> From our side we can fix this by constructing the reshape from `feature_group_count` parameter and filter shape.

Don't we already do it? Or you mean we add an additional reshape right before the depth conv op while now we are removing the reshape op (although it somehow disappeared :p)? The question would be how do we determine if this is a depth conv op, by looking into the value of `feature_group_count`?

**Comment by asaadaldien** [comment]
feature_group_count > 1 && filter[kernel_input_feature_dim] = 1
 yes add a reshape which will set  filter[kernel_input_feature_dim] = feature_group_count,  filter[kernel_output_feature_dim] =filter[kernel_output_feature_dim] / feature_group_count
in your example it will return reshape back to <3x3x32x1xf32>

**Comment by rybakov** [comment]
> Update: A quick workaround is to comment out the reshape op in [legalize_tf.cc](https://github.com/tensorflow/tensorflow/blob/7ebd41b86871ee5ff5221fe31ae2571fb8e96ef5/tensorflow/compiler/mlir/xla/transforms/legalize_tf.cc#L1022-L1033). Then there is no issue to run the model on VMLA.
> 
> btw I'm not sure if the result is correct because all the values are less than 1e-10... @rybakov do we need a more robust input test data for this model?

Yes, I am working on new CL which fixes issue output values < 1e-10
