### ISSUE TITLE
convert-flow-to-hal pass results in null operands in stream fragments

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#1652]
```
func @repro(%static : tensor<1xf32>, %dynamic: tensor<?x?xf32>) {
  flow.ex.stream.fragment(%frag_static = %static : tensor<1xf32>) {
    flow.tensor.update %frag_static, %frag_static[] : tensor<1xf32> -> tensor<1xf32>
    flow.return
  }
  %break_things = dim %dynamic, 0 : tensor<?x?xf32>
  return
}
```

With `$ iree-opt -iree-convert-flow-to-hal --print-ir-after-all` this segfaults. The dim operation is only there to make lowering fail. The issue is that the tensor update ends up with null operands. Also happens with make_ranked_shape.

With some local hacks to the asmprinter, I got it to not segfault on null values and types:

```mlir
*** IR Dump After mlir::iree_compiler::(anonymous namespace)::ConvertFlowToHALPass Failed ***
"module"() ( {
  "func"() ( {
  ^bb0(%arg0: tensor<1xf32>, %arg1: tensor<?x?xf32>):   // no predecessors
    "flow.ex.stream.fragment"(%arg0) ( {
    ^bb0(%arg2: tensor<1xf32>): // no predecessors
      %1 = "flow.tensor.update"(<<NULL>>, <<NULL>>) : (<<NULL TYPE>>, <<NULL TYPE>>) -> tensor<1xf32>
      "flow.return"() : () -> ()
    }) : (tensor<1xf32>) -> ()
    %0 = "std.dim"(%arg1) {index = 0 : index} : (tensor<?x?xf32>) -> index
    "std.return"() : () -> ()
  }) {sym_name = "repro", type = (tensor<1xf32>, tensor<?x?xf32>) -> ()} : () -> ()
  "module_terminator"() : () -> ()
}) : () -> ()
```

This seems to only happen if the conversion fails. If I remove the dim op, which makes the conversion fail, it proceeds happily.

**Comment by benvanik** [comment]
Nice catch!

**Comment by GMNGeoffrey** [comment]
I think the error comes from ExStreamFragmentOpConversion because if I replace it with 

```
rewriter.replaceOp(streamOp, {});
return success();
```

we don't see the nulls.

**Comment by GMNGeoffrey** [comment]
Ok it's something in

```
    for (int i = 0; i < operands.size(); ++i) {
      if (operands[i].getType().isa<IREE::HAL::BufferType>()) {
        rewriter.replaceUsesOfBlockArgument(entryBlock.getArgument(i),
                                            operands[i]);
      }
    }
```

But I don't understand what's wrong with it. My guess is that the conversion framework isn't backtracking the block argument replacement properly

**Comment by River707** [comment]
Yes, replaceUsesOfBlockArgument is 100% broken. I wasn't on the review when it went in and it doesn't do any kind of back tracking.

**Comment by River707** [comment]
No longer segfaults after: https://reviews.llvm.org/D78790
