### ISSUE TITLE
The result in keras_vision_model_MobileNet_test is too small to compare

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1668]
In #1651 we found that the result of the test is too small numerically. All of the numbers are less than 1e-10, so the comparison between backends is not reasonable because we set the error range to 1e-6.

After #1667 being landed, we can also compile and run the model on VMLA. It's good to fix the comparison issue. Otherwise we are just testing if the model is able to run on backends.

Note: I tried to make the input range within [0, 255] but seems not working.

**Comment by hanhanW** [comment]
I can't make @rybakov to assignees for now, so mention it here.

**Comment by rybakov** [comment]
Thank you HanHan, I am working on it.
