### ISSUE TITLE
Support xla_hlo.gather operation on structured ops path to SPIR-V

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#1694]
To express `xla_hlo.gather` faithfully in Linalg, Linalg indexing maps would need to support indirections. In the absence of those, some support could be added by making use of the fact that regions of a `linalg.generic` operation can capture implicitly. 

So the following gather operation 

```
%r = xla.gather(%arg0, %arg1) : (tensor<6x20xf32>, tensor<2xi64>) -> tensor<2x20xf32>
```

can be lowered to

```
#map0 = affine_map<(d0, d1)[s0] -> (s0, d1)>
%3 = linalg.indexed_generic
       {args_in = 0, args_out = 1, 
        indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>]
        iterator_types = [“parallel”, “parallel”]} (%gy, %gx) {
     ^bb0(%arg3 : index, %arg4 : index, %arg5 : f32) {
       %0 = load %arg1[%arg3]
       %1 = affine_apply #map0(%arg3, %arg4, %0)
       %2 = load %arg0[%1#0, %1#1]
       linalg.yield %2;
     } : (tensor<6x20xf32>, tensor<2xi64>) -> tensor<2x20xf32>
```

This lowering means you cannot fuse gathers with its inputs. That might still be OK for a lot of use cases.

**Comment by hanhanW** [comment]
I'll hold this issue off until we see this op shows up in our target models.

**Comment by MaheshRavishankar** [comment]
Closing
