### ISSUE TITLE
Support xla_hlo.concat on Structured Ops Path to SPIR-V

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#1695]
The legacy SPIR-V path supported xla_hlo.concat lowering when it appeared in dispatch functions. This might be an operation though which is handled in the flow dialect itself. Instead of having a concat in dispatch region, the generated kernel just writes the final result at offsets within a buffer to do the concatenation (in-place). There might be use case to handle this in the dispatch region itself, i.e it could handle the same way. The operands of the concat are written into the buffer directly at different offsets. Filing a bug to track the regression of support for this op on Vulkan path for now.

**Comment by benvanik** [comment]
Agreed that flow should mostly handle this, though there will be cases when we cannot easily do so (such as when the indices are dynamic and have a dependency on the calculated values, or the exact set of output buffers is from mixed sources or have different lifetimes e.g. one model state variable and one in a user-provided buffer), in which case having the output indexing done in the kernel would likely be much better than the host round-trip or double allocation. There's also the case of non-outer-dim concats that effectively become scatters - those would be nice to eliminate via other means at the HLO/TCP level, but there will likely be cases where we need to do it anyway.
