### ISSUE TITLE
Support xla_hlo.floor operation on Structured Ops Path to SPIR-V

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#1696]
There doesnt seem to be a equivalent operation to use in Standard Dialect.

**Comment by MaheshRavishankar** [comment]
@hanhanW  is this done?

**Comment by hanhanW** [comment]
No, this is not done. It can be easily supported because there is a lowering from LMHLO to Linalg. I guess it just needs an one-line change (and a test). I'll send out the change.

**Comment by hanhanW** [comment]
Just found that it's supported in XLA recently, we just need to enable the test!
