### ISSUE TITLE
The behavior of load_16.mlir.test is weird

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1705]
Just file an issue for record, not sure if we're going to fix it.

I don't know how to say it, it's really weird. It's passing with bazel command, but it's failing with command line using `iree-run-mlir` manually. The behavior between VMLA and vulkan-spirv is also different. It crashes(?) in VMLA, and output "packed" result in vulkan-spirv.

## VMLA
command: `iree-run-mlir -iree-hal-target-backends=vmla -input-value="17xi8= 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17" iree/test/e2e/regression/load_i16.mlir`

output log:
```
EXEC @load_i16
E0427 19:22:18.558398   74944 api_util.h:30] OUT_OF_RANGE: Attempted to access an address outside of the valid buffer range (offset=0, length=34, end=33, buffer byte_length=17); while executing vmla.buffer.view
E0427 19:22:18.562291   74944 inproc_command_buffer.cc:244] DeviceQueue failure while executing command; permanently failing all future commands: OUT_OF_RANGE:
17xi32=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

## vulkan-spirv
command: `iree-run-mlir -iree-hal-target-backends=vmla -input-value="17xi8= 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17" iree/test/e2e/regression/load_i16.mlir`

output log:
```
EXEC @load_i16
17xi32=513 1027 1541 2055 2569 3083 3597 4111 17 0 0 0 0 0 0 0 0
```

The expected output is "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17", but something like `0x0201 0x0403 ...` is printed.

**Comment by benvanik** [comment]
In both those it looks like it's printing xi32, meaning that the printer thinks it's 32-bit integers, but then it's showing the hex values (0x0201, ...) for 16-bit integers

It's possible there's a bad type detection somewhere (in printer, in parser, in signature mangling, etc).

**Comment by GMNGeoffrey** [comment]
FYI this test is now deleted, but probably there's still a bug here. This is the snippet in question, right:

```mlir
// RUN: iree-run-mlir -iree-hal-target-backends=vmla %s -input-value="17xi16= 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17" | IreeFileCheck %s
// RUN: [[ $IREE_LLVMJIT_DISABLE == 1 ]] || (iree-run-mlir -iree-hal-target-backends=llvm-ir %s -input-value="17xi16= 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17" | IreeFileCheck %s)
// RUN: [[ $IREE_VULKAN_DISABLE == 1 ]] || (iree-run-mlir -iree-hal-target-backends=vulkan-spirv %s -input-value="17xi16= 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17" | IreeFileCheck %s)

// CHECK-LABEL: EXEC @load_i16
func @load_i16(%arg : tensor<17xi16>) -> tensor<17xi32> {
  %0 = "xla_hlo.convert"(%arg) : (tensor<17xi16>) -> tensor<17xi32>
  return %0 : tensor<17xi32>
}
// CHECK: 17xi32=1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
```

**Comment by antiagainst** [comment]
It seems there are no more actions we can take on this. So closing.
