### ISSUE TITLE
Remove device layer extension support

### ISSUE THREAD

**Issue by benvanik** [google/iree#1738]
Vulkan 1.1 deprecated device layers in favor of always using instance layers:
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#extendingvulkan-layers-devicelayerdeprecation

This would let us simplify the vulkan_driver/vulkan_device setup by removing the entire ExtensibilitySpec for devices. We may also be able to clean up some of our API goo for device adoption now that we don't need to know that information.

**Comment by ScottTodd** [comment]
> This would let us simplify the vulkan_driver/vulkan_device setup by removing the entire ExtensibilitySpec for devices.

We still have device **extensions** though:
https://github.com/google/iree/blob/fec60cff4fa130aa601b1855262fd294d537a4b5/iree/hal/vulkan/vulkan_driver_module.cc#L70-L72
https://github.com/google/iree/blob/fec60cff4fa130aa601b1855262fd294d537a4b5/iree/hal/vulkan/vulkan_driver_module.cc#L88-L91

I like being able to reuse `ExtensibilitySpec` for both, even if devices don't support layers.

---

> We may also be able to clean up some of our API goo for device adoption now that we don't need to know that information.

Our Vulkan HAL API doesn't support device layers:

https://github.com/google/iree/blob/fec60cff4fa130aa601b1855262fd294d537a4b5/iree/hal/vulkan/api.h#L141-L145

https://github.com/google/iree/blob/fec60cff4fa130aa601b1855262fd294d537a4b5/iree/hal/vulkan/api.cc#L177-L180

**Comment by benvanik** [comment]
Ahh good points! Well then, keep it all!

**Comment by ScottTodd** [comment]
That all being said, we could carry through the deprecation to the C++ VulkanDevice code:

https://github.com/google/iree/blob/fec60cff4fa130aa601b1855262fd294d537a4b5/iree/hal/vulkan/extensibility_util.h#L53-L57

https://github.com/google/iree/blob/fec60cff4fa130aa601b1855262fd294d537a4b5/iree/hal/vulkan/vulkan_device.cc#L211-L215
