### ISSUE TITLE
Bazel 1.2.1 issue: Fail to find header "src/FixedPoint/FixedPointTypes.h"

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#174]
This happens when building @org_tensorflow//tensorflow/core:framework_internal

This appears to be some kind of bazel bug because the glob in third_party/tensorflow/third_party/eigen3/BUILD EIGEN3_THIRD_PARTY_HEADERS is not being expanded (verified with --sandbox_debug and the src/** files are not present). I wasn't able to tickle the glob to actually work.

Adding the following to the EIGEN3_THIRD_PARTY_HEADERS list in that build file temporarily works around the problem:

    "unsupported/Eigen/CXX11/src/FixedPoint/FixedPointTypes.h",
    "unsupported/Eigen/CXX11/src/FixedPoint/MatMatProduct.h",
    "unsupported/Eigen/CXX11/src/FixedPoint/MatVecProduct.h",

**Comment by ScottTodd** [comment]
That's the error that prompted me to install a "TensorFlow supported" version on Bazel on my machines and the CI (or use Bazelisk to do that automatically). Maybe there's an issue already filed against Bazel or TensorFlow?

**Comment by stellaraccident** [comment]
I didn't immediately see one, and it does appear to be a bazel bug. Filed it here just to get it logged for now.

**Comment by stellaraccident** [comment]
With that workaround, the tree builds with 1.2.1, so it is something funny about that one particular glob.

**Comment by GMNGeoffrey** [comment]
I also ran into this. Installing bazel 1.1 fixed the issue for me
