### ISSUE TITLE
[HLO2Linalg] dot_general op lowering

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1758]
Maybe we can reuse this pattern: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/xla/transforms/lower_general_dot.cc

**Comment by hanhanW** [comment]
I'll prioritize other ops in ASR model, and revisit this operation later. The idea in my mind is doing reshape, transpose and lowering it to batch_matmul or batch_dot in Linalg. Here's a reference regarding reshape/transpose stuff:
https://github.com/google/iree/blob/2d1de7ead9c785b02d0aaa24bad51735653750ee/iree/compiler/Dialect/VMLA/Transforms/PreConversionLowering.cpp#L83-L244

**Comment by stellaraccident** [comment]
Sounds good. Make sure you coordinate approach with @silvasean. He has substantial state on this.

**Comment by silvasean** [comment]
Copying what I did in the VMLA lowering should work fine. The reshapes and transposes should get fused away by linalg.

You may also consider converting this directly to linalg. That might be much simpler and easier to test. Each contracting dimension becomes a linalg "reduction" dimension.

**Comment by MaheshRavishankar** [comment]
Closing since dot_general is now lowered to Linalg.
