### ISSUE TITLE
CMake build fails without Vulkan.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#1778]
The cmake build as described in the [getting started doc](https://github.com/google/iree/blob/master/docs/GetStarted/getting_started_linux_cmake.md) fails to build without having Vulkan installed:

```shell
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) 
CMake Error at build_tools/third_party/dear_imgui/CMakeLists.txt:60 (message):
  Vulkan library was not found


-- Configuring incomplete, errors occurred!
See also "/usr/src/git/iree/build/CMakeFiles/CMakeOutput.log".
See also "/usr/src/git/iree/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
```

This error is thrown in [`build_tools/third_party/dear_imgui/CMakeLists.txt`](https://github.com/google/iree/blob/ea1ff8574682be336ad4bc7f0d1bcf91240fe3d4/build_tools/third_party/dear_imgui/CMakeLists.txt#L56-L61) and in [`iree/samples/vulkan/CMakeLists.txt`](https://github.com/google/iree/blob/18ef4a6f72cceea65d50ff4ad921c09b1a5b9204/iree/samples/vulkan/CMakeLists.txt#L27-L34).

**Comment by ScottTodd** [comment]
For most targets, FindVulkan is not necessary. It should just be needed for the Vulkan GUI sample (and Dear ImGUI, which is only used by that sample). Here's how this is handled on the Bazel side:

Empty rule is created for `@vulkan_sdk//:sdk`:

https://github.com/google/iree/blob/f5c64fabdab88bf96aa4dfe7100a628304327ebe/build_tools/third_party/vulkan_sdk/repo.bzl#L15-L21

Target is marked `manual` so wildcard builds won't attempt to build:

https://github.com/google/iree/blob/f5c64fabdab88bf96aa4dfe7100a628304327ebe/iree/samples/vulkan/BUILD#L34-L47

As a simple fix, we can omit those targets in CMake if the FindVulkan check fails.

**Comment by ScottTodd** [comment]
Removed `spirv_tools` in https://github.com/google/iree/pull/1792. I'm curious to see if the core parts of IREE (as described in the getting started docs) build with just python2.

If it's easy enough for you to iterate on builds, could you try removing `${IREE_BUILD_COMPILER}` from https://github.com/google/iree/blob/d0d81a26221e3c56e2b999f98238f60db7f85b73/CMakeLists.txt#L107-L116

to confirm if there's some other dependency in there?

Here's some of LLVM's use: https://github.com/llvm/llvm-project/search?q=pythoninterp&unscoped_q=pythoninterp

(Installing python3 is good, but keeping the docs simple is better, if possible :D)

**Comment by phoenix-meadowlark** [comment]
I'll look into it after I confirm that I have a working CMake build after #1794!

**Comment by phoenix-meadowlark** [comment]
> Removed `spirv_tools` in #1792. I'm curious to see if the core parts of IREE (as described in the getting started docs) build with just python2.
> 
> If it's easy enough for you to iterate on builds, could you try removing `${IREE_BUILD_COMPILER}` from
> 
> https://github.com/google/iree/blob/d0d81a26221e3c56e2b999f98238f60db7f85b73/CMakeLists.txt#L107-L116
> 
> to confirm if there's some other dependency in there?
> 
> Here's some of LLVM's use: https://github.com/llvm/llvm-project/search?q=pythoninterp&unscoped_q=pythoninterp
> 
> (Installing python3 is good, but keeping the docs simple is better, if possible :D)

Removing `${IREE_BUILD_COMPILER}` allows the getting started build to successfully complete without python3.

**Comment by ScottTodd** [comment]
Oh, this comment thread should have been on https://github.com/google/iree/issues/1779 >_>
