### ISSUE TITLE
Consistent argument capture in FileCheck tests

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#1795]
In our lit FileCheck tests we've got a mix of styles for capturing function arguments. For SSA values, we pretty consistently use:

`// CHECK: %[[NAME:.+]] =`

which is short and easy to read. The `=` provides a clear barrier for FileCheck so the `.+` doesn't capture too much. For arguments, we've got a mix of styles:

1.
```mlir
// CHECK: func @my_fn
// CHECK-SAME: %[[ARG0:[a-zA-Z0-9$._-]+]]
// CHECK-SAME: %[[ARG1:[a-zA-Z0-9$._-]+]]
func @my_fn(%arg0: i32, %arg1: i32) -> (i32) {
```

2.
```mlir
// CHECK-LABEL: @gather_fully_specified_indices
// CHECK-SAME: %[[SRC:.+]]: !vmla.buffer,
// CHECK-SAME: %[[INDICES:.+]]: !vmla.buffer)
func @gather_fully_specified_indices(%input : tensor<5x2x3xf32>, %start_indices : tensor<3xi64>) -> tensor<2x3xf32> attributes { sym_visibility = "private" } {
```

3.
```mlir
// CHECK-LABEL: @rankBroadcastAdd
// CHECK-SAME: %[[LHS:[^:[:space:]]+]]: tensor<?x16xf32>
// CHECK-SAME: %[[RHS:[^:[:space:]]+]]: tensor<16xf32>
func @rankBroadcastAdd(%arg0 : tensor<?x16xf32>, %arg1 : tensor<16xf32>) -> (tensor<?x16xf32>) {
```

4.
```mlir
// CHECK-LABEL: @tensorUpdate
// CHECK-SAME: (%[[UBUF:.+]]:{{.+}}, %[[TBUF:.+]]:{{.+}})
func @tensorUpdate(%arg0 : tensor<1x1x10xf32>, %arg1 : tensor<5x1x10xf32>) -> tensor<5x1x10xf32> {
```

5.
```mlir
// CHECK-LABEL: @slice_stride_part
func @slice_stride_part(%arg0 : tensor<3x4xi32>) -> tensor<1x2xi32> attributes { sym_visibility = "private" } {
  // CHECK-SAME: %[[SRC:.+]]:
```

Let's come up with a clear and consistent way to represent this and try to use that style throughout

**Comment by benvanik** [comment]
I think the colon should be enough in argument cases (matching the = in op cases). That's what I've always used and haven't had any issues. The others all seem more complex with no benefit.

There is an annoying printer behavior in core where arguments won't get spaces between the argument name and the colon (so `%arg0: tensor` instead of `%arg0 : tensor` to be consistent with everything else). That'd be a nice cleanup to file upstream, and then the matchers really do become the same (`%[[VALUE:.+]] =` and `%[[ARG:.+]] :`).

**Comment by GMNGeoffrey** [comment]
Yeah I agree that looks the best. I only see a few examples of that, so I suspect you haven't always used just a colon :-P. Now added an example to the initial post. I suspect that only works if you have one argument though and the only examples we have have only one argument. Otherwise it will capture everything until the last colon. To prevent it capturing multiple args, you need to capture the type and comma delimiter as in style `2`. That doesn't seem like the worst thing. If you don't care about the type you could regex it as well


```mlir
// CHECK-LABEL: @gather_fully_specified_indices
// CHECK-SAME: %[[SRC:.+]]: {{.+}},
// CHECK-SAME: %[[INDICES:.+]]: {{.+}})
func @gather_fully_specified_indices(%input : tensor<5x2x3xf32>, %start_indices : tensor<3xi64>) {
```

That paren mismatch is going to drive me batty though, which actually brings up another point I've been thinking about. I think `CHECK-LABEL` on just `@function_name` is not generally safe because it will also match `@function_name_with_suffix` and labels are supposed to be unique in the file. I've been meaning to bring that up with the MLIR folks. I think we should also capture the parens. So to solve both of those problems:

```mlir
// CHECK-LABEL: @gather_fully_specified_indices(
// CHECK-SAME: %[[SRC:.+]]: {{.+}},
// CHECK-SAME: %[[INDICES:.+]]: {{.+}})
func @gather_fully_specified_indices(%input : tensor<5x2x3xf32>, %start_indices : tensor<3xi64>) {
```

**Comment by benvanik** [comment]
That seems pretty nice - it at least reads as if it's syntactically correct (`name(arg, arg)`) which makes it easier to mentally pattern match.

**Comment by GMNGeoffrey** [comment]
Hmmm it might break down for three types though. The `.+` will capture up to the second comma.

**Comment by GMNGeoffrey** [comment]
Yeah even with types it will break down if you have two arguments of the same type. I think the only ways that are actually always safe are 1, 3, and 4.

**Comment by GMNGeoffrey** [comment]
I don't think the character set is really that unclear and would vote for just always using that. It's the most robust, isn't dependent on spacing (and won't break if we fix the MLIR printer to put a space after args: `%arg0 : type`) and it's explicit and doesn't involve too much regex trickery. It's ugly, but it's just a list of characters that match the ones specified in the MLIR spec so :shrug:

I like the ability to match args on separate lines too, since then you don't have to add extra regexes when you don't care about types.

It might also be worth raising with the MLIR folks, since they're dealing with exactly the same issue. This best practice and that of not capturing sigils could even be added to https://mlir.llvm.org/getting_started/TestingGuide.

**Comment by benvanik** [comment]
Maybe I wasn't hitting issues because I was capturing %, and then y'all went and changed that ;)

I don't think I can be convinced to write out/copypasta a-zA-Zaoisdjfioasdjfaoisdjf for dozens to hundreds of captures. It turns the absolutely disgusting lit capture syntax into something so revolting with no material benefit I'd rather not use captures at all. Consistency for corner cases is not worth the universal pain.

**Comment by GMNGeoffrey** [comment]
Whether or not you capture the `%` should make no difference. It's adjacent to the regex regardless (I didn't have to change any `.+` when I changed the captures). I suspect we just have a lot of one and two argument functions.

**Comment by GMNGeoffrey** [comment]
The other option, of course is to just depend on the names of arguments. Unlike SSA values, they have a fixed ordering that's a part of the contract. Probably mlir isn't going to decide to 1-index it's arguments or something.

The problems with that are:
1. Can't give the variables names. This is a feature I really appreciate when trying to actually read wtf mlir blocks and lit tests do.
2. Block arguments use the same numbering scheme, so if you add an argument to a function you then need to "reflow" all the arguments to block arguments.

Having just had to deal with our brittle tests dramatically slowing down fixing a bug, I'd prefer not to make them more brittle on that front. Maybe we can give a custom naming scheme to the block args for our ops (e.g. stream fragment).

> Consistency for corner cases is not worth the universal pain.

I'm fine with this if you're fine with some people preferring to write out the regex rather than figuring out the correct delimiters to make it work. If the main pain your worried about is that of the writer, rather than the reader, then we should just let everyone write whichever way they prefer. I would make this the general guidance then:

> When capturing identifiers, you can capture them as `%[[FOO:.+]]`. This will not always work, however because the regex may capture too much (especially in the case of arguments). You can either use additional details of the non-regex match to disambiguate or capture the identifier as `%[[FOO:[a-zA-Z0-9$._-]+]]`, the character set for [MLIR identifiers](https://mlir.llvm.org/docs/LangRef/#identifiers-and-keywords).

**Comment by benvanik** [comment]
If someone wants to take on the role of gardening all our tests then feel free to reopen, otherwise 🤷.
