### ISSUE TITLE
Error 'error: Server does not allow request for unadvertised object b4ee523ffc962e25ef96f3bb67847521624d607a' on update of submodules

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#18]
When updating the abseil or llvm submodules, I am often getting this error:
error: Server does not allow request for unadvertised object b4ee523ffc962e25ef96f3bb67847521624d607a

(or similar)

I think this has to do with the shallow submodule fetch.

I was able to make progress by running:
  git submodule update --depth 1000

**Comment by denis0x0D** [comment]
I've faced the same error, my workaround was to delete a `shallow` from .gitmodules
