### ISSUE TITLE
Support multiple iree-translate outputs (or have an easily partitioned single file)

### ISSUE THREAD

**Issue by benvanik** [google/iree#1808]
For near-term AOT work we can rely on shm_open/memfd_create/etc to dlopen directly from memory with the cost of a memcopy. We don't want to do that for deployment, though, so we'll want to have all generated code in a sidecar to the VM module file.

We could try first to output multiple files from iree-translate (with stdout having the combined files), so by default a user gets a single VM module file with embedded elf/pe/etc and then if they want separate files they can pass an additional flag.

Alternatively, we could have a binutils-like tool that lets us slice out the executables, which may be interesting for other uses as well (such as splitting all compiled shaders from the VM code to be able to manage page residency independently).

**Comment by GMNGeoffrey** [comment]
I think something this is maybe needed/useful for being able to have the check-test framework compile each test case into a separate module to avoid repeatedly loading the big module into a new context for each test.

**Comment by benvanik** [comment]
iree-translate should be gutted and turned into vm dialect -> bytecode | emitc only. iree-compile in #3817 will replace the need for this.
