### ISSUE TITLE
Setup install target for the IREE compiler and other host artifacts

### ISSUE THREAD

**Issue by benvanik** [google/iree#1820]
We should be able to produce an install of the IREE compiler that can be used to build modules for our supported targets. Specifically this means tools like iree-opt, iree-translate, iree-tblgen, and iree-run-mlir. We shouldn't need any include files/static libraries as we don't yet have a compiler API (we'll leave that to python bindings/etc to deal with).

* [ ] `find_dependency` works to allow the runtime to be built without building the compiler (tf/llvm submodules should not be required)
* [ ] ensure that the installed compiler tools like iree-opt can execute standalone (without *also* requiring an LLVM/MLIR install)
* [ ] #357: ensure the generated opcode files end up in the install package so `IREE_BUILD_COMPILER=0` does not require LLVM/the compiler portions.

Most of this will be removing global assumptions about things like include paths (currently we include tensorflow paths everywhere, for example), etc.

**Comment by ScottTodd** [comment]
This issue is stale - is there more still to do around how we build/install the host binaries?

**Comment by GMNGeoffrey** [comment]
I think this is fixed. Please reopen if there's more to do
