### ISSUE TITLE
clamp.mlir test fails on vulkan

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1851]
Even we get non-i32 bitwidth emulation support, the clamp.mlir still fails. This is the issue for tracking it.

Expected equality of these values. Contents does not match.
  lhs:
    4xi8=10 4 8 10
  rhs:
    4xi8=0 4 8 10

Expected equality of these values. Contents does not match.
  lhs:
    4xi16=10 4 8 10
  rhs:
    4xi16=0 4 8 10

**Comment by hanhanW** [comment]
My guess is that we don't handle negative number well. clamp(0, -2, 10) -> 10, the negative number might be a huge positive number. I will take a look at it.

**Comment by antiagainst** [comment]
Interesting! Part is correct; part is wrong. This is a similar pattern I've seen for multiple dispatches. Are you testing this on SwiftShader? Could you do a quick check against real GPU?

**Comment by hanhanW** [comment]
I was testing with `bazel test`, so it's on SwiftShader by default I think. I haven't set up the environment for vulkan yet, so I can't do it in a quick way...

**Comment by antiagainst** [comment]
Oh never mind then. I've that set up; let me check later. :)

**Comment by antiagainst** [comment]
Tested: this also fails on real GPU. So there is a bug in our pipeline.
