### ISSUE TITLE
Cannot lower tie_shape outside of stream fragment

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#1894]
A `shapex.tie_shape` op outside of a stream fragment fails to lower. It gets passed a buffer and then verification fails

```mlir
// RUN: iree-opt -split-input-file -iree-convert-flow-to-hal %s | IreeFileCheck %s

func @tie_shape(%t : tensor<?xi32>, %dim : index) -> tensor<?xi32> {
  %shape = shapex.make_ranked_shape %dim : (index) -> !shapex.ranked_shape<[?]>
  %tie = shapex.tie_shape %t, %shape : tensor<?xi32>, !shapex.ranked_shape<[?]>
  return %tie : tensor<?xi32>
}
```

```mlir
// *** IR Dump After mlir::iree_compiler::(anonymous namespace)::ConvertFlowToHALPass ***
module {
  func @tie_shape(%arg0: !hal.buffer, %arg1: index) -> !hal.buffer {
    %0 = shapex.make_ranked_shape %arg1 : (index) -> !shapex.ranked_shape<[?]>
    %1 = shapex.tie_shape %arg0, %0 : !hal.buffer, !shapex.ranked_shape<[?]>
    return %1 : tensor<?xi32>
  }
}
```

```
error: 'shapex.tie_shape' op failed to verify that all of {operand, result} have same type
```

I think this is a bug, but want to confirm that we should be able to handle tie_shape outside of streams. tie_shape ops should just be dropped during this part of conversion, correct?

**Comment by GMNGeoffrey** [comment]
@benvanik, @laurenzo, or @silvasean can you confirm the intended behavior here? I think the tie_shape should just change its return type and pass through and then later we should drop it. I tried dropping it right away, but some patterns during this conversion look for a tie shape to determine some argument's shape so we have to leave it around until the conversion is done.

**Comment by silvasean** [comment]
Can't comment on this specific issues, but that func looks like it has a verifier error: `return %1 : tensor<?xi32>` but the function return type is `!hal.buffer`, so it seems like something has gone wrong already.

Note that if the `return` op is fixed to return !hal.buffer to be consistent with the function, then this specific tie_shape verifier error goes away.

**Comment by GMNGeoffrey** [comment]
Yeah that's basically the same error. If the correct behavior is to have
the tie_shape apply to a buffer then it would return a buffer and go
through to make the return value a buffer as well
