### ISSUE TITLE
failed to legalize operation 'std.tanh' on llvm-ir backend

### ISSUE THREAD

**Issue by hanhanW** [google/iree#1913]
@asaadaldien I added a test for xla_hlo.tanh op and found that this op is not supported on llvm-ir. I tried to add a lowering in MLIR conversion but I couldn't find llvm.tanh. Thus, I'll leave this issue to you. PTAL.

Snippet of the test:
```mlir
func @tanh() attributes { iree.module.export } {
  %input = iree.unfoldable_constant dense<
      [[-100.0, -5.0, -0.5,   1.0],
       [   1.2,  2.0,  3.0, 100.0]]> : tensor<2x4xf32>
  %result = "xla_hlo.tanh"(%input) : (tensor<2x4xf32>) -> tensor<2x4xf32>
  check.expect_almost_eq_const(%result, dense<
      [[-1.0000000, -0.99990916, -0.46211717, 0.7615942],
       [ 0.8336547,  0.96402760,  0.99505470, 1.0000000]]> : tensor<2x4xf32>) : tensor<2x4xf32>
  return
}
```

**Comment by asaadaldien** [comment]
We need to add an llvm intrinsics to enable lowering this op, it currently marked illegal  or a short term solution xla_hlo rewrite as we lower from xla_hlo to linalg `tanh(x) = (exp(2*x) - 1) / (exp(2*x) + 1)`
