### ISSUE TITLE
Upstream a TRACY_NO_FRAME_IMAGE flag for Tracy

### ISSUE THREAD

**Issue by benvanik** [google/iree#1926]
Currently Tracy assumes that users will be posting screenshots of frames via the `tracy::Profiler::SendFrameImage` API. Because of this Tracy starts an additional thread and includes code for performing on-the-fly DXT1 texture compression. Since we never need this it'd be nice to be able to toggle all of that off to reduce the code size impact and extra runtime threads.

**Comment by wolfpld** [comment]
This has been added in https://github.com/wolfpld/tracy/commit/a001683a771f6e730bd7f243d44de99113f77815.

**Comment by benvanik** [comment]
Whoa, cool! Thanks @wolfpld!
