### ISSUE TITLE
iree/compiler/Dialect/Interpreter/CMakeLists.txt adds non existing directories

### ISSUE THREAD

**Issue by marbre** [google/iree#194]
The CMakeLists.txt file was added with commit 3e32ecc350e83a5f8251f44b5857e68bcd9c159f, but the directories do not exist. Maybe it was missed to move files during cleanup or to add some new ones?

**Comment by ScottTodd** [comment]
Yep... that directory is empty right now. It looks like @benvanik has another change pending (not visible on GitHub yet) that moves some files there, but the CMakeLists.txt file slipped into a different commit early :)

We can delete that file for now and add it back when he gets to merging the full change.

**Comment by marbre** [comment]
No need to delete it, just wanted to prevent myself to create a useless pull request ;-)
