### ISSUE TITLE
Implement HAL record/replay for isolated benchmarking

### ISSUE THREAD

**Issue by benvanik** [google/iree#1954]
A HAL shim layer that records submissions and dumps them to a flatbuffer and a replay tool should be pretty easy to throw together. This will let us easily capture entire sequences of model execution and play them back in isolation against any HAL implementation. iree-run-* can have flags for inserting the capture shim and an iree-replay tool could load them for playback.

**Comment by benvanik** [comment]
This may overlap with the idea of precompiled command buffers that's been kicking around in my head for awhile: embedding serialized command buffers in vm.rodata blobs such that at runtime there's no need to construct them at all. Same thing that has existed for ages in the console world and exist in API's like D3D12 (bundles).

**Comment by benvanik** [comment]
[iree_hal_deferred_command_buffer_t](https://github.com/google/iree/blob/44bf1007262e90aa5bfbeb0ee7b513a7ce1f7e0f/iree/hal/utils/deferred_command_buffer.h) is a good model for this. Being able to record/replay is just serializing and deserializing instead of storing in memory.

**Comment by ScottTodd** [comment]
Do the `iree-run-trace` and `iree-benchmark-trace` tools satisfy this issue, or are those higher level than the HAL record/replay that was planned?

**Comment by benvanik** [comment]
yeah those are higher level (program level record/replay) - these would be for HAL command buffers in particular in order to implement GPU-style tools (gapid/renderdoc/etc) and inspect execution. As in https://github.com/google/iree/issues/1954#issuecomment-731672047 though this may just be a core feature we support (serialized command buffers) and then all that's needed is a way to save and load them.

It's probably fine to close this for now until we are ready to work on this so that we can re-evaluate the approach then.
