### ISSUE TITLE
System python3 broken for apt-add-repository in the `rbe-ubuntu16.04` image.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#1966]
apt-add-repository requires a version of python with the `softwareproperties` module. In the `rbe-ubuntu16-04` image the system `python3` is modified and does not have this. So, to use this command we:

1. remove the symlink from `python3` to `python3.6` and symlink it to `python3.5`
2. run `apt-add-repository` with `python3 = python3.5`
3. resymlink `python3` to `/opt/python3.6/bin/python3.6`

Other options would be to install the PPA manually, or to make apt-add-repository use `python3.5` instead of system `python3`. Both of these run into issues however. When manually adding the repository, the following error occurs:

```dockerfile
RUN echo "deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu xenial main" >> /etc/apt/source.list
RUN echo "deb-src http://ppa.launchpad.net/deadsnakes/ppa/ubuntu xenial main" >> /etc/apt/source.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F23C5A6CF475977595C89F51BA6932366A755776
RUN apt-get update
RUN apt-get install -y python3.6 python3.6-dev
# Reading package lists...
# Building dependency tree...
# Reading state information...
# E: Unable to locate package python3.6
# E: Couldn't find any package by glob 'python3.6'
# E: Couldn't find any package by regex 'python3.6'
# E: Unable to locate package python3.6-dev
# E: Couldn't find any package by glob 'python3.6-dev'
# E: Couldn't find any package by regex 'python3.6-dev'
# The command '/bin/sh -c apt-get install -y python3.6 python3.6-dev' returned a non-zero code: 100
```

Editing `apt-add-repository` to use `!# /usr/bin/python3.5` via `sed -i 's/python3/python3.5/g' /usr/bin/apt-add-repository` also doesn't have any affect.

**Comment by benvanik** [comment]
Obsolete?

**Comment by phoenix-meadowlark** [comment]
> Obsolete?

Not really. But it's not something that anyone plans to "fix" either? We don't really control that the RBE toolchain image is broken (with respect to python versioning and `apt-add-repository`).

@GMNGeoffrey wanted the issue for tracking, but I don't think it will ever _go_ anywhere, so maybe it would be better to just leave it as a comment in the file?

**Comment by benvanik** [comment]
Agreed - for forever bugs (especially those related to google owned/controlled infra) we should track those internally and not inflict them upon people trying to actually figure out what the state of our project is :)

**Comment by GMNGeoffrey** [comment]
I think I suggested filing an issue against RBE itself, but yeah fine with closing this if we don't have a plan to fix
