### ISSUE TITLE
Check Vulkan SDK version and fail CMake configuration if < some min version

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#1997]
As we're finding that older Vulkan SDK versions have limited support for timeline semaphores (https://github.com/google/iree/issues/1576 in the loader, and in validation layers), it will help to flag older versions during configuration. We can gate this check on if Vulkan support is enabled: https://github.com/google/iree/blob/e2aad2882908a00fb9feb2db054b3b70111476ad/CMakeLists.txt#L88-L93

After calling `FindVulkan()`, we can do something like this: https://github.com/KhronosGroup/Vulkan-ExtensionLayer/blob/8a457f8552d8d47ce3a96ed80a714ff6396f8ad8/CMakeLists.txt#L145-L155 to extract the SDK version. Currently `FindVulkan()` is optional and non-blocking due to https://github.com/google/iree/issues/1778, but we could also fold it into the `IREE_TARGET_BACKEND_Vulkan_SPIRV` check.

cc @benvanik @antiagainst

**Comment by benvanik** [comment]
Obsolete?

**Comment by ScottTodd** [comment]
> Obsolete?

As stated, I believe so. We can create new issues for further Vulkan configuration problems.
