### ISSUE TITLE
Clean-up/dedup the tail of the TensorFlow import pipeline and the head of the Flow pipeline

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#2007]
While most of the TensorFlow pipeline is specific to TensorFlow, they are now comingled with respect to certain common HLO legalization steps:

- [TensorFlow HLO passes](https://github.com/google/iree/blob/4c7f33634ee6dffbdc7a91468f9ed7d2ee31b5ea/integrations/tensorflow/compiler/Passes.cpp#L34)
- [Flow HLO passes](https://github.com/google/iree/blob/4c7f33634ee6dffbdc7a91468f9ed7d2ee31b5ea/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L42)

There really wasn't a plan for either of these and independent progress has meant adding things to specific places versus generalizing. We should create an HLO pipeline that does all of this (and a few other things that are currently loose passes in the Flow side) and invoke it from the Flow pipeline. This will also help us at some point if we have an alternative path from HLO (i.e. via TCP or equiv).

In the meantime, the two are different with respect to the flow pipeline missing `pm.addPass(Shape::createConvertHLOToShapePass());`, which is required for standalone use of HLO with dynamic shapes. We can just add that on the flow side and then consolidate.

While in there, it would be nice to have a standalone pass at the bottom of the "Input dialect sanitization" section which verified some invariants that we expect to be valid for any IR that proceeds to the main parts of the compiler. That would help us catch issues early. Not having that has caused a couple of recent rabbit trails of debugging sessions.

**Comment by GMNGeoffrey** [comment]
On the topic of invariant checking, at some point I suggested that it would be nice to generalize ConversionTarget in MLIR to allow non-dialect-conversion passes to use it as a way of expression op/dialect composition invariants. I'm not sure if that ever materialized, but I think we could still use it in a somewhat hacky way by just running `applyFullConversion`with an empty list of patterns. I would love to see clearer invariants throughout our pipelines and I think a standard way to specify (at least this class of) them would help

**Comment by silvasean** [comment]
We should get consensus about the "boundary" of IREE. We are going to have awkwardness like this until we define that.

Currently, besides the TF frontend we also have an "HLO frontend" that is what we use in our tests. It's not super well-defined, and I think if we defined that better we would fix this issue pretty naturally.

It's quite natural that two frontends that happen to go through HLO will have duplication. It's just that right now the flow transformation pipeline is also a quasi frontend and so it looks awkward.

@benvanik about thoughts on disentangling an "HLO testing frontend"

**Comment by benvanik** [comment]
Linalg-on-tensors will make this much clearer, as we will stop accepting mhlo/etc into the flow dialect at all as something we snoop. That does not mean that a frontend couldn't squirrel away those ops in pre-built flow.dispatch.regions or linalg.generic ops, but that IREE's dialects won't be including any files related to the mhlo dialect or looking for specific ops within it. Duping to #1354.
