### ISSUE TITLE
Build copts may not need LLVM_ENABLE_RTTI 

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#202]
See #182 and #185 for context. Once the CMake build is more stable, we should be able to debug that particular option to see if it is really needed.

**Comment by stellaraccident** [comment]
I believe it is needed for the python bindings. I can see a path to it not being needed from my work on npcomp, but if it isn't hurting anyone right now, it will reduce churn to just leave it on for now.

**Comment by benvanik** [comment]
(if we want smaller builds we'll want it disabled, though #898)

**Comment by stellaraccident** [comment]
I believe we only presently need it for LLVM when we have Python bindings in the loop, and we have less size pressure on that side right now (or once AOT lands).

And to be clear, I've been able to triage and fix the vague linkage errors that cause this each time before, but it is basically walking through a pile of glass and is very likely to regress on each integrate. I'd like to write a little tool to diagnose the issue where vague, multiple linkage of vtables is coming into the build and then fix upstream versus hunting and pecking through.

**Comment by benvanik** [comment]
Oh, I misread the name as "IREE_ENABLE_RTTI" - yeah, LLVM side doesn't matter.

**Comment by benvanik** [comment]
Don't care about the compiler-side having it enabled (especially with llvmjit getting evicted).
