### ISSUE TITLE
Connect Amber with IREE for easier Vulkan bug report

### ISSUE THREAD

**Issue by antiagainst** [google/iree#2047]
Getting GPU bug repro for communicating with tool developers can take quite some effort. One way to make it easier is to support C++ CodeGen from IREE. Another way we can potentially look at is [Amber](https://github.com/google/amber). It is a graphics API testing framework aiming for simple shader bug report and repro. It is embedded in dEQP, which is Vulkan's testing suite. We could consider connect with Amber to automate the bug repo generation and also make the bug become part of the testing suite so we don't see regression. 

This is blocked on having AST/APIs in Amber so that we can convert the IR into Amber's scripts.

**Comment by antiagainst** [comment]
FYI: @dneto0 @dj2

**Comment by benvanik** [comment]
Still something you are interested in or obsolete?

**Comment by antiagainst** [comment]
I think we won't gotten to this in near term. So closing for now.

**Comment by antiagainst** [comment]
Really closing this. ;-P
