### ISSUE TITLE
Illegal buffer aliasing in HLOToLinalgOnBuffers

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#2073]
Consider the following:

```
func @predict_ex_dispatch_4() {
  %c0 = constant 0 : index
  %cst = constant dense<5.000000e-01> : tensor<f32>
  %0 = hal.interface.load.constant offset = 0 : index
  %1 = shapex.make_ranked_shape %0 : (index) -> !shapex.ranked_shape<[?,256]>
  %2 = linalg.generic {args_in = 1 : i64, args_out = 1 : i64, indexing_maps = [affine_map<(d0, d1) -> ()>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} %cst {
  ^bb0(%arg0: f32):  // no predecessors
    linalg.yield %arg0 : f32
  }: tensor<f32> -> tensor<?x256xf32>
  %3 = shapex.tie_shape %2, %1 : tensor<?x256xf32>, !shapex.ranked_shape<[?,256]>
  hal.interface.store.tensor %3, @legacy_io::@ret0, offset = %c0 : tensor<?x256xf32>
  hal.interface.store.tensor %3, @legacy_io::@ret1, offset = %c0 : tensor<?x256xf32>
  hal.interface.store.tensor %3, @legacy_io::@ret2, offset = %c0 : tensor<?x256xf32>
  return
}
```

This can currently arise when a dispatch region is formed like this:

```
    module {
      func @predict_ex_dispatch_4(%arg0: index) -> (tensor<?x256xf32>, tensor<?x256xf32>, tensor<?x256xf32>) {
        %0 = shapex.make_ranked_shape %arg0 : (index) -> !shapex.ranked_shape<[?,256]>
        %cst = constant dense<5.000000e-01> : tensor<f32>
        %1 = "shapex.ranked_broadcast_in_dim"(%cst, %0) {broadcast_dimensions = dense<[]> : tensor<0xi64>} : (tensor<f32>, !shapex.ranked_shape<[?,256]>) -> tensor<?x256xf32>
        return %1, %1, %1 : tensor<?x256xf32>, tensor<?x256xf32>, tensor<?x256xf32>
      }
    }
```

(this pattern came up when I was doing some work with all dispatch fusion disabled)

I think it is reasonable to say that we should not be generating such dispatch regions, but I wish there was some enforcement.

**Comment by stellaraccident** [comment]
Also, while I can fix the canonicalization to better avoid it, it is a hard property to enforce in the presence of all transformations.

**Comment by antiagainst** [comment]
I might be missing something but IIUC buffer aliasing means referencing the same underlying buffer with different symbols, but here we are actually duplicating the content into three different buffers as far as CodeGen is concerned. While being inefficient, it should be legal at least?

Regarding buffer aliasing in general, I think the contract between the runtime and codegen is that buffers by default aren't aliasing, unless otherwise explicitly noted. Yes we can have two buffers sharing the same descriptor set and binding number but they start with different offsets. That's not strictly buffer aliasing IMO.

**Comment by antiagainst** [comment]
Oh I might miss the big picture here then given I'm only seeing this particular dispatch. From itself, it's hard to see whether we can dedup: there might be following up dispatches that actually uses them differently so the buffers later can be updated with different contents. Dedup needs a more whole-program level analysis and it's better to happen in earlier layers.

**Comment by stellaraccident** [comment]
Right, and that's why my fix was to dedup at the program level. Relatedly, though, it would be a nice to have if this generated legal code on the backends if it does happen. Not a priority right now.

**Comment by benvanik** [comment]
Pass is on its way out thanks to linalg-on-tensors.
