### ISSUE TITLE
Replace usage of direct invocation of native modules with generated wrappers

### ISSUE THREAD

**Issue by benvanik** [google/iree#2075]
iree_vm_invoke is not currently designed to directly invoke native functions. check_test does this, and it only happened to work because there was missing validation inside of the invocation logic. This validation is really useful so it'd be nice to rework check_test to not do this.

**Comment by GMNGeoffrey** [comment]
You're just talking about https://sourcegraph.com/github.com/google/iree/-/blob/iree/modules/check/check_test.cc#L174, not any issue in the check runner, right? It seems a little odd that we have to know whether something is a native function or not at that level. Isn't a native module just one way of implementing a VM module?
Looking at your commit, the validation in question that's breaking is a function that takes variadic arguments, right? Which we can write with a native module but not with a normal bytecode module. Although actually the check module functions don't take variadic arguments. I guess that the way native module function signatures are created has to assume they do though? I used to have another module wrapping the calls to the native module for the unit tests, but removed it in https://github.com/google/iree/commit/25e13625fb693e7d7eb7846022a8e4a5254c4560. Basically you're saying we need to put that back?

**Comment by benvanik** [comment]
Was fixed long ago with https://github.com/google/iree/commit/4c0a53e955c44480e2387a9d756a33f66830a394
