### ISSUE TITLE
CMake equiavlent to Bazel cc_embed_data

### ISSUE THREAD

**Issue by marbre** [google/iree#211]
At the moment `generate_cc_embed_data` is embedded into `add_custom_command`. A CMake equivalent to the Bazel function https://github.com/google/iree/blob/master/build_tools/embed_data/build_defs.bzl#L17-L89 is preferable.

**Comment by ScottTodd** [comment]
I have a working version of this almost ready for review. I wanted to send it out yesterday but got greedy and started on `iree_bytecode_module` (#212) as well :)

**Comment by marbre** [comment]
Good to hear :)
Primarily intended this issue for keeping track of the status. So far I only spent little time on implementing it, but will then wait for your work.
