### ISSUE TITLE
CMake equiavlent to Bazel iree_glsl_vulkan/spirv_kernel_cc_library

### ISSUE THREAD

**Issue by marbre** [google/iree#213]
`iree_glsl_vulkan` (defined [here](https://github.com/google/iree/blob/master/iree/build_defs.bzl#L111-L112)) is aliasing `glsl_vulkan` and finally calls `_glslang` (both defined [here](https://github.com/google/iree/blob/3e572044d1e2014189aa11fd7e7d9f419ab64857/build_tools/third_party/glslang/build_defs.bzl#L17-L42)). In the current CMake implementation, the `glslangValidator` command is embedded into `add_custom_command`. Within Bazel `iree_glsl_vulkan` is called by `spirv_kernel_cc_library` (see [here](https://github.com/google/iree/blob/3e572044d1e2014189aa11fd7e7d9f419ab64857/iree/compiler/Translation/SPIRV/Kernels/spirv_utils.bzl#L20-L46)) to generate the SPIR-V kernels. Instead of using directly defining `add_custom_command` every time, a CMake wrapper closer to Bazel is preferred.

The comment by @benvanik  in `iree/compiler/Translation/SPIRV/Kernels/CMakeLists.txt` mentions to implement this as `iree_glsl_cc_library` for CMake. This would mean we have a slightly different naming between CMake and Bazel. Either we can go close with the Bazel flow or we can handle this all in `iree_glsl_cc_library`. Any thought on this?

Because `generate_cc_embed_data` is called, this depends on #211.

**Comment by benvanik** [comment]
Matching the naming would be nice (I just forgot the name :).
My hope is that at some point soon I'll get some spare cycles to work on adapting something like https://github.com/google/bazel-to-cmake for our use; then we can autogenerate 95% of the cmakelists from the bazel files without needing to manually keep them updated (and also have a CI check that makes sure they are up to date so they can't drift). Having the names and attributes of the bazel rules and cmake rules be the same makes such a tool (well, fancy script) easier. We'll still need some mappings (like to absl/other third_party deps) but it'd be nice not to need mappings for ourselves :)

**Comment by marbre** [comment]
I already looking into `bazel-to-cmake`, where the main blocker (at least at the moment) is that `http_archive` and `load` are not implemented and these are used a lot in the IREE Bazel build.

Anyway, I can take a look into CMake equivalents for `iree_glsl_vulkan` and `spirv_kernel_cc_library` if nobody else is working on it.

**Comment by benvanik** [comment]
Cool! We can also do things incrementally or only where it makes sense; for example, only generating the files under iree/iree/... and leaving the rest (where http_archive and other things live) hand-written.

I don't think anyone is working on it, so feel free to party! @ScottTodd has mostly been dealing with the Vulkan things and has been super thankful for your help!

**Comment by ScottTodd** [comment]
Go for it :D I don't think I'll have time before end of year vacations to work on `iree_glsl_vulkan` / `spirv_kernel_cc_library`.

We don't need bazel to cmake to be fully automated across the entire project - a script that just attempts to migrate Bazel `cc_library` -> CMake `iree_cc_library` would be helpful enough on its own to keep the bulk of the builds up-to-date (though we can still aim for it to do more than that).

**Comment by marbre** [comment]
> Cool! We can also do things incrementally or only where it makes sense; for example, only generating the files under iree/iree/... and leaving the rest (where http_archive and other things live) hand-written.

At the moment `bazel-to-cmake` requires the `WORKSPACE` file, so you have to run it in the root directory of a project. Even worse, `WORKSPACE` is where all the `http_archive` and `load` stuff is defined, so the python script fails since function like `rules_cc` are not defined. However, I fully agree that it makes sense to just generate portions or just to migrate individual functions like @ScottTodd suggested.

**Comment by marbre** [comment]
> Go for it :D I don't think I'll have time before end of year vacations to work on `iree_glsl_vulkan` / `spirv_kernel_cc_library`.

Okay, will start by tomorrow :) If you like, you can also assign me to this. If you're work on #211 does not makes it into the master by tomorrow, please let me know on which branch I can find your work if it's public. Might cherry-pick some changes to test integration.

**Comment by ScottTodd** [comment]
My progress is at https://github.com/ScottTodd/iree/tree/cmake-functions . The first commit (https://github.com/ScottTodd/iree/commit/024ef5a22fe3bed29e32e5f3922b2b79c9f05d80) is pretty close to ready, while the second (https://github.com/ScottTodd/iree/commit/bb6194a9a4f04367d94bd5909c11013e699a0df6) isn't quite working yet.

**Comment by marbre** [comment]
I already got a basic `iree_glslang` working, which imitates Bazel's [_glslang](https://github.com/google/iree/blob/master/build_tools/third_party/glslang/build_defs.bzl#L17-L39). However, I am not really satisfied with replicating [glsl_vulkan](https://github.com/google/iree/blob/master/build_tools/third_party/glslang/build_defs.bzl#L41-L42) and [hlsl_vulkan](https://github.com/google/iree/blob/master/build_tools/third_party/glslang/build_defs.bzl#L44-L45). As mentioned in my initial comment,
[iree_glslang_vulkan](https://github.com/google/iree/blob/master/iree/build_defs.bzl#L111-L112) is aliasing `glsl_vulkan`.

Implementing the CMake function called `iree_spirv_kernel_cc_library` (instead of `iree_glsl_cc_library`) which imitates [spirv_kernel_cc_library](https://github.com/google/iree/blob/master/iree/compiler/Translation/SPIRV/Kernels/spirv_utils.bzl#L20-L46), I would like to ask if you see the need to fully replicate `glsl_vulkan`, `hlsl_vulkan` and `iree_glslang_vulkan`. Instead of passing arguments through all this functions, e.g.

```cmake
function(iree_glsl_vulkan)
  cmake_parse_arguments(
    _RULE
    "PUBLIC;TESTONLY"
    "NAME;SRC"
    ""
    ${ARGN}
  )

  iree_glslang(
    NAME
      ${_RULE_NAME}
    SRC
      ${_RULE_SRC}
    MODE
      "glsl"
    TARGET
      "vulkan"
  )
endfunction()
```

we can add a `TARGET` and a `MODE` keyword directly to `iree_spirv_kernel_cc_library`, allowing to directly call `iree_glslang` from `iree_spirv_kernel_cc_library`. This was partially proposed for `iree_glsl_cc_library` [here](https://github.com/google/iree/blob/master/iree/compiler/Translation/SPIRV/Kernels/CMakeLists.txt#L15-L25).

@benvanik @ScottTodd Looking forward for your suggestions :)

**Comment by ScottTodd** [comment]
Thanks for your work here! Nice to see the CMake build getting closer and closer to Bazel.
