### ISSUE TITLE
Remove IREE_COMMON_INCLUDE_DIRS and avoid large global compiler flags

### ISSUE THREAD

**Issue by benvanik** [google/iree#2195]
IREE_COMMON_INCLUDE_DIRS shouldn't exist; we have several independent compilation scopes within the project and there shouldn't be any common include dirs beyond the workspace directory.

A first pass would be to split this into IREE_COMPILER_INCLUDE_DIRS and IREE_RUNTIME_INCLUDE_DIRS to at least ensure we aren't including LLVM in runtime builds. For the one place we do need it (the HAL LLVMJIT driver) we can add the include directories there specifically, ensuring that the rest of the code builds without the need for a full LLVM checkout.

This will become more important as we start cross-compiling for more targets that have independent (but possibly overlapping in name) includes.

(see #2193 for an example of where large global flags creates issues with bundling)

**Comment by marbre** [comment]
This requires a change amongst other things in `iree_cc_binary` and `iree_cc_library`. In these functions, the includes to `IREE_COMMON_INCLUDE_DIRS` are set via `target_include_directories`.

For `iree_cc_library` one can already specifcy other/additional includes via the parameter `INCLUDES`. Thus one could enforce that includes need to be set for **every** library and one could skip adding `IREE_COMMON_INCLUDE_DIRS` within the CMake function by default. This is however not compatible with `bazel_to_cmake` and I am not sure how to handle it in a clean way. Another possibility is to add includes depending on the source file location, which should at least work for the proposed split into `IREE_COMPILER_INCLUDE_DIRS` and `IREE_RUNTIME_INCLUDE_DIRS`. However, I don't really like this idea either.

@GMNGeoffrey @ScottTodd Any comments or further suggestions?

**Comment by ScottTodd** [comment]
Some random thoughts for a general solution (`IREE_RUNTIME_INCLUDE_DIRS` / `IREE_COMPILER_INCLUDE_DIRS` seems like a good low-tech solution :D)

---

Could we infer what's in `IREE_COMMON_INCLUDE_DIRS` now from the existing explicit `DEPS`, in [`iree_cc_library`](https://github.com/google/iree/blob/main/build_tools/cmake/iree_cc_library.cmake)? Is that similar to your idea to "add includes depending on the source file location"?

Maybe we could generate new targets or patch the existing targets to add include information for `iree_cc_library` to pick up later?

---

As for [`bazel_to_cmake`](https://github.com/google/iree/tree/main/build_tools/bazel_to_cmake), it could insert `INCLUDES` for generated `iree_cc_library` targets when encountering [TensorFlow](https://github.com/google/iree/blob/f505f59b9650825d5e07e799c688b012f300c79d/build_tools/bazel_to_cmake/bazel_to_cmake_targets.py#L126-L128) or [LLVM/MLIR](https://github.com/google/iree/blob/f505f59b9650825d5e07e799c688b012f300c79d/build_tools/bazel_to_cmake/bazel_to_cmake_targets.py#L122-L125) targets
https://github.com/google/iree/blob/f505f59b9650825d5e07e799c688b012f300c79d/build_tools/cmake/iree_copts.cmake#L180-L183
taking into account `BUNDLED` MLIR somehow:
https://github.com/google/iree/blob/f505f59b9650825d5e07e799c688b012f300c79d/build_tools/cmake/iree_copts.cmake#L161-L169

One approach there would be to add a `_convert_includes_from_deps` in the [cc_library conversion](https://github.com/google/iree/blob/f505f59b9650825d5e07e799c688b012f300c79d/build_tools/bazel_to_cmake/bazel_to_cmake_converter.py#L339-L370) that defers to [`bazel_to_cmake_targets.py`](https://github.com/google/iree/blob/main/build_tools/bazel_to_cmake/bazel_to_cmake_targets.py) to add the target name -> include path mappings that we know of.

We could technically add the same mappings to `iree_cc_library` directly, but I'd rather keep it generic and avoid explicit path/dependency patching.

**Comment by benvanik** [comment]
#3874 fixed this.

**Comment by marbre** [comment]
Awesome!
