### ISSUE TITLE
Pointer misalignment on ARM in iree_vm_bytecode_module_alloc_state

### ISSUE THREAD

**Issue by antiagainst** [google/iree#2209]
In `iree_vm_bytecode_module_alloc_state` we have the following logic: 

https://github.com/google/iree/blob/5e0d2c388c17a2c35ca299471983cb914eeec3ec/iree/vm/bytecode_module.cc#L449-L469

`p` does pointer calculation based on `uint8_t` and it is used to populate various pointer fields in `iree_vm_bytecode_module_state_t`. Pointer alignment is not properly considered. I'm seeing pointer misalignment on AArch64 due to this: later `ref` can hold address like `0x74c0eea09c` which is not 8-byte aligned. This causes SIGBUS error.

**Comment by benvanik** [comment]
Good catch!
