### ISSUE TITLE
Fail if no binary was selected before preparing executable from cache

### ISSUE THREAD

**Issue by antiagainst** [google/iree#2248]
At the moment we are generating the following IR sequence for binary selecting and preparing from the cache:

```mlir
      %1 = vm.call.variadic @hal.executable_cache.select_format(%ref_5, [%c1397773893]) : (!vm.ref<!hal.executable_cache>, i32...) -> i32
      %_abs_ex_dispatch_0_binary_spirv = vm.const.ref.rodata @_abs_ex_dispatch_0_binary_spirv : !vm.ref<!iree.byte_buffer>
      %ref_6 = vm.switch.ref %1[%_abs_ex_dispatch_0_binary_spirv] else %null : !vm.ref<!iree.byte_buffer>
      %ref_7 = vm.call @hal.executable_cache.prepare(%ref_5, %_executable_layout_0, %c7, %ref_6) : (!vm.ref<!hal.executable_cache>, !vm.ref<!hal.executable_layout>, i32, !vm.ref<!iree.byte_buffer>) -> !vm.ref<!hal.executable>
```

`%ref_6` can be `%null` here if no binaries were selected.  This will ends up leading to an error in "INVALID_ARGUMENT: Parameter 3 (N4iree2vm3refI24iree_vm_ro_byte_buffer_tEE) must not be null; while executing hal.executable_cache.prepare". It's a bit obscure to decipher the real reason behind; one need to invoke `iree-opt` to get the original IR dump and see the IR sequence to figure out. It would be nice to directly fail if no binary is selected and return a more clear error message.

(This happened for me when I mistakenly uses a `vmfb` not compiled for Vulkan. So this could save some red herring chasing time! ;-P)

**Comment by benvanik** [comment]
Can be handled with the new vm.cond_fail to print an error message if the select_format returns -1.

**Comment by benvanik** [comment]
This is going away as part of #3148.
