### ISSUE TITLE
Lowering to VM fails when branching with IREE Pointer arguments

### ISSUE THREAD

**Issue by rsuderman** [google/iree#2265]
Lowering a simple resource usecase results in an invalid operand for branching. It appears that either VM.Branch should support IREE.Ptr or the value should be lowered earlier.

Attaching input IR and the furthest the lowering gets before failing.

[export (1).zip](https://github.com/google/iree/files/4806516/export.1.zip)

**Comment by rsuderman** [comment]
Allowing AnyPtr for the VM branch op does seem to improve the problem, however there is a mismatched arg issue after. It appears that the block argument is not being converted to an I32 type.

**Comment by benvanik** [comment]
Assuming obsolete - if not please reopen with a test reproducer.
