### ISSUE TITLE
Move IREE to be GitHub first

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#2279]
As announced in https://groups.google.com/d/topic/iree-discuss/F07vsG9Ah4o/discussion

IREE will be trying out a flow where we merge directly on GitHub and also have a separate branch that tracks the internal Google source repository. Frequent merges between branches will be used to propagate changes.

This will allow us to hide some of the complexity of syncing with our internal source repository and get it out of the way of everyday developer flows.

Internal tracking bug http://b/159492658

**Comment by ScottTodd** [comment]
Migration is complete and (somewhat) stable.

**Comment by GMNGeoffrey** [comment]
Should we delete the old `master` branch before calling this done?

**Comment by ScottTodd** [comment]
> Should we delete the old `master` branch before calling this done?

We should do that regardless :P

**Comment by GMNGeoffrey** [comment]
Deleted
