### ISSUE TITLE
Add documentation for building integrations/

### ISSUE THREAD

**Issue by antiagainst** [google/iree#2303]
There are trickiness involved that are not directly obvious. It would be nice to have a doc to provide the steps and configurations.

**Comment by benvanik** [comment]
+1 to docs - +1000 to not needing docs (or integrations/ ;)
If there's tactical work feel free to reopen, but I suspect @phoenix-meadowlark has added the docs needed for integrations/tensorflow.

**Comment by phoenix-meadowlark** [comment]
Documentation is [here](https://google.github.io/iree/developing-iree/tensorflow-integrations) (or [here](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/README.md) with more sane syntax highlighting).

**Comment by benvanik** [comment]
nice!
(related to #3063 I so immensely prefer the github look that I never go to the justthedocs page and always read docs in github instead)
