### ISSUE TITLE
Support tools to read input values from a file

### ISSUE THREAD

**Issue by hanhanW** [google/iree#2304]
When running a mlir file or a module, we need to specify input values via command argument. This sometimes causes issues like `argument list too long`. This situation happens a lot after we started to support models from python level. Because codegen team would like to debug starting from mlir file level (the stage after SaveModel).

For now, a workaround is do not specify values so all the input values would be zero but it's harder to check if there is a numerical issue. Another workaround is starting from python level but it would waste too much time on unnecessary steps.

Support reading input values from a file for tools like iree-run-mlir/iree-run-module/iree-run-benchmark would be useful and speed up the debugging process.

**Comment by Vigilans** [comment]
https://github.com/google/iree/pull/2545
Why is this feature missing in latest main branch?

**Comment by hanhanW** [comment]
I think you're able to use flagfile now. It's a abseil feature.

> --flagfile=filename: read flags from file filename.
