### ISSUE TITLE
Running convolution tests back to back seems to produce error

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#2345]
IN PR #2319 one of the convolution tests seems to be failing when run with the others, but passes when run by itself. This seems to been hit before. the convolution1.mlir and convolution2.mlir [here ](https://github.com/google/iree/tree/main/iree/test/e2e/vulkan_specific) seems to be split for this reason. This bug is for tracking the issue

**Comment by MaheshRavishankar** [comment]
Assigning to @hanhanW for now based on TODOs . Please reassign to me/relevant people

**Comment by hanhanW** [comment]
Tested, this issue does happen on real GPU as well. It's not a SwiftShader specific issue. @ScottTodd FYI

Only nosplit-pad setting can pass the test.  Both split-pad and nocontrol setting are failing. I remember that I checked the indices are all in bounds, will do a double-check.

I guess there might be a race?

**Comment by benvanik** [comment]
I suspect uninitialized GPU memory
