### ISSUE TITLE
Allow setting pass specific flags within check-tests

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#2346]
With PR #2319 , the following option to compiler_flags doesnt seem to work.

```
compiler_flags = ["-iree-codegen-convert-to-gpu=\"use-legacy-conv-lowering=false\""], 
```

I get the following error 

```
 Unknown command line argument '-iree-codegen-convert-to-gpu=legacy-conv-lowering=false'. 
```

The command line works as expected with iree-opt (see test added with PR [here](iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_gpu_option.mlir))

**Comment by GMNGeoffrey** [comment]
So from what we discussed previously, I think a flag like this doesn't work with `iree-translate` either and the check test rules are just invoking `iree-translate`. I haven't played a lot with pass options, but my understanding is that you have to set these flags while building up a pass pipeline and they are specific to an individual instance of the pass (https://mlir.llvm.org/docs/PassManagement/#instance-specific-pass-options). `iree-translate` creates its main pass pipelines programmatically or you can invoke command-line specified pipelines. So you can run `iree-translate -iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vulkan-spirv` to use a predefined pipeline or `iree-translate --iree-hal-target-backends=vulkan-spirv --pass-pipeline=canonicalize,iree-codegen-convert-to-gpu{legacy-conv-lowering=false}` (something like that) to build up your own custom pipeline that includes an individual instance of `iree-codegen-convert-to-gpu` with some specific options, but I don't think you can just `iree-translate -iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vulkan-spirv -iree-codegen-convert-to-gpu=legacy-conv-lowering=false` and get it to pass that option to pre-existing instances of `iree-codegen-convert-to-gpu=legacy-conv-lowering`. I believe something like general global pass options for all instances of a pass would require changes to MLIR infra. For this specific pass, you could probably thread through a flag to `iree-mlir-to-vm-bytecode-module` that controls how it creates instances of this pass.

**Comment by benvanik** [comment]
Yeah can't change pass pipeline options here like that. You could create new targets or use global flags, but I think a more holistic solution for controlling pipelines is better. I'll be exposing the ability for pipeline control as part of #3817 that should allow this to be plumbed through. Closing this issue now as it's 5 months old and we've survived without it in the current infra.

**Comment by MaheshRavishankar** [comment]
Thanks for closing this. @antiagainst  refactored the Vulkan/SPIR-V target to not use pass instance specific options. We just have vanilla LLVM command-line options. Just better overall to have these flags at all levels of the infra (pass, pipeline and binary).
