### ISSUE TITLE
Refactor tf_test_utils for simplicity and work towards upstreaming into tensorflow

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#2435]
As a part of developing better tooling for benchmarking models end to end with IREE, we are planning to refactor `pyiree`'s `tf_test_utils` in the following ways:

- [ ] Transfer functionality unrelated to testing into `pyiree.tf.support.utils`.
  - The biggest change here is moving `tf_test_utils.save_and_compile_tf_module` to `utils.compile_tf_module`, which can be reused to generate artifacts for benchmarking.
- [ ] Add support for expected failing tests.
  - This will allow us to track when previously failing tests begin to pass. This has happened a few times before, but if the newly passing tests aren't added to the CI quickly enough they often regress.
- [ ] Simplify how test cases are created. I need to investigate this more, but it involves: 
  - simplifying the logic surrounding test case creation
  - eventually integrating how model artifacts are generated for benchmarking with how they are generated for testing
- [ ] Integrate the inputs specified in model generation files once they are available.
- [ ] (Potentially) simplify backend comparison by specifying a reference backend.
  - This would allow us to do a one-to-many comparison of backend results against a source of truth. For now that would be `tf` in the CI. In the chance that `tf` starts failing for a particular test, then all of the passing backends would stop passing but produce the same results, which shouldn't be difficult to diagnose. Other backends could still be compared directly via the manual targets.

**Comment by phoenix-meadowlark** [comment]
I would definitely appreciate feedback on any of these if anyone has any. In particular, @GMNGeoffrey and I had discussed the last bullet point here between ourselves, but haven't discussed it with the wider team.

**Comment by benvanik** [comment]
One thing we should track here (or in a new issue) is decoupling ourselves from the integrations/tensorflow/ test infra entirely (in that, a large majority of it should live upstream in tensorflow and not in the IREE repo). Doesn't have to happen overnight, but as improvements are being made here we should be strongly biasing towards isolating what parts are relevant to IREE and what exists in the IREE repository incidentally. We're going to want tflite->TOSA and other tests and all of those should be created upstream, and I suspect they'll be near identical to what's in integrations/tensorflow today.

**Comment by phoenix-meadowlark** [comment]
All of these improvements (and soon after more) were implemented, with the exception of expected failing tests. It would be nice if `bazel` supported those, but it's not something worth halting a PR for.

Agree with using another issue to track the things discussed on Thursday.
