### ISSUE TITLE
Fail to run vulkan tests on Android: Required Vulkan function vkEnumerateInstanceVersion not available

### ISSUE THREAD

**Issue by hanhanW** [google/iree#2506]
Followed instructions in https://google.github.io/iree/GetStarted/AndroidCMake

After working around the issue of `vkCreateInstance`, I hit another error:

```
...
I ../iree/tools/vm_util.cc:305] Creating driver and device for 'vulkan'...
E ../iree/base/api_util.h:29] UNAVAILABLE: Required Vulkan function vkEnumerateInstanceVersion not available
```

Instruction to repro

```
$ ctest -V -R iree/test/e2e/xla_ops:check_vulkan-spirv_vulkan_add.mlir_on_android_device
```

**Comment by benvanik** [comment]
what version of vulkan do you have? vkEnumerateInstanceVersion is 1.1 (our min version)

**Comment by antiagainst** [comment]
Hanhan, is your test phone running Android 10? Vulkan 1.1 should be mandated by Android 10...

**Comment by antiagainst** [comment]
Also you can use https://play.google.com/store/apps/details?id=de.saschawillems.vulkancapsviewer to get detailed information regarding Vulkan implementation on your phone.

**Comment by hanhanW** [comment]
Ah, it's running Android 9, I haven't upgraded my Samsung S10. Let me upgrade it, and test again.

**Comment by antiagainst** [comment]
Yes, please update to whatever newest stable version you can. :)

**Comment by hanhanW** [comment]
> Also you can use https://play.google.com/store/apps/details?id=de.saschawillems.vulkancapsviewer to get detailed information regarding Vulkan implementation on your phone.

Good to know this, it's useful!

**Comment by hanhanW** [comment]
Cool, it's working!

I think it would be good if we add this information to the doc or common issue, eg, we recommend users to upgrade Android to 10 or later version which usually support vulkan 1.1?

**Comment by antiagainst** [comment]
Great! I think there are a few test fails on Vulkan at the moment. I haven't looked into them closely. Could you create an issue to track them? After fixing them, we can then set up buildbots to guard against regressions.

> I think it would be good if we add this information to the doc or common issue, eg, we recommend users to upgrade Android to 10 or later version which usually support vulkan 1.1?

Android 10 requirement is already mentioned in the doc (https://google.github.io/iree/GetStarted/AndroidCMake#vulkan-hal-backend). But please feel free to send a pull request to add a new common issue for this! :)

**Comment by hanhanW** [comment]
Oh, I missed it, it's good to keep it this way. :)

Sure, I'll run the tests on Android and create issues for failing tests.
