### ISSUE TITLE
Disable LLVM JIT when cross-compiling for Android

### ISSUE THREAD

**Issue by hanhanW** [google/iree#2528]
To repro:

```bash
# Follow instruction in https://google.github.io/iree/GetStarted/AndroidCMake to build IREE
$ cd build-android
$ ctest -R iree/modules/check/test:check_llvm-ir_llvm_success.mlir_on_android_device 
```

I will post the log later.

Tag @asaadaldien for visibility

**Comment by antiagainst** [comment]
I think we want to disable LLVM JIT for Android entirely and bring up LLVM AOT for it.

**Comment by benvanik** [comment]
Yeah no JIT needed on Android!
  

  
  

  
  
>

**Comment by antiagainst** [comment]
But still, thanks Hanhan for filing the issue! I retitled it to a task. :)

**Comment by hanhanW** [comment]
Sounds good, note that the tests under xla_ops for LLVM-IR should be disabled as well.

**Comment by ScottTodd** [comment]
This is fixed, right? (also planning on removing LLVM JIT entirely soon)
