### ISSUE TITLE
Enable Wmacro-redefined if possible

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#2556]
Disabling in https://github.com/google/iree/pull/2551 due to (among others)

```
In file included from external/org_tensorflow/tensorflow/core/platform/logging.h:27:
external/org_tensorflow/tensorflow/core/platform/default/logging.h:392:9: error: 'CHECK_OP_LOG' macro redefined [-Werror,-Wmacro-redefined]
#define CHECK_OP_LOG(name, op, val1, val2)                     \
        ^
./iree/base/internal/logging.h:261:9: note: previous definition is here
#define CHECK_OP_LOG(name, op, val1, val2)                      \
        ^
```

**Comment by benvanik** [comment]
There's likely to be some other of these in harder to manage places (like windows API headers and such). We should of course fix them where we can, but I'm also not toooo concerned. What's including both the runtime logging and tensorflow? The two should never meet (tensorflow only in compiler, iree/base/logging only in runtime).

**Comment by ScottTodd** [comment]
Here are the logs from https://github.com/google/iree/pull/2551: https://source.cloud.google.com/results/invocations/b063f6e4-d92d-4ee3-9d8f-24a3464d11f6/targets/iree%2Fgcp_ubuntu%2Fbazel%2Fintegrations%2Fpresubmit/log

```
C++ compilation of rule '//integrations/tensorflow/compiler:tensorflow' failed
```

**Comment by benvanik** [comment]
`#include "iree/base/signature_mangle.h"` in TFSavedModelLowerGlobalTensors.cpp - if we're going to share the file we should make sure it doesn't pull in extra deps, or see if we can split the encoding (for the compiler) from the decoding (for the runtime).
