### ISSUE TITLE
Setup clang-tidy github action

### ISSUE THREAD

**Issue by benvanik** [google/iree#2573]
We should be able to get clang-tidy running on github actions along with the linters. The compile-commands json we generate for ninja should be all we need.

Locally, I'm running clang-tidy like this:
```
clang-tidy d:\Dev\iree\iree\vm\bytecode_module.cc \
    --export-fixes=- \
    --checks=abseil-*,bugprone-*,-bugprone-exception-escape,google-*,misc-*,-misc-unused-parameters,performance-* \
    -p=D:\Dev\iree-build\
```

There is likely a github action already on the market we can plug in and use, otherwise it should be pretty easy to do ourselves for the output. Ideally there's an action that would apply the fixes from clang-tidy (using [github actions](https://developer.github.com/v3/checks/runs/#actions-object):
![image](https://user-images.githubusercontent.com/75337/87864945-76a84900-c923-11ea-98d6-aad51800e212.png)

**Comment by GMNGeoffrey** [comment]
Automatic fixes with GitHub actions are likely to run into GitHub's terrible auth model for forks :-(

**Comment by benvanik** [comment]
Though I still think this would be the coolest thing it'd only be worth doing as a hobby project. Duping in favor of #3310.
