### ISSUE TITLE
Semaphore test is timing out with SwiftShader

### ISSUE THREAD

**Issue by rsuderman** [google/iree#2604]
Tests disabled for presubmits. Semaphore test times out with swiftshader causing integration failure when migrating repos.

**Comment by ScottTodd** [comment]
How about just disabling the test as part of your import (add `notap` tag) to unblock?

**Comment by ScottTodd** [comment]
It's timing out with timeline semaphore emulation. Possibly due to some timing changes in https://github.com/google/iree/pull/2572.

Can repro on a physical GPU with
```
$ bazel test iree/hal/cts:semaphore_test --test_arg=--vulkan_force_timeline_semaphore_emulation=true
```

**Comment by ScottTodd** [comment]
Have a fix. Working on unit tests now.
