### ISSUE TITLE
Use multistage builds for docker test images

### ISSUE THREAD

**Issue by antiagainst** [google/iree#2651]
Right now we rely on inheritance and have a tree-structured docker image relationship. This results in quite some duplication of configuration. A better way might be to use [multistage build](https://docs.docker.com/develop/develop-images/multistage-build/) where we can factor common steps (like installing cmake, installing Vulkan SDK, etc.) into utilities and compose them more easily.

**Comment by GMNGeoffrey** [comment]
I will take a look at this or LMK if you'd like to Phoenix :-)

**Comment by GMNGeoffrey** [comment]
Note that I got multistage builds with copying working for most things, but didn't figure it out for the vulkan sdk. The vulkan install seems to splat things all over the place and even when I tried an install in /opt and copied it over, things didn't work. So despite this being closed, there could be some improvements still.
