### ISSUE TITLE
Importing both pyiree.compiler and pyiree.tf.compiler in the same session causes error

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#2717]
>>> import pyiree.tf.compiler
>>> import pyiree.compiler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/laurenzo/.local/lib/python3.8/site-packages/pyiree/compiler/__init__.py", line 21, in <module>
    from . import binding as binding
ImportError: generic_type: type "OpaqueBlob" is already registered!

Some improper sharing is taking place between the two.

**Comment by stellaraccident** [comment]
Looks like there are two issues:

* The bazel side extension building is not applying the linker script to hide non-exported symbols.
* May need to apply the `py::module_local()` decorator to shared classes from the common compiler directory.

**Comment by benvanik** [comment]
Obsolete?

**Comment by stellaraccident** [comment]
It is unlikely that we will fix this in an isolated fashion and it will get brought along with an overall rework.
