### ISSUE TITLE
assert.h assertion failed at third_party/iree/iree/compiler/Dialect/VM/Analysis/RegisterAllocation.cpp:110 in void mlir::iree_compiler::RegisterUsage::rele aseRegister(uint8_t): refRegisters.test(reg & 0x3F)  

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#272]
I'm getting this in debug builds while attempting to switch TensorFlow tests to vm2.

assert.h assertion failed at third_party/iree/iree/compiler/Dialect/VM/Analysis/RegisterAllocation.cpp:110 in void mlir::iree_compiler::RegisterUsage::releaseRegister(uint8_t): refRegisters.test(reg & 0x3F)  

This isn't the first time I've triggered the assert but previous times have been in a pretty unstable setup that I wasn't able to repro.

**Comment by benvanik** [comment]
What's the stack look like? In particular, what's the operation being processed at the time?
(if cond branch, that may be what I'm currently looking at)

**Comment by benvanik** [comment]
(I believe this is fixed now)
