### ISSUE TITLE
Replace usage of absl::GetCurrentTimeNanos with an IREE version

### ISSUE THREAD

**Issue by benvanik** [google/iree#2801]
The only dependency we have on abseil in iree/base/ right now is on [absl::GetCurrentTimeNanos](https://github.com/abseil/abseil-cpp/blob/master/absl/time/clock.cc#L40). We really don't need what it's doing, as timing information is purely used for logging and deadlines which are both tolerant of some slop. So long as the time increases monotonically we're good.

There's some old internal code from Clips that we could use for doing this in a portable way (//w/l/v/).

**Comment by ScottTodd** [comment]
"So long as the time increases monotonically we're good." do we _really_ need that guarantee?

Current docs: https://github.com/google/iree/blob/b63526b4e7e348091406e3b821600fd8f4f3d404/iree/base/api.h#L383-L389

One API we could use, https://en.cppreference.com/w/cpp/chrono/system_clock , says "It may not be monotonic: on most systems, the system time can be adjusted at any moment."

**Comment by benvanik** [comment]
I think that's why I wrote that comment, but it's probably over-conservative :)

Here's the XRTL code for high performance timers:
https://github.com/google/xrtl/blob/master/xrtl/port/apple/base/mach_system_clock.cc
https://github.com/google/xrtl/blob/master/xrtl/port/common/base/posix_system_clock.cc
https://github.com/google/xrtl/blob/master/xrtl/port/windows/base/win32_system_clock.cc

implementing the interface:
https://github.com/google/xrtl/blob/master/xrtl/base/system_clock.h
