### ISSUE TITLE
Increase convolution ops test coverage

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#2802]
We need to increase the test coverage of the numerical correctness convolution ops by adding more test cases e.g 
dilated convolution, various filter and input shapes and dynamic batched_dim.

**Comment by benvanik** [comment]
Do you feel that these would be mhlo-level tests? If so, do you think that they'd still exist/be relevant if mhlo->tosa or mhlo->linalg existed upstream in tensorflow?

**Comment by asaadaldien** [comment]
+1 for mhlo tests and no more python tf tests, the only reason they exist here is to check numerical correctness. If `mhlo -> *` path exist with correctness tests infrastructure support (e.g mlir-cpu-runner) we should move it upstream.

**Comment by MaheshRavishankar** [comment]
Dropping codegen tag. If there are specific tasks w.r.t to codegen we can file separate issues for those.

**Comment by benvanik** [comment]
@asaadaldien if there's anything you want to do here specific to IREE (like new tests under iree/test/e2e/) then we can track it with this, otherwise we could move upstream.

**Comment by asaadaldien** [comment]
Yes, in the short term lets keep and increase converge of conv numerical tests under `iree/test/e2e/` especially we have an inhouse `col2img` conversion we plan to use and optimize very soon as we start generating fast CPU conv kernels.
