### ISSUE TITLE
[Android Dylib] Error: Unable to open dynamic library:'dlopen failed: cannot locate symbol "memset"

### ISSUE THREAD

**Issue by denis0x0D** [google/iree#2810]
Hi, I'm facing an error while trying to run MobileNetV2 from keras on Android dylib backend:
```
 ../iree/tools/vm_util.cc:237] Creating driver and device for 'dylib'...
E ../iree/base/api_util.h:28] UNAVAILABLE: Unable to open dynamic library:'dlopen failed: cannot locate symbol "memset" referenced by "/data/local/tmp/dylib_executabletXBewa.so"...'
E ../iree/base/api_util.h:28] UNAVAILABLE: while executing hal.executable_cache.prepare
F ../iree/tools/benchmark_module_main.cc:165] Check failed: ::iree::OkStatus() == (Run(state)) (OK vs. UNAVAILABLE: creating context)
Aborted
```

Steps:
1. Take a MobileNetV2 from keras and convert it HLO IR
2. Lower to dylib backend
```
 $ build-android/host/bin/iree-translate -iree-mlir-to-vm-bytecode-module \
 -iree-llvm-target-triple=aarch64-linux-android -iree-hal-target-backends=dylib-llvm-aot MobileNetV2.mlir -o MobileNetV2.vmfb

```
3. Push to Android device.
4. Run:

```
/data/local/tmp/iree-benchmark-module -driver=dylib -input_file=/data/local/tmp/MobilenetV2.vmfb -entry_function=predict -inputs="1x224x224x3xf32"
```
5. Output:
```
./iree/base/api_util.h:28] UNAVAILABLE: Unable to open dynamic library:'dlopen failed: cannot locate symbol "memset" 
```

So, as far as I understood the dispatch region contains the external symbol in symbol table:
 
```
 7: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND memset
```

```
0000000000000310 <predict_ex_dispatch_0>:
 310:   f81e0ffe        str     x30, [sp, #-32]!
 314:   a9014ff4        stp     x20, x19, [sp, #16]
 318:   a9404c14        ldp     x20, x19, [x0]
 31c:   5295f602        mov     w2, #0xafb0                     // #44976
 320:   72a00122        movk    w2, #0x9, lsl #16
 324:   2a1f03e1        mov     w1, wzr
 328:   aa1303e0        mov     x0, x19
 32c:   97fffff5        bl      300 <memset@plt>

```
And unfortunately `dlopen` does not work well for me on Android, when shared lib depends on other libs such as libc, also I do not have a root access on device and cannot use LD_DEBUG to understand a search paths. It works fine on linux host, but I'm not sure how to fix it on Android.

@asaadaldien can you please share, do you know any workaround for the problem like this?
Thanks.

**Comment by asaadaldien** [comment]
You probably need to statically link with libc. We are working on a general better linking story for the dyib. in the mean time try this work around set linker to clang as the following:
`IREE_LLVMAOT_LINKER_PATH = /usr/bin/clang -static-libstdc++`

**Comment by denis0x0D** [comment]
@asaadaldien thanks for an idea about static linking, those options
`-Bstatic -lc++ -Bdynamic -lm -lgcc -lc `
added to https://github.com/google/iree/blob/main/iree/compiler/Dialect/HAL/Target/LLVM/internal/LLVMAOTTargetLinker.cpp#L53
works fine for me.
Thanks.
