### ISSUE TITLE
How to generate mhlo dialect from a python file after a series of transformations？

### ISSUE THREAD

**Issue by onlyoh** [google/iree#2909]
I know that the input of IREE is mhlo dialect , but I don't know how to generate mhlo dialect from a .py file or GraphDef(e.g. a simple calculation graph). I know that simple_ir_walkthrough.md says that it can be achieved through tf2xla, but I don’t know the specific steps. Maybe it's because I don't know much about TensorFlow. Can anyone help me or give me an specific example? Thanks!

**Comment by ScottTodd** [comment]
Hi! Take a look at the Colab notebooks here: https://github.com/google/iree/tree/main/colab. They show a few workflow variations going from TensorFlow Python models to compiled and executed IREE modules. The functions that relate most to your question are `tf.saved_model.save()`, `ireec.tf_load_saved_model()`, and `ireec.tf_compile_saved_model()`.

**Comment by onlyoh** [comment]
Thanks a lot! I will try it.(P.S. This is the first time I have raised an issue on github, thank you for your patient answer! This greatly encouraged me.)

**Comment by benvanik** [comment]
TF->MHLO should be tooled and documented upstream in the tensorflow repo and not have a dependency on the IREE python API. Doesn't mean we won't do the work, but it shouldn't live in IREE. Duping as #2435 as the tests should be sharing that same infra and both should live upstream.
