### ISSUE TITLE
dot_general produces wrong output on GPU

### ISSUE THREAD

**Issue by hanhanW** [google/iree#3000]
```
func @dispatch(%arg0: tensor<1x49x640xf32>,
                            %arg1: tensor<1x640x560xf32>) -> tensor<1x49x560xf32> {
  %0 = "mhlo.dot_general"(%arg0, %arg1) {
    dot_dimension_numbers = {
      lhs_batching_dimensions = dense<0> : tensor<1xi64>,
      lhs_contracting_dimensions = dense<2> : tensor<1xi64>,
      rhs_batching_dimensions = dense<0> : tensor<1xi64>,
      rhs_contracting_dimensions = dense<1> : tensor<1xi64>
    }
  } : (tensor<1x49x640xf32>, tensor<1x640x560xf32>) -> tensor<1x49x560xf32>
  return %0 : tensor<1x49x560xf32>
}
```

To repro:

$ iree-run-mlir -iree-hal-target-backends=vulkan-spirv -input-value-file=inputs.txt dispatch.mlir

$ iree-run-mlir -iree-hal-target-backends=vmla -input-value-file=inputs.txt dispatch.mlir

The output from vmla

```
1x49x560xf32=[[0 -111.77 34.4981 0.653722 ...
```

The output from vulkan-spirv

```
1x49x560xf32=[[0 -53300.1 16465.1 282.537 ...
```

[inputs.txt](https://github.com/google/iree/files/5129282/inputs.txt)

I will try to simplify the test, eg check if this happens in dot op and maybe reduce the input size. We still can go through the IR and see if they are all correct.

**Comment by MaheshRavishankar** [comment]
Seems like I forgot to set `LinalgDistributionOptions` here. Let me try that. Thanks for the repro!

**Comment by MaheshRavishankar** [comment]
This PR seems to fix the issue. Dont know how to add a test though cause the existing test didnt catch this

**Comment by hanhanW** [comment]
The op is still not working as expected, see https://github.com/google/iree/pull/3068
