### ISSUE TITLE
How to run tests for the TensorFlow integration built with CMake?

### ISSUE THREAD

**Issue by onlyoh** [google/iree#3030]
I use CMake to build the python binding, after executing the above command, I found that the integration package is missing. The [Getting Started with Python](https://google.github.io/iree/get-started/getting-started-python) page explains how to use bazel to build tensorflow integration, but it does not explain how to use CMake to build it.

**Comment by stellaraccident** [comment]
Unfortunateley, TensorFlow is a Bazel only project and it is pretty infeasible to support a CMake build for it unless if they choose to want to do that themselves (which is fine to ask for -- it would just need to be done on their issues list). Sorry!

**Comment by onlyoh** [comment]
Thanks! This is my mistake, I ignored this problem.
