### ISSUE TITLE
Change Just the Docs theme to be something more readable/easy on the eyes (incl Python / Bazel / MLIR code)

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#3063]
I've noticed two related issues with code blocks on our documentation hub:

1. Python code is quite difficult to read. The code is displayed with a very light color and the comments are displayed with a dark color. Here's an example of how it's displayed on Just the Docs vs GitHub:
<img width="748" alt="Screen Shot 2020-09-02 at 2 46 58 PM" src="https://user-images.githubusercontent.com/40036383/92040717-c0aa8a00-ed2b-11ea-9a84-173befaf837e.png">
<img width="1020" alt="Screen Shot 2020-09-02 at 2 47 37 PM" src="https://user-images.githubusercontent.com/40036383/92040899-0d8e6080-ed2c-11ea-85f0-56cd14e30f9e.png">

2. Some language settings (e.g. `bazel` and `mlir`) cause the code blocks to display as a weird inline/code block hybrid. A good example is this section of MLIR [on GitHub](https://github.com/google/iree/blob/main/docs/design_roadmap.md#xla-hlo-tensor-to-primitive-conversion) and on [our Just the Docs](https://google.github.io/iree/design-roadmap#xla-hlo-tensor-to-primitive-conversion).

**Comment by antiagainst** [comment]
Yeah. The code highlighting needs some improvements. MLIR is entirely not supported (given it's still fairly new). I neglected that aspect when setting up everything. :( But I guess that's less a priority compared to getting the contents public available. (Well it's already public available but this makes it easier to discover.)

**Comment by benvanik** [comment]
I'm not a fan of the just the docs theme anyway - renaming this to "don't use the current just the docs theme" ;)

**Comment by ScottTodd** [comment]
This is sort of obsolete now. We're set up to use a different website generator / theme (which includes light mode + dark mode), but still don't have native support for MLIR code highlighting. The new site doesn't actually have any MLIR code though :p. I prototyped MLIR highlighting with CodeMirror, which is probably the path forward there.
