### ISSUE TITLE
Upgrade to Bazel 3.5

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#3114]
I'd like to upgrade us to Bazel 3.5. One feature I want from there is the relaxing on inconsistently-applied restrictions on workspace names, which will make integrating with the LLVM build files I'm working on smoother.

As part of this transition, we should be able to get rid of our patch to [bazel_toolchains](https://github.com/google/iree/blob/dcef2858374139821a7dbe2f5177706211438c71/WORKSPACE#L52) because https://github.com/bazelbuild/bazel-toolchains/pull/912 fixed the incompatibility with `--experimental_repo_remote_exec`

https://github.com/bazelbuild/bazel/releases/tag/3.5.0

**Comment by GMNGeoffrey** [comment]
Well now 3.5.1 and 3.6.0 are out. We could consider those as well

**Comment by benvanik** [comment]
Obsolete?

**Comment by GMNGeoffrey** [comment]
Nope. Could now be for upgrading to Bazel 3.7 though
