### ISSUE TITLE
Set `spv.target_env` by querying the device charecteristics

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#3131]
Currently the SPIR-V codegen pipeline uses the default `spv.target_env` for deciding launch configuration (like workgroup size, etc.). This needs to be modified to query the Vulkan API to get the information for the target GPU. Some additional fields are needed as well (list will be updated as needed)

- `VkPhysicalDeviceSubgroupProperties:subgroupSize`
- `VkPhysicalDeviceLimits:maxComputeSharedMemorySize`
- Cooperative matrix multiply sizes

**Comment by benvanik** [comment]
Do you mean querying at runtime? I have a WIP PR for that I can finish up, if so, though the compiler backend will still need some work.

**Comment by MaheshRavishankar** [comment]
Not querying at runtime, though that would be neat. But JIT specialization is a bit of stretch right now. For now just being able to use the device properties when compiling the model, so at IREEs runtime.

**Comment by benvanik** [comment]
Agreed! 👍

**Comment by antiagainst** [comment]
Yup! The plan is certainly beefing up the target description. I've done it in [MLIR/SPIR-V side](https://reviews.llvm.org/D87106) and will work on IREE side soon. At the moment we are using the [target for SwiftShader](https://github.com/google/iree/blob/main/iree/compiler/Dialect/Vulkan/Utils/TargetEnvUtils.cpp#L114-L118), we need to include more targets like `adreno-640`, `arm-g77-android10`, etc. The above are known targets; at the same time one can always specify the detailed configuration via [`-iree-vulkan-target-env`](https://github.com/google/iree/blob/main/iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp#L78-L82).

**Comment by MaheshRavishankar** [comment]
Oh, didnt know about `-iree-vulkan-target-env`. Thats useful. THanks!

**Comment by MaheshRavishankar** [comment]
I think this is done for now. We can revisit later.
