### ISSUE TITLE
Integrate Vector dialect based Matmul GPU Codegen strategy into IREE's SPIR-V codegeneration pipeline

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#3132]
The Matmul codegen strategy has reached suficient matrurity to be able to pull this into IREEs codegeneration path. This needs to be done in two steps.
1) Initial case of just using cooperative matrix multiply instructions
2) Use of scratchspace/workgroup memory + cooperative matrix multiply instructions.

**Comment by benvanik** [comment]
I feel like this may have landed? Or at least parts of it?

**Comment by MaheshRavishankar** [comment]
Yup . Landed. Closing.
