### ISSUE TITLE
unify backends and driver's names in different tools

### ISSUE THREAD

**Issue by rybakov** [google/iree#3177]
There are multiple IREE tools:
* iree/integrations/tensorflow/e2e; 
* iree-run-mlir; 
* iree/tools/benchmark_module_main.cc
* etc

For each of them user have to use different names for the same backends as in example below:

* iree/integrations/tensorflow/e2e
"target_backends" can be: "iree_vmla"; "iree_llvmjit"; "iree_vulkan"

* iree-run-mlir
"iree-hal-target-backends" can be "vmla"; "vulkan-spirv"; "llvm-ir"

* iree/tools/benchmark_module_main.cc driver can be "vmla"...
It is not well documented: ABSL_FLAG(std::string, driver, "vmla", "Backend driver to use."); Does it support only vmla?

It would be great to unify the names of backends and drivers.

**Comment by ScottTodd** [comment]
Prior related discussion here: https://github.com/google/iree/issues/2175

**Comment by rybakov** [comment]
Thank you! Please feel free to close this one as duplicate

**Comment by ScottTodd** [comment]
Duplicate of #2175
