### ISSUE TITLE
Confusing `-input_file`, `-inputs`, and `-inputs_file` flags in tools

### ISSUE THREAD

**Issue by antiagainst** [google/iree#3248]
So we have `-input_file` for specifying the module file and `-inputs`/`-inputs_file` to specify the input buffers to the module. They are similar enough to be confusing and prone to mistypes. I think we should rename `-input_file` to something like `-module_file` to be more descriptive.

**Comment by benvanik** [comment]
+1 - --module_file= and --function=/--function_inputs=/--function_inputs_file= would be a nice way of clarifying that

**Comment by hanhanW** [comment]
This is really annoying, I would like to take sometime to fix it....
