### ISSUE TITLE
Revive zombie code once the dust settles on the VM2 switchover

### ISSUE THREAD

**Issue by benvanik** [google/iree#325]
Commits deleting the code we want to revive will be added to this issue so we can easily find them again and track what has yet to be revived.

* [x] Vulkan integration sample: https://github.com/google/iree/commit/9ea36a0987167464afa088e94b0dd8d3064813c3
* [ ] Emscripten module runner: https://github.com/google/iree/commit/13a849aa00b96b56ef0211ebe8bbf156bc6c0fa2
* [ ] Debug server: https://github.com/google/iree/commit/1f260818a525f5ca712d9e72b891c1b10b86fdd2
* [ ] Debugger app: https://github.com/google/iree/commit/6b8093b8d22f19e92128f3b0c9fc1abfc312f9cc
* [x] Module benchmarking tool: https://github.com/google/iree/commit/2794134eef697fab551669c862619c02768ee572
* [x] iree-run-module: https://github.com/google/iree/commit/245da7cbbcbdf9e16c7fa15247efaf45f51db044

**Comment by GMNGeoffrey** [comment]
I restored iree-run-module and iree-benchmark-module a little bit ago. https://github.com/google/iree/commit/fbf26ee8d8e94e8ef7dda1367e14905d624e48a4 adds iree-run-module back to the docs.

**Comment by benvanik** [comment]
Calling this done as the new debugger infra will look very different.
