### ISSUE TITLE
'signature_def_saved_model_test' is failing in OSS.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#3258]
`integrations/tensorflow/bindings/python/pyiree/tf/compiler:signature_def_saved_model_test` fails in OSS due to the following error: 

```shell
======================================================================
ERROR: testLoadSignatureDefSavedModel (__main__.RuntimeTest)
RuntimeTest.testLoadSignatureDefSavedModel
Tests loading a SignatureDef saved model with a single variable.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integrations/tensorflow/bindings/python/pyiree/tf/compiler/signature_def_saved_model_test.py", line 58, in testLoadSignatureDefSavedModel
    module = compiler.tf_load_signature_def_saved_model(
  File "integrations/tensorflow/bindings/python/pyiree/tf/compiler/__init__.py", line 152, in tf_load_signature_def_saved_model
    input_module = binding.load_signature_def_saved_model(
RuntimeError: Failed to load saved model '/tmp/tmpbm1fmkhw/simple.sm': Not found: No session factory registered for the given session options: {target: "" config: } Registered factories are {}.

----------------------------------------------------------------------
```

It is already marked as `'nokokoro'`, but I added a `'manual'` tag to it in #3257 to avoid `bazel test integrations/...` failing.

**Comment by stellaraccident** [comment]
This is indicative of the python extension missing a dep on the TensorFlow CPU runtime. I would have thought that `"//third_party/tensorflow/core:core_cpu"` would have done it, but the exact incantations needed have sometimes needed some spelunking for me to figure out. I think you may also need the `:direct_session` target from that same package. It is in the integrations/tensorflow/bindings/python/pyiree/tf/BUILD file.

**Comment by phoenix-meadowlark** [comment]
Hmm, from what I understand adding `:direct_session` to the compiler library fixes the error above, but the test still gives the following error:

```
======================================================================
ERROR: testLoadSignatureDefSavedModel (__main__.RuntimeTest)
RuntimeTest.testLoadSignatureDefSavedModel
Tests loading a SignatureDef saved model with a single variable.
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../integrations/tensorflow/bindings/python/pyiree/tf/compiler/signature_def_saved_model_test.py", line 58, in testLoadSignatureDefSavedModel
    module = compiler.tf_load_signature_def_saved_model(
  File ".../integrations/tensorflow/bindings/python/pyiree/tf/compiler/__init__.py", line 152, in tf_load_signature_def_saved_model
    input_module = binding.load_signature_def_saved_model(
RuntimeError: Failed to load saved model '/tmp/tmpq2p7_bz0/simple.sm':
Invalid argument: No OpKernel was registered to support Op 'VarHandleOp' used by {{node Variable}} with these attrs: [
    allowed_devices=[], 
    shared_name="Variable", _class=["loc:@Variable"], 
    container="", 
    shape=[], 
    dtype=DT_INT32, 
    _output_shapes=[[]]
]

Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

         [[Variable]]

----------------------------------------------------------------------
```

**Comment by stellaraccident** [comment]
Ugh - you're now missing op libraries :(  The list is trimmed down in an attempt to keep compile time out of the stratosphere.  This is indicating that you are missing a dep on //tensorflow/core/kernels:variable_ops. There are various arrangements of kernel targets in that file and one of the aggregates may be more appropriate. There may be more such errors after this one, so it is reasonable to add one of the larger sets of kernels and hope it compiles in finite time.

**Comment by phoenix-meadowlark** [comment]
`//tensorflow/core:all_kernels` passes for the low, low price of an extra 3.5 min on a 96 core machine. I'll look for a target that doesn't multiply our integrations build time by 1.5x though 🙃
