### ISSUE TITLE
Library dependency order for building IREE as shared library

### ISSUE THREAD

**Issue by antiagainst** [google/iree#3317]
There seems to be an issue with library dependency when building IREE as a shared library. This is discovered when creating an Android native app wrapping IREE core libraries as a shared library. The main file for the Android native app uses vm_utils, which must be declared before the app itself to be picked up as a dependency. See https://github.com/google/iree/pull/3108#discussion_r496848956 for the context and more details. I haven't gotten time to look deeply into the issue; creating this to track it.

**Comment by benvanik** [comment]
Obsolete? #3874 removed alwayslink which seems to have been one of the root causes of what you were seeing.

**Comment by antiagainst** [comment]
Cool! I'll give it a try and close this if it's gone.

**Comment by antiagainst** [comment]
Confirmed that this is not valid anymore; closing this.
