### ISSUE TITLE
mhlo.{dot|dot_general} -> `linalg.{matmul|batch_matmul}  with dynamic shapes

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#3325]
https://github.com/google/iree/pull/3225 Introduced a canonicalization that reshape and inserts transposes to get mhlo dot operations into the form linalg is expected when inputs are ranked-static. 

In order to lower ops with dynamic ranked shaped tensors we need to do the same rewrites but at linalg level where we can represent reshapes and transposes for dynamic dims.

**Comment by benvanik** [comment]
Still relevant?

**Comment by MaheshRavishankar** [comment]
Yes. It is still relevant. The current batch-matmul lowering does not work for dynamic shapes.

**Comment by MaheshRavishankar** [comment]
I think this is taken care of now. Closing.
