### ISSUE TITLE
Pytype checker

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#3351]
We use python type annotations, but don't appear to validate them anywhere except on import into Google's source control. This means there are random warnings for the integrator. We should run pytype in OSS if we're going to use type annotations.

**Comment by phoenix-meadowlark** [comment]
Implemented in https://github.com/google/iree/pull/3571.

**Comment by GMNGeoffrey** [comment]
I'm seeing pytype failures in a PR that doesn't touch the files it's pointing at. I think the issue is that we're doing a diff vs `main` the base branch as opposed to doing a diff of what is changed in the PR, where I guess we'd be diffing versus the common ancestor of `main` and the PR

https://github.com/google/iree/pull/3611/checks?check_run_id=1311964122
