### ISSUE TITLE
convert-vmla-to-vm is dependent on VMLA dialect

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#3352]
While debugging another issue, I noticed that the convert-vmla-to-vm pass crashes when passed `/dev/null` (I was actually passing it more than that :-D)

https://gist.githubusercontent.com/GMNGeoffrey/f7f1014062ef1e2e0e1e60266ee803d2/raw/6c81e37a0ca9a3a73f9078fafd117a97e32a9c4b/gistfile1.txt

It appears that the issue is that `appendImportModule` [takes a chunk of mlir text](https://github.com/google/iree/blob/8c731d5a38d8858daa6c87466536fe7a257b3147/iree/compiler/Dialect/VMLA/Conversion/VMLAToVM/ConvertVMLAToVM.cpp#L370) and adds it into the input, which means even if the input didn't have any VMLA (and therefore the dialect was not loaded), we end up with VMLA and try to load the dialect while running the pass. Making the pass add VMLA as a dependent dialect results in a circular dependency because VMLADialect uses populateVMLAToVMPatterns.

**Comment by GMNGeoffrey** [comment]
The reason I was hitting this was because of split-input-file with an empty split after I commented stuff out. I continue to hate split-input-file

**Comment by GMNGeoffrey** [comment]
So this turns out to be an edge case, but I still think it raises some potential layering issues. Effectively ConvertVMLAToVM is dependent on the VMLA dialect but it's just through a text block. I could similarly check if the VMLA dialect is already loaded in the pass and fail it if not, but it would have to be by looking up the string "vmla"... bleh

**Comment by benvanik** [comment]
we could split the `VMConversionDialectInterface` interface out from the dialect itself and move it into `VMLA/Conversion/VMConversionInterface.h/cpp` such that both the dialect and the pass depended on it

**Comment by benvanik** [comment]
(all the other dialects have this issue too like hal/etc)

**Comment by benvanik** [comment]
Adding a dialect interface method that walked the module to see if there were any ops from the dialect before merging in would help. The issue is that we don't know which imports are needed until after conversion, but there may be something we could do to ensure we run at the very end (module conversion?) after all conversion patterns on the body have been applied and insert then with just what was used.
