### ISSUE TITLE
Support for importing/exporting memory allocations

### ISSUE THREAD

**Issue by kpet** [google/iree#3379]
Vulkan has support for importing/exporting memory allocations via [VK_KHR_external_memory_fd](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_memory_fd.html), This would be useful to avoid memory copies when IREE is integrated into a multi-device pipeline.

**Comment by benvanik** [comment]
Related to #3378.

**Comment by benvanik** [comment]
Duplicate of #7242. That's tracking the staging/upload buffer optimization where we'd use this with potentially several extensions we could make work.
