### ISSUE TITLE
Create benchmark(able) exported functions for flow.executable op

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#3384]
To benchmark each `flow.executable` in a module we need to add a pass (e.g `flow-export-dispatch-regions`) that does the following:
- Clone each dispatch `flow.dispatch.region` into a function with `iree.module.export` attribute.
- The cloned function should have no inputs arguments are allocated as constants.
-  To amortize allocation add a loop around the actual computation in the region.

**Comment by hanhanW** [comment]
#3624 makes original exported function take no input, so we can benchmark on that with `iree-benchmark-module` easier. Otherwise, there are exported functions that take inputs, so the benchmarking tool won't work with the module directly.
