### ISSUE TITLE
low_level_invoke_function Colab notebook throws errors out of the box on Windows

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#3394]
The [low_level_invoke_funciton](https://github.com/google/iree/blob/main/colab/low_level_invoke_function.ipynb) notebook with this Python code:
```python
import numpy as np
from pyiree.tf import compiler as ireec
from pyiree import rt as ireert
# Compile a module.
ctx = ireec.Context()
input_module = ctx.parse_asm("""
  module @arithmetic {
    func @simple_mul(%arg0: tensor<4xf32>, %arg1: tensor<4xf32>) -> tensor<4xf32>
          attributes { iree.module.export } {
        %0 = "mhlo.multiply"(%arg0, %arg1) {name = "mul.1"} : (tensor<4xf32>, tensor<4xf32>) -> tensor<4xf32>
        return %0 : tensor<4xf32>
    } 
  }
  """)
blob = input_module.compile()
m = ireert.VmModule.from_flatbuffer(blob)
```

produces these error logs for me on Windows:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-859b9be6b3c9> in <module>
     10   }
     11   """)
---> 12 blob = input_module.compile()
     13 m = ireert.VmModule.from_flatbuffer(blob)

RuntimeError: Error compiling IREE module:

[ERROR]: Can't link executable and generate target dylib using lld::elf::link
  at: -:5:14


[ERROR]: failed to serialize op to target backend dylib*
  at: -:5:14
```

We either should get LLVMAOT working without configuration, or not compile with it by default. I have a higher tolerance for this in command-line tools, but the Python code should be held to a higher simplicity / "it just works" standard.

cc @asaadaldien , @phoenix-meadowlark

**Comment by ScottTodd** [comment]
One workaround is to specify a list of backends from [`dylib-llvm-aot', 'llvm-ir', 'vmla', 'vulkan-spirv'`] explicitly:

```python
blob = input_module.compile(target_backends = ["vulkan-spirv"])
```

**Comment by phoenix-meadowlark** [comment]
I've only tested these notebooks internally, which AFAIK will have everything set up automatically. I haven't looked at that part of the python bindings yet. Compiling to a specific backend seems reasonable though. The default of compiling to all target backends exists in the tensorflow python bindings as well.

**Comment by ScottTodd** [comment]
Defaulting notebooks to use only VMLA seems reasonable to me, with instructions on using other compiler targets / runtime backends where useful.

We could do more complicated things like conditionally enabling targets based on availability on the host machine, but I'd rather keep things simple.

**Comment by ScottTodd** [comment]
Improvements to LLVM AOT linking across platforms should have fixed this. We also have pip releases so using the standard Linux runtimes for Colab is also easy.
