### ISSUE TITLE
Use LinalgTileAndFusePass on CPU

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#3407]
The CPU pipeline can use the same approach used for the GPU/SPIR-V codegen to tile + fuse + distribute operations. THis pass is currently used only on the GPU side, but with some refactoring these could be used for both CPU and GPU with just different options.

**Comment by benvanik** [comment]
Obsolete with #1354?

**Comment by MaheshRavishankar** [comment]
Lets close this one. I will create a separate bug to use the same pass on both.
