### ISSUE TITLE
Fuse operations with Matmul, Conv, Pool, etc.

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#3408]
Using the tile + fuse + distribute transformations in Linalg, elementwise operations can be fused into matmuls, conv, reductions, etc. The base transformation here is relevant for both CPU and GPU

**Comment by benvanik** [comment]
here's where the special-casing lives:
https://github.com/google/iree/blob/15c6d4565b1590ed2fcccb1056db7f7478b95101/iree/compiler/Dialect/Flow/Transforms/DispatchConfig.cpp#L32-L38

(concat and slice are ones that we can sometimes pull out into special flow dialect ops as they can impact allocation, but the rest fall into this category and it'd be nice if slices didn't break up dispatch region formation if in the middle of a sequence of ops)

**Comment by benvanik** [comment]
May be subsumed by #1354 work?

**Comment by MaheshRavishankar** [comment]
Nope, this is for work related to fusion. It works for both fusion on buffers and fusion on tensors. (Not everything is solved by moving to linalg on tensors :) )

**Comment by MaheshRavishankar** [comment]
Closing this since the core functionality is added in PR #4008
