### ISSUE TITLE
Investigate out-of-tolerance keras:large_cifar10_internal_tests_ResNet50__tf__iree_vulkan

### ISSUE THREAD

**Issue by benvanik** [google/iree#3489]
After PR #3424 `//integrations/tensorflow/e2e/keras:large_cifar10_internal_tests_ResNet50__tf__iree_vulkan` started having larger diffs (~0.1) than the previous max tolerance. LLVM passes with no tolerance change, so there may be something specific to the Vulkan HAL, swiftshader, or SPIR-V codegen. It'd be useful to narrow down where this is happening and see if we can get a test earlier in the pipeline for whichever area it falls under.

Log:
https://source.cloud.google.com/results/invocations/c52975b6-bc8c-4aed-aa32-a544d7dcfc71/targets/iree%2Fgcp_ubuntu%2Fbazel%2Flinux%2Fx86-swiftshader%2Fintegrations%2Fpresubmit/log

**Comment by hanhanW** [comment]
This one is tricky. The output of second launch is wrong.

VMLA
```
=== Output for predict_ex_dispatch_1 ===
1x16x16x64xf32=[[[-0.0248649 0.181895 -0.162422 ...
```

Vulkan
```
=== Output for predict_ex_dispatch_1 ===
1x16x16x64xf32=[[[-0.209309 -0.013611 -0.0699595 ...
```

I tried several ways but couldn't get the test case smaller.

1) Only test on dispatch_1 (which is a convolution), the outputs are the same.
2) Only test on dispatch_0 + dispatch_1, the outputs are the same.
3) As (2), but use flow variable as one of input arguments (exactly as the same way as in the model), the outputs are the same.


The dispatch_1 is:

```mlir
func @predict_ex_dispatch_1(%arg0: tensor<1x38x38x3xf32>, %arg1: tensor<7x7x3x64xf32>) -> tensor<1x16x16x64xf32> attributes { iree.module.export }{
  %0 = "mhlo.convolution"(%arg0, %arg1) {
    batch_group_count = 1 : i64,
    dimension_numbers = {input_batch_dimension = 0 : i64,
                         input_feature_dimension = 3 : i64,
                         input_spatial_dimensions = dense<[1, 2]> : tensor<2xi64>,
                         kernel_input_feature_dimension = 2 : i64,
                         kernel_output_feature_dimension = 3 : i64,
                         kernel_spatial_dimensions = dense<[0, 1]> : tensor<2xi64>,
                         output_batch_dimension = 0 : i64,
                         output_feature_dimension = 3 : i64,
                         output_spatial_dimensions = dense<[1, 2]> : tensor<2xi64>},
    feature_group_count = 1 : i64,
    padding = dense<0> : tensor<2x2xi64>,
    rhs_dilation = dense<1> : tensor<2xi64>,
    window_strides = dense<2> : tensor<2xi64>
  } : (tensor<1x38x38x3xf32>, tensor<7x7x3x64xf32>) -> tensor<1x16x16x64xf32>
  return %0 : tensor<1x16x16x64xf32>
}
```

note: the results from vulkan and vmla are the same in this single case. They are all `1x16x16x64xf32=[[[-0.0248649 0.181895 -0.162422...`

**Comment by hanhanW** [comment]
I suspect that maybe the constants are not handled well. This case and the case in #3507 are both taking constants as input arguments and resulting wrong output.

I think the next step is to bisect on the commit chain #3424

**Comment by hanhanW** [comment]
The root cause is this commit: https://github.com/google/iree/commit/a8fcd48de752ac7c4e978bbdbfa2e3819c34abf5

It's passing at the previous one, https://github.com/google/iree/commit/2dbe2fbd5a45dba5dd1a894951d9ab881a9d0999

Same thing happens in MobileBert on vulkan.

@benvanik is this good enough for you to debug? I can try to get something more if needed.

**Comment by benvanik** [comment]
Fantastic! I'm really glad I didn't squash that PR :P

I'll work on bert to narrow things down (since I can test that without using python).

**Comment by hanhanW** [comment]
Cool, thanks for the quick fix!

**Comment by benvanik** [comment]
Thanks for helping isolate the issue! It really helped!
