### ISSUE TITLE
Prototype dynamic shape inference lowering to HLO/IREE

### ISSUE THREAD

**Issue by benvanik** [google/iree#35]
This may be done for us as part of MLIR's tf2xla effort however we need to ensure what is produced lines up with what we need to perform symbolic shape calculation. Specifically, we want to be able to know which calculations are part of shape inference vs. general arithmetic and which values are shapes.

**Comment by stellaraccident** [comment]
It's time to pick this up. I'll be enabling dynamic batch dims on one of our examples and chasing the issues down through the stack. In talking with Nicolas, this would be timely with respect to the Linalg/codegen work.

**Comment by stellaraccident** [comment]
Closing since the prototype has been successful.
