### ISSUE TITLE
value_liveness.mlir.test fails on windows with bazel and MSVC

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#3556]
value_liveness.mlir.test fails on windows with bazel and MSVC. The diff is in the names of the basic block arguments. `block_defined = ["%1", "%2", "%bb1_arg0"]` is instead `block_defined = ["%1", "%2", "%bb2_arg0"]` even though the block is called bb1. 

```shell
bash -c "bazel-bin/iree/tools/iree-opt  -split-input-file -pass-pipeline='vm.module(test-iree-vm-value-liveness)' iree/compiler/Dialect/VM/Analysis/test/value_liveness.mlir"
```

gives

https://gist.github.com/GMNGeoffrey/a0dc8be768064740e39b581526110f22

**Comment by benvanik** [comment]
Will be "fixed" by #3859 (by deleting our copy in favor of upstream's :)
