### ISSUE TITLE
Attach Aliased decoration to spv.globalVariable when having overlapping set/binding numbers in shaders

### ISSUE THREAD

**Issue by hanhanW** [google/iree#3573]
Chat with Mahesh and we found that we could already have this issue in current codegen pipeline. This can be caused by fusing reshape ops and iree.load/store ops.

https://github.com/google/iree/blob/b3c56b22161bb8807babeaa40ee9dfd3ee814143/iree/compiler/Conversion/HLOToLinalg/FusionOfTensorOps.cpp#L34-L48

Which causes different shape on same set and binding placeholder in the later pass -- HLOToLinalgOnBuffers.

Another potential case is in #3194. This is okay for now because there are many constraints in the pass. However, we could hit the issue in the future when relaxing the condition.

**Comment by antiagainst** [comment]
#3692 addresses this.
