### ISSUE TITLE
Support splitting a command into multiple RUN lines in IREE lit test

### ISSUE THREAD

**Issue by hanhanW** [google/iree#3668]
LLVM lit test supports to split a test command into multiple RUN lines:

> Each RUN line is executed on its own, distinct from other lines unless its last character is \\. This continuation character causes the RUN line to be concatenated with the next one. In this way you can build up long pipelines of commands without making huge line lengths. The lines ending in \\ are concatenated until a RUN line that doesn’t end in \\ is found.

https://llvm.org/docs/TestingGuide.html#writing-new-regression-tests

I tried it in IREE lit test but failed. MLIR test does have this feature, it would be good if we can have this. E.g.,

```
// RUN: mlir-opt %s -convert-linalg-to-std -convert-linalg-to-llvm \
// RUN: | mlir-cpu-runner -e dot -entry-point-result=f32 -shared-libs=%linalg_test_lib_dir/libmlir_test_cblas%shlibext,%linalg_test_lib_dir/libmlir_test_cblas_interface%shlibext \
// RUN: | FileCheck %s

...
```

https://github.com/llvm/llvm-project/blob/master/mlir/test/mlir-cpu-runner/linalg_integration_test.mlir

Now we have some tests running with complex command, like:

https://github.com/google/iree/blob/85d24a0cbaddbbef591bc6c6cf6fa4c3587e6436/iree/tools/test/simple.mlir#L1-L14

**Comment by GMNGeoffrey** [comment]
This is fixed with the move to using real lit
