### ISSUE TITLE
Bunch of "Validation Error" in unidirectional_lstm.mlir test on vulkan-spirv

### ISSUE THREAD

**Issue by hanhanW** [google/iree#3698]
This is an issue(?) I found in #3682, which looks like a runtime issue. I'm not sure if this is the root cause that makes #3682 presubmit fail, but still filing an issue for tracking this.

Log: https://gist.githubusercontent.com/hanhanW/10265dde764e8115b68484165f1b2024/raw/3d7f6437de29cdc4ecea8cedad46ebf6512b630c/unidirectional_lstm_vulkan_log

To repro:

$ iree-run-mlir iree/test/e2e/models/unidirectional_lstm.mlir -iree-hal-target-backends=vulkan-spirv -function-input="1x5xf32=[0 1 0 3 4]" -function-input="1x5x2x2xf32=[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20]"

**Comment by benvanik** [comment]
The first one (about invalid usage bits) existed before, but the range one seems new. That indicates that the buffer is not being allocated padded out or alignment in one place but is in another.

**Comment by benvanik** [comment]
#1162 is needed to fix the usage bits issues.

**Comment by benvanik** [comment]
(we'll want these fixed prior to the GPU burndown as they are indicating things that have material impact on the performance we care about: running dispatches on host-local buffers is near the top of the "never do that" list for GPU performance :)

**Comment by hanhanW** [comment]
FYI, I gave it another run (since the log was generated 30 days ago), and I got the same errors.

**Comment by benvanik** [comment]
With streams enabled in #7659 I get zero validation warnings with the latest Vulkan SDK 🎉
