### ISSUE TITLE
Update glslang submodule

### ISSUE THREAD

**Issue by marbre** [google/iree#373]
With https://github.com/KhronosGroup/glslang/commit/3b8d94f4223416a45a4dd41e80dc92a06be712bc an option was introduced to disable testing. I would appreciate if the submodule can be updated to a ref that contains this commit.

**Comment by GMNGeoffrey** [comment]
Assuming it doesn't break anything, this seems reasonable. I can do this after we get the cmake build passing. Also FYI, you can still send PRs that update submodules, they just have to be separate from updates to other files (for now, @stellaraccident is working on a fix so we can capture submodule information upstream).
