### ISSUE TITLE
Add a second region to IREE::HAL::ExecutableTargetOp to hold host functions

### ISSUE THREAD

**Issue by benvanik** [google/iree#3737]
Right now the vulkan and llvm backends insert functions for computing the workgroup counts into their modules. This causes a ripple effect of weirdness as translated modules will end up with both host and target functions. Instead we can add a new host region with the existing region 0 staying as the target translated IR that holds all these functions. Then we don't have to check for/ignore them during translation/serialization like [we do now](https://github.com/google/iree/blob/b4d96ebe3d4b1e932fab47a96b9c58a1ddf5bb9e/iree/compiler/Dialect/HAL/Target/LLVM/AOT/LLVMAOTTarget.cpp#L49-L59).

This will also make it easier to scale out to additional functions like this (workgroup size, ordering, etc) as well as possibly clean up all of TargetBackend such that things like the dispatch function are just functions in the host region called by the host code (like `@my_executable::@llvm::@host::@issueDispatch`). The current `hal.device.switch` would then just be switching and calling the dispatch functions (which the inliner could inline, etc to end up with what we have today, but in a much cleaner way).

**Comment by benvanik** [comment]
Improvements here will be required to get dynamic workgroup sizes, data-dependent workgroup counts, etc and would be nice to land prior to starting broader tuning work.

**Comment by MaheshRavishankar** [comment]
I think this is addressed by https://github.com/google/iree/commit/86de3ffe548a265d008fb9270ce839d4fd46843f. Closing
