### ISSUE TITLE
Excise abseil usage from iree/

### ISSUE THREAD

**Issue by benvanik** [google/iree#3848]
Current usage under iree/ (excluding bindings/ and other non-core paths): https://gist.github.com/benvanik/9316c8bfd46d6910a1e996ac1427d6d4

It's cheap enough to keep around for tests and such, but it shouldn't be pulled into any end-user compiler or runtime binaries like it is now with flags/logging/etc that bring in 150-200KB of junk.

* [x] #3814: flags
* [x] ~#2843: logging~ (good to replace, but our core logging doesn't depend on abseil)
* [x] absl/base -> replace with iree/base/api.h or iree/base/threading.h (has most annotations already)
	* [ ] core_headers (used by statusor for `absl::disjunction`)
    * [x] attributes.h
	* [x] macros.h
	* [x] thread_annotations.h
* [x] absl/container
	* [x] flat_hash_map.h
	* [x] flat_hash_set.h
	* [x] inlined_vector.h
* [x] absl/memory/memory.h -> replace with iree/base/memory.h / std::make_unique / iree::wrap_unique
* [x] absl/strings
	* [x] ascii.h
	* [x] match.h
	* [x] numbers.h
	* [x] str_cat.h
	* [x] str_format.h
	* [x] str_join.h
	* [x] str_replace.h
	* [x] str_split.h
	* [x] str_strip.h
	* [x] string_view.h
* [x] absl/synchronization/mutex.h
	* [x] use in IREE -> replace with iree/base/synchronization.h + optional c++ wrapper?)
	* [x] VMA adapter - needs iree_mutex_t reader/writer lock support
* [x] absl/types
	* [x] optional.h (std::optional in c++17)
	* [x] span.h
	* [x] variant.h (unused)
* [x] absl/utility
	* [x] c++11 compat std::remove_cv_t etc
	* [x] c++14 compat absl::exchange etc
	* [x] c++17 compat std::disjunction etc

**Comment by ScottTodd** [comment]
Most of the simple replacements are done now (assuming no other undiscovered bugs >_>).

`absl/strings`, `span`, and `flags` are the notable dependencies left... and each of those will require some more principled work to migrate off of.

**Comment by benvanik** [comment]
I may try to take on flags soonish. VMLA replacement will drop most of our uses of Span. Dropping SIP (signature_parser) will remove some strings usage. HAL buffer_view/string_util are probably the trickiest core parts. Vulkan HAL still needs porting to C to drop the remaining Span usage in there.
