### ISSUE TITLE
Add a flow.variable.load canonicalizer to move it up to the top of its parent block

### ISSUE THREAD

**Issue by hanhanW** [google/iree#3883]
I noticed this in #3861 and #3876. At some point, the complier will generate this kind of code at flow level:

```mlir
module {
  flow.variable @var1 dense<1.000000e+00> : tensor<4xf32>
  flow.variable @var2 dense<2.000000e+00> : tensor<4xf32>
  func @notDominate() -> tensor<4xf32> {
    %c4 = constant 4 : index
    %0 = flow.variable.load @var1 : tensor<4xf32>
    %1 = flow.dispatch.region[%c4 : index](%arg0 = %0 : tensor<4xf32>) -> tensor<4xf32> {
      %4 = mhlo.add %arg0, %arg0 : tensor<4xf32>
      flow.return %4 : tensor<4xf32>
    }
    %2 = flow.variable.load @var2 : tensor<4xf32>
    %3 = flow.dispatch.region[%c4 : index](%arg0 = %0 : tensor<4xf32>, %arg1 = %2 : tensor<4xf32>) -> tensor<4xf32> {
      %4 = mhlo.subtract %arg1, %arg0 : tensor<4xf32>
      flow.return %4 : tensor<4xf32>
    }
    return %3 : tensor<4xf32>
  }
}
```

This will make dispatch regions not mergable. Same issue happens on `iree.unfoldable_constant`, which will be lowered to `iree.do_not_optimize` and be put at the same place as `flow.variable.load`.

In this case, the behavior of E2E testing between taking function arguments and iree_unfoldable_constant is different. One way to fix it is reordering the operations. E.g.,

```mlir
module {
  flow.variable @var1 dense<1.000000e+00> : tensor<4xf32>
  flow.variable @var2 dense<2.000000e+00> : tensor<4xf32>
  func @dominate() -> tensor<4xf32> {
    %c4 = constant 4 : index
    %0 = flow.variable.load @var1 : tensor<4xf32>
    %1 = flow.variable.load @var2 : tensor<4xf32>
    %2 = flow.dispatch.region[%c4 : index](%arg0 = %0 : tensor<4xf32>) -> tensor<4xf32> {
      %4 = mhlo.add %arg0, %arg0 : tensor<4xf32>
      flow.return %4 : tensor<4xf32>
    }
    %3 = flow.dispatch.region[%c4 : index](%arg0 = %0 : tensor<4xf32>, %arg1 = %1 : tensor<4xf32>) -> tensor<4xf32> {
      %4 = mhlo.subtract %arg1, %arg0 : tensor<4xf32>
      flow.return %4 : tensor<4xf32>
    }
    return %3 : tensor<4xf32>
  }
}
```

**Comment by hanhanW** [comment]
One workaround to make the behavior be the same as taking function arguments is to write test like:

https://github.com/google/iree/blob/347d5c49321def2bcfc8252f3057afead9341b68/iree/test/e2e/structural/fused_dispatch_region.mlir#L1-L21

**Comment by benvanik** [comment]
We should see if we can add a canonicalizer to flow.variable.load to move it up in the current block as high as possible (similar to how constants move up in their block to the top) - that should fix this automatically.

**Comment by benvanik** [comment]
As dispatch region formation is critical for GPU performance we need should ensure that we are not introducing anything that may reduce the efficacy of the formation process. #1124 may help here too as then standard MLIR infra may be able to take care of this for us as soon as it knows the memory effects of the flow.variable ops.
