### ISSUE TITLE
Clarify what is root op and leaf op

### ISSUE THREAD

**Issue by hanhanW** [google/iree#3924]
In https://github.com/google/iree/pull/3876, the word's meaning seems not the same to everyone. Chatted with @MaheshRavishankar offline, we would like to make the define like below:

```
func @foo (leaf_op) {
   o <--- leaf op
 /
v
o
  \
   v
    o <--- root op
 return root_op
}
```

This is the issue for tracking it, and we should have a better doc on this.

**Comment by MaheshRavishankar** [comment]
+1!

**Comment by benvanik** [comment]
Dispatch regions are not meant to have singular roots, which is where I think some of the confusion is coming in.  So maybe clarifying that what is being checked here is for a single dependency chain and not something inherent to the whole dispatch region would help. Someone who has a better understanding of all the graph terminology (@silvasean?) may be able to help here.

Sean: what are the blue things in my mspaint diagram called? :P 
![image](https://user-images.githubusercontent.com/75337/99719625-6800a880-2a61-11eb-854b-f8b2b045e65c.png)

**Comment by silvasean** [comment]
In (directed) graph terminology, they would be vertices that have no out-edges.

We probably just want to call these "dispatch region inputs" and "dispatch region outputs".

Inside a particular algorithm for forming dispatch regions, we may want to call them root/leaf if it makes sense for that algorithm.

**Comment by MaheshRavishankar** [comment]
I was also using root op as an op that doesnt have out going edges.

**Comment by hanhanW** [comment]
I think this really depends on how we image the graph, my beginning thought is to add edges from producers to consumers. In this case, the "dispatch function inputs" will be root. For example:

```
        c1
      ^
     /
p1
     \
       v 
        c2
        ^
      /
p2
```

This kind of graph can be called polytree, see https://en.wikipedia.org/wiki/Polytree. The definition states that this is a rooted tree. In this context, p1 and p2 (which are "dispatch region inputs") are root ops.

But if you look it as AST (abstract syntax tree) style (ie, reverse all the edges), consumers would be root ops.

(btw, ASCII art is hard... hope you understand my diagram :-p)

**Comment by silvasean** [comment]
I don't see why a dispatch region needs to be a polytree.

Dispatch region where the underlying undirected graph is cyclic (this could happen when creating a dispatch region from a simple DAG of elementwise ops):

![image](https://user-images.githubusercontent.com/24583347/99833090-6fce5480-2b16-11eb-8fcb-ec9fe255cf77.png)

Dispatch region where the underlying undirected graph is disconnected (this would happen in a "horizontal fusion" case; e.g. two unrelated elementwise ops that operate on the same shape, but with different inputs and outputs; it can be beneficial to fuse them into a single dispatch):

![image](https://user-images.githubusercontent.com/24583347/99833134-7f4d9d80-2b16-11eb-8b87-02f8c30537e9.png)


Also, in a polytree, the term "root" is inherited from a tree, which means that there is a unique root vertex. But for dispatch regions (such as Ben's diagram above), we can have multiple things called "root".

Hopefully we can migrate to linalg on tensors eventually, and have this all just disappear

**Comment by benvanik** [comment]
spot on sean! dispatch regions are more like forests of polytrees

From the IREE perspective one can think of dispatch regions as just black boxes containing any arbitrary IR in any dialect doing whatever it wants. The only requirement IREE has is that the memory effects are defined on the dispatch op such that the dispatch ops can be reordered, folded, etc. You can roughly think of them like [asm](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html) in C: you have some opaque (to the compiler) set of ops and some list of inputs and outputs (the region arguments/results) and clobbers (not yet modeled but part of #1124). Worst case we'll be able to tag a dispatch region with `volatile` indicating that there is unmodeled side-effects: it's always valid/correct to do so but it should terrify someone as much as seeing an `asm volatile` does in C :)

This means that you could today have something like:

```mlir
%output_frame, %new_state = flow.dispatch.region(%user_input = %arg0 : tensor<...>, %previous_state = %arg1 : tensor<...>)
    -> (tensor<...>, tensor<...>) {
  // This could be an arbitrary set of shaders, *or* could call into a java VM and run
  // an entire game frame, or make a network call to go ask some remote server to do it.
  // All that matters to IREE is that the only visible side-effects to IREE are that
  // %user_intput/%previous_state is read and %output_frame/%new_state is written.
  %output_frame, %new_state = minecraft.run_frame(%user_input, %previous_state) ...
  return %output_frame, %new_state
}
```

So whatever we are doing today to form these dispatch regions is just a super tiny fraction of a super tiny set of cases. It's fine to keep it simple (ala IdentifyDispatchRegions2) until we have linalg on tensors but it is important to know that any such limitation on the number of roots or the kinds of operation that can be performed inside a dispatch region is purely artificial and something not fundamental to the concept. Whether that helps with any of this work in the short term I dunno, but it is worth understanding what we're working towards :)

> Hopefully we can migrate to linalg on tensors ... and have this all just disappear

yeah! We still need to get some of the concrete examples drawn up but it's looking more and more like we'll be able to just turn sets of scf.for loops (or something very similar to them) into dispatch regions. And in those cases you could have two sibling scf.for loops producing two different sets of data (each loop is a root of its own tree), etc. It's just code :)

**Comment by benvanik** [comment]
I think this is no longer relevant (or at least would be a question at the linalg level).
