### ISSUE TITLE
CMake configuration for iree::tools

### ISSUE THREAD

**Issue by marbre** [google/iree#393]
At the moment CMake allows to build the executables `iree-tblgen` and `iree-translate`. However, several additional targets are required to catch up with the Bazel build:

- [x] Add configuration for `iree-dump-module`
- [x] Add configuration for `iree_opt_library`
- [x] Add configuration for `iree-opt`
- [ ] Fix and enable configuration for `iree-run-mlir`
- [x] Split `iree-translate` executable into `iree_translate_library` library and executable

The two are related with the `ALWAYSLINK` property and therefore with #190.

**Comment by marbre** [comment]
@ScottTodd I would really appreciate if you could take a look as well. So far I wasn't able to split `iree-translate` into library and executable. The build passed, but the static registration was broken again.

**Comment by ScottTodd** [comment]
Sure, I can take a look at this and other CMake issues once I catch back up. Looks like lots of things changed while I was on vacation :)

**Comment by ScottTodd** [comment]
Looking more into these now. I think I'll start with transitive dependency `ALWAYSLINK` handling then take a shot at splitting `iree-translate` into `iree_translate_library`.

**Comment by marbre** [comment]
@ScottTodd Thanks for all the effort you put into the transitive ALWAYSLINK deps!
