### ISSUE TITLE
Remove vulkan-specific CTS lifetime hack

### ISSUE THREAD

**Issue by benvanik** [google/iree#3933]
https://github.com/google/iree/blob/c2947ad2389050fa926e6ae1fd8a55c72a700083/iree/hal/cts/cts_test_base.h#L44-L53

That this exists is a pretty good indicator that we are just passing the a ticking timebomb to users; every user of IREE will _also_ have to deal with this because we don't. We must track and remove these lest we end up with stackoverflow answer cargoculting "just never release your driver and you'll be fine" and other insane hacks. It's possible for drivers to come and go within a process in ways that are hard for users to hack around too, such as how Android is allowed to load/initialize native modules several times within a single process lifetime.

This doesn't mean the CTS has to recreate the driver each test - instead, we *should* be caching *all* of them in the suite like this without special-casing Vulkan. But we also then should have a test that explicitly tries to create a driver twice and make sure that works. This is a solvable problem without just kicking the ball (that's really a timebomb) over to users.

**Comment by ScottTodd** [comment]
https://github.com/google/iree/pull/3561#discussion_r510996535 might be fixed on newer versions of SwiftShader (I haven't verified that though)

**Comment by benvanik** [comment]
Awesome! I still think it's worth caching the drivers per suite (so we aren't dlopen/dlclosing around every single test), and worth having a test that tries to create a driver twice (as otherwise it's possible for *us* to introduce issues that prevent ourselves from being created multiple times with no way to know), but if we could have Vulkan just work that's gravy :)

**Comment by antiagainst** [comment]
+1. Will clean this up after Hanhan lands the SwiftShader bump. :)

**Comment by ScottTodd** [comment]
This was fixed in several ways:
* our Vulkan API usage was fixed (IIRC it had to do with which structs we populated based on requested extensions)
* SwiftShader fixed some issues
* our new CTS tests do not have this specific hack
