### ISSUE TITLE
Begin Flow/Conversion/TOSAToFlow patterns.

### ISSUE THREAD

**Issue by benvanik** [google/iree#3950]
The TOSA (Tosa?) dialect landed [upstream in MLIR](https://github.com/llvm/llvm-project/tree/620adacf87a376ec536ccc66af59df5bb4dc3b38/mlir/include/mlir/Dialect/Tosa). As we are currently linking in the HLO dialects we should ensure that we can properly depend on it by adding it to our deps and starting to recognize some of the ops we want to pull out into the flow dialect.

**Comment by stellaraccident** [comment]
@rsuderman is going to work on this. The next steps are also upstream: we're going to write transforms in LLVM to lower to LinAlg/Tensors. So hopefully, the IREE work involved is just adding some patterns/passes, not really writing much (or any) code.

**Comment by stellaraccident** [comment]
Also, the TensorFlow converters (from TF and TFL) are almost landed: https://github.com/tensorflow/tensorflow/pull/44851

**Comment by benvanik** [comment]
That was my expectation. This issue is for tracking the things we do need to handle ourselves, such as dynamic-update-slice, not the TOSA->linalg->codegen path.

**Comment by silvasean** [comment]
TOSA -> linalg on tensors might make this task effectively a no-op (depending on the sequencing of that landing)

**Comment by benvanik** [comment]
There are still ops we need to support here, like dynamic-update-slice and variable updates.

**Comment by benvanik** [comment]
I don't think we want this anymore and instead will just be relying on linalg-on-tensors as our input.
