### ISSUE TITLE
Get a standard TFLite Android demo application coded against either the C API or JNI running.

### ISSUE THREAD

**Issue by benvanik** [google/iree#3954]
They have an image classifier [demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo) / [info](https://www.tensorflow.org/lite/performance/gpu#demo_app_tutorials) known to work with the GPU models that we will be trying.

It uses their [JNI wrapper](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/native/nativeinterpreterwrapper_jni.cc) that we can rip up to start as they include delegates and stuff whereas we just want something that uses the C API.

I think for the sprint we can just fork the whole demo + it's config into experimental/ (changing [some things](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/demo/app/src/main/res/drawable-xxhdpi/logo.png) of course ;).

Once we can use vcpkg to build an AAR it'll be much easier to get demos like this stood up, but until then we can just hack the build until it works.

**Comment by ScottTodd** [comment]
How do we feel about putting Android app code in IREE's `experimental/` vs creating a dedicated `iree-samples` repository? The Android file paths can get pretty long :P

**Comment by benvanik** [comment]
I think ideally long-term samples live in their own repo so they can be versioned and don't turn into a monorepo - so google/iree-samples-android/ would have all the copies of gradle jars and icons and xml files and source model files and crap, not our main repo. Short term a single demo could live in google/iree/experimental/, but I'd almost prefer saying that it lives in scotttodd/iree-android-tflite-demo-mumble/ and is something we link to until we want to formalize that. Be agile and such. Even short term we probably shouldn't be in the business of having tflite-based android demos in our repo, and experimental/ would just be for collaboration if it was helpful.

**Comment by ScottTodd** [comment]
Agreed. cc @not-jenni + @KoolJBlack

**Comment by antiagainst** [comment]
I think someday we should have an IREE GitHub organization for hosting various projects. ;-P

**Comment by ScottTodd** [comment]
Done at https://github.com/not-jenni/iree-android-tflite-demo, will move to https://github.com/google/iree-samples soon.
