### ISSUE TITLE
Get command line for tflite flatbuffer (binary and/or json) -> IREE

### ISSUE THREAD

**Issue by benvanik** [google/iree#3970]
Whatever we need to do it should be documented in the `bindings/tflite/README.md` and done as part of a build step in `bindings/tflite/testdata/` for the add.bin/json used in their smoke test.

**Comment by ScottTodd** [comment]
Done with https://colab.research.google.com/github/google/iree/blob/main/colab/tflite_text_classification.ipynb and https://google.github.io/iree/ml-frameworks/tensorflow-lite/.
