### ISSUE TITLE
Setup compiler backend for producing wasm32 + simd executables

### ISSUE THREAD

**Issue by benvanik** [google/iree#4019]
I suspect we will be able to reuse a majority of the LLVM AOT infra for producing the wasm32 binaries: it's just an LLVM target arch/format.

The WAMR examples compile with LLVM with `--target=wasm32-wasi -msimd128`. That should give us a .wasm file (vs. a .dll or .so) we can embed in a wasm flatbuffer (along with the reflection information) or reference as a file.

**Comment by ScottTodd** [comment]
I've started on this. I have a `WasmLinkerTool` that finds `wasm-ld` and is able to link _something_ with `-iree-llvm-target-triple=wasm32-unknown-unknown`. Will need to try out some flags and peek at what it generated to see if the output is usable.

**Comment by benvanik** [comment]
ooo cool! I think I played with adding a wamr submodule once; didn't get far though :P 
![image](https://user-images.githubusercontent.com/75337/107109929-aef87180-67f8-11eb-93d5-72d7d408b90e.png)

**Comment by ScottTodd** [comment]
The wasm executables we can produce now are usable. Here's a prototype proving that we can call into them and read back the expected outputs using [WAMR](https://github.com/bytecodealliance/wasm-micro-runtime), which I'll be integrating into IREE's HAL (tracked in other issues): https://gist.github.com/ScottTodd/4d01f92c434e6caebf1bf2b180f02840.

I haven't looked into simd codegen or runtime support yet, and there is still some room for tweaking flags (`--allow-undefined` in particular).
