### ISSUE TITLE
VMLA raises INVALID_ARGUMENT errors on mhlo that passes on Vulkan-SPIRV

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#4065]
There are two similar errors that VMLA raises when executing MLIR generated by the tensorflow integrations. This issue affects both the python test runner and `iree-run-mlir`. MLIR files and instructions for reproducing the errors with `iree-run-mlir` are linked below.

### `tf.math.mod` (and others) with dynamic shapes

VMLA [passes for input tensors up to rank 5](https://gist.github.com/phoenix-meadowlark/546e88ca20781f1ed1e23d84a1c0d1e4), but [fails for input tensors of rank 6 or higher](https://gist.github.com/phoenix-meadowlark/90c4c764748616f87c8ab9e0c10904f7).

There isn't an example of vulkan passing for this IR because its dynamic shape support isn't there yet.

```
E iree/hal/host/inproc_command_buffer.cc:244] DeviceQueue failure while executing command; permanently failing all future commands: iree/hal/host/serial/serial_command_processor.cc:119: INVALID_ARGUMENT; Push constants out of range
E iree/tools/iree-run-mlir-main.cc:474] Failure for split at line #1: INVALID_ARGUMENT; while invoking C++ function hal.ex.submit_and_wait; while calling import; Evaluating export function 2; Evaluating functions
ERROR running file (/tmp/iree/modules/tf/math/mod/dynamic_dims_non_complex/iree_input.mlir): INVALID_ARGUMENT; while invoking C++ function hal.ex.submit_and_wait; while calling import; Evaluating export function 2; Evaluating functions
```

### KWS Streaming `lstm` (and others) in non-streaming mode

In this case [Vulkan passes but VMLA fails](https://gist.github.com/phoenix-meadowlark/a1cc70f8d5214a19e84bc727016ab59b).

```
E iree/hal/host/inproc_command_buffer.cc:244] DeviceQueue failure while executing command; permanently failing all future commands: iree/hal/vmla/op_module.cc:170: INVALID_ARGUMENT; Invalid binding set=0, binding=33
E iree/tools/iree-run-mlir-main.cc:474] Failure for split at line #1: INVALID_ARGUMENT; while invoking C++ function hal.ex.submit_and_wait; while calling import; Evaluating export function 2; Evaluating functions
ERROR running file (/tmp/iree/modules/kws_streaming/lstm/non_streaming/iree_input.mlir): INVALID_ARGUMENT; while invoking C++ function hal.ex.submit_and_wait; while calling import; Evaluating export function 2; Evaluating functions
```

That Vulkan is passing suggests that this a bug in VMLA and not higher in the stack, at least in the latter case.

**Comment by ScottTodd** [comment]
Obsolete?

**Comment by benvanik** [comment]
vmla doesn't exist, so I'd say yes :)
