### ISSUE TITLE
Adapt MHLO to Linalg on buffers patterns to be MHLO to Linalg on tensors

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#4079]
Currently there are patterns in `HLOToLinalgOnBuffersPass` that convert MHLO ops to Linalg ops on buffers. These are ops that when converted to Linalg contain `reduction` iterator types. With the Linalg on tensors work, there needs these patterns need to be adapted to target Linalg on tensors and move these patterns to MHLO repository.

This would be required for #1354

**Comment by hanhanW** [comment]
All the patterns have been moving to tensors.

- TorchIndexSelect: #3578
- Dot/Matmul: https://github.com/tensorflow/mlir-hlo/commit/8f58f844e5c2405068eab6e886bcb1c73bced57f
- DotGeneral/BatchMatmul: https://github.com/tensorflow/mlir-hlo/commit/300a7c11ce9614f53826870ad6ac415b837ba5e9
- Reduce: https://github.com/tensorflow/mlir-hlo/commit/30ce82790d4ffef48f70e99a6f96f13ddbe857d8 
- Slice: #4611 https://github.com/tensorflow/tensorflow/commit/82c7c6525e91
- Pad: #4806
- Concatenate: #4954
- Normal convolution: #4748
  - Cleanup for normal convolution: #4973 #4972
- Depthwise convolution: #4991 #4941
- Pooling ops: #5000 #5024

**Comment by antiagainst** [comment]
This is fantastic! Thanks Hanhan for all the hard work of porting them over!!

**Comment by stellaraccident** [comment]
Yes - this is fantastic. Thank you for all of the hard work!
