### ISSUE TITLE
Identify function call trees worth deferring for cellular batching

### ISSUE THREAD

**Issue by benvanik** [google/iree#41]
Possibly just op+shape-based to start and only around the core expensive dispatches.

Input:
```mlir
  iree_hl_seq.dispatch[...](...) {
  // giant matmul
}
```

Deferred:
```mlir
  iree_hl_seq.deferred_call @outlined_dispatch(...);
...
func @outlined_dispatch(...) {
  iree_hl_seq.dispatch[...](...) {
    // giant matmul
  }
}
```

**Comment by benvanik** [comment]
`iree_hl_seq`

![unnamed](https://user-images.githubusercontent.com/75337/99891933-47cd1700-2c24-11eb-98f1-72bc0df15ef1.jpg)

**Comment by benvanik** [comment]
Cellular batching concepts are better tracked on a longer-term roadmap for the next quarter or two.

**Comment by mollon650** [comment]
What code is relevant to this issue @benvanik
