### ISSUE TITLE
LLVM FileCheck usage in Bazel and CMake build

### ISSUE THREAD

**Issue by marbre** [google/iree#411]
Whereas in Bazel build `FileCheck` is compiled from source, the CMake configuration of **benchmark** already adds 
```cmake
find_program(LLVM_FILECHECK_EXE FileCheck)
```
and thus makes an *external* `FileCheck` binary available. So far IREE requires LLVM for compilation, so one could assume that `FileCheck` is available anyway. Either one could switch to the system's `FileCheck` executable in the Bazel build or one needs to compile `FileCheck` in the CMake build.

**Comment by marbre** [comment]
@stellaraccident May I ask for your opinion?

**Comment by stellaraccident** [comment]
Hmm, I'm not sure I have a strong opinion. Most of what was done around lit testing in the bazel side was lifted from Google upstream and has not had a lot of scrutiny in terms of OSS needs. As such in general, I wouldn't consider any of this as done for a reason.

For the CMake side, it would be good to follow whatever pattern LLVM sets out for this. Iirc, it allows for both installed and in-tree builds of FileCheck.

**Comment by marbre** [comment]
We're building FileCheck from source in the CMake build, reproducing the Bazel way for now.
