### ISSUE TITLE
CMake builds a Debug build by default

### ISSUE THREAD

**Issue by marbre** [google/iree#412]
Might a Release build be preferable as default? @GMNGeoffrey Maybe at least for the build pipeline?

**Comment by marbre** [comment]
@GMNGeoffrey Gentle ping.

**Comment by GMNGeoffrey** [comment]
Whoops, thanks for the ping: I did indeed forget about this :-)

I think release mode probably does make more sense. Internally we usually have our CIs build with both [fastbuild and opt](https://docs.bazel.build/versions/master/user-manual.html#flag--compilation_mode). They're largely the same, but you want to make sure your build also works for the optimized build you might expect in production (e.g. after stripping asserts). For CI, fastbuild is nice since you usually want the build to be fast :-P

It looks like CMake doesn't really have an equivalent, but I'm guessing generating debug symbols takes more time than the extra optimization from release? Probably we should eventually test both.

Right now the bazel build defaults to optimized mode, which I assume is analogous to release in CMake (https://github.com/google/iree/blob/9dd6c66e5fb86e0d1e91a711b4bfdabd9f8d66f0/.bazelrc#L23). I think it makes sense for these to be the same (doesn't seem like there's a strong reason why they should be different). Please feel free to send a PR to update the default.

**Comment by marbre** [comment]
CMake normaly defines the [CMAKE_BUILD_TYPE](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) `DEBUG`, `RELEASE`,  `RELWITHDEBINFO` and `MINSIZEREL`. These look as follows (copied from CMakeCache.txt generated locally for the IREE build):
```cmake
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
```
So one option is to set a release build as default and build it in the pipeline as well. It should be also possible to introduce a new build type  FASTBUILD with flags `-gmlt -Wl,-S`. This could be configured with `-DCMAKE_BUILD_TYPE=fastbuild` in the CMake build pipeline, whereas a release build is still set as the default in the CMakeLists.

**Comment by GMNGeoffrey** [comment]
Oh nice, I didn't think to copy from the local cache to find the actual flags :-D

I kind of like the idea of adding a fastbuild option, but I don't think it's the highest priority for now (unless you think it will make things fast enough that we can get the CMake build under 10 minutes without resorting to something like goma). We're not even using the actual built-in fastbuild in the bazel CI. For now let's just switch the default to release to match the bazel config.

**Comment by marbre** [comment]
Okay, this was actually a little bit more tricky than I expected. LLVM does not allow a custom build type. Hence, if the build type is set to `FastBuild`, LLVM is build as `Release`. In the other cases, the build type is propagated to LLVM.

It seems there is still a difference between the Bazel and the CMake world. To cite the [documentation](https://github.com/google/iree/blob/master/docs/getting_started_on_linux.md#build)

```
# Or build with optimizations disabled (just for IREE, not for deps) and
# debug symbols retained. This assumes you have an alias like above setup):
bazel test --config=debug bindings/python/...
```
Bazel builds IREE with debug symbols on, but this does not affect the dependencies. Thus, we have the following options:
1. * Build all targets according to IREE's *global* `CMAKE_BUILD_TYPE`
2. * Respect the defaults of the subprojects, e.g. for LLVM this is `Debug`
3. * Set `CMAKE_BUILD_TYPE` to `Release` for all subprojects

So far, #474 implements option 1.

**Comment by stellaraccident** [comment]
On Tue, Jan 14, 2020 at 7:44 AM Marius Brehler <notifications@github.com>
wrote:

> Okay, this was actually a little bit more tricky than I expected. LLVM
> does not allow a custom build type. Hence, if the build type is set to
> FastBuild, LLVM is build as Release. In the other cases, the build type
> is propagated to LLVM.
>
> It seems there is still a difference between the Bazel and the CMake
> world. To cite the documentation
> <https://github.com/google/iree/blob/master/docs/getting_started_on_linux.md#build>
>
> # Or build with optimizations disabled (just for IREE, not for deps) and
> # debug symbols retained. This assumes you have an alias like above setup):
> bazel test --config=debug bindings/python/...
>
>
This is just a bow to development pragmatism and not load bearing: I often
find it faster (to link, etc) to be surgical in the parts of the build
graph that are in what mode. But this is more relevant when combined with
mammoth deps like TensorFlow as it lets you flip debug on for parts of the
project without rebuilding everything. We can skip such incantations on the
cmake side or figure out later how to reach similar ends.

>  Bazel builds IREE with debug symbols on, but this does not affect the
> dependencies. Thus, we have the following options:
>
>    1.
>       - Build all targets according to IREE's *global* CMAKE_BUILD_TYPE
>    2.
>       - Respect the defaults of the subprojects, e.g. for LLVM this is
>       Debug
>    3.
>       - Set CMAKE_BUILD_TYPE to Release for all subprojects
>
> So far, #474 <https://github.com/google/iree/pull/474> implements option
> 1.
>
Option 1 seems fine for now. I'm not sure I have enough mileage on it to
have a stronger opinion.

**Comment by marbre** [comment]
> Option 1 seems fine for now. I'm not sure I have enough mileage on it to have a stronger opinion.

Okay in that case `FastBuild` will also be propagated to all subprojects (except for LLVM, which is build as `Release`) and so far no further changes than the ones in #474 are necessary.

**Comment by GMNGeoffrey** [comment]
So based on #474 it looks like the CMake Release build is actually slower than the Debug build. Maybe we should default to fastbuild? Stella, what was the rationale for defaulting the bazel build to opt? It can be necessary for python stuff, but fastbuild is usually a reasonable compromise I think

**Comment by GMNGeoffrey** [comment]
Well at least one good answer to the above: switching to bazel fastbuild with our current CI doesn't work: https://source.cloud.google.com/results/invocations/ab35437b-2c6d-4451-bc8d-eed7f714da2b/targets

**Comment by stellaraccident** [comment]
Numeric systems like this are nearly unusable without optimizations
enabled, so I usually split the difference to do optimizations by default
with asserts+debug info. Without doing that, you can quickly find that you
get a slightly faster build but your tests take 10-100x longer.

There's nothing sacred about it. If you can make it faster a different way
and that helps, feel free.

**Comment by marbre** [comment]
With #474 merged, this issue is resolved.
