### ISSUE TITLE
keyword_spotting_tests failing LLVM backend

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#4141]
Repro:

```
 bazel run //integrations/tensorflow/e2e/keras:keyword_spotting_tests__model__att_mh_rnn__target_backends__iree_llvmaot
```

*** END MANGLED STACK TRACE ***

*** Begin stack trace ***
        tensorflow::CurrentStackTrace()

        call_ex_dispatch_34
*** End stack trace ***

**Comment by ScottTodd** [comment]
Pretty sure this is obsolete. I enabled more of the keyword_spotting_tests yesterday, and all the current failures appear to be upstream of IREE (in the python source or in the TF->MLIR lowering): https://github.com/google/iree/commit/a3cb661e32b52aa0c608b416a5ec29fbe67b977a
