### ISSUE TITLE
integrations/tensorflow/e2e/ is broken by f46827372

### ISSUE THREAD

**Issue by bjacob** [google/iree#4169]
Commit f46827372 seems to have broken a lot of 'e2e' stuff:

```shell
$ CC=clang CXX=clang++ python3 ./scripts/get_e2e_artifacts.py --test_suites=e2e_tests
Running: `bazel test //integrations/tensorflow/e2e:e2e_tests --color=yes`
ERROR: /usr/local/google/home/benoitjacob/iree/integrations/tensorflow/e2e/BUILD:164:20: no such package 'third_party/py/pyiree': Package is considered deleted due to --deleted_packages and referenced by '//integrations/tensorflow/e2e:e2e_tests__control_flow_test__target_backends__tflite'
```

Commit f46827372 changed the dependency here to a path `third_party/py/pyiree` that never existed according to
```shell
 git log --full-history -- third_party/py/pyiree/
```

I tried to fix this but there are now dependencies on things that don't have a Bazel `BUILD`. At least, there is no `BUILD` in `bindings/python/pyiree/compiler2/`.

@stellaraccident @phoenix-meadowlark

**Comment by stellaraccident** [comment]
Actually integrations/tensorflow/e2e is no longer supported in bazel test anymore.

Looking at that script, there are a number of path changes needed. The biggest item is that it just runs the scripts directly and doesn't invoke bazel. The doc here is updated with build instructions (essentially add -DIREE_BUILD_PYTHON_BINDINGS=ON
-DIREE_BUILD_TENSORFLOW_COMPILER=ON to cmake).

I'm in a meeting right now but can have a look in a bit (if Phoenix doesn't get to it first).

**Comment by phoenix-meadowlark** [comment]
The `bazel` build of the integrations is deprecated. I _think_ you can still use the internal build for the time being as a stop-gap until we develop the tooling and coverage around the cmake side. I'll send out a PR that deleted deperacted scripts (like `get_e2e_artifacts.py`) and adds warnings to the docs until things are a bit more settled.

**Comment by stellaraccident** [comment]
If that specific script helps Benoit's workflow, then I can patch it vs delete it.

**Comment by stellaraccident** [comment]
Also, if you just want to extract artifacts from one of the scripts in the e2e directory, just:

* `export PYTHONPATH=$(realpath bindings/python) # from build directory`
* `python integrations/tensorflow/e2e/mobile_bert_squad_test --target_backends=iree_llvmaot --artifacts_dir=/tmp/foo`

**Comment by bjacob** [comment]
ah thanks! yes, that's exactly all I need.

**Comment by phoenix-meadowlark** [comment]
That script depends on the semantics we defined for `bazel` test suites, so patching it for CMake is contingent on recreating (a potentially modified version of) those semantics.

I think that deperication is the right move long term however because this script exists solely to abide by `bazel`'s opinions on hermetic tests, and it is strictly more complicated for the people using it than it needs to be.

**Comment by stellaraccident** [comment]
Ok - so if the above command lines unblock Benoit's work, maybe the right move is to say that a very simple script here would be fine but once you strip the bazel-isms from this one, there isn't much left.

**Comment by stellaraccident** [comment]
Also, Phoenix - it was an error that the integrations/tensorflow/e2e/BUILD files are still there (something got mixed up in the repo sync flow -- the intent was to delete them).

**Comment by bjacob** [comment]
Sorry, some more help needed! I tried this:

```
export PYTHONPATH=$(realpath bindings/python) # from build directory
```

But actually, my build dir does not contain any directory or file named either `bindings` or `python`. Did I need some special cmake variable to be set?

**Comment by bjacob** [comment]
nevermind, found it by reading the CMakeLists :-)
