### ISSUE TITLE
bazel_to_cmake script should be quieter by default

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#4282]
See sample output here: https://github.com/google/iree/runs/1591120079?check_suite_focus=true

It isn't immediately clear after running the script which "errors" are safe to ignore or which files were actually updated. We could add a new flag to https://github.com/google/iree/blob/main/build_tools/bazel_to_cmake/bazel_to_cmake.py like `--verbose` that includes the current output, then new quieter output could be of the form:

No-op success:
```
Success! 0 CMake file(s) were updated.
```

Success after changing files:
```
Updated iree/hal/CMakeLists.txt.
Updated iree/compiler/Dialect/IREE/IR/CMakeLists.txt.
Success! 2 CMake file(s) were updated.
```

That ^ would be most useful for everyday development:
1) edit `BUILD` file(s)
2) run script
3) check output

instead of currently:
1) edit `BUILD` file(s)
2) run script, see wall of scrolling text
3) check `git status` for list of files changed and hunt for CMake files

---

If we want to report errors:
```
Updated iree/hal/CMakeLists.txt.
Updated iree/compiler/Dialect/IREE/IR/CMakeLists.txt.
Uncaught exception: 
  <blah>
Error! 2 CMake file(s) were updated, with unexpected errors in updating 1 CMake file(s).
```

**Comment by GMNGeoffrey** [comment]
In addition here, it seems to be silently passing when it can't translate targets. That seems like something that only happens if we run it in permissive mode

**Comment by GMNGeoffrey** [comment]
Ok I remember why I haven't fixed this before. Python exception and warning propagation kind of sucks...
