### ISSUE TITLE
Using Iree page 404s

### ISSUE THREAD

**Issue by calewis** [google/iree#4290]
**Describe the bug**
The page https://google.github.io/using-iree which is linked from https://google.github.io/iree/get-started results in a page not found.

**Comment by ScottTodd** [comment]
Whoops! Looks like https://github.com/google/iree/blob/gh-pages/docs/get_started/index.md uses a dash where it should use an underscore.

**Comment by ScottTodd** [comment]
Well, that wasn't enough to fix unfortunately :(

**Comment by ScottTodd** [comment]
We do some funny stuff with underscores and hyphens:
https://github.com/google/iree/blob/4ca12072652be6785075e8e6e48052347f9de784/scripts/prepare_doc_publication.py#L175-L184

passing to @antiagainst :P

**Comment by benvanik** [comment]
oh, yeah, let's make those consistent (no rewriting) - either we rename the files or we allow underscores :)

**Comment by antiagainst** [comment]
:D Let's change the doc files to use hyphens then.

**Comment by ScottTodd** [comment]
I'm actually going to remove the https://google.github.io/iree/using-iree/using-colab page (custom setup is no longer needed to use Colab) and https://google.github.io/iree/using-iree until other docs are written there. We should still sort out the underscore/hyphen issue though :P
