### ISSUE TITLE
[build] Vulkan library should not be required

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#4371]
```
cmake -B ../iree-release . -CMAKE_INSTALL_PREFIX=../iree-install -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DPython3_EXECUTABLE=$(which python)
```

Results in (on a system without the Vulkan library):

```
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
-- Configuring incomplete, errors occurred!
```

This is only needed for samples. Building with `-DIREE_BUILD_SAMPLES=OFF` resolves it, but the detection should be automatic.

**Comment by marbre** [comment]
On one of my machines
```bash
cmake -B ../iree-release . -CMAKE_INSTALL_PREFIX=../iree-install -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 -DPython3_EXECUTABLE=$(which python3) -DIREE_BUILD_SAMPLES=OFF
```
doesn't work either, but dropping `-CMAKE_INSTALL_PREFIX=../iree-install` does the trick.

**Comment by stellaraccident** [comment]
That's a good clue. Unfortunately, I do need the install!

**Comment by antiagainst** [comment]
Shouldn't it be -**D**CMAKE_INSTALL_PREFIX?

**Comment by marbre** [comment]
> Shouldn't it be -**D**CMAKE_INSTALL_PREFIX?

Absolutely! **Good catch!** I simply copied the command from the issue description, but fixing the typo resolves the issue on my non-vulkan machine (no matter if `-DIREE_BUILD_SAMPLES=OFF` or `-DIREE_BUILD_SAMPLES=ON` is passed).

**Comment by ScottTodd** [comment]
Is there still an issue here? IIRC the `Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)` is innocuous and we should be handling that gracefully, even with `-DIREE_BUILD_SAMPLES=ON`. I think there was a different error (maybe from the `-DCMAKE_INSTALL_PREFIX`) elsewhere in the configure logs.

I'll close this for now, but please re-open if needed.
