### ISSUE TITLE
Create quick start samples using published Python packages

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#4389]
https://github.com/google/iree/releases

```
python -m pip install iree-compiler-snapshot iree-runtime-snapshot -f https://github.com/google/iree/releases/tag/snapshot-20210105.14
```

**Comment by ScottTodd** [comment]
cc @stellaraccident

**Comment by benvanik** [comment]
I think if you just point it at `-f https://github.com/google/iree/releases` it'll pull the latest snapshot, which would be good for the quickstart

**Comment by ScottTodd** [comment]
> I think if you just point it at `-f https://github.com/google/iree/releases` it'll pull the latest snapshot, which would be good for the quickstart

Depends on how stable the releases are. If they're grabbed twice daily from `main` then they _should_ be stable, but maybe that will take some time?

**Comment by benvanik** [comment]
It's a bug if main is green but the snapshot doesn't work and we want to hear about those so we can add proper coverage. I'd much rather have people using head (just as if they had checked it out and built it themselves at that moment) than some old revision until we have ordained releases/a schedule/etc.
