### ISSUE TITLE
Build pipeline/Documentation: Installation of numpy

### ISSUE THREAD

**Issue by marbre** [google/iree#441]
The build pipeline installs numpy via `sudo pip install numpy`, which is also mentioned in [Getting Started on Linux](https://github.com/google/iree/blob/master/docs/getting_started_on_linux.md). Is there a specific reason not to install numpy via from the package repository via `sudo apt-get install python3-numpy`? In Ubuntu 18.04, numpy 1.13.3 would be available from the [repository](https://packages.ubuntu.com/bionic/python3-numpy).

**Comment by stellaraccident** [comment]
No reason other than that worked for me when I wrote the doc :)

Feel free to update.
