### ISSUE TITLE
Switch gh-pages/docs to use Material for MkDocs

### ISSUE THREAD

**Issue by benvanik** [google/iree#4414]
This has all the features we want (including reusing the python markdown ecosystem, so we can modify it):
https://squidfunk.github.io/mkdocs-material/getting-started/

The setup for gh-pages is straightforward and we could even change it to happen only on successful release builds, if we wanted to only deploy docs when the release is green:
https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions

Various people have mentioned wanting something different from docs so getting switched to this as part of the reorganization would be a good idea as this gives us a lot more options for how to organize things. For example, we can use [content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/) to avoid the need for so many foo_windows.md and foo_android.md files. There may still be a few useful ones, but in combination with a focus on linking out to source documentation vs duplicating our own (like linking to [this](https://developer.android.com/ndk/guides/graphics/validation-layer) to setup vulkan debugging on android, etc) we can cut down on our non-IREE-related docs quite a bit. This will make them easier to navigate for users, reduce discrepancy (you can clearly see today which people working on which things use which platforms, as the platform-specific docs all have slight different callouts that could be shared), and make it easier to maintain a smaller set of higher quality docs (vs copypasta/forking as we have now).

**Comment by antiagainst** [comment]
Ooh, this one looks neat and also powerful. I love the tab feature. :)

**Comment by benvanik** [comment]
Yeah! It has search too, which will be super useful - right now it's easier to use crappy github search on our docs, and I never want to have to use github search :P
