### ISSUE TITLE
[CMake] iree-translate: Unknown command line argument '-iree-mlir-to-vm-bytecode-module'.

### ISSUE THREAD

**Issue by marbre** [google/iree#443]
In the current CMake build. the command `iree-translate -iree-mlir-to-vm-bytecode-module` fails. To call `iree-translate` with this option is required to build the sample `simple_embedding`. The dependencies defined in the Bazel configuration and in the CMake configuration differ, e.g. `//iree/compiler/Translation:IREEVM"` is included in the Bazel configuration. I assume the dialect is not registered. To add the latter dependcey further changes seem required. Hence, this is also related to #393.

To reproduce patches of #442 need to be applied and `add_subdirectory(simple_embedding)` needs to be enabled again.

**Comment by GMNGeoffrey** [comment]
Thanks for uncovering this Marius. @ScottTodd maybe you can take a look?

**Comment by ScottTodd** [comment]
Sure, I can add this to my list of CMake things to look at next week.
