### ISSUE TITLE
[macos] TensorFlow importer compilation failure (bad warning flag)

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#4448]
error: [0munknown warning option '-Wno-unused-but-set-parameter'; did you mean '-Wno-unused-parameter'? [-Werror,-Wunknown-warning-option]

https://pipelines.actions.githubusercontent.com/SaXEyjchYvnWH9Rq3qeZEPLXtO1Hv1A8b0nd0VWR5igNiKNAhf/_apis/pipelines/1/runs/41693/signedlogcontent/5?urlExpires=2021-01-09T01%3A05%3A48.4711770Z&urlSigningMethod=HMACV1&urlSignature=b0hOWSpOYavAkECMUCrhc9zLVvfbPX24e9tj2xMwhpk%3D

**Comment by stellaraccident** [comment]
Me-thinks the answer is an additional flag: -Wno-unknown-warning-option

**Comment by freedomtan** [comment]
I think `-Wno-unused-but-set-parameter` is only enabled by `generic-gcc`. I think on macos, `generic-clang` should be used instead of `generic-gcc` if you don't have "real gcc"  installed.

**Comment by stellaraccident** [comment]
Indeed. The compiler was being mis-identifier: `Did not recognize C++ compiler AppleClang.  Configuring bazel for gcc mode`
