### ISSUE TITLE
Bulding static libraries with position independent code

### ISSUE THREAD

**Issue by marbre** [google/iree#451]
CMake builds without `-fPIC` by default, but position independent code is required for the python bindings, among other things. For example, abseil is build without position independent code. For the abseil dependencies this can be solved by changing the CMake configuration to
```cmake
set(CMAKE_POSITION_INDEPENDENT_CODE TRUE)
add_subdirectory(third_party/abseil-cpp EXCLUDE_FROM_ALL)
set(CMAKE_POSITION_INDEPENDENT_CODE FALSE)
```
However, position independent code is also required for some other components. Is there any argument not to set this for the whole project?

**Comment by GMNGeoffrey** [comment]
@stellaraccident any reason we shouldn't turn this on everywhere?

**Comment by stellaraccident** [comment]
No reason. Imo, we should always build with `-fPIC` and leave it to the (largely hypothetical at this point) outlier platforms who care to make a different decision if needs be.
