### ISSUE TITLE
cmake-bazel turing build is not actually using turing

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#4514]
This build is supposed to be testing using a real GPU, but it does not launch the docker container with `--gpus all` which means it's not. This explains our great confusion why it didn't start failing like the cmake build because of #4507 (@antiagainst FYI).

https://github.com/google/iree/blob/1cdc99d5d8ac13152f3ba893cbe5b397240b5319/build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build_kokoro.sh#L39-L41

I don't know how these tests are passing. Are we actually testing vulkan at all? Does the container also have swiftshader for some reason? We should probably avoid having swiftshader in the docker container that we're intending for real GPU builds precisely so it doesn't mask this sort of issue.

**Comment by stellaraccident** [comment]
I know nothing about kokoro, and this is puzzling because bazel doesn't (or shouldn't) actually run any tests. Not sure what is going on here...

**Comment by phoenix-meadowlark** [comment]
> Does the container also have swiftshader for some reason? 

Confirmed that `gcr.io/iree-oss/cmake-bazel-tensorflow-swiftshader` doesn't have swiftshader installed (at least not where we install it in any of the `-swiftshader` images).

**Comment by GMNGeoffrey** [comment]
> I know nothing about kokoro, and this is puzzling because bazel doesn't (or shouldn't) actually run any tests. Not sure what is going on here...

Bazel isn't running any tests. The build is just called "cmake-bazel" because it uses both cmake and Bazel. CMake should be invoking those tests I thought and it appears to not actually be exercising the vulkan tests at all.

> Confirmed that gcr.io/iree-oss/cmake-bazel-tensorflow-swiftshader doesn't have swiftshader installed 

You mean gcr.io/iree-oss/cmake-bazel-tensorflow-*nvidia* ? Or also the swiftshader one?

**Comment by GMNGeoffrey** [comment]
This actually doesn't have much to do with Kokoro. It's just docker with GPU drivers (which is real complicated in its own right)

**Comment by GMNGeoffrey** [comment]
Wait it's even worse. The build is using the wrong image:

https://source.cloud.google.com/results/invocations/5ae543c0-b0c4-4f4d-83bd-b17803552750/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-turing%2Fmain/log

> docker run --volume=/tmpfs/src/github/iree:/tmpfs/src/github/iree --workdir=/tmpfs/src/github/iree --rm --user=1003:1004 --volume=/tmpfs/fake_etc/group:/etc/group:ro --volume=/tmpfs/fake_etc/passwd:/etc/passwd:ro --volume=/tmpfs/fake_home:/home/kbuilder --volume=/home/kbuilder/.config/gcloud:/home/kbuilder/.config/gcloud:ro gcr.io/iree-oss/cmake-bazel-tensorflow-swiftshader@sha256:9b000bf74bebc4f3dfd967d54ba6138e312771ebafe0a1a5c5856b668b490129 build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-**swiftshader**/build.sh

https://github.com/google/iree/blob/1cdc99d5d8ac13152f3ba893cbe5b397240b5319/build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/common.cfg#L17 points to the wrong file

I'm going to disable this continuous build until this gets sorted out. Everything it's actually testing is covered by the swiftshader test except this one takes way longer and uses an expensive real GPU. You can still manually trigger presubmits (as before), so testing the fixes for this shouldn't be hampered, but we won't be falsely reporting that things are passing on real GPUs.

**Comment by stellaraccident** [comment]
Well, that is worse, but at least resolves the mystery.

**Comment by GMNGeoffrey** [comment]
Assuming that Phoenix did have a typo in the earlier comment and the swiftshader image isn't also missing swiftshader :-P

We can revert https://github.com/google/iree/commit/55a657adb401504221531d877741ebe1524ae887 (removing build badge from the readme) when this is fixed

**Comment by GMNGeoffrey** [comment]
> Well, that is worse, but at least resolves the mystery.

Yeah there's a lot of that going around right now (#4507). Better to have a bad thing you know than something you just don't understand at all. I think fixing this should just be a few edits (assuming the tests haven't started failing on real GPUs in the meantime):

1. Add `--gpus all` when invoking `docker run`
2. Use the correct path in that build file

Also I just read over my posts here and feel like the tone is grumpy/accusatory, for which I'd like to apologize. Today has been a series of totally mysterious issues mostly related to Nvidia drivers and I'm grumpy about it. That isn't an excuse though, so sorry if I made anyone else's day worse :hugs:

**Comment by stellaraccident** [comment]
I didn't take any of it that way, and no worries if you were a bit grumpy. I've been biting my tongue for days now. A lot of that at just this moment.

**Comment by phoenix-meadowlark** [comment]
> You mean gcr.io/iree-oss/cmake-bazel-tensorflow-nvidia ? Or also the swiftshader one?

That's an unfortunate typo 😅 But yes I meant the `-nvidia` image. At least as it was when I built it last.

**Comment by GMNGeoffrey** [comment]
> > You mean gcr.io/iree-oss/cmake-bazel-tensorflow-nvidia ? Or also the swiftshader one?
> 
> That's an unfortunate typo  But yes I meant the `-nvidia` image. At least as it was when I built it last.

whew :relieved: 

Phoenix, could you make the updates to get this testing the thing it should be testing and run the presubmits to confirm it's still passing? Then we can turn the cbuild back on
