### ISSUE TITLE
Run MNIST Colab notebook

### ISSUE THREAD

**Issue by marbre** [google/iree#453]
Should I be able to run the `colab/mnist_tensorflow.ipynb` notebook (non locally)? Seems that the IREE deps at the remote site are not up-to-date:
```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-4-4524f39e0a49> in <module>()
      3 import tensorflow as tf
      4 from matplotlib import pyplot as plt
----> 5 from pyiree import compiler as ireec
      6 from pyiree import rt as ireert
      7 

ModuleNotFoundError: No module named 'pyiree'
```

**Comment by marbre** [comment]
Or with other words, if IREE is not in Colaboratory by default (which I assume), is there an *easy* way to get it installed?

**Comment by ScottTodd** [comment]
cc @stellaraccident

At the moment you'll need a local runtime, launched using `start_colab_kernel.py` with a working Bazel development environment to run any of the Colab notebooks yourself.

There are a few ways we can make that simpler in the future:

* Publish IREE's python bindings as packages on pip, install on-demand in the notebooks using `pip install`
* Host our own runtimes (not sure how feasible this would be with public notebooks)
* Publish a docker image (see #15) with our dependencies and up to date IREE python bindings 

I think the first option (publishing on pip) will make the most sense in the long term. While code is still changing frequently, maybe the docker image approach would be preferred (as an alternative to setting up Bazel). GPU and Vulkan driver availability and/or SwiftShader use may complicate each of these options.

**Comment by marbre** [comment]
Thanks for clarification. I think adding a one-liner to [README.md]( https://github.com/google/iree/blob/master/colab/README.md) might be useful.

**Comment by ScottTodd** [comment]
Sure, I'll add some notes to the docs.
