### ISSUE TITLE
Executable linking produces executables with multiple layouts but runtime does not support that

### ISSUE THREAD

**Issue by benvanik** [google/iree#4536]
`-iree-hal-link-executables` will create an executable (in LLVM & VMLA) that has multiple interfaces and these then map to multiple executable layouts that are required during binding/dispatch. This doesn't match up with the executable creation semantics which take only a single executable layout - meaning that if the executable layout passed during creation is actually used things get .... weird.

Probably need to change executable creation to take multiple layouts. I've been meaning to change that API for awhile anyway and see if we can make it something a bit more sensible for batch compilation too.

For example, today:
```c
iree_hal_executable_cache_prepare_executable(cache, executable_layout, caching_mode, executable_data, ...);
```

Simple fix:
```c
iree_hal_executable_cache_prepare_executable(cache, caching_mode, executable_data, executable_layout[], ...);
```

Future async coolness:
```c
iree_hal_executable_cache_prepare_executables(cache, caching_mode, executable_data, executable_layout[], signal_semaphore, ...);
```

**Comment by ScottTodd** [comment]
<sub>Just leaving some breadcrumbs for anyone (like us months later) following along...</sub>

* We also discussed this on Discord [here](https://discord.com/channels/689900678990135345/689906000043573354/799704324611375217)
* [This issue comment](https://github.com/google/iree/issues/1587#issuecomment-704438782) first spotted the issue and bounced around some ideas
* [This commit](https://github.com/ScottTodd/iree/commit/bce1bea578a055fb1d85de417d5bd2afbadcb670) on a local branch attempted to work around / fix this limitation
