### ISSUE TITLE
CMake local build failure "interpreter_module_def_generated.h file not found"

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#455]
The default CMake build no longer runs on my machine :-(

The CI is still passing fine though, so this is presumably an environment issue. Posting here for tracking and in case anyone else encounters the issue or happens to know the cause. I'll investigate this more later.

```shell
$ ./build_tools/scripts/cmake_build.sh
...
Scanning dependencies of target iree_hal_interpreter_interpreter_command_processor
[ 25%] Building CXX object iree/hal/interpreter/CMakeFiles/iree_hal_interpreter_interpreter_command_processor.dir/interpreter_command_processor.cc.o
In file included from /usr/local/google/home/gcmn/git/iree-fork/iree/hal/interpreter/interpreter_command_processor.cc:23:
In file included from /usr/local/google/home/gcmn/git/iree-fork/iree/hal/interpreter/bytecode_executable.h:25:
/usr/local/google/home/gcmn/git/iree-fork/iree/hal/interpreter/interpreter_module.h:30:10: fatal error: 'iree/schemas/interpreter_module_def_generated.h' file
      not found
#include "iree/schemas/interpreter_module_def_generated.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [iree/hal/interpreter/CMakeFiles/iree_hal_interpreter_interpreter_command_processor.dir/build.make:63: iree/hal/interpreter/CMakeFiles/iree_hal_interpreter_interpreter_command_processor.dir/interpreter_command_processor.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:25474: iree/hal/interpreter/CMakeFiles/iree_hal_interpreter_interpreter_command_processor.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by marbre** [comment]
Missing dep on iree::hal::interpreter::bytecode_executable. PR will follow in a few minutes.

**Comment by marbre** [comment]
interpreter_command_processor missed a dep on bytecode_executable, which itself depends on iree::schemas::interpreter_module_def_cc_fbs. So adding the missing dep should (at least fix) this issue. Seems that further deps in the Bazel configuration had changed, gave it a quick try to adopt it. If I missed something and you wan't to dig in, feel free to take over the changes in the branch associated with my PR.

**Comment by marbre** [comment]
Ah, I further reordered deps to the same order used in the Bazel configration, making it easier to check manually, till we have some automated process for this.

**Comment by GMNGeoffrey** [comment]
Oh I assumed this was something with my environment since it wasn't showing up in the CI build. Argh it seems this is once more a version thing. I tried it out with cmake 3.12 and now it succeeds.

**Comment by marbre** [comment]
Actually, it should have also failed with newer CMake versions. Seems more like a race condition, meaning the target `iree::schemas::interpreter_module_def_cc_fbs` was already build and thus the header file was present.

**Comment by GMNGeoffrey** [comment]
Ah gotta love race conditions in the build system!
