### ISSUE TITLE
vkDestroySemaphore that is currently in use

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#4633]
```
308: E /project/main_checkout/iree/hal/vulkan/debug_reporter.cc:40] Cannot call vkDestroySemaphore on VkSemaphore 0x28d500000028d5[] that is currently in use by a command buffer. The Vulkan spec states: All submitted batches that refer to semaphore must have completed execution (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroySemaphore-semaphore-01137)
```

Steps to repro: 

* Download the Linux release (https://github.com/google/iree/releases/download/snapshot-20210127.63/iree-dist-snapshot-20210127.63-linux-x86_64.tar.xz)
* Extract and cd into `tests` directory
* `sed -i 's|/project/main_checkout/||' CTestTestfile.cmake` (see #4632 )
* `export PATH=$(realpath ../bin):$(realpath bin):$PATH`
* `ctest -j 32 -V`

Note that tests pass but this message is spammed continuously for any of them that use the GPU.

Vulkan info:

```
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.126

Device Properties and Extensions:
=================================
GPU0:
VkPhysicalDeviceProperties:
---------------------------
	apiVersion     = 4202641 (1.2.145)
	driverVersion  = 83894276 (0x5002004)
	vendorID       = 0x8086
	deviceID       = 0x5917
	deviceType     = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName     = Intel(R) UHD Graphics 620 (KBL GT2)
```

**Comment by ScottTodd** [comment]
I don't see that `vkDestroySemaphore` validation layer warning on my Windows machine with relatively up-to-date validation layers 

```
λ vulkaninfo | grep validation
VK_LAYER_KHRONOS_validation (Khronos Validation Layer) Vulkan version 1.2.162, layer version 1:
                VK_EXT_validation_features : extension revision 2
                        VK_EXT_validation_cache : extension revision 1
```

I do see this warning with `mnist_fake_weights.mlir` and `edge_detection.mlir` (and maybe others)

> 51: E D:\dev\projects\iree\iree\hal\vulkan\debug_reporter.cc:40] Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-00331 ] Object 0: handle = 0x5d11410000000004, type = VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT; | MessageID = 0xde8c9ed7 | vkCmdPushDescriptorSetKHR() failed update validation: Write update to Push Descriptors defined with VkDescriptorSetLayout 0x5d11410000000004[] binding #1 failed with error message: Attempted write update to buffer descriptor failed due to: Buffer (VkBuffer 0xcc0459000000001c[]) with usage mask 0x3 being used for a descriptor update of type VK_DESCRIPTOR_TYPE_STORAGE_BUFFER does not have VK_BUFFER_USAGE_STORAGE_BUFFER_BIT set.. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_STORAGE_BUFFER or VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC, the buffer member of each element of pBufferInfo must have been created with VK_BUFFER_USAGE_STORAGE_BUFFER_BIT set (https://vulkan.lunarg.com/doc/view/1.2.162.0/windows/1.2-extensions/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00331)

**Comment by ScottTodd** [comment]
I suspect the Vulkan SDK and validation layers are ancient on that machine since `Vulkan Instance Version: 1.1.126` + `apiVersion     = 4202641 (1.2.145)`. Earlier validation layers had some false positives (see [these issues](https://github.com/KhronosGroup/Vulkan-ValidationLayers/search?q=timeline+semaphore&type=issues)) with timeline semaphores.

**Comment by benvanik** [comment]
The descriptor set ones are expected (we are legit not tracking the usage correctly ---- soooon~~).

**Comment by ScottTodd** [comment]
Closing this as obsolete. I think updating validation layers would have made that warning go away.
