### ISSUE TITLE
Dynamically load the CUDA runtime when available.

### ISSUE THREAD

**Issue by benvanik** [google/iree#4653]
ala the Vulkan HAL, using #4642. Can probably start as a copy of https://github.com/tensorflow/tensorflow/commit/e0d156b3bfef7388b31b35793a2add7b0a5fab6d#diff-cf221cdcf67efb2d297b724f35f535c6a9fd649728f67851ac890583c6831936R67-R131

**Comment by benvanik** [comment]
There's also:
https://github.com/tensorflow/tensorflow/blob/8100f8c782e5c5eb9f876d7e0cb4eff78478ff8d/tensorflow/stream_executor/cuda/cuda_stub.cc
https://github.com/tensorflow/tensorflow/blob/8100f8c782e5c5eb9f876d7e0cb4eff78478ff8d/tensorflow/stream_executor/cuda/cuda_runtime_11_2.inc

it's a bit sketchier as we won't be running any of this through nvcc and don't need those __host__ attributes - just a lot of boilerplate that could drift.

**Comment by ThomasRaoux** [comment]
The patch below makes it work pretty easily (highly inspired from the first patch you pointed in tensorflow)
https://github.com/ThomasRaoux/iree/commit/8a93ef5c459d08cc8783be6dfcb73c9b925ab93b#diff-cc3c58d02e4d14191c5d3439f7ce37e75e1b04063f648440cdbcd13af6fb946b
