### ISSUE TITLE
Getting Started `Linux with CMake` Documentation Errors

### ISSUE THREAD

**Issue by ewconnell** [google/iree#4667]
I was trying out IREE *Getting Started* and ran into problems.

The file `simple.mlir` has recently been split/renamed, so the current instructions are incorrect. Also in the `LLVM Ahead-of-Time (AOT) backend` section, references to `./build` should be `../iree-build` to be consistent with previous paragraphs.

**Comment by ScottTodd** [comment]
After https://github.com/google/iree/commit/32b3101ba74d0283b49304d1e8062ba9a2db2585, I think we should have a new set of sample files. My concern with directly using the new files like https://github.com/google/iree/blob/main/iree/tools/test/iree-run-module.mlir is that they aren't named to be obviously simple test cases (user-facing), they are named as tests for individual tools (developer-facing).

Ideally we could use files from https://github.com/google/iree/tree/main/iree/test/e2e/xla_ops and other test directories, but that is blocked on https://github.com/google/iree/issues/1538.
