### ISSUE TITLE
iree-android-benchmark builds are failing during git init

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#4668]
Sample failure: https://buildkite.com/iree/iree-android-benchmark/builds/1756#bb2e2fe3-32f9-4504-aa19-0a9d5b0f7b65

Relevant logs:

```
[18:05:26 UTC] echo 'Initializing submodules'
--
  | Initializing submodules
  | [18:05:26 UTC] ./scripts/git/submodule_versions.py init
  | fatal: Couldn't find remote ref refs/heads/master
  | Unable to fetch in submodule path 'third_party/llvm-project'
  | *** Initializing submodules
  | +git submodule init  [from /usr/src/github/iree]
  | Submodule state differs from SUBMODULE_VERSIONS.txt file. Run (and commit) one of:
  | ./scripts/git/submodule_versions.py import # Use version in SUBMODULE_VERSIONS.txt ('written')
  | ./scripts/git/submodule_versions.py export # Use version in git state ('actual')
  | third_party/llvm-project : actual=c85b6bf33c473633c9873b600f8a31fa55464e1e written=b92a39ac1319c796777bca19a3af2856acbc69c1
  | third_party/tensorflow : actual=9fd861b9a1d777daef138a2e06d7f50b7ea63744 written=16613a70ef36b103e7c1ffa903d541814b62c109
  | third_party/mlir-hlo : actual=30ce82790d4ffef48f70e99a6f96f13ddbe857d8 written=2b72ddc6b2b4d670bcd1ffa3f4652468b419f986
  | Warning: git submodule state does not match SUBMODULE_VERSIONS.txt. Using state in SUBMODULE_VERSIONS.txt
```

https://github.com/llvm/llvm-project/ recently deleted their `master` branch in favor of `main`, but none of our other builds are failing. Is there some improperly cached git state on these machines?

**Comment by GMNGeoffrey** [comment]
I suspect this is because this build uses a persistent runner. I can probably ssh in and clear its cache

**Comment by GMNGeoffrey** [comment]
Hmmm I tried ssh'ing into the agent's VM and couldn't repro. Going to try restarting the agent

**Comment by GMNGeoffrey** [comment]
Restarting the agent did not fix the issue

**Comment by GMNGeoffrey** [comment]
Whelp I'm stumped. I also don't understand why the exact same command on the exact same agent, as part of the non-benchmark android workflow doesn't also fail. Let's see if this is still happening on Monday

**Comment by hanhanW** [comment]
Oh I missed this today. I will take a look tomorrow.

**Comment by hanhanW** [comment]
I got some clues, but still need some time to dig in more. If you ssh to the agent, su to buildkite agent, go to `/var/lib/buildkite-agent/builds/buildkite-ubuntu/iree/iree-android-benchmark`, and run `git submodule update --init`, you can repro the issue.

```
fatal: Couldn't find remote ref refs/heads/master
Unable to fetch in submodule path 'third_party/llvm-project'
```

https://buildkite.com/organizations/iree/pipelines/iree-android-benchmark/builds/1771/jobs/7bf41482-d3be-499a-afd7-5da33831f7f4/raw_log

I feel that there is something wrong on local side, and recreate the directory may help

**Comment by hanhanW** [comment]
I got something to run, will revisit this later today.

**Comment by hanhanW** [comment]
I think it's fixed, it is building IREE now. I moved the directory to somewhere, and force it to re-create a new one. This looks like a `.git/config` issue to me. I don't know the actual issue, and I don't plan to look into more details.

I will re-run all past revision.

**Comment by GMNGeoffrey** [comment]
Thanks Hanhan. It was also my suspicion that this was something in the agent's git config, but I couldn't figure out how to clear it. Specifically, how did you su to the buildkite agent? I didn't see it in the list of users when I ssh'ed in

**Comment by hanhanW** [comment]
> Thanks Hanhan! It was also my suspicion that this was something in the agent's git config, but I couldn't figure out how to clear it. Specifically, how did you su to the buildkite agent? I didn't see it in the list of users when I ssh'ed in

I found it in @antiagainst's BuildKite agent setup doc when I was setting an agent (S10), the command is `sudo -u buildkite-agent bash`.
