### ISSUE TITLE
Add cleaner symbol visibility syntax for all flow/hal/vm types

### ISSUE THREAD

**Issue by benvanik** [google/iree#4670]
Upstream made the symbol visibility attribute part of the syntax of ops like func. It's awesome. It'd be nice to update our ops:

```mlir
hal.variable @_executable_exe init(@_executable_exe_initializer) : !hal.executable attributes {sym_visibility = "private"}
```

->

```mlir
hal.variable private @executable_exe init(@_executable_exe_initializer) : !hal.executable
```

flow/hal.variable, vm.global, vm.func, hal.executable, etc etc all could get these changes. Basically, we shouldn't have any sym_visibility bits in our IR. There's no functional change here but things will get much easier to hand-write and read and make our IR match the upstream canonical types making it easier for people to move between the two.

**Comment by ScottTodd** [comment]
<sub>Discussion about this on Discord [here](https://discord.com/channels/689900678990135345/689906000043573354/845331194652262470)</sub>

Seems we could use https://mlir.llvm.org/docs/OpDefinitions/#custom-directives with

* [`parseOptionalVisibilityKeyword`](https://github.com/llvm/llvm-project/blob/16b284e99e4bca8d1e571310f545f10512dc979b/mlir/lib/IR/SymbolTable.cpp#L1067-L1081)
* [visibility parsing](https://github.com/llvm/llvm-project/blob/16b284e99e4bca8d1e571310f545f10512dc979b/mlir/lib/IR/FunctionImplementation.cpp#L197-L198)
* [visibility printing](https://github.com/llvm/llvm-project/blob/16b284e99e4bca8d1e571310f545f10512dc979b/mlir/lib/IR/FunctionImplementation.cpp#L355-L357)

**Comment by benvanik** [comment]
We now have a SymbolVisibility custom assembly format thingie here: https://github.com/google/iree/blob/8e1ffddfe68969960fdb6944da75a149901bab4d/iree/compiler/Dialect/Util/IR/UtilOps.h#L34 - just need to sprinkle it over the other dialects.
