### ISSUE TITLE
VMLA timing out running dynamic-shape PRelu

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#4690]
**Describe the bug**
The keras layers test using the VMLA backend times out, even with a 15 minute timeout. The math here is not complex enough to warrant that. I've reproduced the behavior using the input IR with just IREE core.

**To Reproduce**
Compile and run this IR on the VMLA backend: https://gist.github.com/GMNGeoffrey/60d9f7bc68eeaaf9f576ec6109ed5f35

```shell
$ iree-translate prelu.mlir --iree-hal-target-backends=vmla -iree-mlir-to-vm-bytecode-module -o prelu.vmfb
$ iree-run-module prelu.vmfb --entry_function=PReLU__3x3x3x3x3__f32__uniform --function_inputs=3x3x3x3x3xf32
```

**Comment by ScottTodd** [comment]
Trying to repro (on Windows), debugger catches here: https://github.com/google/iree/blob/a0d7eb84d14be4da6340545aac4488ad4d1655bf/iree/task/worker.c#L263-L264

then appears to hang around here (program does not abort): https://github.com/google/iree/blob/a0d7eb84d14be4da6340545aac4488ad4d1655bf/iree/base/wait_handle_win32.c#L377-L381

**Comment by GMNGeoffrey** [comment]
This popped up in the latest main -> google merge, so the culprit is likely one of the commits in #4682.

**Comment by benvanik** [comment]
Hitting that indicates that the VMLA execution returned a failure - which really shouldn't happen unless the VMLA module itself is malformed. So that's likely the root cause, and the hang is just because of the not-yet-implemented propagation.

**Comment by benvanik** [comment]
Looking at the input IR I suspect some indexing snafu in our hlo->vmla lowerings - which then at runtime will cause failures for out of bounds/etc.

**Comment by ScottTodd** [comment]
I got a slice of an error message by adding some `iree_status_format` code and poking at it with a debugger: 
```
D:\\dev\\projects\\iree\\iree\\modules\\vmla\\op_module.cc:269: OUT_OF_RANGE; while calling import;
```

**Comment by ScottTodd** [comment]
that points to https://github.com/google/iree/blob/060f152c74b8cab1766b00c62ac3c63bf5039463/iree/modules/vmla/op_module.cc#L268-L274

**Comment by benvanik** [comment]
Yep - so sounds like a mistranslation of one of the ops.

**Comment by ScottTodd** [comment]
Do we have a way to step through IR snapshots together with debugger execution yet, or is that still a "one day we could do this" dream? :P 

This would be a good case to see where in the IR we were running at the point of the error status then follow that back up the IR stack to see which op translation was incorrect.

**Comment by benvanik** [comment]
Best way right now - which should get you what you need - is setting 1 https://github.com/google/iree/blob/17856ed8424bb99bf2e698e903703793949151fc/iree/vm/bytecode_dispatch_util.h#L135

You can then see each call happening and it's easy to correlate with the vmla mlir right before serialization (as they are 1:1).

**Comment by benvanik** [comment]
(then, work backwards through a print-ir-after-all to see what is creating the buffer view op that is bad)

**Comment by GMNGeoffrey** [comment]
I just tried rerunning the same steps (both translate and run) back at 8d74bfa28 (before the last main -> google) and still got the error, which is confusing... Since you've got a debugger setup here, I'm going to assume you're tackling this Scott, but lmk if I can help

**Comment by ScottTodd** [comment]
> I just tried rerunning the same steps (both translate and run) back at [8d74bfa](https://github.com/google/iree/commit/8d74bfa28dd35203fba700aa1f1d88c200c848cd) (before the last main -> google) and still got the error, which is confusing... Since you've got a debugger setup here, I'm going to assume you're tackling this Scott, but lmk if I can help

Yeah, I can triage.

**Comment by ScottTodd** [comment]
Here's output from `-print-ir-after-all` and `#define IREE_DISPATCH_LOGGING 1`: https://gist.github.com/ScottTodd/504b181fa70a6d9b450c27f28b08c042

**Comment by benvanik** [comment]
So there's your isolated input to test:
```mlir
      func @PReLU__3x3x3x3x3__f32__uniform_ex_dispatch_2(%arg0: index, %arg1: tensor<?x3x3x3x3xf32>, %arg2: index) -> tensor<?x3x3x3x3xf32> {
        %0 = shapex.make_ranked_shape %arg0 : (index) -> !shapex.ranked_shape<[?,3,3,3,3]>
        %1 = shapex.make_ranked_shape %arg2 : (index) -> !shapex.ranked_shape<[?,3,3,3,3]>
        %cst = constant dense<-0.000000e+00> : tensor<3x3x3x3xf32>
        %2 = shapex.tie_shape %arg1, %1 : tensor<?x3x3x3x3xf32>, !shapex.ranked_shape<[?,3,3,3,3]>
        %3 = "shapex.ranked_broadcast_in_dim"(%cst, %0) {broadcast_dimensions = dense<[1, 2, 3, 4]> : tensor<4xi64>} : (tensor<3x3x3x3xf32>, !shapex.ranked_shape<[?,3,3,3,3]>) -> tensor<?x3x3x3x3xf32>
        %4 = "shapex.ranked_broadcast_in_dim"(%2, %0) {broadcast_dimensions = dense<[0, 1, 2, 3, 4]> : tensor<5xi64>} : (tensor<?x3x3x3x3xf32>, !shapex.ranked_shape<[?,3,3,3,3]>) -> tensor<?x3x3x3x3xf32>
        %5 = mhlo.multiply %3, %4 : tensor<?x3x3x3x3xf32>
        return %5 : tensor<?x3x3x3x3xf32>
      }
```

Seems pretty straightforward, but also involves rank>4 and dynamic shapes, so who knows what kind of untested code paths you are going down.

**Comment by ScottTodd** [comment]
Moved discussion to Discord for realtime chat: [message link](https://discord.com/channels/689900678990135345/689906000043573354/806282584505319436)

**Comment by ScottTodd** [comment]
> This popped up in the latest main -> google merge, so the culprit is likely one of the commits in #4682.

Likely comes from https://github.com/google/iree/pull/4621 (still tracking down where specifically)

**Comment by ScottTodd** [comment]
Ah, this actually was my fault :P working on a fix...

**Comment by benvanik** [comment]
nah: I fixed up a lot of these paths for MaterializeResourceCaches but that happens after linking and I didn't think to pop up the stack and also verify that
