### ISSUE TITLE
mlir::iree_compiler::IREE::HAL::MaterializeInterfacesPass fail xla_ops using linalg-on-tensors pass

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#4692]
**Describe the bug**
MaterializeInterfacesPass fails with the following error when lowering some pointwise ops: 

```
unsupported interface function argument 3 type 'f32'; requires tensors or simple primitive values (i32, etc)
```

**To Reproduce**
```
 $iree-translate --iree-hal-target-backends=dylib-llvm-aot --iree-mlir-to-vm-bytecode-module /tmp/clamp.mlir -o /tmp/clamp.vmfb 
 func @f32() -> tensor<4xf32> attributes {iree.module.export} {
    %0 = iree.unfoldable_constant dense<0.000000e+00> : tensor<4xf32>
    %1 = iree.unfoldable_constant dense<[-2.000000e+00, 4.000000e+00, 8.000000e+00, 1.200000e+01]> : tensor<4xf32>
    %2 = iree.unfoldable_constant dense<1.000000e+01> : tensor<4xf32>
    %3 = "mhlo.clamp"(%0, %1, %2) : (tensor<4xf32>, tensor<4xf32>, tensor<4xf32>) -> tensor<4xf32>
    return %3 : tensor<4xf32>
  }
  ```

**Comment by asaadaldien** [comment]
Full log: https://gist.github.com/asaadaldien/cd24d19ad00e01f84ae1c2cfb5812007

**Comment by benvanik** [comment]
supporting floats (or arbitrary types) coming across that is TBD - it requires some casting (or really, likely just dropping down to uniform buffers vs. push constants) - the short term fix is to find what's adding the f32 argument and removing it

**Comment by MaheshRavishankar** [comment]
@asaadaldien having a gist of the dump with `-print-ir-before-all -mlir-disable-threading` would be useful here.

**Comment by asaadaldien** [comment]
> @asaadaldien having a gist of the dump with `-print-ir-before-all -mlir-disable-threading` would be useful here.

https://gist.github.com/asaadaldien/4e9ad7de8a428d1327a87f6d8947f880

**Comment by MaheshRavishankar** [comment]
This pass should be running upstream https://github.com/google/iree/blob/a15d08f3adba62b9541824fc55e5501711da08f5/iree/compiler/Conversion/LinalgToLLVM/Passes.cpp#L120

I dont know why it is running all the way in the translation passes? (Same on the SPIR-V side)

**Comment by benvanik** [comment]
The major issue here (f32 not supported) is because the load-bearing pass that prevents this from happening is conditionally disabled on the linalg on tensors path:
https://github.com/google/iree/blob/4ae2178fcb8d1c1bcbd612d3c147dc9032dd851f/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L211-L214

it's an important pass - don't recall why it's off - it should be on - fix that and you fix this issue :)

**Comment by asaadaldien** [comment]
> createDecomposeHLOClampPass

As far as I remember this was created to do some `HLO -> HLO` only for codegen not vmla so it was added here.

**Comment by asaadaldien** [comment]
> The major issue here (f32 not supported) is because the load-bearing pass that prevents this from happening is conditionally disabled on the linalg on tensors path:
> https://github.com/google/iree/blob/4ae2178fcb8d1c1bcbd612d3c147dc9032dd851f/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L211-L214
> 
> it's an important pass - don't recall why it's off - it should be on - fix that and you fix this issue :)

unfortunately still same error :(

**Comment by benvanik** [comment]
Given that ntv disabled it like that I suspect he just hacked right past it and it may never have been tested/ported to the linalg on tensors path. Looking at it, it makes sense it doesn't work:
https://github.com/google/iree/blob/204c599d9a7357593125457f8021447e4f889762/iree/compiler/Dialect/Flow/Transforms/RematerializeDispatchConstants.cpp#L162-L171

it's not yet adapted to FlowDispatchWorkgroupsOp :)

**Comment by benvanik** [comment]
(this pass is pretty complex for what it does because it had to observe a bunch of the restrictions around old dispatch regions that couldn't have consts in them and such - the new path in there should be much simpler as there's no need for canDispatchRegionContainConstants)

**Comment by asaadaldien** [comment]
Getting same failure when lowering `mho.dot`. This can be fixed by moving the splat constant `%cst_1` inside the dispatch region.  
```
// *** IR Dump Before mlir::iree_compiler::IREE::Flow::DispatchLinalgOnTensorsPass ***
func @large() -> tensor<32x64xf32> attributes {iree.module.export} {
  %cst = constant dense<1.000000e+00> : tensor<32x1024xf32>
  %cst_0 = constant dense<4.000000e-01> : tensor<1024x64xf32>
  %cst_1 = constant 0.000000e+00 : f32
  %0 = iree.do_not_optimize(%cst) : tensor<32x1024xf32>
  %1 = iree.do_not_optimize(%cst_0) : tensor<1024x64xf32>
  %2 = linalg.init_tensor [32, 64] : tensor<32x64xf32>
  %3 = linalg.fill(%2, %cst_1) : tensor<32x64xf32>, f32 -> tensor<32x64xf32>
  %4 = linalg.matmul ins(%0, %1 : tensor<32x1024xf32>, tensor<1024x64xf32>) outs(%3 : tensor<32x64xf32>) -> tensor<32x64xf32>
  return %4 : tensor<32x64xf32>
}

// *** IR Dump After mlir::iree_compiler::IREE::Flow::DispatchLinalgOnTensorsPass ***
func @large() -> tensor<32x64xf32> attributes {iree.module.export} {
  %cst = constant dense<1.000000e+00> : tensor<32x1024xf32>
  %cst_0 = constant dense<4.000000e-01> : tensor<1024x64xf32>
  %cst_1 = constant 0.000000e+00 : f32
  %c1 = constant 1 : index
  %c32 = constant 32 : index
  %c64 = constant 64 : index
  %0 = iree.do_not_optimize(%cst) : tensor<32x1024xf32>
  %1 = iree.do_not_optimize(%cst_0) : tensor<1024x64xf32>
  %2 = linalg.init_tensor [32, 64] : tensor<32x64xf32>
  %3 = linalg.fill(%2, %cst_1) : tensor<32x64xf32>, f32 -> tensor<32x64xf32>
  %4 = flow.dispatch.workgroups[%c64, %c32, %c1] (%cst_1, %0, %1) : (f32, tensor<32x1024xf32>, tensor<1024x64xf32>) -> tensor<32x64xf32> = (%arg0 : f32, %arg1 : !flow.dispatch.input<32x1024xf32>, %arg2 : !flow.dispatch.input<1024x64xf32>, %arg3 : !flow.dispatch.output<32x64xf32>) {
    %c32_2 = constant 32 : index
    %c64_3 = constant 64 : index
    %c0 = constant 0 : index
    %c1024 = constant 1024 : index
    %c1_4 = constant 1 : index
    %5 = linalg.init_tensor [32, 64] : tensor<32x64xf32>
    %6 = linalg.fill(%5, %arg0) : tensor<32x64xf32>, f32 -> tensor<32x64xf32>
    %workgroup_size_0 = flow.dispatch.workgroup.size[0] : index
    %workgroup_size_1 = flow.dispatch.workgroup.size[1] : index
    %workgroup_id_0 = flow.dispatch.workgroup.id[0] : index
    %workgroup_count_0 = flow.dispatch.workgroup.count[0] : index
    %workgroup_id_1 = flow.dispatch.workgroup.id[1] : index
    %workgroup_count_1 = flow.dispatch.workgroup.count[1] : index
    %7 = muli %workgroup_size_1, %workgroup_id_1 : index
    %8 = muli %workgroup_size_1, %workgroup_count_1 : index
    scf.for %arg4 = %7 to %c32_2 step %8 {
      %9 = muli %workgroup_size_0, %workgroup_id_0 : index
      %10 = muli %workgroup_size_0, %workgroup_count_0 : index
      scf.for %arg5 = %9 to %c64_3 step %10 {
        %11 = affine.min affine_map<(d0, d1) -> (d1, -d0 + 32)>(%arg4, %workgroup_size_1)
        %12 = flow.dispatch.input.load %arg1, offsets = [%arg4, %c0], sizes = [%11, %c1024], strides = [%c1_4, %c1_4] : !flow.dispatch.input<32x1024xf32> -> tensor<?x1024xf32>
        %13 = affine.min affine_map<(d0, d1) -> (d1, -d0 + 64)>(%arg5, %workgroup_size_0)
        %14 = flow.dispatch.input.load %arg2, offsets = [%c0, %arg5], sizes = [%c1024, %13], strides = [%c1_4, %c1_4] : !flow.dispatch.input<1024x64xf32> -> tensor<1024x?xf32>
        %15 = affine.min affine_map<(d0, d1) -> (d1, -d0 + 32)>(%arg4, %workgroup_size_1)
        %16 = affine.min affine_map<(d0, d1) -> (d1, -d0 + 64)>(%arg5, %workgroup_size_0)
        %17 = subtensor %5[%arg4, %arg5] [%15, %16] [1, 1] : tensor<32x64xf32> to tensor<?x?xf32>
        %18 = linalg.fill(%17, %arg0) : tensor<?x?xf32>, f32 -> tensor<?x?xf32>
        %19 = linalg.matmul {__internal_linalg_transform__ = "workgroup"} ins(%12, %14 : tensor<?x1024xf32>, tensor<1024x?xf32>) outs(%18 : tensor<?x?xf32>) -> tensor<?x?xf32>
        flow.dispatch.output.store %19, %arg3, offsets = [%arg4, %arg5], sizes = [%15, %16], strides = [%c1_4, %c1_4] : tensor<?x?xf32> -> !flow.dispatch.output<32x64xf32>
      }
    }
    flow.return
  }
  return %4 : tensor<32x64xf32>
}
```

**Comment by MaheshRavishankar** [comment]
Interesting. That was sort of expected. Did you do something to move the `fill` into the dispatch region? I didnt expect that to happen.

**Comment by asaadaldien** [comment]
> Interesting. That was sort of expected. Did you do something to move the `fill` into the dispatch region? I didnt expect that to happen.

The fusion moved it (just passing`--iree-flow-dispatch-linalg-on-tensors-enable-fusion`) otherwise the`DispatchLinalgOnTensorsPass` will fail with ` Failed to rewrite destructive updates in:`

**Comment by asaadaldien** [comment]
> Given that ntv disabled it like that I suspect he just hacked right past it and it may never have been tested/ported to the linalg on tensors path. Looking at it, it makes sense it doesn't work:
> https://github.com/google/iree/blob/204c599d9a7357593125457f8021447e4f889762/iree/compiler/Dialect/Flow/Transforms/RematerializeDispatchConstants.cpp#L162-L171
> 
> it's not yet adapted to FlowDispatchWorkgroupsOp :)

And this is the right place to do this =), just need to adapt it to work with `DispatchWorkgroupsOp` @benvanik you were ahead of me looking at this thanks :)
