### ISSUE TITLE
Reorder flow transformation passes

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#4708]
We want to reorder passes in flow transformation pipeline:
https://github.com/google/iree/blob/main/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
To look like the following:

```
// HLO, Tosa and other pre- processing passes
// Shape ops passes
// Any pre HAL required transformation (reflections..etc)
if (clEnableLinalgOnTensorsDispatch) {
  // Dispatch linalg op
} else {
   // Partition and dispatch HLO ops
}
// Reset of the passes
```
This issue to refactor load bearing HLO ops and pull them out.

**Comment by MaheshRavishankar** [comment]
Fixed by PR #4797
