### ISSUE TITLE
Document profiling with tracy between two computers over the network

### ISSUE THREAD

**Issue by hanhanW** [google/iree#4750]
This is a note that how I capture the trace over the network. I will update it to the doc.

1. Connect the mobile phone to my local laptop
2. Run `adb forward tcp:8086 tcp:8086` on laptop
3. Port forwarding for tracy tools: `ssh -NR 8086:127.0.0.1:8086 "${remote_machine}"`
4. Build tracy/capture/build/unix on remote workstation

Run the program on Android, e.g.,

```
adb shell TRACY_NO_EXIT=1 taskset 80 /data/local/tmp/iree-run-module \
  --module_file=/data/local/tmp/a.vmfb \
  --driver=dylib \
  --function_inputs=1x384xi32=0,1x384xi32=0,1x384xi32=0 \
  --entry_function=serving_default
```

Then run `./capture-release -o trace.tracy` on workstation.

note: order matters for execution and capturing trace.

**Comment by ScottTodd** [comment]
https://github.com/google/iree/pull/8080 added some similar docs. Let's close this stale issue?
