### ISSUE TITLE
Add multithreaded versions to benchmark targets

### ISSUE THREAD

**Issue by hanhanW** [google/iree#4752]
Forked from #4686, we need a multithreaded version benchmarks.

**Comment by asaadaldien** [comment]
We need to create to separate mako configurations
1) Single threaded with the following args:
```
taskset 80, driver=dylib-sync
``` 

2) Multi-threaded with the following args:
```
taskset f0, driver=dylib,--worker_count=3
```

**Comment by hanhanW** [comment]
Do we pass `--iree-hal-target-backends=dylib-llvm-aot` to `iree-translate` for compiling both modules?

**Comment by asaadaldien** [comment]
> Do we pass `--iree-hal-target-backends=dylib-llvm-aot` to `iree-translate` for compiling both modules?

Correct! same compilation the difference is runtime only.
