### ISSUE TITLE
Unused LogicalResult being cast to void

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#4759]
To avoid errors when integrating, we've worked around unused `LogicalResult` returns by casting to `void`. There's a good reason those warn on unused and these should be fixed. Basically every instance of `(void)` in https://github.com/google/iree/pull/4755/files, or alternatively, almost every instance in https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/google/iree%24+%22%28void%29%22+f:iree/compiler&patternType=regexp

**Comment by MaheshRavishankar** [comment]
Should be fixed by PR #4840

**Comment by GMNGeoffrey** [comment]
There are still many results from the search linked above

**Comment by MaheshRavishankar** [comment]
Ah, I didnt realize the bug is for all of them. Ok, Ill leave it open for now. THanks
