### ISSUE TITLE
[DOC] tools/test/simple.mlir doesn't exist

### ISSUE THREAD

**Issue by masahi** [google/iree#4773]
The getting started doc https://google.github.io/iree/get-started/getting-started-linux-cmake mentions `iree/tools/test/simple.mlir` but it doesn't exist in the current repo (the link is dead).

Which test cases would you recommend for a beginner to play with?

**Comment by ScottTodd** [comment]
See also https://github.com/google/iree/issues/4667

https://github.com/google/iree/tree/main/iree/tools/test has a few files that are simple to get started with. Larger scale samples are in https://github.com/google/iree/tree/main/iree/test/e2e, though some aren't compatible out-of-the-box with tools like `iree-run-mlir`

**Comment by masahi** [comment]
Thanks, I didn't notice that there is an issue for this already.
