### ISSUE TITLE
IREE inline function binding policy

### ISSUE THREAD

**Issue by ewconnell** [google/iree#4781]
This question is about establishing a general policy for FFI's and IREE inline functions.

When creating an FFI binding to IREE, there is an issue of how we want to handle inline functions. They can't be implemented at the call site, and there is nothing to link to. As an example, `iree/base/api.h` currently has 8 inline functions. Perhaps some of these won't be needed from a front end language, but something like `iree_allocator_system` might.
```C
static inline iree_allocator_t iree_allocator_system() {
  iree_allocator_t v = {NULL, iree_allocator_system_allocate,
                        iree_allocator_system_free};
  return v;
}
```
In general how would we like to handle these? Three options that come to mind:
- don't make them available to the foreign language (possibly inconvenient)
- change them to not be inline anymore so they can be linked to (maybe a performance hit)
- duplicate them in the foreign language (concern about single source of truth)

A Rust duplicate might look like
```Rust
#[inline]
pub fn iree_allocator_system() -> iree_allocator_t {
  iree_allocator_t {
    self_: null_mut(),
    alloc: Some(iree_allocator_system_allocate),
    free: Some(iree_allocator_system_free),
  }
}
```
Thoughts?

**Comment by benvanik** [comment]
They aren't exported functions as they are always to be inlined at the use-site. They are considered equivalent to macros (they are effectively constexpr functions, only constexpr doesn't exist in C) and to be replaced with language-specific versions when exposed through bindings.

**Comment by ewconnell** [comment]
Yes there are a lot of macro definitions that fall into the same category.
To be clear, you are saying you would like to see macros and inline functions replicated in the language-specific binding layer? Like how I showed above for `iree_allocator_system`?

After defining a user model, we might end up deciding not to expose them "as is", but that's a different discussion down the road.

**Comment by benvanik** [comment]
Whatever makes the most sense. They are all just helpers/initializers and in most cases shouldn't be exposed to users in the foreign language as hopefully it's wrapping things up with more canonical types vs. just calling the low level C functions. For example, I'd expect something in rust land to have its own allocator type that then is mapped at a very low level right before calling into the IREE C API into iree_allocator_t, vs passing an iree_allocator_t struct around through various rust code. At that point just having that goo populate the struct is best so something like iree_allocator_system() may never be used.

**Comment by ewconnell** [comment]
Agree, that's what I meant by "After defining a user model, we might end up deciding not to expose them "as is" "
Thanks
