### ISSUE TITLE
Compiled DNN training with JAX causes segfaults.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#4803]
Running [dnn_training_repro.py](https://gist.github.com/phoenix-meadowlark/a6a5b4e2fbafd26a8a9c608f97587488) causes segmentation faults at somewhat  random intervals. On my machine it does so every time, but doesn't cause segfaults if you move `"GradientDescent"` to the top of the `OPTIMIZERS_TO_HPARAMS` dictionary.

Aside from the optimizer order, both lines [90](https://gist.github.com/phoenix-meadowlark/a6a5b4e2fbafd26a8a9c608f97587488#file-dnn_training_repro-py-L90) and [95](https://gist.github.com/phoenix-meadowlark/a6a5b4e2fbafd26a8a9c608f97587488#file-dnn_training_repro-py-L95) are necessary to cause the error.

**Comment by stellaraccident** [comment]
Ok, I've repro'd an issue like what you reported on discord:

```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Compiling: Adam
  lowering through HLO
  compiling HLO --> LLVM-AOT
  loading compiled binary into runtime bindings
Created IREE driver dylib: <pyiree.rt.binding.HalDriver object at 0x7f3e501516b0>
SystemContext driver=<pyiree.rt.binding.HalDriver object at 0x7f3e501516b0>
Traceback (most recent call last):
  File "jax_mlp_crash.py", line 110, in <module>
    main()
  File "jax_mlp_crash.py", line 92, in main
    module = iree.rt.load_module(cpp_vm_module, config=rt_config)
  File "/usr/local/google/home/laurenzo/src/iree-build/bindings/python/pyiree/rt/system_api.py", line 325, in load_module
    return load_modules(module, config=config)[0]
  File "/usr/local/google/home/laurenzo/src/iree-build/bindings/python/pyiree/rt/system_api.py", line 318, in load_modules
    context = SystemContext(modules=modules, config=config)
  File "/usr/local/google/home/laurenzo/src/iree-build/bindings/python/pyiree/rt/system_api.py", line 269, in __init__
    self._vm_context = _binding.VmContext(instance=self._config.vm_instance,
RuntimeError: Error creating vm context with modules: INTERNAL
```

This happens on the very first module that we are attempting to load, and I was able to repro it by using compiler binaries from ~a week ago with a runtime from ~tonight. When I upgraded to yesterday's compiler binary snapshots, the error did not happen. I haven't done a full bisect, but I believe that this points to something changing in the binary ABI in the intervening time. I was then also able to get segfaults/stack traces as you reported that looked spookily like the gc bug I fixed last week. I checked, and I happened to have a branch checked out from right before that fix (I think). I'm going to do some more digging and tighten up the diagnosis.

**Comment by stellaraccident** [comment]
I'm still having trouble activating ASAN in a session where jax is loaded, so I'm doing this the somewhat imprecise way (we will need to track that down but trying to get you to a good state first).

**Comment by stellaraccident** [comment]
Also, please verify the versions that you have installed (something like `pip freeze | grep iree`). Mine are:

```
iree-compiler-snapshot==20210207.85
iree-runtime-snapshot==20210207.85
iree-tools-xla-snapshot==20210207.85
```

And your example has run multiple times without a crash on those versions. Given that I was able to repro both of your issues with combinations of older versions, I would like to double check...

**Comment by benvanik** [comment]
(drive by: you can use `iree_status_to_string` in `CheckApiStatus` to get a source location and message for the status instead of just the code)

**Comment by phoenix-meadowlark** [comment]
> Also, please verify the versions that you have installed (something like `pip freeze | grep iree`). Mine are:
> 
> ```
> iree-compiler-snapshot==20210207.85
> iree-runtime-snapshot==20210207.85
> iree-tools-xla-snapshot==20210207.85
> ```
> 
> And your example has run multiple times without a crash on those versions. Given that I was able to repro both of your issues with combinations of older versions, I would like to double check...

I haven't taken the time to figure out how to mix the pip binaries with a local CMake build, and I haven't had the time to set up packaging for the JAX frontend, so I've just been building everything locally. I saw the segfaults at a commit from a few days ago (I _think_ after your fixes), but updated to 707cf08c913f222ab73a641f5434b3ccc6f4341e to be sure before creating the repro.

**Comment by stellaraccident** [comment]
> (drive by: you can use `iree_status_to_string` in `CheckApiStatus` to get a source location and message for the status instead of just the code)

Thanks. Will send a PR shortly with the better message printing. Here is what it reports (indeed looks like a version skew problem): ```RuntimeError: Error creating vm context with modules: /usr/local/google/home/laurenzo/src/iree/iree/vm/context.c:146: INTERNAL; import function signature mismatch between module and source hal; expected 0r[i]i.r but got 0ri[i].```

**Comment by stellaraccident** [comment]
It is quite possible that there is something deeper going on, but from what I see, we've got quite a few bugs fixed or outstanding recently and the possibility of some stale state:

1. The "gc issue" #4738 (fixed 5 days ago)
2. A compiler<->runtime version issue that seems to have come about in the last 5 days
3. #4706 which generates bad code for (I think) any depthwise conv, resulting in weird segfaults (which was likely the initial trigger for mobilenetv1 issues)

I would not discount there be another undiscovered 4 on that list, but I haven't been able to repro it. The real answer is to find out why we can't enable ASAN and JAX at the same time... without that, we are flying blind a bit.

**Comment by benvanik** [comment]
> > (drive by: you can use `iree_status_to_string` in `CheckApiStatus` to get a source location and message for the status instead of just the code)
> 
> Thanks. Will send a PR shortly with the better message printing. Here is what it reports (indeed looks like a version skew problem): `RuntimeError: Error creating vm context with modules: /usr/local/google/home/laurenzo/src/iree/iree/vm/context.c:146: INTERNAL; import function signature mismatch between module and source hal; expected 0r[i]i.r but got 0ri[i].`

hooray for good error messages :)
caused by HAL changes - there's only a bit of effort into making the compiler/runtime/executable ABI stable just yet so it's generally safe to assume that there will be issues if mixing versions until things settle down (I've got a few more PRs landing that have similar changes, but this was one of the first breakages in awhile) - I'd at least not build any non-debugging workflows around skewed versions :)

**Comment by stellaraccident** [comment]
> caused by HAL changes - there's only a bit of effort into making the compiler/runtime/executable ABI stable just yet so it's generally safe to assume that there will be issues if mixing versions until things settle down (I've got a few more PRs landing that have similar changes, but this was one of the first breakages in awhile) - I'd at least not build any non-debugging workflows around skewed versions :)

Yeah, it's fine for now. It just so happened that I was intentionally mixing with an old branch with some asan patches. Not something I endorse.

**Comment by stellaraccident** [comment]
Ok, got asan working with python+iree+jax and it seems clean at head. I even scattered some random `gc.collect()` calls in (the usual way to smoke these things out).

Phoenix, if you need to do a local frankenbuild, here's what I've done:

```
# Build everything at head and install to a temp directory in release mode (good for getting all of the TF and compiler bits optimized while fiddling with the rest).
cmake -DIREE_BUILD_XLA_COMPILER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/tmp/iree -DIREE_ENABLE_LLD=ON .

# This will create individual python packages under $HOME/tmp/iree/python_packages that you can manually add to your PYTHONPATH however you like.
ninja install

# Manually make a package for the non-installable jax frontend and symlink it from the source tree.
# We really should make this installable (I can help with that tomorrow once I find out whether Geoffrey broke my releases with the TF toolchain changes).
mkdir -p $HOME/tmp/iree/python_packages/jax/pyiree
ln -s $HOME/src/iree/bindings/python/pyiree/jax $HOME/tmp/iree/python_packages/jax/pyiree
```

# Reconfigure to just build the runtime in Debug mode with ASAN.
cmake -DCMAKE_BUILD_TYPE=Debug -DIREE_BUILD_XLA_COMPILER=OFF -DIREE_BUILD_COMPILER=OFF -DIREE_BUILD_TESTS=OFF -DIREE_BUILD_SAMPLES=OFF -DIREE_BUILD_PYTHON_BINDINGS=ON
cmake -DIREE_ENABLE_ASAN=ON .
ninja

# Create a franken PYTHONPATH with the bits you want from each location.
export PYTHONPATH=$HOME/tmp/iree/python_packages/iree_compiler:$HOME/tmp/iree/python_packages/iree_tools_xla:$HOME/tmp/iree/python_packages/jax:$(realpath $HOME/src/iree-build/bindings/python)

# Run some jax+iree python program with ASAN injected.
# You may need to root around on your file-system to find the asan runtime library that corresponds to your clang.
LD_PRELOAD=/usr/lib/llvm-11/lib/clang/11.0.1/lib/linux/libclang_rt.asan-x86_64.so python jax_mlp_crash.py
```

I don't necessarily expect you to be doing that, just documenting my process. A shortcut (albeit one that can cut you) is to just install the latest wheels with pip, then just configure IREE to build the runtime and only set your PYTHONPATH up to your local `iree-build/bindings/python` directory to get the parts that you want from a local build. As Ben says, though, there are still a couple more ABI breaking changes in queue, so there is some danger of version skew with this one.

**Comment by phoenix-meadowlark** [comment]
Okay, I was able to rebuild and confirm that the issue seems resolved at head. Do you think it's reasonable to add the repro as a temporary test in `bindings/python/pyiree/jax/e2e/`?
