### ISSUE TITLE
Benchmark allocates buffers in each iteration without releasing after #4767

### ISSUE THREAD

**Issue by hanhanW** [google/iree#4852]
**Describe the bug**
See a sample: https://buildkite.com/iree/iree-android-benchmark/builds/1877

The error log:

```
F ../iree/tools/iree-benchmark-module-main.cc:77] Check failed: ::iree::IsOk(_status77) ../iree/hal/vulkan/status_util.c:53: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import
```

I can reproduce this on local side. One workaround is to reduce the number of `--benchmark_repetitions`. It is working with `--benchmark_repetitions=5` but not `--benchmark_repetitions=10`.

**To Reproduce**

- Download artifacts from https://buildkite.com/iree/iree-android-benchmark/builds/1877
- Upload files to an Android phone
- Run the model, e.g., `adb shell LD_LIBRARY_PATH=/data/local/tmp taskset 80 /data/local/tmp/benchmark_tmpdir/iree-benchmark-module --flagfile=/data/local/tmp/benchmark_tmpdir/flagfile --module_file=/data/local/tmp/benchmark_tmpdir/mobile-bert-vulkan-spirv.vmfb --driver=vulkan --benchmark_repetitions=10`

**Comment by hanhanW** [comment]
This also happens on VMLA. With VMLA, it turns my Pixel 4 to RAMDUMP Mode. And VMLA is working on desktop. This started from #4767

**Comment by antiagainst** [comment]
I run into this too after rebasing and saw MobileNet perf regressed ~25ms. Took a Tracy profile for MobileNet. Looks like right now in each benchmark iteration we allocate a buffer, but not ever releasing it. 

[iree-mobilenet-21-02-15.tracy.zip](https://github.com/google/iree/files/5990002/iree-mobilenet-21-02-15.tracy.zip)

**Comment by benvanik** [comment]
Thanks for the trace lei! Looking now.

**Comment by hanhanW** [comment]
The trace looks really nice, thanks!

**Comment by benvanik** [comment]
Think I found the issue - if we were running ASAN on the bots it would have caught the leak :)

Adding some tests and will send for review.

**Comment by benvanik** [comment]
Thanks again for the trace @antiagainst - made this super easy to track down!
Running the benchmark bot against #4858 and will make sure it passes.

**Comment by benvanik** [comment]
Much easier to spot issues like this with allocation tracing enabled :)
![image](https://user-images.githubusercontent.com/75337/108108647-bbc16480-7045-11eb-82b5-4479858cc7bc.png)
