### ISSUE TITLE
Add an `#iree.preserve` unit attribute that has the same behavior as `iree.do_not_optimize`.

### ISSUE THREAD

**Issue by benvanik** [google/iree#4857]
Needing a new op for each dialect or routing through `iree.do_not_optimize` is messy:

```mlir
    %c0 = vm.const.i32 0 : i32
    %c0dno = iree.do_not_optimize(%c0) : i32
    %c1 = vm.const.i32 1 : i32
    %c1dno = iree.do_not_optimize(%c1) : i32
    %c2 = vm.const.i64 0 : i64
    %c2dno = iree.do_not_optimize(%c2) : i64
    %c3 = vm.const.i64 1 : i64
    %c3dno = iree.do_not_optimize(%c3) : i64
```

Instead, if we could add a `#iree.preserve` attribute on to any arbitrary ssa-defining op then we'd be able to get this behavior everywhere without so much boilerplate:

```mlir
    %c0 = vm.const.i32 0 : i32 { #iree.preserve }
    %c1 = vm.const.i32 1 : i32 { #iree.preserve }
    %c2 = vm.const.i64 0 : i64 { #iree.preserve }
    %c3 = vm.const.i64 1 : i64 { #iree.preserve }
```

This could be implemented as a pass that expands to the do_not_optimize form, or possibly something nicer. The point is that having a preserve attribute should preserve the op through lowerings and into the output.

This would also replace `iree.unfoldable_constant`, which is not great as it requires each dialect to have a conversion pattern for it vs. using their native constant-defining ops.

**Comment by ScottTodd** [comment]
Seems like this could overlap with part of the work on https://github.com/google/iree/issues/6908?

> We'll likely need a `util.constant` to hold this, as `std.constant` is closed over the attribute types it supports. This could be useful for other purposes anyway (we could turn `util.unfoldable_constant` into `util.constant {noinline}`).

(similar ideas with noinline / do not optimize / unfoldable)

**Comment by benvanik** [comment]
yeah - noinline feels better - duplicate of #6908.

**Comment by benvanik** [comment]
Duplicate of #6908.

**Comment by benvanik** [comment]
gg github https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate
