### ISSUE TITLE
Snapdragon 855 CI phone needs manual interventions

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#4861]
Something is screwed up with auth on this phone. It needs to be poked.

```
error: device unauthorized.
--
  | This adb server's $ADB_VENDOR_KEYS is not set
  | Try 'adb kill-server' if that seems wrong.
  | Otherwise check for a confirmation dialog on your device.
  | 🚨 Error: The command exited with status 1
```

https://buildkite.com/iree/iree-android-benchmark/builds/1885#3da95266-6b90-4dce-8a8c-bbaea24174f2

**Comment by hanhanW** [comment]
There are two Pixel 4 phones. One is in the lab, and another is owned by someone. I actually don't know who owns it. The broken one is in the lab. Last time I hit a similar issue on S20, I asked Eric to take a look.

Both phones have issue now.
The phone in the lab: https://buildkite.com/iree/iree-android-benchmark/builds/1885#3da95266-6b90-4dce-8a8c-bbaea24174f2
The phone not in the lab: https://buildkite.com/iree/iree-android-arm64-v8a/builds/3628#18611ef4-efa7-42bc-9ede-1b993827ec06

We need someone to go into the lab to authorize the device. The phone that is not in the lab seems disconnected. I don't see it in BuildKite agents. https://buildkite.com/organizations/iree/agents

**Comment by antiagainst** [comment]
Yeah. I think @stellaraccident owns the Pixel 4 not in the lab.

**Comment by ScottTodd** [comment]
Is there still an issue worth tracking here? It looks like the CI phone was fixed and hasn't had issues for some time?
