### ISSUE TITLE
[CMake/Windows] iree-translate build error `fatal error C1041: cannot open program database`

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#490]
Seeing this on one of my Windows machines building `iree_tools_iree-translate` with the `Visual Studio Community 2019 - amd64` CMake kit in VSCode:

```
[build] FAILED: iree/compiler/Dialect/IREE/Conversion/PreserveCompilerHints/CMakeFiles/iree_compiler_Dialect_IREE_Conversion_PreserveCompilerHints_PreserveCompilerHints.dir/PreserveCompilerHints.cpp.obj 
[build] C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\cl.exe  /nologo /TP  -I..\ -I. -I..\third_party\llvm-project\llvm\include -Ithird_party\llvm-project\llvm\include -I..\third_party\llvm-project\mlir\include -Ithird_party\llvm-project\llvm\tools\mlir\include -I..\third_party\tensorflow /DWIN32_LEAN_AND_MEAN /EHsc /FS /MDd /Zi /Ob0 /Od /RTC1   /DWIN32_LEAN_AND_MEAN /EHsc /FS -std:c++14 /showIncludes /Foiree\compiler\Dialect\IREE\Conversion\PreserveCompilerHints\CMakeFiles\iree_compiler_Dialect_IREE_Conversion_PreserveCompilerHints_PreserveCompilerHints.dir\PreserveCompilerHints.cpp.obj /Fdiree\compiler\Dialect\IREE\Conversion\PreserveCompilerHints\CMakeFiles\iree_compiler_Dialect_IREE_Conversion_PreserveCompilerHints_PreserveCompilerHints.dir\iree_compiler_Dialect_IREE_Conversion_PreserveCompilerHints_PreserveCompilerHints.pdb /FS -c ..\iree\compiler\Dialect\IREE\Conversion\PreserveCompilerHints\PreserveCompilerHints.cpp
[build] ..\iree\compiler\Dialect\IREE\Conversion\PreserveCompilerHints\PreserveCompilerHints.cpp: fatal error C1041: cannot open program database 'iree\compiler\Dialect\IREE\Conversion\PreserveCompilerHints\CMakeFiles\iree_compiler_Dialect_IREE_Conversion_PreserveCompilerHints_PreserveCompilerHints.dir\iree_compiler_Dialect_IREE_Conversion_PreserveCompilerHints_PreserveCompilerHints.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
```

"if multiple CL.EXE write to the same .PDB file, please use /FS" points me to https://docs.microsoft.com/en-us/cpp/build/reference/fs-force-synchronous-pdb-writes?view=vs-2019, though just adding `/FS` to https://github.com/google/iree/blob/df6b77a46efa939a496012a186d3d94dec35d8c3/build_tools/cmake/iree_copts.cmake#L44-L47 didn't help.

**Comment by benvanik** [comment]
this is a MAX_PATH issue - the relative path length is 242 chars, so prefixing it with the repo path will likely put you over the limit. I wonder if there's a CMake option to make the file name less ... redundant.

**Comment by benvanik** [comment]
I added `set(CMAKE_OBJECT_PATH_MAX 128)` and it logged a bunch of our long paths. PreserveCompilerHints is the longest at (what cmake uses, the basename of) 175 chars.

I don't like how PreserveCompilerHints is under its own dir anyway - I'm going to move it.

**Comment by GMNGeoffrey** [comment]
FYI the reason it was in its own directory was to mirror the layout of other dialects, e.g. iree/iree/compiler/Dialect/VM/Conversion/StandardToVM/

NBD though
