### ISSUE TITLE
IREE Compiler crash with -fdevirtualize (default for O2 level) in DispatchLinalgOnTensors.cpp

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#4919]
Repro'd on gcc 10.2.1 and 9.3.1.

Compiled in Release mode with the default (O2) optimization level, this call results in a segfault due to dereferencing a nullptr for the op: `rewriter.setInsertionPointToStart(&dispatchOp.getRegion().front());` (DispatchLinalgOnTensors.cpp:267).

**Comment by stellaraccident** [comment]
Note that this failure was bisected to this commit: https://github.com/google/iree/commit/ad85d17fa880a811407353c435b3595668a63569

**Comment by alliemartens** [comment]
From triage meeting 6/9 - closing issue.
