### ISSUE TITLE
Document how to use release TF tools binaries in cmake build

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#4980]
Likely involves a bit more than documentation to make it work right. See TODO in `getting_started_tensorflow.md`

**Comment by ScottTodd** [comment]
Anything left to do here / do we still care?
We have https://google.github.io/iree/building-from-source/python-bindings-and-importers/#building-tensorflow-frontend-bindings and https://github.com/google/iree/tree/main/integrations/tensorflow#readme .
