### ISSUE TITLE
iree-android-benchmark fails on S20

### ISSUE THREAD

**Issue by hanhanW** [google/iree#4990]
A sample: https://buildkite.com/iree/iree-android-benchmark/builds/1979#378614df-0cc0-4cd2-a1dc-b00ca8caf755

Error log:

```
adb shell LD_LIBRARY_PATH=/data/local/tmp taskset 80 /data/local/tmp/benchmark_tmpdir/iree-benchmark-module --flagfile=/data/local/tmp/benchmark_tmpdir/flagfile --module_file=/data/local/tmp/benchmark_tmpdir/mobile-bert-vulkan-spirv.vmfb --driver=vulkan --benchmark_repetitions=10
--
  | + tee test_output_files/mobile-bert-vulkan-spirv_output.txt
  | I ../iree/tools/utils/vm_util.cc:247] Creating driver and device for 'vulkan'...
  | ../iree/hal/vulkan/dynamic_symbols.cc:127: UNAVAILABLE; required method vkGetInstanceProcAddr not found in provided Vulkan library (did you pick the wrong file?); creating driver 'vulkan'
```

**Comment by hanhanW** [comment]
This starts from #4988, but looks no sense to me

**Comment by antiagainst** [comment]
I asked Eric to update S20 to Android 11. I think that's the reason. Let me look into it.

**Comment by hanhanW** [comment]
I see,, we probably have to copy the libvulkan.so again I guess.

**Comment by antiagainst** [comment]
We don't need to copy it again actually. That's needed for working around an Android 10 bug. For Android 11, binaries in `adb` environment can access the Vulkan loader normally.

**Comment by antiagainst** [comment]
I just ssh'ed in to remove the copied `libvulkan.so`. Should be working now.
