### ISSUE TITLE
Disable llvm-loop-vectorization default option

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#5001]
The llvm compilation pass relies on `llvm-loop-vectorization` to emit SIMD instructions, instead we want all generated pointwise-ops to operate on vectors and not scalar.

**Comment by asaadaldien** [comment]
So far this can be done by :

- [ ] Extending the [LoadStoreVectorization](https://github.com/google/iree/blob/main/iree/compiler/Conversion/LinalgToVector/LoadStoreVectorization.cpp) to handle pointwise-ops with broadcast semantics.

**Comment by MaheshRavishankar** [comment]
This is done already.
