### ISSUE TITLE
Refactor SPIR-V codegen pipeline to allow for multiple code-generation strategies

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#5038]
The current Linalg to SPIR-V codegen pipeline is bloated and needs some pruning to remove things that we do need anymore, or have a better way to do when moving to linalg on tensors

Ideally we want to move the codegeneration pipeline closer to something similar to the `CodegenStrategy` upstream (at least in spirit). Each `CodegenStretegy` does the following transformation
- It assumes the input to the operation is already tiled + distributed.
- It applies all the necessary tiling, promotion and vectorization patterns as a single pass or a pass pipeline
- The resulting code can then be lowered directly to a SPIR-V (or NVVM), i.e. all `CodegenStrategies` share this behavior.

We can have multiple `CodegenStratagies` and each executable could be translated using a different strategy. Potentially, an attribute on the surrounding `hal.executable.target` can be used to pick between the different strategies.  

After PR #4999  `LinalgTileAndFuse` just contains the patterns needed to lower from a tile+distributed+fused ops to GPU using promotion/vectorization, etc. That is already a great start. Other passes in the pipeline need to be re-evaluated with this in mind

__ConvertToGPUPass__
This pass has three main things which belong in different places
- Mapping an untiled Linalg Structured operation across threads on a GPU using `GlobalInvocationID`. This should be done before `LinalgTileAndFusePass` (preferably with TileAndDistributeAmongstWorkgroupsPass in PR #4999)
- Mapping an untiled Linalg Structured operation across threads within a workgroup. This should be done within the `CodegenStrategy` itself
- There are some other patterns w.r.t mapping copy operations to threads within a workgroup, that either need to be revisited, or moved to the right place

__ConvertVectorToGPUPass__
A lot of these seem to be there to map to SPIR-V. Need to separate this pass to what is needed for lowering to SPIR-V in which case it can be a "LegalizeVectorForSPIRV" pass that can live in core (first preference) or IREE (second preference)

**Comment by MaheshRavishankar** [comment]
The advantage of allowing for different `CodegenStrategies` 
1) It will also provide a pipeline for `CodegenStrategies` developed in the sandbox ([here](https://github.com/google/iree/tree/main/experimental/runners) into IREEs codegen.
2) We can treat CPU/GPU codegeneration as just different strategies (which would also extend to RISC-V and PowerVR)
3) We can have an autotuner search across code-generation strategies, and pick the best one for a hardware/model. Having different codegeneration strategies will reduce the search space considerably.

**Comment by antiagainst** [comment]
I think vector related passes needs clean up and it's not strictly related to this. So created #5051 for it.

**Comment by MaheshRavishankar** [comment]
The CPU passes have been moved to use dynamic pass pipelines #5934 . The CUDA and SPIR-V passes need to do the same.

**Comment by MaheshRavishankar** [comment]
THis is now done with use of dynamic pass pipelines in SPIR-V backend. Closing.
