### ISSUE TITLE
Lowering all operations through Linalg on tensors path

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#5043]
The initial bring up of Linalg on tensors focused on supporting a few operations needed to get MobileBert running. There are a few remaining. The full list of CPU ops needed to reach compatibility with the buffer path are [here](https://github.com/google/iree/blob/895bfb18cb9901712b0ef40bbf39ee69b1036e9a/iree/test/e2e/xla_ops/BUILD#L138) for CPU and [here](https://github.com/google/iree/blob/895bfb18cb9901712b0ef40bbf39ee69b1036e9a/iree/test/e2e/xla_ops/BUILD#L199) for GPUs. The main ones remaining are

1) Convolution (That is being addressed in PR #4999)
2) Pooling (or reduce_window)
3) Torch Index Select

After these have all been verified to run on GPU and CPU, all the supported models in [integrations/tensorflow](https://github.com/google/iree/tree/main/integrations/tensorflow) need to be tested and moved over to use Linalg on tensors path. Then the Linalg on buffers path can be deprecated.

**Comment by hanhanW** [comment]
I'm surprised that we can get MobilBert running without torch_index_select. I remembered there is a torch_index_select op in the model. I was thinking to work on torch_index_select op, so we can upstream it to MHLO repo, but I was afraid to break MobileBert.

The big difference in torch_indexe_select op is the init_tensor is derived from shaped dialect, not operands. I will take a look on the op, and see if it is easy to make it work on the new path.

**Comment by MaheshRavishankar** [comment]
I have it working locally (so I think it doesnt need torch_index_select). I think the version in Mobilbert is a gather? I am about to send a PR for a few more ops, then I'll confirm again.

**Comment by hanhanW** [comment]
A gather op will be legalized to a torch_index_select op in HLOToHLOPreprocessing.

https://github.com/google/iree/blob/4ec98bba6b67ba492a74504dbcd249d7f0bbfd10/iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp#L816

I'm happy to take a look once you send out the PR!

**Comment by benvanik** [comment]
(as an aside, it'd be nice to move that pass to `integrations/tensorflow/iree_tf_compiler/TF` so we have fewer places dramatically changing HLO IR in the main pipeline - would be a good cleanup after linalg on tensors is ready and less code is actively changing)
