### ISSUE TITLE
Better handle ops with > 3 parallel dims when creating flow.dispatch.workgroups

### ISSUE THREAD

**Issue by antiagainst** [google/iree#5048]
Although at flow level workgroups are abstract and can have any number of dimensions, at the moment we only allow tiling along <= 3 parallel dimensions when creating `flow.dispatch.workgroups`. This makes it easy to convert to HAL workgroups, which has <= 3 dimensions. 

However, it causes issues for ops like convolution, which has > 3 parallel dimensions. In order to still tile along three dimensions, right now we have special handling in `DispatchLinalgOnTensorsPass` to recognize convolution ops and omit one parallel dimension. It is not scalable and having special cases is not good. Figure out a better way to avoid this.

**Comment by MaheshRavishankar** [comment]
This is fixed now in the `DispatchLinalgOnTensors` pass. The innermost 3 dimensions of a loop are parallelized. This generalizes for all use cases we have today. Revisit this if we need to do something better here. Closing for now.
