### ISSUE TITLE
Turn vectorization on by default in GPU CodeGen

### ISSUE THREAD

**Issue by antiagainst** [google/iree#5049]
For the current path (linalg on buffers), we have vectorization controlled by a command-line option `-iree-spirv-enable-vectorization` and it's off by default. For the new path (linalg on tensors), we should turn it on by default and remove the command-line option to give us a good starting point and have vectorization well tested.

**Comment by MaheshRavishankar** [comment]
I think this is done. Closing this since its too general a description and not trackable with specific tasks
