### ISSUE TITLE
Issue in HLOToLinalgOnBuffers.cpp, function PadTensorOpConversion::apply

### ISSUE THREAD

**Issue by dpotop** [google/iree#5072]
**Context**

We develop a processor on top of iree. Our first objective, which we just attained, was to transform a function containing only mhlo operations (and return) into low-level code (object code to be linked into a larger project). To do this, our idea was to modify the pass ```iree-codegen-hlo-to-linalg-on-buffers``` in order to go all the way to linalg+std on memrefs. The meaningful code is inside file ```HLOToLinalgOnBuffers.cpp```, which defines the pass struct ConvertHLOToLinalgOnBuffersPass. The main difference w.r.t. ```ConvertHLOToLinalgOnBuffersPass``` is that we don't use the ```hal.interface``` operations for I/O. However, besides this, everything should stay the same, most notably the ```populateHLOToLinalgOnBuffersConversionPatterns``` which defines the transformations that do not touch HAL operations. 

**Describe the bug**

Our code only works if the modify function ```PadTensorOpConversion::apply``` by changing the test:
```
  if (auto cstOp = dyn_cast<ConstantOp>(inputBuffers[0].getDefiningOp())) {
```
into
```
        if (!inputBuffers[0].isa<BlockArgument>()
    	  && isa<ConstantOp>(inputBuffers[0].getDefiningOp())) {
	auto cstOp = dyn_cast<ConstantOp>(inputBuffers[0].getDefiningOp()) ;
```
The explanation is quite simple: This code lowers ```linalg.pad_tensor```, and when the first input is a constant stored in global symbols or a function input,  it must be copied.

Would it be possible to have this modification checked and upstreamed? It would save us a lot of maintenance effort by allowing the direct use of ```populateHLOToLinalgOnBuffersConversionPatterns``` (instead of a copy of the whole file).

We are on revision a51fb8ede6a2221ea1f85fdd98f917696e90ace9.

**Comment by benvanik** [comment]
Interesting - trying to understand what you're doing: you're using these passes but not the rest of IREE?
In general, the iree-codegen transforms are only expected to function from within the IREE toolchain unless it is upstreamed into MLIR or Tensorflow, and not something safe to rely on.

If you are relying on them directly you're going to want to move these passes upstream or integrate them into your project: they're implementation details of IREE and we're actually working now to delete them as we've switched to using linalg-on-tensors. This lets us lower HLO to linalg-on-tensors, and then codegen no longer knows about HLO and only takes the linalg ops. If you are using IREE then it won't look any different: HLO will be accepted during import and binaries will spit out the other side.

Since we are working to delete these passes we are unlikely to upstream them - or really, upstream would be unlikely to take them from us because we'd just be throwing them stuff over the wall and not signing up for maintaining it - so it's best that a real user drives that if it's needed.

cc @MaheshRavishankar for more context/thoughts

**Comment by dpotop** [comment]
> Interesting - trying to understand what you're doing: you're using these passes but not the rest of IREE?

Indeed, we've just used transformations of IREE as part of a flow of transformations going all the way from TF to executable single-core code (which we want to use as a baseline). The set of transforms in ```iree-codegen-hlo-to-linalg-on-buffers``` was really useful in doing this, and I hope you'll upstream its elements if you actually delete them from IREE.

**Comment by MaheshRavishankar** [comment]
As Ben mentioned, The `HLOToLinalgOnBuffersPass` is to be deprecated. Hanhan has systematically moved all MHLO -> Linalg conversions to be MHLO -> Linalg on tensors and moved them to MHLO repository. The `HLOToLinalgOnTensors` pass survives (and pulls in the MHLO -> Linalg on tensors patterns) but will probably move out of its current location to somewhere else in IREE codebase.

So if you take all the passes in `addHLOToLinalgOnTensorsPasses`, they will convert MHLO -> Linalg on tensors. This is completely IREE agnostic at this point. We could even move this as a "pre-processing step" for MHLO input and IREE will only work with Linalg on tensors.  All of this is completely IREE agnostic, and you should be able to use that.

The remaining step though has to do with Bufferization. That is a fairly involved process. IREE has two separate bufferization. One is in `Flow` for bufferization between dispatch regions and intra-dispatch region Bufferization. Ben can talk about the former, but the latter is now done using `LinalgBufferization` in `iree/compiler/Conversion/Common`. That might help a bit, but its fairly specific to IREE.  So this might get more involved for your use case.

**Comment by dpotop** [comment]
> So if you take all the passes in `addHLOToLinalgOnTensorsPasses`, they will convert MHLO -> Linalg on tensors. This is completely IREE agnostic at this point. We could even move this as a "pre-processing step" for MHLO input and IREE will only work with Linalg on tensors. All of this is completely IREE agnostic, and you should be able to use that.

On my version of IREE (2 days old, commit a51fb8ede6a2221ea1f85fdd98f917696e90ace9), translating a stock RESNET (quite standard NN) with the passes of ```addHLOToLinalgOnTensorsPasses``` still leaves ```mhlo.reduce_window``` unlowered. This is why we needed the transformations of the ```addHLOToLinalgOnBuffersPasses```pipeline. :)

**Comment by MaheshRavishankar** [comment]
I think ToT now uses the mhlo.reduce_window -> linalg::Pooling* on tensors.

**Comment by hanhanW** [comment]
Yes, ToT now uses  mhlo.reduce_window -> linalg::Pooling* on tensors, see https://github.com/google/iree/commit/4ec98bba6b67ba492a74504dbcd249d7f0bbfd10. And I upstreamed the patterns to MHLO repo yesterday. They will be removed from IREE soon (once the integration happens).

**Comment by MaheshRavishankar** [comment]
@dpotop I am closing this for now. Please let us know if you have any more issues here.
