### ISSUE TITLE
Finish automating python wheel release pipeline

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#5093]
Most of the Python release pipeline is automated, presently excluding some testing and actually flipping the draft flag on the release once smoke tests pass. We should finish this and then also set a reminder to check/triage this weekly, manually publishing if needed. This might also be a good cadence for uploading binary packages to pypa (multi-time per day snapshots seems excessive, but weekly snapshots might be nice).

**Comment by ScottTodd** [comment]
New issues were filed for the automation mentioned here: https://github.com/google/iree/issues/6315, https://github.com/google/iree/issues/6316.

PyPI and other "official" releases on a less frequent basis are still TBD.
