### ISSUE TITLE
Evaluate a VMLA replacement

### ISSUE THREAD

**Issue by benvanik** [google/iree#5123]
VMLA has always forked off quite early in the compilation flow from codegen (HLO) but with linalg-on-tensors landing and HLO being moved higher up in the stack (eventually outside of IREE entirely) it becomes an even bigger issue. This issue is tracking how to preserve the benefits we get from having VMLA as a reference backend while aligning closer with our other codegen targets (SPIRV, PTX, LLVM) to unwind the divergence in paths.

Key benefits of a VM-based reference backend (currently VMLA):
* built on our VM, so no external dependencies
* runs anywhere C and the rest of IREE runs
* extremely low overhead (KB of RAM and ROM) so usable for bringup on embedded devices
* 1:1 with the MLIR, no additional toolchain to debug if there are issues
* easy to add new methods as no external frameworks/libraries/compilers/runtimes need to be modified

VMLA is really two parts: the use of the IREE VM for calling functions and managing values and the VMLA module exporting a set of HLO-like operations. That the IREE VM is used is orthogonal to what the VMLA set of functions are: it's possible to use the VMLA functions with the VM running via emitc or via a completely different route (VM->LLVM AOT, wasm, etc). What's important to this issue is what the set of functions is and how we get to that set via the common codegen path in IREE. How those functions are called may change over time (or have multiple routes to get to it).

One route we can go is to simplify things and ignore the vector dialect: instead, we would lower to std+scf+math by scalarizing all of the vector ops (I believe there is a pass that does this). We can then use the VM builtins for control flow and basic arithmetic (loops, etc), add the planned but not yet implemented f32 extension to the VM for scalar math (~10-15 simple instructions [here](https://github.com/google/iree/blob/416891602125f4cd244e226338793150bfc46f4f/iree/vm/bytecode_dispatch.c#L1457-L1458) like the I64 above it), and then dump any helpers we need for fancier math into a math module we can reuse. This won't be fast, but it could be a good baseline to bring up and would always provide a fallback. It would flesh out the compiler path for a sibling target to SPIRV & co that takes in the vector dialect.

A follow-on to that - or maybe something even easier to do together - is picking some of the vector ops and mapping those to functions on the new module. In this way we would be treating the VM+module as a virtual variable-length vector ISA. While still in the vector dialect with nice `vector<>` types we have simple patterns that turn them into `foo.vector.*` ops, similar to how we do HLO->VMLA today. The set of ops is rather small, and we can use similar ones to LLVM to allow us to rip off those patterns. There's also some standard (or now "math"?) ops that operate on vectors, but the set is reasonable (add, div, etc).

Here's some relevant tests showing the vector ops:
* [vector.reduction -> llvm.intr.vector.reduce.*](https://github.com/llvm/llvm-project/blob/ba87f99168c93461b28a4aa2d05e238ff774d57a/mlir/test/Conversion/VectorToLLVM/vector-reduction-to-llvm.mlir#L12-L22) ([llvm intrinsics](https://llvm.org/docs/LangRef.html#vector-reduction-intrinsics))
* [vector.matrix_multiply -> llvm.intr.matrix.multiply](https://github.com/llvm/llvm-project/blob/df5ccf5a94ad04231e8426dd0d02689a0717453b/mlir/test/Conversion/VectorToLLVM/vector-to-llvm.mlir#L1026-L1035) ([llvm intrinsics](https://llvm.org/docs/LangRef.html#matrix-intrinsics))

A lot of the ops in vector->llvm above are optional; for example, all the masked stuff is something we could punt on and legalize away in the future (the current SPIRV path doesn't support these, for example). The lowerings to LLVM for a lot of the operations are also lower level than we need. Instead, things like vector.transfer_read may map directly to our module ops just like above. We could also rip off patterns from the SPIRV world, where the load/store semantics are much higher level than LLVM and more of what we want:
https://github.com/google/iree/blob/416891602125f4cd244e226338793150bfc46f4f/iree/compiler/Conversion/LinalgToSPIRV/test/vector_to_gpu.mlir#L3-L20

One of the few open questions is how to represent the vectors in the VM. The easiest thing is to have a `!foo.vector<...>` type that is backed by stack memory. We'd then take the memrefs that float around, bufferize them using the upstream bufferization (or whatever ntv@ is doing now in his sandbox), and then load/store memref<->vector is something we externalize. This may also solve issues with wasm sandboxing, as a fat call for a full load of a large vector wouldn't be prohibitively expensive (compared to fat calls for every byte read/written).

I think it may be useful to stand up a skeleton of the required components and then work bottoms-up to start eating away at the incoming IR:
* [x] pick a name
* [x] add a new top-level IREE dialect with that name - which would also have the vm imports.mlir file
* [x] add a new IREE HAL target backend with a dummy pass pipeline
* [x] add a new `iree/modules/` native module
* [x] add a new `iree/hal/local/` loader (like the vmla loader) that wires the two together

From there, we can start fleshing out the pass pipeline to go from linalg-on-tensors down to vector+scf, scf->std, std->vm, and producing the final VM binary. We should be able to get a no-op executable running end-to-end.

From there we solve some of the first issues:
* [x] hal.interface.* goo (like vmla)
* [x] memref -> !foo.buffer, add type at runtime
* [x] vector -> !foo.vector, add type at runtime
* [x] vector load/store ops
* [ ] pick a vector op to prototype (matrix multiply, reduce, etc) and plumb it through

The long tail after that is finding out the ~10 other vector ops we need, the ~10-15 std/math ops on vectors, and plumbing those through to runtime. Most will fall into the unary/binary/ternary template category and be fast to plumb.

**Comment by GMNGeoffrey** [comment]
+1 for the value of having a simple backend that doesn't have any toolchain/driver/whatever deps. I've really appreciated having a reference backend. Not sure if this would be prohibitively slow, but do we need the vector part of this? Could we just unroll linalg generics to loops of std/math/whatever scalar ops and then implement the handful of scalar ops?

**Comment by benvanik** [comment]
Yep! That's the base approach with the vector stuff being something we sprinkle in where required. Many cases probably won't matter _too_ much, but matmul and conv in particular are dealbreakers (like 1000x slower, minutes+ to run kind of bad). Those are the easiest vector ops to snoop on, though, as they'll end up being a 1:1 replaceOpWithNewOp. The more complex vector stuff (masked operations, reductions, etc) are all just optimizations we can do as needed. One benefit we'll have here is that we'll be able to run VMLA multithreaded, so even if it's 4x slower than the old C++ kernels if you run it on 4 threads you'll end up about the same :P

**Comment by asaadaldien** [comment]
Thanks for the great (as always :)) write up Ben, I think we can very quickly bring up scalar pass then we add the vector intrinsic support later once we solve the `hal.interface`, `memref -> !our_new_dialect.buffer` and have the scalar part running smoothly (You know it feels good getting the X- perf :p)

Its going to be very interesting looking at performance of the VM executing `STD` level IR specially the good performance we have on other backends relays on the good and very heavy optimization done at LLVM and later codegen for that particular backends (e.g aarch64 backends eliminates  transposes in some cases by vertical loads registers + broadcast). which might build a case for MLIR level optimizations (VM-O3 !?).

**Comment by benvanik** [comment]
The VM will never be fast as it's just a simple interpreter and WASM with a full JIT will be much faster but still not native (1-5x slower depending on the instruction mix) - so I can confidently say we will need a bulk of the larger operations to be the variable-length vector style. We'll want to plan less for how to perform optimizations on the VM and more for how to represent them as variable-length vector intrinsics (which should hopefully be easy to get out of the vector dialect). We lose a lot of the value here if we have to build out a big code path/significant custom optimizations/etc that's specific to this target or the VM - the goal is to slice off the common path and add as little as possible to it :)

Knowing what those intrinsic-style calls are like is important as it determines how we represent data (like `!vmla.buffer`) and we want to have that in mind as we setup all the stuff. We don't need to know the exact set, but having at least one will ensure we are building something that scales out to the rest instead of something that only works for the ultra-slow path that we know we can't use (full scalars running raw on VM). Like, "how do we get elementwise add + mul + tanh into something that uses add/mul/tanh intrinsics instead of a scalar loop" is the real hard/fun question we need to stitch together - everything after that is just plumbing :)

**Comment by benvanik** [comment]
I've done a first pass and think I have a decent idea of where the dragons lie and have a good portion of the plumbing done. There's some larger specific issues to work out that I'll file dedicated issues for and I'll work to land the skeleton ASAP so we have something to iterate on.

**Comment by benvanik** [comment]
Filed some enhancements that are generally good things (both for normal host VM and VMVX use):
* #5544: Add fused VM ops for common sequences of addressing arithmetic.
* #5545: Add a few dedicated bytecode->module shims for faster calls.
* #5546: Implement the F32/F64 VM instruction extensions.

**Comment by benvanik** [comment]
Created a project to track: https://github.com/google/iree/projects/30

And filed the major work items that'll follow after the skeleton:
* #5547: Upstream improvements for scf.for folding on loop ranges.
* #5548: Get work distribution working properly for VMVX (and others).
* #5549: Lower vectors into VMVX.

These are things we'll want to brainstorm on and some may just resolve themselves with work already in-flight (like #5548 that ahmed may already be fixing for the LLVM path).

**Comment by benvanik** [comment]
VMVX is landing; going to close this and focus on the required improvements in #5880.
