### ISSUE TITLE
Doc build failing on generated ir_examples

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#5124]
The page build failed for the `gh-pages` branch with the following error:

The tag `{%` on line 419 in `docs/ir_examples/dynamic-mhlo-dot-vmla.md` was not properly closed with `%}`. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#tag-not-properly-terminated.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request at https://support.github.com/contact?repo_id=208145128&page_build_id=240128759

You can also see the failure in the project settings tab: https://github.com/google/iree/settings

**Comment by ScottTodd** [comment]
One of the problematic lines is
```
    %20 = flow.dispatch @dot_ex_dispatch_0::@dot_ex_dispatch_0[%5](%8, %9, %6, %10, %11, %7, %12, %13) : (index, index, tensor<?x?xf32>{%14, %15}, index, index, tensor<?x?xf32>{%16, %17}, index, index) -> tensor<?x?xf32>{%18, %19}
```

this is within a code block, but some preprocessor through Jekyll is still seeing `{%` and thinking "oh! that's for me! ... wait, where's the `%}`?".

**Comment by benvanik** [comment]
🤦 

`{%DROP ALL TABLES...`

**Comment by ScottTodd** [comment]
One idea to try: https://stackoverflow.com/questions/24102498/escaping-double-curly-braces-inside-a-markdown-code-block-in-jekyll. Maybe we could also escape the `{%`s explicitly.

**Comment by ScottTodd** [comment]
Okay, I don't quite understand `sed` well enough to #testinprod a fix to https://github.com/google/iree/blob/46e8331f0ac66c75e0f9ac789e9397e93d36d12f/build_tools/cmake/build_docs.sh#L104-L109

so I think I'll need to build the docs locally (see [instructions here](https://github.com/google/iree/tree/gh-pages#how-to-update-documentation)) to iterate a bit. Unless someone else wants to try ;D

It looks like wrapping our code blocks there with `{% raw %} ... {% endraw %}` should do the trick.

**Comment by antiagainst** [comment]
Thanks @ScottTodd for fixing this! :D
