### ISSUE TITLE
Move `subtensor` operations into dispatch regions instead of always creating `flow.tensor.slice`

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#5131]
PR #5130 adds support for lowering `subtensor` operations to `flow.dispatch.slice` operations when the slice is known to be contiguous so that they could be handled outside of dispatch regions. The reason for this is due to the following sequence of instructions at the end of Bert model [here](https://github.com/google/iree/blob/main/iree/test/e2e/models/bert_encoder_unrolled_fake_weights.mlir)

```
    %5389 = "mhlo.slice"(%5388) {limit_indices = dense<[1, 1, 384]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<1> : tensor<3xi64>} : (tensor<2x1x384xf32>) -> tensor<1x1x384xf32>
    %5390 = "mhlo.reshape"(%5389) : (tensor<1x1x384xf32>) -> tensor<1x384xf32>
    %5391 = "mhlo.slice"(%5388) {limit_indices = dense<[2, 1, 384]> : tensor<3xi64>, start_indices = dense<[1, 0, 0]> : tensor<3xi64>, strides = dense<1> : tensor<3xi64>} : (tensor<2x1x384xf32>) -> tensor<1x1x384xf32>
    %5392 = "mhlo.reshape"(%5391) : (tensor<1x1x384xf32>) -> tensor<1x384xf32>
    check.expect_almost_eq_const(%5390, dense<895.256> : tensor<1x384xf32>) : tensor<1x384xf32>
    check.expect_almost_eq_const(%5392, dense<895.256> : tensor<1x384xf32>) : tensor<1x384xf32>
```

If the `subtensor` is left as is (i.e not converted to `flow.tensor.slice`) then this results in dispatch regions of the form

```
%1 = constant 1 : index
%s = subtensor %v[1, 0, 0] [1, 1, 384] [1, 1, 1] : tensor<2x1x384xf32> to tensor<1x1x384xf32>
%r = linalg.tensor_reshape %s [affine_map<(d0, d1, d2) -> (d0, d1)>, affine_map<(d0, d1, d2) -> (d2)>]
     : tensor<1x1x384xf32> to tensor<1x384xf32>
```

which post bufferization would be
```
#map0 = affine_map<(d0, d1, d2) -> (384 + 384 * d0 + 384 * d1 + d2)>
%s = subview %v_buffer[1, 0, 0] [1, 1, 384] [1, 1, 1]
    : memref<2x1x384xf32> to memref<1x1x384xf32, #map0>
%r = linalg.reshape %s [affine_map<(d0, d1, d2) -> (d0, d1)>, affine_map<(d0, d1, d2) -> (d2)>]
     : memref<1x1x384xf32, #map0> to ...
```
here the `linalg.reshape` is illegal because the source cannot have reassociation maps. The solution here is that during the `subtensor` to `subview` conversion the `#map0` in the result type of the `subview` needs to be dropped. This could be done in two ways
1) Change the `subview` op build methods where the inferred type does not add the reassociation maps to the result type for cases above, i.e. its a pure pointer offset and the result is a contiguous within the source `memref`. This though interacts poorly with the way `subview` is lowered to LLVM using Memref descriptors.
2) Insert a `memref.cast` operation to drop the reassociation map. This should keep the LLVM lowering happy and the memref cast is a no-op. Unfortunately, the memref cast does not like the reassociation map to be dropped.

This is an upstream issue, and needs to be resolved. The solution in PR #5130 allows for us to side-step this. Downside of this though is that `flow.dispatch.slice` is lowered to a copy, which is not necessary. So this overhead can be removed to not use a copy but just return the a (pointer +offset) on the source buffer (at least in cases where the source buffer has no more uses).

**Comment by MaheshRavishankar** [comment]
@benvanik for visibility on the issue with the flow side.

@nicolasvasilache  for pointers to how to resolve the issue with reassociation maps upstream (I got lost in the memref descriptor code of lowering `subview` to LLVM

**Comment by benvanik** [comment]
RE the `flow.dispatch.slice` copy: that'll go away with buffer allocation in most cases (like the one in the example above) - the copy you have in #5130 is a correctness thing but the optimization is fairly straightforward (it shares the same behavior with all the other operations).

There is a (mostly unimplemented, like `flow.tensor.slice`) `flow.tensor.reshape` that is meant to handle this particular case (add/remove dimensions). The intent there was to allow for aliasing when possible while still handling dynamic shape cases and such; it predates tied results and could be extended with that and the verification that the reshape is not changing element count and such. It's of course better if you can get rid of reshapes in linalg land prior to dispatch region formation (propagating shapes around, etc), but `flow.tensor.reshape` will be the best for standalone things that can't be folded (even if you can form a dispatch region that is a no-op that'll still be 10000x more overhead than just doing nothing by letting the `flow.tensor.reshape` pass along a pointer :). That said, it's a similar case to the DMA operations and may be something we want to handle like that (if there's a flow.dispatch.workgroups that just reshapes then convert that to `flow.tensor.reshape`, etc).

**Comment by MaheshRavishankar** [comment]
Current dispatch region creation handles this correctly. When possible it lowers a `subtensor` to a `flow.tensor.slice`. Otherwise the `subtensor` is moved into a dispatch region and fused wherever possible. 

@benvanik dropping this from the codegen project (cause there is nothing to do there for this part right now). If you want to keep this to track not always doing a copy, thats fine. If not, please close it.
