### ISSUE TITLE
Problem when exporting MHLO MLIR and lowering it down to bytecode

### ISSUE THREAD

**Issue by nick-furry** [google/iree#5132]
I'm trying to export a MHLO MLIR file of a model from Tensorflow model zoo and lower it down to bytecode (vmla backend). 

I generated the MLIR file of MobileNetv3 following instructions at this link https://google.github.io/iree/developing-iree/e2e-benchmarking using `iree/integrations/tensorflow/e2e/keras/applications/applications_test.py`. 

After this I tried lowering this generated MLIR file to bytecode using `iree-translate` as follows:
`./iree-translate -iree-mlir-to-vm-bytecode-module -iree-hal-target-backends=vmla -iree-flow-dispatch-linalg-on-tensors mobilenet.mlir -o mobilenet_bytecode_module.module` 

But the conversion fails with error message starting with:
```
<unknown>:0: error: failed to legalize operation 'hal.interface.binding.subspan' that was explicitly marked illegal
<unknown>:0: note: see current operation: %0 = "hal.interface.binding.subspan"(%c0) {binding = @legacy_io::@arg0} : (index) -> !flow.dispatch.input<1x224x224x3xf32>
<unknown>:0: error: conversion to the VMLA dialect failed
```

Am I missing any relevant flags to iree-translate or is my way of generating MLIR file itself is wrong?

Thank you.

**Comment by hanhanW** [comment]
The Linalg on tensors path is not stable yet. And I think it doesn't work with VMLA.

If you are targeting on VMLA, maybe try this: `./iree-translate -iree-mlir-to-vm-bytecode-module -iree-hal-target-backends=vmla mobilenet.mlir -o mobilenet_bytecode_module.module`.

**Comment by nick-furry** [comment]
That worked, thank you for the clarification.

**Comment by nick-furry** [comment]
The exported MHLO MLIR has `loc(#loc<num>)` appended to every op and each `loc<num>` references `tensorflow/python/eager/function.py` of current environment. Example:
```
#loc10 = loc(callsite("MobilenetV3small/tf.__operators__.add_97/AddV2@__inference_<lambda>_13622"("/home/python3.8/site-packages/tensorflow/python/keras/engine/functional.py":424:0) at callsite("/home/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py":1012:0 at callsite("integrations/tensorflow/e2e/keras/applications/applications_test.py":95:0 at callsite("/home/python3.8/site-packages/tensorflow/python/autograph/core/function_wrappers.py":117:0 at callsite("integrations/tensorflow/e2e/keras/applications/applications_test.py":95:0 at callsite("/home/python3.8/site-packages/tensorflow/python/framework/func_graph.py":966:0 at callsite("/home/python3.8/site-packages/tensorflow/python/eager/def_function.py":634:0 at callsite("/home/python3.8/site-packages/tensorflow/python/framework/func_graph.py":990:0 at callsite("/home/python3.8/site-packages/tensorflow/python/eager/function.py":3196:0 at "/home/python3.8/site-packages/tensorflow/python/eager/function.py":3361:0))))))))))
```
Is there a way to generate MLIR file that doesn't have these hardcoded paths and thus is portable?

Thank you

**Comment by hanhanW** [comment]
I personally pass it to `iree-opt` to re-generate the IR. E.g., `./iree-opt a.mlir > b.mlir`.

**Comment by benvanik** [comment]
Any idea @stellaraccident? Is there a flag to disable emitting the locations or enable reproducable builds on the tf-side?

**Comment by stellaraccident** [comment]
It's akin to debug symbols and shouldn't be hurting anything. There is not a flag to control it, but one can be added: iree-tf-import-main, line 184 is what enables it. Patches welcome.

**Comment by benvanik** [comment]
ah I was looking for that but in the python files - thanks!

Yeah, this should only be an issue if you a) don't want to leak paths from build machines (in which case, the final IREE outputs can be stripped) b) want to be able to perform reproducable builds (for caching intermediate artifacts, etc). But as Stella mentions there should be no change in program behavior from these and no issue with portability.

**Comment by nick-furry** [comment]
I tried passing it through `iree-opt` and that helped. Thanks everyone!
