### ISSUE TITLE
depthwise_conv_2d_input_nhwc_filter_hwcf is not supported in Linalg on tensors

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5154]
This operation is important and shows up in many integration tests. Unfortunately, we even don't have an end-to-end tests for this. We should support this operation, and add more tests for it.

**Comment by antiagainst** [comment]
+1. I'd assume it's relatively easy to plumb this through given it's quite similar to `linalg.depthwise_conv_2d_input_nhwc_filter_hwc`.

**Comment by hanhanW** [comment]
Yes, that is what I'm thinking too! I will add more tests around this!

**Comment by hanhanW** [comment]
Fixed in https://github.com/google/iree/pull/5189
