### ISSUE TITLE
Proposed simplification of iree_status_allocate_vf() api

### ISSUE THREAD

**Issue by ewconnell** [google/iree#5184]
The `iree_status_allocate_vf` function signature is currently 
```C
IREE_API_EXPORT IREE_MUST_USE_RESULT iree_status_t IREE_API_CALL
iree_status_allocate_vf(iree_status_code_t code, const char* file,
                        uint32_t line, const char* format, va_list varargs_0,
                        va_list varargs_1)
```
It has two va_list arguments due to the internal implementation requirements. 
I propose we remove `varargs_1` and simply do a `va_copy` on function entry. I looked at the implementations of `va_start` and `va_copy` and this will actually be less work than the current implementation's creating two `va_lists`. It will also make the public api more sensible for callers.
```C
IREE_API_EXPORT IREE_MUST_USE_RESULT iree_status_t IREE_API_CALL
iree_status_allocate_vf(iree_status_code_t code, const char* file,
                        uint32_t line, const char* format, va_list varargs_0)
  // make a copy so we can walk the arguments once to determine storage size
  // and once to print the values.
  va_list varargs_1;
  va_copy(varargs_1, varargs_0);
```
I have already implemented this and it seems to work correctly.

**Comment by benvanik** [comment]
Cool - had no idea va_copy existed - that's a great improvement!

**Comment by ewconnell** [comment]
I will need to make a variation on my fix to make sure that the va_end is called on the copy, since these functions have multiple returns and C has no `defer` statement. I will make the changes for your review.
