### ISSUE TITLE
MobileNet V2 can't be compiled toward valhall-g77-unknown-android10 in Linalg on tensors

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5190]
**Describe the bug**
The model can be compiled with `--iree-vulkan-target-triple=qualcomm-adreno640-unknown-android10`, but not `--iree-vulkan-target-triple=valhall-g77-unknown-android10`.

I found this when I tried to add new metrics for Linalg on tensors path to benchmark infra. This is not urgent. I filed this for tracking the issue. Assign to @antiagainst since he has been working on MobileNet V2.

**To Reproduce**

1. Download the model from https://storage.googleapis.com/iree-model-artifacts/mobilenet-v2.tar.gz
2. Run `iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vulkan-spirv -o a.vmfb --iree-vulkan-target-triple=valhall-g77-unknown-android10 -iree-flow-dispatch-linalg-on-tensors -iree-codegen-spirv-experimental-linalg-on-tensors mobilenet-v2/iree_input.mlir`

**Comment by antiagainst** [comment]
I think you missed `-iree-spirv-enable-vectorization` in the command line options. Note that we will turn on vectorization by default in the new tensor-based path.

**Comment by antiagainst** [comment]
Verified that with vectorization turned on it works.

**Comment by hanhanW** [comment]
I was not aware that turning vectorization off would affect the success of compilation, but I guess maybe #5187 fixed it... Anyway, thanks for looking into this.
