### ISSUE TITLE
Allow filtering which CMake test targets are configured and built

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#5192]
<sub>Filing after [a discussion on Discord](https://discord.com/channels/689900678990135345/690274711523164166/821505739913953320).</sub>

Our `check` test targets (mostly under [iree/test/e2e/](https://github.com/google/iree/tree/main/iree/test/e2e)) invoke our compiler as a build step then run the compiled module at test time, checking for correctness in the outputs<sup>[1]</sup>.

What's especially painful for development is that we have a growing number of larger tests at [iree/test/e2e/models](https://github.com/google/iree/tree/main/iree/test/e2e/models) that can take on the order of 5-10 *minutes* to compile in `DEBUG` configurations, even on powerful development machines.

I propose we add test size tags, mirrored between Bazel and CMake, then add a CMake option that controls which sizes of tests are enabled. Developers using debug builds can then opt-out of building large tests, build bots could run smoketests on only small tests or choose to run large tests only on post-submit.

Bazel has some common test size labels documented [here](https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-tests) and [here](https://docs.bazel.build/versions/master/test-encyclopedia.html#role-of-the-test-runner):

| Size | Default timeout |
| --- | --- |
| small | short (1 minute) |
| medium | moderate (5 minutes) |
| large | long (15 minutes) |
| enormous | eternal (60 minutes) |

I'm not aware of a similar concept for CMake/ctest, particularly since the size is an issue at _build_ time for us, not (just) at test time.

---

<sup>[1]</sup>A separate side effect is that compile errors are treated as build failures instead of test failures, which blocks building the full list of targets (the default with `cmake --build`).

**Comment by GMNGeoffrey** [comment]
Another thought. We could enable users to provide a separate build configuration for these host tools. Bazel has this built in, where tools that run as part of the build are built with optimizations. I don't want to do that (it is totally reasonable to want to run this compilation in debug mode and we got rid of magical double-invocation), but it would be nice if someone working on the runtime could build the compiler once with optimizations and then reference those tools.

I don't think we should incorporate the build time into what we use as the test size or timeout. (though I do support adding test timeouts in general). Honestly the whole notion of test sizes is so confused and conflates so many different things, that I would prefer that we just explicitly set timeouts and whatever other features we care about.  I would use a different way to categorize these. Like right now we could just call these "model tests" and exclude them.

**Comment by benvanik** [comment]
I still think we should fix/file bugs upstream/etc the cause of these being 1000x slower than release mode - that'll help everyone. There's no reason for our builds to be this slow: we're compiling IR with a few hundred ops.

**Comment by ScottTodd** [comment]
> I don't think we should incorporate the build time into what we use as the test size or timeout. (though I do support adding test timeouts in general).

Yeah, let's keep timeouts separate from this (e.g. https://github.com/google/iree/issues/5121)

> I would use a different way to categorize these. Like right now we could just call these "model tests" and exclude them.

(also discussed offline) Yeah, the Bazel `size` label brings a bunch of baggage with it from Google's infrastructure. I still would prefer to use a label in some way, since I want to avoid having more special cases where a block of CMake for one directory is skipped if some option is set. With labels we can have `iree_check_test` handle that logic.

> I still think we should fix/file bugs upstream/etc the cause of these being 1000x slower than release mode - that'll help everyone. There's no reason for our builds to be this slow: we're compiling IR with a few hundred ops.

Definitely. However, I think even with speedups, it would still be useful to give a way to enable/disable larger tests.

**Comment by GMNGeoffrey** [comment]
One component of this that I think factors into our larger test infra discussion is that this is a case where compilation is kind of part of the test, but we want it to be run separately and on the host (and in Bazel land, cached and such is nice). "Normally" you aren't testing or editing compilation like this so you don't expect failures and you can also do the compilation using some prebuilt tool (like we're not building clang from source in debug mode for our C++ test compilation either).

**Comment by ScottTodd** [comment]
I had another idea this morning: add a CMake option for filtering targets/tests at configure time, like `EXCLUDE_FROM_ALL` but through options (not requiring changes to `CMakeLists.txt` files). Then I could filter out `iree/test/e2e/`, specific subdirectories, etc. with full flexibility.

**Comment by GMNGeoffrey** [comment]
I like that. Would it completely disable configuring that target, or just exclude it from the default target? The problem with completely disabling for configuring is that you'd have to make sure to disable all things that depended on it as well. We could conditionally set `EXCLUDE_FROM_ALL` on targets using this mechanism though, which means they would still be configured, but not necessarily built in the default target.

OTOH completely disabling is nice if you know you really don't want something and you want it to just error out if it's somehow required. I kind of like the idea of having both:

```cmake
function(iree_configure_target_build_options TARGET_NAME)
  if ("${TARGET_NAME}" MATCHES "${IREE_EXCLUDE_FROM_DEFAULT_REGEX}")
	set_property(TARGET ${TARGET_NAME} PROPERTY EXCLUDE_FROM_ALL ON)
  endif()
endfunction()

macro(iree_maybe_disable NAME)
  if ("${NAME}" MATCHES "${IREE_DISABLE_REGEX}")
	# This is a macro so returns from calling function's scope.
	return()
  endif()
endmacro()
```

Our current target and test naming conventions are a bit confusing IMO. We used to have test names == target names, but now tests have slashes and targets have underscores I think. We do a lot of name mangling between the various types. This would be a good chance to clean some of that up maybe. Before making names load-bearing.

The disable could be only per-directory, which might be more straightforward

**Comment by ScottTodd** [comment]
> The disable could be only per-directory, which might be more straightforward

A per directory disable would mean adding some new code to the top of every file. I guess we could piggyback off of `iree_add_all_subdirs()` (either renaming it to cover a broader set of tasks, or adding a new standard line above it).

The other direction would be to sprinkle those functions/macros in our helpers at https://github.com/google/iree/tree/main/build_tools/cmake. I see this mostly being used for large tests (`iree_check_test`), but we could add it everywhere for consistency.

**Comment by ScottTodd** [comment]
https://github.com/google/iree/pull/8423 marking `test/e2e/` targets as `EXCLUDE_FROM_ALL` and moving them to an explicit `iree-test-deps` target may be enough for this. I hesitate to add more complexity (test size tags or more configurable filtering) unless it's needed
