### ISSUE TITLE
failed to legalize operation 'memref.alloc' on GPU in Linalg on Tensors

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5206]
**Describe the bug**
Some `memref.alloc` will be generated in LinalgBufferizePass. And they do not go away in later passes. I feel that they are some promotion stuff. Because it allocates a buffer and copies the result of `memref.subview` to the allocated buffer.

The full log can be found at https://gist.github.com/hanhanW/d170e9d0372ca4af50eb63be9d0bc6a0

I did not see the issue last week. This is a new failure and was not detected due to lacking tests.
I verified that it starts failing from https://github.com/google/iree/commit/9f968d0cf213d181f37d3a5d6f617e4443ea8d7b
It is passing at https://github.com/google/iree/commit/79b8fbf224275a1bc2b557e57f6ad1ad347d1f6f

Before "Tile and distribute linalg.generic in DispatchLinalgOnTensors" was introduced, the pass won't generate any memref.alloc ops. 

@MaheshRavishankar @ThomasRaoux any clues on this?

note: this only happens on vulkan path. It is doing fine on cpu path.

**To Reproduce**

Run `iree-run-mlir iree/test/e2e/models/edge_detection.mlir -export-all -iree-hal-target-backends=vulkan-spirv -function-input="1x128x128x1xf32" -iree-flow-dispatch-linalg-on-tensors -iree-codegen-spirv-experimental-linalg-on-tensors`

**Comment by MaheshRavishankar** [comment]
Seems to be an issue with bufferization. Ill take this one.

**Comment by hanhanW** [comment]
note: the end-to-end test will be added in #5306
