### ISSUE TITLE
iree-translate does not generate identical IREE module on vulkan-spirv backend

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5216]
**Describe the bug**

I'm seeing different performance on Tracy with and without `--iree-hal-benchmark-dispatch-repeat-count=1`. The default value is `1`, so it should not change any behavior. Then I found that the generated IREE module is not identical. Should `iree-translate` always generates identical IREE modules given the same input and the same command?

 I verified that it does on VMLA and dylib-llvm-aot, but not vulkan-spirv.

**To Reproduce**

```
$ iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vulkan-spirv iree/test/e2e/models/mobilenetv2_fake_weights.mlir -o a.vmfb
$ iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vulkan-spirv iree/test/e2e/models/mobilenetv2_fake_weights.mlir -o b.vmfb
$ diff a.vmfb b.vmfb
Binary files a.vmfb and b.vmfb differ
```

**Comment by hanhanW** [comment]
It looks like symbol names are different?

I tested with simple abs.mlir file, xxd the modules and found this:

one is `ce_var_110228624__` and another is `ce_var_110947328__`.
one is `source_var_110216464__` and another is `source_var_110935168__`.
one is `__resource_var_140261758471744__` and another is `__resource_var_140298735454080__`

(I do not know where they come from.)

**Comment by MaheshRavishankar** [comment]
That is coming from the ConverToSPIRV pass [here](https://github.com/google/iree/blob/603b208f623e65eb48d8594c4ffc4218f36f41f5/iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp#L167) . Basically pointer value serialized to generate the name. Maybe not a good thing.

**Comment by benvanik** [comment]
Yeah, definitely not a good thing - but a good catch!

**Comment by antiagainst** [comment]
Yup. The logic is there to handle resource aliases, because we have patterns in the existing buffer-based CodeGen path that mutate placeholder ops by giving them different types. Aliases are generally bad and we should avoid. Now the whole world is changing they might not be needed. Need to check on the tensor path. At least we can have a better global naming scheme.

**Comment by MaheshRavishankar** [comment]
The new path is also using `hal.interface.binding.subspan ... : memref<...>`. That could potentially also alias resources. So the pass itself needs to pick deterministic names. THere is nothing you can do really before that.
