### ISSUE TITLE
Wrong outputs while inferencing with MobilenetV3Small MLIR

### ISSUE THREAD

**Issue by nick-furry** [google/iree#5224]
I'm trying to perform inference using MobilenetV3Small (akin to https://github.com/google/iree/blob/main/iree/samples/simple_embedding/simple_embedding_test.cc) with MLIR file being generated using this script (https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/keras/applications/applications_test.py). I made sure to pass the `use_external_weights` flag to save the weights as well. 

However, no matter what input image I provide I get the same values (wrong) as inference result.

**Comment by benvanik** [comment]
We'll need a bit more info to reproduce and help - such as the code you are using to invoke the model. There's too many ways things could go wonky to guess :)

**Comment by nick-furry** [comment]
Steps to reproduce:
I generated the MLIR file by the following steps. I have attached MLIR file, so these steps can be skipped unless there's something wring with the generation

1. Cloning IREE repo and installing dependencies in virtual environment:
``` 
>> git clone https://github.com/google/iree.git
>> cd iree
>> git submodule update --init
>> python3 -m venv iree_env && source iree_env/bin/activate
>> pip install wheel tensorflow-gpu
>> pip install iree-compiler-snapshot iree-runtime-snapshot iree-tools-tf-snapshot -f https://github.com/google/iree/releases
```

2. Building IREE and installing python packages. Remember to specify install directory:
```
>> mkdir install && mkdir build && cd build
>> cmake -G Ninja -DIREE_BUILD_COMPILER=ON -DIREE_BUILD_TESTS=ON -DIREE_ENABLE_MLIR=ON -DIREE_ENABLE_TENSORFLOW=ON -DIREE_BUILD_PYTHON_BINDINGS=ON -DCMAKE_INSTALL_PREFIX=/path/to/install -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11 .. && ninja install
>> cd ./../install/python_packages/iree_compiler
>> python setup.py install
>> python -m pip wheel .
```

3. To generate MLIR artifacts:
```
>> cd ./../../..
>> python ./integrations/tensorflow/e2e/keras/applications/applications_test.py  --target_backends=iree_vmla --model=MobileNetV3Small --data=imagenet --use_external_weights
>> /iree/install/path/bin/iree-opt /tmp/iree/modules/MobileNetV3Small/imagenet/iree_input.mlir > mobilenet.mlir
```

The following link contains .zip file that contains a folder which is self-contained to do inference. [mobilenet.zip](https://github.com/google/iree/files/6200148/mobilenet.zip)

Simply place the folder in `iree/iree/samples` and build IREE to generate the executable.

**Comment by benvanik** [comment]
Thanks for the code - that made it easy to spot :)

```c
  IREE_ASSERT_OK(iree_hal_buffer_fill(arg_buffer, 0, IREE_WHOLE_BUFFER,
                                      &imgData, sizeof(float)));
```

That is just taking the first float of imgData and splatting it out over the entire buffer (like memset) - so you're just running the model with whatever channel 0 of pixel 0 is :)

You want `iree_hal_buffer_write_data` (which will write a span of bytes into a buffer):
```c
iree_hal_buffer_write_data(arg_buffer, 0, imgData, sizeof(float) * kElementCount);
```

This may not be the only issue - but it's a start :)

**Comment by benvanik** [comment]
Oh yeah, that is part of the problem - the other is that imgData is not going to work like that (vector of vector of vector of vector) - std::vector is a C++ type with random fields in it, where instead you want densely packed data.

So flatten out imgData into a single `std::vector<float>`, and then pass the underlying buffer:
```c
std::vector<float> imgData(kElementCount);
// fill it
iree_hal_buffer_write_data(arg_buffer, 0, imgData.data(), imgData.size());
```

**Comment by nick-furry** [comment]
Thank you for your inputs. I did the recommended changes and thankfully the output values have changed. However the values are still not equal to the ground truth. I flatteneed the data to RGB values (row-wise).

**Comment by benvanik** [comment]
Sorry, I'm not sure what the input format for that particular model is. I think you'll have to find someone who knows how to feed the inputs, or look at how the python is transforming the input and match that. What IREE accepts as a valid input buffer should match exactly what any other runtime invoking the model expects.

@phoenix-meadowlark may know, but it may be best to ask whoever made the original model.

**Comment by phoenix-meadowlark** [comment]
The image shape and dtype are right (the model expects `1x224x224x3xf32`), so I'm not sure what the issue is. I'm not very familiar with C++ vectors / indexing, but the model expects `NHWC` formatting. I would have guessed that the channels should be contiguous, but it looks like they're `height*width` apart?

In any case, you can validate that the compiled model behaves as expected using the python bindings:

```python
from typing import *

import iree.runtime
import numpy as np


class Module(object):
  """Loads a compiled VmModule into a callable TF/PyTorch-like module.

  Example usage:
    vm_flatbuffer = iree.compiler.tf.compile_module(...)
    model = iree.runtime.Module.from_flatbuffer(vm_flatbuffer, driver="...")
    model.forward(np.zeros(input_shape, np.float32))
  """

  def __init__(self, vm_module: iree.runtime.VmModule,
               config: iree.runtime.Config,
               context: iree.runtime.SystemContext):
    self._vm_module = vm_module
    self._config = config
    self._context = context

  @classmethod
  def load_file(cls, path: str, driver: str):
    with open(path, "rb") as f:
      vm_flatbuffer = f.read()
    return cls.load_flatbuffer(vm_flatbuffer, driver)

  @classmethod
  def load_flatbuffer(cls, vm_flatbuffer: bytes, driver: str):
    vm_module = iree.runtime.VmModule.from_flatbuffer(vm_flatbuffer)
    config = iree.runtime.Config(driver)
    context = iree.runtime.SystemContext(vm_modules=[vm_module], config=config)
    return cls(vm_module, config, context)

  def __getattr__(self, attr: str) -> Callable:
    # Try to resolve it as a function.
    return self._context.vm_modules[self._vm_module.name][attr]


your_data = np.random.normal(0, 1, (1, 224, 224, 3)).astype(np.float32)
module = Module.load_file("/tmp/iree/modules/MobileNetV3Small/imagenet/iree_llvmaot/compiled.vmfb", driver="dylib")
print(module.call(your_data))
```

**Comment by nick-furry** [comment]
Thank you both for your inputs. Here's my latest observation: as suggested above I changed the input image such that all channels are contagious and the buffer size shouldn't be set to vector size rather vector size * no of elements. 

`iree_hal_buffer_write_data(arg_buffer, 0, flattenedImgData.data(), sizeof(float) * kElementCount);`

I get the following classification scores from C++ that seems "correct":
Labrador_retriever: 0.65755, Saluki: 0.127343, Weimaraner: 0.054688 
compared to python scores:
Labrador_retriever: 0.5759909, Weimaraner: 0.12080416, Saluki: 0.096903406

Although the classification is correct, I'm not sure if this variance is expected since essentially the same weights are loaded in C++.

**Comment by benvanik** [comment]
it's possible the data is still wrong but in a deterministic way, like flipped vertically, color channels flipped, etc - I've seen some pretty crazy things pass comparison tests like that :)

**Comment by nick-furry** [comment]
I think I may have found the reason. I had to preprocess the image in Python and save it as int file and load it in C++ but the python input has floating point values. I pray that's the source of this variance :)

**Comment by benvanik** [comment]
@ScottTodd and I were chatting about adding some specific examples for things like image/audio/etc - should make it easier for at least a few of these example models to get started!

**Comment by nick-furry** [comment]
Here's my updated file, hope you find it useful. 
[mobilenet_test.zip](https://github.com/google/iree/files/6201327/mobilenet_test.zip)

**Comment by phoenix-meadowlark** [comment]
Validated that the model has absolute error <= 1e-6 on this image:
![woof](https://static.wikia.nocookie.net/dogs/images/2/20/Lab.jpg/revision/latest/scale-to-width-down/224?cb=20121222015226)

**Comment by nick-furry** [comment]
Oh I validated the model with real data. You could find the image in the first link that I posted here.
