### ISSUE TITLE
Cannot generate IREE benchmarking module for Vulkan backend

### ISSUE THREAD

**Issue by nick-furry** [google/iree#5244]
I'm following this documentation (https://google.github.io/iree/developing-iree/profiling-vulkan-gpu) to benchmark an IREE module for vulkan backend.  I'm not able to generate the `iree-run-module-vulkan-gui` through bazel (no BUILD in /iree/testing/vulkan) as well as using cmake command. I have vulkan sdk installed. Here's my cmake command to build IREE:
```
cmake -G Ninja -DIREE_BUILD_COMPILER=ON -DIREE_BUILD_TESTS=ON -DIREE_ENABLE_MLIR=ON -DIREE_ENABLE_TENSORFLOW=ON -DIREE_BUILD_PYTHON_BINDINGS=ON -DCMAKE_INSTALL_PREFIX=/iree/install -DIREE_BUILD_SAMPLES=ON -DIREE_HAL_DRIVER_VULKAN=ON .. && ninja install
```
I inspected the CMakeLists.txt and I suspect that I maybe missing `imgui`. Any information on how to integrate `imgui` with IREE would also be helpful. 

Just follow the steps in the above link and you can see there's no executable generated after build. 

I'm trying to bechmark IREE's performance on GPU (vulkan) and tensorflow.

**Comment by benvanik** [comment]
Will let scott talk about the specific gui issue, but if you just want to run something then you don't need any of the gui stuff - it's all just demos - iree-run-module should work for executing things and doesn't have dependencies on imgui/SDL/etc.

**Comment by nick-furry** [comment]
`iree-run-module` works but it only provided total time of run and CPU time. I'm trying to benchmark inference performance on GPU (vulkan) and I thought `iree-run-module-vulkan-gui` would probably give that information. After building IREE with the above cmake command, `iree-run-module-vulkan-gui` binary was not generated. Inspecting the CMakeLists in `iree/testing/vulkan` seemed like the executable wouldn't build if the two dependencies aren't presend (imgui and SDL).

**Comment by ScottTodd** [comment]
First, regarding building `iree-run-module-vulkan-gui`: https://github.com/google/iree/pull/4130 has some info that can help with the build configuration, but the documentation at https://google.github.io/iree/developing-iree/profiling-vulkan-gpu is out of date. Specifically, you'll need CMake's `find_package` to locate imgui and SDL2: https://github.com/google/iree/blob/84b0c2cadd165f3dd88fc6eb79e82b66af330512/iree/testing/vulkan/CMakeLists.txt#L29-L41

The most robust way I've found for getting C++ dependencies like those is using [vcpkg](https://github.com/microsoft/vcpkg) with the install commands mentioned in that CMake file and on that PR. If you'd rather not install _yet another_ package manager, you can 'install' those dependencies on their own (e.g. https://wiki.libsdl.org/Installation, not sure about imgui...).

---

Second, regarding GPU benchmarking in general: `iree-run-module-vulkan-gui` won't give you more detailed information on its own. That program is just a GUI wrapper around `iree-run-module` in the hopes of getting external developer tools (like [NVIDIA Nsight Graphics](https://developer.nvidia.com/nsight-graphics)) to recognize that the program is actually submitting commands worth instrumenting. Lots of the GPU tools were built with a graphics focus, where there is a render loop (100 API calls used to generate frame 1, 250 API calls to generate frame 2, etc.)... but we just use compute, so there isn't as clear a place to start/stop measuring. That being said, Nsight has new support for compute applications ([source](https://developer.nvidia.com/nsight-graphics-2021_1)):

> * GPU Trace supports graphics compute applications with no frame boundaries (Beta)
>   * It is now possible for you to profile graphics applications which use D3D Compute, DirectML and Vulkan Compute but do not have a traditional frame begin/end/present.
>    * To use this feature, set the ‘Capture Type’ to ‘One-shot [Beta]’

Broadly speaking, an apples to apples comparison between IREE's GPU execution and another framework like TensorFlow's would either need to operate at a very coarse granularity (entire model dispatch including overheads) _or_ would require both a vendor tool like Nsight and a trained eye to understand which parts of program execution to compare.

As Ben mentions, `iree-run-module` does "work" with GPU execution, with the usual caveats about measuring anything involving a GPU/accelerator/remote system:
  * the reported CPU time includes overheads from building command buffers, submitting those to the GPU, uploading data, synchronizing when complete, reading data back, etc.
  * depending on the computation (e.g. batch size, image dimensions, computational complexity) those overheads could totally eclipse what's actually happening in the kernels
  * reported measurements may be difficult to interpret, particularly if conditions are not controlled (e.g. other programs are running, network has variable latency, thermal throttling on mobile systems)

---

That all being said, we are very interested in benchmarking, profiling, comparing with similar libraries, etc. and would be happy to help figure out ways to make these sorts of investigations easier.

cc @antiagainst (did I miss anything? xD)

**Comment by ScottTodd** [comment]
Oh, I can also give a bit more context on why we'd like to be specific about what is measured and compared, particularly for GPU execution.

As ML models get increasingly complex (by supporting things like dynamic flow control, dynamic shapes, and variables), the overheads from building command buffers, scheduling, and moving data grow. Additionally, for inference on mobile/edge devices, small batch sizes and varying workloads can make it difficult to fully saturate the compute resources on a device. Together, this means that we're expecting to run in scenarios where the overheads _are already_ fairly high compared to actual kernel execution costs. IREE is designed (though not exclusively) for those cases where model complexity is high and resources are limited. For example, we'd expect to see pretty different results analyzing the performance on an arithmetic heavy convolutional model compared to on a model including tree-based search algorithms.

We're also designing for streaming cases, where applications would do something like asynchronously push data into a model (e.g. frames of audio) then periodically poll for outputs (e.g. text transcriptions). The performance metrics such applications care about aren't as easily captured by a benchmark that could introduce artificial synchronization points.

See https://www.usenix.org/conference/osdi20/presentation/ma for similar ideas in a different project.

(Sorry if this feels like excess/unrelated detail, I may have got nerd sniped here...)

**Comment by antiagainst** [comment]
Thanks @ScottTodd  for the fantastic and detailed explanations. Yup as Scott said, the GUI tool is just for integrating with existing developer tools so you can invoke them to understand more what's happening on the GPU for performance tuning, etc.

> `iree-run-module` works but it only provided total time of run and CPU time. I'm trying to benchmark inference performance on GPU (vulkan) 

Actually the time reported there is meant to measure the inference performance. It has overhead right now as explained by @ScottTodd. So if you are trying to measure the inference time for models that run fast, like MobileNet, the overhead can dominate the reported time. We are trying to introduce modes to better reflect just the GPU kernel time, right now with https://github.com/google/iree/pull/5012. But it has problems as tracked by https://github.com/google/iree/issues/5248. Right now if you just want to know _exactly_ the GPU kernel time, the reliable way is to [enable Tracy profiling](https://google.github.io/iree/developing-iree/profiling-with-tracy) and then look the time for `iree_hal_semaphore_wait_with_deadline`. This will improve after #5248 is addressed.

**Comment by nick-furry** [comment]
Thank you @ScottTodd for the very detailed explanation, this is super useful. As @antiagainst  suggested, I'll use `iree_hal_semaphore_wait_with_deadline` duration that I got from Tracy to compare against Tensorflow execution and keep an eye out for upcoming patches. Thank you

**Comment by benvanik** [comment]
@nick-furry something else you'll want to make sure of is that you set the `--vulkan_validation_layers=false` flag - it's probably time we flipped it off by default and enabled it on the CI's/tests explicitly.
