### ISSUE TITLE
[bazel-to-cmake] MLIR SPIR-V mappings

### ISSUE THREAD

**Issue by marbre** [google/iree#529]
MLIR's CMake configuration only provides the targets

- MLIRSPIRVTestPasses
- MLIRSPIRVTransforms
- MLIRSPIRV
- MLIRSPIRVSerialization

whereas the Bazel cc_library are more fine grained:

- SPIRVLowering [inlcuded in MLIRSPIRV]
- SPIRVSerialization
- SPIRVTranslateRegistration [included in MLIRSPIRVSerialization]
- SPIRVDialectRegistration [included in MLIRSPIRV]
- SPIRVDialect [inlcuded in MLIRSPIRV]

This need to be handled in `bazel_to_cmake`.

**Comment by marbre** [comment]
@GMNGeoffrey I noticed your comment `# TODO(gcmn): Update SPIRV dependencies so that they map better to cmake files.` in`third_party/tensorflow/third_party/mlir/BUILD` . Will this reduce the granularity or does this only apply to the tablegen targets?

**Comment by marbre** [comment]
@ScottTodd I hopefully find some time for this tomorrow, but If you're working on the script today, you can of cause take over. Just wanted to write it down somewhere.

**Comment by GMNGeoffrey** [comment]
Hmmm I didn't actually write that TODO, but I guess someone thought I should look into that...

**Comment by ScottTodd** [comment]
Resolved in #537 

Manually closing since "If the commit is in a non-default branch, the issue will remain open and the issue will be referenced with a tooltip." [source](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords)
