### ISSUE TITLE
Add support for lowering mhlo.rng_normal in codegen

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5298]
See definition in https://www.tensorflow.org/xla/operation_semantics#rngnormal

Example IR:

```
%0 = "mhlo.rng_normal"(%arg0, %arg1, %arg2) : (tensor<f32>, tensor<f32>, tensor<2xi64>) -> tensor<1x512xf32>
```

**Comment by asaadaldien** [comment]
We need to dig a little to see if the rng is const initialized with rng_normal that get leaked in inference which means we don't have to implement this mhlo lowering or its actually part of the inference of the model. rng is a stateful and will require maintaining  states between invocations and in general tricky to implement.

**Comment by benvanik** [comment]
Agreed. We can lower this to flow.variable load/store of the prng state, but if it can all be folded away in mhlo/earlier that's the best :)

**Comment by hanhanW** [comment]
I see. I didn't think it deeply. Let me poke around it next week and circle back with you.

**Comment by hanhanW** [comment]
From @ScottTodd : on the topic of RNG: https://llvm.discourse.group/t/random-number-generation-in-mlir/2381

**Comment by hanhanW** [comment]
Just found that they are folded away. We no longer see them in the MLIR file. (I guess this is like what Ahmed said)

**Comment by stellaraccident** [comment]
This is rather surprising: the model is private but definitely applies random noise to the input signal.

**Comment by hanhanW** [comment]
I studied it and found that tensorflow has an internal global state. See the last section of https://www.tensorflow.org/api_docs/python/tf/random/set_seed

> The second call of foo returns '(A2, A2)' instead of '(A1, A1)' because tf.random.uniform maintains an internal counter.


In TF -> mhlo lowering, we ignore the seed: https://github.com/tensorflow/tensorflow/blob/98106e0e17cfbc6f9cc360e15f8636b509ccbfe4/tensorflow/compiler/mlir/xla/transforms/legalize_tf_patterns.td#L695-L710

```
foreach srcDstOpPair = [[TF_RandomUniformOp, HLO_RngUniformOp],
                        [TF_RandomStandardNormalOp, HLO_RngNormalOp]] in {
// TODO(b/148269299): handle random number generator seeds/states correctly.
def : Pat<(srcDstOpPair[0]:$old $shape, $seed, $seed2),
          (srcDstOpPair[1]
            (HLO_ConstOp
              (NativeCodeCall<"$_builder.getFloatAttr(old.dtype(), 0.0)">)),
            (HLO_ConstOp
              (NativeCodeCall<"$_builder.getFloatAttr(old.dtype(), 1.0)">)),
            (CastValueToI64 $old, $shape)),
          [(IsShapedTensor $shape)]>;
}
```

For now, we can hardcode the seed like https://github.com/google/iree/pull/6676

Ideally we should create the flow.variable global seed at some point, and load/store for the state.
