### ISSUE TITLE
Add support for lowering mhlo.einsum in codegen

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5376]
There is no definition in https://www.tensorflow.org/xla/operation_semantics

See definition in https://www.tensorflow.org/api_docs/python/tf/einsum

The `equation` is just like affine_map. I think we can use a generic op + some reduction loops to handle it.

**Comment by hanhanW** [comment]
From @phoenix-meadowlark , these tests/the mlir the generate cover a fair amount of einsum's behavior:

https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/einsum_vector_test.py
https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/einsum_static_test.py
https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/einsum_dynamic_test.py

**Comment by hanhanW** [comment]
I think it can be legalized to `mhlo.dot_general`. We have patterns to tweak `mhlo.dot_general` to `linalg.batch_matmul` and `linalg.matmul` forms. Then we can focus optimization on gemm more.

**Comment by MaheshRavishankar** [comment]
This is done now. Closing

**Comment by phoenix-meadowlark** [comment]
Does this mean there is support for lowering `tf.einsum` now? If so, could we enable these tests for the relevant backends?
https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/BUILD#L102-L104

**Comment by raikonenfnu** [comment]
> Does this mean there is support for lowering `tf.einsum` now? If so, could we enable these tests for the relevant backends?
> https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/BUILD#L102-L104

I think we should be able to lower tf.einsum now, since iirc tf.enisum lowers to mhlo.einsum anyways. But @hanhanW will know for sure :)

**Comment by hanhanW** [comment]
We can give it a shot. IIRC there are missing cases.

IIRC, the op is rewritten to dot_general. We assumed that there are at least one contracting dim and one parallel dim in dot_general. and it will cause errors in HLOToHLOPreprocessing pass. I'll take a look. Will file an issue to track it if it is the case.

**Comment by hanhanW** [comment]
note: IIRC, lowering the op to generic op (@raikonenfnu 's pattern) handles the case. I have to verify it.
