### ISSUE TITLE
Add support for mhlo.dynamic-slice

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5377]
They can be lowered to subtensor or subtensor_insert, and be `flow.tensor.update`

**Comment by GMNGeoffrey** [comment]
I just encountered this in a real model I'm trying to get working. Should I assume you're looking at it?

**Comment by hanhanW** [comment]
Yes, please. I already have a ongoing patch. (still have few comments to address)

**Comment by hanhanW** [comment]
mhlo.dynamic-slice is added in https://github.com/tensorflow/mlir-hlo/commit/a3fc99efe0af66da3eae469e30685ed32b3b6877

Do you want me to prioritize the support of dynamic-update-slice? It should be simple; it is not a blocker to me. So I plan to hold it off a bit.

**Comment by GMNGeoffrey** [comment]
Not currently blocking me, so proceed at the pace that makes sense. Thanks for taking care of dynamic-slice :-)

**Comment by MaheshRavishankar** [comment]
This should work now right? If so please close it?

**Comment by hanhanW** [comment]
dynamic-update-slice is not supported, I should file another issue for it.
