### ISSUE TITLE
[bazel-to-cmake] Preserve order of dependencies

### ISSUE THREAD

**Issue by marbre** [google/iree#538]
To compare the generated CMakeLists.txt with Bazel's BUILD files, it would be awesome if the order of the dependencies is preserved. Maybe as additional option, but actually I see no need for a sorted dep list.

Only removing `sorted` in the line below
https://github.com/google/iree/blob/c8ded4a56998f646b8114e80b11f748eef481adb/build_tools/scripts/bazel_to_cmake.py#L170
is not sufficient.

**Comment by ScottTodd** [comment]
We typically sort Bazel dependencies lexicographically using [Buildifier](https://github.com/bazelbuild/buildtools/tree/master/buildifier) and related tools. One advantage of having consistent formatting (spacing, ordering, etc.) is that we can run additional automated tools (like [Buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer)) across the dependencies and they can make local changes easily without needing to adapt to formatting differences.

However, a few dependency names are different between Google's upstream repository and the repository here on GitHub, so the dependency order when sorted can (infrequently) be different.
For example, `//third_party/flatbuffers` -> `@com_github_google_flatbuffers//:flatbuffers`.

To avoid similar differences in the CMake build, I was thinking we could sort the dependencies there as well.

**Comment by marbre** [comment]
Got you're point. Nevertheless, I think that a 1:1 translation, preserving the order, might be helpful as long as the conversion is not applied fully automatic(?).

**Comment by ScottTodd** [comment]
Sure, I think we could go either way here - matching the ordering or sorting. If Google's upstream and GitHub diverge, we could find a way to solve / work around that on our end.

If we get to the point where the script is run on our automation and warns/errors if any diff is found between the code in a commit and what the script would generate, then standard formatting like sorting would become more necessary.

If the blocking issue for preserving the order is in that duplicate pruning step, we could use an approach like this: https://stackoverflow.com/a/37134890 instead of `list(set(deps_list))`

**Comment by benvanik** [comment]
I'm not a fan of this logic -- the hard rule in bazel land is to sort alphabetically. It just happens that package paths prefixed with ':' are lexicographically first. I'd much rather us support relative package paths in cmake if we wanted 1:1 alignment than try to emulate the ordering of relative vs. absolute packages in bazel. Rule of least surprise, and all. Right now, it looks unsorted if I'm looking at the cmake files and does not match what buildifier would do if you were to run it on a bazel file containing absolute package paths like our cmake files have.

**Comment by ScottTodd** [comment]
I like the idea of supporting relative package paths in CMake. We could update `iree_cc_library` and related functions to expand a leading `::` to the current package. For example, 
in `iree/hal/CMakeLists.txt`, `iree::hal::buffer` could change to `::buffer`, which would get expanded back to `iree::hal::buffer` for `target_link_libraries()`.

**Comment by marbre** [comment]
My motivation for preserving the order was motivated by using `bazel_to_cmake.py` in this early stage, with not all mappings yet supported. If the deps are sorted, it rises the effort to manually compare the Bazel and the CMake files. With the order preserved it's straightforward to use `git add -p` **and** to identify which mappings need further attention. So please consider the changes applied with my PR more as an intermediate step and not as the final solution.

Thus I agree with both of you. Sorting alphabetically + supporting relative packages would be the nicest

**Comment by GMNGeoffrey** [comment]
I think that logic makes sense. Let's preserve ordering for now, while we're trying to tweak bazel_to_cmake, but not run bazel_to_cmake on existing files just to update the orderings (I've got a PR where I do it, but I really only did it to prove that my changes didn't screw anything up across a wide section of the files). Then
1. Add support for relative paths
2. Switch to strict alphabetical sorting
3. Run the converter across everything (or some big chunk like the iree directory)
4. Add automation to enforce that CMakeLists match the output of the converter

**Comment by GMNGeoffrey** [comment]
We've come to a point where I think we're going to have to switch to alphabetical order for cmake targets. I've just about got bazel_to_cmake working upstream, where the order of dependencies is different, so there's no way we can have it preserve order and have that. Now that we've got relative deps that should make less of a difference though, I think. I'm preparing https://github.com/google/iree/pull/777 to sort the dependencies.

The good news is that this means it should be possible to enforce that people run the tool as a presubmit, which should keep those files up to date much better.

**Comment by marbre** [comment]
Yeah, I fully agree. With support for relative packages we're definitely at a point where we can switch to alphabetical order :)

**Comment by marbre** [comment]
Closing as we sort deps alphabetically now with ff6c6d6.
