### ISSUE TITLE
Revisit signed/unsigned integer in IREE

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5383]
MLIR introduced signedness for integer types in the past year. Some passes and checks were added before it, so we actually did not handle it correctly.

E.g.,

In flow type converter, it does not handle `ui64` types.

https://github.com/google/iree/blob/5b952e42adcd2c7c076d4ce1814225d1590aaf60/iree/compiler/Dialect/Flow/Conversion/TypeConverter.cpp#L41-L51

In MHLO -> Linalg patterns, it does not handle unsigned types.

https://github.com/tensorflow/mlir-hlo/blob/6d2209e30192f71d8164cd0fc9dbbe1f8f60680f/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc#L239-L243

IIRC, the `isSignlessIntOrFloat` stuff were added by integration fixes. Now it causes issues to compile ASR models, and it's a good time to clean these up.

**Comment by GMNGeoffrey** [comment]
I think we're trying to lower some very similar models here :-P I just hit the same issue of unhandled unsigned types in linalg. See some discussion in https://discord.com/channels/689900678990135345/689932666505920596/830177574096207892

**Comment by hanhanW** [comment]
After talking to @antiagainst , we found that there are unsigned integers and signless integers in the model. I don't see `si[0-9]` in the MLIR files.

**Comment by GMNGeoffrey** [comment]
Yes that's because MHLO incorrectly uses signless to mean signed because integer signedness was not originally present in MLIR. So for legacy reasons signless integers in MHLO should be interpreted as signed, but that's something that really needs to be fixed.

**Comment by GMNGeoffrey** [comment]
MHLO -> linalg now handles unsigned types at a basic level. IREE itself uses signless ints, but this new conversion of ui64->i32 is happening before dispatch region formation (which is why we're still seeing unsigned). Once we switch entirely to linalg-on-tensors this should be easier to cleanup. For now though, this is doing more than just silently truncating (which is already not great). It's also silently converting unsigned to signed, effectively, because this is still happening on MHLO where signless means signed. This means that the op created would be an signed instead of an unsigned variant. Stuff gets weird and this is likely going to result in some confusing bug.

**Comment by GMNGeoffrey** [comment]
The rationale for converting unsigned to signless is that std.constant doesn't support unsigned.

https://github.com/google/iree/blob/0b3289aea9fcea8d0e00117045a1256fdddb93f7/iree/compiler/Dialect/Flow/Conversion/TypeConverter.cpp#L41-L51

I don't think that's right though. At least, it's not enforced by the verifier. My understanding is that std.constant is supposed to support *any* type, which I assume would include [un]signed integers. You hit an assert printing such a constant though.

Sent https://reviews.llvm.org/D101810 to clean that up

**Comment by GMNGeoffrey** [comment]
Ok my take on std.constant was wrong. It does indeed require signless integers. This is just a bug in the lowering of mhlo.dynamic-slice to std.subtensor though, I think. It's assuming signed (aka signless)

> /tmp/repro.mlir:428:12: error: expected result element type to be 'i64'
    %388 = "mhlo.dynamic-slice"(%364, %387) {slice_sizes = dense<1> : tensor<1xi64>} : (tensor<3xui64>, tensor<i32>) -> tensor<ui64>
           ^
/tmp/repro.mlir:428:12: note: see current operation: %639 = "std.subtensor"(%632, %638) {operand_segment_sizes = dense<[1, 1, 0, 0]> : vector<4xi32>, static_offsets = [-9223372036854775808], static_sizes = [1], static_strides = [1]} : (tensor<3xi64>, index) -> tensor<ui64>

**Comment by GMNGeoffrey** [comment]
Sent a patch to fix the lowering. Now hitting the same issue with mhlo.concatenate. I'm just going to fix these and we can hopefully remove this hack

**Comment by GMNGeoffrey** [comment]
Fixing in upstream MHLO is not hard. For some reason IREE has its own pattern for concat as well though

**Comment by GMNGeoffrey** [comment]
https://github.com/tensorflow/tensorflow/commit/55338bb43c76edad2557be1cd62dc315c4106314 for dynamic-slice

**Comment by GMNGeoffrey** [comment]
https://github.com/tensorflow/tensorflow/commit/6adc0d0d9f7d2db7649f70ad5cdd231e365cd745 for concatenate

**Comment by hanhanW** [comment]
Thanks for working on this!

I think we still use our own lowering for concatenate op. I did not know that there is a version in MHLO repo. I suspect that MHLO's one has some issues that I hit before. I will take a look and raise the issue to MHLO folks if that is the case. Everything looks good in IREE now. :)

**Comment by GMNGeoffrey** [comment]
> I think we still use our own lowering for concatenate op. I did not know that there is a version in MHLO repo. I suspect that MHLO's one has some issues that I hit before. I will take a look and raise the issue to MHLO folks if that is the case. Everything looks good in IREE now. :)

Yeah I think I looked at using it briefly and there was some issue I hit (should've written it down). Should be easy to repro though by just removing our pattern
