### ISSUE TITLE
Drop some HLO To HLO patterns in IREE

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5398]
Some patterns are not needed, at least not in CPU and GPU backend. They are implemented in HHLO repro.

E.g.,

DecomposeClampOp -- The difference between this pattern and [MHLO upstream pattern](https://github.com/tensorflow/mlir-hlo/blob/0ec0a23e61ffada96ada5258d82178b043fd5d18/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc#L2055) is that MHLO pattern does not reject implicitly broadcasted cases.

https://github.com/google/iree/blob/29610cebc4174225b5d6785703c63e6053409b68/iree/compiler/Conversion/HLOToHLO/DecomposeHLOClamp.cpp#L26-L53

Some operations in HLOToHLOPreprocessing should be removed, like DecomposeLog1PPattern and DecomposeExpM1Pattern. They are also implemented in legalize_to_linalg.cc (and they are doing the same thing!). I guess it currently only benefit VMLA?
We really should remove them after deprecating VMLA (if this is the reason).

**Comment by hanhanW** [comment]
note: I found these when I'm implementing DynamicSlice lowering support. This is not a blocker for anything.

**Comment by MaheshRavishankar** [comment]
@stellaraccident maybe this is not needed any more after PR #6030. If you already took care of this please close this issue

**Comment by stellaraccident** [comment]
I had my eye on these but just moved them to a new home in the interests of not making the first step of my task harder. Unless if I messed up my intention, they are still there.

**Comment by MaheshRavishankar** [comment]
Looked at the PR above once again. They are moved to the right place. This might also explain the atanh failure. Essentially it ended up with a `log(1+x)` operation which SPIR-V backend didnt handle. That is fixed now. So some of these were probably doing a canonicalization to get around some missing conversions in the backends. In any case, I think this isnt relevant anymore. Closing the issue
