### ISSUE TITLE
Unsupported linalg.vecmat lowering in vulkan backend

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5444]
There are some gemm can be legalized to vec x mat. E.g.,

```mlir
"mhlo.dot"() : (tensor<1x1024xf32>, tensor<1024x1024xf32>) -> tensor<1x1024xf32>
```

We probably want to legalize them to `reshape + vecmat + reshape`.

I hit the lowering issue when working on dft. CPU supports it, but GPU not.

**Comment by antiagainst** [comment]
We could at least turn it into `linalg.generic` and lower to loops to get unblocked? Certainly need an accelerated version though.

**Comment by MaheshRavishankar** [comment]
I think this is fixed now. It should get a general configuration if it is not explicitly set.
