### ISSUE TITLE
warning: no target backends  provided buffer constraints; falling back to host default

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5449]
Seeing many warnings in `iree/samples/*` when building IREE.

E.g.,

```
iree/modules/tensorlist/tensorlist_test.mlir:1:1: warning: no target backends provided
 buffer constraints; falling back to host default
func @identity_through_set_item_get_item(%arg0: !hal.buffer_view) -> !hal.buffer_view attributes {iree.module.export, iree.abi.none} {
^
...
iree/modules/strings/strings_module_test.mlir:15:1: warning: no target backends provid
ed buffer constraints; falling back to host default
func @print_example_func(%arg0 : i32) attributes { iree.module.export } {
```

Looks like we forgot to pass target backends in

https://github.com/google/iree/blob/1a941fc4fd4398c83e168281e5cf657c663e8e40/iree/modules/tensorlist/BUILD#L48-L54

I don't remember I saw it before... not sure what happened.

**Comment by hanhanW** [comment]
It's either from `IdentifyConstantPools.cpp` or `PackAllocations.cpp`.

**Comment by benvanik** [comment]
yep - both will do it depending on usage - we should be passing a target backend there

**Comment by hanhanW** [comment]
cool, let me send a quick fix later.
