### ISSUE TITLE
[New documentation] Write docs for "Python bindings"

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#5456]
* Live preview of this page: https://scotttodd.github.io/iree/bindings/python/, which will eventually live on https://google.github.io/iree/ after we switch over the docs.
* Source currently lives on the `staging-docs-rework` branch here: https://github.com/google/iree/blob/staging-docs-rework/mkdocs/docs/bindings/python.md . PRs or direct commits to the branch are okay. We'll want to be careful about force pushes / rebases though.
* See the README here for instructions on previewing changes locally: https://github.com/google/iree/tree/staging-docs-rework/mkdocs
* mkdocs + mkdocs material offer a bunch of nice features, like https://squidfunk.github.io/mkdocs-material/reference/code-blocks/ (line numbers, highlighting specific lines, etc.)

Site and doc layout can be changed, but I've sketched out a rough draft already. These areas in particular are TODO:

https://github.com/google/iree/blob/b6a38b389be8a66d984a5bfaf7aabe98474fa332/mkdocs/docs/bindings/python.md#L14-L22

https://github.com/google/iree/blob/b6a38b389be8a66d984a5bfaf7aabe98474fa332/mkdocs/docs/bindings/python.md#L99-L108

I was thinking we could have each "frontend" page discuss the formats used, features supported, and APIs available, while covering general Python binding details here. We could use content tabs ([see these docs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/)) to let people switch between frontends in some code samples, or just pick a single example and link to the different frontend docs for other specifics.

**Comment by stellaraccident** [comment]
This seems to not regress our current docs. Could use more but we can do that as we go.

**Comment by ScottTodd** [comment]
> This seems to not regress our current docs. Could use more but we can do that as we go.

Yep. I won't block switching to the new site on fully writing this page (or most others).

**Comment by ScottTodd** [comment]
I think the main thing missing for the Python bindings docs is published API reference material (https://github.com/google/iree/issues/5477), so we could call this issue fixed.
