### ISSUE TITLE
[New documentation] Write docs for "Building Python bindings"

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#5457]
* Live preview of this page: https://scotttodd.github.io/iree/building-from-source/python/, which will eventually live on https://google.github.io/iree/ after we switch over the docs.
* Source currently lives on the `staging-docs-rework` branch here: https://github.com/google/iree/blob/staging-docs-rework/mkdocs/docs/building-from-source/python.md . PRs or direct commits to the branch are okay. We'll want to be careful about force pushes / rebases though.
* See the README here for instructions on previewing changes locally: https://github.com/google/iree/tree/staging-docs-rework/mkdocs
* mkdocs + mkdocs material offer a bunch of nice features, like https://squidfunk.github.io/mkdocs-material/reference/code-blocks/ (line numbers, highlighting specific lines, etc.)

I'd like for this page to aggregate the "building from source" aspects of our current Python pages:
* https://google.github.io/iree/get-started/getting-started-python
* https://google.github.io/iree/get-started/getting-started-tensorflow
* https://google.github.io/iree/developing-iree/tensorflow-integrations (maybe)

This will be linked from the "Python bindings" page (preview: https://scotttodd.github.io/iree/bindings/python/) and possibly from the Python frontend pages, in cases where users will benefit from building from source instead of installing from our published packages.

**Comment by ScottTodd** [comment]
Also worth noting that I only set up a single "building from source" page for C++ (preview: https://scotttodd.github.io/iree/building-from-source/getting-started/), which exclusively uses CMake. If we put details on building TensorFlow in here, they may also need to cover setting up Bazel.

(I'm open to the idea of putting a "Getting started - Bazel" alongside "Getting started - CMake", like we have today, but I'd really prefer to steer users towards CMake)

**Comment by stellaraccident** [comment]
Let me take a stab at this today. It's going to be a bit gross - but that reflects the state of the system.

**Comment by ScottTodd** [comment]
Started in https://github.com/google/iree/commit/04818be2306764412bcedbbe1e743b3570aca268. Thanks!

**Comment by ScottTodd** [comment]
Actually, let's call this fixed for now? We can refine over time.

**Comment by stellaraccident** [comment]
Let me re-open for a bit: I want to add a section at least with a path through for TensorFlow packages.

**Comment by ScottTodd** [comment]
https://google.github.io/iree/building-from-source/python-bindings-and-importers/ looks like it covers what this issue was asking for
