### ISSUE TITLE
[New documentation] Write docs for "CPU LLVM backend"

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#5458]
* Live preview of this page: https://scotttodd.github.io/iree/backends/cpu-llvm/, which will eventually live on https://google.github.io/iree/ after we switch over the docs.
* Source currently lives on the `staging-docs-rework` branch here: https://github.com/google/iree/blob/staging-docs-rework/mkdocs/docs/backends/cpu-llvm.md . PRs or direct commits to the branch are okay. We'll want to be careful about force pushes / rebases though.
* See the README here for instructions on previewing changes locally: https://github.com/google/iree/tree/staging-docs-rework/mkdocs

I'd like for this page to explain what commands like
```
iree-translate \
  -iree-hal-target-backends=dylib-llvm-aot \
  -iree-llvm-target-triple=x86_64-linux-gnu \
  ...
```
and
```
iree-run-module \
  -driver=dylib
  ...
```
(or equivalent, via bindings) mean, with some basic description of CPU [multithreaded/singlethreaded] compilation and execution.

I sketched some ideas in the doc already:

https://github.com/google/iree/blob/97d4eeac924177a094110984a825d8cce6604fa8/mkdocs/docs/backends/cpu-llvm.md#L12-L27

**Comment by antiagainst** [comment]
Done with #5572.
