### ISSUE TITLE
[New documentation] Write docs for "GPU Vulkan backend"

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#5459]
* Live preview of this page: https://scotttodd.github.io/iree/backends/gpu-vulkan/, which will eventually live on https://google.github.io/iree/ after we switch over the docs.
* Source currently lives on the `staging-docs-rework` branch here: https://github.com/google/iree/blob/staging-docs-rework/mkdocs/docs/backends/gpu-vulkan.md . PRs or direct commits to the branch are okay. We'll want to be careful about force pushes / rebases though.
* See the README here for instructions on previewing changes locally: https://github.com/google/iree/tree/staging-docs-rework/mkdocs

This doc should look like the "CPU LLVM backend" doc (https://github.com/google/iree/issues/5458). Some things can be pulled from https://google.github.io/iree/get-started/generic-vulkan-env-setup and https://google.github.io/iree/developing-iree/profiling-vulkan-gpu, though we should link to external/official documentation more and include specific troubleshooting/setup details less.

I sketched some ideas in the doc already:

https://github.com/google/iree/blob/97d4eeac924177a094110984a825d8cce6604fa8/mkdocs/docs/backends/gpu-vulkan.md#L1-L15

**Comment by antiagainst** [comment]
This is done via #5519.
