### ISSUE TITLE
Revamp C API samples, including `simple_embedding_test.cc`

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#5481]
We should have actual C API samples that do not use C++. Our samples should also look like application code, not googletest test code.

- [x] Switch from C++ to C
  - [x] Drop test-only macros. Use `IREE_CHECK_OK` instead of `IREE_ASSERT_OK`
  - [x] Use `NULL` (C) instead of `nullptr` (C++)
  - [x] Drop dependencies on `iree/vm/ref_cc.h`
  - [x] Drop dependencies on `absl/*`
  - [x] Drop dependencies on `<vector>`
  - [x] Generate C from https://github.com/google/iree/tree/main/build_tools/embed_data instead of C++?
- [x] Create `cc_binary` targets that can be run outside of the test framework. If tests are still useful, they can be written as `sh_test` (or some other language) scripts that call the binaries and verify they succeeded

**Comment by hcindyl** [comment]
https://github.com/google/iree/pull/5540 should be the base of https://github.com/google/iree/pull/5524 to create the C sample. I will patch https://github.com/google/iree/pull/5524 later with https://github.com/hcindyl/iree/commit/34cca792e3ec0b3de4e2ea896a9a0f81861655e0
