### ISSUE TITLE
Get work distribution working properly for VMVX (and others).

### ISSUE THREAD

**Issue by benvanik** [google/iree#5548]
Currently elementwise ops need the `-iree-flow-tile-and-distribute-elementwise-ops` flag and it does some weird things that seems to thwart vectorization (unshaped stuff, etc). It'd be nice if we can turn this pass on by default and then burn down the issues with it such that we generate reasonable vector-level IR. There's also a `-iree-flow-dispatch-linalg-on-tensors-tile-sizes=` flag and that probably also needs to work somehow. There's currently logic in https://github.com/google/iree/blob/11b3bfe7f40d2691971549aa4a1d3f1af01412d5/iree/compiler/Conversion/LinalgToLLVM/MaterializeCPULaunchConfigurationPass.cpp but it falls over in all the cases I could get to it and may need some more generalization for the above to work.

The goal here is to end up with workgroups that process parts of the total problem and within each workgroup have some level of tiling over a known vector size. If MaterializeCPULaunchConfigurationPass can be made to work correctly for LLVM then it - or a fork of it - could be used for VMVX.

(all of this is required on the CPU path to vectorize and distribute ops - this issue is tracking making sure it's generalized enough to not just be hardcoded into the LLVM pipeline)

Some relatively simple example input IR:
```mlir
func @simple_mul(%arg0: tensor<2x4096xi32>, %arg1: tensor<2x4096xi32>) -> tensor<2x4096xi32> attributes {iree.module.export, iree.reflection = {f = "I27!B10!t6d2d4096B10!t6d2d4096R14!B10!t6d2d4096", fv = "1"}} {
  %0 = linalg.init_tensor [2, 4096] : tensor<2x4096xi32>
  %1 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%arg0, %arg1 : tensor<2x4096xi32>, tensor<2x4096xi32>) outs(%0 : tensor<2x4096xi32>) {
  ^bb0(%arg2: i32, %arg3: i32, %arg4: i32):  // no predecessors
    %2 = muli %arg2, %arg3 : i32
    linalg.yield %2 : i32
  } -> tensor<2x4096xi32>
  return %1 : tensor<2x4096xi32>
}
```

It'd be good to track our progress here based on how close we can get to something that does more than just a `1,1,1` workgroup count and supports scf+vector on the inside (vector transfer read/writes and a vector muli).

**Comment by MaheshRavishankar** [comment]
@benvanik this should be done now with PR #6084. Could you verify and close this?

**Comment by MaheshRavishankar** [comment]
Closing this for now. THere might be individual ops that could be distributed better, but the structure is in place.
