### ISSUE TITLE
[New documentation] Decide on category naming

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#5555]
Forking from https://github.com/google/iree/pull/5519#discussion_r617710585

This is the current structure:

```
IREE
- Home

Frontends
 - TensorFlow
 - TensorFlow Lite
 - JAX

Backends
 - CPU - LLVM
 - GPU - Vulkan

Building from source
 - Getting started
 - Python bindings
 - Android cross-compilation

Bindings
 - Python
 - C API
 - TensorFlow Lite

Community
 - Projects
```

which I think makes sense for new users approaching the project, but could use some refinement on the particular category names.

## "Frontends"

This category covers machine learning frameworks and file formats that users would start with, including IREE-specific tooling for importing, and IREE python packages with compiler/runtime/util APIs.

Here are some alternate names to consider:

* Frontends
* Integrations
* Frameworks
* Framework integrations
* Framework importers

## "Backends"

This category is set up to cover the common [compiler target, runtime HAL driver] configurations that users are expected to use. For example:

* `-iree-hal-target-backends=vulkan-spirv` compilation -> `-driver=vulkan` at runtime on a device that has Vulkan 1.2 support.
* `-iree-hal-target-backends=dylib-llvm-aot -iree-llvm-target-triple=aarch64-linux-android` compilation -> `-driver=dylib` at runtime on Android

_Some_ of this can be considered implementation details that users shouldn't need to care about. Certain types of users will just want a high level "how do I run on CPU" vs "how do I run on GPU" decision point. This section could grow to contain "bare-metal" and other deployment configurations.

Since "backend" already has meaning in a compiler context, here are some other names to consider:

* Execution runtimes
* Executors
* Runtime drivers
* Runtime HAL drivers
* Runtime backends
* Configurations
* Runtime configurations

## Bindings

This category covers the IREE C API and bindings built on top of it (Python, TFLite, Swift, Java, etc.). I could also see calling this "APIs" or it getting folded under a generic "Reference" category which would include generated API documentation.

**Comment by antiagainst** [comment]
I like bikeshedding! :) Rephrasing the comment I've at https://github.com/google/iree/pull/5519#discussion_r617727246:

The main concern I've with the "frontend" and "backend" terms is that they are mainly from the compiler's perspective. So it's entirely fine and proper we use them when in that context, but IMO not so much here given we are mainly providing docs for general users wanting to integrate IREE. So using terminology they are familiar with is preferable. 

For "Frontends", I'd vote for "Framework integrations". Frameworks are what typically people call them. I prefer "integration" over "importer" because "importer" hints it's just one tool to me; we provide more than that with various tools and entry points. So "integration" is better.

For "Backends", I think we likely need to split here because there are compiler target backends and HAL drivers. For application integration, I don't think compiler target backends are of a great concern; it should pretty much be an offline tool to convert the model from format A to format B. (It's more important for system integration for sure. Just different audience.) What's more important is to integrate the HAL runtime into the application. I'd vote for "Runtime drivers" and "Runtime HAL drivers" here.

**Comment by benvanik** [comment]
good points! "ML Frameworks" seems pretty unambiguous as a good replacement for frontends (today - we may have non ML frontends but those could be separate).

On the compiler side "HAL Targets" is the level at which I think of the backends (hence `Dialects/HAL/Targets/`) - just like you think of compiler targets: each HAL target has a triple and defines its execution environment - like Vulkan or local CPU - and its format for its executables - like SPIR-V or ELF. I'm adding this next week to make it more concrete in the IR, but it does match up nicely with LLVM targets like `aarch64-pc-linux-elf` (which encodes the architecture, environment, and format).

On the runtime side we have the "HAL Drivers" which are the things that consume those things - I think it's good to separate them but link them together: the concerns of someone wanting to tweak the compiler for a certain target are mostly separate from wanting to tweak the runtime to consume the outputs of the compiler as they are effectively different codebases.

The target/driver split is intended to be like GPUs: you "target" SPIR-V/Vulkan as an output artifact and you use a "driver" to drive your SPIR-V/Vulkan execution.

**Comment by ScottTodd** [comment]
"Framework integrations" or "ML Frameworks" both sound good to me for the first category. I'm leaning a bit away from "integrations" since I think of IREE as a separate system that you convert through _after_ doing your development in your framework of choice, rather than a sort of mix-in that offers particular benefits during model authoring / training / etc. (though that line is blurry in a few places).

For the second category, "Runtime configurations" or "Deployment configurations" are both growing on me, in the sense that users will roughly

1. pick a model
2. import that model from their ML framework into MLIR/IREE
3. decide how they want to run that model (GPU on Android, multithreaded CPU on desktop, bare metal, wasm + web)
4. compile for that configuration
5. use the applicable API/bindings for their platform and set up a driver matching the compiled module

I'm looking to explain steps 3-5 coherently. One idea I had was to have these sorts of "common recipe" pages that would match the compiler and runtime configurations together. We could certainly split that out to "Compiler HAL targets" and "Runtime HAL drivers" sections.

**Comment by benvanik** [comment]
^ I like

**Comment by ScottTodd** [comment]
"Frontends" / "Backends" / "Bindings" are categories on our Discord server
"integrations/" matches our code and GitHub issue structure 🤔

I'm still leaning towards "ML Frameworks" and "Deployment configurations" for website sections though.

**Comment by antiagainst** [comment]
> "Frontends" / "Backends" / "Bindings" are categories on our Discord server
> "integrations/" matches our code and GitHub issue structure 🤔

I think that is fine given the Discord server / source code is more for folks changing IREE itself. So a different terminology can be used. (And we can also change there to be consistent.)


> 
> I'm still leaning towards "ML Frameworks" and "Deployment configurations" for website sections though.

+1. SGTM!
