### ISSUE TITLE
Reenable cooperative matrix test using workgroup memory

### ISSUE THREAD

**Issue by antiagainst** [google/iree#5608]
LLVM integration https://github.com/google/iree/commit/799dd5410e5fb5ecba73c8429a3c011d93c4fa6f silently disabled cooeprative matrix using workgroup memory. #5607 migrated cooperative matrix to Linalg on tensors path for the normal test but not the workgroup memory version. Tracking the reenabling task with this issue.

**Comment by MaheshRavishankar** [comment]
We have disabled workgroup memory usage in general in SPIR-V backend now since its not profitable. Need to revisit this anyway. This particular test was experimental, and not load-bearing. I dont think we need to re-enable this right now. So closing this bug.
