### ISSUE TITLE
error: unhandled multiple root operations in dispatch region

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5636]
Seeing errors with `--iree-flow-dispatch-formation-enable-operand-fusion` when compiling Mobilbert. This only happens on CPU side. Note: the compilation is still successful. This happens in `MaterializeCPULaunchConfigurationPass`.

Full log of `print-before-all`: https://gist.github.com/hanhanW/c1764e6feb3fea1b5eb931627b997130/raw

To repro: `iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=dylib-llvm-aot iree/test/e2e/models/bert_encoder_unrolled_fake_weights.mlir -iree-flow-dispatch-formation-enable-operand-fusion -o a.vmfb`

**Comment by MaheshRavishankar** [comment]
Superceded by #6973 . Closing this one.
