### ISSUE TITLE
Help including IREE as a thirdparty to target RISCV

### ISSUE THREAD

**Issue by nick-furry** [google/iree#5686]
I'm trying to build a version of `iree-run-module-main.cc` (https://github.com/google/iree/blob/main/iree/tools/iree-run-module-main.cc) and run it on RISCV QEMU (https://google.github.io/iree/get-started/getting-started-riscv-cmake). 

As a first step, I wanted to try and just build `iree-run-module-main-v2.cc` and the supported RISCV IREE tools on x86. I passed the following flags to build IREE as cross-compiling IREE compiler isn't supported: 
```
      -DIREE_BUILD_BINDINGS_TFLITE:BOOL=OFF
      -DIREE_ENABLE_TENSORFLOW:BOOL=OFF
      -DIREE_BUILD_COMPILER:BOOL=OFF
      -DIREE_ENABLE_MLIR:BOOL=OFF
      -DIREE_BUILD_SAMPLES:BOOL=OFF
```

When I try to build the above project with dependency on IREE, I get the following linker error:
```
/usr/bin/ld: iree-run-module-v2/CMakeFiles/iree-run-module-v2.dir/iree-run-module-v2.cc.o: in function `iree::Run()':
nnc-iree-run-module.cc:(.text+0x7c): undefined reference to `iree::CreateDevice(std::basic_string_view<char, std::char_traits<char> >, iree_hal_device_s**)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Observation/things that I've tried:
1. The library `libiree_tools_utils_vm_util.a` that contains `iree::CreateDevice()` signature is generated. I tried explicitly linking the library but with no success. Changing the order of linking didn't help too.
2. Building IREE with `IREE_BUILD_SAMPLES=ON` successfully builds but this flag in turn turns on the compiler that cannot be cross compiled. 
3. In the function call to `iree::CreateDevice()`, I tried using `std::string` as well as `absl::string_view` so I don't think it's a signature matching issue. 

The same error comes when building with RISCV toolchain. The reason for building for x86 arch was just to make debugging easier. 

Please let me know if you need any other information, any help would be much appreciated. Thank you!

**Comment by ScottTodd** [comment]
Just a note: cross compiling the compiler isn't supported, but I did succeed at it recently (through Emscripten) with some effort. See [this gist](https://gist.github.com/ScottTodd/7898981998cefb60902d4fbc8a471ccf) for details.

---

Depending on when you branched from `main`, I think you'll need to incorporate the changes to `iree-run-module.cc` from https://github.com/google/iree/pull/5602 to your `iree-run-module-main-v2.cc`. Specifically, `ABSL_FLAG(std::string,` was replaced with `IREE_FLAG(string,`, along with some other details.

From your linker error, I think there was an implicit cast here that no longer exists:
```
- IREE_RETURN_IF_ERROR(CreateDevice(absl::GetFlag(FLAGS_driver), &device));
+ IREE_RETURN_IF_ERROR(CreateDevice(std::string(FLAG_driver), &device));
```

That `CreateDevice` function accepts `absl::string_view`:

https://github.com/google/iree/blob/e749314a05d7d0ff8bc174096ff546d6fc65ec1c/iree/tools/utils/vm_util.h#L79

**Comment by ScottTodd** [comment]
(you can also bring your own flags impl, including Abseil's, or avoid flags entirely, but maybe a different cast is needed to match that `string_view` parameter?)

**Comment by nick-furry** [comment]
I removed the flag in my program and had explicitly casted the driver name to both std::string and absl::string_view but gives the above linker error

**Comment by marbre** [comment]
As a more general note, if you want to use IREE in a thirdparty project, https://github.com/iml130/iree-template-cpp might be worth to look at.

**Comment by nick-furry** [comment]
Thank you @marbre and @ScottTodd for your inputs. I tried again with the above template and was able to sort the issue. The linker error was introduced due to a cmake file (which I thought to be innocuous!) that I was including in my project.
