### ISSUE TITLE
iree_bytecode_module can't generate the bytecode module if CC_NAMESPACE/C_OUTPUT field is not specified

### ISSUE THREAD

**Issue by hcindyl** [google/iree#5714]
If the user only want to generate the bytecode module (.vmfb), there's no artifact generated unless the field cc_namespace or c_output is specified.

**To Reproduce**
1. Make a copy of https://github.com/google/iree/blob/7c2d310/iree/samples/simple_embedding/CMakeLists.txt#L65-L78 and change the target name (e.g., byte_module_foo)
2. Remove the CC_NAMESPACE and C_OUTPUT field

$ cmake --build <build path> --target iree/samples/simple_embedding/all
$ ls <build path>/iree/samples/simple_embedding/
only the vmfb from simple_embedding_test_bytecode_module target is created along with the c/c++ code.

**Additional context**
bazel build is okay.

**Comment by GMNGeoffrey** [comment]
Yeah this is what I was saying about CMake being bad with generated files :-)

**Comment by GMNGeoffrey** [comment]
This is now correctly driven by a custom target, thanks to https://github.com/google/iree/pull/9387. Please reopen if you hit additional issues
