### ISSUE TITLE
Subtensor insert fails for tosa.concat

### ISSUE THREAD

**Issue by rsuderman** [google/iree#5729]
**Describe the bug**
Previously passing implementation of tosa.concat is now failing during both compilation and execution. Attached compilation failure as it is simplier to triage

**To Reproduce**
Attempt to compile the attached tosa test tosa test

`~/Repos/iree/iree-build/iree/tools/iree-translate -iree-mlir-to-vm-bytecode-module -iree-hal-target-backends dylib-llvm-aot <file>`

Fails during ConvertToHALPass with `TensorRewriteAdaptor newValue is invalid type`:

    %0 = linalg.init_tensor [12] : tensor<12xf32>
    %1 = flow.ex.stream.fragment(%0) : (tensor<12xf32>) -> %0 =
        (%arg0: tensor<12xf32>) -> tensor<12xf32> {
      %c0 = constant 0 : index
      %c6 = constant 6 : index
      %const_span_0 = hal.constant.subspan @_const_pool_storage_buffer[#hal.byte_range<80, 24>] : tensor<6xf32>
      %const_span_1 = hal.constant.subspan @_const_pool_storage_buffer[#hal.byte_range<48, 24>] : tensor<6xf32>
      %2 = flow.tensor.update %const_span_0, %arg0[%c0] : tensor<6xf32> -> tensor<12xf32>
      %3 = flow.tensor.update %const_span_1, %2[%c6] : tensor<6xf32> -> tensor<12xf32>
      flow.return %3 : tensor<12xf32>
    }

I am speculating the because no fill is performed on the init_tensor it never materializes into an allocation.

**Additional context**

**Comment by benvanik** [comment]
Hmm I'm surprised that this didn't fold away earlier - the whole thing should be constant (constant values getting inserted at constant indices into a statically shaped tensor).

I suspect the issue is the init_tensor - that should not be there.

**Comment by MaheshRavishankar** [comment]
(Cant find the attachment).

But the TOSA lowering should add a `linalg.fill` (related issue : https://github.com/google/iree/issues/4985) . `linalg.init_tensor` is purely used only for shape information. So it has no "data". Doing a `subtensor_insert` with result of `linalg.init_tensor` as destination should be illegal (hard to write a verifier for these, but we could)

**Comment by rsuderman** [comment]
Attached missing file.

[concat_6_float_axis_0.mlir.txt](https://github.com/google/iree/files/6423373/concat_6_float_axis_0.mlir.txt)

**Comment by rsuderman** [comment]
For validation we should be able to check that every init tensor is consumed by a LinalgOp. That should validate the init_tensor valid usecase.

**Comment by MaheshRavishankar** [comment]
I agree, but I think there are cases where `linalg.init_tensor` is being used for "data" upstream. Trying to avoid that in IREE. Should look into doing that though.

**Comment by rsuderman** [comment]
Inserting a superfluous fill corrected the issue. Long term we should consider having a method of allocating a tensor with "don't care" contents. Zeroing a tensor just to overwrite the values feels silly.

**Comment by benvanik** [comment]
Agreed! I mean, besides folding all of this away :)
Ideally the fill ends up inside of the dispatch region where it can be elided if the linalg ops fully populate the contents. This is needed because if we tried to guess from the outside whether the fill was required cases where padding require it would be missed. Lots of phase ordering stuff here, but I think the first steps are to insert the fills for correctness and then work to get them fused into linalg ops as much as possible (not as in/out here, but just pure outputs). Fills that remain outside can still be useful (resetting global variable state, constant broadcasts as DMA operations, etc) but should be pretty rare.

**Comment by rsuderman** [comment]
Upstream fix sent out:
https://reviews.llvm.org/D101848

**Comment by MaheshRavishankar** [comment]
Exactly. Thats why when this was done from MHLO there was an issue filed for it.
As it stands, most fill operations get fused with producer linalg ops alraedy. But with concat thats not always possible. So its a corner case. 
We could just make this particular fill a DMA op which will help a bit (maybe).

**Comment by rsuderman** [comment]
Fix is landed. Should appear on llvm-integrate.
