### ISSUE TITLE
Set up RISC-V CI test

### ISSUE THREAD

**Issue by hcindyl** [google/iree#5751]
Setting up RISC-V cross-compile CI test so we can catch the potential breakage sooner.

 - [x] Setup docker in GCR
 - [x] Setup Kokoro script
~~Setup buildkite yml script~~

**Comment by GMNGeoffrey** [comment]
If you're setting up a Kokoro script (as in #5762) there's no need to also set up buildkite

**Comment by hcindyl** [comment]
Oh, okay. I put the item out to see If the long-term plan is to move to buildkite. I will remove it.

**Comment by GMNGeoffrey** [comment]
If it is, then we can do it as part of that :slightly_smiling_face:

**Comment by hcindyl** [comment]
Turned the presubmit on check today.
