### ISSUE TITLE
Investigate a better benchmark dashboard

### ISSUE THREAD

**Issue by antiagainst** [google/iree#5766]
Right now we are using https://mako.dev/ as the dashboard to aggregate and present benchmark results. It's okay if we just have a few benchmarks to track; but as we are expanding the benchmark suite (which is a product of models/microbenchmarks x flavour x phones x hardware), it has a scalability problem: the system does not provide many configuration dimensions that we can map to the above and have flexible filtering to let different folks focusing on different subset of benchmarks of interest. Mako also performs analysis during result upload phaze and it does not have good integration with GitHub: one cannot easily see which commit is associated with a data point and easily go to the corresponding GitHub commit.

https://github.com/google/dana looks a better substitution. It is designed for benchmarking purpose, with flexible filtering, presentation, regression analysis etc.

**Comment by antiagainst** [comment]
We have https://perf.iree.dev now, powered by Dana. Marking as done.

**Comment by IlyasMoutawwakil** [comment]
hi @antiagainst , I'm very interested by your work on benchmarking models on different hardwares and backends. I really appreciate your explanations in this [blogpost](https://www.lei.chat/posts/android-native-library-benchmarking-pipeline-for-open-source-projects/). Can you please share with me how you managed to use Dana? it's not documented well and the demo is full of errors.

**Comment by antiagainst** [comment]
@IlyasMoutawwakil thanks for the interest! It has been a while since I set that up; so I'm not sure I can systematically recall all the details and lay them out consistently. What's your problem? Maybe I can provide some hints there. Feel free to create issues in Dana repo and at me there; given this is the IREE repo.

**Comment by IlyasMoutawwakil** [comment]
@antiagainst Thanks I'll at you in the issue.
