### ISSUE TITLE
Add one stop TensorFlow to execution quick start example

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#580]
Our colabs and examples are all geared towards IREE/compiler hacking versus simplest use as a user. We should organize them as developer tools and have one or two of the canonically simplest examples from TensorFlow to execution.

**Comment by ScottTodd** [comment]
I think this is fairly well addressed by https://colab.research.google.com/github/google/iree/blob/main/colab/tensorflow_hub_import.ipynb and https://colab.research.google.com/github/google/iree/blob/main/colab/tflite_text_classification.ipynb (not the simplest, but representative enough). https://colab.research.google.com/github/google/iree/blob/main/iree/samples/variables_and_state/variables_and_state.ipynb and some other notebooks are simpler but use toy programs.
