### ISSUE TITLE
Revisit the default SPIR-V CodeGen tiling and vectorization configurations

### ISSUE THREAD

**Issue by antiagainst** [google/iree#5852]
At the moment we only have good tiling and vectorization configurations for ARM architectures. For all other GPU architectures, we fallback to a set of "placeholder" configurations, which was chosen just to get started. We need to revisit this and put up a set of better default configurations to avoid let all other GPU architectures' performance fall off the cliff.

**Comment by MaheshRavishankar** [comment]
Kind of open-ended bug. Lets close this. We can re-open one if we have a specific task in mind.

**Comment by antiagainst** [comment]
That's fine for me. (I'm actually sort of working on this now.)
