### ISSUE TITLE
slim_vision_model_test tensorflow integration test fails for iree_vmvx backend

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#5924]
Running mobilenet_v2 & v3 with `vmvx` backend generates incorrect output (see [log](https://gist.github.com/asaadaldien/d835b6b6372355244e8bc1630fe256ea))

Repro:

```
 $ python3 integrations/tensorflow/e2e/slim_vision_models/slim_vision_model_test.py -tf_hub_url=https://tfhub.dev/google/imagenet/ -model=mobilenet_v2_100_224 -target_backends=iree_vmvx
```

**Comment by GMNGeoffrey** [comment]
https://github.com/google/iree/pull/5887 deleted coverage for vmla, but did not replace it with coverage for vmvx
