### ISSUE TITLE
Bad failure mode on malformed flag to iree-run-module

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#5931]
The following command hangs forever:

```shell
iree-run-module -module_file=/does/not/exist
```

The issue is that the flag passed with a single dash (a mistake people are likely to make given LLVM accepting them) is being interpreted as a positional argument and then iree-run-module happily proceeds looking for input on stdin. I think there are a few things we can do to make this better, although it is a tricky edge case:

1. Update our documentation to consistently use two dashes for long options. IMO it's bad that LLVM accepts a single dash for long options. It flies in the face of all the conventions I know of.
2. Error out on args that start with a single dash, when parsing flags: https://github.com/google/iree/blob/f6d36fecb5c1a5ca281318ea589cdad7eeb24bab/iree/base/internal/flags.c#L342-L345. It should still be possible to pass a literal dash with `\-`
3. Add error checking for unexpected positional arguments to flags parsing.
4. Make stdin something that has to be explicitly requested.
5. Print that we are reading from stdin when reading from stdin

**Comment by benvanik** [comment]
If LLVM supports `--` we should change all our docs to that - then less confusion/chances for mismatches. It makes sense for people to copy parts of commands and it triggers me when I see someone who (understandably) uses both in the same invocation :P

We can also enable support for `-` - it sucks but for the reasons you mention we should probably be consistently inconsistent along with LLVM just as an ease of use thing, even if we document everything as `--`.

**Comment by okkwon** [comment]
There was a similar bug that hangs when an invalid option is given. `iree-benchmark-module --module-file=foo.vmfb`. The option does not exist. The right one is `--module_file=foo.vmfb`. It just hangs waiting input from stdin instead of reporting a bad option.
