### ISSUE TITLE
Allow VMVX to be optionally built

### ISSUE THREAD

**Issue by antiagainst** [google/iree#5942]
Right now if setting `IREE_HAL_DRIVERS_TO_BUILD` to exclude `VMVX`, we can see errors like:

```
CMake Error at build_tools/cmake/iree_cc_test.cmake:76 (add_executable):
[build]   Target "iree_modules_strings_strings_module_test" links to target
[build]   "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
[build]   find_package() call is missing for an IMPORTED target, or an ALIAS target
[build]   is missing?
[build] Call Stack (most recent call first):
[build]   iree/modules/strings/CMakeLists.txt:39 (iree_cc_test)
```

This means we are assuming `VMVX` at places, which should be fixed and let `VMVX` be optional (or emit proper errors where it cannot be).

**Comment by hcindyl** [comment]
I think this issue is obsolete. `iree/modules/strings` is removed in https://github.com/google/iree/pull/6248
