### ISSUE TITLE
LinkExecutables pass overrides duplicate named tensors

### ISSUE THREAD

**Issue by rsuderman** [google/iree#5946]
**Describe the bug**
During the LinkExecutables pass for vmvx, duplicately named tensors are overridden to a single value. 

**To Reproduce**
Download the attached file and execute below:

`iree-opt /tmp/test.mlir.txt --split-input-file --iree-hal-link-executables --iree-hal-target-backends vmvx`

vm.rodata for both functions will result in being the same

**Additional context**
[test.mlir.txt](https://github.com/google/iree/files/6504932/test.mlir.txt)

**Comment by Hawkmike** [comment]
> **Describe the bug**
> During the LinkExecutables pass for vmvx, duplicately named tensors are overridden to a single value.
> 
> **To Reproduce**
> Download the attached file and execute below:
> 
> `iree-opt /tmp/test.mlir.txt --split-input-file --iree-hal-link-executables --iree-hal-target-backends vmvx`
> 
> vm.rodata for both functions will result in being the same
> 
> **Additional context**
> [test.mlir.txt](https://github.com/google/iree/files/6504932/test.mlir.txt)

**Comment by ScottTodd** [comment]
This sounds similar to what was discussed here: https://github.com/google/iree/issues/4897#issuecomment-800803557 , which points to an unresolved TODO here: https://github.com/google/iree/blob/b5f3dda010b4b3ed4982f11c3e3b72277ad84451/iree/compiler/Dialect/HAL/Target/TargetBackend.cpp#L113-L122

**Comment by ScottTodd** [comment]
Here's some debug output from that linking code:

```
symbol conflict: '__constant_4xi8'
target op:
vm.rodata @__constant_4xi8 dense<[0, 0, 0, 1]> : tensor<4xi8>
  (visibility public)
source op:
vm.rodata @__constant_4xi8 dense<[0, 0, 1, 0]> : tensor<4xi8>
  (visibility public)
ops are *not* equivalent, need to disambiguate
```

Relating this back to [the comment thread there](https://github.com/google/iree/issues/4897#issuecomment-800803557), could these `vm.rodata` ops be marked private ([Symbol Visibility docs](https://mlir.llvm.org/docs/SymbolsAndSymbolTables/#symbol-visibility))? I'm trying to decide how to resolve that conflict and it would be safer to only rename private symbols while merging modules.

**Comment by ScottTodd** [comment]
We have other private `RodataOp`s, like https://github.com/google/iree/blob/53b850448b371d4d828091c7617d2b51bdb5d8f2/iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertExecutableOps.cpp#L77-L84

What code is producing those in this case?

**Comment by benvanik** [comment]
RE visibility: rodata should all be private so it's worth setPrivate()ing everywhere.

**Comment by ScottTodd** [comment]
public rodata ops are coming from https://github.com/google/iree/blob/b154cd99df25272e17bb4cbb29438b70f445028b/iree/compiler/Dialect/VM/Conversion/MemRefToVM/ConvertMemRefToVM.cpp#L107-L109

I can reproduce this bug compiling https://github.com/google/iree/blob/main/iree/test/e2e/models/edge_detection.mlir:

```
symbol conflict: '__constant_3x3x1x1xf32'
target op:
vm.rodata @__constant_3x3x1x1xf32 dense<[-1.000000e+00, 0.000000e+00, 1.000000e+00, -2.000000e+00, 0.000000e+00, 2.000000e+00, -1.000000e+00, 0.000000e+00, 1.000000e+00]> : tensor<9xf32>
  (visibility public)
source op:
vm.rodata @__constant_3x3x1x1xf32 dense<[1.000000e+00, 2.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, -1.000000e+00, -2.000000e+00, -1.000000e+00]> : tensor<9xf32>
  (visibility public)
ops are *not* equivalent, need to disambiguate
```

I'll work on a fix to the linking pass. This is what I have sketched so far (to handle the general case):
```c++
// Destructively merges |sourceModuleOp| into |targetModuleOp|.
// |targetSymbolMap| is updated with the new symbols.
//
// If a private symbol in |sourceModuleOp| conflicts with another symbol
// (public or private) tracked in |targetSymbolMap|, it will be renamed and
// |privateSymbolOccurrences| will be updated to reflect this.
//
// Fails if a public symbol in |sourceModuleOp| conflicts with another public
// symbol tracked in |targetSymbolMap|.
static LogicalResult mergeModuleInto(
    Operation *sourceModuleOp, Operation *targetModuleOp,
    DenseMap<StringRef, Operation *> &targetSymbolMap,
    llvm::StringMap<unsigned> &privateSymbolOccurrences) {
```

that's modeled after @MaheshRavishankar 's earlier attempt here: https://github.com/MaheshRavishankar/iree/commit/7d3baeb0bd7fa0d8402daf1a3cefee8552a6b8f4
