### ISSUE TITLE
Failure lowering hal.constant.subspan inside flow.ex.stream.fragment

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#5989]
The following reproducer (extracted from a large model) results in an assert failure while running  `allocateTransientBuffers`: https://github.com/google/iree/blob/07bfdd4c8162d12ec2caf6946c7a1b7156569744/iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp#L366-L367

because the constant subspan op is mapped to multiple buffers.

```mlir
// configuration: -pass-pipeline='iree-convert-to-hal'

func @main() {
  %0 = flow.ex.stream.fragment() : () -> tensor<4x8x11x2xf32> =
      () -> tensor<4x8x11x2xf32> {
    %const_span = hal.constant.subspan @_const_pool_splats[#hal.byte_range<16, 2816>] : tensor<4x8x11x2xf32>
    flow.return %const_span : tensor<4x8x11x2xf32>
  }
  return
}
```

**Comment by GMNGeoffrey** [comment]
So in this particular case, the issue is that the constant.subspan is being processed twice. Once as an output buffer and once because of the special hardcoded logic for handling constant.subspan ops (https://github.com/google/iree/blob/07bfdd4c8162d12ec2caf6946c7a1b7156569744/iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp#L550). I assume that the assumption is that a stream returning a constant shouldn't have been formed at all. This particular stream wasn't originally that though, it was more like

```mlir
func main() -> tensor<4x8x11x2xf32> {
    %0 = flow.ex.stream.fragment(%arg65, %arg4, %arg3, %arg14) : (tensor<33708x7xf32>, tensor<7xf32>, tensor<7xf32>, tensor<7x22xf32>) -> tensor<4x8x11x2xf32> = (%arg66: tensor<33708x7xf32>, %arg67: tensor<7xf32>, %arg68: tensor<7xf32>, %arg69: tensor<7x22xf32>) -> tensor<4x8x11x2xf32> {
      %const_span = hal.constant.subspan @_const_pool_splats[#hal.byte_range<16, 2816>] : tensor<4x8x11x2xf32>
	  // many dispatches ...
      %23 = flow.tensor.reshape %22 : tensor<4x22xf32> -> tensor<4x1x11x2xf32>
      %24 = flow.tensor.update %23, %const_span[%c0, %c0, %c0, %c0] : tensor<4x1x11x2xf32> -> tensor<4x8x11x2xf32>
      flow.return %24 : tensor<4x8x11x2xf32>
  }
  return %0 : tensor<4x8x11x2xf32>
}
```

This stream processing code really makes too many assumptions that aren't even properly checked by preconditions and just randomly assert somewhere.

**Comment by GMNGeoffrey** [comment]
This is coming from the lowering of an `mhlo.dynamic-update-slice`, I'm pretty sure

**Comment by GMNGeoffrey** [comment]
It's interesting because the location information given from the diagnostic is not really very useful:

```
/tmp/mhlo_repro_cleaned.mlir:6:10: error: 'flow.ex.stream.fragment' op constant subspan op was mapped to multiple buffer ranges while allocating transient buffers
    %3 = "mhlo.compare"(%arg0, %2) {comparison_direction = "GT"} : (tensor<1x4xf32>, tensor<1x4xf32>) -> tensor<1x4xi1>
         ^
```

**Comment by GMNGeoffrey** [comment]
> It's interesting because the location information given from the diagnostic is not really very useful:

I've realized this is because the stream op has a fused location and the diagnostic handler only prints out the first one

**Comment by GMNGeoffrey** [comment]
Ok I was finally able to reduce the repro from the original mhlo mlir through various iterative removals followed by cleanup passes:


```mlir
  func @main(%arg0: tensor<4x1x11x2xf32>) -> tensor<4x8x11x2xf32> attributes {iree.module.export} {
    %0 = mhlo.constant dense<0.000000e+00> : tensor<4x8x11x2xf32>
    %1 = mhlo.constant dense<1.000000e+00> : tensor<4x1x11x2xf32>
    %2 = mhlo.constant dense<0> : tensor<i32>
    %3 = mhlo.multiply %arg0, %1 : tensor<4x1x11x2xf32>
    %4 = "mhlo.dynamic-update-slice"(%0, %3, %2, %2, %2, %2) : (tensor<4x8x11x2xf32>, tensor<4x1x11x2xf32>, tensor<i32>, tensor<i32>, tensor<i32>, tensor<i32>) -> tensor<4x8x11x2xf32>
    return %4 : tensor<4x8x11x2xf32>
  }
```

```shell
$ iree-opt --iree-hal-target-backends=dylib-llvm-aot --iree-transformation-pipeline repro.mlir
```

So as I suspected, the heart of this problem is the mhlo.dynamic-update-slice. So this is a local reproducer that actually comes from the above example (not the one generated by the MLIR reproducer generation because that one includes a bunch of unrelated goop.

```mlir
  // configuration: -pass-pipeline='iree-convert-to-hal'
  func @main(%arg0: tensor<4x1x11x2xf32>) -> tensor<4x8x11x2xf32> attributes {iree.module.export, iree.reflection = {f = "I14!B10!d4d1d11d2R14!B10!d4d8d11d2", fv = "1"}} {
    %0 = flow.ex.stream.fragment(%arg0) : (tensor<4x1x11x2xf32>) -> tensor<4x8x11x2xf32> =
        (%arg1: tensor<4x1x11x2xf32>) -> tensor<4x8x11x2xf32> {
      %c2 = constant 2 : index
      %c11 = constant 11 : index
      %c4 = constant 4 : index
      %c32 = constant 32 : index
      %const_span = hal.constant.subspan @_const_pool_splats[#hal.byte_range<0, 2816>] : tensor<4x8x11x2xf32>
      %1 = flow.tensor.reshape %arg1 : tensor<4x1x11x2xf32> -> tensor<4x11x2xf32>
      %2 = flow.dispatch @main_dispatch_0::@main_dispatch_0[%c2, %c11, %c4](%1) {hal.bindings = [#hal.ex.operand_buffer<"s0b0_ro_external", 0 : index>, #hal.ex.result_buffer<"s0b1_xw_external", 0 : index>]} : (tensor<4x11x2xf32>) -> tensor<4x11x2xf32>
      %3 = flow.dispatch @main_dispatch_1::@main_dispatch_1[%c2, %c11, %c32](%2, %const_span) {hal.bindings = [#hal.ex.constant_storage<"s0b0_ro_constant", "_const_pool_splats", 0 : index, 2816 : index>, #hal.ex.operand_buffer<"s0b1_ro_external", 0 : index>]} : (tensor<4x11x2xf32>, tensor<4x8x11x2xf32>) -> %const_span
      flow.return %3 : tensor<4x8x11x2xf32>
    }
    return %0 : tensor<4x8x11x2xf32>
  }
```

**Comment by GMNGeoffrey** [comment]
Ah sorry I forgot to note that the above repro is with Hanhan's changes patched in (lowering mhlo.dynamic-update-slice to linalg on tensors). That's why it's a dispatch now, I'd guess.

**Comment by GMNGeoffrey** [comment]
The same initial mhlo triggers the same issue without that patch as well. In this case the local reproducer is

```mlir
  // configuration: -pass-pipeline='iree-convert-to-hal'
  func @main(%arg0: tensor<4x1x11x2xf32>) -> tensor<4x8x11x2xf32> attributes {iree.module.export, iree.reflection = {f = "I14!B10!d4d1d11d2R14!B10!d4d8d11d2", fv = "1"}} {
    %0 = flow.ex.stream.fragment(%arg0) : (tensor<4x1x11x2xf32>) -> tensor<4x8x11x2xf32> =
        (%arg1: tensor<4x1x11x2xf32>) -> tensor<4x8x11x2xf32> {
      %c2 = constant 2 : index
      %c11 = constant 11 : index
      %c4 = constant 4 : index
      %c0 = constant 0 : index
      %const_span = hal.constant.subspan @_const_pool_splats[#hal.byte_range<0, 2816>] : tensor<4x8x11x2xf32>
      %1 = flow.tensor.reshape %arg1 : tensor<4x1x11x2xf32> -> tensor<4x11x2xf32>
      %2 = flow.dispatch @main_dispatch_0::@main_dispatch_0[%c2, %c11, %c4](%1) {hal.bindings = [#hal.ex.operand_buffer<"s0b0_ro_external", 0 : index>, #hal.ex.result_buffer<"s0b1_xw_external", 0 : index>]} : (tensor<4x11x2xf32>) -> tensor<4x11x2xf32>
      %3 = flow.tensor.reshape %2 : tensor<4x11x2xf32> -> tensor<4x1x11x2xf32>
      %4 = flow.tensor.update %3, %const_span[%c0, %c0, %c0, %c0] : tensor<4x1x11x2xf32> -> tensor<4x8x11x2xf32>
      flow.return %4 : tensor<4x8x11x2xf32>
    }
    return %0 : tensor<4x8x11x2xf32>
  }
```

**Comment by GMNGeoffrey** [comment]
It really doesn't make sense that we'd be doing an update into a constant span. Seems like trying to write into that is both bad and is what's causing the issue here.

**Comment by GMNGeoffrey** [comment]
@rsuderman am I remembering right that you looked at dynamic-update-slice at some point? It looks like somewhere in the pipeline we're trying to overwrite an existing tensor which doesn't work with the value semantics. I have a vague recollection of us arguing about this before :stuck_out_tongue: (sorry if I'm misremembering).

https://www.tensorflow.org/xla/operation_semantics#dynamicupdateslice definitely implies value semantics to me.

Obviously at some point in the pipeline we should realize that that constant is only ever used for one thing, that it's a splat, and that it's getting overwritten so the whole thing shouldn't be externed into some constant pool at all.

In fact, in this particular case I think the dynamic-update-slice could be converted to a pad operation, since the constant is a splat: https://www.tensorflow.org/xla/operation_semantics#pad. But IMO that's also just working around some other issues we have here

**Comment by GMNGeoffrey** [comment]
It's not clear to me whether conversion of an `mhlo.dynamic-update-slice` to an `mhlo.pad` would be considered a candidate for a canonicalization, but I think it might be a pattern we want and we could add it to [HLOToHLOPreprocessing](https://github.com/google/iree/blob/main/iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp). Again this is just a workaround for what is fundamentally at least one bug in the compiler, but given that we're trying to delete all the stream stuff in the next month or so, it might be an OK workaround. A pattern that does something like:

```mlir
%target = mhlo.constant dense<0.000000e+00> : tensor<4x8x11x2xf32>
%1 = mhlo.constant dense<0> : tensor<i32>
%2 = "mhlo.dynamic-update-slice"(%target, %update, %1, %1, %1, %1) : (tensor<4x8x11x2xf32>, tensor<4x1x11x2xf32>, tensor<i32>, tensor<i32>, tensor<i32>, tensor<i32>) -> tensor<4x8x11x2xf32>
```
->
```mlir
%c0 = mhlo.constant dense<0.000000e+00> : tensor<f32>
%1 = "mhlo.pad"(%update, %c0) {
    edge_padding_low = dense<0> : tensor<4xi64>,
    edge_padding_high = dense<[0, 7, 0, 0]> : tensor<4xi64>,
    interior_padding = dense<0> : tensor<4xi64>
} : (tensor<4x8x11x2xf32>, tensor<f32>) -> tensor<4x8x11x2xf32>
```

Could also be a more generic lowering to an `mhlo.dynamic_pad` which then already has canonicalizations to get canonicalized to a pad, but I think the value prop is maybe less clear if you have to do math on all the padding dimensions.

**Comment by GMNGeoffrey** [comment]
Lei seems like you've figured out a fix for this while I was out? I should go on vacation more often :grin:

**Comment by antiagainst** [comment]
Shhh, don't tell anyone. 😊  I was hitting the same issue when addressing a new segfault after rebasing https://github.com/google/iree/pull/5614 to the top of the tree. Let me address comments and try to get the fix landed.

**Comment by antiagainst** [comment]
https://github.com/google/iree/pull/6174 should address this. @GMNGeoffrey please verify and close the issue.

**Comment by GMNGeoffrey** [comment]
Was about to comment on that issue asking if you could add a test like:

```mlir
  func @main(%arg0: tensor<1xf32>) -> tensor<8xf32> attributes {iree.module.export} {                                                                         
    %0 = mhlo.constant dense<0.0> : tensor<8xf32>                                                                                                    
    %2 = mhlo.constant dense<0> : tensor<i32>                                                                                                                 
    %4 = "mhlo.dynamic-update-slice"(%0, %arg0, %2) : (tensor<8xf32>, tensor<1xf32>, tensor<i32>) -> tensor<8xf32>                                            
    return %4 : tensor<8xf32>                                                                                                                                 
  }
```

I'll follow-up with that. Thanks for addressing!
