### ISSUE TITLE
Basic dynamic-update-slice crashes runtime

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#6013]
Running the following check test triggers an assert in the runtime

```mlir
func @dynamic_update_slice() attributes { iree.module.export } {
  %target = iree.unfoldable_constant dense<2> : tensor<3x3xi32>
  %update = iree.unfoldable_constant dense<1> : tensor<2x2xi32>
  %c0 = iree.unfoldable_constant dense<0> : tensor<i32>
  %result = "mhlo.dynamic-update-slice"(%target, %update, %c0, %c0)
    : (tensor<3x3xi32>, tensor<2x2xi32>, tensor<i32>, tensor<i32>) -> tensor<3x3xi32>
  check.expect_eq_const(%result, dense<[
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2]]> : tensor<3x3xi32>) : tensor<3x3xi32>
  return
}
```

> check_vmvx_vmvx_dynamic-update-slice.mlir: iree/task/worker.c:262: _Bool iree_task_worker_pump_once(iree_task_worker_t *, iree_task_submission_t *): Assertion
 `!!((__builtin_expect(!!((uintptr_t)(status) == IREE_STATUS_OK), 1)))' failed.  

This is I think the same op as is triggering https://github.com/google/iree/issues/5989, but the above snippet doesn't trigger the same compilation failure. See also https://github.com/google/iree/issues/5982

We already do have dynamic-update-slice in two other places in the repo though, so it's not like this is just totally unsupported.

**Comment by GMNGeoffrey** [comment]
@hanhanW do you want to take a look at this as part of #5982? Are support story here is weird, but I'd guess that there's a miscompile here that is just hitting really bad error behavior in the runtime

**Comment by hanhanW** [comment]
Thanks for the snippet! I will take a look at this. IIRC, sometimes we don't want to lower subtensor/subtensor_insert to flow ops directly. Instead, we would expect some of them to be pull into a dispatch. Let me try with a similar support we have in dynamic-slice, remove the old lowering we had, and see how to proceed it.

cc @MaheshRavishankar

**Comment by hanhanW** [comment]
It's working on my local side and I send out the change to @GMNGeoffrey. We need:
- Land the lowering to MHLO repo
- Delete the pattern in HLOToFlow

I verified that it's working with `iree-run-mlir`. I will check the test in after reviews and integrations.

**Comment by MaheshRavishankar** [comment]
> It's working on my local side and I send out the change to @GMNGeoffrey. We need:
> 
> * Land the lowering to MHLO repo
> * Delete the pattern in HLOToFlow
> 
> I verified that it's working with `iree-run-mlir`. I will check the test in after reviews and integrations.

Without knowing the details, there might be a use case to lower it to flow. We cant fuse dynamic update slice with anything. AFAICS it should map to a `subtensor_insert`. Lowering to flow avoids using a kernel dispatch for it. Doing a DMA operation is almost always beneficial if there is no opportunity for fusion (as is the case here). Not all `subtensor_insert`s can lower to `flow.tensor.update` ops, but for those that do (which are supported today) its better to lower to Flow for these.

**Comment by hanhanW** [comment]
They are lowered to `subtensor_insert` in https://github.com/tensorflow/mlir-hlo/commit/28c411606f8b28bf3e83d6202eefa7faffea20c5

The end-to-end works with that pattern.
