### ISSUE TITLE
Define a CMake flag to build the bare-metal target without the thread dependency

### ISSUE THREAD

**Issue by hcindyl** [google/iree#6027]
Currently `third_party/benchmark` and `third_party/abseil-cpp` have hard dependency of the thread library, as well as some modules utilize the thread library. For bare-metal target, thread library is not necessary available. Without an option to filter out the dependency, the bare-metal target is not buildable.

**Comment by hcindyl** [comment]
Aside from excluding `third_party/benchmark`, `third_party/cpuinfo`, and  `third_party/abseil-cpp` from the top-level CMakeLists.txt, Also need to find ways to untangle the following libraries

 - [ ] iree/base/time.c  -- ` #error IREE system clock needs to be set up for your platform`
 - [ ] iree/hal/driver_registry.c -- part of iree::hal library but requires thread support

Other runtime libraries could be configured with CMake option flag to avoid the thread dependency.

**Comment by hcindyl** [comment]
Also, `IREE_BUILD_TESTS` option needs to be disabled util https://github.com/google/iree/issues/3848 is properly addressed.

**Comment by benvanik** [comment]
Nice cleanup!

> Aside from excluding `third_party/benchmark`, `third_party/cpuinfo`, and `third_party/abseil-cpp` from the top-level CMakeLists.txt, Also need to find ways to untangle the following libraries
> 
> * [ ]  iree/base/time.c  -- ` #error IREE system clock needs to be set up for your platform`
> * [ ]  iree/hal/driver_registry.c -- part of iree::hal library but requires thread support

You will need to implement time for your platform (or no-op it, but that's dangerous).

driver_registry does not require threading - just synchronization/call_once which are going to be present in other places as well and need to be stubbed out when safe. There's a flag in iree/base/config.h `IREE_SYNCHRONIZATION_DISABLE_UNSAFE` - when set to 1  iree/base/internal/synchronization.h should switch to being no-ops but it looks like iree/base/internal/call_once.h still needs that #if. Once done you can set that config define when building for bare-metal and things should work (bare-metal does not always imply single-core and single-core does not always imply bare-metal so we want to ensure we are keeping those orthogonal). Things like call_once and synchronization will show up in other places too and you won't be able to cleanly avoid them so it's best to get them no-op'ed correctly (for example, the HAL module will depend on driver_registry soon).

I started work on abstracting out third_party/benchmark (iree/testing/benchmark.h) but it needs an alternative implementation - once that's done we should be able to make third_party/benchmark optional but conditionally excluding for now sounds good to me.

I'm still not sure I like third_party/cpuinfo - it's what xnnpack uses, but it's big (almost the same size as the entire IREE runtime!) and we aren't even really using it today. It's only used by some helpers in iree/task/topology.h so it'll at least be excludable like you mention and as a follow-up I may use that as an excuse to remove it entirely soon :)

**Comment by hcindyl** [comment]
Re: third_party/cpuinfo:

The library doesn't support RISCV, so for my immediate application, it will not provide useful insight even it is buildable. The baremetal doesn't include `iree/task` subdirectory since it uses the synchronized executor (which is how I came up with the cleanup PR), so I am fine of not using cpuinfo at all. :)

I also found IREE_SYNCHRONIZATIOM_DISABLE_UNSAFE macro and noticed it was not used in call_once. Will look into that next unless you are working on it already. Totally agree baremetal != single core, so my approach is to set the macro explicitly in the `cmake/riscv.toolchain.cmake` as part of this exploration (may move it CLI later).

**Comment by hcindyl** [comment]
> Also, `IREE_BUILD_TESTS` option needs to be disabled util #3848 is properly addressed.

We probably need to rewrite some low-level tests in base/hal in the binary executable form (and test with binary_test or lit_test) so we can test the bare-metal behavior.
