### ISSUE TITLE
How is the initialization of global ops supposed to work in a bytecode module? 

### ISSUE THREAD

**Issue by simon-camp** [google/iree#6033]
I'm currently expanding the [vm unit tests](https://github.com/google/iree/tree/main/iree/vm/test) around global ops and hit issues regarding intialization of globals as both of the following tests fail.

```mlir
vm.module @global_ops {

  //===--------------------------------------------------------------------===//
  // global.i32
  //===--------------------------------------------------------------------===//

  vm.global.i32 @c42 mutable 42 : i32
  vm.global.i32 @c42_init mutable init(@initializer) : i32

  vm.func @initializer() -> i32 {
    %c42 = vm.const.i32 42 : i32
    // This ensures the initializer doesn't get folded into an initial_value attribute.
    %c42_dno = iree.do_not_optimize(%c42) : i32
    vm.return %c42_dno : i32
  }

  vm.export @test_global_load_i32
  vm.func @test_global_load_i32() {
    // The global is marked mutable to prevent folding into a vm.const.i32.
    %actual = vm.global.load.i32 @c42 : i32
    %expected = vm.const.i32 42 : i32
    vm.check.eq %actual, %expected, "@c42 != 42" : i32
    vm.return
  }

  vm.export @test_global_load_i32_init
  vm.func @test_global_load_i32_init() {
    %actual = vm.global.load.i32 @c42_init : i32
    %expected = vm.const.i32 42 : i32
    vm.check.eq %actual, %expected, "@c42_init != 42" : i32
    vm.return
  }
}
```

I haven't found any code regarding this in the bytecode module initialization or serialization. Some clarification or links to the correct code would be welcome.

**Comment by benvanik** [comment]
This pass finds all the initializers and creates a single exported `__init` function: https://github.com/google/iree/blob/552d3f888e46f96c8227b1bd2e4600b85338237b/iree/compiler/Dialect/VM/Transforms/GlobalInitialization.cpp

Examples:
https://github.com/google/iree/blob/6dfc315bd853e15d90b48b7ee982df60580abb68/iree/compiler/Dialect/VM/Transforms/test/global_initialization.mlir

Then that is called automatically by the VM context on creation: https://github.com/google/iree/blob/a14d612aaac7d720edc2e73f90d2f9ce22b47565/iree/vm/context.c#L389-L390

So you shouldn't have to do anything special - you'll just have an __init function and it's called for you.

**Comment by benvanik** [comment]
(if you're having issues you should make sure the __init function is being emitted and called)

**Comment by benvanik** [comment]
(closing for now as there's the answer above - feel free to ping on discord if you have any more questions!)
