### ISSUE TITLE
Unsupported select op lowering in the pipeline (on scalar, tensor<>, tensor<> form)

### ISSUE THREAD

**Issue by hanhanW** [google/iree#6034]
I'm seeing some interesting patterns in ASR models. We sometimes would have std `select` op in the MLIR files. E.g.,

```mlir
    %1 = tensor.extract %arg0[] : tensor<i1>
    %2 = select %1,  %cst, %arg1 : tensor<i1>
```

This kind of pattern is not supported in IREE. The select op won't be lowered to Linalg ops because the condition is `i1`. It will live until convertToHAL pass. There are couple ways to fix such issue at different levels.

# Handle select op conversion in ConvertToHAL Pass

I had a prototype on local side and it does address the issue. I verified that we have a pattern to convert select ops to VM dialect, and I feel we miss the pattern to convert it convert to HAL. Note that the pattern is needed because type conversion is involved. This is also the easiest way to unblock ASR compilation.

# Run a std to mhlo preprocessing pass

If the select op is taking condition from a 0-D tensor, we can broadcast the condition and pass to `select`. In this case, we will drop tensor.extract op and it meets all the use cases of this pattern in ASR models. Since they are introduced by importing tool, it's fair to add the pattern to preprocessing pass. Ideally, we should run it in the importing stage, like HLOToHLOPreprocessing.

The implementation can be found at https://github.com/google/iree/pull/5906

One of the benefits is that we can avoid memory readback on host side. If we handle the case later than PrePartitioningConversionPass, the `tensor.extract` op will be lowered to `flow.tensor.load` and we will read the data back to host.

# Convert select ops to Linalg ops

I had a prototype for this, but this does not work end-to-end. Because one of the operand is scalar, not tensor. We can not pass it to the input of linalg.generic op. Instead, we can use the scalar value in the body directly. In this case, we will pass some scalars to `flow.dispatch.workgroups`, which I believe that it violates some policy in IREE. The approach in my mind is to convert the scalar to tensor using `tensor.from_element`, and add support for bufferization.

E.g.,

```
    %1 = tensor.extract %arg0[] : tensor<i1>
    %2 = tensor.from_elements %1 : tensor<i1>
    %3 = linalg.generic {...} ins(%2, %true_value, %false_value) ...
```

If this happens before PrePartitioningConversionPass, I think we can fold tensor operations out. Like we probably want to handle tensor.extract in ConvertToFlowOpsPass, not PrePartitioningConversionPass. If we still have some `tensor.from_elements` ops during bufferization stage. We can reference to Bufferization pass in MLIR core and figure out how to support it in IREE.

**Comment by hanhanW** [comment]
I think I will go with the first approach. Others are more like improvements to me, so I put some of my investigations here.

**Comment by stellaraccident** [comment]
My PR (https://github.com/google/iree/pull/6030) suspiciously hit some of these same load promotion issues last week and I did rework some of it. Might be useful to sequence this after that -- how the input pipeline is layered right now for load promotion is not great. Hoping to land that PR in the next ~day.

**Comment by hanhanW** [comment]
SG! I think in either way, we still can add support for doing type conversion for select op in ConvertToHAL pass. IREE host side is able to handle the case.

For load promotion issue, we can revisit it after you land the PR.
