### ISSUE TITLE
[bazel-to-cmake]: Open Tasks

### ISSUE THREAD

**Issue by marbre** [google/iree#607]
Just an issue list to track what still needs to be done. Feel free to edit/extend.

- [x] Add support for `iree_flatbuffer_cc_library()`
- [x] Do not translate tablegenerated deps to `DEPS`:
  * This leads to linkage failures, if it is includes in a library marked as `ALWAYSLINK`.
  * The IREE targets end on the suffix `_gen` or `Gen`.
  * Targets ending on `_gen` are already filtered, but there might be a cleaner solution.
  * We might add these dependencies via `add_dependency()` to the CMake targets, also a dep is existing implicitly via file depends. This would require to extend `iree_cc_library`.
- [ ] Handle visibility, as discussed in #548.
- [x] Add support for trampoline deps.
- [x] Add support for `textual_headers`, added with #604.

**Comment by marbre** [comment]
I think @GMNGeoffrey has fixed trampoline deps.

**Comment by GMNGeoffrey** [comment]
Fixed enough :-D

**Comment by marbre** [comment]
As only the visibility remains and this one is documented in a separate issue, I am closing this task list.
