### ISSUE TITLE
Canonicalizer causes wrong types for flow.ex.stream.fragment op

### ISSUE THREAD

**Issue by hanhanW** [google/iree#6075]
To repro:

```mlir
module  {
  func @foo(%arg0: tensor<i32>) -> tensor<1xi32> {
    %0 = flow.ex.stream.fragment(%arg0) : (tensor<i32>) -> tensor<1xi32> =
        (%arg1: tensor<i32>) -> tensor<1xi32> {
      %1 = flow.tensor.reshape %arg1 : tensor<i32> -> tensor<1xi32>
      flow.return %1 : tensor<1xi32>
    }
    return %0 : tensor<1xi32>
  }
}
```

Run `iree-opt -canonicalize foo.mlir`, and you will see

```mlir
module  {
  func @foo(%arg0: tensor<i32>) -> tensor<1xi32> {
    %0 = flow.ex.stream.fragment(%arg0) : (tensor<i32>) -> %arg0 =
        (%arg1: tensor<i32>) -> tensor<1xi32> {
      %1 = flow.tensor.reshape %arg1 : tensor<i32> -> tensor<1xi32>
      flow.return %1 : tensor<1xi32>
    }
    return %0 : tensor<1xi32>
  }
}
```

If you pass the output to `iree-opt`, it will complain:

```
...: error: use of value '%0' expects different type than prior uses: 'tensor<1xi32>' vs 'tensor<i32>'
    return %0 : tensor<1xi32>
           ^
...:3:5: note: prior use here
    %0 = flow.ex.stream.fragment(%arg0) : (tensor<i32>) -> %arg0 =
```

**Comment by hanhanW** [comment]
I actually don't know if this is a blocker. I found this issue when creating repro for other bugs.

**Comment by benvanik** [comment]
There's probably a few things hiding here, two I spot immediately are
* we shouldn't be creating a stream that only does a reshape like this
* the operand is tied (` -> %arg0`) but the shape differs between operand and result which is invalid

Right now tied operands assume they have the same shape so disallowing tying when the shape differs would probably unblock this. It'd be really nice if they were tied, though, so one approach would be to insert the reshapes to keep the shapes the same (here, inserting a reshape to `f32` on the inside of the stream and to `1xf32` outside of the stream.

A pattern to elide streams that have no dispatchable operations can come after - right now this would create some pretty silly behavior where an empty command buffer is created and submitted :P

**Comment by hanhanW** [comment]
This also happens on other cases. The reshape one is the simplest IR I found. :-D

Some other examples are:

```
  %97:3 = flow.ex.stream.fragment(%c6, %c1, %96, %arg4) : (index, index, tensor<6xi32>, tensor<i32>) -> (tensor<i1>, tensor<1xi32>, tensor<i8>) =
      (%arg17: index, %arg18: index, %arg19: tensor<6xi32>, %arg20: tensor<i32>) -> (tensor<i1>, tensor<1xi32>, tensor<i8>) {
    %300 = flow.dispatch @run_dispatch_44::@run_dispatch_44[%arg17, %arg18, %arg18](%arg19) : (tensor<6xi32>) -> tensor<6xi1>
    %301 = flow.dispatch @run_dispatch_45::@run_dispatch_45[%arg18, %arg18, %arg18](%300) : (tensor<6xi1>) -> tensor<i1>
    %302 = flow.tensor.reshape %arg20 : tensor<i32> -> tensor<1xi32>
    %303 = flow.dispatch @run_dispatch_3::@run_dispatch_3[%arg18, %arg18, %arg18](%301) : (tensor<i1>) -> tensor<i8>
    flow.return %301, %302, %303 : tensor<i1>, tensor<1xi32>, tensor<i8>
  }
```

After pasting the IR, I found that it also only apply reshape op on the argument. There are more cases, but I did not check all of them.

**Comment by benvanik** [comment]
Awesome - thanks for the examples! I'll work on this today.
