### ISSUE TITLE
Operand fusion breaks compilation for Vulkan GPU

### ISSUE THREAD

**Issue by hanhanW** [google/iree#6086]
We can't compile the model for benchmarking with `--iree-flow-dispatch-formation-enable-operand-fusion`. We had the flag in iree_mlir_benchmark_suite, but it is not working now.

To repro:

Run `iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vulkan-spirv ~/mobilenet-v2/iree_input.mlir -o a.vmfb --iree-input-type=mhlo --iree-vulkan-target-triple=valhall-unknown-android11 --iree-flow-inline-constants-max-byte-length=2048 --iree-flow-dispatch-formation-enable-operand-fusion --iree-enable-fusion-with-reduction-ops`

Will see some errors like `unhandled allocation type`, which was generated from `AllocOpPattern` in StandardToSPIRV pass.

**Comment by antiagainst** [comment]
Yeah, it's broken. Although the convolution and element-wise consumer op are still put in the same dispatch region, `TileAndVectorizeInOneWorkgroupPass` does not kick in: no vectorization at all. Looking into this..
