### ISSUE TITLE
Operand fusion in MobileNet causing segfaults on ARM CPU

### ISSUE THREAD

**Issue by antiagainst** [google/iree#6090]
**Describe the bug**
Compiling MobileNetV2 with operand fusion generates modules that causes segfault when running after dfc2f7dcd810fc6e84b3a33552004845231bee98.

**To Reproduce**

1. Download input mhlo model from https://storage.googleapis.com/iree-model-artifacts/MobileNetV2-b0c5c584.tar.gz.
2. Compile with `iree/tools/iree-translate -iree-input-type=mhlo -iree-mlir-to-vm-bytecode-module -iree-hal-target-backends=dylib-llvm-aot --iree-llvm-target-triple=aarch64-none-linux-android29 -iree-flow-inline-constants-max-byte-length=2048 -iree-flow-dispatch-formation-enable-operand-fusion --iree-llvm-loop-unrolling=true -o compiled.vmfb /path/to/MobileNetV2`.
3. Run `iree-translate --flagfile=/path/to/flagfile` with the following flagfile content
```
--driver=dylib
--module_file=compiled.vmfb
--entry_function=call
--function_input=1x224x224x3xf32
--task_topology_group_count=1

```

**Additional context**

(Not sure operand fusion is the root cause though; but at least it reveals the problem. Maybe related to #5857 or not.)

**Comment by asaadaldien** [comment]
I am not familiar with operand fusion. @antiagainst Does it create extra memory allocations when fusing ? if Yes, we should disable it for CPU especially dispatching CPU workgroups is very cheap and aggressive fusion while creating extra stack allocations won't have any performance benefits It might be worse.

**Comment by MaheshRavishankar** [comment]
+1 for disabling operand fusion on CPU. It is not intended to create extra stack allocation, but it needs to be plumbed through properly to cover all cases.

**Comment by antiagainst** [comment]
It was already disabled via #6089. I haven't looked into details why; I suspect it's triggering segfault due to other reasons. Also failing on GPU (#6086); hopefully after fixing that it will be more clear.

**Comment by MaheshRavishankar** [comment]
This is superceded by #6973. Closing.
