### ISSUE TITLE
atomic alignment warning in iree/base/internal/synchronization.c while building for 32-bit bare-metal system

### ISSUE THREAD

**Issue by hcindyl** [google/iree#6102]
Discover this issue while investigating https://github.com/google/iree/issues/6027.

Set `IREE_SYNCHRONIZATION_DISABLE_UNSAFE` macro to 1 in this case

```
[22/112] Building C object iree/base/internal/CMakeFiles/iree_base_internal_synchronization.dir/synchronization.c.obj
.../iree/iree/base/internal/synchronization.c:567:8: warning: large atomic operation may incur significant performance penalty; the access size (8 bytes) exceeds the max lock-free size (4  bytes) [-Watomic-alignment]
      (iree_atomic_load_int64(&notification->value, iree_memory_order_seq_cst) &
       ^
.../iree/iree/base/internal/atomics.h:97:32: note: expanded from macro 'iree_atomic_load_int64'
#define iree_atomic_load_int64 iree_atomic_load_auto
                               ^
.../iree/iree/base/internal/atomics_clang.h:45:3: note: expanded from macro 'iree_atomic_load_auto'
  __c11_atomic_load((object), (order))
...
6 warnings generated.
```
The warnings seem to be related to https://github.com/google/iree/blob/931a3b1465246e81ea99d8d7b308626c50709238/iree/base/internal/synchronization.c#L562-L644
with the `iree_atomic_load_int64` and `iree_atomic_add_int64` calls.

I am not sure how this would actually affect the runtime perf yet, but just wondering if these are expected warnings for the 32-bit target.

**Comment by benvanik** [comment]
Probably just need to change it so that the DISABLE macro swaps to an entirely different implementation that is either no-op or just an int flag. It's just a performance warning, though, so nothing to worry about.

**Comment by benvanik** [comment]
#6265 added a disable path; the warning would still be nice to avoid on 32-bit targets that are using threading and could probably be silenced with a #pragma warning of some sort. Will leave this open for now.
