### ISSUE TITLE
mhlo.iota should support unsigned ints

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#6107]
```
%699 = "mhlo.iota"() {iota_dimension = 0 : i64} : () -> tensor<30000xi32>
```

Fails in legalization to linalg.

**Comment by stellaraccident** [comment]
Also note that the actual model is operating on a `ui32` tensor (I sed-ed it to overcome some signed issues at this point)

**Comment by hanhanW** [comment]
Yes, I created a change in MHLO repo. It will be supported after landing it.

**Comment by hanhanW** [comment]
The change is landed. https://github.com/tensorflow/mlir-hlo/commit/25b93c8d666118a176da07f35e0f0a29f2a85d02
