### ISSUE TITLE
Integrate new Symbol DCE infra in MLIR to IREE

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#614]
This should eliminate a lot of unused symbols and related code from VM binaries.

**Comment by silvasean** [comment]
Also, we should use it in tf_saved_model dialect.

**Comment by marbre** [comment]
@stellaraccident I assume you're referring to https://github.com/llvm/llvm-project/commit/b276dec5b65dfb885bf661484b9eab1e719c5e47.
Do you explicitly have the VM dialect in mind, as you mention VM binaries, or do you suggest to add the DCE pass also to other dialects within the IREE repo?

**Comment by silvasean** [comment]
Also, I'm not sure that anything in IREE can create dead symbols, so I
don't know the priority of this work. Of course, it is still useful for VM
to have this so that it is a nice standalone dialect.

-- Sean Silva

**Comment by antiagainst** [comment]
I think all those unused `vm.import`s can be trimmed away? Certain unused global variables after optimization, too.

**Comment by benvanik** [comment]
As an update, some of this has started to make its way in (for example, I'm tagging vm.imports with symbol visibility so they'll go away), but there's still a comprehensive sweep required to clean things up.

**Comment by silvasean** [comment]
This would be a great starter bug! Geoff: maybe Phoenix could take a look
at this?

**Comment by benvanik** [comment]
A remaining issue I found today was that some of our input paths and tests have all symbols as public, which means that if you use that as your signal as to whether to export or not you'll end up exporting private functions (and trying to run them through the ABI mangling and such). Should just be a burn down on the unit tests until things pass adding `SymbolTable::Visibility::Private` to things.

I'm tagging a few bits of code with this github issues - there shouldn't be much to cleanup once solved and finding code paths that break is mostly trying things when `iree.module.export` is disabled.

**Comment by benvanik** [comment]
@GMNGeoffrey I vaguely recall chatting about removing `iree.module.export` a week or two ago - were you looking into that? That may be enough to call this one complete.

**Comment by GMNGeoffrey** [comment]
I'm not actively pursuing it, no. Just remember you saying it shouldn't be necessary on one of my changes, so I tried removing it and determined that it was definitely still necessary :-D

**Comment by benvanik** [comment]
Darn :P Well, if you're looking for something to poke at on the compiler side this would be a good one.
