### ISSUE TITLE
Investigate continuously testing Colab notebooks and other samples

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#6165]
<sub>discussion on Discord: [link](https://discord.com/channels/689900678990135345/689957613152239638/852319263607226369)</sub>

Some of our user-facing samples are valuable to have in the main IREE repo but are not tested on our infrastructure. These samples are prone to bit rot and we currently rely on developers or users running them periodically to report issues.

Some ideas:

* Execute Colab notebooks via some mechanism like `jupyter nbconvert --execute <notebook>` and check for exceptions
  * diffing of outputs will be unreliable since we have so much variance in our outputs (version numbers, randomness / imprecision in model weights, logging from TF and IREE, etc.)
* include a `run.sh` or `test.sh` script with samples that runs any applicable cmake commands, notebooks, etc. and check those on our CI

**Comment by ScottTodd** [comment]
Once we have tests to run, we can figure out where/when to actually run them. The Colab notebooks in particular depend on Python packages that could either be sourced from a build (using our release pipeline?) or from the GitHub releases. There may be no (reasonable) way to make a code change to the compiler and test/update affected Colab notebooks in the same commit. Something running nightly that alerts but does not block PRs would still be an improvement over what we have now.

**Comment by benvanik** [comment]
+1 to nightly/per-release - anything is better than nothing!

**Comment by ScottTodd** [comment]
> +1 to nightly/per-release - anything is better than nothing!

Both have pros/cons, and ways to trigger using github actions (https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release). Probably similar story for Buildkite.

**Comment by ScottTodd** [comment]
Early signs are good for testing our Colab notebooks, as well as any samples that depend on their outputs.

I'm still putting something together, but the Colab bits look roughly like:
```shell
# Run under a virtual environment to isolate Python packages.
python -m venv .venv
source .venv/bin/activate
# TODO(scotttodd): deactivate at the end of the python steps
#                  (try/catch/finally around fn)

# Install general Jupyter notebook requirements.
python -m pip install --upgrade pip
python -m pip install jupyter_core nbconvert ipykernel

# Install specific requirements for this notebook.
python -m pip install tensorflow

# Run the notebook, discarding output (still fails if an exception is thrown).
jupyter nbconvert --to notebook --execute variables_and_state.ipynb \
  --stdout > /dev/null
```

We could measure the overhead of using a separate venv for each notebook's test. I like the isolation, and system-wide caching of downloads will help, but some installs can be slow :D

**Comment by ScottTodd** [comment]
I've got some scripts that test the things I want to test, and now I'm figuring out how to run them on Buildkite. I'm tempted to hook these scripts up via `iree_py_test` and `iree_run_binary_test` in CMake to be able to run them through ctest and get nice summary tables for passes/fails. However, the scripts do rather invasive things like pip installing packages (after trying to create python venvs) and running full CMake configure + build commands.

I could gate some ctest targets behind a new top level CMake option, or just keep the tests as loose scripts that aren't integrated into the build system. Thoughts?

It's also looking like I'll need to update our Docker images to include some extra dependencies.

**Comment by benvanik** [comment]
If they are run as a separate post-submit test it seems like it'd be consistent to have them as a separate manual script (which ideally would be just what the CI invokes) - especially if it's doing things like invoking cmake/bazel or may conflict with normal configurations (would want to be thrashing the cmake cache). Would also mean that we could support them on a smaller set of platforms (instead of trying to run them on windows/etc).

**Comment by ScottTodd** [comment]
Yeah, the Buildkite pipeline is basically

```yml
- label: "Test Colab notebooks"
  commands:
    - docker run ... colab/test.sh

- label: "Test Samples"
  commands:
    - docker run ... iree/samples/variables_and_state/test.sh
```

right now. I'm also only planning to test the notebooks on Linux, but the samples could be tested on other platforms.

**Comment by ScottTodd** [comment]
I rewrote my `colab/test.sh` into `colab/test_notebooks.py`, to create one "test case" per notebook with cleaner support for expected failures and skipping. Still tuning the verbosity (script commands, TF logging, pip output, etc.), but here's some sample output: https://gist.github.com/ScottTodd/a64109502ffad29ab8beb5264af6bd50

Next I need to modify the Docker image used, probably by inheriting from https://github.com/google/iree/blob/main/build_tools/docker/cmake-python-swiftshader/Dockerfile.

**Comment by ScottTodd** [comment]
Another idea: we may be able to test code (build instructions, configuration samples, etc.) that we include in our documentation in a similar way. https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#embedding-external-files may help with that.

**Comment by benvanik** [comment]
that'd be awesome - like python [doctests](https://docs.python.org/3/library/doctest.html).

**Comment by ScottTodd** [comment]
https://buildkite.com/iree/iree-samples is now set up to run our Colab notebooks and the two samples (variables and state, dynamic shapes) that use Colab and CMake commands. I have it running on a daily schedule with no alerting for now, and will add alerting and some more documentation once I've determined it to be stable.

I have thought of, but not yet starting implementing
* testing on presubmit
* triggering after each GitHub release
* testing on release candidates prior to publishing

**Comment by ScottTodd** [comment]
Going to close this since the builds have been stable. Not sure if it would be worth adding alerts to the whole team.
