### ISSUE TITLE
Improve error messages for unsupported MHLO -> Linalg lowering

### ISSUE THREAD

**Issue by hanhanW** [google/iree#6216]
Instead of marking all the mhlo ops illegal in HLOToLinalgOnTensorsPass, we should let them pass and have something like VerifyFullyConvertedPass. It will be much easier to see what ops are not get lowered to Linalg on tensors.

https://github.com/google/iree/blob/ab7ce7062c3530f9d6cc0d63041ad80ed6d935e0/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp#L236-L246

E.g., if there are TF operations not lowered to mhlo ops, we will see prettier error messages like:

```
'tf.Const' op : unlegalized TensorFlow op still exists
'tf.Add' op : unlegalized TensorFlow op still exists
```

**Comment by hanhanW** [comment]
I think we would like to generalize VerifyFullyConvertedPass and use it in the pipeline.

https://github.com/google/iree/blob/main/integrations/tensorflow/iree_tf_compiler/TF/VerifyFullyConverted.cpp

**Comment by stellaraccident** [comment]
If we don't mark them as illegal, then they won't convert. Do you mean to do a partial conversion?

There is also a verification pass at the front of the flow pipeline. Between the two of them, we could probably generalize something.

**Comment by hanhanW** [comment]
A createVerifyCompilerMHLOInputLegality was added. https://github.com/google/iree/blob/541d4c4729efd780b58bf5efd22644e58b1344aa/iree/compiler/InputConversion/MHLO/Passes.cpp#L85
