### ISSUE TITLE
`iree/runtime` library cannot support bare-metal thread-less fileIO-less configuration

### ISSUE THREAD

**Issue by hcindyl** [google/iree#6247]
`iree/runtime` library needs some clean up to support bare-metal configuration

- [x] Split up the dependency of iree/hal/driver (task executor --> thread dependency).
- [ ] Split up fileIO depenency.  

We should have a subset of APIs that can support bare-metal config and a full APIs to support more sane systems.

**Comment by benvanik** [comment]
What do you think about an iree/base/config.h define for whether to enable file IO (`IREE_FILE_IO_ENABLE`)? This could be used to disable `iree_runtime_session_append_bytecode_module_from_file` while keeping `iree_runtime_session_append_bytecode_module_from_memory` for example.

**Comment by hcindyl** [comment]
That could be helpful, thanks! However, we need to create customized CMakeLists.txt instead of the one generated from BUILD.

In addition, I am not sure we have fixed the thread dependency for `iree/hal/driver` yet. It would require https://github.com/google/iree/issues/4298 to be solved first.

**Comment by benvanik** [comment]
> we need to create customized CMakeLists.txt instead of the one generated from BUILD.
what do you mean?

**Comment by hcindyl** [comment]
I am thinking about https://github.com/google/iree/blob/331946c/iree/runtime/CMakeLists.txt#L46 and how we can add it only when `if(${IREE_ENABLE_FILE_IO})` in CMakeLists.txt.

**Comment by benvanik** [comment]
Ah - we would just make the file_io code no-op (like how we make the atomics and mutex stuff no-op) - file_io only relies on stdio, so it pulls in no deps you would otherwise not want
