### ISSUE TITLE
Unregistered dialects in iree-tf-opt

### ISSUE THREAD

**Issue by hanhanW** [google/iree#6282]
Some dialects (like TensorDialect) are not registered in `iree-tf-opt`, this will cause reproducing issue. Instead of registering them individually in each `*-main`, I think we can have a `registerIREEInputDialect()` and define the input of IREE there, like

https://github.com/google/iree/blob/f5623dda5f0724da9fc939d8570172a1dfef3f4b/iree/tools/init_mlir_dialects.h#L34-L53

Today, the expected input dialects are StandardDialect, TensorDialect, MathDialect, MemRefDialect.

**Comment by jpienaar** [comment]
What is missing from https://github.com/google/iree/blob/bba260da24d2822f61c1d6764ebff85a1f160ddf/compiler/src/iree/compiler/Tools/init_mlir_dialects.h#L45 ? E.g., for this bug to be finished what needs to be done still? (is it splitting that register function into an explicit one for input dialects?)

**Comment by hanhanW** [comment]
This is probably stale, closing the issue.
