### ISSUE TITLE
`OrdinalAllocationPass` not workig in `iree-mlir-to-vm-{c,bytecode}-module` pass

### ISSUE THREAD

**Issue by marbre** [google/iree#6307]
I recently noticed that `OrdinalAllocationPass` is not working as expected, as calling `iree/tools/iree-translate --iree-mlir-to-vm-c-module --print-ir-after-all iree/vm/test/global_ops.mlir` segfaults. However, `iree-translate --iree-vm-ir-to-c-module --print-ir-after-all iree/vm/test/global_ops.mlir` works as expected. In the following I elaborate on this by creating a bytecode module (as this doesn't require to build with `IREE_ENABLE_EMITC`).

Running `iree-translate --iree-vm-ir-to-bytecode-module --print-ir-after-all iree/vm/test/global_ops.mlir` gives
```mlir
// -----// IR Dump After mlir::iree_compiler::IREE::VM::OrdinalAllocationPass //----- //
vm.module @global_ops attributes {ordinal_counts = #vm.ordinal_counts<import_funcs = 0, export_funcs = 2, internal_funcs = 2, global_bytes = 8, global_refs = 0, rodatas = 0, rwdatas = 0>} {
  vm.global.i32 @c42 42 : i32 attributes {ordinal = 0 : i32}
```
which has correct `ordinal_counts` and an `vm.module @global_ops` at the top level.

Running `iree-translate --iree-mlir-to-vm-bytecode-module --print-ir-after-all iree/vm/test/global_ops.mlir` gives
```mlir
// -----// IR Dump After mlir::iree_compiler::IREE::VM::OrdinalAllocationPass //----- //
vm.module @module attributes {ordinal_counts = #vm.ordinal_counts<import_funcs = 0, export_funcs = 0, internal_funcs = 0, global_bytes = 0, global_refs = 0, rodatas = 0, rwdatas = 0>} {
  vm.module @global_ops {
    vm.global.i32 @c42 42 : i32
```
with all `ordinal_counts` set to 0 and an additional outer module `vm.module @module`. Having all `ordinal_counts` set to 0 is the cause for the segfault of running `iree/tools/iree-translate --iree-mlir-to-vm-c-module --print-ir-after-all iree/vm/test/global_ops.mlir` as the VM to EmitC conversion tries to accesses the ordinals:
https://github.com/google/iree/blob/11f68ec4c5bbd3b6bfdece1acdcd4e5747c4f693/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp#L629

The pattern ***only*** applied in `iree-mlir-to-vm-bytecode-module` and causing the issue somehow is
https://github.com/google/iree/blob/11f68ec4c5bbd3b6bfdece1acdcd4e5747c4f693/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp#L27

As I am not familiar with neither the `StandardToVM` pass nor with the `OrdinalAllocationPass`, thus any help is appreciated!

**Comment by benvanik** [comment]
Reproduced!

**Comment by benvanik** [comment]
This is caused by the total weirdness that is the MLIR implicit outer module:
```mlir
module  {
  module  {
    vm.module @global_ops {
```

The ModuleOpConversion is checking the mid-level module, seeing that it's not the top-level one, and converting it. I think I know where the extra module is coming from (also trying to deal with the implicit outer module when it's _not_ present) and will fix that.
