### ISSUE TITLE
Index out of bound assertion in FusionOfTensorOps for TensorExpandShapeOp

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#6310]
Error:

```
iree-translate: /usr/local/google/home/laurenzo/src/iree/third_party/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:257: const T &llvm::ArrayRef<long>::operator[](size_t) const [T = long]: Assertion `Index < Length && "Invalid index!"' failed. 
```

[log_softmax_dynamic.mlir.txt](https://github.com/google/iree/files/6711577/log_softmax_dynamic.mlir.txt)

Repro:

```
./iree/tools/iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=dylib-llvm-aot log_softmax_dynamic.mlir.txt
```

Note that this was extracted from a dynamic log_softmax with various optimization patterns and passes disabled (i.e. the optimized form compiles properly but this more generic form does not -- and should)

**Comment by MaheshRavishankar** [comment]
Should be fixed by https://reviews.llvm.org/D104970
