### ISSUE TITLE
Plumb through Cooperative matrix usage on SPIRV and CUDA backends

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#6326]
It seems like with all the current refactoring, we dont have an e2e way to start with something like 

```
func @matmul(%arg0 : tensor<4096x4096xf16>, %arg1 : tensor<4096x4096xf16>) -> tensor<4096x4096xf16> {
  %0 = "mhlo.dot"(%arg0, %arg1) : tensor<4096x4096xf16>, tensor<4096x4096xf16> -> tensor<4096x4096xf16>
  return %0 : tensor<4096x4096xf16>
}
```

and generate code with `spv.CooperativeMatrixMulAddNV` instructions (even with the right vulkan target). 

Running

```
$ iree-translate -iree-hal-target-backends=vulkan-spirv -iree-mlir-to-vm-bytecode-module -iree-vulkan-target-triple=turing-t4-linux matmul.mlir -iree-input-type=mhlo
```

gives the error

```
matmul.mlir:2:8: error: failed to legalize operation 'linalg.fill'
  %0 = "mhlo.dot"(%lhs, %rhs) :
       ^
matmul.mlir:1:1: note: called from
func @matmul(%lhs : tensor<4096x4096xf16>, %rhs : tensor<4096x4096xf16>) -> tensor<4096x4096xf16> {
^
matmul.mlir:2:8: note: see current operation: "linalg.fill"(%7, %cst) ( {
^bb0(%arg0: f16):  // no predecessors
  "linalg.yield"(%cst) : (f16) -> ()
}) {__internal_linalg_transform__ = "workgroup"} : (memref<64x64xf16, affine_map<(d0, d1)[s0] -> (d0 * 4096 + s0 + d1)>>, f16) -> ()
```

So far the lowering has only looked at using these instructions for a single matmul (starting from the HAL layer with linalg.matmul on memrefs). Unfortunately, with the tensors path, there is never going to be only a matmul in a dispatch region. There is either going to be a zero-fill of the output buffer, or a copy from the init-values buffer to the result buffer (details of why this happens omitted here cause its sort of orthogonal to the issue here). So fusion needs to be handled (at least fusion at the outs operand, which is easier)

There are tests that do make sure that starting from buffers, the pipeline can generate `spv.CooperativeMatrixMulAddNV` instructions for a single matmul, but there are no e2e tests with these (since non of the hardware we use for e2e tests have this instruction available AFAIK). So this seems to have fallen through the cracks when we moved to Linalg on tensors.

**Comment by MaheshRavishankar** [comment]
Renaming to make this bug track the plumbing on both CUDA and SPIR-V.

**Comment by MaheshRavishankar** [comment]
CUDA now uses tensor core ops, and SPIR-V support for co-operative matrix ops is removed for now.. Nothing more to track on this issue. Closing

**Comment by antiagainst** [comment]
SPIR-V support for cooperative matrix is [still](https://github.com/google/iree/blob/main/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp) [there](https://github.com/google/iree/blob/main/iree/compiler/Codegen/SPIRV/SPIRVVectorToCooperativeOps.cpp).
