### ISSUE TITLE
Polish documentation for RISC-V build instructions and configuration options

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#6327]
We should refresh our documentation for how to use IREE on RISC-V.

I'm thinking of something fitting in around these pages
* https://google.github.io/iree/building-from-source/android/
* https://google.github.io/iree/deployment-configurations/cpu-dylib/

"deploying on bare metal" could go in "deployment configurations" and "cross compiling for RISC-V" could go in the "building from source" section - or some other structure, I'm open to other ideas :D

We have this document today, which could be migrated to the new site ([source for the website](https://github.com/google/iree/tree/main/docs/website)):
https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_riscv_cmake.md

On a related note, the "simple embedding" sample ([source](https://github.com/google/iree/tree/main/iree/samples/simple_embedding)) has a a number of configurations that would be good to document with a README. See https://github.com/google/iree/tree/main/iree/samples/variables_and_state for ideas on structure and topics to cover.

**Comment by hcindyl** [comment]
Still trying to figure out how the "deploy on bare-metal" fits. It's essentially three parts
- [ ] dylib with embedded library 
- [ ] CMake and Macros set for `IREE_PLATFORM_GENERIC`, `IREE_ENABLE_THREADING`, and `IREE_SYNCHRONIZATION_DISABLE_UNSAFE`
- [ ] Machine BSP (linker script, crt0.s, stubs for `IREE_TIME_NOW_FN` and logging)

The first one should go to https://google.github.io/iree/deployment-configurations/cpu-dylib/, and the two others can be another doc.

**Comment by ScottTodd** [comment]
Here's a slide from a while ago (which I don't think we ever published :o) that shows some of the ways I think about "deployment configurations": 

![image](https://user-images.githubusercontent.com/4010439/124162478-56e63400-da53-11eb-8c9e-b8f802e55d7b.png)

My goal with that section of the website ([introduced here](https://google.github.io/iree/#selecting-deployment-configurations)) is to walk through individual slices of that chart.

1. Start from your use-case and technical constraints
    * What platform are you deploying on?
    * How dynamic do you want your model(s) to be?
    * What features do you want from the runtime?
2. Determine how you'll be using your ML frontend and the IREE compiler
    * What format is your model coming from? Does it need preprocessing or postprocessing (e.g. quantization, training/inference splitting)?
    * Which target backend should you be using?
    * What flags should you be setting?
3. Integrate the runtime and/or any language bindings into your program and load+run your model
    * What HAL driver should you be using? Does it have special requirements?
    * If your platform has constraints like no threading or file system then how do you bundle your model with your program?

The distinctions between "deployment configurations" can get fuzzy. It's good being able to reuse components for different applications, so long as we give enough guidance to users about what their choices are and which matter the most for their needs.

So for this I'd want to see something like

* Base CPU using LLVM documentation (what's in cpu-dylib now)
* Bare-metal documentation
    * using LLVM compiler target configured to generate a static library or use emitc -> how to integrate those into your application using the C API
    * RISC-V and other platforms as examples where the bare-metal or generic configuration is needed

**Comment by hcindyl** [comment]
> * Base CPU using LLVM documentation (what's in cpu-dylib now)
> * Bare-metal documentation
>   * using LLVM compiler target configured to generate a static library or use emitc -> how to integrate those into your application >   using the C API
>  * RISC-V and other platforms as examples where the bare-metal or generic configuration is needed

I don't see a TODO in the `cpu-dylib` about the embedded library option. Should we add a TODO for this? I think it's a more generic option since it can help us separating the compiler/runtime better and create a real portable artifact.

I can add how to use the embedded linker library to the bare-metal doc. Maybe we can add the static section once https://github.com/google/iree/pull/6225 is landed?
