### ISSUE TITLE
LegalizeInputTypesPass does not work for linalg.tensor_expand_shape

### ISSUE THREAD

**Issue by hanhanW** [google/iree#6399]
To repro:

```mlir
  func @foo(%arg0: tensor<9xi64>) -> tensor<1x9xi64> {
    %0 = linalg.tensor_expand_shape %arg0 [[0, 1]] : tensor<9xi64> into tensor<1x9xi64>
    return %0 : tensor<1x9xi64>
  }
```

Run: `iree-opt -iree-mhlo-legalize-input-types input.mlir`

You will see

```
br.mlir:3:3: error: type of return operand 0 ('tensor<1x9xi64>') doesn't match function result type ('tensor<1x9xi32>') in function @foo
  return %265 : tensor<1x9xi64>
```

The output from `print-ir-after-all`:

```
// -----// IR Dump After LegalizeInputTypes Failed //----- //
"module"() ( {
  "func"() ( {
  ^bb0(%arg0: tensor<9xi32>):  // no predecessors
    %0 = "linalg.tensor_expand_shape"(%arg0) {reassociation = [[0, 1]]} : (tensor<9xi32>) -> tensor<1x9xi64>
    "std.return"(%0) : (tensor<1x9xi64>) -> ()
  }) {sym_name = "while", type = (tensor<9xi32>) -> tensor<1x9xi32>} : () -> ()
  "func"() ( {
  ^bb0(%arg0: tensor<9xi64>):  // no predecessors
    %0 = "linalg.tensor_expand_shape"(%arg0) {reassociation = [[0, 1]]} : (tensor<9xi64>) -> tensor<1x9xi64>
    "std.return"(%0) : (tensor<1x9xi64>) -> ()
  }) {sym_name = "while", type = (tensor<9xi64>) -> tensor<1x9xi64>} : () -> ()
}) : () -> ()
```

**Comment by hanhanW** [comment]
It looks like some linalg ops are created in `mlir::iree_integrations::TF::ConvertToMHLOPass`, and we assume all Linalg ops only contain valid types.

https://github.com/google/iree/blob/be17032646cbb2ad48b67e2fce2e72ada9f65e75/iree/compiler/InputConversion/MHLO/LegalizeInputTypes.cpp#L79-L84

**Comment by hanhanW** [comment]
They are come from DirectLoweringPatterns.

https://github.com/google/iree/blob/be17032646cbb2ad48b67e2fce2e72ada9f65e75/integrations/tensorflow/iree_tf_compiler/TF/DirectLoweringPatterns.cpp#L43-L51

@stellaraccident I think we can't use `mhlo.reshape` because we will lose collapsing/expanding dims information? If we really want this, I think we can legalize the types for these two operations.

**Comment by stellaraccident** [comment]
If this is causing you trouble, you can disable the direct lowering
patterns in the TF pipeline. But really legalize input types needs an
overhaul.

**Comment by stellaraccident** [comment]
It is (much) better to lower them this way but not strictly required. The
real issue is that legalize input types should be much smarter or we should
be doing type conversion earlier.

**Comment by MaheshRavishankar** [comment]
This should be fixed now. Closing
