### ISSUE TITLE
Add support for saving mid level IRs in python artifacts

### ISSUE THREAD

**Issue by hanhanW** [google/iree#6412]
In the past, the result of iree-import-tf was mhlo IRs. Now they are all lowered to linalg/std/tensor ops. It's would be very nice if we can save mhlo IRs to the artifact dir. It's easier to debug and spot missing support if the issue happens at MHLO level.

**Comment by stellaraccident** [comment]
We already save a couple of temp files here. Easy enough to add another
flag:
https://github.com/google/iree/blob/5fea3963b934d2907c2eead3f637097d3f0ad8e1/integrations/tensorflow/iree_tf_compiler/iree-import-tf-main.cpp#L227

You could just split the main tf pipeline here:
https://github.com/google/iree/blob/5fea3963b934d2907c2eead3f637097d3f0ad8e1/integrations/tensorflow/iree_tf_compiler/TF/Passes.cpp#L108
and do the MHLO lowering in the main() function, saving a temp fine in
between.

Note that it is not pure MHLO: some things are lowered directly from tf and
we will be lowering some things to tosa in the near future. But there will
likely always be this "mid level ir" split and dumping it as a temp file
there makes sense to me. Maybe call it -save-temp-mid-level ?

They can be plumbed through the python API by following the example of one
of the other save-temp flags:
https://github.com/google/iree/blob/5fea3963b934d2907c2eead3f637097d3f0ad8e1/bindings/python/iree/compiler/tf.py#L152

Looks like we aren't testing those:
https://github.com/google/iree/blob/5fea3963b934d2907c2eead3f637097d3f0ad8e1/bindings/python/tests/compiler_tf_test.py#L46

But could be with a test like this:
https://github.com/google/iree/blob/5fea3963b934d2907c2eead3f637097d3f0ad8e1/bindings/python/tests/compiler_core_test.py#L175

**Comment by stellaraccident** [comment]
Also, sorry I hadn't thought of adding this. I use -print-ir-after on
iree-import-tf pretty extensively but it sounds like you have another flow,
which is fine.

**Comment by hanhanW** [comment]
Thanks for the detailed pointers and explanations! I will add the feature.

Yes, I also use `-print-ir-after` with `iree-import-tf`. However, I found that it is not convenience to get the mid level IR through python test target. I can run `iree-import-tf` with the saved model artifacts (i.e. the pb file) to get the IR. After doing it couple times, I think it's better to dump the mid level IR to the artifacts as well.
