### ISSUE TITLE
Consider checking if git submodules have been initialized

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#6434]
We use git submodules that require `git submodule update --init` for successful builds. A number of users have encountered issues after checking out the project or changing to a commit that includes new submodules. One idea is to warn about uninitialized submodules in CMake. Dirty submodules (submodules with local changes) are fine and not worth warning about, but empty submodules (uninitialized) are not.

There is a suggestion at https://cmake.org/pipermail/cmake/2012-May/050190.html:

```cmake
if( NOT EXISTS "${MY_SOURCE_DIR}/project/.git" )
message( SEND_ERROR "The git submodules are not available. Please run
git submodule update --init --recursive"
)
endif()
```

We could do something similar, iterating over all submodules we expect to be initialized and recommending `git submodule update --init` (no `--recursive`).

**Comment by niloysikdar** [comment]
Hello @ScottTodd , can you please explain a little more about this issue like which particular thing we need to change?

**Comment by ScottTodd** [comment]
Sure!

We have a number of dependencies in IREE that are included via git submodules ([docs](https://git-scm.com/docs/git-submodule)). These are all enumerated in [.gitmodules](https://github.com/google/iree/blob/main/.gitmodules) and are located in [third_party/](https://github.com/google/iree/tree/main/third_party). A `git clone` or `git checkout` won't "initialize" those submodules, so they'll be empty directories.

If someone tries to build without a submodule initialized, they'll get an error like this one:

```
CMake Error at build_tools/cmake/external_cc_library.cmake:108 (add_library):
  Cannot find source file:

    .../iree/third_party/libyaml/src/api.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  build_tools/third_party/libyaml/CMakeLists.txt:9 (external_cc_library)


CMake Error at build_tools/cmake/external_cc_library.cmake:108 (add_library):
  No SOURCES given to target: yaml_yaml
Call Stack (most recent call first):
  build_tools/third_party/libyaml/CMakeLists.txt:9 (external_cc_library)
```

that error message sort of explains what happened (a file is missing), but we could provide a more obvious message in the case that a submodule is not initialized at all, like

```
git submodule "third_party/libyaml" is not initialized, run "git submodule update --init"
```

To check for uninitialized submodules and print such an error message, we would put some CMake code around here: https://github.com/google/iree/blob/790ed1ad9b8486258b112979ac2c83ef33708f85/CMakeLists.txt#L263-L265

maybe referencing a helper function defined in [build_tools/cmake/iree_macros.cmake](https://github.com/google/iree/blob/main/build_tools/cmake/iree_macros.cmake) (to keep the root CMakeLists.txt less complicated).

That code would go through directories in `third_party/` checking for uninitialized submodules in some way (e.g. checking for empty directories, checking for paths from `.gitmodules` that don't yet have a `.git` file, or running some command(s) from https://git-scm.com/docs/git-submodule). If an uninitialized submodule is found, that code would print a fatal error message. If all submodules are initialized, the code should not print anything.

**Comment by niloysikdar** [comment]
Thanks a lot @ScottTodd for the detailed explanation. I will surely research more on this and if possible I will try to make a pr for fixing this.

**Comment by stellaraccident** [comment]
Can you just use `git submodule status` for this:

```
       status [--cached] [--recursive] [--] [<path>...]
           Show the status of the submodules. This will print the SHA-1 of the currently checked out commit for each
           submodule, along with the submodule path and the output of git describe for the SHA-1. Each SHA-1 will
           possibly be prefixed with - if the submodule is not initialized, + if the currently checked out submodule
           commit does not match the SHA-1 found in the index of the containing repository and U if the submodule has
           merge conflicts.
```

(check for a '-' prefix)

It'd be nice if this were a script in `build_tools` that CMake invoked (i.e. `check_submodule_status.py`). Then that script could output some useful help and a failing status code on submodule mismatch. (i.e. just trying to keep open coded CMake macros to a minimum)

**Comment by stellaraccident** [comment]
This should also no-op if the root of the project is not a git repository (i.e. does not have a `.git` directory is probably enough). This way, source tarballs and other exotic ways to stitch repositories will not trigger this.

**Comment by ScottTodd** [comment]
> Can you just use `git submodule status` for this:
> 
> ```
>        status [--cached] [--recursive] [--] [<path>...]
>            Show the status of the submodules. This will print the SHA-1 of the currently checked out commit for each
>            submodule, along with the submodule path and the output of git describe for the SHA-1. Each SHA-1 will
>            possibly be prefixed with - if the submodule is not initialized, + if the currently checked out submodule
>            commit does not match the SHA-1 found in the index of the containing repository and U if the submodule has
>            merge conflicts.
> ```
> 
> (check for a '-' prefix)
> 
> It'd be nice if this were a script in `build_tools` that CMake invoked (i.e. `check_submodule_status.py`). Then that script could output some useful help and a failing status code on submodule mismatch. (i.e. just trying to keep open coded CMake macros to a minimum)

We have a similar script already: https://github.com/google/iree/blob/main/scripts/git/submodule_versions.py. As written now, `python3 ./scripts/git/submodule_versions.py check` does not error for uninitialized submodules though. Also, that script checks our [SUBMODULE_VERSIONS.txt](https://github.com/google/iree/blob/main/SUBMODULE_VERSIONS.txt) file to ensure there are no _changes_ in submodules (either commits or diffs), when for this we want to allow that, but warn on _empty_ (uninitialized) submodules.

`git submodule status` does work for this, yes :D. In particular, the `-` prefix before any line of output is what we want to look for and error on.

For example, here is the output with a fresh checkout and uninitialized submodules:
```
λ git submodule status
-39c8d58a76ce7c3398786ee96a452668e8392af7 third_party/benchmark
-5916273f79a21551890fd3d56fc5375a78d1598d third_party/cpuinfo
-32aabef14ccc0e3ac15602c99476d25dcd230d19 third_party/flatcc
-aa533abfd4232b01f9e57041d70114d5a77e6de0 third_party/googletest
-88b845dee001723c4a0db1fe5477de735b6d3bb0 third_party/liburing
-acd6f6f014c25e46363e718381e0b35205df2d83 third_party/libyaml
-d046fb62b7e7cd273b104fee0162725003411c00 third_party/llvm-project
-5a6c67a5c32199e240cd8e5f8ad38b0821371031 third_party/mlir-hlo
-4c7697dbe973ed01ae6fbec37d186ebd05982e1f third_party/pybind11
-2e1b5fb39ebc2ef4cb77005f8267e4f3a6241ba1 third_party/spirv_cross
-f5417a4b6633c3217c9a1bc2f0c70b1454975ba7 third_party/spirv_headers
-b42009b3b9d4ca35bc703f5310eedc74f584be58 third_party/stblib
-0e956f76c739425e45a3e1d15e0d84d782011d86 third_party/tensorflow
-50f7deb1a389bd3785c12fbe0be74128343f11f7 third_party/tracy
-9d10a96f2d57c3c37e167f2e73c9a31ac2e51fa5 third_party/vulkan_headers
-8d4a9e9174a9c6ad6a3a3ae981b915ef13fc12c4 third_party/vulkan_memory_allocator
```

and here is output with initialized submodules (including some with changes):
```
λ git submodule status
 39c8d58a76ce7c3398786ee96a452668e8392af7 third_party/benchmark (v1.5.1-10-g39c8d58)
 5916273f79a21551890fd3d56fc5375a78d1598d third_party/cpuinfo (remotes/origin/HEAD)
 32aabef14ccc0e3ac15602c99476d25dcd230d19 third_party/flatcc (v0.6.0-160-g32aabef)
 aa533abfd4232b01f9e57041d70114d5a77e6de0 third_party/googletest (release-1.8.0-2728-gaa533abf)
 88b845dee001723c4a0db1fe5477de735b6d3bb0 third_party/liburing (liburing-0.7-189-g88b845d)
 acd6f6f014c25e46363e718381e0b35205df2d83 third_party/libyaml (0.2.5-1-gacd6f6f)
+d046fb62b7e7cd273b104fee0162725003411c00 third_party/llvm-project (llvmorg-13-init-15579-gd046fb62b7e7)
+5a6c67a5c32199e240cd8e5f8ad38b0821371031 third_party/mlir-hlo (remotes/origin/HEAD)
 4c7697dbe973ed01ae6fbec37d186ebd05982e1f third_party/pybind11 (v2.6.2-50-g4c7697d)
 2e1b5fb39ebc2ef4cb77005f8267e4f3a6241ba1 third_party/spirv_cross (2021-01-15-152-g2e1b5fb3)
 f5417a4b6633c3217c9a1bc2f0c70b1454975ba7 third_party/spirv_headers (1.5.4.raytracing.fixed-69-gf5417a4)
 b42009b3b9d4ca35bc703f5310eedc74f584be58 third_party/stblib (b42009b)
+0e956f76c739425e45a3e1d15e0d84d782011d86 third_party/tensorflow (v1.12.1-57065-g0e956f76c73)
 f03b677ffa0fd96fcf859c32e79b740fac7dd59e third_party/tracy (v0.7.7-114-gf03b677f)
 9d10a96f2d57c3c37e167f2e73c9a31ac2e51fa5 third_party/vulkan_headers (v1.2.181)
 8d4a9e9174a9c6ad6a3a3ae981b915ef13fc12c4 third_party/vulkan_memory_allocator (v2.1.0-460-g8d4a9e9)
```

**Comment by niloysikdar** [comment]
Hey @ScottTodd , sorry for the delay, I have made a simple python script that will iterate over our all submodules and will check the status of the submodules. If all of the submodules are initialized and updated then it will print nothing, if we find that minimum one of the submodules hasn't been initialized and updated, then it will simply print a warning message about updating our submodules. Please guide me where I can use this script.

**Comment by ScottTodd** [comment]
I think some CMake after this block would be a good place run the script: https://github.com/google/iree/blob/790ed1ad9b8486258b112979ac2c83ef33708f85/CMakeLists.txt#L313-L322

Looks like https://cmake.org/cmake/help/latest/command/execute_process.html could be used to run the script and check the result (see https://stackoverflow.com/a/52077145, for example). Note that the script shouldn't be run if `python` is not installed.

**Comment by niloysikdar** [comment]
@ScottTodd I was thinking of adding a similar script to this directory https://github.com/google/iree/tree/main/scripts/git . Not getting the point of how to add that python script into this CMakeLists.txt file. Can you help me a little ? I am really excited and looking forward to fix this bug.

**Comment by ScottTodd** [comment]
CMake use is generally split into a _configure_ step and a _build_ step. We want to check for uninitialized submodules at configure time, before developers try to build.

Some CMake like this around that location would let you run your script and check its result:

```cmake
#-------------------------------------------------------------------------------
# Check if git submodules have been initialized
#-------------------------------------------------------------------------------

execute_process(
    COMMAND false # (your command would go here)
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    RESULT_VARIABLE ret
)
if(NOT ret EQUAL "0")
  message(FATAL_ERROR "Command failed: ${ret}")
else()
  message(STATUS "Success")
endif()
```

We have instructions on building IREE here: https://google.github.io/iree/building-from-source/getting-started/#clone-and-build (see also [general documentation here](https://cmake.org/runningcmake/)), and the `cmake -B ../iree-build/ -DCMAKE_BUILD_TYPE=RelWithDebInfo .` configure command is where that code would run and pass/fail, with output like

```
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" --no-warn-unused-cli -DIREE_TARGET_BACKENDS_TO_BUILD=all -DIREE_HAL_DRIVERS_TO_BUILD=all -DIREE_BUILD_TESTS=ON -DIREE_BUILD_COMPILER=ON -DIREE_ENABLE_MLIR=ON -DIREE_BUILD_PYTHON_BINDINGS=OFF -DIREE_BUILD_SAMPLES=ON -DIREE_ENABLE_RUNTIME_TRACING=ON -DCMAKE_TOOLCHAIN_FILE=D:/dev/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=d:/dev/projects/iree/../iree-build/install -Wno-dev -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -Hd:/dev/projects/iree -Bd:/dev/projects/iree-build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Building HAL drivers: Cuda;DyLib;VMVX;Vulkan
[cmake] -- Building target backends: CUDA;DYLIB-LLVM-AOT;WASM-LLVM-AOT;Metal-SPIRV;ROCM;Vulkan-SPIRV;VMVX
[cmake] -- Found Python3: C:/Python38/python.exe (found version "3.8.2") found components: Interpreter 
[cmake] CMake Error at CMakeLists.txt:334 (message):
[cmake]   Command failed: 1
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "D:/dev/projects/iree-build/CMakeFiles/CMakeOutput.log".
[cmake] See also "D:/dev/projects/iree-build/CMakeFiles/CMakeError.log".
```

**Comment by niloysikdar** [comment]
Thanks a lot @ScottTodd , I am trying to fix this asap.

**Comment by niloysikdar** [comment]
Hey @ScottTodd, I wrote this python script which will warn us about the uninitialized submodules if we run this. But I am really unable to figure out how we can execute this with CMake.
```python
import os

output = os.popen("git submodule status")
submodules = output.readlines()

for submodule in submodules:
    if (submodule.strip()[0] == "-"):
        print("The git submodules are not available. Please run git submodule update --init")
        break
```

**Comment by ScottTodd** [comment]
Here's one way to integrate that script into CMake: https://github.com/ScottTodd/iree/commit/5c0d7f484127d19b6b0b622728fab3c8fd08d995

Running this, I'm noticing that `git submodule status` takes 2-3 seconds on my machine, which is a bit steep to add to every CMake configure command.

**Comment by niloysikdar** [comment]
Thanks @ScottTodd for helping me with figuring out how to run that script with CMake. Should I make the pr?

**Comment by ScottTodd** [comment]
Sure. Note that there are two TODOs on that commit that should be resolved before merging:
* don't run the script if it isn't running in a git repository
* skip the CMake `execute_process` if `python3` is not available on the system

**Comment by niloysikdar** [comment]
Sure @ScottTodd I will make the required changes.

**Comment by niloysikdar** [comment]
@ScottTodd, I have made [this pr](https://github.com/google/iree/pull/6568), but some checks are failing. Do I need to make changes to the code?

**Comment by ScottTodd** [comment]
> @ScottTodd, I have made [this pr](https://github.com/google/iree/pull/6568), but some checks are failing. Do I need to make changes to the code?

Yep, that's checking for formatting using https://github.com/google/yapf. The logs at  https://github.com/google/iree/pull/6568/checks?check_run_id=3178347239 also show what changes should be made.

**Comment by Caellian** [comment]
For future reference, if you're using CMake, it has [`ExternalProject`](https://cmake.org/cmake/help/latest/module/ExternalProject.html) module which handles submodules so that might be a preferred solution that integrates better with the build system than running shell commands and scripts.
