### ISSUE TITLE
Run IREE's E2E TensorFlow and the flagfile --function_input is empty

### ISSUE THREAD

**Issue by rednoah91** [google/iree#6441]
I'm base on ae1889b520a251fea3d63b8a2f1885b244a603bf

Follow the instructions in https://github.com/google/iree/blob/main/docs/developers/developing_iree/e2e_benchmarking.md

Build the python binding and TF compiler successfully

Execute `matrix_ops_static_test.py` successfully
```
python ../iree/integrations/tensorflow/e2e/matrix_ops_static_test.py --target_backends=iree_vmvx
```

The --function_input in flagfile `/tmp/iree/modules/MatrixOpsStaticModule/iree_vmvx/traces/basic_matmul/flagfile` is EMPTY:
```
--module_file=/tmp/iree/modules/MatrixOpsStaticModule/iree_vmvx/compiled.vmfb
--driver=vmvx
--entry_function=basic_matmul
--function_input=
```
Does anyone has the same problem? Could you take a look at this? Thanks.

**Comment by stellaraccident** [comment]
Please assign to someone in the office :)

**Comment by rednoah91** [comment]
@stellaraccident Could you help check this : ) ?

**Comment by stellaraccident** [comment]
It looks like our documentation is out of date. We can update that. I'm the
mean time, the mechanism for capturing a trace has changed. It is
documented here:
https://github.com/google/iree/blob/main/bindings/python/iree/runtime/README.md

(You set an environment variable before running the python script)

The results of that can be run with the tool `iree-run-benchmark`. One of
us needs to scrub that document and bring it up to current. Apologies.

**Comment by stellaraccident** [comment]
Sorry - the tool name to use is iree-benchmark-trace (on mobile and making
typos)

**Comment by rednoah91** [comment]
Thanks @stellaraccident.
The instructions you provide works at `MatrixOpsStaticModule` and `MobileNetV3Small`, but for `MobileBertSquad` I encountered the following error:
```
export IREE_SAVE_CALLS=/home/hongrongh/iree-ToT/iree-build-host/temp_mobileBERT
python ./integrations/tensorflow/e2e/mobile_bert_squad_test.py --target_backends=iree_llvmaot
../iree-build-host/iree/tools/iree-run-trace  --driver=dylib ../iree-build-host/temp_mobileBERT/calls__1.yaml
--- CALL[module.serving_default] ---
/home/hongrongh/iree-ToT/iree/iree/tools/utils/trace_replay.c:292: INVALID_ARGUMENT; (16): expected sequence node for type; replaying trace file '../iree-build-host/temp_mobileBERT/calls__1.yaml'
```
Did I miss something?

**Comment by stellaraccident** [comment]
It is likely something unimplemented. The BERT tests use a couple of
advanced features which were likely missed in the iree-benchmark-trace
tool. Very likely an easy fix but will need a patch.

**Comment by rednoah91** [comment]
Thanks @stellaraccident , could you notify me once the patch is committed?

**Comment by stellaraccident** [comment]
Just coming back from a camping trip today and will put this on the top of
the queue.
