### ISSUE TITLE
How to setup IREE module cross-compiling for Graviton (aarch64)

### ISSUE THREAD

**Issue by cioc-shoreline** [google/iree#6463]
**Describe the bug**
We would like to use IREE to cross compile from x86_64 to arm64, specifically on x86_64 servers for graviton servers (https://aws.amazon.com/ec2/graviton/). We have considered the tutorials for cross compiling for android and for risc (https://google.github.io/iree/building-from-source/android/ and https://google.github.io/iree/building-from-source/riscv/). However, it was hard to translate the structure of these to a new target.

**To Reproduce**

We are using the python bindings and our models are built in JAX. We use the aot call. We have had success with target_backend=vmvx and adding extra_args = ["-iree-llvm-target-triple=aarch64-pc-linux-elf"]. Ideally, we could cross compile for arm using target_backend=dylib-llvm-aot (like in the risc tutorial). 

When we use target_backend=dylib-llvm-aot and extra_args = ["-iree-llvm-target-triple=aarch64-pc-linux-elf"] we get the following output

```
iree.compiler.tools.CompilerToolError: Error invoking IREE compiler tool iree-translate
Diagnostics:
/usr/bin/ld: /tmp/main_dispatch_0-85405c.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/main_dispatch_0-85405c.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/main_dispatch_0-85405c.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/main_dispatch_0-85405c.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/main_dispatch_0-85405c.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/main_dispatch_0-85405c.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/main_dispatch_0-85405c.o: error adding symbols: file in wrong format
Linking failed; escaped command line returned exit code 256:

/usr/bin/ld -o /tmp/main_dispatch_0-85405c.so -nostdlib -shared -undefined suppress /tmp/main_dispatch_0-85405c.o

<unknown>:0: error: failed to link executable and generate target dylib using linker toolchain /usr/bin/ld
<unknown>:0: error: failed to serialize op to target backend dylib*
<unknown>:0: error: conversion from source -> vm failed


Invoked with:
  /home/charles/.local/lib/python3.8/site-packages/iree/tools/core/iree-translate - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib-llvm-aot --iree-mlir-to-vm-bytecode-module --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvm-target-triple=aarch64-pc-linux-elf
```

**Comment by benvanik** [comment]
That is using your system linker (/usr/bin/ld) - if you are cross-compiling you'll need to specify what linker you want to use via environment variables. Setting `IREE_LLVMAOT_LINKER_PATH` to your crosstool linker (ld/lld/etc) may work. This path is fraught with complexity when cross-compiling (as any cross-compiling is), but should be workable.

Alternatively you can use the embedded ELF target which will not require any extra cross-compilation support (it'll target anything the IREE-built lld can target from any host) - you get that by adding `-iree-llvm-link-embedded=true` to your iree-translate flags. See for example https://github.com/google/iree/blob/651aa77717362b5570388d83ee370f4520b43ffd/iree/samples/simple_embedding/CMakeLists.txt#L148 that we use to build modules that should just work for you. When first bringing up your platform I'd recommend getting that simple_embedding demo running before you attempt your own models/tooling to help isolate the issues.

(there are still some issues with the -iree-llvm-link-embedded path that need to be worked through, so until #4717 is fixed you may have to use the more complicated approach - it's worth giving a shot to the embedded one though; you'll know quickly if it doesn't work and it's easy to try with just adding that one flag vs. trying to mess with linkers and crosstools)

**Comment by sergiuiacob1** [comment]
Hello! We're having some issues running a JAX model on a Graviton instance (aarch64) built on an x86_64 machine which had `lld` installed.
We built the model by providing these arguments 
```
target_backends = ["dylib-llvm-aot"]
extra_args = ["--iree-llvm-target-triple=aarch64-pc-linux-elf", "--iree-llvm-link-embedded=true"]
```
to the JAX frontend. We're getting this error when loading the model on the aarch64 machine:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 9, in load_iree_binary
  File "/usr/local/lib/python3.7/site-packages/iree/runtime/system_api.py", line 310, in add_vm_module
    self.add_vm_modules((vm_module,))
  File "/usr/local/lib/python3.7/site-packages/iree/runtime/system_api.py", line 307, in add_vm_modules
    self._vm_context.register_modules(vm_modules)
RuntimeError: Error registering modules: /agent/iree/iree/vm/native_module.c:232: NOT_FOUND; no function hal.device.match.id exported by module
```

We've build IREE from source like this (source code was in `/agent/iree`) on an ARM machine:
```
cd /agent/iree-arm && \
    cmake -G Ninja /agent/iree \
      -B aarch64-py \
      -DIREE_BUILD_EXPERIMENTAL=ON \
      -DIREE_ENABLE_LLD=ON \
      -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
      -DCMAKE_C_COMPILER=/agent/iree-arm/clang+llvm-10.0.0-aarch64-linux-gnu/bin/clang \
      -DCMAKE_CXX_COMPILER=/agent/iree-arm/clang+llvm-10.0.0-aarch64-linux-gnu/bin/clang++ \
      -DIREE_BUILD_PYTHON_BINDINGS=ON \
      -DPython3_EXECUTABLE="/usr/local/bin/python3.7" \
      -DPython3_INCLUDE_DIR=/usr/local/include/python3.7m  \
      -DPython3_LIBRARY=/usr/local/lib/python3.7/config-3.7m-aarch64-linux-gnu/libpython3.7m.a
```

```
cd /agent/iree-arm && \
    cmake --build ./aarch64-py --target install 
```

Any ideas what the issue is here? We also tried using `vmvx` instead of `dylib` but we got the same error.

Also, a weird thing is that running `file <model>` when the target backend was vmvx yielded
```
model.vmfb: data
```
but when the target backend was `dylib-llvm-aot`, the result was
```
model.vmfb: TIM image, Pixel at (0,0) Size=58350x65533, (0,0)
```
I don't understand why the `file` command would say the model is an image.

@benvanik any ideas? Thanks!

**Comment by benvanik** [comment]
You're out of date on one side or the other - you'll need to pull a new release of the python stuff as well as an up-to-date runtime. We've got some work to do before we are binary stable and you shouldn't let either side drift far: https://github.com/google/iree/projects/32

`file` is just guessing by looking at bytes - it'll display whatever it thinks the file is based on the contents, and if you change the contents it'll guess something different. Those files are flatbuffers and I doubt file supports them :)

**Comment by sergiuiacob1** [comment]
> You're out of date on one side or the other - you'll need to pull a new release of the python stuff as well as an up-to-date runtime. We've got some work to do before we are binary stable and you shouldn't let either side drift far: https://github.com/google/iree/projects/32
> 
> `file` is just guessing by looking at bytes - it'll display whatever it thinks the file is based on the contents, and if you change the contents it'll guess something different. Those files are flatbuffers and I doubt file supports them :)

I used this version on both sides:
https://github.com/google/iree/releases/tag/snapshot-20210713.397
Do you know if the latest pre-release would work?

**Comment by ScottTodd** [comment]
Was this fully resolved, or were there still issues/questions?

**Comment by sergiuiacob1** [comment]
> Was this fully resolved, or were there still issues/questions?

We got it working by upgrading the IREE version. Thanks!
