### ISSUE TITLE
Build failure on main: undefined reference to pthread_mutex_trylock

### ISSUE THREAD

**Issue by Cypher1** [google/iree#6466]
**Describe the bug**
New build fails with <home dir>/iree/iree/base/internal/synchronization.c:253: undefined reference to `pthread_mutex_trylock'

**To Reproduce**
1. cd
2. git clone https://github.com/google/iree.git 
3. cd iree
4. cmake -B ../iree-build/ -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja .
5. cmake --build ../iree-build/
6. Observe error

**Additional context**
I'm aware the problem might be caused by a misconfiguration/use of ninja, so I also attempted
1. rm -rf ../iree-build
2. cmake -B ../iree-build/ -DCMAKE_BUILD_TYPE=RelWithDebInfo .
3. cmake --build ../iree-build/
4. Observe error

But the error persisted.

Longer form of the error message:
```
[4239/4284] Linking C executable iree/sampl...simple_embedding/simple_embedding_vmvx_sync
FAILED: iree/samples/simple_embedding/simple_embedding_vmvx_sync 
: && /usr/bin/cc -O2 -g -DNDEBUG -lm -lpthread iree/samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/device_vmvx_sync.c.o iree/samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/simple_embedding.c.o -o iree/samples/simple_embedding/simple_embedding_vmvx_sync  iree/samples/simple_embedding/libiree_samples_simple_embedding_simple_embedding_test_bytecode_module_vmvx_c.a  iree/base/libiree_base_base.a  iree/hal/libiree_hal_hal.a  iree/hal/local/libiree_hal_local_local.a  iree/hal/local/loaders/libiree_hal_local_loaders_vmvx_module_loader.a  iree/hal/local/libiree_hal_local_sync_driver.a  iree/modules/hal/libiree_modules_hal_hal.a  iree/vm/libiree_vm_bytecode_module.a  build_tools/third_party/flatcc/libflatcc_runtime.a  -lm  -lpthread  iree/modules/vmvx/libiree_modules_vmvx_vmvx.a  iree/hal/local/libiree_hal_local_local.a  iree/base/internal/libiree_base_internal_arena.a  iree/base/internal/libiree_base_internal_atomic_slist.a  iree/hal/libiree_hal_hal.a  iree/base/internal/libiree_base_internal_synchronization.a  iree/vm/libiree_vm_impl.a  iree/base/libiree_base_base.a && :
/usr/bin/ld: iree/base/internal/libiree_base_internal_synchronization.a(synchronization.c.o): in function `iree_mutex_try_lock':
/usr/local/google/home/jopra/iree/iree/base/internal/synchronization.c:253: undefined reference to `pthread_mutex_trylock'
collect2: error: ld returned 1 exit status
[4252/4284] Generating simple_embedding_test_bytecode_module_dylib_x86_64.vmfb
ninja: build stopped: subcommand failed.
```

**Comment by benvanik** [comment]
What platform are you building on that does not have pthread_mutex_trylock? it's been in the POSIX pthreads spec since at least 2004.

**Comment by ScottTodd** [comment]
It looks like you might be using gcc (system default usually)? You may have more success using clang:
```
sudo apt install cmake clang
export CC=clang
export CXX=clang++
```

Could check `/usr/bin/cc --version` also.

**Comment by GMNGeoffrey** [comment]
Yeah I'm confused since we can see the linker command has `-lpthread` in there (my first assumption was that the dep hadn't been declared correctly)

**Comment by GMNGeoffrey** [comment]
It could be a command ordering issue though? That would be https://github.com/google/iree/issues/5702. I thought we had fixed that with https://github.com/google/iree/pull/6253, but it looks like that was just for ldl

**Comment by stellaraccident** [comment]
Remember: link libraries are order dependent. I think there is a missing
-lpthread on one of the base synchronization libraries.

**Comment by benvanik** [comment]
ahh:
https://stackoverflow.com/questions/2009625/undefined-reference-to-pthread-mutex-trylock
it does mention in there sometimes a pthread option needs to be passed during compilation as well due to stubs. 

We currently add -lpthread just to linkopts:
https://github.com/google/iree/blob/75d4bb8b1cf4402d522f4152d6c26c77a2e0e90f/build_tools/cmake/iree_copts.cmake#L279

I thought we had a PR that changed this to using the cmake [FindThreads](https://cmake.org/cmake/help/latest/module/FindThreads.html) which probably would handle it for us.

**Comment by stellaraccident** [comment]
This one should have a dep on pthread: /usr/bin/ld:
iree/base/internal/libiree_base_internal_synchronization.
a(synchronization.c.o)

**Comment by benvanik** [comment]
all libraries link with -lpthreads (it's added to IREE_DEFAULT_LINKOPTS) - the issue is that they aren't compiling with it

**Comment by stellaraccident** [comment]
Repeating myself from previous issues: -lpthread is not a link option but a
lib. Link opts get added before the library. Link libs get added after,
allowing them to resolve the undefined symbols properly.

This gets done wrong frequently and due to the ways that command lines get
constructed, can appear to be working but it's actually unstable

**Comment by stellaraccident** [comment]
But you may be right that depending on cmake's Threads::Threads in the base
synchronization library should be the most robust way to go.

**Comment by ScottTodd** [comment]
> I thought we had a PR that changed this to using the cmake [FindThreads](https://cmake.org/cmake/help/latest/module/FindThreads.html) which probably would handle it for us.

Here is that PR, which had some unresolved issues: https://github.com/google/iree/pull/6258

**Comment by Cypher1** [comment]
Building with clang fixed it (I can now build with ninja quite quickly). Thank you!

**Comment by GMNGeoffrey** [comment]
Glad you found something that worked :-) I'm going to leave this closed, but only because I think it's a dupe of #5702. This is definitely something we should fix.
