### ISSUE TITLE
Improve mhlo.fft performance

### ISSUE THREAD

**Issue by hanhanW** [google/iree#6477]
We lower a mhlo.fft to matmul (ie DFT implementation), which is much slower than FFT. We should prototype on FFT implementation, and think how to integrate it into Linalg stuff (like tiling, fusion, etc). This could be another example that we need to tile along reduction loops and think how to merge the results.

**Comment by MaheshRavishankar** [comment]
I dont think there is any more work planned on this. Lets close this for now?

**Comment by hanhanW** [comment]
Yes, there are no more work on this. I think we are at good place now.
