### ISSUE TITLE
RETURN_IF_ERROR not appending message in OSS

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#648]
We use the insertion operator on RETURN_IF_ERROR to add messages to error status error returns. This does not appear to work in OSS, where the messages are lost

**Comment by ScottTodd** [comment]
Status payloads, stack traces, and messages are not fully implemented yet in the OSS version (see https://github.com/google/iree/blob/master/iree/base/internal/status.cc). There was a decent amount of code to fork / rewrite as part of supporting them, so I opted to skip them with the initial implementation.
