### ISSUE TITLE
failed to legalize operation 'mhlo.convolution' that was explicitly marked illegal

### ISSUE THREAD

**Issue by ArunaKote** [google/iree#6504]
When I try to run iree-build/iree/tools/iree-opt --iree-mhlo-to-linalg-on-tensors file.mlir on iree-main/iree/test/e2e/models/edge_detection.mlir I am getting error as  error: failed to legalize operation 'mhlo.convolution' that was explicitly marked illegal.

But  when I run func @linalg.conv_1d_input_nwc_filter_wcf(%arg0: tensor<?x8x?xf32>, %arg1: tensor<2x?x?xf32>)
  -> tensor<?x7x?xf32> {
  %0 = "mhlo.convolution"(%arg0, %arg1) {
    batch_group_count = 1 : i64,
    dimension_numbers = {
      input_batch_dimension = 0 : i64,
      input_feature_dimension = 2 : i64,
      input_spatial_dimensions = dense<[1]> : tensor<1xi64>,
      kernel_input_feature_dimension = 1 : i64,
      kernel_output_feature_dimension = 2 : i64,
      kernel_spatial_dimensions = dense<[0]> : tensor<1xi64>,
      output_batch_dimension = 0 : i64,
      output_feature_dimension = 2 : i64,
      output_spatial_dimensions = dense<[1]> : tensor<1xi64>
    },
    feature_group_count = 1 : i64,
    padding = dense<[[0], [0]]> : tensor<2x1xi64>,
    rhs_dilation = dense<1> : tensor<1xi64>,
    window_strides = dense<1> : tensor<1xi64>
  } : (tensor<?x8x?xf32>, tensor<2x?x?xf32>) -> tensor<?x7x?xf32>
  return %0 : tensor<?x7x?xf32>
}

I able to run without any error . 

The inputs in iree-main/iree/test/e2e/models/edge_detection.mlir are static . Is --iree-mhlo-to-linalg-on-tensors pass only supports dynamic shaped inputs?

**Comment by hanhanW** [comment]
There are some passes before `iree-mhlo-to-linalg-on-tensors`. E.g., we run `iree-mhlo-to-mhlo-preprocessing` to adjust the input as expected. Then lower mhlo ops to Linalg ops.

This would work: `iree-opt -iree-mhlo-to-mhlo-preprocessing -iree-mhlo-to-linalg-on-tensors iree/test/e2e/models/edge_detection.mlir`

The test is compiled with `iree-run-mlir`, you can also use `iree-translate` to compile it into a module and see the IR after all the passes.

E.g., `iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=dylib-llvm-aot --iree-input-type=mhlo input_mlir.mlir`

**Comment by hanhanW** [comment]
Adding `-mlir-disable-threading -print-ir-after-all` can see all the IRs after each pass. Other useful flags can be found at https://mlir.llvm.org/getting_started/Debugging/

**Comment by benvanik** [comment]
Yep; in general iree-opt is only useful for running individual passes or subsets of passes from the whole pipeline and should only be used in testing. Use iree-translate to translate from one form of IR to another (input to something IREE can run, etc).

Out of curiosity: we've had a few questions like this where people are trying to use iree-opt directly; was there documentation that you found indicating this should work that we could fix? Ideally we shouldn't be routing anyone to iree-opt unless they are developers maintaining code under iree/compiler/.

**Comment by ArunaKote** [comment]
Thank You.It was not from any documentation. I used iree-opt to run individual passes from pipeline. when I use iree-opt like that  I was beginner to iree. .Now I got to know about pass pipeline in iree.
