### ISSUE TITLE
Make lab phones to provide stable benchmarking numbers

### ISSUE THREAD

**Issue by antiagainst** [google/iree#6521]
Right now benchmarking results fluctuate, especially for multi-threaded CPU and GPU. This renders the benchmarking results less inductive and requires us to always sanity check to make sure. 

The phones in the lab contributes to the issue: OS scheduling, thermal controls, etc. all can cause instability of workload execution. We should find ways to reduce such fluctuation. Notably with better cooling solutions, rooting, and pinning down CPU/GPU frequencies.

-----
_[Original issue content:]_

This issue is a bit weird. It happens when I'm trying to switch the benchmarking phone from my dev phone to the one in the lab (which now is properly rooted). But at least it's deterministic. 

We call the `iree-benchmark-module` binary with JSON output format in the benchmark pipeline with Python subprocess. For "MobileNetV2 [fp32,imagenet] (TensorFlow) 1-thread,big-core,full-inference with IREE-Dylib @ SM-G980F (CPU-ARMv8.2-A)", looks `iree-benchmark-module` returns the output in two batches; the first batch just contains the context. It still keeps running and then after a while the results for benchmark will be returned. Somehow, Python thinks `iree-benchmark-module` has completed after seeing the first batch, which is just partial and invalid JSON. So we are seeing errors like [this one](https://buildkite.com/iree/iree-benchmark/builds/505#ab1d9078-8b91-40c4-a09e-3d72f44d7564). 

We are [calling into subprocess.run](https://github.com/google/iree/blob/471a36d7b4edfa69b8bd78e97adc216f4a083041/build_tools/android/common/benchmark_description.py#L36-L45), so it can be that I'm using subprocess.run wrongly or there is an issue with subprocess.run itself..

**Comment by antiagainst** [comment]
Took a deeper look. Turns out that the rooted S20 phone in the lab has issues. It keeps rebooting for large workloads like MobileBERT. This is happening even without pinning down GPU frequency. So likely there are issues with rooting. 

For such cases though, `adb` just returns with a 0 value; no errors of any kind, which is super confusing.

**Comment by GMNGeoffrey** [comment]
One thing I've encountered in the past is that for old API versions adb doesn't return the exit code of the underlying process. You'll want to throw in `echo $?` or something to get the real exit code. Not sure if that's what you're encountering here, but worth checking

**Comment by GMNGeoffrey** [comment]
I think it was based on the android API version. Yeah I realize that's not the actual root cause, just pointing out that weirdness in case it was frustrating your debugging efforts

**Comment by antiagainst** [comment]
Here are some general observations regarding benchmark number stability from phone's perspective:

- I didn't monitor CPU numbers extensively. But generally, CPU numbers on [S20](https://perf.iree.dev/serie?IREE?MobileNetV3Small%20[fp32,imagenet]%20(TensorFlow)%201-thread,little-core,full-inference,experimental-flags%20with%20IREE-Dylib%20@%20SM-G980F%20(CPU-ARMv8.2-A)) are less stable than [Pixel 4](https://perf.iree.dev/serie?IREE?MobileNetV3Small%20[fp32,imagenet]%20(TensorFlow)%201-thread,little-core,full-inference,experimental-flags%20with%20IREE-Dylib%20@%20Pixel-4%20(CPU-ARMv8.2-A)). Models running longer are also less stable. Also multiple threaded cases.
- Mali GPU numbers on S20 are generally not stable. This is especially true for full inference, which involves CPU. It can fluctuate a lot, in a [bi-polar](https://perf.iree.dev/serie?IREE?DeepLabV3%20[fp32]%20(TFLite)%20full-inference,experimental-flags%20with%20IREE-Vulkan%20@%20SM-G980F%20(GPU-Mali-G77)) | [fashion](https://perf.iree.dev/serie?IREE?MobileSSD%20[fp32]%20(TFLite)%20full-inference,experimental-flags%20with%20IREE-Vulkan%20@%20SM-G980F%20(GPU-Mali-G77)). For GPU kernel execution, with batching we can achieve some stability for [certain models](https://perf.iree.dev/serie?IREE?MobileNetV2%20[fp32,imagenet]%20(TensorFlow)%20kernel-execution,experimental-flags%20with%20IREE-Vulkan%20@%20SM-G980F%20(GPU-Mali-G77)), but we can also observe the [bi-polar state](https://perf.iree.dev/serie?IREE?PoseNet%20[fp32]%20(TFLite)%20kernel-execution,experimental-flags%20with%20IREE-Vulkan%20@%20SM-G980F%20(GPU-Mali-G77)).
- Adreno GPU numbers on Pixel 4 are actually much better. They are typically very stable (a linear line). 

[benchmark_thresholds.py](https://github.com/google/iree/blob/main/build_tools/benchmarks/common/benchmark_thresholds.py) can be used to define similarity thresholds for benchmark configurations. Right now it mostly contains adjusted thresholds for Mali GPUs.

**Comment by antiagainst** [comment]
Now we have quite stable numbers reported for benchmarking from the phones. Call this as done and closing it.
