### ISSUE TITLE
Tile and distribute scatter ops.

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#6548]
Currently scatter ops are executed sequentially on device. With the TiledOpInterface these can be tiled and distribute. The flow level tile + distribute that does the first level of distribution (to workgroups/blocks on the CUDA backend) is in progress. The same needs to be done for distributing it to threads. In effect, the scatter needs to just be as fast as memcpy.

**Comment by ThomasRaoux** [comment]
Confirmed that it is working and gives us the perf we want on CUDA

**Comment by tianxiangsong** [comment]
where is this pr? I met the same question, so it is has been finished?
