### ISSUE TITLE
Not able to get  flow.dispatch.workgroups() from dispatch-linalg-on-tensors-tile-sizes pass

### ISSUE THREAD

**Issue by ArunaKote** [google/iree#6572]
When I run this iree-build/iree/tools/iree-opt --iree-mhlo-to-mhlo-preprocessing --iree-mhlo-to-linalg-on-tensors --iree-flow-dispatch-linalg-on-tensors-tile-sizes="0,0,0,0" -iree-flow-dispatch-formation-enable-operand-fusion  edge_detection.mlir

I am not able to see flow.dispatch.workgroups.

But if I run  iree-build/iree/tools/iree-opt --iree-mhlo-to-mhlo-preprocessing --iree-mhlo-to-linalg-on-tensors --iree-flow-dispatch-linalg-on-tensors-pass -iree-flow-dispatch-formation-enable-operand-fusion  edge_detection.mlir I am able to see workgroups.

**Comment by benvanik** [comment]
You'll need to use pipelines instead of individual passes. Use this instead:
```
iree-opt -iree-mhlo-input-transformation-pipeline -iree-flow-transformation-pipeline ...
```

(you should only specify individual passes if writing specific lit tests against the specific pass or you are running a crash reproducer that has them expanded for you - it's not practically possible to specify them yourself)

**Comment by benvanik** [comment]
oh, if you want to see why it's not practical, take a look at the pipelines :)
https://github.com/google/iree/blob/baa1a482d9876afb3bb83d17fa4ea98238f2c4e0/iree/compiler/InputConversion/MHLO/Passes.cpp
https://github.com/google/iree/blob/323108e3869648a42dbfc82f8eb54cf05bdbafef/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
