### ISSUE TITLE
Optimizing the check of git submodule status

### ISSUE THREAD

**Issue by niloysikdar** [google/iree#6575]
**Issue:**
Currently, we are running a `check_submodule_init.py` script during CMake configure. [PR](https://github.com/google/iree/pull/6568) for the part. The script can be found [here](https://github.com/google/iree/blob/main/scripts/git/check_submodule_init.py)

It is taking ~2 seconds to run, we can use caching the result and only checking once the git commit changes as suggested by @ScottTodd , [here](https://github.com/google/iree/pull/6568#pullrequestreview-717282697)

**Comment by benvanik** [comment]
Ah yeah we should not be doing that as part of configure - especially for things that are extremely rare/obvious to fix otherwise. @ScottTodd I don't understand why this was done in python - cmake can do this itself and not require the extra python invocation (which is bad).

**Comment by benvanik** [comment]
See something like https://gist.github.com/paddy74/c44273abe3cca4337c00489f9ac307ed

**Comment by ScottTodd** [comment]
The slow part is `git submodule status` itself (particularly for tensorflow), not Python.

I think this is valuable to have in _some_ form, given the number of users that have ran into issues (on first checkout or after we add a new submodule). A consistent cost for every configure is not great though.

**Comment by benvanik** [comment]
I'm still of the opinion that we should not be adding infra complexity for things that are universal to any git project 🤷 
Walking the dirs in `$proj_root/.git/modules/third_party/$d` and checking if `$proj_root/third_party/$d` is empty and only running init if one is will avoid this. Can all be done in cmake.

**Comment by ScottTodd** [comment]
Agreed re: infra complexity, and I wish git submodules + CMake had more of a natural interaction (i.e. with easier to understand error messages, less weirdness when switching git branches, etc.)

`git submodule status` is the best source of truth that we could find. `.git/modules/...` can still hold files for deleted submodules:
![image](https://user-images.githubusercontent.com/4010439/127382943-d48594d8-b3a3-46eb-8f00-a8ec829a51f4.png)

**Comment by benvanik** [comment]
That's fine - it's not used for anything but detection - if there's no dir under third_party/ then skip it. We don't want to be running git unless we have to.
