### ISSUE TITLE
Upgrade Python version

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#6589]
TensorFlow has dropped support for Python 3.6 (https://groups.google.com/a/tensorflow.org/g/announce/c/9wOc3XBDaZs). Python 3.6 is going to be EOL at the end of the year (https://www.python.org/dev/peps/pep-0494/#id15) even though it's the version on Ubuntu 18.04 LTS.

But given that our Python tests use TF, we don't have much choice other than to upgrade as well. We updated TF versions  That means updating all our documentation to say we require Python 3.7 and updating all docker images to use 3.7 as well.

The last TF version with 3.6 support was TF 2.6 and we upgraded to TF 2.7 with https://github.com/google/iree/pull/6559, so we're actually now running in an unsupported configuration, giving this some degree of urgency. Another option to reduce urgency would be rolling back those changes and sticking with TF 2.6 until we've upgraded Python.

**Comment by stellaraccident** [comment]
+1 to upgrading.

**Comment by GMNGeoffrey** [comment]
This will also unblock https://github.com/google/iree/issues/4131

**Comment by GMNGeoffrey** [comment]
I rolled back #6559 with #6591, so we're no longer in the unsupported state, at least
