### ISSUE TITLE
[CMake] Ensure that external projects can depend on IREE's libraries

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#659]
We could set up a repository like `iree-hello` that shows how to depend on IREE with each build system.

----

Of note, `ALWAYSLINK` handling as part of #190 and #653 make depending on IREE tricky.

I *think* that other projects can (for example) develop their own `my-library-opt` binaries depending on `iree_tools_iree_opt_library`, as long as they have their own solution for `ALWAYSLINK`-style linking.

Prior to #655, other projects could also (in theory) use `iree_cc_library` and `iree_cc_binary` themselves to leverage IREE's solution for linking. With those changes, `iree_complete_binary_link_options()` runs when IREE is included in the project, before other project code. That might be okay (a project could try calling it again), or we could find a different way to "complete" the link options.

**Comment by marbre** [comment]
:+1:

Do you have something in mind in addition to the custom dialect example?

**Comment by marbre** [comment]
I gave it a quick try. A CMake configuration could look like:

```CMake
cmake_minimum_required(VERSION 3.13)

project(iree-hello CXX C)
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

list(APPEND CMAKE_MODULE_PATH
  ${CMAKE_CURRENT_LIST_DIR}/iree/build_tools/cmake/
  ${CMAKE_CURRENT_LIST_DIR}/iree/third_party/abseil-cpp/absl/copts/
)
include(..) # Whatever functions one wants to use..

add_subdirectory(iree EXCLUDE_FROM_ALL)

add_subdirectory(custom_modules)
```

I just created a copy of `iree/samples/custom_modules` within the repository root. Building fails, because the `ALWAYSLINK` stuff isn't handled yet.

Would you prefer to register as submodule (nested submodules work fine, checked that) or would you favour a docu explaining how to clone manually? I personally would like to avoid that CMake itself clones the iree repository.

**Comment by ScottTodd** [comment]
There are a few different ways that projects could depend on IREE that we'll want to support across each build system, including:

* Extending the compiler. For example, `my-library-opt` that uses some combination of compiler passes defined in IREE and compiler passes defined elsewhere. The custom dialects that we have in-tree (within the IREE repository itself) are examples of this, and we may eventually move some of these out into separate repositories like `iree-tf`. This part of the build can be tricky to depend on and customize, depending on which features are needed (and may get weirder as other frontends are added to MLIR/IREE).
* Using the runtime VM / C APIs, as in `samples/vulkan/` and `samples/simple_embedding/`. These build targets should probably be the simplest, since we want people to be able to use them from whatever toolchain they have (without needing to compromise due to opinions in IREE's build configuration).
* Using the language/platform bindings. We have Python bindings in an early form right now, and expect to add Java and possibly other languages further down the line. We should work with pip, Gradle, etc. where possible.

So this issue as stated is pretty broad and partly depends on interested users letting us know what they want out of the project and if our configuration is or isn't working for them (see the note in the README [here](https://github.com/google/iree#dependencies)). Concretely, having some minimal samples as in your comment showing how to do something would help keep the build stable and give users some ideas for how to get started. Within Google we often take for granted how difficult it can be to take a dependency on a project, since we use Bazel almost exclusively throughout our monorepo.

---

I'm not quite following the question about submodules. I don't think IREE should take on opinion on whether it gets copied into a project or includled as a git submodule, if that's what you're asking. If we create a repository dedicated to samples of how to use IREE from out of tree, then we would probably use a git submodule though.

**Comment by marbre** [comment]
I created a first example to show how IREE can be integrated into another project, located at https://github.com/iml130/iree-template-cpp. This is intended as a first draft and will change as IREE's CMake configuration still needs some refactoring. However, fell free to comment.

**Comment by marbre** [comment]
Made some sufficient progress here. The latest in-tree changed allowed me to build the `custom_modules` samples without all the alwayslink stuff. There are still some differences when building `custom-opt` in-tree or out-of-tree. Comparing the output of `custom-opt -h|grep iree` build in-tree and out-off-tree, the following options are missing building out-of-tree:
```
1a2
>       --iree-convert-flow-to-hal                       -   Convert input flow ops to the IREE HAL dialect
14a16,17
>       --iree-flow-materialize-exported-reflection      -   Materializes argument/result level reflection metadata for exported functions.
>       --iree-flow-merge-exported-reflection            -   Merges per arg and result exported reflection metadata into function level reflection attributes.
32a36
>       --iree-linalg-vector-transforms                  -   Lower linalg to vector dialect
49a54,55
>       --iree-flow-transformation-pipeline              -   Runs the full IREE flow dialect transformation pipeline
>       --iree-hal-transformation-pipeline               -   Runs the full IREE HAL dialect transformation pipeline
50a57
>       --iree-transformation-pipeline                   -   Runs the full IREE input to VM transformation pipeline
55a63,67
>   --iree-vm-bytecode-module-optimize                   - Optimizes the VM module with CSE/inlining/etc prior to serialization
>   --iree-vm-bytecode-module-output-format=<value>      - Output format the bytecode module is written in
>   --iree-vm-bytecode-module-strip-debug-ops            - Strips debug-only ops from the module
>   --iree-vm-bytecode-module-strip-source-map           - Strips the source map from the module
>   --iree-vm-bytecode-module-strip-symbols              - Strips all internal symbol names from the module
57a70
>       --iree-convert-flow-to-hal                       -   Convert input flow ops to the IREE HAL dialect
70a84,85
>       --iree-flow-materialize-exported-reflection      -   Materializes argument/result level reflection metadata for exported functions.
>       --iree-flow-merge-exported-reflection            -   Merges per arg and result exported reflection metadata into function level reflection attributes.
88a104
>       --iree-linalg-vector-transforms                  -   Lower linalg to vector dialect
105a122,123
>       --iree-flow-transformation-pipeline              -   Runs the full IREE flow dialect transformation pipeline
>       --iree-hal-transformation-pipeline               -   Runs the full IREE HAL dialect transformation pipeline
106a125
>       --iree-transformation-pipeline                   -   Runs the full IREE input to VM transformation pipeline
110a130
>       --iree-convert-flow-to-hal                       -   Convert input flow ops to the IREE HAL dialect
123a144,145
>       --iree-flow-materialize-exported-reflection      -   Materializes argument/result level reflection metadata for exported functions.
>       --iree-flow-merge-exported-reflection            -   Merges per arg and result exported reflection metadata into function level reflection attributes.
141a164
>       --iree-linalg-vector-transforms                  -   Lower linalg to vector dialect
158a182,183
>       --iree-flow-transformation-pipeline              -   Runs the full IREE flow dialect transformation pipeline
>       --iree-hal-transformation-pipeline               -   Runs the full IREE HAL dialect transformation pipeline
159a185
>       --iree-transformation-pipeline                   -   Runs the full IREE input to VM transformation pipeline
```
For `custom-translate`, the following command line arguments don't show up yet:
```
2a3
>       --iree-vm-ir-to-bytecode-module                     - iree-vm-ir-to-bytecode-module
13a15
>       --iree-convert-std-to-vm                         -   Convert Standard Ops to the IREE VM dialect
35a38
>       --iree-hal-rewrite-legacy-io                     -   Rewrites hal.interface usage to legacy iree.load_input/iree.store_output
42a46,48
>       --iree-linalg-vector-transforms                  -   Lower linalg to vector dialect
>       --iree-shape-cleanup-placeholders                -   Cleans up unnecessary shape placeholders.
>       --iree-shape-convert-hlo                         -   Converts dynamic shape dependent HLO ops to shaped variants.
54a61,63
>       --test-iree-flow-dispatchability                 -   Test pass used for dispatchability analysis
>       --test-iree-vm-register-allocation               -   Test pass used for register allocation
>       --test-iree-vm-value-liveness                    -   Test pass used for liveness analysis
65a75
>       --iree-convert-std-to-vm                         -   Convert Standard Ops to the IREE VM dialect
87a98
>       --iree-hal-rewrite-legacy-io                     -   Rewrites hal.interface usage to legacy iree.load_input/iree.store_output
94a106,108
>       --iree-linalg-vector-transforms                  -   Lower linalg to vector dialect
>       --iree-shape-cleanup-placeholders                -   Cleans up unnecessary shape placeholders.
>       --iree-shape-convert-hlo                         -   Converts dynamic shape dependent HLO ops to shaped variants.
106a121,123
>       --test-iree-flow-dispatchability                 -   Test pass used for dispatchability analysis
>       --test-iree-vm-register-allocation               -   Test pass used for register allocation
>       --test-iree-vm-value-liveness                    -   Test pass used for liveness analysis
2a3
>       --iree-vm-ir-to-bytecode-module                     - iree-vm-ir-to-bytecode-module
13a15
>       --iree-convert-std-to-vm                         -   Convert Standard Ops to the IREE VM dialect
35a38
>       --iree-hal-rewrite-legacy-io                     -   Rewrites hal.interface usage to legacy iree.load_input/iree.store_output
42a46,48
>       --iree-linalg-vector-transforms                  -   Lower linalg to vector dialect
>       --iree-shape-cleanup-placeholders                -   Cleans up unnecessary shape placeholders.
>       --iree-shape-convert-hlo                         -   Converts dynamic shape dependent HLO ops to shaped variants.
54a61,63
>       --test-iree-flow-dispatchability                 -   Test pass used for dispatchability analysis
>       --test-iree-vm-register-allocation               -   Test pass used for register allocation
>       --test-iree-vm-value-liveness                    -   Test pass used for liveness analysis
65a75
>       --iree-convert-std-to-vm                         -   Convert Standard Ops to the IREE VM dialect
87a98
>       --iree-hal-rewrite-legacy-io                     -   Rewrites hal.interface usage to legacy iree.load_input/iree.store_output
94a106,108
>       --iree-linalg-vector-transforms                  -   Lower linalg to vector dialect
>       --iree-shape-cleanup-placeholders                -   Cleans up unnecessary shape placeholders.
>       --iree-shape-convert-hlo                         -   Converts dynamic shape dependent HLO ops to shaped variants.
106a121,123
>       --test-iree-flow-dispatchability                 -   Test pass used for dispatchability analysis
>       --test-iree-vm-register-allocation               -   Test pass used for register allocation
>       --test-iree-vm-value-liveness                    -   Test pass used for liveness analysis
```
Furthermore, the documentation might still need some improvement. Anyway, feel free to check-out and/or comment on https://github.com/iml130/iree-template-cpp.

**Comment by GMNGeoffrey** [comment]
I'm getting a request for a Bazel project that wants to depend on our Python APIs. Longer term the right way is https://github.com/google/iree/issues/1677, but right now a Bazel project that wants to use IREE has to build from source. Even worse, it has to configure each of our dependencies. We could factor out a few functions from WORKSPACE that could be reused by dependent projects. I'd want to keep things like RBE toolchain separate from source dependencies, and also have logical compiler, runtime, bindings divisions where possible.

This bug is specifically tagged with CMake but talks about "how to depend on IREE with each build system". Should I create a separate issue for Bazel?

@krzys-ostrowski FYI

**Comment by marbre** [comment]
> I'm getting a request for a Bazel project that wants to depend on our Python APIs. Longer term the right way is #1677, but right now a Bazel project that wants to use IREE has to build from source. Even worse, it has to configure each of our dependencies. We could factor out a few functions from WORKSPACE that could be reused by dependent projects. I'd want to keep things like RBE toolchain separate from source dependencies, and also have logical compiler, runtime, bindings divisions where possible.
> 
> This bug is specifically tagged with CMake but talks about "how to depend on IREE with each build system". Should I create a separate issue for Bazel?
> 
> @krzys-ostrowski FYI

Good question and still unanswered :see_no_evil: Well, I think I would have closed this as we're actually able to depend with other project on IREE.

**Comment by marbre** [comment]
Any further comments? I would like to close this as resolved otherwise.

**Comment by ScottTodd** [comment]
I think we can close this one, then follow-up on Bazel / Python separately.
