### ISSUE TITLE
Compiler errors with IREE_VM_EXT_*_ENABLE defines set

### ISSUE THREAD

**Issue by hcindyl** [google/iree#6620]
When set `-DIREE_VM_EXT_I64_ENABLE=0 -DIREE_VM_EXT_F32_ENABLE=0` in CMake, The compiler will hit the following errors
```
iree/iree/vm/bytecode_dispatch.c:1543:5: error: use of undeclared identifier 'kDispatchTable_EXT_I64'; did you mean 'kDispatchTable_CORE'?
...
iree/iree/vm/bytecode_dispatch.c:1812:5: error: use of undeclared identifier 'kDispatchTable_EXT_F32'; did you mean 'kDispatchTable_CORE'?
...
```

It seems we have the implementation mismatch at 
https://github.com/google/iree/blob/f8101bad85ff5fe29bdcd674ce8ccd0d96a0ef75/iree/vm/bytecode_dispatch_util.h#L296-L299
https://github.com/google/iree/blob/f8101bad85ff5fe29bdcd674ce8ccd0d96a0ef75/iree/vm/bytecode_dispatch.c#L1543-L1544
bytecode_dispatch.c handles the define being off with return iree_make_status(IREE_STATUS_UNIMPLEMENTED);, bytecode_dispatch_util.h handles it with omitting the table entirely

**Comment by benvanik** [comment]
Ah - works on MSVC, so likely just something isolated in that alternate path for computed gotos.

**Comment by hcindyl** [comment]
hmm... it also works building with Linux. So it is only broken when `-DIREE_PLATFORM_GENERIC -DIREE_SYNCHRONIZATION_DISABLE_UNSAFE=1 -DIREE_FILE_IO_ENABLE=0` (i.e., bare-metal) is set.

**Comment by benvanik** [comment]
Weird, as that code doesn't interact with either of those. Maybe it's GCC or something?
(I haven't looked at the code/error yet, but will try to get to it tonight/tomorrow)

**Comment by hcindyl** [comment]
Scratch comment 

> hmm... it also works building with Linux. So it is only broken when `-DIREE_PLATFORM_GENERIC -DIREE_SYNCHRONIZATION_DISABLE_UNSAFE=1 -DIREE_FILE_IO_ENABLE=0` (i.e., bare-metal) is set.

Scratch this comment, I put the definition at the wrong place.... Testing it again with Linux build....

**Comment by hcindyl** [comment]
okay, the flag `-DIREE_VM_EXT_I64_ENABLE=0` also fails with the X86_64 linux config
