### ISSUE TITLE
Missing Flow->HAL->VM lowering for f32 fills/splats

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#6629]
Splitting this off from https://github.com/google/iree/issues/1159#issuecomment-891245839

Running detensoring on `collatz.mlir` from [`control_flow_test.py`](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/control_flow_test.py) is producing IR like this ([full IR dump here](https://gist.github.com/ScottTodd/941825f6ea6eb33e9cc1b249d0d4eddb)):

```mlir
^bb5(%18: f32):  // pred: ^bb1
  %19 = flow.tensor.splat %18 : tensor<f32>
  %20 = hal.tensor.cast %19 : tensor<f32> -> !hal.buffer_view
  return %20 : !hal.buffer_view
}
```

but that `flow.tensor.splat` can't be lowered to a `hal.command_buffer.fill_buffer` directly (fill takes only i32). The current lowering code is here: https://github.com/google/iree/blob/c3ea7a879abfa86aa7c0994afba2b19d7354a459/iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp#L977-L983 (note that `splatFillPattern` only handles ints right now)

from @benvanik :
> For the f32 fill we should insert a bitcast - which I don't think exists upstream or in the VM yet. We can allow the hal op to take any 32-bit value (or anything <=4 bytes) and then when converting hal->vm can insert the cast. I had thought I needed this for something else and added it but maybe in some long-lost branch.

The existing HAL->VM patterns seem to be nearly all direct conversions: https://github.com/google/iree/blob/c3ea7a879abfa86aa7c0994afba2b19d7354a459/iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertCommandBufferOps.cpp#L66-L73

so I'm wondering if it would be better to keep int32 patterns and insert `std.fpext` + `std.bitcast` (for floats) / `std.zexti` (for lower bit depth ints) ops ahead of `hal.command_buffer.fill_buffer` ops, then lower directly to `vm.ext.i16.i32.s` / `vm.bitcast`, etc. In fact, `splatFillPattern` is already doing that int extending. Roughly (we're missing a few ops in IREE and upstream for this):

```mlir
%0 = flow.tensor.splat %arg1 : tensor<f16>

// flow -> hal lowering: insert extend / std.bitcast (as needed), accept only int32 patterns on fill_buffer
%pattern_extended = fpext %arg1 : f16 to f32
%pattern_int32 = std.bitcast %pattern_extended : f32 to i32
hal.command_buffer.fill_buffer .. .pattern(%pattern_int32 : i32)

// hal -> vm lowering
%pattern_extended = vm.ext.f16.f32
%pattern_int32 = vm.bitcast %pattern_extended : f32 to i32
vm.call @hal.command_buffer.fill_buffer ...
```

However, for my immediate case, changing `hal.command_buffer.fill_buffer` to accept `f32` or `int32` patterns and adding a `vm.bitcast` that gets inserted during hal->vm lowering would be fastest.

**Comment by ScottTodd** [comment]
Either way, it looks like we'll want a `vm.bitcast` op, which I can base off of the proposed standard dialect version on https://reviews.llvm.org/D105376

**Comment by ScottTodd** [comment]
Oh, we do already have a floating-point to signed integer type cast op in std + vm:
https://mlir.llvm.org/docs/Dialects/Standard/#stdfptosi-mlirfptosiop
https://github.com/google/iree/blob/c3ea7a879abfa86aa7c0994afba2b19d7354a459/iree/vm/ops.h#L315-L320
those may be enough for now...

**Comment by benvanik** [comment]
that's not a bitcast though and won't be correct (unless your float is always a round number)

**Comment by ScottTodd** [comment]
Yeah, realized that after I wrote the comment and edited :P hmm...

**Comment by benvanik** [comment]
Bitcast isn't even needed in the bytecode VM - all registers are untyped so bitcasting i32 to f32 is just saying "do integer op on register R and then do floating point op on register R." It's useful as an IR construct, though, and emitc/LLVMIR lowering/etc may need the information so it's worth having in the IR even if we don't serialize it in the bytecode. Everything in the VM is sized so we'd want `vm.bitcast.x32` and `vm.bitcast.x64` and when lowering from the std op switch into one of those based on type.getIntOrFloatBitWidth().

**Comment by benvanik** [comment]
(oh and I think it may as well be emitted into bytecode - an assign-like op can be useful for cloning registers)

**Comment by silvasean** [comment]
Just hit this in npcomp! reach out to me if there is anything I can do to help :) It's moderately blocking for me.

**Comment by ScottTodd** [comment]
> Just hit this in npcomp! reach out to me if there is anything I can do to help :) It's moderately blocking for me.

I'm actively working on a `vm.bitcast` op in IREE, but I'll still be missing `std.bitcast` to lower through, while https://reviews.llvm.org/D105376 is still under discussion/review. If you could help get that landed that would help. Otherwise, I'd consider adding an `iree.bitcast` to hold us over until discussion upstream resolves.

**Comment by ScottTodd** [comment]
Oh, can you also provide some IR snippets that are failing, @silvasean ? I can make sure what I'm working on will support those cases.

**Comment by silvasean** [comment]
https://gist.github.com/silvasean/7057047ce45d7c621ee219198dd41bfa

**Comment by ScottTodd** [comment]
> https://gist.github.com/silvasean/7057047ce45d7c621ee219198dd41bfa

Thanks! Looks like the IR for that is roughly:

```mlir
%12 = linalg.fill(%cst_0, %11) : f32, tensor<?x?x?x?xf32> -> tensor<?x?x?x?xf32>

%22 = flow.tensor.splat %cst : tensor<?x?x?x?xf32>{%arg1, %arg2, %arg3, %arg4}

"hal.command_buffer.fill_buffer"(%41, %40, %43, %39, %25) : (!hal.command_buffer, !hal.buffer, index, index, f32) -> ()
```

so yeah, this will also need updates to the `flow.tensor.splat` lowering to handle `f32` values, which will use bitcasts: https://github.com/google/iree/blob/c3ea7a879abfa86aa7c0994afba2b19d7354a459/iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp#L943-L997

**Comment by ScottTodd** [comment]
Oh nice! The folders on `std.bitcast` can handle that `%cst_0` directly without needing to lower to the `vm.bitcast` I'm adding :D

I have a change that together with https://reviews.llvm.org/D105376 fully lowers the IR in that gist.

**Comment by ScottTodd** [comment]
This is fixed now :D
