### ISSUE TITLE
converting tflite models to mlir using iree

### ISSUE THREAD

**Issue by ArunaKote** [google/iree#6638]
I have installed packages using python -m pip install \
  iree-compiler-snapshot \
  iree-runtime-snapshot \
  iree-tools-tflite-snapshot \
  -f https://github.com/google/iree/releases

 when I import the TFLite model to  MLIR: iree-import-tflite  sample.tflite   -o sample.mlir

I am getting error as bin/iree-import-tflite", line 5, in <module>
    from iree.tools.tflite.scripts.iree_import_tflite.__main__ import main
ModuleNotFoundError: No module named 'iree.tools.tflite.scripts'

**Comment by ScottTodd** [comment]
Running the tool in Colab works for me: https://colab.research.google.com/github/google/iree/blob/main/colab/tflite_text_classification.ipynb
see this section:
```python
IREE_TFLITE_TOOL = iree_tflite.get_tool('iree-import-tflite')
!{IREE_TFLITE_TOOL} {ARTIFACTS_DIR}/text_classification.tflite -o={ARTIFACTS_DIR}/text_classification.mlir
```

The `iree.tools.tflite.scripts` in your error message is probably coming from here: https://github.com/google/iree/blob/f0d243f09d678f33a7150392048e4ec9026efd2a/integrations/tensorflow/bindings/python/iree/tools/tflite/setup.py.in#L81-L85

so maybe something in the console scripts isn't working? (added in https://github.com/google/iree/commit/b008ff6d3e268ddcb6dd456ad148cc85ec58c2d3)

**Comment by ScottTodd** [comment]
Yeah, I can repro the `ModuleNotFoundError` on Linux/Debian with Python 3.9.2:


```shell
scotttodd:~/.../scratch/iree$ python -m venv .venv
scotttodd:~/.../scratch/iree$ source .venv/bin/activate
(.venv) scotttodd:~/.../scratch/iree$ python -m pip install \
  iree-compiler-snapshot \
  iree-runtime-snapshot \
  iree-tools-tflite-snapshot \
  -f https://github.com/google/iree/releases
Looking in links: https://github.com/google/iree/releases
Collecting iree-compiler-snapshot
  Downloading https://github.com/google/iree/releases/download/snapshot-20210801.437/iree_compiler_snapshot-20210801.437-py3-none-manylinux2014_x86_64.whl (34.7 MB)
     |████████████████████████████████| 34.7 MB 18.2 MB/s
Collecting iree-runtime-snapshot
  Downloading https://github.com/google/iree/releases/download/snapshot-20210801.437/iree_runtime_snapshot-20210801.437-cp39-cp39-manylinux2014_x86_64.whl (425 kB)
     |████████████████████████████████| 425 kB 44.4 MB/s
Collecting iree-tools-tflite-snapshot
  Downloading https://github.com/google/iree/releases/download/snapshot-20210801.437/iree_tools_tflite_snapshot-20210801.437-py3-none-manylinux2014_x86_64.whl (5.2 MB)
     |████████████████████████████████| 5.2 MB 50.6 MB/s
Installing collected packages: iree-tools-tflite-snapshot, iree-runtime-snapshot, iree-compiler-snapshot
Successfully installed iree-compiler-snapshot-20210801.437 iree-runtime-snapshot-20210801.437 iree-tools-tflite-snapshot-20210801.437
(.venv) scotttodd:~/.../scratch/iree$ which iree-import-tflite
/usr/local/google/home/scotttodd/code/scratch/iree/.venv/bin/iree-import-tflite
(.venv) scotttodd:~/.../scratch/iree$ iree-import-tflite --help
Traceback (most recent call last):
  File "/usr/local/google/home/scotttodd/code/scratch/iree/.venv/bin/iree-import-tflite", line 5, in <module>
    from iree.tools.tflite.scripts.iree_import_tflite.__main__ import main
ModuleNotFoundError: No module named 'iree.tools.tflite.scripts'
(.venv) scotttodd:~/.../scratch/iree$ iree-translate --help
Traceback (most recent call last):
  File "/usr/local/google/home/scotttodd/code/scratch/iree/.venv/bin/iree-translate", line 5, in <module>
    from iree.tools.core.scripts.iree_translate.__main__ import main
ModuleNotFoundError: No module named 'iree.tools.core.scripts'
```

**Comment by ScottTodd** [comment]
I think there's an issue to fix here with the `console_scripts` (or our documentation), but for now @ArunaKote you could match what that Colab notebook is doing.

**Comment by ScottTodd** [comment]
@stellaraccident can you help triage the `console_scripts` issue? Was that usage working before? Should our documentation be suggesting something different?

**Comment by stellaraccident** [comment]
We don't have a test for it (such a test is a bit tricky to write and be effective -- more of a post install smoke test). And I remember verifying these, but there were a bunch of them and may have been fat fingers.

**Comment by stellaraccident** [comment]
I think I know how I tested this incorrectly: I installed the wheel from the directory it is built in and then tried the command. It worked because the PYTHONPATH includes CWD, and the bug involves excluding files from the wheel. We really need a separate post-build step which installs these things and runs basic tests.
