### ISSUE TITLE
Can I convert tf saved_models to tf/HLO dialect using iree

### ISSUE THREAD

**Issue by ArunaKote** [google/iree#6656]
Hi,
   Can I convert tf saved_models to tf/HLO dialect using iree? If yes what are the commands I should use?

Thanks

**Comment by stellaraccident** [comment]
Iree does that for its own purposes but doesn't have a general way (ie. We convert to a mix of hlo and other dialects based on our requirements). The upstream tensorflow project has some standalone tools that people have used for this, though.

**Comment by stellaraccident** [comment]
You are, of course, free to look at the iree-import-tf source for inspiration: https://github.com/google/iree/blob/main/integrations/tensorflow/iree_tf_compiler/iree-import-tf-main.cpp
