### ISSUE TITLE
IREE build failed

### ISSUE THREAD

**Issue by uccoder-hk** [google/iree#6684]
Hello,

I have tried to build IREE as mentioned in https://google.github.io/iree/building-from-source/getting-started/
But build failed with below logs.. 

Commit : af31bf4c9cae087994011250e03a7f7f04f0910e

Build Commands:
cmake -B ../iree-build/ -DCMAKE_BUILD_TYPE=RelWithDebInfo .
cmake --build ../iree-build/

[ 57%] Building CXX object third_party/mlir-hlo/lib/Dialect/mhlo/IR/CMakeFiles/obj.ChloDialect.dir/chlo_ops.cc.o
[ 57%] Built target obj.ChloDialect
[ 57%] Linking CXX static library libChloDialect.a
[ 57%] Built target ChloDialect
[ 57%] Building generated_lower_complex.inc...
[ 57%] Built target MLIRMhloLowerComplexIncGen
[ 57%] Building generated_legalize_to_standard.inc...
[ 57%] Built target MLIRMhloLegalizeToStandardIncGen
[ 57%] Building generated_chlo_legalize_to_hlo.inc...
[ 57%] Built target MLIRChloLegalizeToHloIncGen
[ 57%] Building CXX object third_party/mlir-hlo/lib/Dialect/mhlo/transforms/CMakeFiles/obj.MhloTypeConversion.dir/type_conversion.cc.o
[ 57%] Built target obj.MhloTypeConversion
[ 57%] Linking CXX static library libMhloTypeConversion.a
[ 57%] Built target MhloTypeConversion
[ 57%] Building CXX object third_party/mlir-hlo/lib/Dialect/mhlo/transforms/CMakeFiles/obj.MhloToStandard.dir/legalize_control_flow.cc.o
In file included from /Users/uccoder/src/ir-dev/iree/third_party/mlir-hlo/lib/Dialect/mhlo/transforms/legalize_control_flow.cc:22:
/Users/uccoder/src/ir-dev/iree/third_party/mlir-hlo/include/mlir-hlo/Dialect/mhlo/transforms/PassDetail.h:32:10: fatal error:
      'mlir-hlo/Dialect/mhlo/transforms/mhlo_passes.h.inc' file not found
#include "mlir-hlo/Dialect/mhlo/transforms/mhlo_passes.h.inc"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [third_party/mlir-hlo/lib/Dialect/mhlo/transforms/CMakeFiles/obj.MhloToStandard.dir/legalize_control_flow.cc.o] Error 1
make[1]: *** [third_party/mlir-hlo/lib/Dialect/mhlo/transforms/CMakeFiles/obj.MhloToStandard.dir/all] Error 2
make: *** [all] Error 2

Please share the build instructions if I am missing anything

**Comment by stellaraccident** [comment]
It is a problem with an upstream cmake file which seems to affect a couple
of folks. An outside contributor said they were going to submit a patch but
either it hasn't landed in iree or hasn't landed upstream yet (don't have
the link handy).

Conversation was on discord. Here are relevant excerpts:

---
Perfect. I think that allows me to identify the issue: ChloPasses doesn't
include  MLIRMhloPassIncGen
https://github.com/tensorflow/tensorflow/blob/fb51d1bf77f83d9c76e45775389f38bdd834025a/tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/CMakeLists.txt#L33
---

I had to add the three lines to the ChloPasses  to make it work.

MLIRMhloPassIncGen
MLIRLmhloPassIncGen
MLIRDiscRalPassIncGen
---

As a local measure, you can explicitly make/ninja those three targets and
then try the build step again and it should work.

Apologies - we should have created an issue to track when this was
discussed.

**Comment by stellaraccident** [comment]
Here is the relative upstream commit: https://github.com/tensorflow/mlir-hlo/commit/70399f0334e53b4fc1339a9e72af7e0e63992d5a

Looks like we haven't integrated from tensorflow in a few days and it will be picked up in the one (prob early next week). You can cherrypick that patch into your local third_party/mlir-hlo submodule in the mean-time.

**Comment by stellaraccident** [comment]
I've made some comprehensive build fixes to the upstream mlir-hlo project: https://github.com/tensorflow/mlir-hlo/commit/144c1c6733c6ac771288612b76b099160ff518ed

They should come in with the next integrate, or that patch can be made locally.

**Comment by uccoder-hk** [comment]
> Here is the relevant upstream commit: [tensorflow/mlir-hlo@70399f0](https://github.com/tensorflow/mlir-hlo/commit/70399f0334e53b4fc1339a9e72af7e0e63992d5a)
> 
> Looks like we haven't integrated from tensorflow in a few days and it will be picked up in the next one (prob early next week). You can cherrypick that patch into your local third_party/mlir-hlo submodule in the mean-time.

Thanks. This resolved the above issue and build is successful.
