### ISSUE TITLE
iree-translate : dependency issue

### ISSUE THREAD

**Issue by uccoder-hk** [google/iree#6690]
Hello,

I have installed IREE pip packages (from snapshot-20210805.445) mentioned in https://google.github.io/iree/ml-frameworks/tensorflow-lite/

But iree-translate commands fails to run

Logs:
$iree-translate
Traceback (most recent call last):
  File "/opt/anaconda3/envs/iree-dev/bin/iree-translate", line 5, in <module>
    from iree.tools.core.scripts.iree_translate.__main__ import main
ModuleNotFoundError: No module named 'iree.tools.core.scripts'

python version : 3.7.0

**Comment by stellaraccident** [comment]
Most likely the same issue as: https://github.com/google/iree/issues/6638
(but for this package). These convenience scripts were getting excluded by
setup.py. until we push a fix, you can find the actual executable embedded
in the python package (in the lib dir) or in the main-dist tarball in the
release. It is just the wrapper script that isn't installed properly.

**Comment by uccoder-hk** [comment]
Thanks..
