### ISSUE TITLE
[iree-translate (Host executable] : Conversion from TFLite failed for MobileNet V2

### ISSUE THREAD

**Issue by uccoder-hk** [google/iree#6691]
Hello,

I tried to use iree-translate executable generated after https://google.github.io/iree/building-from-source/getting-started/
for compiling mobile net V2 TFLite model. (Since the iree-translate form pip package didn't work https://github.com/google/iree/issues/6690)

Though the conversion from .tflite to .mlir is successful using iree-import-tflite , conversion from .mlir to .vmfb failed..

COMMAND:
iree/tools/iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vmvx ../mobilenet_v2.mlir -o ../mobilenet_v2.vmfb 2>&1 | tee | grep -E "error|fail"

Model : mobilenet_v2_1.0_224.tflite (https://storage.googleapis.com/download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224.tgz)

Logs(Only error):
../mobilenet_v2.mlir:110:12: error: 'tosa.conv2d' op operand #0 must be unranked.tensor of number values or 4D tensor of number values, but got '!hal.buffer_view'
../mobilenet_v2.mlir:1:1: error: conversion from source -> vm failed

**Comment by ScottTodd** [comment]
The https://colab.research.google.com/github/google/iree/blob/main/colab/tflite_text_classification.ipynb notebook shows a similar error (and that worked at some point).

```
CompilerToolError: Error invoking IREE compiler tool iree-translate
Diagnostics:
<stdin>:13:11: error: 'tosa.gather' op operand #1 must be 2D tensor of 32-bit signless integer values, but got '!hal.buffer_view'
    %10 = "tosa.gather"(%9, %arg0) : (tensor<1x10003x16xf32>, tensor<1x256xi32>) -> tensor<1x256x16xf32>
          ^
```

**Comment by stellaraccident** [comment]
Both are missing the --iree-input-type=tosa flag (input_type=tosa).

The input pipeline in the compiler has a bug: the validation pass that verifies only legal input is provided should be catching this and telling you to include the flag, but it isn't. I think this happened when Mahesh split the code up. The error is coming because the tosa op is getting through unconverted and being treated like a custom op -- which it is not.

**Comment by stellaraccident** [comment]
Also, to save you some time:

* Quantized convolution codegen is still being implemented (actively - shouldn't be long but does not work now) -- so float only
* Performance work on depthwise conv and friends is scheduled but not done beyond POCs. It will work but is not nearly as efficient as it should be.

**Comment by ScottTodd** [comment]
> Both are missing the --iree-input-type=tosa flag (input_type=tosa in python).
> 
> The input pipeline in the compiler has a bug: the validation pass that verifies only legal input is provided should be catching this and telling you to include the flag, but it isn't. I think this happened when Mahesh split the code up. The error is coming because the tosa op is getting through unconverted and being treated like a custom op -- which it is not (it falls verification when bufferized).

Ah, thanks for pointing that out! Adding the `input_type=tosa` option does fix that notebook. I can send a PR tomorrow to update the notebook + docs.

**Comment by uccoder-hk** [comment]
> Both are missing the --iree-input-type=tosa flag (input_type=tosa in python).
> 
> The input pipeline in the compiler has a bug: the validation pass that verifies only legal input is provided should be catching this and telling you to include the flag, but it isn't. I think this happened when Mahesh split the code up. The error is coming because the tosa op is getting through unconverted and being treated like a custom op -- which it is not (it falls verification when bufferized).

Adding --iree-input-type=tosa  resolved the above issue. Thanks

**Comment by benvanik** [comment]
Glad it worked for you, and thanks for filing the issue! With #6707 I think we can call this fixed and hopefully not trip up others in the future :)
