### ISSUE TITLE
Compiler should reject tosa and MHLO without proper flags

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#6692]
See https://github.com/google/iree/issues/6691

When @MaheshRavishankar split the input pipeline source code, the verification passes stopped enforcing that no high level ops survive to the main pipeline. It should do so and raise an appropriate error.

**Comment by MaheshRavishankar** [comment]
Would it make sense to have a verification pass at the start of IREE compilation that checks that the only a know list of ops are present in IREE at the start of the compilation. The MHLO pipeline and the TOSA pipeline do check that all MHLO and TOSA ops are converted, but if the `-iree-input-type` flag isnt used, then those pipelines (and those verification passes) are not invoked. I can add that.

**Comment by benvanik** [comment]
That's tricky because we want to allow for custom ops that make their way to runtime: we can't have a strict allowlist of ops and also have that work. Having a denylist of dialects, though, seems doable: no tosa, mhlo, etc allowed regardless of which input type was specified.

**Comment by benvanik** [comment]
(this is really just to help prevent people from accidentally having ops go through so it's fine to have false negatives - false positives are bad though as that prevents functionality)

**Comment by MaheshRavishankar** [comment]
Having a deny list means that `tosa` and `mhlo` dialects need to be linked into the core IREE compiler. I wanted to avoid that.

**Comment by benvanik** [comment]
Ah no - you just string compare the dialect name instead of using the C++ type.

**Comment by MaheshRavishankar** [comment]
Ok, thats slight better, but it means the dialect name is hard-coded, and there is no gaurantee that that name shouldnt change. We can expect that it doesnt change.

**Comment by benvanik** [comment]
Yeah I think that's fine - if "mhlo" or "tosa" change their name there's a lot bigger issues than a string in one place :)

**Comment by stellaraccident** [comment]
+1 on string compare and a lit test to make sure it is working.

I don't think we're ready for a whitelist yet. And i think the custom op story needs to converge some more. Probably needs to be based on an interface or something vs just any old op.

**Comment by benvanik** [comment]
Yeah agreed - I'm excited now that it's possible to register interfaces on ops out of dialect as it will let us have custom op shims that mark up the ops we know we can handle. Of course, the longer we can put off needing any of that the better :)
