### ISSUE TITLE
Type mismatch lowering f32 ops to the VM

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#6712]
Found while working on https://github.com/google/iree/issues/1159 with local changes, so plenty of things could be misconfigured. I'm mainly wondering at which level this error I'm encountering should be addressed.

I'm starting from a `flow.tensor.load %0 : tensor<f32>`, which eventually gets down to this error during `IREE::VM::ConversionPass`:
```mlir
D:\dev\projects\iree/../iree-data/tests/collatz.mlir:15:5: error: type mismatch for bb argument #1 of successor #0
    br ^bb1(%cst_3, %arg0 : tensor<f32>, tensor<f32>)
    ^
D:\dev\projects\iree/../iree-data/tests/collatz.mlir:3:3: note: called from
  func @collatz(%arg0: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi = "{\22a\22:[[\22ndarray\22,\22f32\22,0]],\22r\22:[[\22ndarray\22,\22f32\22,0]],\22v\22:1}"} {
  ^
D:\dev\projects\iree/../iree-data/tests/collatz.mlir:15:5: note: see current operation: "vm.br"(%0, %10)[^bb1] : (f32, i32) -> ()
    br ^bb1(%cst_3, %arg0 : tensor<f32>, tensor<f32>)
    ^
```

### Main IR causing the issue

before ConvertToHAL
```mlir
    %0 = hal.tensor.cast %arg0 : !hal.buffer_view -> tensor<f32>
    %1 = flow.tensor.load %0 : tensor<f32>
    br ^bb1(%cst, %1 : f32, f32)
  ^bb1(%2: f32, %3: f32):  // 3 preds: ^bb0, ^bb3, ^bb4
    %4 = cmpf ogt, %3, %cst_1 : f32
```

after ConvertToHAL
```mlir
    %off = hal.buffer_view.compute_offset %arg0, indices = [] : index
    %buffer = hal.buffer_view.buffer %arg0 : !hal.buffer
    %0 = hal.buffer.load<%buffer : !hal.buffer>[%off] : f32
    br ^bb1(%cst, %0 : f32, f32)
  ^bb1(%1: f32, %2: f32):  // 3 preds: ^bb0, ^bb3, ^bb4
    %4 = cmpf ogt, %3, %cst_1 : f32
```

during VM conversion
note the hal.buffer.load call and `vm.br` now use `i32` while `^bb1` is still expecting `f32`
```mlir
      %8 = "vm.call"(%arg0) {callee = @hal.buffer_view.buffer} : (!vm.ref<!hal.buffer_view>) -> !vm.ref<!hal.buffer>
      %9 = "vm.const.i32"() {value = 4 : i32} : () -> i32
      %10 = "vm.call"(%8, %5, %9) {callee = @hal.buffer.load} : (!vm.ref<!hal.buffer>, i32, i32) -> i32
      "vm.br"(%0, %10)[^bb1] : (f32, i32) -> ()
    ^bb1(%11: f32, %12: f32):  // 3 preds: ^bb0, ^bb3, ^bb4
      %13 = "vm.cmp.gt.f32.o"(%12, %2) : (f32, f32) -> i32
```

full IR in [this gist](https://gist.github.com/ScottTodd/fe6709362cef9ff93d6e8a623cce086e)

### Looking at the code

The HAL->VM lowering gets the return type for `BufferLoadOp` from imports:
https://github.com/google/iree/blob/36d3efcb3fb4fda86c4cbb947ebf17c8ef22131f/iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertBufferOps.cpp#L28-L35
https://github.com/google/iree/blob/36d3efcb3fb4fda86c4cbb947ebf17c8ef22131f/iree/compiler/Dialect/HAL/hal.imports.mlir#L58-L63

but the op is defined as returning any `HAL_PrimitiveType`: https://github.com/google/iree/blob/36d3efcb3fb4fda86c4cbb947ebf17c8ef22131f/iree/compiler/Dialect/HAL/IR/HALOps.td#L726-L728
https://github.com/google/iree/blob/36d3efcb3fb4fda86c4cbb947ebf17c8ef22131f/iree/compiler/Dialect/HAL/IR/HALBase.td#L367

**Comment by benvanik** [comment]
In the short-term we could insert a bitcast there (now that we have it) during hal->vm conversion. Long-term we'll probably want to remove the hal.buffer.load/store runtime functional entirely (as it presumes fast local memory access) and at most provide a way to read into/write from vm.buffers where we can reuse the existing vm ops for typed load/stores.

**Comment by ScottTodd** [comment]
So make `BufferLoadOpConversion` produce something like this?

```mlir
%10 = "vm.call"(%8, %5, %9) {callee = @hal.buffer.load} : (!vm.ref<!hal.buffer>, i32, i32) -> i32
%11 = vm.bitcast.i32.f32 %10 : i32 -> f32
"vm.br"(%0, %11)[^bb1] : (f32, f32) -> ()
```

**Comment by benvanik** [comment]
I think so - and the reverse for stores.
