### ISSUE TITLE
TOSA expandDims has incorrect logic for negative elements

### ISSUE THREAD

**Issue by dan-garvey** [google/iree#6768]
> If you are an IREE team member, please consider doing further triage: remove the "help wanted" label, add other relevant labels, and redirect to a more appropriate assignee.
> 
> **Describe the bug**

If the reshape dim is <-1, the current logic will still append a dimension to the end of the existing shape. The current logic also fails on elementAttrs with >0 rank. (rank 1 should be fine as well)

> **To Reproduce**
> Steps to reproduce the behavior:
> If you believe this is an issue with IREE core (not integrations) please provide a reproduction (including artifacts) that does not require integrations
> ([Instructions for extracting artifacts from TF tests](https://github.com/google/iree/blob/main/docs/developers/developing_iree/e2e_benchmarking.md))

generate a saved model using tensorflow official Bert.
./bazel-bin/iree_tf_compiler/iree-import-tf  --tf-savedmodel-exported-names="predict"  --use-tosa /path/to/saved/bert

expected failure: `iree-import-tf: external/org_tensorflow/tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc:1170: llvm::Optional<Value> mlir::tosa::convertExpandDimsOp(mlir::PatternRewriter &, mlir::Operation *, mlir::Value, mlir::Value, mlir::Value): Assertion dim_elem.getType().getRank() == 0 && "expected scalar tensor"' failed.`

> 
**Additional context**

Will open a PR on upstream TF to fix the issue.

**Comment by GMNGeoffrey** [comment]
Thanks for the report. I'm going to hand this over to Rob, but yeah this looks like an issue in TF, not IREE per se.
