### ISSUE TITLE
iree-translate failure when compiling npcomp lowered Resnet18 model

### ISSUE THREAD

**Issue by hunbssfy** [google/iree#6790]
**Describe the bug**
I used npcomp to lower a Resnet18 model to a compatible IREE input MLIR module and then npcomp will try to use IREE python binding (`iree.compiler`) to call into IREE compiler. 
**If I run the test script end-to-end it will pass** but if I extract the command line built from the code below (`cl` variable) to call `iree-translate` directly error occurs:
iree/compiler/core.py:240
```
def compile_str(input_str: Union[str, bytes], **kwargs):
  """Invokes the IREE compiler with an input string.

  Args:
    input_str: MLIR assembly to parse/compile (str or bytes).
    **kwargs: Keyword arguments corresponding to CompilerOptions.
  Returns:
    Either a byte buffer of the compiled content or None if output_file
    was specified in the options.
  """
  with TempFileSaver.implicit() as tfs:
    options = CompilerOptions(**kwargs)

    #extract this command line
    cl = build_compile_command_line("-", tfs, options) 

    input_bytes = input_str.encode("utf-8") if isinstance(input_str,
                                                          str) else input_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
    if options.output_file:
      return None
    return result
```
and the command line is:
```
/root/.pyenv/versions/3.8.9/lib/python3.8/site-packages/iree/tools/core/iree-translate --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib-llvm-aot --iree-mlir-to-vm-bytecode-module --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false after_lowering.mlir`
```

I will got the following error:
![image](https://user-images.githubusercontent.com/6930027/129871076-87710024-812e-438e-8f0c-ceedfd409e4e.png)

@silvasean suggested (from this original npcomp issue: https://github.com/llvm/mlir-npcomp/issues/280) that this might be  an IREE error so I opened up this bug issue here.

**To Reproduce**
I attached my lowered module at the end and you could skip the npcomp related steps if you want to reproduce the error quickly. But I suggest going through building the preparing npcomp so maybe you can find something wrong in my steps of getting my lowered mlir module...

This is how I got the npcomp lowered Resnet18 mlir module:
1. Setup mlir/npcomp within the docker env they provided following the instruction from here: https://github.com/llvm/mlir-npcomp/blob/main/README.md , Please build Pytorch frontend and install the latest `iree-compiler-snapshot`and `iree-runtime-snapshot` with `pip install`
2. Go to `frontends/pytorch/examples` within npcomp repository
3. Change the code between import_module and bankend.compile as below:
```
backend = iree.IreeNpcompBackend()
#backend = refjit.RefjitNpcompBackend()
lowering = frontend_lowering.lower_object_graph(mb.module)
asm_for_error_report = mb.module.operation.get_asm(enable_debug_info=True)
import tempfile, os
filename = os.path.join(tempfile.gettempdir(),
                        'after_lowering.mlir')
with open(filename, 'w') as f:
    f.write(asm_for_error_report)
```
4. Now run `python torchscript_resnet18_e2e.py`, the script will run successfully and you will get after_lowering.mlir under /tmp directory
5. copy after_lowering.mlir to the current directory
6. Run iree-translate command and produce the error:
```
/path/to/the/iree/installed/with/pip/tools/core/iree-translate --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib-llvm-aot --iree-mlir-to-vm-bytecode-module --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false after_lowering.mlir`
```

**Quick Reproduce**
I also attached my lowered module here and you can use it directly with the command line above:
[after_lowering.mlir.zip](https://github.com/google/iree/files/7006138/after_lowering.mlir.zip)

**Comment by GMNGeoffrey** [comment]
Hmm one thing I notice about your attached mlir file is that all the constants are `constant opaque<"_", "0xDEADBEEF">`. That might explain a difference between the IR you have in the test vs what you're getting from after_lowering.mlir

I think npcomp is the thing generating that. Maybe with `--mlir-elide-elementsattrs-if-larger`? Can you take a look at whether dropping that generates IR without the failure?

**Comment by hunbssfy** [comment]
@silvasean I don't think there are instructions about how to regenerate IR without opaque constants..
Could you tell me the instructions? Currently, I am lowering the graph using Passmanager but I think `--mlir-elide-elementsattrs-if-larger` is a `mlir-opt` option?

**Comment by silvasean** [comment]
You want to make sure that you don't pass the `large_elements_limit` kwarg to `get_asm` Python method.

**Comment by hunbssfy** [comment]
@silvasean https://github.com/llvm/mlir-npcomp/issues/280#issuecomment-899971118 I actually dropped this option in the npcomp issue, but it still gets an error.

**Comment by silvasean** [comment]
Can you dump mb.module right after mb.import_module and after lower_object_graph? We need to find where those opaque constants are coming from.

**Comment by hunbssfy** [comment]
@silvasean I think I got the dumped ir wrong ... Dropping `large_elements_limit` fixes the problem. Sorry...
