### ISSUE TITLE
IREE not catching out-of-memory failures in bare-metal environment

### ISSUE THREAD

**Issue by jtate-pu** [google/iree#6807]
**Describe the bug**
IREE's VM does not catch out-of-memory failures (malloc returning nullptr) in bare-metal embedded environments.

**To Reproduce**
Using the RISC-V bare metal target, attempt to run a model that requires more memory than the embedded target has available. You can check this artificially by attempting to use a very low memory target in qemu. In our case, we were attempting to run a proprietary model that needed to allocate 4.7 megabytes in a single malloc on a platform that only has 4 available.

**Additional context**
The asserts that should have caught this issue seem to be disabled on release builds, which unfortunately allowed the error to propagate and become more obfuscated. We should consider ensuring that, at minimum, the runtime safety asserts surrounding standard library calls are always checked regardless of build type.

Attn: @hcindyl

**Comment by benvanik** [comment]
Do you have any more details about what you are using to allocate? We do check for allocation failure when using the system allocator, so I'm guessing you are using your own custom allocator or not using IREE's allocation interface somewhere?

https://github.com/google/iree/blob/5ca3e18afc6b1bbf6df5bcac0ea14a2c479d5fe5/iree/base/allocator.c#L95-L98

**Comment by benvanik** [comment]
I got rid of the two places we weren't routing through iree_allocator_t here: https://github.com/google/iree/pull/6809, so now if you are hitting unguarded allocations they are likely in your application/embedding code or a bug at a specific place we'd need a callstack for.

**Comment by hcindyl** [comment]
I found the bug (or one of them)
https://github.com/google/iree/blob/main/iree/hal/buffer_heap.c#L60

Need to return `status` :)

**Comment by benvanik** [comment]
Hah! Awesome! Will send a fix 1 sec.

**Comment by benvanik** [comment]
(added to https://github.com/google/iree/pull/6809)

**Comment by hcindyl** [comment]
Get the useful status message with #6809. Need to fix one `iree_status_is_ok(status)` in our own application.
```
iree/iree/base/allocator.c:89: RESOURCE_EXHAUSTED; system allocator failed the request; while invoking native function hal.allocator.allocate; while calling import;
```
Thanks for the help!

**Comment by benvanik** [comment]
np nice find on the bad heap buffer returns! Also kicked me into fixing the ELF loader stuff you pointed out the other day :)
