### ISSUE TITLE
Complete lit tests for the VM to EmitC Conversion/Target

### ISSUE THREAD

**Issue by simon-camp** [google/iree#6858]
Some of the vm ops supported and tested under `iree/vm/test` are missing lit tests under `iree/compiler/Dialect/VM/Conversion/VMToEmitC/test` and/or `iree/compiler/Dialect/VM/Target/C/test` respectively. 

For example
- `vm.global.ref`
- `vm.global.load.ref`
- `vm.global.store.ref`

**Comment by marbre** [comment]
We have tests in `iree/compiler/Dialect/VM/Conversion/VMToEmitC/test` for these ops now. Do you think we'll need to add tests for the ops listed above to `iree/compiler/Dialect/VM/Target/C/test` as well or is this issue outdated?

**Comment by marbre** [comment]
After internal discussion, we agreed that this issue is already solved.
