### ISSUE TITLE
Fuse together tensor slices consumed by linalg ops.

### ISSUE THREAD

**Issue by benvanik** [google/iree#6903]
[tf.split](https://www.tensorflow.org/api_docs/python/tf/split) is a common construct in the models we care about (used inside of LSTM cells for example), and after lowering out of mhlo that looks like this:
```
  %58 = tensor.extract_slice %57[0, 20] [1, 10] [1, 1] : tensor<1x40xf32> to tensor<10xf32>
  %60 = tensor.extract_slice %57[0, 10] [1, 10] [1, 1] : tensor<1x40xf32> to tensor<10xf32>
  %61 = tensor.extract_slice %57[0, 0] [1, 10] [1, 1] : tensor<1x40xf32> to tensor<10xf32>
```

Due to linalg basically eating up all of the rest of the LSTM this leaves us with these 3 slices each passed in as operands to a single linalg.generic! This later on in lowering results in additional buffer work, bindings required to pass the unique buffers in, etc. It also means that the dispatch region misses an entire loop dimension that it could be operating over.

Having a canonicalization that folded slices back together by propagating the slice ranges to the linalg operand ranges may kick off a good chain of existing canonicalizations. Or failing that we can canonicalize `flow.dispatch.workgroups` to pull in slices, however that'd strictly be benefiting runtime binding count but wouldn't help in the actual code that is generated.

This example is from `iree/test/e2e/models/unidirectional_lstm.mlir`.

**Comment by cycheng** [comment]
Hi @benvanik 
I would like to try this issue, could you give me some more hints and direction? I will try to figure out the details. Thanks :)

> Having a canonicalization that folded slices back together by propagating the slice ranges to the linalg operand ranges

I guess I will add another fold hook in ExtractSliceOp::fold, but given the following input what is the expected result after the canonicalization fusion? (Sorry for the noob question)

```mlir
  %95 = linalg.generic {..}

  %96 = tensor.extract_slice %95[0, 20] [1, 10] [1, 1] : tensor<1x40xf32> to tensor<1x10xf32>
  %97 = linalg.init_tensor [1, 10] : tensor<1x10xf32>
  %98 = linalg.generic {..} ins(%96, %cst_13 :..) outs(%97 : ..) { .. }

  %107 = tensor.extract_slice %95[0, 10] [1, 10] [1, 1] : tensor<1x40xf32> to tensor<1x10xf32>
  %108 = linalg.init_tensor [1, 10] : tensor<1x10xf32>
  %109 = linalg.generic {..} ins(%107, %cst_13 :..) outs(%108 : ..) {..}

  ...
```

**Comment by benvanik** [comment]
Good question :)
From discord:

I was trying to get an IR capture to better explain but it looks like there was a regression and now things aren't fusing very well so it's hard to see ;(

But from the older IR where it did fuse, dispatch 13 here: https://gist.github.com/benvanik/e2bca20c15f7b878523657f3ff7dde7e#file-0_unidirectional_lstm-mlir-L507 captures slice %27, %30, %32, and %37 (through reshapes), and then pops them all out: https://gist.github.com/benvanik/e2bca20c15f7b878523657f3ff7dde7e#file-0_unidirectional_lstm-mlir-L380-L393

The intent would be that since all those are originally sliced from the same %26 we could just pass in %26 to the dispatch and have it slice out on the inside. The reason is that instead of spending any time doing all the slicing work on the host, setting up the unique bindings, dealing with copy-on-write semantics, etc we could sink that into the dispatch and let it slice in there
(basically, the fewer inputs/outputs we have to manage the better).

I suspect this is best modeled as a flow.dispatch.workgroups canonicalization (maybe) as it's easy to move things across that boundary.

So %44 would be captured instead of %56 and then the %arg4 load would have updated offsets/sizes/etc to match the %44 slice: 
```mlir
  %55 = flow.tensor.slice %44[%c0, %c30 for %c1, %c10] : tensor<1x40xf32> -> tensor<1x10xf32>
  %56 = flow.tensor.reshape %55 : tensor<1x10xf32> -> tensor<10xf32>
  %57 = flow.dispatch.workgroups[%c10, %c1, %c1](%37, %41, %56, %52) : (tensor<10xi1>, tensor<10xf32>, tensor<10xf32>, tensor<10xf32>) -> tensor<10xf32> =
      (%arg2: !flow.dispatch.tensor<readonly:10xi1>, %arg3: !flow.dispatch.tensor<readonly:10xf32>, %arg4: !flow.dispatch.tensor<readonly:10xf32>, %arg5: !flow.dispatch.tensor<readonly:10xf32>, %arg6: !flow.dispatch.tensor<writeonly:10xf32>) {
      ...
      %68 = affine.min affine_map<(d0, d1) -> (d0, -d1 + 10)>(%workgroup_size_0, %arg7)
      %69 = flow.dispatch.tensor.load %arg4, offsets = [%arg7], sizes = [%68], strides = [1] : !flow.dispatch.tensor<readonly:10xf32> -> tensor<?xf32>
```

but we probably need to get some more examples together to really know if it's best there or as part of the DispatchLinalgOnTensors pass. Looking at the above it's linalg-agnostic and could be used regardless of whether we are dispatching linalg ops, but it may be easier to do it during the linalg pass as pulling in producers is something it already does.

**Comment by MaheshRavishankar** [comment]
This particular issue is fixed now in `unidirectional_lstm` test. Closing
