### ISSUE TITLE
Error in lowering TF HUB Masked RCNN model using iree-import-tf

### ISSUE THREAD

**Issue by ArunaKote** [google/iree#6920]
Added model signature to model using below code:

import tensorflow as tf
import tensorflow_hub as hub

model_url = "https://tfhub.dev/tensorflow/mask_rcnn/inception_resnet_v2_1024x1024/1"
loaded_model = hub.load(model_url)
call = loaded_model.__call__.get_concrete_function(
tf.TensorSpec(shape=(1, 1024, 1024, 3), dtype=tf.uint8))
signatures = {'predict': call}
tf.saved_model.save(loaded_model,'/data/aruna/maskedrcnn/iree', signatures=signatures)

Then used /data/aruna/iree/integrations/tensorflow/bazel-bin/iree_tf_compiler/iree-import-tf -tf-import-type=savedmodel_v1 -tf-savedmodel-exported-names=predict /data/aruna/maskedrcnn/iree --print-ir-before-all&>2 -o sample.mlir

:0: error: loc(callsite(callsite(callsite("BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/Select@__inference___call___42606" at "StatefulPartitionedCall@__inference_restored_function_body_108980") at "StatefulPartitionedCall@__inference_signature_wrapper_110151") at "StatefulPartitionedCall")): currently unsupported operand types: 'tensor<?xf32>' and 'tensor<300xf32>'
:0: note: loc("StatefulPartitionedCall"): called from
Running iree-import-tf TF import pass pipeline failed

I have attached log file
[iree_log.txt](https://github.com/google/iree/files/7083440/iree_log.txt)

**Comment by ArunaKote** [comment]
When I tried to create tflite model for the saved_model got error .Attached error log.
[tflite_error_logs.txt](https://github.com/google/iree/files/7083312/tflite_error_logs.txt)

**Comment by GMNGeoffrey** [comment]
Based on the error message, I believe this is coming from shape inference in MHLO (you could use `--mlir-print-stacktrace-on-diagnostic` to confirm, see https://mlir.llvm.org/getting_started/Debugging/): https://github.com/tensorflow/tensorflow/blob/6758f54d3e524f86a3608ae0c2e4e76ae31bfa3f/tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/IR/hlo_ops.cc#L2601

So basically this is a TF bug/missing functionality, though we do quite frequently contribute to that part of it

Is `tflite_convert` an IREE tool?

But yeah, overall seems like StatefulPartitionedCall is not supported by any of the TF frontends

It does seem like shape inference should be pretty simple there. Looks like @lucyrfox has a TODO to expand it and maybe there's an easy drop-in replacement function that could be used now.

**Comment by ArunaKote** [comment]
tflte_convert is not a IREE tool. As suggested https://github.com/google/iree/issues/6893 to check model whether it can be run in tflite.

**Comment by dinkdeep** [comment]
Hi @lucyrfox do we have some thing for that .

**Comment by ArunaKote** [comment]
I have attached log of 
[log.txt](https://github.com/google/iree/files/7088971/log.txt)
  /data/aruna/iree/integrations/tensorflow/bazel-bin/iree_tf_compiler/iree-import-tf -tf-import-type=savedmodel_v1 -tf-savedmodel-exported-names=predict /data/aruna/maskedrcnn/iree -mlir-print-stacktrace-on-diagnostic -o sample_hlo.mlir

**Comment by GMNGeoffrey** [comment]
Ah it looks like maybe @hanhanW is already looking into this for you? When filing issues, GitHub unfortunately doesn't allow non-collaborators to assign issues, but if there's already someone involved we'd appreciate you @'ing them. I get assigned all issues by default so that we don't miss things (it's a great triage mechanism :-P), but am not always the best one to look into it.

**Comment by hanhanW** [comment]
Yes, I looked into it last Friday, and asked @ArunaKote to file another issue for tracking this model.

RE tflite stuff: I think most of time, if you can't run this in xla/tflite you probably can't run it in iree. There are weird things in #6893, so I asked @ArunaKote to make sure if it is TFLite compatible.

For this model, the first question is, does it use dynamic shapes in the model?

If not, my experience is that we miss some patterns in type inference on TF side. You will have to look into the IR (after TFShapeInferencePass), and see which pattern is not supported.

E.g., I found a missing inference for tf.fill op before, and contributed to tensorflow repo. You probably will end up with the same place.

https://github.com/tensorflow/tensorflow/commit/398181d5965fcf7ce7be13f614c701bfa2724f15#diff-9da012ec84a56e3ee9d8cbabb407bed9d71d1a2bea836404ce7dd031dc065fef

**Comment by ArunaKote** [comment]
some ops in the model contains dynamic shapes.

**Comment by GMNGeoffrey** [comment]
@powderluv I think you are looking into MCRNN? Could you take a look at this and the two related issues? https://github.com/google/iree/issues/6956 and https://github.com/google/iree/issues/6893. It would be helpful to have it documented somewhere that this is known to not work but is on the roadmap. I think these are all missing functionality in TF upstream, but still affects our ability to lower these models
