### ISSUE TITLE
Setup CI/release automation for iree-compiler-api

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#6958]
The new `llvm-external-projects/iree-compiler-api` project is the the new home of IREE's compiler API and is what we should be shooting for releasing (it will completely replace the current IREE compiler wheels when ready). There is still a bit of work to implement the existing compiler API in here (largely going to be done with `cp`) so it is a drop-in/strict improvement.

This version brings several additional features:

* Full Python and C-API for the IREE compiler (based on the MLIR Python and C APIs - and interopping with them)
* In process compilation
* Embeddable into other LLVM projects
* Full Python builder APIs for in-process construction/compilation of IR (in all dialects supported by IREE)
* Has a real `setup.py` and follows normal Python conventions for wheel building

This is the basis of new integrations being done, such as JAX.

I don't have any CI on it yet, so preserving the build instructions for posterity:

## Building manylinux wheels locally

```
./build_tools/python_deploy/manylinux_foreach_py.sh ./llvm-external-projects/iree-compiler-api/build_tools/build_python_wheels.sh
./build_tools/python_deploy/audit_wheels.sh \
     ./llvm-external-projects/iree-compiler-api/wheels/iree_compiler_api-*.whl
```

**Comment by GMNGeoffrey** [comment]
Is this fixed?
