### ISSUE TITLE
Set up a CI for gcc

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#6959]
GCC (system compilers) are used for all distributable artifacts on Linux (esp since things like Python source builds can't make the compiler assumption). We don't have a CI for it and should.

**Comment by ScottTodd** [comment]
Some notes for implementation:

To leverage our existing Docker images + CI pipelines, we'd have to override what we set in the base Docker image:
https://github.com/google/iree/blob/accc5230038a55a02584239478a2addaf7b462cc/build_tools/docker/base/Dockerfile#L9-L11

I'd suggest putting another entry in the ["build configurations" pipeline](https://buildkite.com/iree/iree-build-configurations) for organization (I wouldn't expect the gcc build to have major differences in test coverage or runtime behavior, so just running a build with no tests should provide enough coverage):
https://github.com/google/iree/blob/accc5230038a55a02584239478a2addaf7b462cc/build_tools/buildkite/cmake/build_configurations.yml#L8-L15
using a script like one of these:
* https://github.com/google/iree/blob/main/build_tools/cmake/build_tracing.sh
* https://github.com/google/iree/blob/main/build_tools/cmake/rebuild.sh
* https://github.com/google/iree/blob/main/build_tools/cmake/build_host_install.sh

**Comment by GMNGeoffrey** [comment]
Seems like we must be using a docker image for the release pipeline, so should be able to use that.

**Comment by stellaraccident** [comment]
It's a manylinux image with rhel patched dev set. You're welcome to use it
- but it is a pita to extend and patch with modern tools.

Why not just use the regular docker container and set either the cmake
compiler flags to GCC or set the env vars in whatever script kicks off the
build?

**Comment by GMNGeoffrey** [comment]
Well the thing we actually care about is being able to build the release, so it seems like we should just build in the same image. But we can also use whatever gcc is in the base ubuntu18.04 that our docker images are based on

**Comment by GMNGeoffrey** [comment]
And with that approach we have a failure:

```
/usr/bin/g++    -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -w -fdiagnostics-color -ffunction-sections -fdata-sections -DC
XX_SUPPORTS_WERROR_GLOBAL_CONSTRUCTOR -fPIE   -Werror -Werror=global-constructors -std=c++14 -o CMakeFiles/cmTC_ee7d9.dir/src.cxx.o -c src.cxx                
cc1plus: error: -Werror=global-constructors: no option -Wglobal-constructors
```

Apparently the image has gcc 7, whereas your manylinux image has gcc 9. OTOH when I try to run with your manylinux image it's all upset about being unable to find Python3, which we apparently need for the compiler :grimacing: I don't really feel like supporting old GCC versions for no reason or debugging cmake python detection. I'll make a new image

**Comment by stellaraccident** [comment]
They keep updating the devtoolset in the upstream manylinux... I think it
is in 10 now but that is not pinned. In any case, a moving target. The
manylinux image has all python versions installed under /opt/python. One
needs to be selected and added to the path.

I feel like at this point, gcc9 is as far back as we should go.
