### ISSUE TITLE
Deprecate or upstream `affine.min` canonicalizations in IREE

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#6974]
By my count there are three separate `affine.min` canonicalizations that are used in IREE. 
- [`AffineMinCanonicalizationPattern`](https://github.com/google/iree/blob/aa64b7d1d0a99bf5253062c961a3bd072d181205/iree/compiler/Codegen/Transforms/AffineMinCanonicalization.cpp#L85)
- [`AffineMinSCFCanonicalizationPattern`](https://github.com/google/iree/blob/aa64b7d1d0a99bf5253062c961a3bd072d181205/iree/compiler/Codegen/Transforms/AffineMinDistributedSCFCanonicalization.cpp#L148)
- [`FoldAffineMinOverProcessorID`](https://github.com/google/iree/blob/aa64b7d1d0a99bf5253062c961a3bd072d181205/iree/compiler/Codegen/SPIRV/SPIRVFoldGPUProcessorIDUses.cpp#L155)

Also closely related to this is

- [`RemoveTripOneLoopPattern`](https://github.com/google/iree/blob/aa64b7d1d0a99bf5253062c961a3bd072d181205/iree/compiler/Codegen/SPIRV/SPIRVRemoveOneTripTiledLoops.cpp#L74)

Apart from being redundant, these are all AFAICS unnecessary. The problem that these complex canonicalization patterns are trying to solve is that linalg tiling generates the following code pattern

```
scf.for %iv = %lb to %ub step %ts {
  %actual_ts = affine.min affine_map<(d0)[s0, s1] -> (s0, s1 - d0)>(%iv)[%ts, %ub]
  ...
}
```

This accounts for the partial tiles when the problem size is not a multiple of tile size. For the cases of interest in IREE, the tile size always divides the problem size. In such cases, the presence of `affine.min` result in the computation within the tiled loop body to have `?` in it shapes. This hampers vectorization which would kill performance. All these patterns above are trying to look for these complex code patterns involving loop bounds, and processor ids/counts when tile + distribute is used. AFAICS this is unnecessary. The real issue is the determination of whether partial tiles exist given a loop bounds and the tile size. An alternative representation of the code would be

```
scf.for %iv = %lb to %ub step %ts {
  %mod = remi_unsigned %ub, %ts : index
  %cond = cmpi, "eq", %mod, %c0 : index
  %partial_ts = affine.min affine_map<(d0)[s0, s1] -> (s0, s1 - d0)>(%iv)[%ts, %ub]
  %actual_ts = select %cond, %ts, %partial_ts
  ...
}
```
When the `%ts` and `%ub` are static and the `%mod == 0`, the whole calculation canonicalizes to `%actual_ts == %ts`. I have prototyped this and this works as expected. There hasn't been an agreement on whether this should be pushed to core or in what form, so this has been known for a while, but hasnt been resolved. Once the above (or an equivalent) way of expressing the tile size used has been plumbed through, all of the above patterns can be deprecated.

**Comment by antiagainst** [comment]
`RemoveTripOneLoop` is gone after https://github.com/google/iree/pull/7214.

Just wanted to note that `FoldAffineMinOverProcessorID` is slightly different than the others. It's meant for handling the indexing maps for convolution inputs, which typically are of the form `affine_map<(d0) -> (<tile-size>, <dim-size> - d0 * <stride>)>(%<processor-id>)` after tiling. So it's different than matmul ops, where we have `(d0) -> (<tile-size>, <dim-size> - d0)`. 

Note that `<dim-size> - d0 * <stride>` is a linear expression, so by definition it's bound between the two extremes of `d0`. That's how  `FoldAffineMinOverProcessorID` folds such `affine.min` ops: it plugs `d0`'s min (`0`) and max (`<processor-count> - 1`) value into the linear expression and get the range there. If the range is >= `<tile-size>`, then we can prove that the `affine.min` ops can be canonicalized into `<tile-size>` entirely.

Just logging this down as details given that we are developing patterns upstream to replace them. These details might be useful.

**Comment by antiagainst** [comment]
#7564 adds patterns that use upstream utilities and should be sufficient to replace existing ones. It removes `FoldAffineMinOverProcessorID`; but it does not remove `AffineMinCanonicalizationPattern` and `AffineMinSCFCanonicalizationPattern`, which is still in use in LLVM CPU/GPU. Will leave that to @ThomasRaoux to verify and remove.
