### ISSUE TITLE
Error in lowering tf.where and tf.TopKV2

### ISSUE THREAD

**Issue by ArunaKote** [google/iree#7049]
I am taking test case of tf.where ,tf.TopKV2
[top_where.zip](https://github.com/google/iree/files/7169547/top_where.zip)
and trying to lower to mhlo using iree-import-tf.But it failed 
<unknown>:0: error: loc(callsite(callsite("TopKV2@__inference___call___20" at "StatefulPartitionedCall@__inference_signature_wrapper_33") at "StatefulPartitionedCall")): 'tf.TopKV2' op : unlegalized TensorFlow op still exists
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite("TopKV2@__inference___call___20" at "StatefulPartitionedCall@__inference_signature_wrapper_33") at "StatefulPartitionedCall")): see current operation: %6:2 = "tf.TopKV2"(%5, %2) {device = "", sorted = true} : (tensor<?xi64>, tensor<i32>) -> (tensor<1xi64>, tensor<1xi32>)
<unknown>:0: error: loc(callsite(callsite("Where@__inference___call___20" at "StatefulPartitionedCall@__inference_signature_wrapper_33") at "StatefulPartitionedCall")): 'tf.Where' op : unlegalized TensorFlow op still exists
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite("Where@__inference___call___20" at "StatefulPartitionedCall@__inference_signature_wrapper_33") at "StatefulPartitionedCall")): see current operation: %4 = "tf.Where"(%3) {device = ""} : (tensor<6xi1>) -> tensor<?x1xi64>
<unknown>:0: error: The following Tensorflow operations still remain:
        tf.TopKV2 (count: 1)
        tf.Where (count: 1)

I am attaching python and log files

**Comment by sun2011yao** [comment]
@ArunaKote Hi， Have you solved this problem?  I ran into the same problem.
<unknown>:0: error: The following illegal operations still remain:
	tf.Where (count: 1)

**Comment by GMNGeoffrey** [comment]
Hi @sun2011yao I made a general comment about this in https://github.com/google/iree/issues/7045#issuecomment-920426329 (unfortunately GitHub doesn't seem to have a way to post a comment to many issues at once). These failures to lower TF ops likely mean a missing lowering in upstream TF. That's not something within the purview of the IREE team (though we do sometimes make contributions there). You should check if this issue also occurs when using the TF->XLA MLIR-based bridge, without the old XLA-path fallback enabled (https://github.com/tensorflow/tensorflow/blob/5cbf38a7ca90d9a5e46d5e1c0ed451325ba6b832/tensorflow/compiler/mlir/xla/transforms/xla_legalize_tf_passes.td#L56). If not, then you could file an issue in https://github.com/tensorflow/tensorflow. If you find that  it does work along this path, then there may be something IREE isn't hooking into properly and please open an issue against us, but I don't see a lowering for tf.Where, so I suspect that is not the case.

**Comment by sun2011yao** [comment]
@GMNGeoffrey OK，thank you
