### ISSUE TITLE
Fix -iree-vm-bytecode-module-strip-symbols=true to strip internal functions.

### ISSUE THREAD

**Issue by hcindyl** [google/iree#7063]
Add `-iree-vm-bytecode-module-strip-symbols=true` in `iree-translate` causes execution failure

In `iree/samples/simple_embedding/simple_embedded_dylib`
```
$ ./simple_embedding_dylib 
/usr/local/google/home/hcindyl/Projects/iree-dev/iree/iree/vm/bytecode_module.c:166: INVALID_ARGUMENT; mismatched internal_functions/function_descriptors vectors (0 != 2)
```

**Comment by benvanik** [comment]
Darn, the reflection info is currently embedded on internal function defs - it should be on exports (ended up there due to weird reasons) - I'll work on fixing that so we can drop the table.
