### ISSUE TITLE
ConvertMHLOToLinalgExt Failed :mhlo.sort to linalg_ext.sort

### ISSUE THREAD

**Issue by ArunaKote** [google/iree#7090]
I am trying to understand tf.NonMaxSuppressionV4 lowering in iree with static shapes.I have attached tf,hlo and iree log file.
For tf->HLO I used:tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-opt  -xla-legalize-tf-with-tf2xla=device-type=XLA_CPU_JIT  tf.mlir 
The output HLO I try to run using :
/data/aruna/iree-latest/iree-build/iree/tools/iree-run-mlir --iree-input-type=mhlo -iree-hal-target-backends=dylib-llvm-aot -iree-flow-dispatch-formation-enable-operand-fusion -iree-flow-dispatch-linalg-on-tensors-tile-sizes="0,0,0,0" -print-ir-before-all -print-ir-after-all  hlo.mlir &>out.mlir
Got error as :loc(callsite("hlo.mlir split at line #1":19:13 at "hlo.mlir split at line #1":2:3)): error: 'linalg_ext.sort' op dimension must be within (0, 1]

Thanks
[tf.log](https://github.com/google/iree/files/7194834/tf.log)
[hlo.log](https://github.com/google/iree/files/7194832/hlo.log)
[iree .log](https://github.com/google/iree/files/7194833/iree.log)

**Comment by stellaraccident** [comment]
Looks like an underimplemented of the sort lowering. That work was just done recently. Hanhan: do you have any idea on what is going on here?

**Comment by hanhanW** [comment]
Looks like there is a sort op not lowered correctly.

```mlir
    %12:2 = "mhlo.sort"(%arg1, %11) ( {
    ^bb0(%arg4: tensor<f32>, %arg5: tensor<f32>, %arg6: tensor<i32>, %arg7: tensor<i32>):  // no predecessors
      %92 = "mhlo.compare"(%arg4, %arg5) {compare_type = "TOTALORDER", comparison_direction = "GT"} : (tensor<f32>, tensor<f32>) -> tensor<i1>
      "mhlo.return"(%92) : (tensor<i1>) -> ()
    }) {dimension = -1 : i64, is_stable = false} : (tensor<3xf32>, tensor<3xi32>) -> (tensor<3xf32>, tensor<3xi32>)
```

I think we miss the case that `dimension = -1`. This is defined in XLA operation semantics, so it should be an easy fix, I'll send it out soon

> If no dimension number is provided, then the last dimension is chosen by default.

**Comment by hanhanW** [comment]
Landed the patch upstream. Will get fixed in the next integration.

https://github.com/tensorflow/tensorflow/commit/956f5c8b826652a5d1f0dc315f38bc30ba42dd0b#diff-c00bdbe9d983f1358e442fa0ea5ea984046931192394e63bcbae65edc1d36f39
