### ISSUE TITLE
`iree-translate` failed with dynamic shapes when lowering Resnet18 to CUDA backend

### ISSUE THREAD

**Issue by hunbssfy** [google/iree#7187]
**Describe the bug**
I used Npcomp to lower a Resnet18 model. The first dimension (batch) is unknown at this stage. 
I've noticed that there is this fix (https://github.com/google/iree/pull/6957) to the CUDA backend to support dynamic shapes so I want to give it a try. So I used iree-translate to compile the model.

However, I got this error during compilation:

> iree-translate: /mnt/workspace/holmes/third_party/llvm-project/mlir/include/mlir/IR/Types.h:235: bool mlir::Type::isa() const [U = mlir::LLVM::LLVMVoidType]: Assertion `impl && "isa<> used on a null type."' failed.
> PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.

The stack trace is here:https://gist.github.com/hunbssfy/a8a8659352c7df2877cb004c5c5a376e

I debugged a little bit and I found that there are three `hal.interface.bindings` in the symbol-table before `ConvertToNVVM` while in a normal state there should be two (the other one is a constant rather than a function argument...), in other words, the number of `hal.interface.bindings` and `hal.interface.bindings.subspan` mismatches in the IR. I posted my IR before convert-to-nvvm here: https://gist.github.com/hunbssfy/eac40ad3c3fd1dd6893ccbac5b79ade3

And this caused there are three "Arg mappings" generated here: https://github.com/google/iree/blob/7bc297e9fc8bcc7f291d84e8854a44d5161f2cd6/iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.cpp#L169 during a walk of the symbol table. But only two elements in `llvmInputTypes` were populated when visiting all the `hal.interface.bindings.subspan` afterwards: https://github.com/google/iree/blob/7bc297e9fc8bcc7f291d84e8854a44d5161f2cd6/iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.cpp#L171
The one left unmodified was a NULL type which lead to verification failure here: https://github.com/google/iree/blob/7bc297e9fc8bcc7f291d84e8854a44d5161f2cd6/iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.cpp#L200

**To Reproduce**
**I am not using the latest iree build, I am using this tag: snapshot-20210914.525**
1. Build iree
2. Download the Resnet18 model: https://drive.google.com/file/d/1AwdJatbhAaBlFoYx-UcFd4vj2wN37D8g/view?usp=sharing

3. ` iree-translate resnet18_batch_unknown.mlir --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=cuda --iree-mlir-to-vm-bytecode-module --mlir-print-debuginfo --mlir-disable-threading --mlir-print-op-on-diagnostic=false --mlir-elide-elementsattrs-if-larger=100 --print-ir-after-failure --print-ir-before=iree-convert-to-nvvm`

And @ThomasRaoux Could you help me take a look? Thanks!

**Comment by stellaraccident** [comment]
This is a really nice big report. Thank you for the details! Making a provisional assignment based on the stack trace.

**Comment by ThomasRaoux** [comment]
Thanks for the detailed bug report and for finding the root cause. This made it trivial to fix. https://github.com/google/iree/pull/7215 solves the problem
