### ISSUE TITLE
Unable to flatten dynamic shapes in FlattenMemRefSubspan

### ISSUE THREAD

**Issue by hanhanW** [google/iree#7229]
After enabling operand fusion by default, I observed that there are couple VMVX tests failed. Because there are some cases not handled in flattening memref pass.

To repro: `iree-translate -iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vmvx -iree-input-type=tosa iree/test/e2e/tosa_ops/fully_connected.mlir --iree-flow-dispatch-formation-enable-operand-fusion=true -o /tmp/z.vmfb`

The IR before the pass: https://gist.githubusercontent.com/hanhanW/fefb3b12fe09ef36e9fdd5ed2d7c2c82/raw

Repro with `iree-opt`: `build-tracy/iree/tools/iree-opt --iree-codegen-flatten-memref-subspan before_flatten.mlir`

**Comment by MaheshRavishankar** [comment]
@antiagainst any quick ideas here?

**Comment by antiagainst** [comment]
We have `memref.alloca` in the IR. `memref.alloca` and `memref.alloc` is [not supported](https://github.com/google/iree/blob/8a4bae2/iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir#L158-L168) right now. So it's a missing feature. Should be easy to implement though. Let me throw in a pattern.

**Comment by MaheshRavishankar** [comment]
ok, probably need to look into why there is an alloca

**Comment by MaheshRavishankar** [comment]
@hanhanW could you upload the dump after all?

**Comment by MaheshRavishankar** [comment]
probably needs a bufferization fix

**Comment by hanhanW** [comment]
oops, I thought I didi it. One interesting thing is that vulkan pass the test, but VMVX not. Seems that Lei fixes the issue, I'll review the PR.

**Comment by hanhanW** [comment]
Here is the IR dump: https://gist.githubusercontent.com/hanhanW/2ffd41ca42f0a2a6ec62c0a1fc8e2b30/raw

**Comment by MaheshRavishankar** [comment]
Thanks! I think the issue here is the second level of tiling. In SPIR-V bufferization is done ahead of time. THis also means we have an alloca on the CPU side for the same code. Needs investigation in the bufferization.
