### ISSUE TITLE
Linker error on macOS Catalina

### ISSUE THREAD

**Issue by OliverUrbann** [google/iree#724]
I'm trying to compile iree on macOS Cataline following the Linux doc and
```
cmake -DIREE_BUILD_COMPILER=ON -DIREE_BUILD_TESTS=ON -DIREE_BUILD_SAMPLES=OFF -DIREE_BUILD_DEBUGGER=OFF ..
```

Then `make` results in:

```
ld: unknown option: --whole-archive
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ 37%] Built target LLVMBitReader
make[2]: *** [iree/tools/iree-tblgen] Error 1
make[1]: *** [iree/tools/CMakeFiles/iree_tools_iree-tblgen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by marbre** [comment]
We need to support `-Wl,-force_load` to build on macOS. Can you test to build the branch https://github.com/iml130/iree/tree/cmake-macos in our fork?

**Comment by ScottTodd** [comment]
Thanks for the report! Yep, we'll need a macOS branch in the `ALWAYSLINK` handling. Thanks for sketching that out.

As far as I know, we haven't had anyone else try building on macOS yet, but we'll want the project stable there as well. We can also look into getting continuous builds/tests running on macOS, probably after Windows. The configuration for Kokoro is unfortunately mostly Google-internal and we chose to focus on Kokoro over GitHub Actions / TravisCI / CircleCI / etc. for various reasons, so someone on our end (probably me or @GMNGeoffrey) will need to set that up. If continuous builds on macOS or Windows are important to you, please speak up and we can prioritize them.

**Comment by marbre** [comment]
I chatted offline with Oliver. The patches in our fork relax the situation, but aren't sufficient for a successful build. There are still some in-project targets/libraries that cannot be linked. We will try to figure it out. So far, there is no need for continuous builds on macOS.
