### ISSUE TITLE
CTest: run on CI

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#732]
I've got 5 (6 if you include https://github.com/google/iree/issues/731) tests failing locally at the moment. I think we can exclude these with `-E` and start running everything on presubmit. Might require throwing some additional resources at the problem so it doesn't hold things up too much. I'd like to stop having to test this manually though.

@marbre: It looks like you've been working towards this. Anything to add?

```shell
ctest -E "(iree_base_file_io_test|iree_compiler_Translation_SPIRV_LinalgToSPIRV_test_pw_add.mlir.test|iree_tools_vm_util_test|iree_tools_test_multiple_args.mlir.test|iree_tools_test_scalars.mlir.test|iree_tools_test_simple.mlir.test)"
```

**Comment by GMNGeoffrey** [comment]
Running in a kokoro VM, I actually have an additional failure: "iree_hal_vulkan_dynamic_symbols_test"

**Comment by GMNGeoffrey** [comment]
Well I just discovered the `-j` flag for ctest, so I think we're ok with additional 9 seconds to run this, which is how long iree_vm_bytecode_module_benchmark takes (although probably we shouldn't be running 10 seconds of benchmarking by default...)

**Comment by marbre** [comment]
:+1: LGTM
