### ISSUE TITLE
TensorFusion produces invalid IR when executing on the rosetta model

### ISSUE THREAD

**Issue by rsuderman** [google/iree#7333]
**Describe the bug**
Tensor fusion produces invalid linalg operations on multiple operations.

**To Reproduce**

1. Download sample model [tosa.zip](https://github.com/google/iree/files/7341901/tosa.zip)
2. Unzip the contained tosa.mlir
3. Compile using the tosa import path
```
ireec tosa.mlir \
	--iree-input-type=tosa \
	--iree-vm-bytecode-module-output-format=flatbuffer-binary \
	--iree-hal-target-backends=dylib-llvm-aot \
	-o=module.bytecode \
	--iree-mlir-to-vm-bytecode-module \
	--mlir-print-debuginfo \
	--mlir-print-op-on-diagnostic=false \
	--print-ir-before-all \
	--mlir-elide-elementsattrs-if-larger=8 \
	--mlir-disable-threading
```
4. Observe that the verification fails after the tensor fusion pass but is valid before hand.

**Comment by MaheshRavishankar** [comment]
This should be fixed by https://reviews.llvm.org/D117908
