### ISSUE TITLE
Build EmitC as part of the Bazel build

### ISSUE THREAD

**Issue by marbre** [google/iree#7345]
To build EmitC as part of the Bazel build, BUILD files corresponding to the CMake files listed below need to be modified/created.

The build configuration replies on two main dependencies `MLIREmitC` (available in Bazel via the [llvm-project-overlay](https://github.com/llvm/llvm-project/blob/e356027016c6365b3d8924f54c33e2c63d931492/utils/bazel/llvm-project-overlay/mlir/BUILD.bazel#L1818-L1835)) and `emitc::TranslateToCpp`. The latter is configured in [third_party/mlir-emitc/CMakeLists.txt](https://github.com/google/iree/blob/main/build_tools/third_party/mlir-emitc/CMakeLists.txt) and is **not equivalent** to `TargetCpp` in upstream. It needs an equivalent on the Bazel side.
Furthermore, the define `IREE_HAVE_EMITC_DIALECT`, defined in [iree_copts.cmake](https://github.com/google/iree/blob/d54543ee56ec2867b0e09cba10d4f1993f88136c/build_tools/cmake/iree_copts.cmake#L401-L403), needs to be ported to Bazel.

#### Build configuration:
`VMToEmitC`, depends on `MLIREmitC`

- [x] [iree/compiler/Dialect/VM/Conversion/VMToEmitC/CMakeLists.txt](https://github.com/google/iree/blob/main/iree/compiler/Dialect/VM/Conversion/VMToEmitC/CMakeLists.txt)

`C` target, depends on `emitc::TranslateToCpp` and `VMToEmitC`
- [x] [iree/compiler/Dialect/VM/Target/CMakeLists.txt](https://github.com/google/iree/blob/main/iree/compiler/Dialect/VM/Target/CMakeLists.txt)
- [x] [iree/compiler/Dialect/VM/Target/C/CMakeLists.txt](https://github.com/google/iree/blob/main/iree/compiler/Dialect/VM/Target/C/CMakeLists.txt)

`IREEVM`, depends on `C` target
- [x] [iree/compiler/Translation/CMakeLists.txt](https://github.com/google/iree/blob/main/iree/compiler/Translation/CMakeLists.txt)

`iree-opt` and `iree-mlir-lsp-server`, depend on `MLIREmitC`
`iree-translate`, depends on `MLIREmitC` and `emitc::TranslateToCpp`
- [x] [iree/tools/CMakeLists.txt](https://github.com/google/iree/blob/main/iree/tools/CMakeLists.txt)

`module_test`, uses `iree_c_module.cmake` and thus depends on `iree-translate`
- [ ] [iree/vm/test/emitc/CMakeLists.txt](https://github.com/google/iree/blob/main/iree/vm/test/emitc/CMakeLists.txt)

EmitC samples, use `iree_c_module.cmake` and thus depends on `iree-translate`
- [ ] [iree/samples/emitc_modules/CMakeLists.txt](https://github.com/google/iree/blob/main/iree/samples/emitc_modules/CMakeLists.txt)

**Comment by GMNGeoffrey** [comment]
We don't really need `IREE_HAVE_EMITC_DIALECT` in Bazel. Just an `extra_cmake_content` to insert it
