### ISSUE TITLE
iree-benchmark-module and iree-benchmark-trace produce wildly different measurements

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#7363]
Artifact download: https://drive.google.com/file/d/1MUsZgM-MvZywjVFfa7RsaxD7PqabDbJN/view?usp=sharing

Repro:

* Download [trace_module_mismatch_repro.tgz](https://drive.google.com/file/d/1MUsZgM-MvZywjVFfa7RsaxD7PqabDbJN/view?usp=sharing) and tar xzf it
* Run: `iree-benchmark-module --driver=dylib --function_input=1x128xi32 --function_input=1x128xi32 --function_input=1x128xi32 --entry_function=predict --module_file=call_repro/module.vmfb`
* Run: `iree-benchmark-trace call_repro/calls.yaml --driver=dylib`

Note that the measurements are wildly different:

```
$ iree-benchmark-module --driver=dylib --function_input=1x128xi32 --function_input=1x128xi32 --function_input=1x128xi32 --entry_function=predict --module_file=call_repro/module.vmfb
I /usr/local/google/home/laurenzo/src/iree/iree/tools/utils/vm_util.cc:185] Creating driver and device for 'dylib'...
2021-10-15T18:29:05+00:00
Running /usr/local/google/home/laurenzo/src/iree-build/iree/tools/iree-benchmark-module
Run on (96 X 2000 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x48)
  L1 Instruction 32 KiB (x48)
  L2 Unified 1024 KiB (x48)
  L3 Unified 39424 KiB (x2)
Load Average: 0.04, 0.08, 0.09
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
BM_predict/process_time/real_time       40.6 ms          218 ms           17
```

```
$ iree-benchmark-trace call_repro/calls.yaml --driver=dylib
2021-10-15T18:29:32+00:00
Running /usr/local/google/home/laurenzo/src/iree-build/iree/tools/iree-benchmark-trace
Run on (96 X 2000 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x48)
  L1 Instruction 32 KiB (x48)
  L2 Unified 1024 KiB (x48)
  L3 Unified 39424 KiB (x2)
Load Average: 0.13, 0.10, 0.09
--------------------------------------------------------------------------
Benchmark                                Time             CPU   Iterations
--------------------------------------------------------------------------
BM_calls/process_time/real_time        164 ms          728 ms            4
```

**Comment by bjacob** [comment]
I would like to understand why there were denormals here in the first place. Is it expected given what this computation is doing or is it some uninitialized data? If denormals aren't expected in this computation then we should avoid accidentally creating them, because if we do, "just suppress denormals" is never going to be a full solution. This feature does not consistently work as expected on all CPUs, and even when it does, it only converts unexpected denormals into unexpected zeros, and unexpected zeros can give unexpected 0/0 == NaN, and some CPUs have slowness issues with NaN values too, and unlike denormals there isn't a way to "just suppress NaNs".

**Comment by stellaraccident** [comment]
Ultimately coming from some numpy manipulation. The raw buffer is passed to
iree and put in the trace.

**Comment by benvanik** [comment]
Yep - we can cross that bridge when we get to it - given that we are trying to compete with frameworks that made the fixed decision to flush in handwritten code and this issue causes confusion and invalid benchmark numbers having it default for now is appropriate.

**Comment by benvanik** [comment]
(nothing actionable here anymore)
