### ISSUE TITLE
Re-enable disabled `pow` test on dylib + embedded linking path

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#7415]
PR #7404 added support for ceilf and powf on the embedded linker path. The test for the powf function though fails with `bazel` and with `cmake-swiftshader` bots. So that test is disabled for now.

The `bazel` failure is strange cause the `.vmfb` generated by using the `iree-translate` is identical to the one generated from using `iree-translate` built with cmake. Running this `.vmfb` file using the `iree-check-module` from `bazel` fails, which using the `iree-check-module` from `cmake` passes.

(havent triaged the issue with cmake-swiftshader).

**Comment by MaheshRavishankar** [comment]
Ill post more info here shortly, but in the meantime, this removes pulling in the `powf` code.

https://github.com/google/iree/pull/7425

**Comment by MaheshRavishankar** [comment]
Leaving some brain dump of way forward here. Will probably pick this up next week.

Right now the way the `librt` IR is linked with the other generated code is by just doing a linking. That probably needs to be changed to taking the LLVM IR generated for each executable, looking at the function to see calls and explicitly clone in the functions from `librt` into the module. There are two advantages with this
1) Currently these calls to librt are not inlined. With this you can clone, it and run the optimizations again to inline the functions.
2) I have to follow up on why `powf` on MUSL for 32-bit is returning an error. That might take a while to resolve. To unblock us, we can selectively inline `powf` function only if we are compiling for 64-bit. So concretely it would mean having a separate `librt64` which contains just the `powf` that is embedded into the module if we are compiling for 64-bit target.

**Comment by benvanik** [comment]
For 1 we could check our lld settings - it should be able to perform LTO inlining and unused function stripping - if we can make it do that stuff instead just as with normal code that'd be the most robust route (just like it does if you are hand-authoring code). There's the traditional path (emitting bitcode and invoking lld) but there's also a C API we could hook into: https://llvm.org/docs/LinkTimeOptimization.html - in theory we could serialize the codegen bitcode, add both it and the librt bitcode to the lto_code_gen_t, and then have it compile and produce a native object file we pass along as normal.

Of course, having any of this working is the most important part, so really just an option for now - it may be easier to get lld to do what we need (cross-module inlining and dce) than writing that code ourselves, but if it isn't then hacking in whatever works seems like a fine first step :)

**Comment by MaheshRavishankar** [comment]
Ok, I am not opposed to that. AFAIK, thats how the libdevice stuff is linked in to CUDA device side code (but that might also be because it predates LTO and hasnt been adapted).
Ok, to avoid doing a lot of work to start with, let me just do a `librt64` that is linked in only for 64-bit architecture. That will unblock us. The actual linking can be figured out later.

**Comment by powderluv** [comment]
FWIW - I am building on OSX and pow kills the linker. Don't know why though. 

```[36/177] Generating check_dylib-llvm-aot_dylib_pow.mlir_module.vmfb
FAILED: iree/test/e2e/xla_ops/check_dylib-llvm-aot_dylib_pow.mlir_module.vmfb /Users/anush/github/iree/build/iree/test/e2e/xla_ops/check_dylib-llvm-aot_dylib_pow.mlir_module.vmfb 
cd /Users/anush/github/iree/build/iree/test/e2e/xla_ops && /Users/anush/github/iree/build/iree/tools/iree-translate -iree-mlir-to-vm-bytecode-module -mlir-print-op-on-diagnostic=false --iree-hal-target-backends=dylib-llvm-aot -iree-input-type=mhlo /Users/anush/github/iree/iree/test/e2e/xla_ops/pow.mlir -o check_dylib-llvm-aot_dylib_pow.mlir_module.vmfb -iree-llvm-embedded-linker-path="/Users/anush/github/iree/build/third_party/llvm-project/llvm/bin/lld"
ld: warning: -flat_namespace is deprecated on free standing
final section layout:
    __TEXT/__text addr=0x100003F04, size=0x000000BC, fileOffset=0x00003F04, type=1
    __TEXT/__const addr=0x100003FC0, size=0x00000040, fileOffset=0x00003FC0, type=0
    __DATA/__const addr=0x100004000, size=0x00000090, fileOffset=0x00004000, type=0
ld: b(l) ARM64 branch out of range (-4294983492 max is +/-128MB): from __tensor_dispatch_0 (0x100003F04) to _powf (0x00000000) in '__tensor_dispatch_0' from /var/folders/4s/y549893s4xd5g6lvq_w50cfc0000gn/T/pow_linked_llvm-1cbf9d.o for architecture arm64
Linking failed; escaped command line returned exit code 256:```

**Comment by MaheshRavishankar** [comment]
@powderluv this might not be related to the embedded linking?
