### ISSUE TITLE
rbe-toolchain image can't build latest swiftshader

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#7419]
https://github.com/google/iree/pull/7117 and https://github.com/google/iree/pull/6859 didn't actually update the rbe-toolchain image to use later swiftshader commits. I tried rebuilding recently and had to downgrade the swiftshader commit because swiftshader doesn't build at the newer commit. I think the issue is that the rbe-toolchain is Ubuntu 16.04 with clang 3.8. It's not finding C++17 `std::shared_mutex`:

```
/install-swiftshader/swiftshader/third_party/llvm-10.0/llvm/include/llvm/Support/RWMutex.h:100:8: error: no type named 'shared_mutex' in namespace 'std'; did you mean 'timed_mutex'?
```

Given that Ubuntu 16.04 is EOL, we're probably going to need to come up with a longer term solution. I've been postponing upgrading to Ubuntu 18.04 because RBE doesn't provide base docker images for that. But also RBE after Bazel 4 wants you to specify an egregious amount of config. It can be autogenerated and stored in GCS or something (although they recommend in source control :vomiting_face:), but I'm pondering just dropping remote execution entirely and only doing remote caching.

But anyway, for now swiftshader in the RBE containers is still at https://github.com/google/swiftshader/commit/84f5eeb6dd9b225f465f93737fa76aad7de355cf and in https://github.com/google/iree/pull/7406 I'm making the Dockerfile actually reflect that again.

**Comment by ScottTodd** [comment]
This is one of the blockers for https://github.com/google/iree/pull/8018 - we need the timeline semaphore support from https://github.com/google/swiftshader/commit/6846389f25cad4233a4bd04fd3fc6c60ae30ff35 to drop our timeline semaphore emulation. The relevant tests pass on our CI that uses CMake but fail on the CI that uses Bazel due to the different SwiftShader versions.

**Comment by GMNGeoffrey** [comment]
Please wait a bit for everything to settle before submitting things that depend on this
