### ISSUE TITLE
Start releasing binaries for Python 3.10

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#7444]
Runners recently started running with Python 3.10 when requesting Python 3.x. I've pinned them consistently to 3.8 for the time being, but we should upgrade.

* [x] Upgrade stellaraccident/manylinux2014_x86_64-bazel-3.7.2:latest docker image to head to get Python 3.10 (current version only goes up to 3.9.
* [ ] Extend the list in `build_package.yml` `CIBW_BUILD: "cp37-* cp38-* cp39-*"`
* [ ] Potentially re-pin `validate_publish_release.yaml`. Bonus points for upgrading it to a matrix and actually running some tests.

**Comment by ScottTodd** [comment]
We've had our first user (well, developer :P, [Discord conversation here](https://discord.com/channels/689900678990135345/689900680009482386/954143994353418290)) try installing with Python 3.10 only to find that we don't yet build for 3.10.

**Comment by stellaraccident** [comment]
We've long since upgraded this image for other reasons and it has 3.10 now, so I think we can just add it to the CIBW_BUILD var.

**Comment by marbre** [comment]
Seems there are no builds for Python 3.10 uploaded to https://github.com/google/iree/releases at the moment.

**Comment by ScottTodd** [comment]
Here's a recent build: https://github.com/google/iree/runs/5718146564?check_suite_focus=true

```
Build runtime wheels

build_selector: BuildSelector('cp37-* cp38-* cp39-* cp310-*' - '*-win32 *-manylinux_i686')

Building cp37-manylinux_x86_64 wheel
Building cp38-manylinux_x86_64 wheel
Building cp39-manylinux_x86_64 wheel

(no cp310-)
```

**Comment by stellaraccident** [comment]
I suspect that we need to also update the pinned cibuildwheel: `python -m pip install cibuildwheel==1.7.2`

I'll bump it to head tomorrow (just pushed a change to upgrade bazel and would only like to have one change at a time).

**Comment by ScottTodd** [comment]
Presumably we'll also need to update https://github.com/google/iree/blob/6b38136399f1705b292a3a96fb8aafe6569e3c08/bindings/python/iree/runtime/setup.py.in#L26-L30

(though note that [JAX doesn't have that yet](https://github.com/google/jax/blob/58f8e93d72492a93b4802b163d681f890dfaab7d/setup.py#L79-L83), but [TensorFlow does](https://github.com/tensorflow/tensorflow/blob/28ed5da70ccba9dc6274d457f5ce8dafde3936f5/tensorflow/tools/pip_package/setup.py#L309-L329))

**Comment by stellaraccident** [comment]
The release process has been completely reworked and as a side effect also produced 3.10 wheels. Closing.
