### ISSUE TITLE
Compiling a model for a bare-metal platform fails

### ISSUE THREAD

**Issue by freddan80** [google/iree#7563]
**Describe the bug**
I was following the steps [here](https://google.github.io/iree/deployment-configurations/bare-metal/#compile-the-model-for-bare-metal), using a few different (.tflite) models. One of them being text classifications acquired from [this example](https://colab.research.google.com/github/google/iree/blob/main/colab/tflite_text_classification.ipynb).

**To Reproduce**
The steps I used was:
1. Convert model from .tflite to .mlir
`iree-import-tflite text_classification.tflite -o text_classification.mlir`
2. Compile model
`iree/tools/iree-translate     -iree-mlir-to-vm-bytecode-module     -iree-hal-target-backends=dylib-llvm-aot     -iree-llvm-target-triple=x86_64-pc-linux-elf     -iree-llvm-debug-symbols=false     text_classification.mlir     -o text_classification.vmfb`

The second step throws the following error message:

```
text_classification.mlir:2:3: error: TensorRewriteAdaptor newValue is invalid type 'tensor<1x2xf32>'
  func @main(%arg0: tensor<1x256xi32>) -> tensor<1x2xf32> attributes {tf.entry_function = {inputs = "input_5", outputs = "Identity"}} {
  ^
iree-translate: /home/freknu01/repos/iree/iree/compiler/Dialect/HAL/Utils/TypeUtils.cpp:140: static mlir::iree_compiler::IREE::HAL::TensorRewriteAdaptor mlir::iree_compiler::IREE::HAL::TensorRewriteAdaptor::get(mlir::Location, mlir::Value, mlir::Value, mlir::ConversionPatternRewriter &): Assertion `succeeded(TensorRewriteAdaptor::verifyConstructionInvariants( loc, oldValue, newValue, rewriter))' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: iree/tools/iree-translate -iree-mlir-to-vm-bytecode-module -iree-hal-target-backends=dylib-llvm-aot -iree-llvm-target-triple=x86_64-pc-linux-elf -iree-llvm-debug-symbols=false text_classification.mlir -o text_classification.vmfb
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
```

**Additional context**
N/A

**Comment by freddan80** [comment]
Thx for the quick reply @marbre! I'll try it out this week

**Comment by hcindyl** [comment]
`-iree-input-type=tosa` is the required setting for `.tflite` input (see [instructions](https://google.github.io/iree/ml-frameworks/tensorflow-lite/#importing-models)). Depending on your CPU target, you need to adjust the llvm flags differently if compiled with `dylib-llvm-aot` backend (see different configurations in https://github.com/google/iree/blob/ec9d61fc/iree/samples/simple_embedding/CMakeLists.txt). As @marbre mentioned, we are working on arm32 backend for `dylib-llvm-aot`, but if your target is x86_64, rv32, or rv64, they should work at ToT

**Comment by freddan80** [comment]
I can confirm it worked! I ran into another issue with another network, related to depthwise conv, but I'll write a separate ticket for the if I can't figure it out. Feel free to close the ticket.

Thx @marbre and @hcindyl ! Btw, there are quite a few arguments to `iree-translate`, is there a more comprehensive documentation than `iree-translate --help` to gain an understanding what arguments I can/should/shouldn't play around with?
