### ISSUE TITLE
Bazel build is broken on the master branch.

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#757]
Broken as of https://github.com/google/iree/commit/cc1a5a0782ed4021677706181b6ae516820f8f64 .

I'm working on this with @GMNGeoffrey . We're in a tricky spot trying to keep the upstream builds passing while updating the LLVM and TF submodules, BUILD files, and CMake files on GitHub. We're hoping to get the build stable again tomorrow morning PST.

**Comment by marbre** [comment]
Do you need assistance for the CMake side?

**Comment by ScottTodd** [comment]
I wouldn't worry about it. We'll be offline this afternoon then back tomorrow to see where the dust settles upstream :)
