### ISSUE TITLE
question about the VectorizeMMT4d.cpp

### ISSUE THREAD

**Issue by jackmsye** [google/iree#7576]
hello @bjacob  firstly, thanks for your great works.

I find some misalignment between the code comments and the implementation.
https://github.com/google/iree/blob/main/iree/compiler/Codegen/Common/VectorizeMMT4d.cpp#L35 says ```This converts linalg.mmt4d with operands <1x1xM0xK0>, <1x1xK0xN0>```
however in https://github.com/google/iree/blob/main/iree/compiler/Codegen/Common/VectorizeMMT4d.cpp#L72 
the size is N0xK0

is there any problems? or Do I misunderstand the codes?

**Comment by bjacob** [comment]
Thank you for the report (yes you are right!)

Fixing it in PR #7588.
