### ISSUE TITLE
Adding new op  to HLO and add tf to HLO lowering and add it to the iree-import-tf

### ISSUE THREAD

**Issue by ArunaKote** [google/iree#7586]
I want to lower tf.leakyrelu to the new HLO op mhlo.leaky_relu. For this,
I created new op in mhlo for leakyrelu in iree/third_party/tensorflow/tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/hlo_ops.td
Then in iree/third_party/tensorflow/tensorflow/compiler/mlir/xla/transforms/legalize_tf.cc updated the lowering for tf.leakyrelu to mhlo.leakyrelu

But when I run bazel build iree_tf_compiler:importer-binaries getting error as
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/552a1865bc9b933b5dd3d8c3ed93b3cd/external/org_tensorflow/tensorflow/compiler/mlir/xla/BUILD:442:11: C++ compilation of rule '@org_tensorflow//tensorflow/compiler/mlir/xla:mlir_hlo_to_hlo' failed (Exit 1): clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 319 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 319 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/org_tensorflow/tensorflow/compiler/mlir/xla/mlir_hlo_to_hlo.cc:1274:
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/xla/operator_writers.inc:483:26: error: no member named 'LeakyRelu' in namespace 'xla'
auto xla_result = xla::LeakyRelu(Unwrap(xla_arg_0), Unwrap(xla_arg_1));
1 error generated.
Target //iree_tf_compiler:importer-binaries failed to build

Which are the files do I need to update if I want to have lowering to new hlo op.

**Comment by ScottTodd** [comment]
I'm not totally sure, but I can point out that the `include/mlir-hlo/Dialect/mhlo/IR/hlo_ops.td` path also exists in https://github.com/tensorflow/mlir-hlo/, which IREE includes at `third_party/mlir-hlo`. We redirect between those paths depending on which part of the project is getting built (to avoid dependencies on the full TensorFlow project where possible): https://github.com/google/iree/blob/2415338832472f47f20f6f499642d060502ee92d/integrations/tensorflow/WORKSPACE#L31-L39

**Comment by GMNGeoffrey** [comment]
That's not the issue. Both those edits were under third_party/tensorflow. The issue is that MHLO ops have "automatic" conversion back to XLA via the client builder and the default path doesn't work for the op you added. Note that this is purely an issue in MHLO and has nothing to do with IREE. To actually make the change you would need to send PRs to the tensorflow repository. To get around this you can set the `hasCustomHLOConverter` in the op definition.

One other note/nit:

> I want to lower tf.leakyrelu to the new HLO op mhlo.leaky_relu

If you're adding the MHLO op leaky_relu in hlo_ops.td, then necessarily their is no mhlo.leaky_relu. It sounds like a new op was added to XLA HLO?

**Comment by ArunaKote** [comment]
I able to do the conversion by setting the hasCustomHLOConverter in the op definition
.I added
LogicalResult ExportXlaOp(LeakyReluOp op, OpLoweringContext ctx) {
return failure();
}

in tensorflow/compiler/mlir/xla/mlir_hlo_to_hlo.cc

Thank you
