### ISSUE TITLE
Finish implementing end-to-end i64 support.

### ISSUE THREAD

**Issue by benvanik** [google/iree#7633]
The VM has i64 support but there are a few places where it is not currently allowed - specifically any HAL VM export that only supports i32 types.

A quick work around is to add variants of the calls that split i64s into high/low i32s for crossing the boundary. Things like `hal.command_buffer.fill_buffer` and `hal.buffer.load`/`store` need this, possibly others too.

A better solution is to allow methods with i64 types. We'd only want these exported when the VM was compiled with i64 support though, and that makes any vmfb compiled using them incompatible. That's probably fine, as if you are on a size-constrained deployment you shouldn't be using i64 anyway.

**Comment by benvanik** [comment]
Related: #5732 (dynamic detection of vm extension support), #6991 (f64 support, which requires this issue first), #5731 (weak imports so we could conditionally export the i64 ops).

**Comment by benvanik** [comment]
I mocked up lo/hi word support for fill_buffer and the pattern to support it in the compiler, but since zero target APIs (including CUDA) support it I'm not sure it's worth making part of the HAL. It'd just require all backends to have builtin executables to handle. Instead I think we should take fills on i64/f64 and put them in dispatches. I think the best time to do that is flow as then we have a chance of fusion. I'll poke at that approach.

**Comment by benvanik** [comment]
I could also emulate this in the stream dialect - stream fills/splats of 64-bit values get turned into dispatches there. Yuck to all of this.

**Comment by ScottTodd** [comment]
For constant fills, could we employ the trick you mentioned for WebGPU (https://github.com/gpuweb/gpuweb/issues/1968#issuecomment-891293181) - fill with 0 using a supported bit depth then fold the constant into consumers?

> The particular advantage our approach has is that if we can shift the math around - so as long as we can zero something we can fill it to any value T by making the first access (read or write) be zero+T - we just need a way to get the reused buffers into predictable states.

**Comment by benvanik** [comment]
That'd be pretty nice and could happen at the linalg level - a 1 byte fill of i8 will always be the fastest across implementations. That won't cover the non-linalg cases that may arise during further lowerings so it'd mostly be useful as an optimization vs. something load-bearing for correctness.

I'm currently reworking things to require i8/i16/i32 for stream/HAL fills and then doing the pattern canonicalization during stream tensor encoding (i1 -> i8, f32 -> i32, bf16 -> i16, etc). When we have a 64-bit value we'll emit a new builtin that's a hand-authored executable in linalg or something. I kind of wanted to demonstrate how this was done for things like sparsity anyway so it's a good excuse to plumb that all through. I may need help writing good IR for it though :P

**Comment by benvanik** [comment]
#8039 gets us much closer and working on hal.buffer.load/store now. I'm not actually sure if there's anything left after that besides some potential rough edges on tools that don't have i64 in a switch statement for parsing or whatnot.

**Comment by benvanik** [comment]
I believe with #8091 this is done: not fast, but should work. Can reopen if we find more rough edges.
