### ISSUE TITLE
Improve story for "system modules"

### ISSUE THREAD

**Issue by silvasean** [google/iree#766]
@stellaraccident , for the Python bindings we can just pork-barrel all the needed VM modules, but for real use folks are going to want a better story. Filing this issue to keep track of it.

**Comment by benvanik** [comment]
Can you elaborate @silvasean?
(doesn't make much sense without context)

**Comment by silvasean** [comment]
In the python bindings we add modules [hal and tensorlist into everything](https://github.com/google/iree/blob/44860eba7cef2e6a9f69bd6e10d091a35ee9a9da/bindings/python/pyiree/rt/system_api.py#L97-L98). Long-term for deployment, we need a better story, e.g. if a program doesn't use tensorlist, then we don't necessarily want the tensorlist module loaded. Similarly, if we are hypothetically in the future lowering directly to a Vulkan VM dialect, then we wouldn't want to load the hal dialect in deployments.

I think the questoin here is can we have a better story than "just link in modules and add them to your vm context until your program runs". E.g. could the compiler produce some sort of metadata (or perhaps we can read it already out of the flatbuffer) that we could use to generate a stub .cc file with the needed vm context initialization calls? (just a random idea of what this could look like).

**Comment by benvanik** [comment]
Ah cool - didn't know this was at the python level - thanks!

**Comment by silvasean** [comment]
I think it will also apply to non-python use cases down the road (should people link in the tensorlist module into their application when they use IREE? strings module? ...)

**Comment by stellaraccident** [comment]
As you say, Sean, I kind of have in my mind that a module dependency (including some currently undefined notion of version) needs to be embedded in the flatbuffer binary in a similar way that dynamic library dependencies are embedded in a .so. Then the loading machinery can line up the runtime modules appropriately.

I don't have a specific design beyond that in mind, but I think that is the approach that resonates with me.

Just shoving it in the python API is very much a "get something working" step.

**Comment by benvanik** [comment]
The work done on [native_module](https://github.com/google/iree/blob/dcef2858374139821a7dbe2f5177706211438c71/iree%2Fvm%2Fnative_module.h#L103-L118) provided a stable API for upper layers to inject modules that can interact with the lower layers. Tensorlist & co should be rewritten to use this.
