### ISSUE TITLE
Use submodule llvm (and mlir) vs versions bundled with tensorflow

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#77]
The llvm and mlir situation is presently complicated because the triad of (tensorflow, llvm, and mlir) are in a constant state of flux and frequently need to be at various deltas behind head, depending on how the various repos are updated.

I'd like to switch to submodule repos that we control, since our touch points with tensorflow are minimal and we should be able to manage these deps. However, there are build files we need and it will all be easier when mlir in in llvm (one less divergent piece).

Right now it is also wasteful because the llvm submodule is huge (and is used for cmake) and tensorflow then turns around and downloads a zip file.

This is painful every time we have to rebase to head.

**Comment by GMNGeoffrey** [comment]
Yeah I just ran into this trying to fix #101. I was surprised that bumping only the MLIR module didn't seem to fix the breakage with bazel.

**Comment by stellaraccident** [comment]
Yeah, how TF does this is problematic but temporary. I'm half waiting to see if/when MLIR lands in the LLVM repo, as that will be a lot easier to track.

**Comment by GMNGeoffrey** [comment]
Is this fixed now Stella? Or is TF still using its own version of LLVM?

**Comment by benvanik** [comment]
Assuming this is covered elsewhere (vcpkg deployment, llvm-bazel, etc).
