### ISSUE TITLE
iree-run-mlir to get LLVM Dialect  IR

### ISSUE THREAD

**Issue by ArunaKote** [google/iree#7758]
Can  I stop iree-run-mlir after LLVMCPUSynchronizeSymbolVisibility pass that is not to run HAL and VM passes that is to get output as llvm dialect?

**Comment by benvanik** [comment]
You should be able to use `-print-ir-after=iree-hal-link-target-executables` to see the output containing all of the LLVM dialect IR.

**Comment by ArunaKote** [comment]
Thank You.May I know can I use --iree-codegen-linalg-to-llvm-pipeline  in iree-opt to get llvm Dialect?
If I use --iree-mhlo-input-transformation-pipeline --iree-flow-transformation-pipeline  to get linalg then can I use --iree-codegen-linalg-to-llvm-pipeline to get LLVM Dialect

**Comment by benvanik** [comment]
That won't give you what IREE produces - you'll need to lower through the other dialects. If you want to piece together dialects then this is (today) one that works and stops after LLVM IR is generated for each executable:
```
-iree-import-public
-iree-abi-transform-pipeline
-iree-mhlo-input-transformation-pipeline
-iree-flow-transformation-pipeline
-iree-stream-transformation-pipeline
-pass-pipeline=iree-hal-transformation-pipeline{serialize-executables=false},canonicalize
```
