### ISSUE TITLE
SPIR-V lowering generates multiple types of workgroup query functions.

### ISSUE THREAD

**Issue by benvanik** [google/iree#7759]
I noticed in #7750 that the generated SPIR-V IR contains both the IREE HAL query methods (`hal.interface.workgroup.id` etc) and the GPU dialect query methods (`"gpu.thread_id"` etc). Until the very end of translation into the SPIR-V dialect these remain un-CSE'd and will hurt incremental optimization as the values returned by both are seen as unique and divergent:
```
      %workgroup_id_x = hal.interface.workgroup.id[0] : index
      %workgroup_id_y = hal.interface.workgroup.id[1] : index
      %10 = "gpu.thread_id"() {dimension = "x"} : () -> index
      %11 = "gpu.thread_id"() {dimension = "y"} : () -> index
```

(depending on where in the pipeline this falls we'd either want to convert the HAL ops first or not insert the GPU ops yet)

**Comment by antiagainst** [comment]
They are for different levels: `hal.interface.workgroup.id` is for the workgroup level while `gpu.thread_id` is for the workitem level. They should not be CSE'd. (`gpu.block_id` == `hal.interface.workgroup.id`)

**Comment by benvanik** [comment]
Ahh good catch!
