### ISSUE TITLE
The link of IREE Runtime Design Tech Talk fails

### ISSUE THREAD

**Issue by leslie-fang-intel** [google/iree#7832]
Dear all, I am studying the `IREE Runtime Design Tech Talk` (https://drive.google.com/file/d/1CA-FRRjZUbDFS4pGPiLT86lwghNxMN2M/view?usp=sharing). I find the links in this PDF file fails to open. Is there any where I can find the links?

**Comment by ScottTodd** [comment]
Oh weird, same for me. Seems like the Slides -> .pdf export removed links but kept the styling?

**Comment by ScottTodd** [comment]
Maybe @julianwa or @benvanik could try exporting again?

**Comment by ScottTodd** [comment]
Fixed in https://github.com/google/iree/pull/7857. Thanks for the report!

**Comment by penyung** [comment]
Hi @ScottTodd and @julianwa, 
The link of  IREE Runtime Design Tech Talk (https://drive.google.com/file/d/1ikgOdZxnMz1ExqwrAiuTY9exbe3yMWbB/view?usp=sharing) fails to open again.
Could you help to fix it?

**Comment by ScottTodd** [comment]
> Hi @ScottTodd and @julianwa, The link of IREE Runtime Design Tech Talk (https://drive.google.com/file/d/1ikgOdZxnMz1ExqwrAiuTY9exbe3yMWbB/view?usp=sharing) fails to open again. Could you help to fix it?

That link (and all the links at https://github.com/google/iree#presentations-and-talks) still works for me in a few different browsers. Maybe try again? We could also host the slides and videos on other platforms if that helps (e.g. youtube for recordings, github for pdfs?).

**Comment by penyung** [comment]
Hi @ScottTodd,
It works in other browser. It's really werid. :(
Sorry for bothering.
