### ISSUE TITLE
Bring up WebGPU/WGSL compiler target using Tint

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#7840]
We need to emit shader code in the [WebGPU Shading Language (WGSL)](https://www.w3.org/TR/WGSL/) to use WebGPU. The [Tint compiler](https://dawn.googlesource.com/tint/) supports compiling from SPIR-V to WGSL (and MSL). Most of our existing SPIR-V compilation flow can be reused, though there are some differences in capabilities between Vulkan and WebGPU (and Metal).

Tasks:

- [ ] Add new WebGPUTarget to [iree/compiler/Dialect/HAL/Target](https://github.com/google/iree/tree/main/iree/compiler/Dialect/HAL/Target)
- [x] Include Tint as a dependency when the WebGPU target is enabled
  - [x] Include Tint's dependencies (SPIRV-Headers, SPIRV-Tools)
  - [x] Get Tint building within IREE using CMake and optionally Bazel
- [ ] Invoke Tint during `serializeExecutable()` in the new target
- [ ] Write the serialized WGSL to a flatbuffer using a schema defined at [iree/schemas](https://github.com/google/iree/tree/main/iree/schemas)

---

### Entry point identifiers

Tint throws an error for [this spirv](https://gist.github.com/ScottTodd/13dabfb9365a10c1e278a3ad21beb974):

```
λ tint.exe D:\dev\projects\iree-tmp\webgpu\unidirectional_lstm_dispatch_norename.spv -o D:\dev\projects\iree-tmp\webgpu\unidirectional_lstm_dispatch_norename.wgsl

error: entry point name is not a valid WGSL identifier: _main_dispatch_2
```

This seems to be accepted by the spec: https://www.w3.org/TR/WGSL/#identifiers, but is rejected by tint's source: https://dawn.googlesource.com/tint/+/refs/heads/main/src/reader/spirv/parser_impl.cc#749. This issue might be relevant: https://bugs.chromium.org/p/tint/issues/detail?id=1319. We can choose other identifier names in IREE or remove most identifier names altogether.

### Struct decorations

Tint throws an error for [this spirv](https://gist.github.com/ScottTodd/57dd4d8e6010885ccfdb7772c2ce96d3):

```
λ tint.exe D:\dev\projects\iree-tmp\webgpu\simple_abs.spv -o D:\dev\projects\iree-tmp\webgpu\simple_abs.wgsl

type RTArr = [[stride(4)]] array<f32>;

error: can't handle a struct with more than one decoration: struct 2 has 2
```

for this section:

```
               OpDecorate %_runtimearr_float ArrayStride 4
               OpMemberDecorate %_struct_2 0 Offset 0
               OpDecorate %_struct_2 Block
               OpDecorate %__resource_var_0_0_ Binding 0
               OpDecorate %__resource_var_0_0_ DescriptorSet 0
               OpDecorate %_struct_2 Block
               OpDecorate %__resource_var_0_1_ Binding 1
               OpDecorate %__resource_var_0_1_ DescriptorSet 0
```

### Push constants

IREE currently uses push constants for all but the simplest of programs. These are not supported by WebGPU or Metal, so we'll need to them them into uniform buffer bindings.

Tint throws an error for [this spirv](https://gist.github.com/ScottTodd/b79caefcb9ab3c56e916ca5ec096438f):

```
λ tint.exe D:\dev\projects\iree-tmp\webgpu\unidirectional_lstm_dispatch.spv -o D:\dev\projects\iree-tmp\webgpu\unidirectional_lstm_dispatch.wgsl

type Arr = [[stride(4)]] array<u32, 1u>;

struct S {
  field0 : Arr;
};

error: unknown SPIR-V storage class: 9SPIR-V pointer type with ID 6 has invalid storage class 9
```

(storage class 9 is [`SpvStorageClassPushConstant`](https://github.com/KhronosGroup/SPIRV-Headers/blob/29414ae1fd07a43cf8fe29b4437bfe8475cdd0d8/include/spirv/1.2/spirv.h#L141-L156))

**Comment by benvanik** [comment]
RE push constants, what I currently have is bind group 3 with a single dynamic uniform buffer binding that is set to the offset of the push constants for the dispatch. So if it was a `struct { uint32_t a; uint32_t b; }` in push constants that's now just a uniform; like this in wgsl:

```wgsl
[[block]] struct PushConstants {
  a: u32;
  b: u32;
};
[[group(3), binding(0)]] var<uniform> push_constants: PushConstants;
...
  push_constants.a;
  push_constants.b;
```

There's a few ways we could do the transformation - one would be to do it after translation to the SPIR-V dialect (turning ` spv.GlobalVariable @__push_constant_var__ : !spv.ptr<!spv.struct<(!spv.array<2 x i32, stride=4> [0])>, PushConstant>` into a binding) - the other would be to do this before lowering into SPIR-V at the head of the translation by turning the `hal.interface.load.constant` ops into `hal.interface.binding.subspan` ops.

**Comment by dneto0** [comment]
Re: identifiers can start with underscore.   This was a recent change.  It may 


Re: Duplicate decorations.  I filed https://bugs.chromium.org/p/tint/issues/detail?id=1337 to make Tint's spir-v reader more tolerant of duplicates. Vulkan/SPIR-V allows them (by not prohibiting them), but WGSL is specifically disallows them.

**Comment by ben-clayton** [comment]
>Re: identifiers can start with underscore. This was a recent change. Tint has some updates in this area, but may not be complete.

Small fix up for review: https://dawn-review.googlesource.com/c/tint/+/72320

**Comment by dneto0** [comment]
> error: can't handle a struct with more than one decoration: struct 2 has 2

Tint issue [1337](https://bugs.chromium.org/p/tint/issues/detail?id=1337) (so [elite](https://en.wikipedia.org/wiki/Leet), you know..)  and proposed fix is in review: https://dawn-review.googlesource.com/c/tint/+/72500

**Comment by ScottTodd** [comment]
End of week update:

We have WGSL shaders generated by the compiler using Tint, serialized flatbuffers with all the right bits, most of a [WebGPU HAL implementation on a branch](https://github.com/google/iree/tree/benvanik-webgpu-skeleton) that (mostly) works with wgpu-native and dies on an expected misuse of the API in Dawn. [Hello World](https://github.com/google/iree/blob/main/iree/samples/models/simple_abs.mlir) runs, but more complex programs will need more runtime and compiler work (push constants, buffer use, etc.).

* Fixes for entry point identifiers are in for Tint and MLIR (https://reviews.llvm.org/D115531)
* Fixes for struct decorations are in for MLIR (https://reviews.llvm.org/D115532) and landing soon in Tint
* More general cleanup in MLIR: https://reviews.llvm.org/D115534, https://reviews.llvm.org/D115541
* The compiler side work in IREE (outlined as tasks in the original issue description) is mostly finished [on my branch](https://github.com/ScottTodd/iree/tree/webgpu-target). A few infra details to resolve before we can merge this:
  * git submodules vs CMake FetchContent
  * picking dependency versions and settings that are compatible between the runtime (Dawn/wgpu-native) and compiler (Tint/SPIRV-Tools)
  * waiting for the MLIR changes to make their way to IREE's LLVM submodule / waiting for the Tint changes to be merged

**Comment by benvanik** [comment]
I think I got the fetch stuff all working pretty well for tint/dawn (and wgpu-native) - we could pull that out of my branch and land it now.
