### ISSUE TITLE
There is an infinite loop when running iree-translate tool for centernet model

### ISSUE THREAD

**Issue by sun2011yao** [google/iree#7875]
[centernet_iree_input.mlir.gz](https://github.com/google/iree/files/7711791/centernet_iree_input.mlir.gz)

Hi, I want to use iree-translate tool to translate centernet_iree_input.mlir file to vmfb file,  but it failed, there seems to be an infinite loop in llvm-project/mlir/lib/Dialect/Vector/VectorOps.cpp::foldExtractStridedOpFromInsertChain function.

Run the command as follows:
```shell
iree-translate \
  --iree-input-type=none \
  --iree-vm-bytecode-module-output-format=flatbuffer-binary \
  --iree-hal-target-backends=cuda \
  --iree-mlir-to-vm-bytecode-module \
  ./centernet_iree_input.mlir -o after_translate_cuda.vmfb
```

Thanks a lot!

**Comment by GMNGeoffrey** [comment]
Ok, it looks like this is actually a tar file, so the file extension was a bit confusing. But after correctly untarring, I can't repro your issue. It looks like your model file has a `hal.tensor.cast` which is an op that no longer exists. I can try rebuilding at an old commit if you can let me know what commit you're at. Or can you try reproducing this from tot? An infinite loop certainly sounds like a bug. Could you also share how you came to that conclusion?

**Comment by benvanik** [comment]
@ThomasRaoux wrote the code and may be able to spot something, but it look at first glance like it wouldn't be able to get into an infinite loop: https://github.com/llvm/llvm-project/blob/be0a7e9f27083ada6072fcc0711ffa5630daa5ec/mlir/lib/Dialect/Vector/VectorOps.cpp#L2144 

perhaps it's just really slow/this model has a ton of these to run? (there was an issue for awhile where folding some things could take on the order of 5-10 minutes in certain build configurations and looked like an infinite loop)

**Comment by sun2011yao** [comment]
> Ok, it looks like this is actually a tar file, so the file extension was a bit confusing. But after correctly untarring, I can't repro your issue. It looks like your model file has a `hal.tensor.cast` which is an op that no longer exists. I can try rebuilding at an old commit if you can let me know what commit you're at. Or can you try reproducing this from tot? An infinite loop certainly sounds like a bug. Could you also share how you came to that conclusion?

the commit id is 2601fa940dde3bc9bf12eedcd6cd096ea192daa9

**Comment by sun2011yao** [comment]
Run for more than an hour and still run in that loop

**Comment by ThomasRaoux** [comment]
I took a quick look and the problem is that we generate a huge amount of IR for one of the dispatch. It looks like it is a problem with a sort op that has copies, since we only pick the tile size based on the sort we don't tile all the dimensions of the copy and we end up creating vector<1x576000xf32> that gets unrolled.

I'll see if it still happens with latest code and if so I'll look at a fix tomorrow

**Comment by sun2011yao** [comment]
> I took a quick look and the problem is that we generate a huge amount of IR for one of the dispatch. It looks like it is a problem with a sort op that has copies, since we only pick the tile size based on the sort we don't tile all the dimensions of the copy and we end up creating vector<1x576000xf32> that gets unrolled.
> 
> I'll see if it still happens with latest code and if so I'll look at a fix tomorrow

OK, thanks a lot

**Comment by ThomasRaoux** [comment]
Sent a PR to solve this: https://github.com/google/iree/pull/7892
We shouldn't vectorize dispatch regions with sort as they potentially create those large vectors.

Note that the code generated will be extremely slow with the current implementation of sort op as the sorted dimension is completely serialized. The PR solves the compilation but most likely the execution will run forever.
If you can give us some details on what we are trying to do we can try to figure out if this can be solved short term.

@MaheshRavishankar can you had some details about the sort performance problem?

**Comment by MaheshRavishankar** [comment]
We havent really looked at the specifications for the operation that allows sort to be executed efficiently. For all the cases that were blocking, the sorted dimensions itself was small enough and there were other parallel dimensions (essentially there were n-parallel sorts), that we punted on the problem of making sort itself efficient. If we need to make the sort distributed (as seems to be the case here where there are no parallel dimensions), then we need to rethink the way the sort op is represented in IR. This has some of the same characteristics as the FFT op. We dont represent FFT directly, but rather a stage of FFT as an operation in IR. This exposes the parallelism that we can use to distribute the op to threads etc. (even FFT, we have only looked at the CPU side, and not on the GPU side). We probably need something similar for sort. If we want to distribute sort, we want to represent each stage of a tree reduction as an operation in the IR. I am being scant on the details, cause the details matter here, and we arent looking at optimizing sort in the next few months (thats a whole different project by itself, that we are just not staffed to do).

**Comment by hanhanW** [comment]
+1, if we want to make sort op efficient, we're going to study some sort algorithms and represent it like FFT stage ops. If the sorting dim is small, then tile along parallel loops should be fine here.

**Comment by sun2011yao** [comment]
@ThomasRaoux  after updating the latest code, iree-translate can be run, but iree-run-module takes a long time to run, it's not over for more than half an hour. 
Run the command as follows:
iree-run-module   --module_file=after_translate_cuda.vmfb   --driver=cuda   --entry_function=serving_default --function_input="1x320x320x3xf32"

**Comment by MaheshRavishankar** [comment]
@sun2011yao  If I had to guess from the bug above, and as I mentioned, we have invested **zero** effort in parallelizing sort. Even the sequential sort is not very efficient. It is the bare minimum needed to connect things enough to run. If we need to make sort efficient it would be a project. We arent planning to do this in the next few months unless our priorities change. So I am again cautioning you against expecting anything w.r.t sort (especially on CUDA path).

**Comment by ThomasRaoux** [comment]
@sun2011yao as mentioned before the current implementation will serialize the large sort op onto a single thread which will cause the model to run extremely slow. 
Feel free to file an issue about improvement on sort op but as Mahesh mentioned this is currently not in current priorities.

**Comment by sun2011yao** [comment]
@MaheshRavishankar @ThomasRaoux Okay, thank you very much for your careful answers
