### ISSUE TITLE
Windows release builds failing on CI after compiler inception work

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#7942]
<sub>some initial triage [on Discord here](https://discord.com/channels/689900678990135345/689957613152239638/923250898900250665)</sub>

Sample logs for `windows-2019 :: Build py-compiler-pkg Package`: https://github.com/google/iree/runs/4568108953?check_suite_focus=true

```
    D:\a\iree\iree\main_checkout\iree\vm\bytecode_disasm.c(424): warning C4013: '_Generic' undefined; assuming extern returning int
    D:\a\iree\iree\main_checkout\iree\vm\bytecode_disasm.c(424): error C2275: 'int8_t': illegal use of this type as an expression
...
    D:\a\iree\iree\main_checkout\iree\vm\bytecode_dispatch.c(1161): error C2059: syntax error: ':'
    D:\a\iree\iree\main_checkout\iree\vm\bytecode_dispatch.c(1183): error C2275: 'int8_t': illegal use of this type as an expression
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\stdint.h(18): note: see declaration of 'int8_t'
```

Commit range between https://github.com/google/iree/actions/runs/1593485704 (success) and https://github.com/google/iree/actions/runs/1595268899 (failure) points to https://github.com/google/iree/pull/7858

Seems related to newly depending on runtime code within the compiler. I wasn't able to repro in my local Windows development environment, so maybe something about the Python bindings or CI toolchain?

**Comment by stellaraccident** [comment]
Thanks. Looking.

**Comment by ScottTodd** [comment]
https://github.com/google/iree/pull/7943 may fix this. We'll watch the next CI build.

**Comment by ScottTodd** [comment]
Latest CI build succeeded. Calling this fixed.
