### ISSUE TITLE
Support for i64 constant filling is missing in `hal.command_buffer.fill_buffer` op.

### ISSUE THREAD

**Issue by gprateek93** [google/iree#7976]
On compiling the following IR:
```
module attributes {torch.debug_module_name = "TestFill"}  {
  func @forward(%arg0: !torch.vtensor<[?,?],f32>) -> !torch.vtensor<[?],si64> {
    %0 = torch_c.to_builtin_tensor %arg0 : !torch.vtensor<[?,?],f32> -> tensor<?x?xf32>
    %int4 = torch.constant.int 4
    %none = torch.constant.none
    %c0 = arith.constant 0 : index
    %1 = tensor.dim %0, %c0 : tensor<?x?xf32>
    %c1 = arith.constant 1 : index
    %2 = tensor.dim %0, %c1 : tensor<?x?xf32>
    %c1_0 = arith.constant 1 : index
    %3 = arith.muli %c1_0, %1 : index
    %4 = arith.muli %3, %2 : index
    %5 = arith.index_cast %4 : index to i64
    %6 = torch_c.from_i64 %5
    %7 = torch.prim.ListConstruct %6 : (!torch.int) -> !torch.list<!torch.int>
    %8 = torch_c.to_i64 %6
    %9 = arith.index_cast %8 : i64 to index
    %c0_i64 = arith.constant 0 : i64
    %10 = linalg.init_tensor [%9] : tensor<?xi64>
    %11 = linalg.fill(%c0_i64, %10) : i64, tensor<?xi64> -> tensor<?xi64> 
    %12 = tensor.cast %11 : tensor<?xi64> to tensor<?xi64>
    %13 = torch_c.from_builtin_tensor %12 : tensor<?xi64> -> !torch.vtensor<[?],si64>
    return %13 : !torch.vtensor<[?],si64>
  }
}
```
I am getting the following error:
```
<stdin>:12:10: error: 'hal.command_buffer.fill_buffer' op operand #4 must be 1-bit signless integer or 8-bit signless integer or 16-bit signless integer or 32-bit signless integer or 16-bit float or 32-bit float, but got 'i64'
            %6 = linalg.fill(%c0_i64, %5) : i64, tensor<?xi64> -> tensor<?xi64> 
                 ^
<stdin>:2:3: note: called from
          func @forward(%arg0: tensor<?x?xf32>) -> tensor<?xi64> {
          ^
<stdin>:1:1: error: conversion from source -> vm failed
        module attributes {torch.debug_module_name = "TestFill"}  {
```

**Comment by ScottTodd** [comment]
i64 is not fully supported yet (see https://github.com/google/iree/issues/7633). The fill buffer operation in particular will need emulation on Vulkan and other non-cpu backends (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdFillBuffer.html only supports 32 bit fill patterns, though we could special case the 0 fill here). However, I think we could safely truncate i64 to i32 for the program you provided.

We have a few spots doing that truncation already, so maybe it's just a matter of finding the right path through one of those conversions for that program and/or the `linalg.fill` -> `hal.command_buffer.fill_buffer` pattern:

https://github.com/google/iree/blob/7a742709d6454c1be4856548a604c3d26105b629/iree/compiler/Dialect/Flow/Transforms/TypeConverter.cpp#L33-L44

https://github.com/google/iree/blob/7a742709d6454c1be4856548a604c3d26105b629/iree/compiler/Dialect/VM/Conversion/TypeConverter.cpp#L51-L70

**Comment by Shukla-Gaurav** [comment]
More simpler `linalg IR` to debug/reproduce the issue:

`module attributes {torch.debug_module_name = "Fill_TensorInt64"}  {
  func @forward(%arg0: tensor<?x?xi64>) -> tensor<?x?xi64> {
    %c1 = arith.constant 1 : index
    %c0 = arith.constant 0 : index
    %c1_i64 = arith.constant 1 : i64
    %0 = tensor.dim %arg0, %c0 : tensor<?x?xi64>
    %1 = tensor.dim %arg0, %c1 : tensor<?x?xi64>
    %2 = linalg.init_tensor [%0, %1] : tensor<?x?xi64>
    %3 = linalg.fill(%c1_i64, %2) : i64, tensor<?x?xi64> -> tensor<?x?xi64> 
    return %3 : tensor<?x?xi64>
  }
}
`

**Comment by ScottTodd** [comment]
Ah, with i64 on the boundary (as program input or output) truncating types across the entire program to i32 won't be possible. We'd either need to truncate internally then expand back out or implement full support for the i64 fill (and any other i64 operations needed).

Particularly for non-zero fills we'll need the real fill logic. A fill of 0 using i32 is equivalent to a fill of 0 using i64, but most other values aren't as easy :)
