### ISSUE TITLE
Can this restriction be relaxed, otherwise convtranspose will fail

### ISSUE THREAD

**Issue by sun2011yao** [google/iree#7999]
https://github.com/google/iree/blob/682a9c7bfdf5ca22e4968fa4116ea956ea451159/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp#L131

**Comment by ScottTodd** [comment]
See also: https://github.com/google/iree/issues/7963

**Comment by rsuderman** [comment]
This likely involves a rewrite of the mhlo.conv to linalg lowering, which is a fairly significant piece of work. I am hoping to look into the convolution lowering sometime soon but not sure when I can get around to it.

**Comment by sun2011yao** [comment]
@rsuderman
