### ISSUE TITLE
LinalgVectorLoweringPass creates memref.alloca ops in stage 2 (vector.transfer split)

### ISSUE THREAD

**Issue by hanhanW** [google/iree#8076]
Haven't looked into details yet, but I noticed that some memref.alloca ops will be created in progressive vector lowering. It happens in stage 2 which additionally enables vector.transfer split. This also happens in sandbox.

The IR before `stage=2`: https://gist.githubusercontent.com/hanhanW/859a9481119f0778c91dc776703ed015/raw
The result IR after `stage=2`: https://gist.github.com/hanhanW/cdff230be88da61e208684000225f55c/raw

**Comment by hanhanW** [comment]
Looks like VectorToSCF will also create memref.alloca ops, which is `stage=4`.

https://github.com/llvm/llvm-project/blob/4614b93f53736f18779e46c42a35375fc373ab5d/mlir/include/mlir/Conversion/VectorToSCF/VectorToSCF.h#L26-L48

**Comment by hanhanW** [comment]
Have an offline discussion with @MaheshRavishankar , it's fine to have stack allocation for now.

**Comment by MaheshRavishankar** [comment]
Closing this.
