### ISSUE TITLE
Audit tensorflow-related documentation and samples

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#8086]
Following the work discussed on https://groups.google.com/g/iree-discuss/c/cWZUMXlXscE/m/qTlRXY8NFAAJ, let's check that our documentation and samples are still up to date

- [x] https://google.github.io/iree/building-from-source/python-bindings-and-importers/#building-tensorflow-components-with-bazel
- [x] https://github.com/google/iree/tree/main/colab
- [x] https://google.github.io/iree/ml-frameworks/tensorflow/

ideally we should also expand on documentation and samples for other frontends

**Comment by stellaraccident** [comment]
I've got a lot more work to do. I think we should get someone else to do this. Probably better for someone not-me to trial it anyway: I'm too familiar with it all to spot rough areas.

**Comment by ScottTodd** [comment]
TF docs seem to still be accurate, and the recently added TFLite docs help too: https://google.github.io/iree/getting-started/tflite/

As JAX and other frontends stabilize we should write new docs for them.
