### ISSUE TITLE
Linalg Tensor Fusion causes invalid code with `linalg.index`

### ISSUE THREAD

**Issue by rsuderman** [google/iree#8116]
Tensor Fusion does not appear to check linalg.index behavior during the fusion process. This can result in invalid linalg.generic functions after the TensorFusion pass. This causes failures in some mobilenet style models that contain tfl.image_resize operations.

**Comment by rsuderman** [comment]
A simplified TOSA example of this failure is attached below.

[linalg_failure.zip](https://github.com/google/iree/files/7909317/linalg_failure.zip)

**Comment by rsuderman** [comment]
Here is the IR immediately before the FusionOfTensorOps pass.

[before.zip](https://github.com/google/iree/files/7911358/before.zip)

**Comment by MaheshRavishankar** [comment]
Should be fixed by https://reviews.llvm.org/D117856

@ThomasRaoux this is the same issue as previously reported. I am disabling the pattern for ops with index semantics.

**Comment by ThomasRaoux** [comment]
Oops, thanks for taking care of it @MaheshRavishankar

**Comment by MaheshRavishankar** [comment]
Closing as this should be fixed at HEAD now. Please open if needed.
