### ISSUE TITLE
Linalg Tensor Fusion causes invalid shape for rosetta model

### ISSUE THREAD

**Issue by rsuderman** [google/iree#8127]
[Rosetta](https://github.com/google/iree-samples/blob/main/tflitehub/rosetta_test.py) model compiles to linalg correctly but fails after tensor fusion. The tensor fusion pass must be producing an invalid shape after fusion.

**Comment by rsuderman** [comment]
Bisected IR snippet attached. Fails on the fusion stage.

[failure.zip](https://github.com/google/iree/files/7909653/failure.zip)

**Comment by MaheshRavishankar** [comment]
Can you post the IR before the failing pass.

**Comment by rsuderman** [comment]
It is a little too long to inline but here is the operations with elided constants.

[before.zip](https://github.com/google/iree/files/7911345/before.zip)

**Comment by MaheshRavishankar** [comment]
Latent bug from 16 months ago (introduced by this commit https://github.com/llvm/llvm-project/commit/7060920bd1f70b778105703a5c95066658ed5886 ) .

https://reviews.llvm.org/D117908 should fix it

**Comment by MaheshRavishankar** [comment]
Closing as this should be fixed at HEAD now. Please reopen if needed.
