### ISSUE TITLE
Error: Expected 1 dynamic sizes values

### ISSUE THREAD

**Issue by mariecwhite** [google/iree#8150]
Some models are failing with "Expected 1 dynamic sizes values". Example IR: [tosa.mlir.zip](https://github.com/google/iree/files/7908171/tosa.mlir.zip)

Reproduction steps:
lit -v tflitehub/mobilenet_v1_test.py
lit -v tflitehub/mobilenet_v2_int8_test.py
lit -v tflitehub/mobilenet_v3-large_test.py
lit -v tflitehub/mobilenet_v35_int8_test.py
lit -v tflitehub/resnet_50_int8_test.py

**Comment by rsuderman** [comment]
Validated this is fixed in [llvm commit](https://reviews.llvm.org/D117691). Will close once propagated to IREE head

**Comment by mariecwhite** [comment]
Fix validated and tests re-enabled.
