### ISSUE TITLE
MobileBert Quantized Models Failing on Numerics

### ISSUE THREAD

**Issue by mariecwhite** [google/iree#8152]
2 quantized MobileBert models are failling numerical agreement with TFLite. Interestingly, the IREE invocation time is much lower than the TFLite invocation time.

```
lit -v tflitehub/mobilebert_edgetpu_s_quant_test.py

I0120 12:12:52.698822 140536980965184 test_util.py:134] Invoking TFLite
I0120 12:13:23.273390 140536980965184 test_util.py:96] Invocation time: 30.5742 seconds
I0120 12:13:23.274014 140536980965184 test_util.py:137] Invoke IREE
I0120 12:13:25.117683 140536980965184 test_util.py:111] Invocation time: 1.8433 seconds
I0120 12:13:25.118679 140536980965184 test_util.py:72] Max error (0): 3.331508
I0120 12:13:25.118940 140536980965184 test_util.py:72] Max error (1): 2.141685
````

```
lit -v tflitehub/mobilebert_tf2_quant_test.py

I0120 12:15:18.637756 140600037373760 test_util.py:134] Invoking TFLite
I0120 12:15:38.204409 140600037373760 test_util.py:96] Invocation time: 19.5659 seconds
I0120 12:15:38.205646 140600037373760 test_util.py:137] Invoke IREE
I0120 12:15:39.322192 140600037373760 test_util.py:111] Invocation time: 1.1159 seconds
I0120 12:15:39.323499 140600037373760 test_util.py:72] Max error (0): 3.912988
I0120 12:15:39.323726 140600037373760 test_util.py:72] Max error (1): 3.912988
```

**Comment by benvanik** [comment]
(oooo - assuming we can get it to actually produce the right results that's pretty cool - thanks for including the stats :)

**Comment by rsuderman** [comment]
I looked at the difference between the two models. Its noisy but the general trend looks approximately correct. This is likely related to the inconsistent quantized operation behavior in TFLite.

![Figure_1](https://user-images.githubusercontent.com/5508949/150499270-ec3e66a8-c182-4f3c-afb1-fa54b1f4c395.png)
![Figure_2](https://user-images.githubusercontent.com/5508949/150499271-80a51639-6756-4bd3-b7fe-5efcc7b8fe37.png)

**Comment by mariecwhite** [comment]
I ran this in MLPerf over Squad1.1 mini dataset and the quant version has accuracy 3% worse than TFLite. Ran this on x86 with dylib. On the other hand, the float version is looking great!

**Float MobileBert**
dylib: 188.87 ms 90th percentile latency, 93.0667 accuracy.
TFLite: 774.6 ms 90th percentile latency, 93.0667 accuracy.

**Quantized MobileBert**
dylib: 1091.5 ms 90th percentile latency, **90.6410** accuracy.
TFLite: 675.45 ms 90th percentile latency, 93.2121 accuracy.

**Comment by stellaraccident** [comment]
Thanks, Marie - definitely needs a closer look. I've seen those kinds of accuracy deltas literally be accounted for by some ops corrupting half of their activations before (not in IREE - just historically), so could literally be anything.

**Comment by benvanik** [comment]
Awesome - thanks for the update! Sad we got slower, though, maybe part of the upstream/sandbox integration work?

**Comment by rsuderman** [comment]
> Awesome - thanks for the update! Sad we got slower, though, maybe part of the upstream/sandbox integration work?

Nope, its because we aren't tiling quantized matmuls. Benoit is working to fix this.

**Comment by benvanik** [comment]
Ah - the numbers for float got worse too, so may be something lower level: 188 -> 245 f32, and 1091 -> 1227 i8

**Comment by mariecwhite** [comment]
I've updated the MobileBert tests to use real inputs and increased numerical thresholds. Closing this since there is sufficient confidence that IREE is performing accurately on MobileBert.
