### ISSUE TITLE
Plumb in HAL allocator into Python API

### ISSUE THREAD

**Issue by powderluv** [google/iree#8188]
Currently we have a 3ms overhead when doing e2e tests from the IREE python api vs if you did it with other frameworks. Based on the discussion here: https://discord.com/channels/689900678990135345/760577505840463893/935647551619735602

We need to plumb in https://github.com/google/iree/pull/8183 into the Python API and also the backend CUDA HAL.

**Comment by stellaraccident** [comment]
This has been fixed for some time now.
