### ISSUE TITLE
Add CUDA SDK packages to Turing VMs

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#8242]
Here is the incantation to get sufficient SDK packages on a RHEL based system (note that this is a subset and does not install/mess with the driver):
```
yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo
yum install -y cuda-nvcc-11-6 cuda-cudart-devel-11-6 cuda-cupti-11-6
```

Apt is probably something like:
```
apt ... some repo/key thingy ...
apt install -y cuda-nvcc-11-6 cuda-cudart-devel-11-6 cuda-cupti-11-6
```

According to nvidia docs, the package names are consistent between RHEL and Debian.

Once that is done, please resolve TODOs in the turing build.sh files:

```
# TODO: Add "-DIREE_TARGET_BACKEND_CUDA=ON -DIREE_HAL_DRIVER_CUDA=ON" once the
# VMs have been updated with the correct CUDA SDK.
```

**Comment by ThomasRaoux** [comment]
We ended up adding the full cuda toolkit for simplicity
