### ISSUE TITLE
Fail to build the iree_tf_compiler using bazel

### ISSUE THREAD

**Issue by Jackwin** [google/iree#8267]
Hi folks，

This issue is not about IREE-core bugs, but about the issue of the latest Tensorflow integration.

I have used the IREE last Dec version to build the whole project, everything goes well, including IREE-core and Tensorflow integration.

Recently, It's been found that the IREE project changed a lot, so I pull the version from Feb 4, with the commit ID: 5062ae3994220b. The IREE-core is built successfully, but the TensorFlow integration failed. And the error varies as my trial to build the integration using bazel. From the following pictures, the errors seem to be related to the llvm-project or Eigen? Could you please give some hints to fix it? The platform is Ubuntu 20.4. 
```
cd integration/tensorflow
 bazelisk build iree_tf_compiler:importer-binaries
```

One more question: the TensorFlow integration has been changed a lot, so I believe that the integration/TensorFlow should be compiled standalone, right? Many thanks to IREE team.

![image](https://user-images.githubusercontent.com/4569334/152986314-ffb914b0-31a9-4838-b357-5c4c7bcada5f.png)
![image](https://user-images.githubusercontent.com/4569334/152986399-760221ef-ba0d-4795-914e-6323bce5d583.png)

**Comment by GMNGeoffrey** [comment]
This looks like things just aren't configured correctly. Have you run [configure_bazel.py](https://github.com/google/iree/blob/main/configure_bazel.py)? (you should have a configured.bazelrc in the root of the IREE repository). Next thing to do is run `bazel sync --configure` in the integrations directory. Bazel needs to reconfigure some things after a change to the local system, which you may have had in the meantime

**Comment by Jackwin** [comment]
Thanks, @GMNGeoffrey. It's solved.
