### ISSUE TITLE
iree/vm/ fails to build through MSVC (missing _Atomic and stdatomic.h)

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#827]
I'm trying to build `iree_vm_ref` (and eventually `iree_tools_iree-run-mlir`) with MSVC using the CMake kit 'Visual Studio Community 2019 - amd64' on Windows. The target builds without issues through Clang / Bazel on this Windows machine.

I see errors like this:
```
[build] C:\dev\iree\iree/vm/ref.h(64): error C2061: syntax error: identifier '_Atomic'
[build] C:\dev\iree\iree/vm/ref.h(65): error C2059: syntax error: '}'
[build] C:\dev\iree\iree/vm/ref.h(66): error C2065: '_Atomic': undeclared identifier
[build] C:\dev\iree\iree/vm/ref.h(66): error C2146: syntax error: missing ')' before identifier 'intptr_t'
[build] C:\dev\iree\iree/vm/ref.h(66): error C2059: syntax error: ')'
[build] ..\iree\vm\ref.c(18): fatal error C1083: Cannot open include file: 'stdatomic.h': No such file or directory
```

referencing these lines: https://github.com/google/iree/blob/3522abb6ae27383e8258c8d50e1d6f8e411fea91/iree/vm/ref.h#L62-L67

https://github.com/google/iree/blob/3522abb6ae27383e8258c8d50e1d6f8e411fea91/iree/vm/ref.c#L17-L19

note this is after locally adding 

```
if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
  # Ignore "Host Visual Studio version 16.4 is known to miscompile part of LLVM"
  set(LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN ON)
endif()
```

here (to ignore a recently added warning): https://github.com/google/iree/blob/3522abb6ae27383e8258c8d50e1d6f8e411fea91/build_tools/cmake/iree_copts.cmake#L58-L62

**Comment by benvanik** [comment]
Looks like we can just spoof the _Atomic support (as it's just a macro), ala what's done here: http://docs.ros2.org/latest/api/rcutils/win32_2stdatomic_8h_source.html

I'll take a look at fixing this as part of larger MSVC work.
