### ISSUE TITLE
IREEComprehensiveBufferize does not generate memref.assume_alignment

### ISSUE THREAD

**Issue by hanhanW** [google/iree#8293]
We do want generate the alignment op in IREE. IREE does not generate the op after switching to IREEComprehensiveBufferize. File an issue for tracking it.

**Comment by hanhanW** [comment]
Yes, I think so. @ThomasRaoux may have more context about it since the ops are added in https://github.com/google/iree/pull/7787

**Comment by ThomasRaoux** [comment]
Correct the assume ops were created at the same time as `InterfaceBindingSubspanOp`. Where do we create such op with upstream bufferization? We should probably also add the assume ops there.

**Comment by matthias-springer** [comment]
I think they should be added here: https://github.com/google/iree/blob/main/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp#L258

I can do that tmr.

**Comment by hanhanW** [comment]
@matthias-springer can we close the issue when landing the PR? Github will automatically close the issue when there are "fix XXX" in commit messages.

Or do I miss something here? If so, could you add some comments about it?

**Comment by matthias-springer** [comment]
Oh I thought I had already landed the commit. I think the PR can be merged.
