### ISSUE TITLE
RESOURCE_EXHAUSTED; failed to create eventfd (24)

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#8309]
I have a test that repeatedly creates a driver (vmvx) and drops it on the floor (the test is supposed to do more but I'm testing a degenerate case). In 2 out of 17 tries, `iree_hal_driver_registry_try_create_by_name` fails with:

```
Error creating driver: /home/stella/src/iree/iree/base/internal/wait_handle_posix.c:39: RESOURCE_EXHAUSTED; failed to create eventfd (24)
```

There is also a double fault when this happens, resulting in a segmentation fault in `iree_task_executor_destroy` (commented out here so I could get the exception):

```
  if (!iree_status_is_ok(status)) {
    // NOTE: destroy will ensure that any workers we have initialized are
    // properly cleaned up.
    //iree_task_executor_destroy(executor);
    IREE_TRACE_ZONE_END(z0);
    return status;
  }
```

Segmentation fault stack trace:

```
#0  0x00007fff51f8e448 in iree_wait_set_free (set=0x0) at /home/stella/src/iree/iree/base/internal/wait_handle_poll.c:170                                                                                               #1  0x00007fff51f847fa in iree_task_poller_deinitialize (poller=poller@entry=0x61b0000a0a20) at /home/stella/src/iree/iree/task/poller.c:134
#2  0x00007fff51f80192 in iree_task_executor_destroy (executor=<optimized out>) at /home/stella/src/iree/iree/task/executor.c:198
#3  0x00007fff51f7fde2 in iree_task_executor_create (scheduling_mode=<optimized out>, topology=0x7fffffff8100, worker_local_memory_size=<optimized out>, allocator=..., out_executor=<optimized out>)                       at /home/stella/src/iree/iree/task/executor.c:164                                                                                                                                                                   #4  0x00007fff51f7f2a8 in iree_task_executor_create_from_flags (host_allocator=..., out_executor=<optimized out>) at /home/stella/src/iree/iree/task/api.c:114                                                          
#5  0x00007fff51f73955 in iree_hal_vmvx_driver_factory_try_create (self=<optimized out>, driver_id=<optimized out>, host_allocator=..., out_driver=<optimized out>)
    at /home/stella/src/iree/iree/hal/vmvx/registration/driver_module.c:66                                                                                                                                              #6  0x00007fff51f03d45 in iree_hal_driver_registry_try_create_by_name (registry=0x7fff521ea320 <iree_hal_driver_registry_default_>, driver_name=..., allocator=..., out_driver=<optimized out>)
    at /home/stella/src/iree/iree/hal/driver_registry.c:349                                                                                                                                                            
```

I doubt that my specific repro will be of much use to you but I could try to reduce it. ASAN is clean in both the fault and double-fault case.

The ultimate caller is a Python unit test that is doing:

```
  def setUp(self):
    # Doesn't matter what device. We just need one.
    config = rt.Config("vmvx")
    self.device = config.device
```

Adding an explicit tearDown() clears the resource exhaustion:

```
  def tearDown(self):
    self.device = None
    import gc
    gc.collect()
```

This leads me to believe that in whatever case I am tickling, the cycle collector is deferring deallocation, and that is causing a backlog of drivers to be created. Intuitively, I don't expect vmvx to be tied to such system wide resource limits, but ?

In any case, we should fix the double fault on failure to allocate an eventfd.

**Comment by benvanik** [comment]
Cool - should be easy to fix the explosion.

As for resources: assuming there's not a leak (what I'll check) if you're running out of events it's probably just the canary (some low file descriptor limit) - we create one event per task system, and if you are relying on GC to clean up the thread pools you're going to have a bad time. You really don't want to be leaving things like that to GC :)

**Comment by stellaraccident** [comment]
It's a dumb unit test. I changed it to initialize once for the whole test class. But we should fix the seg fault
