### ISSUE TITLE
Implementation of scatter-like op in Linalg_ext dialect

### ISSUE THREAD

**Issue by vivekkhandelwal1** [google/iree#8318]
This issue is related to the pull request (https://github.com/google/iree/pull/8266), which was earlier closed.

Hi @MaheshRavishankar, after discussing with @cathyzhyi, we concluded that we could implement a `scatter-like` op that will be generalized and satisfy our requirements. It will have two fundamental differences from the original `scatter` op:
1.) In the original scatter op, the indices are constrained to be a 2-d tensor, while in this case, it would be constrained to a 1-d tensor.
2.) In the original scatter op, all the loop iterators are parallel, while in our case, one will be reduction type, and the remaining ones will be parallel.

Can we go ahead with this op? If yes, what would be the appropriate name for this op?

**Comment by MaheshRavishankar** [comment]
Have been thinking about this a bit. The current implementation of `scatter` assumes that the elements updated by the op are all dynamically independent (if they are not, its a race condition). That allows doing all updates in parallel. For the case you have that is not true. There are two options that I am considering
1) Can we add a reduction loop to scatter op that serializes all updates to the output. Not sure how much impact it will have on the existing implementation
2) We can add a `scatter_update` operation which states explicitly which loop dimension corresponds to the scatter update dimension, forcing it to be sequential.

I am biasing towards the second option. The PR you have is very specific to bin-counting. You need to generalize the operation. Also if the operation is not implementing the `getTiledImplementation` method, I dont really see a way of landing this. For these ops we have usually proceeded in these steps

1) Have some basic idea about the scope of the operation, and how the tiled and distributed computation looks. For example here, some questions I have are
	a) The op as defined is very specific. You need to generalize it to allow any arbitrary scalar computation for the updates. The reasoning here is that the actual ops to do the update are not of concern for the operation itself. It is just used during lowering to loops
    b) What is the parallel and sequential dimensions of the loop, and how does the op-specification tell you which loop dimension is parallel and which is sequential. This part is missing for me.
2) Add the basic op-definition with lowering to loops.
3) Add the tiling implementation to do the distribution.

With this, you should automatically have e2e support to some extent. Some more information about what is needed would be useful

**Comment by hanhanW** [comment]
Another question about bincount op. How do we know the size of output tensor? Is it always static number? If not, we may hit issues in bufferization. We'll need to get the maximal value in input and allocate a big enough buffer for output, which is scary to me.

**Comment by benvanik** [comment]
The tf op has a max length you can provide, and I think it's fine to require that: https://www.tensorflow.org/api_docs/python/tf/math/bincount
(XLA & co don't have dynamic shapes, so if they supported this they'd require it too)

**Comment by benvanik** [comment]
(if we wanted to support this we could do the reduce_max to derive the dynamic dimension, with the caveat that it'll be a host readback/synchronization)

**Comment by vivekkhandelwal1** [comment]
Hi @hanhanW, I have two requirements:

1.)
```
for (i = 0; i < indices.size(); i++)
        count[indices[i]]++
```

2.)
```
for (i = 0; i < indices.size(); i++) {
        if (padding_idx != indices[i]) {
                scale = 1.0
                if (scale_grad_by_freq)
                        scale /= count[indices[i]]
                for (j = 0; j < grad_out.size()[1]; j++)
                        grad_out[indices[i], j] += grad[i, j] * scale
        }
}
```

In both these cases, the `indices` can contain repeated values. These are my exact requirements. In the first case, the output tensor is a 1-d tensor and the indices. While in the second case, the output tensor is 2-d, while the `indices` tensor is 1-d.

```
How do we know the size of the output tensor? Is it always a static number?
```
No, the size of the output tensor need not always be static. It depends on some pre-computation done at the torch-mlir side.

**Comment by vivekkhandelwal1** [comment]
Hi @MaheshRavishankar, I am also of the opinion that the second option i.e.
```
We can add a scatter_update operation which states explicitly which loop dimension corresponds to the scatter update dimension, forcing it to be sequential.
```
is better.

We will implement the tiled part as well. What we can do is, along with the other inputs, we can also take a `dimension` as input which will be sequential, and the remaining ones will be parallel.

**Comment by benvanik** [comment]
Unfortunate :( Any algorithm that has data dependent shapes is suboptimal and should be avoided but something we still need to support - but if we implement anything here we should ensure that cost is entirely on the user of the suboptimal algorithm instead of structural in our layers. Whatever ops we use for the binning then should require a bin count as an SSA value parameter. That means that in the general case by decomposition this becomes a reduce_max to find the limit value followed by the binning - which in practice becomes the reduction, a full synchronization with all pending work on device, a readback of that result, an allocation of the dynamic output, and then the actual binning. By allowing the dynamic value it enables a user who cares about performance the ability to specify the maximum bin count (derived by hand, profile-guided, or baked in via constant eval) and avoid the readback - we'll allocate the worst case statically and then from the binning return the actual bin count that can be used to slice out from the storage result if needed. Data-dependent subranges are much easier to optimize across dispatches vs data-dependent allocations as you can always use less memory than available but never more.

**Comment by vivekkhandelwal1** [comment]
Hi @benvanik, thanks for your detailed reply. But it's still not clear to me whether we can add such an op or not?

**Comment by hanhanW** [comment]
Adding a new operation needs more exploration about why and how. Ben and I were exploring how bincount would work in IREE. We may go with adding the new op, but it's good to list down caveats for this approach.

 As @MaheshRavishankar mentioned, we may need to generalize the operation. Would you like to answer some of the questions?

>Have some basic idea about the scope of the operation, and how the tiled and distributed computation looks. For example here, some questions I have are
a) The op as defined is very specific. You need to generalize it to allow any arbitrary scalar computation for the updates. The reasoning here is that the actual ops to do the update are not of concern for the operation itself. It is just used during lowering to loops
b) What is the parallel and sequential dimensions of the loop, and how does the op-specification tell you which loop dimension is parallel and which is sequential. This part is missing for me.


So far, I don't really see a clear op definition. Here are some questions I have based on your proposal:

> In the original scatter op, the indices are constrained to be a 2-d tensor, while in this case, it would be constrained to a 1-d tensor.

Do we really need to constrained to a 1-d tensor? Can we play it with a reshape trick (e.g., 3xf32 -> 3x1xf32)?

>  In the original scatter op, all the loop iterators are parallel, while in our case, one will be reduction type, and the remaining ones will be parallel.

Which loop will be reduction type? Is it the first dimension in original scatter op (which is the number of updates)?

I feel that we're going to copy all the codes of scatter op except this section:

https://github.com/google/iree/blob/662cc3763be0cb0ab1a5567af49c4a9b3d7ceb52/llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp#L190-L194

If my guess is true, this will be "reduction, parallel, parallel...".

**Comment by cathyzhyi** [comment]
> In the original scatter op, the indices are constrained to be a 2-d tensor, while in this case, it would be constrained to a 1-d tensor.

I also think we don't need to constrain it to be a 1-d tensor. 

> I feel that we're going to copy all the codes of scatter op except this section

Yes, that's our understanding as well. Except that there seems to be the need to add an extra operand to specify the max length according to https://github.com/google/iree/issues/8318#issuecomment-1040598391. In this case, the max length can be a 1-D memref <_index_depth_ xi32>.

@vivekkhandelwal1 and I will write a [doc](https://docs.google.com/document/d/14IgcDTMBwlZBuDmd9lWCUN_A72Plm_qP9qLF_mfd2Do/edit#heading=h.17a1hecg2kko) to describe what we have in mind.

**Comment by hanhanW** [comment]
> Yes, that's our understanding as well. Except that there seems to be the need to add an extra operand to specify the max length according to https://github.com/google/iree/issues/8318#issuecomment-1040598391. In this case, the max length can be a 1-D memref <index_depth xi32>.

I think we don't need it. The Linalg and bufferization work in a different logic. Both dynamic cases and static cases work similar to me in my mind. We will have an init_tensor + fill as "operand" in linalg_ext.scatter* op.

For static cases, the init_tensor takes a static constant value. E.g.,

```mlir
%init = linalg.init_tensor [100] : tensor<100xi32>
%fill = linalg.fill(%cst_0, %init) ...
%0 = linalg_ext.scatter ins(%indices, %updates) outs(%fill) ...
```

For dynamic cases, the init_tensor would take the result of a reduce op.

```
%max = mhlo.reduce ( ... ) // Can be other linalg ops form
%init = linalg.init_tensor [%max] : tensor<?xi32>
%fill ...
...
```

**Comment by MaheshRavishankar** [comment]
> > In the original scatter op, the indices are constrained to be a 2-d tensor, while in this case, it would be constrained to a 1-d tensor.
> 
> I also think we don't need to constrain it to be a 1-d tensor.
> 
> > I feel that we're going to copy all the codes of scatter op except this section
> 
> Yes, that's our understanding as well. Except that there seems to be the need to add an extra operand to specify the max length according to [#8318 (comment)](https://github.com/google/iree/issues/8318#issuecomment-1040598391). In this case, the max length can be a 1-D memref <_index_depth_ xi32>.
> 
> @vivekkhandelwal1 and I will write a [doc](https://docs.google.com/document/d/14IgcDTMBwlZBuDmd9lWCUN_A72Plm_qP9qLF_mfd2Do/edit#heading=h.17a1hecg2kko) to describe what we have in mind.

Doc would help me personally to figure out the space here.
