### ISSUE TITLE
Bazel build is broken, errors updating TensorFlow submodule

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#834]
We need to update our Bazel version (https://github.com/google/iree/pull/755) and make some changes to be compatible with the latest changes in TensorFlow (notably https://github.com/tensorflow/tensorflow/commit/09fe958feebec0405ccac225c94fc130304fc2f4).

I'm working on this, but it will take some time to untangle. Unknown impact on CMake.

**Comment by marbre** [comment]
The CMake build is broken as well, but that seems to be related to the latest LLVM submodule update. Let's see if I can fix this before my flight departures ;)

**Comment by ScottTodd** [comment]
Synced TF and LLVM, Bazel and CMake builds/tests both seem to be passing again :tada:
