### ISSUE TITLE
Remove extracting padding attributes patterns from MHLO to MHLO preprocessing

### ISSUE THREAD

**Issue by hanhanW** [google/iree#8347]
We have patterns like ExtractReduceWindowOpPaddingAttributes and ExtractConvOpPaddingAttributes when prototyping padding support in the beginning. We now are sure we do want to split out padding attribute at Linalg level. So far, upstream patterns in MHLO do not accept non-zero padding values lowering. We should extend the lowering support there and remove these patterns.

It's already done for normal convolution cases, and we can reuse some methods there, e.g., https://github.com/tensorflow/tensorflow/pull/53524

The patterns to clean up:

https://github.com/google/iree/blob/db64daa4006abb0ccd3474a9791f7df140aa0074/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp#L82

https://github.com/google/iree/blob/db64daa4006abb0ccd3474a9791f7df140aa0074/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp#L340

**Comment by Ash-KODES** [comment]
Please assign this to me!
I will be happy to contribute:)

**Comment by hanhanW** [comment]
Thanks @Ash-KODES !  Feel free to create a PR in tensorflow and tag me. I'm happy to review the changes. Once they are checked in and integration happens, we can clean up the IREE side.

**Comment by pzread** [comment]
If no one has started yet, I'll work on the lowering support in the upstream.
