### ISSUE TITLE
Add flow/stream op for empty tensors.

### ISSUE THREAD

**Issue by benvanik** [google/iree#8350]
It's possible to end up with known-empty tensors after canonicalization/linalg/IPO at flow/etc. Today we keep around all of the computation in order to produce the empty tensors but should instead be swapping out any computation with the empty value so it can propagate.

Example IR:
https://gist.githubusercontent.com/vivekkhandelwal1/3747f5a13241cc1d18160141a0333a95/raw/d3e83a58a48c44a85663bc9f328e8df74184777b/log_canonicalize.mlir#:~:text=./../misc/bert_static.mlir,operation%3A%20%22builtin.module%22()%20(%7B

```mlir
    %1095 = "linalg.init_tensor"() {static_sizes = [0, 2]} : () -> tensor<0x2xf32>
    %1096 = "linalg.generic"(%1095) ({
    ^bb0(%arg1: f32):
      "linalg.yield"(%17) : (f32) -> ()
    }) {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"], operand_segment_sizes = dense<[0, 1]> : vector<2xi32>} : (tensor<0x2xf32>) -> tensor<0x2xf32>
    %1097 = "linalg.matmul"(%1094, %7, %1096) ({
    ^bb0(%arg1: f32, %arg2: f32, %arg3: f32):
      %1100 = "arith.mulf"(%arg1, %arg2) : (f32, f32) -> f32
      %1101 = "arith.addf"(%arg3, %1100) : (f32, f32) -> f32
      "linalg.yield"(%1101) : (f32) -> ()
    }) {linalg.memoized_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d2, d1)>, affine_map<(d0, d1, d2) -> (d0, d1)>], operand_segment_sizes = dense<[2, 1]> : vector<2xi32>} : (tensor<0x384xf32>, tensor<384x2xf32>, tensor<0x2xf32>) -> tensor<0x2xf32>
    %1098 = "tensor.cast"(%1097) : (tensor<0x2xf32>) -> tensor<?x2xf32>
    %1099 = "hal.tensor.export"(%1098, %2) {operand_segment_sizes = dense<[1, 1, 0]> : vector<3xi32>, source_encoding = tensor<?x2xf32>} : (tensor<?x2xf32>, index) -> !hal.buffer_view
    "std.return"(%1099) : (!hal.buffer_view) -> ()
```

Here the %1095 is known to be empty but is still computed as %1096/%1097 and finally exported as %1099.

A folder on linalg ops could look for outputs that are empty init tensors and reroute them back to the empty init tensor; the above would become:
```mlir
    %1095 = "linalg.init_tensor"() {static_sizes = [0, 2]} : () -> tensor<0x2xf32>
    %1098 = "tensor.cast"(%1095) : (tensor<0x2xf32>) -> tensor<?x2xf32>
    %1099 = "hal.tensor.export"(%1098, %2) {operand_segment_sizes = dense<[1, 1, 0]> : vector<3xi32>, source_encoding = tensor<?x2xf32>} : (tensor<?x2xf32>, index) -> !hal.buffer_view
    "std.return"(%1099) : (!hal.buffer_view) -> ()
```

Then a `flow.tensor.empty` op that followed the `flow.tensor.splat` signature with capturing dimensions could be added such that the tensor.cast could be absorbed. Stream/HAL could then handle the empty tensor as an undefined buffer (the contents aren't undefined, but it has no defining backing storage) - what gets returned by the `hal.tensor.export` would then be a buffer view with 0 elements and no backing storage. The above IR would become:
```mlir
    %1095 = flow.tensor.empty : tensor<0x2xf32>
    %1098 = "tensor.cast"(%1095) : (tensor<0x2xf32>) -> tensor<?x2xf32>
    %1099 = "hal.tensor.export"(%1098, %2) {operand_segment_sizes = dense<[1, 1, 0]> : vector<3xi32>, source_encoding = tensor<?x2xf32>} : (tensor<?x2xf32>, index) -> !hal.buffer_view
    "std.return"(%1099) : (!hal.buffer_view) -> ()
```
and via canonicalizers/folders:
```mlir
    %1095 = flow.tensor.empty : tensor<0x2xf32>
    %1099 = "hal.tensor.export"(%1095) {operand_segment_sizes = dense<[1, 0, 0]> : vector<3xi32>, source_encoding = tensor<0x2xf32>} : (tensor<0x2xf32>, index) -> !hal.buffer_view
    "std.return"(%1099) : (!hal.buffer_view) -> ()
```

* [x] Fold linalg ops with empty init tensors into the init tensor value
* [x] Add `flow.tensor.empty` like `flow.tensor.splat` without the splat value
* [ ] Ensure tensor.cast folds with flow/stream ops
* [x] Add a corresponding `stream.tensor.empty` (we still need to capture the encoding, as an empty sparse tensor may still need bytes)

**Comment by benvanik** [comment]
#8515 makes the example input program mostly melt away. There's likely more work that can be done with tensor.cast and other edges of the dialect boundaries but it'd be useful to do that as we find real programs doing that kind of stuff. It's also likely that improvements to tensor.cast/linalg would make it so we never see those cases by the time we hit flow/stream anyway.

**Comment by MaheshRavishankar** [comment]
Nice! I think for some of the cases that were being hit on trying the bert dynamic models, it was a case of missing canonicalizations/patterns. They were probably removed cause they werent needed for the static case, but are needed for the dynamic case. So https://github.com/google/iree/commit/086fb7bfc5c9015dfbe6fd58195cec8159de3b94 cleaned some of those up.
