### ISSUE TITLE
EmitC static library test disabled

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#8380]
Fails with an error like:

```
/home/stella/scratch/emitc.mlir:90:5: error: failed to legalize unresolved materialization from '!vm.ref<!hal.executable>' to '!emitc.opaque<"iree_vm_ref_t*">' that remained live after conversion
    vm.br ^bb3(%ref_2 : !vm.ref<!hal.executable>)
    ^
/home/stella/scratch/emitc.mlir:90:5: note: see current operation: %167 = "builtin.unrealized_conversion_cast"(%166) : (!vm.ref<!hal.executable>) -> !emitc.opaque<"iree_vm_ref_t*">
```

**Comment by stellaraccident** [comment]
Both Mahesh and I spent a bit of time looking at this. Something seems to go wrong in some relatively tricky BranchOpConversions in ConvertVMToEmitC (and corresponding interaction with the type converter). I tried some obvious things to figure it out, but there are no unit tests for this code that I could find. We really can't have code like this in tree without unit tests (esp. something tricky like this). I suspect something subtle changed upstream which should not have affected this but did. There are a number of uses of the original op operands vs adaptor operands without a clear explanation of what the intent is (likely a bug here but can't spot what is intentional vs not).

**Comment by stellaraccident** [comment]
(also building samples in this way as part of the main build is not great -- even if there were unit tests, the sample (effectively an integration test) would block running them)

**Comment by marbre** [comment]
Seems like the upstream change llvm/llvm-project@d4a53f3 causes the problems on our side. @simon-camp already has a fix for this.

Beside the the `VMToEmitC` tests, located in [`/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test`](https://github.com/google/iree/tree/main/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test), there are additional tests in [vm/test](https://github.com/google/iree/tree/main/iree/vm/test). These are also used to test EmitC: https://github.com/google/iree/blob/2b46f3cd2831a1b65d94264e3d6bc0ea02a38835/iree/vm/test/emitc/CMakeLists.txt#L22-L44

Looking into the tests, we expected 

https://github.com/google/iree/blob/2b46f3cd2831a1b65d94264e3d6bc0ea02a38835/iree/vm/test/control_flow_ops.mlir#L74-L86

to fail. Unfortunately, it did not. We see if we can add a test covering the issue.

**Comment by stellaraccident** [comment]
Thanks Marius - indeed, the lack of a unit test for this code is what prompted me to make the decision to exclude vs fix (I and Mahesh did try to fix it but without a test, it was not easy to discern what the expected behavior was).

Those tests you link to are still very "integration-test-y". The conversion patterns generally need at least a cursory lit test for each pattern. Sometimes we fudge that for variations on a theme that share an implementation, but for something subtle like this, we probably really need several unit/lit tests making sure to evaluate each of the conversion branches.

**Comment by marbre** [comment]
I got your point and fully agree. I'll try to make sure that we increase the test coverage asap.

**Comment by stellaraccident** [comment]
To elaborate a bit more, when we encounter a failure of a pattern, we look for an existing unit test. The best case is that there is a failing unit test, and then the job is to make that pass. If not, it often calls for a more specific unit test, and you want to fork that or reduce from an existing. It's not a great case when something regresses and there is no unit test coverage because it is very hard to reason from a broken state regarding what should be done.

**Comment by stellaraccident** [comment]
Thanks - and we mid air collided on my second response (I must have been typing when you submitted). Didn't mean to say more when we were already in agreement :)
