### ISSUE TITLE
[MLIR] Reduce the iteration space of a `LinalgOp` if only a slice of it is used.

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#8410]
Consider the following sequence of ops

```
#map0 = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d1)>
%0 = linalg.generic {
    indexing_maps = [#map0, #map1, #map0],
    iterator_types = ["parallel", "parallel"]}
    ins(%a0, %a1 : tensor<?x?xf32>, tensor<?xf32>
    outs(%a0 : tensor<?x?xf32>) {
    ^bb0(%b0 : f32, %b1 : f32, %b2 : f32):
      %1 = arith.addf %b0, %b1 : f32
      linalg.yield %1 : f32
} -> tensor<?x?xf32>
%2 = tensor.extract_slice %0 [%o0, %o1] [%s0, %s1] [1, 1]
    : tensor<?x?xf32> into tensor<?x?xf32>                             
```

If `%0` has a single use this could be rewritten as

```
#map0 = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d1)>
%0 = tensor.extract_slice %a0[%o0, %o1] [%s0, %s1] [1, 1] : tensor<?x?xf32> into tensor<?x?xf32>
%1 = tensor.extract_slice %a1[%o1] [%s1] [1] : tensor<?xf32> into tensor<?xf32>
%2 = linalg.generic {
    indexing_maps = [#map0, #map1, #map0],
    iterator_types = ["parallel", "parallel"]}
    ins(%0, %1 : tensor<?x?xf32>, tensor<?xf32>
    outs(%0 : tensor<?x?xf32>) {
    ^bb0(%b0 : f32, %b1 : f32, %b2 : f32):
      %3 = arith.addf %b0, %b1 : f32
      linalg.yield %3 : f32
} -> tensor<?x?xf32>   
```
This shifts the `tensor.extract_slice` above the `linalg.generic`. If the producers of `%a0` or `%a1` are themselves `linalg.generic` operations, then this pattern could apply again and further reduce the computation done.

In reality, this does not need to be restricted to `linalg.generic`. This transformation holds for any operation that implements the `LinalgOp` interface.

**Comment by okkwon** [comment]
A transformation is implemented in llvm-project and it needs to be called in iree.

**Comment by MaheshRavishankar** [comment]
The work here is done. It just needs to be called from IREE, but there was no use case found to actually use it (though there has been some examples/bug filed for this). We can add this when a use case surfaces.
