### ISSUE TITLE
Ability to select HAL/CUDA  device from the API

### ISSUE THREAD

**Issue by powderluv** [google/iree#8444]
It would be good to provide an API to select the device to run IREE on (in case of GPU like devices). Currently this is possible by setting the ENV vars for CUDA but we would like to be able to do it from the API so that if you provide a command line arg to iree-run-module you should be able to run IREE on that particular device.

**Comment by benvanik** [comment]
Vulkan does this here:
https://github.com/google/iree/blob/931a3b1465246e81ea99d8d7b308626c50709238/iree/hal/vulkan/registration/driver_module.cc#L24
->
https://github.com/google/iree/blob/931a3b1465246e81ea99d8d7b308626c50709238/iree/hal/vulkan/api.h#L236

(that is, there's a way to pass it in on the programmatic API for creating drivers as well as a flag exposed that just sets that value when using the flags approach)

**Comment by nirvedhmeshram** [comment]
I think CUDA has it in the API too right?
https://github.com/google/iree/blob/931a3b1465246e81ea99d8d7b308626c50709238/iree/hal/cuda/api.h#L27
I can just add the flag similar to Vulkan, anything else that would be needed?

**Comment by nirvedhmeshram** [comment]
Raised this PR, that exposes a flag to select device https://github.com/google/iree/pull/8455/files

**Comment by nirvedhmeshram** [comment]
https://github.com/google/iree/pull/8455
