### ISSUE TITLE
Constant order issue causing performance regression?

### ISSUE THREAD

**Issue by antiagainst** [google/iree#8484]
This issue tracks a mysterious performance regression happened for PoseNet on Mali G78 that were fixed by https://github.com/google/iree/pull/8454.

From Tracy traces [before](https://buildkite.com/iree/iree-benchmark/builds/2215#dc94ae1f-a299-4200-8b31-13a7ff09eb58) and [after](https://buildkite.com/iree/iree-benchmark/builds/2217#095ee51b-bc04-4b3f-9e3b-219c2fe924d9) the fix, dispatch 23 took noticeable longer time:

![Screen Shot 2022-03-07 at 3 48 00 PM](https://user-images.githubusercontent.com/487928/157115899-aacc0c93-898b-4ac5-9edc-a37c1aa31efb.png)

![Screen Shot 2022-03-07 at 3 47 38 PM](https://user-images.githubusercontent.com/487928/157115919-f91905dd-19ca-415c-932b-59c21894e692.png)

But diffing the SPIR-V CodeGen `dispatch23-before-fix.mlir` and `dispatch23-after-fix.mlir` shows that the final SPIR-V is identical. So it's not a CodeGen issue.

Diffing the output after [the last canonicalization at TOSA input conversion](https://github.com/google/iree/blob/74cab16/iree/compiler/InputConversion/TOSA/Passes.cpp#L52) `tosa-input-before-fix.mlir` and `tosa-input-after-fix.mlir` shows only constant ordering difference. (Basically reverse orders.)

This leads me to suspect the issue is because of constant ordering. 

MLIR files mentioned are here: https://gist.github.com/antiagainst/7b666a817e1af780b4ba2e0af5f04dc7
To repro, just revert https://github.com/google/iree/commit/74cab16fa7fafa0c92d41c3d86105ac73d5c4af3

**Comment by benvanik** [comment]
Can you post IR after `-iree-stream-pack-constants`? That will show the exact ordering of the constants in the file as well as what constants are used by dispatch_23 - there's no need to guess :)
If dispatch_23 accesses a single constant then this may not be related to ordering specifically but something else.

**Comment by benvanik** [comment]
This may be related to alignment - by reordering the constants the final offsets in the constant buffer change for some values. #8486 bumps the alignment up to 64B from 32B ensuring each tensor starts at a 64B offset. The issue is that we need to know alignment information in the streams dialect but don't yet know the target information in order to assign a real minimum alignment. I'll need to work on that in subsequent changes but if we can get to a happy default for now that'd be great.

**Comment by antiagainst** [comment]
Awesome, thanks Ben for the quick fix! :D Yeah, it's architecture specific. Though I don't think memory technologies under the hood differ much; so I have faith that we can reach a reasonable default to carry us forward for a while. :)
