### ISSUE TITLE
Problem about running IREE bytecode modules on QEMU-based RISC-V system

### ISSUE THREAD

**Issue by Jench2103** [google/iree#8493]
Hi, 
I am trying to build and run IREE bytecode modules on QEMU RISC-V 64-bit Linux emulator refer to [RISC-V cross-compilation - IREE](https://google.github.io/iree/building-from-source/riscv/). I'm working in a docker container which is based on ubuntu 20.04 image on an x86 architecture computer.

However, I encountered the error message after typed in the [Run the RISC-V emulation](https://google.github.io/iree/building-from-source/riscv/#:~:text=Run%20the%20RISC%2DV%20emulation) command:
```
$ ${QEMU_BIN} \
    -cpu rv64 \
    -L ${RISCV_TOOLCHAIN_ROOT}/sysroot/ \
    ../iree-build-riscv/iree/tools/iree-run-module \
    --driver=vmvx \
    --module_file=/tmp/simple_abs_vmvx.vmfb \
    --entry_function=abs \
    --function_input=f32=-5
Error while loading ../iree-build-riscv/iree/tools/iree-run-module: No such file or directory
```

Before started the emulation, I followed almost all instructions in the document except for executing `build_tools/riscv/riscv_bootstrap.sh`. For some reasons, I want to download the toolchains and QEMU binary by myself: [rvv-llvm-toolchain.tar.bz2](https://docs.google.com/open?id=13q6sYVlae-hRrgj7SNlvbJFYI3Q8sCI4) and [riscv-qemu-v5.2.0-rvv-rvb-zfh-856da0e-linux-ubuntu.tar.gz](https://docs.google.com/uc?export=download&id=1JkLana7CGeD2wfwn8shHQxcYrv3j1l9s). 

I have exported environment variables `RISCV_TOOLCHAIN_ROOT` and `QEMU_BIN` according to the unzip destinations of the two compressed files.

The following is my full steps:

- Install prerequisites
  ```shell
  ## Add kitware's repository for cmake to apt sources list
  $ sudo apt update \
      && sudo apt install -y software-properties-common lsb-release \
      && sudo apt clean all
  $ wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
      | gpg --dearmor - | \
      sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
  $ sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
  
  ## Install packages
  $ sudo apt install -y cmake ninja-build clang lld libncurses5
  ```

- Download toolchain
  ```shell
  $ pip install gdown
  $ export PATH=$PATH:"$HOME/.local/bin"
  $ gdown --id 13q6sYVlae-hRrgj7SNlvbJFYI3Q8sCI4 -O /workspace/system/riscv/
  $ tar jxpf /workspace/system/riscv/rvv-llvm-toolchain.tar.bz2 -C /workspace/system/riscv/
  $ export RISCV_TOOLCHAIN_ROOT=/workspace/system/riscv/rvv-llvm-toolchain
  ```

- Download QEMU binary
  ```shell
  $ mkdir -p /workspace/system/riscv/iree-qemu
  $ gdown --id 1JkLana7CGeD2wfwn8shHQxcYrv3j1l9s -O /workspace/system/riscv/
  $ tar zxpf /workspace/system/riscv/riscv-qemu-v5.2.0-rvv-rvb-zfh-856da0e-linux-ubuntu.tar.gz \
      -C /workspace/system/riscv/iree-qemu/
  $ export QEMU_BIN=/workspace/system/riscv/iree-qemu/bin/qemu-riscv64
  ```

- Clone IREE source code
  ```shell
  $ git clone https://github.com/google/iree.git /workspace/system/riscv/iree
  $ cd /workspace/system/riscv/iree
  $ git submodule update --init
  ```

- Configure and build
  ```shell
  ## Host configuration
  $ cmake -GNinja -B ../iree-build/ \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_INSTALL_PREFIX=../iree-build/install \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      .
  $ cmake --build ../iree-build/ --target install
  
  ## Target configuration
  $ cmake -GNinja -B ../iree-build-riscv/ \
      -DCMAKE_TOOLCHAIN_FILE="./build_tools/cmake/riscv.toolchain.cmake" \
      -DIREE_HOST_BINARY_ROOT=$(realpath ../iree-build/install) \
      -DRISCV_CPU=rv64 \
      -DIREE_BUILD_COMPILER=OFF \
      -DRISCV_TOOLCHAIN_ROOT=${RISCV_TOOLCHAIN_ROOT} \
      .
  ```

- Running IREE modules on QEMU RISC-V system
  ```shell
  $ ../iree-build/install/bin/iree-translate \
      -iree-mlir-to-vm-bytecode-module \
      -iree-hal-target-backends=vmvx \
      iree/samples/models/simple_abs.mlir \
      -o /tmp/simple_abs_vmvx.vmfb
  
  $ ${QEMU_BIN} \
      -cpu rv64 \
      -L ${RISCV_TOOLCHAIN_ROOT}/sysroot/ \
      ../iree-build-riscv/iree/tools/iree-run-module \
      --driver=vmvx \
      --module_file=/tmp/simple_abs_vmvx.vmfb \
      --entry_function=abs \
      --function_input=f32=-5
  ```

Did I do anything wrong? Thanks!

**Comment by Jench2103** [comment]
Thanks for your help!!!

However, I got another error while starting QEMU emulation after the `iree-run-module` appeared in `../iree-build-riscv/iree/tools/`:
```
I /workspace/system/riscv/iree/iree/tools/utils/vm_util.cc:199] Creating driver and device for 'vmvx'...
Error in cpuinfo: processor architecture is not supported in cpuinfo
EXEC @abs
result[0]: hal.buffer_view
f32=5
```

**Comment by benvanik** [comment]
That's just cpuinfo being cpuinfo - you can ignore it (we're going to be removing cpuinfo at some point #8469). It just means we can't detect the thread count automatically - you still got your result.

**Comment by Jench2103** [comment]
Oh, I understand. Thanks for your explanation!

**Comment by benvanik** [comment]
No problem, and thanks for reminding me it doesn't support RISCV yet! Helps me prioritize removing it :)
