### ISSUE TITLE
CI checks fail cloning

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#85]
The CI check for code style seems to always fail with an error like:

```
Run git clone https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE --no-checkout --no-tags
  git clone https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE --no-checkout --no-tags
  git checkout $GITHUB_SHA
  shell: /bin/bash -e {0}
Cloning into '/home/runner/work/iree/iree'...
fatal: reference is not a tree: 878dbb61141a3d91c59f419f5ea5c99d8f75c387
##[error]Process completed with exit code 128.
```

In fact, I don't think this check has ever worked. Here are various PRs where it has failed:
https://github.com/google/iree/pull/80/checks?check_run_id=268891759
https://github.com/google/iree/pull/62/checks?check_run_id=261297673
https://github.com/google/iree/pull/84/checks?check_run_id=269955914

**Comment by GMNGeoffrey** [comment]
Maybe we should disable this until it works?

**Comment by benvanik** [comment]
Fixed (in theory!) - though it'd be nice to figure out how to get the clang format checks to show up inline in the files changed - instead it just shows that clang-format failed in the yaml file.
