### ISSUE TITLE
Prototype Split-K support for matmul

### ISSUE THREAD

**Issue by ThomasRaoux** [google/iree#8563]
On large GPUs it is hard to have enough parallelism in GEMM to all the GPU cores available. In order to get extra parallelism we can split the reduction dimension to between a parallel and reduction dimension and create a second dispatch doing the remaining of the reduction as a second dispatch. 
The downside of this is that it will increase the memory and bandwidth usage but the extra parallelism should help significantly "small" gemm performance.

This transformation can be done at the linalg level before dispatch region creation:

```
 %D = linalg.matmul  ins(%A, %B: tensor<MxKxf32>, tensor<KxNxf32>)  outs(%C: tensor<MxNxf32>)  -> tensor<MxNxf32>
```
to
```
%A0 = tensor.expand_shape %A, [0], [1, 2] : tensor<MxKxf32> -> tensor<MxK0xK1xf32>
%B0 = tensor.expand_shape %B, [0, 1], [2] : tensor<KxBxf32> -> tensor<K0xK1xNxf32>
%I = init_tensor[M, N, K0]  -> tensor<MxNxK0> 
%C0 = linalg.fill (%C0_f : f32, %I : tensor<MxNxK0>) -> tensor<MxNxK0> 
%C1 = linalg.generic {
  indexing_maps = [
    affine_map<(m, n, k0, k1) -> (m, k0, k1)>,
    affine_map<(m, n, k0, k1) -> (k0, k1, n)>,
    affine_map<(m, n, k0, k1) -> (m, n, k0)>
  ],
  iterator_types = ["parallel", "parallel", "parallel", "reduction"] }
    ins(%A0, %B0 : tensor<MxK0xK1xf32>, tensor<K0xK1xNxf32>)
   outs(%C0 : tensor<MxNxK0xf32>) {
    ^bb(%a: f32, %b: f32, %c: f32) :
      %d = arith.mulf %a, %b: f32
      %e = arith.addf %c, %d: f32
      linalg.yield %e : f32
  } -> tensor<MxNxK0>
  %D = linalg.generic {
  indexing_maps = [
    affine_map<(m, n, k) -> (m, n, k)>,
    affine_map<(m, n, k) -> (m, n)>
  ],
  iterator_types = ["parallel", "parallel", "reduction"] }
    ins(%C1 : tensor<MxNxK0xf32>)
    outs(%C : tensor<MxNxf32>) {
    ^bb(%a: f32, %b: f32) :
      %c = arith.addf %a, %b: f32
      linalg.yield %c : f32
  } -> tensor<MxNxf32>
```

Those ops can then go through dispatch creation which will fuse the linalg and first generic op into one dispatch and the following reduction along with consumers into a second dispatch region.

We then need to match the 1st linalg.generic to go through the same codegen path as matmul named op. This is equivalent to a batch_matmul where the batch dimension is the inner dimension and we should treat it the same.

Then the last part is to decide when to apply the transformation and by what factor should the K dimension be split. Since this has to be done before dispatch region creation we need to do the transformation before getting to the codegen part. However this is a problem several transformation would run into (like mmt4d)

**Comment by MaheshRavishankar** [comment]
> Those ops can then go through dispatch creation which will fuse the linalg and first generic op into one dispatch and the following reduction along with consumers into a second dispatch region.

Is this a typo? What is "fuse linalg and first generic op" mean?

**Comment by MaheshRavishankar** [comment]
Have you thought about using atomics?

**Comment by ThomasRaoux** [comment]
> > Those ops can then go through dispatch creation which will fuse the linalg and first generic op into one dispatch and the following reduction along with consumers into a second dispatch region.
> 
> Is this a typo? What is "fuse linalg and first generic op" mean?

There is 1 linalg.fill and 2 generic op. The fill and generic will be one dispatch region and the reduce + consumers will be a second dispatch region.

**Comment by MaheshRavishankar** [comment]
Another question. How do you decide `K0` and `K1`?

**Comment by ThomasRaoux** [comment]
> Another question. How do you decide `K0` and `K1`?

that's part of the heuristic

**Comment by ThomasRaoux** [comment]
> Have you thought about using atomics?

This is something we discussed and it has the problem that it causes non deterministic results for float, and since this is not what neither libraries and other frameworks do I would rather start with well beaten path

**Comment by antiagainst** [comment]
Cool stuff, thanks Thomas!

**Comment by nicolasvasilache** [comment]
This is fine as a first stab.
Longer-term, it will likely be better to evolve a LinalgExt.ReduceOp that can do this automatically and have a different phase ordering.
This would be introduce by simple tiling and lowering to concrete parallelism would introduce the other ops.

**Comment by nicolasvasilache** [comment]
Fun trivia: the transformation from conv / normalization to group conv / group normalization is ~50% of this transformation.
They just stop at splitting into (parallel, reduction) and avoid the harder part :)

**Comment by MaheshRavishankar** [comment]
> This is fine as a first stab. Longer-term, it will likely be better to evolve a LinalgExt.ReduceOp that can do this automatically and have a different phase ordering. This would be introduce by simple tiling and lowering to concrete parallelism would introduce the other ops.

We just spent a whole bunch of time moving tiling out of Flow (i.e. this level). If we add it back, it needs to be very targeted. I dont want to keep revisiting the phase ordering issue, feels like a hamster on  a wheel.

**Comment by ThomasRaoux** [comment]
First step is under review:
https://reviews.llvm.org/D122045

The second step of getting iree to do good codegeneration is under progress by Nirvedh

**Comment by ThomasRaoux** [comment]
This is done and us currently controlled by command line. This gives significant improvements on some shapes with large K and small MxN. A better control will be supported later once IREE infrastructure allows it.
