### ISSUE TITLE
VM::ConversionPass: Assertion `isConstFloatBuildableWith<SZ>(value, value.getType())' failed.

### ISSUE THREAD

**Issue by silvasean** [google/iree#8714]
**Describe the bug**

Assertion failure inside VM::ConversionPass

Full error log: https://gist.github.com/silvasean/99dec1502b7e700989ab4389cdcaf25b

**To Reproduce**

```
$ iree-compile --iree-hal-target-backends=dylib-llvm-aot core-input.mlir
```

core-input.mlir

```
#map = affine_map<(d0) -> (d0)>
module attributes {torch.debug_module_name = "ArangeNegativeStartFloatModule"} {
  func @forward() -> tensor<?xf32> {
    %c1_i64 = arith.constant 1 : i64
    %cst = arith.constant -1.400000e+00 : f64
    %cst_0 = arith.constant 5.700000e+00 : f64
    %0 = arith.truncf %cst : f64 to f32
    %1 = arith.truncf %cst_0 : f64 to f32
    %2 = arith.sitofp %c1_i64 : i64 to f32
    %3 = arith.subf %1, %0 : f32
    %4 = arith.divf %3, %2 : f32
    %5 = math.ceil %4 : f32
    %6 = arith.fptoui %5 : f32 to i64
    %7 = arith.index_cast %6 : i64 to index
    %8 = linalg.init_tensor [%7] : tensor<?xf32>
    %9 = linalg.generic {indexing_maps = [#map], iterator_types = ["parallel"]} outs(%8 : tensor<?xf32>) {
    ^bb0(%arg0: f32):
      %10 = linalg.index 0 : index
      %11 = arith.index_cast %10 : index to i64
      %12 = arith.sitofp %11 : i64 to f32
      %13 = arith.mulf %2, %12 : f32
      %14 = arith.addf %0, %13 : f32
      linalg.yield %14 : f32
    } -> tensor<?xf32>
    return %9 : tensor<?xf32>
  }
}
```

**Comment by benvanik** [comment]
This is an f64 issue - they aren't currently supported and will need to be truncated (we do this on the MHLO path today).

**Comment by silvasean** [comment]
Is there a pre-existing pass for doing the truncation?

**Comment by silvasean** [comment]
Heh, I just realized that this whole computation can be constant folded to a single index... I will work to add some upstream folders here too.

**Comment by benvanik** [comment]
https://github.com/google/iree/blob/main/iree/compiler/InputConversion/MHLO/LegalizeInputTypes.cpp is currently doing the truncation on the MHLO path (it's pretty old/fragile) - there's also https://github.com/google/iree/blob/main/iree/compiler/Codegen/Common/DemoteF32ToF16.cpp which looks like a more general implementation that could be reused.

**Comment by benvanik** [comment]
We should really unify these passes - if we had them on the IREE side then we could just make them a flag on the compiler instead of requiring configuration. I can take a crack at that tomorrow.
