### ISSUE TITLE
[Vulkan] Numerical failures on many FP32 TFLite models

### ISSUE THREAD

**Issue by mariecwhite** [google/iree#8733]
Seeing large numerical differences between IREE Vulkan and TFLite on FP32 models.

#### albert_test.py
```
I0401 10:03:16.533273 139983536047936 test_util.py:72] Max error (0): nan
I0401 10:03:16.533511 139983536047936 test_util.py:72] Max error (1): nan
```
(mlir files too large)

#### deeplab_v3_test.py
```
I0401 10:02:52.230115 140678299027264 test_util.py:72] Max error (0): 7.042989
```
[tflite.mlir.zip](https://github.com/google/iree/files/8399970/tflite.mlir.zip)
[tosa.mlir.zip](https://github.com/google/iree/files/8399967/tosa.mlir.zip)

#### east_text_detector_test.py
```
I0401 10:03:00.999032 140287240742720 test_util.py:72] Max error (1): 159.195740
```
[tflite.mlir.zip](https://github.com/google/iree/files/8399992/tflite.mlir.zip)
[tosa.mlir.zip](https://github.com/google/iree/files/8399993/tosa.mlir.zip)

#### efficientnet_lite0_test.py
```
I0401 10:03:01.499392 140027516471104 test_util.py:72] Max error (0): 0.618559
```
[tflite.mlir.zip](https://github.com/google/iree/files/8400000/tflite.mlir.zip)
[tosa.mlir.zip](https://github.com/google/iree/files/8400002/tosa.mlir.zip)

#### inception_v4_test.py
```
I0401 10:04:05.200421 140588094011200 test_util.py:72] Max error (0): 0.698596
```
(mlir files too large)

#### mobilenet_v2_test.py
```
I0401 10:02:59.006421 139725152675648 test_util.py:72] Max error (0): 0.913395
```
[tflite.mlir.zip](https://github.com/google/iree/files/8400032/tflite.mlir.zip)
[tosa.mlir.zip](https://github.com/google/iree/files/8400034/tosa.mlir.zip)

**Comment by antiagainst** [comment]
Oh no. How can I reproduce this?

**Comment by mariecwhite** [comment]
To see a comparison between IREE and TFLite, you'll need to run the test in iree-samples:

```
git clone https://github.com/<github_handle>/iree-samples
cd iree-samples

./setup_venv.sh
source iree-samples.venv/bin/activate

lit -a tflitehub/deeplab_v3_test.py
```

**Comment by antiagainst** [comment]
Identified the issue. In a fused `linalg.pooling_nhwc_sum ` and `linalg.generic` dispatch, both are tiled into thread-level, but `linalg.pooling_nhwc_sum` is not vectorized and turned into loops later while `linalg.generic` is vectorized. This causes issues later in bufferization---`memref.alloc` for workgroup memory was created to hold inputs/results to `linalg.pooling_nhwc_sum` but we are in thread-level there.

**Comment by antiagainst** [comment]
Hi @mariecwhite, hopefully #8994 addresses the issue. Could you double check after it's picked up in a new Python release? I didn't figure out an easy way to build all IREE Python wrappers and connect with iree-samples. Thanks!

Keep it open until confirmed by @mariecwhite.

**Comment by mariecwhite** [comment]
@antiagainst All models are now passing except for albert_test.py. I'll close this and create a new one just for albert_test.py.
