### ISSUE TITLE
Slow compilation of mobilebert-baseline-tf2-quant.tflite.mlir

### ISSUE THREAD

**Issue by okkwon** [google/iree#8734]
The quantized model takes very long time to compile. A few findings:

1. There are about 1500 dispatches.
2. Some of the dispatches have a large number of LLVM instructions.

How to reproduce:
1. Setup the IREE build with the benchmark suites:
```
mkdir release_build && cd release_build
cmake -GNinja -DIREE_BUILD_BENCHMARKS=ON -DIREE_IMPORT_TFLITE_PATH=/usr/local/google/home/okwan/.venv/bin/iree-import-tflite ​​-DIREE_ENABLE_ASSERTIONS=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DIREE_ENABLE_LLD=ON ..
ninja iree-benchmark-suites
```
2. The last one, which is the quant model, takes very long time. Type ctrl+C to break.
3. Run this command to dump IR for a few passes.
```
iree-compile --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=dylib-llvm-aot --iree-input-type=tosa --iree-llvm-target-triple=aarch64-none-linux-android29 --mlir-print-op-on-diagnostic=false benchmark_suites/TFLite/mobilebert-baseline-tf2-quant.tflite.mlir -o tmp.vmfb -print-ir-before=tosa-to-linalg -print-ir-before=iree-codegen-tile-and-distribute-to-workgroups -print-ir-before=iree-convert-to-llvm -print-ir-after=iree-convert-to-llvm --mlir-disable-threading --mlir-elide-elementsattrs-if-larger=1
```

The attached is part of the dump. The dispatch 6 shows the issue.
[dispatch_6_before_and_after_convert_to_LLVM.txt](https://github.com/google/iree/files/8400180/dispatch_6_before_and_after_convert_to_LLVM.txt)

**Comment by hanhanW** [comment]
Thanks for all the good finding, @okkwon!

It looks like the quantized matmul configuration is bad. The default configuration is too progressive, which introduces many LLVM instructions after vector unrolling. We can set a different configuration for quantized matmul cases for ARM codegen.

**Comment by benvanik** [comment]
Is there a way to change the default overall? Anything that creates thousands of instructions that result in compilations of tens of minutes feels like it should be opt-in.
