### ISSUE TITLE
Windows test failures

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#874]
I took some time to triage and get the Windows bazel build running (I was not able to find the magic flags to make CMake happy with the compiler choices).

The good news is that everything except TensorFlow builds cleanly, and I was able to get TensorFlow parts building (and all tests passing) by sprinkling the typical "#undef ERROR" through the stream executor headers (which we shouldn't even need but do for now).

Test results were a bit surprising. There was one failure in the Python bindings that smells of UB of some kind. The rest are spurious mismatches when running through Vulkan. Note that a lot of the Vulkan-related tests do pass, so I was not able to immediately see a common culprit.

This is at commit 1035824f5a856e19e3e1f69a085b550d41f33582

Excerpt of test failures:
```
cos:
test/e2e/xla/cos.mlir:10:11: error: CHECK: expected string not found in input
// CHECK: 4xf32=1 0.540302 0.0707372 -0.416147
          ^
<stdin>:2:1: note: scanning from here
4xf32=1 0.540302 0.0707371 -0.416147

convert_int:
test/e2e/xla/convert_int.mlir:10:11: error: CHECK: expected string not found in input
// CHECK: 1xi8=42
          ^
<stdin>:2:1: note: scanning from here
1xi8=0


while:
test/e2e/xla/while.mlir:23:11: error: CHECK: expected string not found in input
// CHECK: i32=4
          ^
<stdin>:2:1: note: scanning from here
i32=1


//bindings/python/pyiree/rt:function_abi_test:
FAIL: test_static_arg_dtype_mismatch (__main__.FunctionAbiTest)
test_static_arg_dtype_mismatch (__main__.FunctionAbiTest)
----------------------------------------------------------------------
ValueError: Mismatched buffer format (received: l, expected: f): For argument = [[[0 0 0 ... 0 0 0]
AssertionError: "Mismatched\ buffer\ format\ \(received:\ i,\ expected:\ f\)" does not match "Mismatched buffer format (received: l, expected: f): For argument =



```

**Comment by ScottTodd** [comment]
I saw a similar floating point precision test failure with `test/e2e/xla/cos.mlir` on Linux with Vulkan earlier this week. There were other errors too, which I don't think I recorded - they may match the rest of what you found.

We don't have Vulkan tests running on Kokoro yet, as that requires SwiftShader or a physical GPU. We weren't sure how to configure SwiftShader to work with RBE, but we do have RBE disabled right now anyway... might be a good time to try.

**Comment by stellaraccident** [comment]
It takes ~2-3 minutes to build/run tests on my workstation without RBE or
any caching -- can we just get bigger VMs? I continue to be worried about a
dependency on such a specific piece of technology for a project that is not
anywhere near the norm that it was built for. It'd be nice to just have
SwiftShader built/installed on the VM images and the appropriate env vars
setup to find the ICD files. This is what I do on my testing VM.

I'd like to avoid layers of complicated/opaque infra if a sensible ~once a
month process (to update a VM) and/or larger provisioned systems can take
care of it for us.

**Comment by ScottTodd** [comment]
cc @GMNGeoffrey 

We tried VMs with 64 cores on Linux and didn't notice a significant speed-up over using 32 cores (both seemed to take ~20 minutes to build/test the full suite). With no caching, that could mean a 20 minute run blocking each submit action. That seemed to be just around the limit that we'd be comfortable with.

We can try 96 cores, and other changes (e.g. to the targets built, to the compiler flags). I agree that setting up SwiftShader on the images directly makes sense.

We could also go for a hybrid approach, like use RBE for testing the compiler and integrations and using local VMs with SwiftShader for the Vulkan runtime portions.

**Comment by stellaraccident** [comment]
On Fri, Feb 28, 2020 at 10:45 AM Scott Todd <notifications@github.com>
wrote:

> cc @GMNGeoffrey <https://github.com/GMNGeoffrey>
>
> We tried VMs with 64 cores on Linux and didn't notice a significant
> speed-up over using 32 cores (both seemed to take ~20 minutes to build/test
> the full suite). With no caching, that could mean a 20 minute run blocking
> each submit action. That seemed to be just around the limit that we'd be
> comfortable with.
>

You probably need SSDs or some kind of large ram disk. On my machine, it
pegs 64 cores and shows on the order of ~20-30% utilization of the IO
bandwidth to the RAID of SSDs. There is no way that spinning platters would
keep up with that.

**Comment by GMNGeoffrey** [comment]
Regarding the original issue, I recall @MaheshRavishankar was seeing some flakes related to floating point precision on Vulkan.

The CI VMs are already using SSD, a 100GB boot disk and a 375GB local scratch disk.

I wouldn't say that we weren't sure how to set up swiftshader. It's just work and we haven't done it yet. RBE supports custom docker images. Stella you don't have `--disk_cache` in your bazelrc?

**Comment by benvanik** [comment]
(technically not flakes, but normal acceptable diffs in differing implementations - more reason to have a non-filecheck-based test tool like what you're working on with check :)

**Comment by stellaraccident** [comment]
On Fri, Feb 28, 2020 at 10:56 AM Geoffrey Martin-Noble <
notifications@github.com> wrote:

> Regarding the original issue, I recall @MaheshRavishankar
> <https://github.com/MaheshRavishankar> was seeing some flakes related to
> floating point precision on Vulkan.
>
The floating point precision is one thing. There are a number of those
tests that are reporting incorrect integer results (which could be rooted
in float-ish issues I guess) and that is what caught my attention.


> The CI VMs are already using SSD, a 100GB boot disk and a 375GB local
> scratch disk.
>
> I wouldn't say that we weren't sure how to set up swiftshader. It's just
> work and we haven't done it yet. RBE supports custom docker images. Stella
> you don't have --disk_cache in your bazelrc?
>

I don't think I do on this machine. Plus I get similar results from CMake
builds, which I know doesn't have it.

**Comment by benvanik** [comment]
This bug is a bit too broad - closing in favor of more targeted bugs ("this type of test fails" etc).
