### ISSUE TITLE
Add Mac ARM Python wheels

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#8742]
Please add Mac M1 (ARM) Python wheels to the IREE release!

**Comment by stellaraccident** [comment]
Let me see about bumping this up in priority when I'm back from vacation.

Peter, since you may have done similar things already: do you have any incantations for doing fat or x86-arm cross builds for MacOS? Or do you all have M1 runners?

The last time I looked at this, there was still a lot of rough edges for targeting M1, but since then, I know that @powderluv has gotten through it with IREE --so hopefully we're down to mechanics.

Are the iree-compiler and iree-runtime wheels sufficient? Or do you need the old xla proto importer? If not, we get to avoid building any part of Tensorflow, which is a lot easier (the TF Mac and windows builds have historically been high enough overhead for us that we stopped doing them).

**Comment by stellaraccident** [comment]
Looks like https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html should do the trick with a new enough cmake and pip.

**Comment by powderluv** [comment]
both the hosted GITHUB Runner and the self-hosted don't seem to support M1. The self-hosted could possibly run the agent under rosetta. I will play around with it and report back. 

https://github.com/actions/virtual-environments/issues/2187

**Comment by hawkinsp** [comment]
It looks to me like IREE's wheels are now universal wheels (i.e., the host code is built for ARM?), but if I attempt to use the wheel on a Macbook M1 I get things like this when running a trivial JAX program via IREE:

```
JAX_PLATFORMS=iree python t.py
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/t.py", line 2, in <module>
    print(lax.add(1, 2))
  File "/Users/phawkins/p/jax/jax/_src/lax/lax.py", line 402, in add
    return add_p.bind(x, y)
  File "/Users/phawkins/p/jax/jax/core.py", line 323, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/Users/phawkins/p/jax/jax/core.py", line 326, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/Users/phawkins/p/jax/jax/core.py", line 676, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/Users/phawkins/p/jax/jax/_src/dispatch.py", line 101, in apply_primitive
    return compiled_fun(*args)
  File "/Users/phawkins/p/jax/jax/_src/dispatch.py", line 167, in <lambda>
    return lambda *args, **kw: compiled(*args, **kw)[0]
  File "/Users/phawkins/p/jax/jax/_src/dispatch.py", line 700, in _execute_compiled
    out_flat = compiled.execute(in_flat)
  File "/Users/phawkins/p/jax/jax/_src/iree.py", line 102, in execute
    outputs = self.module_object[self.function_name](*inputs)
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/runtime/function.py", line 129, in __call__
    self._invoke(arg_list, ret_list)
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/runtime/function.py", line 153, in _invoke
    self._vm_context.invoke(self._vm_function, arg_list, ret_list)
RuntimeError: Error invoking function: <vm>:0: UNKNOWN; device not supported in the compiled configuration;
[ 0] bytecode jit_prim_fun_0.main:338 "jit(add)/jit(main)/add"(/Users/phawkins/p/jax/t.py:1:1)
```

Are we perhaps missing an ARM target configuration somewhere?

(The exact same code works on an x86 Mac.)

**Comment by benvanik** [comment]
IIRC there may be an issue with LLVM auto detecting the host configuration in universal builds. If you specify the target CPU directly it should work (`--iree-llvm-target-triple=whatever m1 is`).

**Comment by benvanik** [comment]
ok cool I wasn't imagining things: https://github.com/google/iree/issues/9028

**Comment by hawkinsp** [comment]
`extra_args=["--iree-llvm-target-triple=arm64-apple-darwin21.5.0"],` did the trick, thanks.

I suspect we can close this issue, given the wheels are now universal and the other issue covers the remaining problems I know about.
