### ISSUE TITLE
Slow dispatches from SPIR-V codegen when using f16 types.

### ISSUE THREAD

**Issue by benvanik** [google/iree#8751]
The existing `-iree-flow-demote-f32-to-f16` option had stopped working and when fixed in #8738 it revealed a ~160% regression in the mobilebertsquad f16 benchmarks:
https://gist.github.com/iree-github-actions-bot/a843920d0e69b97c2c9dab8831d41ff9

Attached are the f16 and f32 traces from the above benchmark run showing a 140ms -> 440ms GPU time increase:
[mobilebertsquad-f16-f32-traces.zip](https://github.com/google/iree/files/8403384/mobilebertsquad-f16-f32-traces.zip)

**Comment by antiagainst** [comment]
Thanks Ben. One annoying thing about SPIR-V is its strong typed pointers. We cannot declare the buffer as a runtime array of fp32 and then do type casting arbitrary to some small sized fp16 vector. Instead the buffer must be declared as a runtime array of vector<4xf32> for good memory access and use various tricks and bitcasts to extract and cast at the fine-grained native vector level to be valid. It involves quite a lot of patterns to work cooperatively to achieve the desired code. Took a look, a few things are broken/missing now:

* We'd need the tile sizes for N and K to be some multiple of 8. We'd need different native vector sizes for vector transfer ops (`vector<8xf16>`) and vector computation ops (`vector<4xf16>`). Broken at the moment. 
* `vector.insert_strided_slice` is inserting `vector<4xf16>` into `vector<8x8xf16>` and then extract `vector<8xf16>`. Need a new pattern to directly insert two `vector<4xf16>` into a `vector<8xf16>` to avoid the 2-D vector.
* After a few rounds of API changes, [`vector.bitcast` bubbling patterns](https://github.com/llvm/llvm-project/commit/7630520ae3c5af3f3536a81740cf316d3a21304e) were disconnected and didn't kick in anymore. 
* ...
