### ISSUE TITLE
Error when building for RISC-V 32-bit bare-metal

### ISSUE THREAD

**Issue by chiachia36** [google/iree#8767]
Hi,

Because I want to run some samples on Spike, I tried to build for the 32-bit bare-metal machine.
I followed the steps [here](https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_riscv_cmake.md).
When I ran [RISC-V 32-bit bare-metal target](https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_riscv_cmake.md#risc-v-32-bit-bare-metal-target), I got errors.
Here is my command.
```
cmake -G Ninja -B ../iree-build-riscv/ \
-DCMAKE_TOOLCHAIN_FILE="./build_tools/cmake/riscv.toolchain.cmake" \
-DIREE_HOST_BINARY_ROOT="../iree-build-host/install" \ 
-DRISCV_CPU=rv32-baremetal \
-DIREE_BUILD_TESTS=OFF \ 
-DIREE_BUILD_COMPILER=OFF \
-DIREE_BUILD_SAMPLES=ON \
-DRISCV_TOOLCHAIN_ROOT=${RISCV_TOOLCHAIN_ROOT} \
.
```
Here is the error in CMakeError.log.
```
FAILED: CMakeFiles/cmTC_f589f.dir/CheckIncludeFile.c.o
 /users/student/mr108/cwlu19/ic8/riscv/toolchain/clang/linux/RISCV/bin/clang   -fPIE -std=gnu11 -MD -MT CMakeFiles/cmTC_f589f.dir/CheckInclud    eFile.c.o -MF CMakeFiles/cmTC_f589f.dir/CheckIncludeFile.c.o.d -o CMakeFiles/cmTC_f589f.dir/CheckIncludeFile.c.o -c CheckIncludeFile.c
 CheckIncludeFile.c:1:10: fatal error: 'malloc/malloc.h' file not found
 #include <malloc/malloc.h>
               ^~~~~~~~~~~~~~~~~
 1 error generated.
 ninja: build stopped: subcommand failed.
```
There are several similar errors.

I ran the flow for RISC-V 64-bit Linux machine successfully before, but I got error when running for 32-bit bare-metal machine.

Thanks!

**Comment by GMNGeoffrey** [comment]
Cindy, can you help out here?

**Comment by hcindyl** [comment]
Please make sure you have a rv32 bare-metal compatible toolchain built and link it properly at `-DRISCV_TOOLCHAIN_ROOT=${RISCV_TOOLCHAIN_ROOT}` If you use the prebuilt at `./build_tools/riscv/riscv_bootstrap.sh`, it was built for rv64 linux configuration (as described in the doc) so it won't work with rv32 bare-metal configuration.

You need to rebuild the toolchain with [source repositories](https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_riscv_cmake.md#prerequisites) specifically for rv32 bare-metal

**Comment by chiachia36** [comment]
I got it! I will rebuild it. Thanks a lot!
