### ISSUE TITLE
Questions about RISC-V 32-bit toolchain(Prerequisites of getting started on RISC-V with Cmake)

### ISSUE THREAD

**Issue by chiachia36** [google/iree#8778]
Hi,
I tried to install risc-v 32-bit elf toolchain.
I cloned GNU toolchain from: https://github.com/riscv/riscv-gnu-toolchain (master branch).
Then I did actions below to get tools in riscv32-unknown-elf-gcc.
```
./configure --prefix=/opt/riscv32 --with-arch=rv32imc --with-abi=ilp32d 
make
```
```
riscv32-unknown-elf-addr2line   riscv32-unknown-elf-gcc-nm         riscv32-unknown-elf-nm
riscv32-unknown-elf-ar          riscv32-unknown-elf-gcc-ranlib     riscv32-unknown-elf-objcopy
riscv32-unknown-elf-as          riscv32-unknown-elf-gcov           riscv32-unknown-elf-objdump
riscv32-unknown-elf-c++         riscv32-unknown-elf-gcov-dump      riscv32-unknown-elf-ranlib
riscv32-unknown-elf-c++filt     riscv32-unknown-elf-gcov-tool      riscv32-unknown-elf-readelf
riscv32-unknown-elf-cpp         riscv32-unknown-elf-gdb            riscv32-unknown-elf-run
riscv32-unknown-elf-elfedit     riscv32-unknown-elf-gdb-add-index  riscv32-unknown-elf-size
riscv32-unknown-elf-g++         riscv32-unknown-elf-gprof          riscv32-unknown-elf-strings
riscv32-unknown-elf-gcc         riscv32-unknown-elf-ld             riscv32-unknown-elf-strip
riscv32-unknown-elf-gcc-11.1.0  riscv32-unknown-elf-ld.bfd
riscv32-unknown-elf-gcc-ar      riscv32-unknown-elf-lto-dump
```
But when I went back to steps in [riscv 32-bit baremetal target](https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_riscv_cmake.md#risc-v-32-bit-bare-metal-target), I got error

```
CMake Error at CMakeLists.txt:16 (project):
  The CMAKE_C_COMPILER:

    /users/student/mr108/cwlu19/ic8/riscv-gnu-toolchain/my-32-riscv-gnu-toolchain/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

```

There are not compiler tools in directory I built.
I wonder did I miss any steps so I couldn't have some tools.
Sorry for asking questions about RISCV-V toolchain.
I used [prebuilt RISC-V Tools](https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_riscv_cmake.md#install-prebuilt-risc-v-tools-risc-v-64-bit-linux-toolchain) and didn't met the problem, but I don;t know the problem is about which side.

Thanks a lot!

**Comment by GMNGeoffrey** [comment]
I don't know anything about riscv, but the error message says it's looking for clang, whereas it looks like you have gcc

**Comment by hcindyl** [comment]
As described in the [doc](https://google.github.io/iree/building-from-source/riscv/#optional-configuration), building the RISCV toolchain is a two-step process. You need to build gcc first to build the tools, binutils, and gcc libraries; however, the compiler is actually clang, so you need to build from llvm after you build the gcc artifacts.

**Comment by chiachia36** [comment]
Git it! Thanks a lot!
