### ISSUE TITLE
vulkan__LayerNormalization.run failed on some CI

### ISSUE THREAD

**Issue by hanhanW** [google/iree#8794]
After bumping LLVM/MHLO/TF submodules, this test passed on `cmake_bazel_linux_x86-turing_tensorflow_integrations` but not `cmake_bazel_linux_x86-swiftshader_tensorflow_integrations`.

See https://github.com/google/iree/pull/8792 and one of examples:

https://source.cloud.google.com/results/invocations/e1d786fd-a880-483b-82e7-3c4c8120440a/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-turing%2Fmain/log

**Comment by ScottTodd** [comment]
Sounds like the LayerNormalization test is now passing within tolerance on physical NVIDIA GPUs but is failing outside of tolerance on SwiftShader

https://github.com/google/iree/blob/773e654db9c01ac95e4368f37ddbd29dce1f64d3/integrations/tensorflow/test/python/iree_tf_tests/layers/layers_test.py#L302-L303

physical GPU:
```
I0406 22:24:54.395228 140655995078464 tf_utils.py:258] Floating point difference between ref and tar was within tolerance. Max abs diff: 0.00e+00, atol: 1.00e-06, max relative diff: 0.00e+00, rtol: 1.00e-06
I0406 22:24:54.395596 140655995078464 tf_utils.py:258] Floating point difference between ref and tar was within tolerance. Max abs diff: 1.43e-06, atol: 1.00e-06, max relative diff: 1.01e-06, rtol: 1.00e-06

Max abs diff: 1.43e-06, atol: 1.00e-06, max relative diff: 1.01e-06, rtol: 1.00e-06
```

SwiftShader:
```
I0406 22:29:07.608804 140682285590336 tf_utils.py:258] Floating point difference between ref and tar was within tolerance. Max abs diff: 0.00e+00, atol: 1.00e-06, max relative diff: 0.00e+00, rtol: 1.00e-06
E0406 22:29:07.609251 140682285590336 tf_utils.py:253] Floating point difference between ref and tar was too large. Max abs diff: 3.58e-06, atol: 1.00e-06, max relative diff: 2.53e-06, rtol: 1.00e-06

Max abs diff: 3.58e-06, atol: 1.00e-06, max relative diff: 2.53e-06, rtol: 1.00e-06
```

Could someone more familiar with that test weigh in on if the SwiftShader diff is still okay, or if it indicates a correctness bug in SwiftShader? If it's okay, we should up the tolerance for that test case (or the entire suite?)

**Comment by hanhanW** [comment]
I think it's fine to up the tolerance for the entire suite because they are floating-point comparison. We might need someone to look into if it is a correctness bug in SwiftShader though. For now, let's up the tolerance to turn CI green?

**Comment by antiagainst** [comment]
Sorry, late to this. 0.00000x is a very small difference. I believe it's fine to adjust the threshold. I recall similar internal discussions with @mariecwhite and @bjacob about a 2^-12 difference we fixed previously by adjusting threshold.

**Comment by antiagainst** [comment]
Let me send out a pull request soon.

**Comment by antiagainst** [comment]
Actually Hanhan already included the threshold adjustment patch (https://github.com/google/iree/pull/8792) in the initial post. Thought that was the failing pull request and didn't look into it.. Thanks Hanhan! :)

**Comment by hanhanW** [comment]
And `llvmaot__LayerNormalization.run` is passing after adjusting the threshold. :p
