### ISSUE TITLE
Problem about using simulator and iree-run-module

### ISSUE THREAD

**Issue by chiachia36** [google/iree#8839]
Hi,

There are steps of using RISC-V QEMU and `iree-run-module` to run the model.
I want to do some experiments.
I tried to use Spike and `iree-run-module` to run the module with command 
```
spike --varch=vlen:256 \
../iree-build-riscv/iree/tools/iree-run-module \
  --driver=vmvx \
  --module_file=/tmp/simple_abs_vmvx.vmfb \
  --entry_function=abs \
  --function_input=f32=-5
```

I wonder where the problem is.
The argument setting of spike or `iree-run-module`, or other reasons.
Could you give me some advice or hints?
Thanks!

**Comment by hanhanW** [comment]
Why do you run with `--driver=vmvx`? It should be `dylib`, IIRC.

https://google.github.io/iree/building-from-source/riscv/#optional-configuration

**Comment by chiachia36** [comment]
I followed the command [here](https://google.github.io/iree/building-from-source/riscv/#running-iree-bytecode-modules-on-the-risc-v-system).

I tried to modify `dirver`, but it didn't work.

**Comment by hanhanW** [comment]
The `iree-hal-target-backends` and `driver ` should match. What's the errors?

@hcindyl and @dcaballe can you help on this?

**Comment by hcindyl** [comment]
spike is a system emulator, and `iree-run-module` is built to run on an OS. The build CLIs in the [webdoc](https://google.github.io/iree/building-from-source/riscv/#risc-v-64-bit-linux-target) is specifically for RV64 Linux config, and the QEMU emulator used in the doc is a Linux [user space emulator](https://www.qemu.org/docs/master/user/index.html), instead of the [system emulator](https://www.qemu.org/docs/master/system/index.html) configuration.

To run the binary on spike, it is best to build bare-metal binary that include the workload with binary without the fileIO, see [webdoc](https://google.github.io/iree/deployment-configurations/bare-metal/#compile-the-model-for-bare-metal) and code examples at https://github.com/google/iree/tree/main/iree/samples/static_library and https://github.com/google/iree/tree/main/iree/samples/simple_embedding. 

For the spike simulation, you also need include the  linker script, the crt0 implementation, and the libgloss implementation that matches your machine configuration (a.k.a BSP), to support `-nostartfiles` COPT. See the ARM example at https://github.com/iml130/iree-bare-metal-arm

Both `vmvx` and `dylib` work on the baremetal configuration.

**Comment by chiachia36** [comment]
Thanks for replying.
I will check the document and try again.
Thanks a lot!

**Comment by chiachia36** [comment]
Hi,
I checked the docs and tried.
I have two questions.
1. I want to try the demo in [samples/static_library](https://github.com/google/iree/tree/main/iree/samples/static_library).
I clone the whole project again and build it with command [here](https://github.com/google/iree/tree/main/iree/samples/static_library#instructions), and I get some error messages.
```
CMake Error at build_tools/cmake/iree_cc_binary.cmake:67 (add_executable):
  Target "iree_tools_iree-translate" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:437 (iree_cc_binary)
```
Did I misunderstand the illustration on the website?

2. After I checked  [ https://github.com/google/iree/tree/main/iree/samples/static_library](https://github.com/google/iree/tree/main/iree/samples/static_library) and [https://github.com/google/iree/tree/main/iree/samples/simple_embedding](https://github.com/google/iree/tree/main/iree/samples/simple_embedding), I still confuse about how to use the `.vmfb` file we have.
I check the [website](https://google.github.io/iree/deployment-configurations/bare-metal/#compile-the-model-for-bare-metal).
If I followed the steps here and get the `.vmfb` file how could I run it for the bare-metal target then run on spike?

I'm sorry to ask so many problems.
Thanks!

**Comment by hcindyl** [comment]
> Hi, I checked the docs and tried. I have two questions.
> 
> 1. I want to try the demo in [samples/static_library](https://github.com/google/iree/tree/main/iree/samples/static_library).
>    I clone the whole project again and build it with command [here](https://github.com/google/iree/tree/main/iree/samples/static_library#instructions), and I get some error messages.
> 
> ```
> CMake Error at build_tools/cmake/iree_cc_binary.cmake:67 (add_executable):
>   Target "iree_tools_iree-translate" links to target
>   "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
>   find_package() call is missing for an IMPORTED target, or an ALIAS target
>   is missing?
> Call Stack (most recent call first):
>   iree/tools/CMakeLists.txt:437 (iree_cc_binary)
> ```
> 
> Did I misunderstand the illustration on the website?
> 
Sorry, I was referring to the code, but the CMakeLists.txt for `static_library` is currently set for be built in the host compilation only

https://github.com/google/iree/blob/7f2972c11e626248817f43857216b9188c6f95e3/iree/samples/static_library/CMakeLists.txt#L9-L10

If you remove that condition in the CMakeLists,txt, you also need to update
https://github.com/google/iree/blob/7f2972c11e626248817f43857216b9188c6f95e3/iree/samples/static_library/CMakeLists.txt#L14
with 
```
iree_get_executable_path(_TRANSLATE_TOOL_EXECUTABLE "iree-compile")
```

Then you should be able to build `static_library` and `simple_embedding` samples with the cross-compile bare-metal target, barring the BSP support, similar to https://github.com/iml130/iree-bare-metal-arm/tree/main/samples

> 2. After I checked  [ https://github.com/google/iree/tree/main/iree/samples/static_library](https://github.com/google/iree/tree/main/iree/samples/static_library) and https://github.com/google/iree/tree/main/iree/samples/simple_embedding, I still confuse about how to use the `.vmfb` file we have.
>    I check the [website](https://google.github.io/iree/deployment-configurations/bare-metal/#compile-the-model-for-bare-metal).
>    If I followed the steps here and get the `.vmfb` file how could I run it for the bare-metal target then run on spike?
> 
In these two cases, the `.vmfb` file is converted into the embedded {.c, .h} source code and to be included during building the binary
https://github.com/google/iree/blob/7f2972c11e626248817f43857216b9188c6f95e3/iree/samples/static_library/CMakeLists.txt#L55-L69
and 
https://github.com/google/iree/blob/7f2972c11e626248817f43857216b9188c6f95e3/iree/samples/static_library/create_bytecode_module.c#L8-L20
> I'm sorry to ask so many problems. Thanks!

**Comment by chiachia36** [comment]
Let me make sure I have it right.
After I modified file, `iree/iree/samples/static_library/CMakeList.txt` should look like
```
  7 if(NOT ${IREE_TARGET_BACKEND_DYLIB_LLVM_AOT}
  8   OR NOT ${IREE_HAL_DRIVER_DYLIB})
  9   #  OR NOT ${IREE_BUILD_COMPILER})
 10   return()
 11 endif()
 12
 13 # Set iree-compile binary.
 14 #set(_TRANSLATE_TOOL_EXECUTABLE $<TARGET_FILE:iree_tools_iree-compile>)
 15 iree_get_executable_path(_TRANSLATE_TOOL_EXECUTABLE "iree-compile")
```

After I modified the file, I tried to run command in [static_library](https://github.com/google/iree/tree/main/iree/samples/static_library#instructions) again.

I got error messages.
```
CMake Error at build_tools/cmake/iree_cc_binary.cmake:67 (add_executable):
  Target "iree_tools_iree-translate" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:437 (iree_cc_binary)


CMake Error at build_tools/cmake/iree_cc_binary.cmake:67 (add_executable):
  Target "iree_tools_iree-translate" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:437 (iree_cc_binary)


CMake Error at build_tools/cmake/iree_cc_binary.cmake:67 (add_executable):
  Target "iree_tools_iree-compile" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:449 (iree_cc_binary)


CMake Error at build_tools/cmake/iree_cc_binary.cmake:67 (add_executable):
  Target "iree_tools_iree-compile" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:449 (iree_cc_binary)


CMake Error at build_tools/cmake/iree_cc_library.cmake:103 (add_library):
  Target "iree_compiler_ConstEval_ConstEval" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/compiler/ConstEval/CMakeLists.txt:36 (iree_cc_library)


CMake Error at build_tools/cmake/iree_cc_library.cmake:103 (add_library):
  Target "iree_compiler_ConstEval_Runtime" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/compiler/ConstEval/CMakeLists.txt:57 (iree_cc_library)


CMake Error at build_tools/cmake/iree_cc_library.cmake:103 (add_library):
  Target "iree_compiler_Translation_IREEVM" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/compiler/Translation/CMakeLists.txt:32 (iree_cc_library)


CMake Error at build_tools/cmake/iree_cc_library.cmake:103 (add_library):
  Target "iree_tools_iree_opt_main" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:389 (iree_cc_library)


CMake Error at build_tools/cmake/iree_cc_library.cmake:103 (add_library):
  Target "iree_tools_iree_translate_lib" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:404 (iree_cc_library)


CMake Error at build_tools/cmake/iree_cc_binary.cmake:67 (add_executable):
  Target "iree_tools_iree-opt" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:461 (iree_cc_binary)


CMake Error at build_tools/cmake/iree_cc_binary.cmake:67 (add_executable):
  Target "iree_tools_iree-mlir-lsp-server" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:471 (iree_cc_binary)


CMake Error at build_tools/cmake/iree_cc_binary.cmake:67 (add_executable):
  Target "iree_tools_iree-run-mlir" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:485 (iree_cc_binary)


CMake Error at build_tools/cmake/iree_cc_library.cmake:99 (add_library):
  Target "iree_compiler_ConstEval_Runtime.objects" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/compiler/ConstEval/CMakeLists.txt:57 (iree_cc_library)


CMake Error at build_tools/cmake/iree_cc_library.cmake:99 (add_library):
  Target "iree_compiler_ConstEval_ConstEval.objects" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/compiler/ConstEval/CMakeLists.txt:36 (iree_cc_library)


CMake Error at build_tools/cmake/iree_cc_library.cmake:99 (add_library):
  Target "iree_compiler_Translation_IREEVM.objects" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/compiler/Translation/CMakeLists.txt:32 (iree_cc_library)


CMake Error at build_tools/cmake/iree_cc_library.cmake:99 (add_library):
  Target "iree_tools_iree_translate_lib.objects" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:404 (iree_cc_library)


CMake Error at build_tools/cmake/iree_cc_library.cmake:99 (add_library):
  Target "iree_tools_iree_opt_main.objects" links to target
  "iree::hal::vmvx::registration" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  iree/tools/CMakeLists.txt:389 (iree_cc_library)
```
Did I have to set cmake options [here](https://google.github.io/iree/deployment-configurations/bare-metal/#build-bare-metal-runtime-from-the-source) or add general options [here](https://google.github.io/iree/building-from-source/getting-started/#clone-and-build)?

Thanks!

**Comment by hcindyl** [comment]
Can you share the exact the CMake config you use, for both the host compiler and the cross-compile target? The error log shows you are not following the bare-metal webdoc to set the CMake options. The cross-compilation target should not process `iree/compiler` nor `iree/tools`

Also, please note that building the samples directly from IREE project is not enough to run a system emulation in Spike. You still need the device specific linker script (to match the memory layout) and the crt0. The examples I referred above is used to show how the c API should be used, but you need to add more dependency in your own CMakeLists.txt

**Comment by chiachia36** [comment]
I followed the steps in the issue you mentioned.
Then I modified the file `iree/iree/samples/static_library/CMakeList.txt`
```
  7 if(NOT ${IREE_TARGET_BACKEND_DYLIB_LLVM_AOT}
  8   OR NOT ${IREE_HAL_DRIVER_DYLIB})
  9   #  OR NOT ${IREE_BUILD_COMPILER})
 10   return()
 11 endif()
 12
 13 # Set iree-compile binary.
 14 #set(_TRANSLATE_TOOL_EXECUTABLE $<TARGET_FILE:iree_tools_iree-compile>)
 15 iree_get_executable_path(_TRANSLATE_TOOL_EXECUTABLE "iree-compile")
```
I followed the step [here](https://github.com/google/iree/tree/main/iree/samples/static_library#instructions).
```
cmake -B ../iree-build/ \
  -DIREE_BUILD_SAMPLES=ON \
  -DIREE_TARGET_BACKEND_DEFAULTS=OFF \
  -DIREE_TARGET_BACKEND_DYLIB_LLVM_AOT=ON \
  -DIREE_HAL_DRIVER_DEFAULTS=OFF \
  -DIREE_HAL_DRIVER_DYLIB_SYNC=ON \
  -DIREE_BUILD_COMPILER=ON \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo .
```
Then I still got the error messages I mentioned before.

I also found that after running the script, I want to run the command [here](https://google.github.io/iree/deployment-configurations/bare-metal/#compile-the-model-for-bare-metal), but there is not `iree/tools/iree-compile` in my folder.

**Comment by hcindyl** [comment]
From the CLI you provided, you should find `iree-compile` under `../iree-build/iree/tools/iree-compile`

The CMake build configuration, especially for the host compiler, should still follow https://google.github.io/iree/building-from-source/riscv/#host-configuration

The RISC-V cross compile config should follow https://google.github.io/iree/deployment-configurations/bare-metal/#set-cmake-options

See https://github.com/google/iree/blob/main/build_tools/cmake/build_riscv.sh of the two-step build process.

Again, you still need your own crt0 and linker script to be added into the build process in order to build a binary that can be simulated with Spike. See the ARM example in https://github.com/iml130/iree-bare-metal-arm/blob/e5cc71e2e347efe5fc8fa06afb6e0ece9b44a627/samples/static_library/CMakeLists.txt#L81

**Comment by chiachia36** [comment]
I followed the steps from [here](https://github.com/google/iree/issues/8802#issuecomment-1098772745).
After I git clone the project and set `$RISCV_RV32_NEWLIB_TOOLCHAIN_ROOT` and `$RISCV_CONFIG`, I ran` ./build_tools/cmake/build_riscv.sh`
Then I finished running the script with no errors, but I didn't get `iree-build` folder.
I am confused about the docs you mentioned ([https://google.github.io/iree/building-from-source/riscv/#host-configuration](https://google.github.io/iree/building-from-source/riscv/#host-configuration) and [ https://google.github.io/iree/deployment-configurations/bare-metal/#set-cmake-options]( https://google.github.io/iree/deployment-configurations/bare-metal/#set-cmake-options) ), didn't they run in the script?

Thanks for your friendly reminder, but I think I should solve the problem about building and generating files first, and then I could check the requirements of simulating with Spike?

**Comment by hcindyl** [comment]
If you run the `build_riscv.sh` script, the host compiler is built under `./build-host/`
https://github.com/google/iree/blob/0f80995367c332cd5dd747768ec2265a30eeeb14/build_tools/cmake/build_riscv.sh#L30

where as the riscv artifacts are at `./build-riscv/`
https://github.com/google/iree/blob/0f80995367c332cd5dd747768ec2265a30eeeb14/build_tools/cmake/build_riscv.sh#L54

Those CMake options for the bare-metal configuration are set in the riscv.toolchain.cmake file
https://github.com/google/iree/blob/0f80995367c332cd5dd747768ec2265a30eeeb14/build_tools/cmake/riscv.toolchain.cmake#L44-L56
and the file is used in 
https://github.com/google/iree/blob/0f80995367c332cd5dd747768ec2265a30eeeb14/build_tools/cmake/build_riscv.sh#L67

**Comment by chiachia36** [comment]
I could find `iree-compile` in `build-host`.
When I ran the command [here](https://github.com/google/iree/tree/7f2972c11e626248817f43857216b9188c6f95e3/iree/samples/static_library#instructions), I still get the error I mentioned before.(https://github.com/google/iree/issues/8839#issuecomment-1098745061)

**Comment by chiachia36** [comment]
After running `build_riscv.sh`, did that mean I could run command [here](https://github.com/google/iree/tree/7f2972c11e626248817f43857216b9188c6f95e3/iree/samples/static_library#instructions) directly?
`cmake --build ../iree-build/ --target iree_samples_static_library_demo`
Or I still have to run 
```
cmake -B ../iree-build/
  -DIREE_BUILD_SAMPLES=ON \
  -DIREE_TARGET_BACKEND_DEFAULTS=OFF \
  -DIREE_TARGET_BACKEND_DYLIB_LLVM_AOT=ON \
  -DIREE_HAL_DRIVER_DEFAULTS=OFF \
  -DIREE_HAL_DRIVER_DYLIB_SYNC=ON \
  -DIREE_BUILD_COMPILER=ON \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo .
```

Because I am confused that tools `build_riscv.sh` generated still couldn't  work for running sample.

**Comment by hcindyl** [comment]
> After running `build_riscv.sh`, did that mean I could run command [here](https://github.com/google/iree/tree/7f2972c11e626248817f43857216b9188c6f95e3/iree/samples/static_library#instructions) directly? `cmake --build ../iree-build/ --target iree_samples_static_library_demo` Or I still have to run
> 
> ```
> cmake -B ../iree-build/
>   -DIREE_BUILD_SAMPLES=ON \
>   -DIREE_TARGET_BACKEND_DEFAULTS=OFF \
>   -DIREE_TARGET_BACKEND_DYLIB_LLVM_AOT=ON \
>   -DIREE_HAL_DRIVER_DEFAULTS=OFF \
>   -DIREE_HAL_DRIVER_DYLIB_SYNC=ON \
>   -DIREE_BUILD_COMPILER=ON \
>   -DCMAKE_BUILD_TYPE=RelWithDebInfo .
> ```
> 
Unfortunately, neither options are applicable. The CLI in `iree/samples/static_library/README.md` does not work for cross compile, and `iree/samples/static_library/CMakeLists.txt` is not configured to compile for RISC-V either, so you will need more surgeries to make the targets here built for RISC-V. I brought up this directory because you can reference the {.c, .h} here to build the no-file-system example, but you need to reconfigure the CMakeLists.txt to make it work for cross-compilation.

On the other hand, after you run `build_riscv.sh` successfully, you should see executables built under `build-riscv/iree/samples/simple_embedding`, as artifacts built with RV32 configuration. In that directory, both c code and the CMakeLists.txt are set to support cross-compilation (so we can run rv32 bare-metal CI). Still, it will not allow you to execute the binary on spike, for which you still need to hook up with crt0 and device-specific linker script.
> Because I am confused that tools `build_riscv.sh` generated still couldn't work for running sample.
> 
> When I run the command, I get error messages like I mentioned before([#8839 (comment)](https://github.com/google/iree/issues/8839#issuecomment-1098808401)) If I ignore it and run `cmake --build ../iree-build/ --target iree_samples_static_library_demo`, I get `make: *** No rule to make target 'iree_samples_static_library_demo'. Stop.`

**Comment by chiachia36** [comment]
Thanks for helping.
I will try to use `iree-compile` to compile model for bare-metal with command [here](https://google.github.io/iree/deployment-configurations/bare-metal/#compile-the-model-for-bare-metal), and convert to binary for running on Spike!

**Comment by dcaballe** [comment]
Hi @chiachia36, is this issue already solved?

Thanks!
