### ISSUE TITLE
Copy the two CUDA files we need on bots so we can build it by default.

### ISSUE THREAD

**Issue by benvanik** [google/iree#8847]
Currently all of the CUDA compiler and runtime code is only built on one bot and only on postsubmit. That makes it effectively an experimental feature and prone to incidental breakage. To enable the CUDA codepath to be supported by the broader team and community we must have at least presubmits compiling it. This will reduce the number of postsubmit detected build issues that are happening ~1-2 times a week.

nvidia has a supported install path that is much smaller than the normal install methods and platform agnostic via https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#tarball-zipfile-overview

The cuda.h file we need for the runtime is in here (`include/cuda.h`):
https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/linux-x86_64/

The libdevice.10.bc file we need for the compiler is here (`nvvm/libdevice/libdevice.10.bc`):
https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/linux-x86_64/

The entirety of these together is ~37MB, vs the 3.5GB normal toolkit install. As neither of these two files are platform dependent every build configuration should have them available and we should be building with CUDA on by default. The bots can extract these and then we can point cmake at the paths by setting `CUDAToolkit_INCLUDE_DIRS` and `IREE_CUDA_LIBDEVICE_PATH` ourselves.

Update: nvidia recommends just setting `CUDAToolkit_ROOT` to the extraction path, then FindCUDAToolkit should (in theory) work ([example here](https://github.com/NVIDIA/build-system-archive-import-examples/tree/main/cmake/1_FindCUDAToolkit)). That may be easiest, as all we need to do is:
```
mkdir cuda_toolkit
cd cuda_toolkit/
wget -q0- https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/linux-x86_64/cuda_cudart-linux-x86_64-11.6.55-archive.tar.xz | tar -xf
wget -q0- https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/linux-x86_64/cuda_nvcc-linux-x86_64-11.6.124-archive.tar.xz | tar -xf
...
cmake ... -DCUDAToolkit_ROOT=cuda_toolkit/
```

**Comment by stellaraccident** [comment]
This is a good find -- I had looked for something like this previously and not found it.

I'm going to try to login later today to do some work and watching docker images build seems like the right kind of post sickness reentry task :)

**Comment by benvanik** [comment]
that sounds good - we already have the LIBDEVICE cmake variable anyway
