### ISSUE TITLE
custom op 'linalg.pad_tensor' is unknown

### ISSUE THREAD

**Issue by pshung** [google/iree#8891]
**Describe the bug**

I've compiled a tensorflow saved_model using 'iree-import-tf'.
The generated MLIR contains the "linalg.pad_tensor" operation.
When I compile using 'iree-compile', it shows that "custom op 'linalg.pad_tensor' is unknown"

I find there is a patch that moving this operation to 'tensor' dialet. 
https://reviews.llvm.org/D117892

Is there a consistency issue between the front end and the MLIR?

BTW, the tool 'iree-import-tf' is installed by python pip. 
How can I build 'iree-import-tf' from the source?

**Comment by hanhanW** [comment]
It's been moved for a while. The latest [release/tag](https://github.com/google/iree/tags) should contain the change. You won't hit the issue if you update the package.

For building it from source, please see https://google.github.io/iree/building-from-source/python-bindings-and-importers/#python-bindings-and-importers

**Comment by pshung** [comment]
I'm using the latest tag 'candidate-20220413.106'
It has the same issue.
