### ISSUE TITLE
Couldn't find class 'I32BitEnumAttrCase'

### ISSUE THREAD

**Issue by qianqing13579** [google/iree#8892]
I have a problem about iree as follows when I install it:
![image](https://user-images.githubusercontent.com/8730200/163335375-b8bffb11-d5d6-4bff-9dd7-a239e280c4d1.png)

**Comment by qianqing13579** [comment]
which branch of llvm-project should I use?

**Comment by antiagainst** [comment]
The recent LLVM integration replaced `BitEnumAttr` with `I32BitEnumAttr`. Please make sure you update git submodules; that would update the repo to track the proper LLVM/MLIR project commit.

**Comment by antiagainst** [comment]
Nothing actionable additionally. Closing.
