### ISSUE TITLE
Missing simple_module_test_bytecode_module.h simple_compute_test_module.h in Samples

### ISSUE THREAD

**Issue by powderluv** [google/iree#90]
Samples fail to build with 
....
-Wno-shadow -Wno-missing-noreturn -std=gnu++14 -MD -MT iree/samples/hal/CMakeFiles/iree_samples_hal_simple_compute_test.dir/simple_compute_test.cc.o -MF iree/samples/hal/CMakeFiles/iree_samples_hal_simple_compute_test.dir/simple_compute_test.cc.o.d -o iree/samples/hal/CMakeFiles/iree_samples_hal_simple_compute_test.dir/simple_compute_test.cc.o -c ../iree/samples/hal/simple_compute_test.cc
../iree/samples/hal/simple_compute_test.cc:38:10: fatal error: 'iree/samples/hal/simple_compute_test_module.h' file not found
#include "iree/samples/hal/simple_compute_test_module.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
.....
[2/4] Building CXX object iree/samples/rt/CMakeFiles/iree_samples_rt_bytecode_module_test.dir/bytecode_module_test.cc.o -MF iree/samples/rt/CMakeFiles/iree_samples_rt_bytecode_module_test.dir/bytecode_module_test.cc.o.d -o iree/samples/rt/CMakeFiles/iree_samples_rt_bytecode_module_test.dir/bytecode_module_test.cc.o -c ../iree/samples/rt/bytecode_module_test.cc
../iree/samples/rt/bytecode_module_test.cc:40:10: fatal error: 'iree/samples/rt/simple_module_test_bytecode_module.h' file not found
#include "iree/samples/rt/simple_module_test_bytecode_module.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by stellaraccident** [comment]
I believe this is due to the cc_embed_data rule not having been ported yet to cmake. I had to implement a version of it for oss that worked like our upstream version and got that in on the Basel side last week. It shouldn't be too hard to do on cmake but just hadn't been done yet.

**Comment by powderluv** [comment]
I can add the cmake rule but where to get the file

**Comment by marbre** [comment]
I already wrote a `CMakeLists.txt` to compile `generate_cc_embed_data`. Hence, only the cmake rules to call `iree-translate` and `generate_cc_embed_data` are missing in order to generate the required source and header files. I can send a PR next week if you are interested.

**Comment by GMNGeoffrey** [comment]
Yes please send PRs :-)

**Comment by GMNGeoffrey** [comment]
FYI we now have a cmake CI, although it excludes the samples because of this issue. When we do get them working, I can change the option to add these to the CI, so a PR would be welcome :-)

**Comment by marbre** [comment]
I missed to add a parable comment in my latest PR, but this issue is finally fixed within the master and can be closed.
