### ISSUE TITLE
Migrate to use IREEComprehensiveBufferize in BufferizeCopyOnlyDispatchesPass

### ISSUE THREAD

**Issue by hanhanW** [google/iree#9047]
We'd like to use IREEComprehensiveBufferize in BufferizeCopyOnlyDispatchesPass.

BufferizeCopyOnlyDispatchesPass early bufferizes some ops to memref. Today, it uses IREE old bufferization. The CPU backend is going to use `IREEComprehensiveBufferize` for all kernels. There are difference between `LinalgBufferize` and `IREEComprehensiveBufferize`, which causes issues. We'll hit an assertion when running `IREEComprehensiveBufferize` on early bufferized kernels. If we migrate to use the same bufferization pipeline for copy only dispatches, it works. See https://github.com/google/iree/pull/9035#issuecomment-1116025681

However, there are other issues when migrating it to use comprehensive bufferize. To repro:

1. Patch https://github.com/google/iree/commit/d54523e70fb0a4a21a1860b9ad056aba7ef4b85a
1. Run ctest: `ctest -V -R iree/compiler/Codegen/Common/test/bufferize`

We'll see errors like:

```
428: within split at iree/compiler/src/iree/compiler/Codegen/Common/test/bufferize_copy_only_dispatches.mlir:1 offset :25:5: error: unable to generate copy op within bufferization from type
'memref<?xi32, affine_map<(d0)[s0, s1] -> (d0 * s1 + s0)>>' to
'memref<?x1xi32, affine_map<(d0, d1)[s0, s1, s2] -> (d0 * s1 + s0 + d1 * s2)>>'
428:     flow.dispatch.tensor.store %source_load, %dest, offsets = [%dest_offset_y, %dest_offset_x],
```

**Comment by MaheshRavishankar** [comment]
Trying to fix this in #9092 . I see this transformation during bufferization

```
// -----// IR Dump Before IREEComprehensiveBufferize //----- //
module {
  func @_concatenate_cst_dispatch_1() {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c2 = arith.constant 2 : index
    %cst = arith.constant dense<0> : tensor<2x3xi32>
    %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readwrite:2x5xi32>
    flow.dispatch.tensor.store %cst, %0, offsets = [%c0, %c2], sizes = [2, 3], strides = [%c1, %c1] : tensor<2x3xi32> -> !flow.dispatch.tensor<readwrite:2x5xi32>
    return
  }
}

// -----// IR Dump After IREEComprehensiveBufferize //----- //
module {
  memref.global "private" constant @__constant_2x3xi32 : memref<2x3xi32> = dense<0> {alignment = 128 : i64}
  func @_concatenate_cst_dispatch_1() {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c2 = arith.constant 2 : index
    %0 = memref.get_global @__constant_2x3xi32 : memref<2x3xi32>
    %1 = bufferization.to_tensor %0 : memref<2x3xi32>
    %2 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c0) alignment(64) : memref<2x5xi32>
    memref.assume_alignment %2, 64 : memref<2x5xi32>
    %3 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readwrite:2x5xi32>
    %4 = memref.subview %2[%c0, %c2] [2, 3] [%c1, %c1] : memref<2x5xi32> to memref<2x3xi32, affine_map<(d0, d1)[s0, s1, s2] -> (d0 * s1 + s0 + d1 * s2)>>
    linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%0 : memref<2x3xi32>) outs(%4 : memref<2x3xi32, a\
ffine_map<(d0, d1)[s0, s1, s2] -> (d0 * s1 + s0 + d1 * s2)>>) {
    ^bb0(%arg0: i32, %arg1: i32):
      linalg.yield %arg0 : i32
    }
    return
  }
}
```

The SPIR-V side does not handle constants this way. This is valid only for LLVM path. SPIR-V has its own way of handling it that is more targeted to SPIR-V spec. The bufferization should instead leave the `arith.constant` as is and insert a `bufferization.to_memref` to convert the `tensor` to `memref`.

@matthias-springer I would claim this is an upstream bug since such a lowering is not supported for the SPIR-V compilation path. I havent looked at this recently but the approach described above + `arith::createConstantBufferizePass` will effectively have the same behavior. I dont think the bufferization needs to do much more here....

**Comment by matthias-springer** [comment]
Just to clarify, you need to simply wrap the `arith.constant` op in a `bufferization.to_memref` and then copy this memref into the subspan buffer. Is that correct?

How will the `arith.constant` + `bufferization.to_memref` be lowered then?

You can change the `BufferizationOptions` to get this behavior:
```
// TODO: Add function overload with OpTy template parameter.
opt.denyOperationInFilter(arith::ConstantOp::getOperationName());
opt.allowUnknownOps = true;
```

Ops that are not bufferizable (or deactivated in the filter) will be ignored and wrapped in `to_memref` ops.

**Comment by MaheshRavishankar** [comment]
> How will the `arith.constant` + `bufferization.to_memref` be lowered then?

They should be handled on the IREE CPU backend using these two passes (https://github.com/google/iree/blob/6031ff4080f5755bcc52826a8d41ae7360106ffd/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp#L373). SPIR-V doesnt need special handling in IREE. THe upstream one works just fine.

**Comment by MaheshRavishankar** [comment]
@matthias-springer that worked. All e2e tests pass, but I am seeing this kind of code generated for `LinalgExt` ops.

```
func.func @reverse_dim(%pos: index) -> f32 {
  %input = arith.constant dense<[[1.0, 2.0, 3.0],
                                 [4.0, 5.0, 6.0]]> : tensor<2x3xf32>

  %init = linalg.init_tensor [2, 3] : tensor<2x3xf32>
  %0 = iree_linalg_ext.reverse
         dimensions(dense<0> : tensor<1xi64>)
         ins(%input : tensor<2x3xf32>)
         outs(%init : tensor<2x3xf32>) : tensor<2x3xf32>

  %1 = tensor.extract %0[%pos, %pos] : tensor<2x3xf32>
  return %1 : f32
}
```

bufferizes to

```
#map = affine_map<(d0, d1)[s0, s1, s2] -> (d0 * s1 + s0 + d1 * s2)>
module {
  func.func @reverse_dim(%arg0: index) -> f32 {
    %cst = arith.constant dense<[[1.000000e+00, 2.000000e+00, 3.000000e+00], [4.000000e+00, 5.000000e+00, 6.000000e+00]]> : tensor<2x3xf32>
    %0 = bufferization.to_memref %cst : memref<2x3xf32, #map>
    %1 = memref.alloc() : memref<2x3xf32>
    iree_linalg_ext.reverse dimensions(dense<0> : tensor<1xi64>) ins(%0 : memref<2x3xf32, #map>) outs(%1 : memref<2x3xf32>)
    %2 = memref.load %1[%arg0, %arg0] : memref<2x3xf32>
    memref.dealloc %1 : memref<2x3xf32>
    return %2 : f32
  }
}
```

that seems off. Any quick pointers?

**Comment by hanhanW** [comment]
Looks fine? There are no IREE flow.dispatch ops, so the init_tensor is expected to be converted to `memref.alloc` op?

Or do you mean the below line? I'm confused why we need an affine_map here.

```
%0 = bufferization.to_memref %cst : memref<2x3xf32, #map>
```

**Comment by MaheshRavishankar** [comment]
That makes sense. Ok I think this was the last hold out. Let me fix the lit test and see what the presubmits say.
