### ISSUE TITLE
Other ops are not vectorized when fused with conv2d ops

### ISSUE THREAD

**Issue by pzread** [google/iree#9086]
When using the LLVMCPU codegen pipeline, in a dispatch with `fill + conv_2d_nhwc_hwcf + generic` ops, only the `conv_2d_nhwc_hwcf` is vectorized after the vectorization pass.

Example: https://gist.github.com/pzread/1d2b1f989969fcbab85efed08c3216c3

It looks like due to an incorrect filter setting on LinalgVectorizationPattern.

**Comment by hanhanW** [comment]
You may repro it with `iree-opt`: `iree-opt --pass-pipeline="func.func(linalg-single-tiling-expert-driver{vectorize})" a.mlir`

**Comment by dcaballe** [comment]
I'm observing the same issue in my RISC-V experiments

**Comment by pzread** [comment]
Fixed with #9089
