### ISSUE TITLE
Add HF minilm to nightly builders

### ISSUE THREAD

**Issue by powderluv** [google/iree#9136]
Add https://github.com/google/iree-samples/blob/main/ModelCompiler/nlp_models/huggingface_MiniLM_run.py to test nightly builds on CPU, CUDA and VULKAN.  We have a regression in Vulkan currently and the TF MHLO flow was broken previously. 

If there are good pointers on where to add it I am happy to do so.

**Comment by ThomasRaoux** [comment]
Why can't this be ran like we do for minilm benchmark on the shared GCP instance?

**Comment by powderluv** [comment]
Yes we can. But would be good to surface it in the buildkite flow

**Comment by julianwa** [comment]
Giving @pzread a heads up on this since he has it on his list to add the MiniLM BERT model to our x86 benchmarking. I assume this is the same model that we'd want for benchmarking, right?

**Comment by powderluv** [comment]
yes yes. same model.

**Comment by powderluv** [comment]
Tracked by #9318
