### ISSUE TITLE
Fix 'clz.mlir' integration test for VMVX and Vulkan

### ISSUE THREAD

**Issue by dcaballe** [google/iree#9152]
[D125592](https://reviews.llvm.org/D125592) breaks `iree/test/e2e/tosa_ops/clz.mlir` for VMVX and Vulkan:

```
/usr/local/google/home/diegocaballero/iree/iree/test/e2e/tosa_ops/clz.mlir:3:13: error: failed to legalize operation 'math.ctlz'
  %result = "tosa.clz"(%0) : (tensor<4xi32>) -> tensor<4xi32>
```

I'm disabling those tests to proceed with the integration while @rsuderman is working on a fix.

**Comment by antiagainst** [comment]
Closing given this is a duplicate with https://github.com/google/iree/issues/9191.
