### ISSUE TITLE
VMFB rodata needs to be partitioned in the flatbuffers to stay under the `uoffset_t` limit

### ISSUE THREAD

**Issue by benvanik** [google/iree#9153]
We currently embed rodata in the flatbuffer; unfortunately flatbuffers never grew 64-bit support and this limits us to ~2GB files. If removing the rodata, though, we'll never get close to 2GB (it'd have to be 2GB of bytecode!) so the easy fix that prevents the need to invent a new file format is to hoist the rodata contents into a concatenated slab following the flatbuffer.

`RodataSegmentDef` would change to contain a byte offset from the end of the flatbuffer data (+ alignment). We'd still be able to range check that the final address is within bounds of the total available data.

The current BytecodeModuleTarget impl would change to write the flatbuffer first with calculated offsets for the rodata and then follow with all of the rodata. The polyglot zip option can still be supported and actually work properly because the flatbuffers headers wouldn't be messing with things. Though the current zip output is only zip32, so that'd need to be updated to zip64...

* [x] Change bytecode_module_def.fbs
* [x] Swap BytecodeModuleTarget to calculate offsets
* [x] Add padding between flatbuffer end and rodata begin (size is written as prefix)
* [x] Write all rodata (computing CRC if needed, etc) to the output
* [x] Compute rodata offset using flatbuffers_read_size_prefix + pad logic to get the buffer offset / size is - `sizeof(flatbuffers_uoffset_t)`
* [x] Make bytecode_module.c verify rodata bounds
* [x] Have rodata_table initialization do the offsetting

**Comment by stellaraccident** [comment]
> zip is a terrible file format

True, but haven't we known that for thirty years?
