### ISSUE TITLE
[TFL] Fix `tosa.clz` lowering to not use intrinsic for VMVX and Vulkan

### ISSUE THREAD

**Issue by rsuderman** [google/iree#9191]
TOSA's clz operation generates a `math.ctlz` operation. For Vulkan and VMVX there are no lowering to a supported operation.
Add decomposition to the old path to unblock these operations.

**Comment by antiagainst** [comment]
I don't think there are SPIR-V instructions for counting leading zeros, other than Intel specific `OpUCountLeadingZerosINTEL`, so will need to rely on decomposition for now..

**Comment by benvanik** [comment]
Are there any benchmarks we have checked in that use this op? (this motivated me to add a ctlz op to the VM, but it'd be cool to see the delta :)
