### ISSUE TITLE
Add support for modifying MLIR attributes in IREE compiler API

### ISSUE THREAD

**Issue by powderluv** [google/iree#9224]
Auto tuners would like to insert attributes like LoweringConfig etc via the IREE Python API. This prevents the need to add explicit C++ passes like:

https://github.com/mmperf/mmperf/blob/main/matmul-iree/src/tiling/add-tiling-attribute-pass.cpp

We would like to achieve the same effect as the "add-tiling-attribute" pass purely using the IREE Python API. 

@MaheshRavishankar @stellaraccident

**Comment by stellaraccident** [comment]
Thanks - this should be possible with the APIs we publish (the iree.compiler API includes the MLIR Python API with IREE dialects registered). Probably the best thing to do is have me sketch out an example. May need to poke through additional bindings for some of the attributes but will see.

**Comment by powderluv** [comment]
thanks thanks

**Comment by stellaraccident** [comment]
I think this will do what you want and can be adapted:

```
import sys
from typing import List

from iree.compiler import ir
from iree.compiler.transforms import ireec

MATMUL_OP_NAMES = set([
    "linalg.matmul",
    "linalg.batch_matmul",
    "mhlo.dot",
    "mhlo.dot_general",
])


def main(ctx: ir.Context, *, input_file: str):
  with open(input_file, "rb") as f:
    input_contents = f.read()
  module = ir.Module.parse(input_contents)

  # The Python API does not expose a general walk() function, so we just
  # do it ourselves.
  walk_children(module.operation)

  if not module.operation.verify():
    raise RuntimeError("Modified program does not verify!")

  # More efficient than: print(module)
  #   - Disables verification (already done above)
  #   - Writes as binary, avoiding costly unicode conversions
  sys.stdout.buffer.write(
      module.operation.get_asm(assume_verified=True, binary=True))


def walk_children(op: ir.Operation):
  handle_operation(op)
  for region in op.regions:
    for block in region.blocks:
      for child_op in block.operations:
        # TODO: This is dumb. Both Operation and OpView should expose
        # 'operation' and 'name' attributes.
        if isinstance(child_op, ir.OpView):
          child_op = child_op.operation
        walk_children(child_op)


def handle_operation(op: ir.Operation):
  if op.name in MATMUL_OP_NAMES:
    add_compilation_info(op,
                         tile_sizes=[[32, 32], [8, 8, 0], [0, 0, 8]],
                         translation_info="CPUDoubleTilingPadExpert",
                         workgroup_size=[])
    add_split_k(op, 64)
    print(f"Updated op {op}", file=sys.stderr)


def add_compilation_info(op: ir.Operation, tile_sizes: List[List[int]],
                         translation_info: str, workgroup_size: List[int]):
  # We don't have a Python binding for CompilationInfo, so we just parse
  # its string form.
  attr = ir.Attribute.parse(
      f"#iree_codegen.compilation_info<"
      f"lowering_config = <tile_sizes = {repr(tile_sizes)}>, "
      f"translation_info = <{translation_info}>, "
      f"workgroup_size = {repr(workgroup_size)}>")
  op.attributes["compilation_info"] = attr


def add_split_k(op: ir.Operation, k: int):
  attr = ir.IntegerAttr.get(ir.IntegerType.get_signless(64), k)
  op.attributes["iree_flow_split_k"] = attr


def create_context() -> ir.Context:
  context = ir.Context()
  ireec.register_all_dialects(context)
  return context


if __name__ == "__main__":
  with create_context() as ctx:
    main(ctx, input_file=sys.argv[1])
```

**Comment by stellaraccident** [comment]
(there are some things that can be improved about it - let me know if you land it somewhere and I can make it a bit better with some upstream work)

**Comment by yzhang93** [comment]
@stellaraccident Thanks for the codes. I was able to annotate a synthetic model with multiple matmul shapes and different configs. But when I worked on the real huggingface minilm model, I had the error at this function `module = ir.Module.parse(input_contents)`, and the error is

```loc("-":2020:414): error: #"tf_type"<"shape<1x512>"> : 'none' attribute created with unregistered dialect. If this is intended, please call allowUnregisteredDialects() on the MLIRContext, or use -allow-unregistered-dialect with the MLIR opt tool used```
Any suggestions how to solve this?

**Comment by stellaraccident** [comment]
It looks like tf is littering some of its attributes. These can be ignored by setting `ctx.allow_unregistered_dialects = True` in the create_context function. See the available options: https://github.com/llvm/llvm-project/blob/827fa2c419617b40b639995ccfd43896cefd4a3c/mlir/python/mlir/_mlir_libs/_mlir/ir.pyi#L461

**Comment by yzhang93** [comment]
@stellaraccident This works. Thanks for your help!
