### ISSUE TITLE
iree-benchmark-module not being shipped with releases

### ISSUE THREAD

**Issue by raikonenfnu** [google/iree#9231]
iree-benchmark-module not being shipped with releases

**To Reproduce**
```bash
python -m pip install --find-links https://github.com/google/iree/releases iree-compiler iree-runtime
ls /path/to/venv/lib/python3.9/site-packages/iree/runtime/
#you will notice the expected iree-benchmark-module is missing.
```

According to Scott the fix/bug may be caused by the recent tool dir move, and may live somewhere here:
https://github.com/google/iree/blob/065575c8ec0b9f02dce30acc6e13a5aa89940cbf/runtime/bindings/python/CMakeLists.txt#L78-L82
https://github.com/google/iree/blob/065575c8ec0b9f02dce30acc6e13a5aa89940cbf/build_tools/cmake/iree_macros.cmake#L270-L311

@stellaraccident @ScottTodd

**Comment by ScottTodd** [comment]
I attempted to debug this a bit. I looked at a few releases [in a Colab notebook](https://colab.research.google.com/gist/ScottTodd/b8e91d79102a64bbfea052745dbbe1b9/iree-release-tools.ipynb) and by manually downloading .whl files from the releases.

* in the notebook, old and new releases had the compiler tools, but not runtime tools (`No such file or directory: '/usr/local/lib/python3.7/dist-packages/iree/runtime/scripts/iree_run_module/../../iree-run-module'`)
* just looking at the whl files directly, the runtime packages are 1MB+ lighter and are recently missing the `iree-run-trace`, `iree-run-module`, etc. binaries

In the `iree_macros.cmake`, `iree_symlink_tool` does still appear to be working when I build locally (`iree-build/runtime/bindings/python/` contains the expected symlinks and I can run the tools via those symlinks).

**Comment by ScottTodd** [comment]
Maybe some relative paths need updating for the `iree/tools/` -> `tools/` move? I could have missed such paths in my changes, like these https://github.com/google/iree/blob/b4967867b2eff4434c0f2ffb8d6f04e2bd1fe48b/runtime/bindings/python/iree/runtime/scripts/iree_run_module/__main__.py#L15

(I haven't actually narrowed this down to the tools move, bisecting through the releases to see when this started would also be a good idea)

**Comment by powderluv** [comment]
I think whatever packages the binaries needs updating. The wrapper scripts seem ok.

````
(iree-samples.venv) anush@anush-large-nvme:~/data/anush/iree-samples/ModelCompiler/nlp_models$ ireec
iree-compile: Not enough positional command line arguments specified!
Must specify at least 1 positional argument: See: /home/anush/data/anush/iree-samples/iree-samples.venv/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile --help
(iree-samples.venv) anush@anush-large-nvme:~/data/anush/iree-samples/ModelCompiler/nlp_models$ iree-run-module 
Traceback (most recent call last):
  File "/home/anush/data/anush/iree-samples/iree-samples.venv/bin/iree-run-module", line 8, in <module>
    sys.exit(main())
  File "/home/anush/data/anush/iree-samples/iree-samples.venv/lib/python3.9/site-packages/iree/runtime/scripts/iree_run_module/__main__.py", line 16, in main
    return subprocess.call(args=[exe] + args)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/anush/data/anush/iree-samples/iree-samples.venv/lib/python3.9/site-packages/iree/runtime/scripts/iree_run_module/../../iree-run-module'
````

**Comment by stellaraccident** [comment]
I'll look into it today

**Comment by powderluv** [comment]
thanks thanks. I think it may just be some path update to https://github.com/google/iree/blob/main/runtime/setup.py

**Comment by stellaraccident** [comment]
Undoubtedly... But which one :)

**Comment by stellaraccident** [comment]
Debugging session notes:

```
# From build directory:
rm iree_runtime-*.whl
pip wheel runtime/
unzip -l iree_runtime-*.whl

# Indeed, binaries are missing.
# Where are they?
find runtime/build -name iree-benchmark-module
# Nothing.
$ find . -name iree-benchmark-module
./runtime/bindings/python/iree-benchmark-module
./tools/iree-benchmark-module

# Ok, so in the build tree only, not the install tree. Boo.
# Not in the install file:
less runtime/bindings/python/cmake_install.cmake

# Appears to be in the cmake_install.cmake of the root directory,
# but is wrong:
grep iree-benchmark-module $(find . -name cmake_install.cmake)

# Printing a message from the deferred reveals that variable expansions
# are not happening:
cmake_language(DEFER DIRECTORY "${IREE_SOURCE_DIR}"
  CALL message install
  TARGETS
    iree-benchmark-module
    iree-benchmark-trace
    iree-run-module
    iree-run-trace
    ${_EXTRA_INSTALL_TOOL_TARGETS}
  DESTINATION "${_INSTALL_DIR}/iree/runtime"
  COMPONENT "${_INSTALL_COMPONENT}"
)

Prints:
installTARGETSiree-benchmark-moduleiree-benchmark-traceiree-run-moduleiree-run-traceDESTINATION/iree/runtimeCOMPONENT

From the manual: "Variable references in arguments are evaluated at the time the deferred call is executed."
Boo.
```
