### ISSUE TITLE
[vmla] error: 'vmla.buffer.clone' op requires one result

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#932]
Failing test: test/e2e/xla/mnist.mlir

loc(callsite("third_party/iree/test/e2e/xla/mnist.mlir split at line #1":12:10 at fused["third_party/iree/test/e2e/xla/mnist.mlir split at line #1":12:10, "third_party/iree/test/e2e/xla/mnist.mlir split at line #1":14:10])): error: 'vmla.buffer.clone' op requires one result

**Comment by stellaraccident** [comment]
Appears to be related to legalization of xla_hlo.copy:

/google/src/cloud/laurenzo/vmla4/google3/third_party/iree/test/e2e/xla/fullyconnected.mlir:48:9: error: 'vmla.buffer.clone' op requires one result
  %27 = "xla_hlo.copy"(%arg1) {name = "copy.3"} : (tensor<1x5x3x1xf32>) -> tensor<1x5x3x1xf32>

**Comment by stellaraccident** [comment]
%1 = "xla_hlo.copy"(%0) {name = "copy.3"} : (tensor<1x5x3x1xf32>) -> tensor<1x5x3x1xf32> 
"vmla.buffer.clone"(%7, %14) {name = "copy.3"} : (!vmla.buffer, !vmla.buffer) -> ()

**Comment by benvanik** [comment]
ah yeah, copy needs its own rewriter:
https://source.corp.google.com/piper///depot/google3/third_party/iree/iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertHLOToVMLA.cpp;l=449-460

right now it's using the default which is trying to allocate an output buffer and pass that in

**Comment by stellaraccident** [comment]
Can it just use the IdentityOpConversion?

**Comment by benvanik** [comment]
I believe so (as we don't do in-place updates) - I'm not honestly sure why copy exists at all in HLO
