### ISSUE TITLE
[vmla] test/e2e/xla/through_std.mlir failing

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#933]
third_party/iree/test/e2e/xla/through_std.mlir:11:11: error: CHECK: expected string not found in input
// CHECK: f32=2
          ^
<stdin>:2:1: note: scanning from here
f32=1
^

Input file: <stdin>
Check file: third_party/iree/test/e2e/xla/through_std.mlir

-dump-input=help describes the format of the following dump.

Full input was:
<<<<<<
          1: EXEC @xla_through_stdops
          2: f32=1
check:11     X~~~~ error: no match found
          3: f32=1
check:11     ~~~~~

**Comment by benvanik** [comment]
I believe this is fixed with the VMLA_PureOp -> VMLA_Op change to prevent alloc collapsing. Passes for me (windows/cmake) now.
