### ISSUE TITLE
Failed to legalize operation 'mhlo.scatter'

### ISSUE THREAD

**Issue by Birch-san** [google/iree#9361]
thanks for everyone's effort so far in getting iree to utilise the M1 GPU via Vulkan. 🙂 

**Describe the bug**

```python
from iree import compiler

CODE = """
#loc0 = loc(unknown)
module @jit_prim_fun.12 {
  func.func public @main(%arg0: tensor<1x1xi32> loc(unknown), %arg1: tensor<1xi32> loc(unknown), %arg2: tensor<1xi32> loc(unknown)) -> tensor<1x1xi32> {
    %0 = "mhlo.scatter"(%arg0, %arg1, %arg2) ({
    ^bb0(%arg3: tensor<i32> loc(unknown), %arg4: tensor<i32> loc(unknown)):
      "mhlo.return"(%arg4) : (tensor<i32>) -> () loc(#loc1)
    }) {indices_are_sorted = true, scatter_dimension_numbers = #mhlo.scatter<update_window_dims = [0], inserted_window_dims = [1], scatter_dims_to_operand_dims = [1]>, unique_indices = true} : (tensor<1x1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<1x1xi32> loc(#loc1)
    return %0 : tensor<1x1xi32> loc(#loc0)
  } loc(#loc0)
  } loc(#loc0)
#loc1 = loc("jit(scatter)/jit(main)/scatter[update_consts=() dimension_numbers=ScatterDimensionNumbers(update_window_dims=(0,), inserted_window_dims=(1,), scatter_dims_to_operand_dims=(1,)) indices_are_sorted=True unique_indices=True mode=GatherScatterMode.FILL_OR_DROP]"("/Users/birch/anaconda3/envs/torch-nightly/lib/python3.9/site-packages/transformers/models/bart/modeling_flax_bart.py":926:1))
"""

extra_args = ["--mlir-print-ir-after-failure"]

# also reproduces with backend "dylib", the default backend for macOS
iree_binary = compiler.compile_str(
    CODE, target_backends=["vulkan"], input_type="mhlo", extra_args=extra_args)
```

```
Error invoking IREE compiler tool iree-compile
Diagnostics:
/Users/birch/anaconda3/envs/torch-nightly/lib/python3.9/site-packages/transformers/models/bart/modeling_flax_bart.py:926:1: error: failed to legalize operation 'mhlo.scatter' that was explicitly marked illegal
        input_ids = input_ids.at[(..., -1)].set(self.config.eos_token_id)
```

```mlir
// -----// IR Dump After ConvertMHLOToLinalgExt Failed //----- //
func.func public @main(%arg0: tensor<1x1xi32> loc(unknown), %arg1: tensor<1xi32> loc(unknown), %arg2: tensor<1xi32> loc(unknown)) -> tensor<1x1xi32> {
  %0 = "mhlo.scatter"(%arg0, %arg1, %arg2) ({
  ^bb0(%arg3: tensor<i32> loc(unknown), %arg4: tensor<i32> loc(unknown)):
    "mhlo.return"(%arg4) : (tensor<i32>) -> () loc("jit(scatter)/jit(main)/scatter[update_consts=() dimension_numbers=ScatterDimensionNumbers(update_window_dims=(0,), inserted_window_dims=(1,), scatter_dims_to_operand_dims=(1,)) indices_are_sorted=True unique_indices=True mode=GatherScatterMode.FILL_OR_DROP]"("/Users/birch/anaconda3/envs/torch-nightly/lib/python3.9/site-packages/transformers/models/bart/modeling_flax_bart.py":926:1))
  }) {indices_are_sorted = true, scatter_dimension_numbers = #mhlo.scatter<update_window_dims = [0], inserted_window_dims = [1], scatter_dims_to_operand_dims = [1]>, unique_indices = true} : (tensor<1x1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<1x1xi32> loc("jit(scatter)/jit(main)/scatter[update_consts=() dimension_numbers=ScatterDimensionNumbers(update_window_dims=(0,), inserted_window_dims=(1,), scatter_dims_to_operand_dims=(1,)) indices_are_sorted=True unique_indices=True mode=GatherScatterMode.FILL_OR_DROP]"("/Users/birch/anaconda3/envs/torch-nightly/lib/python3.9/site-packages/transformers/models/bart/modeling_flax_bart.py":926:1))
  return %0 : tensor<1x1xi32> loc(unknown)
} loc(unknown)
```

```
Invoked with:
 iree-compile /Users/birch/anaconda3/envs/torch-nightly/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/birch/anaconda3/envs/torch-nightly/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --mlir-print-ir-after-failure
```

to do a more realistic macOS/MoltenVK integration, I'd recommend the following `extra_args` too:  
https://github.com/nod-ai/SHARK/blob/1186d7c58e6046aea6a6115c608dbd77728e7aca/shark/iree_utils.py#L93-L96

```python
extra_args += [
"--iree-llvm-target-triple=arm64-apple-darwin21.5.0",
"--iree-flow-demote-i64-to-i32",
"--iree-vulkan-target-triple=m1-moltenvk-macos",
"--iree-llvm-target-cpu-features=host",
"--iree-mhlo-demote-i64-to-i32=false"]
```

the problem reproduces either way.

**reproducing in _integration context_**

Using very-new jax+jaxlib and iree, I invoked a known-good jax model [`dalle-playground`](https://github.com/saharmor/dalle-playground), with environment variables:

```bash
JAX_PLATFORMS=iree
JAX_IREE_BACKEND=vulkan
````

and `extra_args`:

```python
extra_args += [
"--iree-llvm-target-triple=arm64-apple-darwin21.5.0",
"--iree-flow-demote-i64-to-i32",
"--iree-vulkan-target-triple=m1-moltenvk-macos",
"--iree-llvm-target-cpu-features=host",
"--iree-mhlo-demote-i64-to-i32=false"]
```

Then follow [these steps](https://github.com/google/jax/issues/8074#issuecomment-1147994168) to install & run [dalle-playground](https://github.com/saharmor/dalle-playground).  
Typical output looks [like this](https://gist.github.com/Birch-san/fb3d77f102bb177e4095df5c9be5702f).

**Additional context**

I reproduced this against:  
jax+jaxlib commit https://github.com/google/jax/commit/345cc19949273cc414d94e6f13d0620b780af465 (which I built myself locally)  
iree compiler+runtime release [candidate-20220606.161](https://github.com/google/iree/releases/tag/candidate-20220606.161) (https://github.com/google/iree/commit/f90a3a13807b312407d08a20965a6b5774e3371b)  
dalle-playground commit https://github.com/saharmor/dalle-playground/commit/5a7be250e5c377b18a3f9f07631d177bcf91c934  
MacBook Pro (14-inch, 2021) M1 Max (2 efficiency cores + 8 perf cores + 64GB unified memory + 32 GPU cores)

**Comment by antiagainst** [comment]
Actually this fails in the `ConvertMHLOToLinalgExt` pass. So it's not specific to Vulkan.

**Comment by jpienaar** [comment]
Thanks for reporting, let me try and make a dump here.

**Comment by jpienaar** [comment]
Testing with

```bash
mlir-hlo-opt --hlo-legalize-to-linalg /tmp/test.mlir 
```

I get

```mlir
#map0 = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (0)>
#map2 = affine_map<(d0, d1) -> (d0)>
module @jit_prim_fun.12 {
  func.func public @main(%arg0: tensor<1x1xi32>, %arg1: tensor<1xi32>, %arg2: tensor<1xi32>) -> tensor<1x1xi32> {
    %0 = linalg.generic {indexing_maps = [#map0, #map1, #map2, #map0], iterator_types = ["parallel", "parallel"]} ins(%arg0, %arg1, %arg2 : tensor<1x1xi32>, tensor<1xi32>, tensor<1xi32>) outs(%arg0 : tensor<1x1xi32>) {
    ^bb0(%arg3: i32, %arg4: i32, %arg5: i32, %arg6: i32):
      %1 = linalg.index 1 : index
      %2 = arith.index_cast %arg4 : i32 to index
      %3 = arith.cmpi eq, %1, %2 : index
      %4 = arith.select %3, %arg5, %arg6 : i32
      linalg.yield %4 : i32
    } -> tensor<1x1xi32>
    return %0 : tensor<1x1xi32>
  }
}
```

So that seems to work, but I wasn't using that exact version above.

**Comment by jpienaar** [comment]
Same works at the tag. 

If in src/iree/compiler/InputConversion/MHLO/Passes.cpp I switch 

passManager.addNestedPass<func::FuncOp>(createConvertMHLOToLinalgExtPass());
  passManager.addNestedPass<func::FuncOp>(createMHLOToLinalgOnTensorsPass());

around, then it passes. 

Seems due to 

```
target.addIllegalOp<mhlo::SortOp, mhlo::ScatterOp, mhlo::FftOp,
                        mhlo::ReverseOp>();
```

in ConvertMHLOToLinalgExt.cpp and so any Scatter that can't be lowered to LinalgExt version would fail. Assigning to @hanhanW who added this for comment.

**Comment by Birch-san** [comment]
btw here's the original PR where mhlo::ScatterOp was designated illegal: https://github.com/google/iree/pull/6419

**Comment by hanhanW** [comment]
We should lower the op to linalg_ext.scatter. We don't want to use the pattern in `hlo-legalize-to-linalg` because it's very fragile, limited and expensive. (The pattern was added by me, and we end up with not using it. Maybe we should delete the pattern though...)

@rsuderman can you help look into what's missing in the lowering for this case?

**Comment by jpienaar** [comment]
It fails to match as this scatter doesn't have canonical dimension numbers. In particular it requires the rank of scatter indices to be at least 2 - but canonicalize doesn't pass doesn't affect this op. Perhaps a missing canonicalization.

**Comment by rsuderman** [comment]
Looking into it now. Chances are its a edge case missed during the lowering to `linalg_ext.scatter`. In most cases its not that complicated. There are also some earlier legalizations that attempt to turn complex scatters to simpler ones.

**Comment by rsuderman** [comment]
Determined the issue but its not clear whether it has a good fix. The implementation is scatter to a lower dimension and updating a window across a higher dimension. My understanding is JAX was not supposed to generate scattering to only lower dimensions. Trying to think of a fix beyond transposing the destination tensor and transposing back.

**Comment by MaheshRavishankar** [comment]
@rsuderman could you write the expected semantics in loop form to help me understand whats going on here.

**Comment by alliemartens** [comment]
Hey Rob, any update on this?

**Comment by Birch-san** [comment]
As a stopgap, it does sound like this PR would be an improvement over the current behaviour (i.e. failure):  
https://github.com/google/iree/pull/9378

**Comment by Birch-san** [comment]
@MaheshRavishankar 
perhaps this issue should be reopened, to continue tracking a "preferred solution" described here:  
https://github.com/google/iree/pull/9378#issuecomment-1159520812

**Comment by MaheshRavishankar** [comment]
@Birch-san even if we keep it open, we dont know exactly the form of scatter or what is needed here to support this. Its unlikely to be a high priority for us in the next few months. If this is of interest to you, I am happy to keep this open and suggest some ways forward.
