### ISSUE TITLE
Add flag to python API for controlling IREE_SAVE_TEMP behavior.

### ISSUE THREAD

**Issue by powderluv** [google/iree#9460]
### Request description

When we set IREE_SAVE_TEMPS env var it seems to be overwriting files when we loop through a set of tests etc. 

It would be great if IREE_SAVE_TEMPS created a `date`_uuid directory of each run. This is so that we can run 100s of tests in parallel and capture all the SAVE_TEMPS in the root IREE_SAVE_TEMPS dir. 

I know in the Python API the mlir file is input as stdin so we may not have access to a model or program name -- but if there was such a flag we can set it during large tests so it is easy to find the IREE_SAVE_TEMPS dir corresponding to a particular model. 

### What component(s) does this issue relate to?

Compiler

**Comment by benvanik** [comment]
You can do this by setting the env var to a unique value yourself - we don't want to do this ourselves as it'll make it impossible to make stable tooling.

**Comment by benvanik** [comment]
Instead of using the env var for programmatic invocations there should be a flag that does this instead.

**Comment by powderluv** [comment]
From @ScottTodd "{id} - A per-process monotonically increasing number for each compiler invocation. Can be overridden by the API if a better symbolic name is available (i.e. test case, etc)."

https://iree-python-api.readthedocs.io/en/latest/compiler/tools.html#module-iree.compiler.tools.debugging
