### ISSUE TITLE
matmul+add+broadcast_maximum  output is all NAN

### ISSUE THREAD

**Issue by sun2011yao** [google/iree#9493]
### What happened?

HI, excuse me. I met a problem. Transformer model results are wrong, they are all NAN. I ran the mlir file below and the output is all NAN

func.func @predict() -> tensor<8x32x256xf32> {
    %10 = "mhlo.constant"() {value = dense<0.000000e+00> : tensor<f32>} : () -> tensor<f32>
    %194 = util.unfoldable_constant dense<2.2> : tensor<256x128xf32>
    %118 = util.unfoldable_constant dense<0.78132498> : tensor<128x256xf32>
    %195 = "mhlo.dot"(%194, %118) : (tensor<256x128xf32>, tensor<128x256xf32>) -> tensor<256x256xf32>
    %196 = "mhlo.reshape"(%195) : (tensor<256x256xf32>) -> tensor<8x32x256xf32>
    %197 = util.unfoldable_constant dense<0.78132498> : tensor<8x32x256xf32>
    %198 = "mhlo.add"(%196, %197) : (tensor<8x32x256xf32>, tensor<8x32x256xf32>) -> tensor<8x32x256xf32>
    %199 = "chlo.broadcast_maximum"(%198, %10) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<8x32x256xf32>, tensor<f32>) -> tensor<8x32x256xf32>
    return %199 : tensor<8x32x256xf32>
}

### Steps to reproduce your issue

1. iree-compile --iree-input-type=mhlo \
      --mlir-disable-threading \
      --iree-mlir-to-vm-bytecode-module \
      --iree-hal-target-backends=cuda \
      --iree-hal-cuda-llvm-target-arch=sm_80 \
     test.mlir -o test.vmfb

3. iree-run-module --module_file=./test.vmfb --device=cuda --entry_function=predict
4. output is all NAN,  If i removed --iree-hal-cuda-llvm-target-arch=sm_80 compile option, result is normal.

### What component(s) does this issue relate to?

Compiler, Runtime

### Version information
latest commit, commit id 597b310a4a475a25875efc4c6d476e35de38adb3

**Comment by ThomasRaoux** [comment]
Thanks for reporting and for the great bug report. I fixed the bug in MLIR:
https://github.com/llvm/llvm-project/commit/a6f2c2291ede82777fb3b92c6f2ea78d56e97aca

This should be integrated in IREE in few days. I'll close the bug at that time. Hopefully you should be able to cherry-pick the fix in the meantime if needed.

**Comment by sun2011yao** [comment]
OK, thanks a lot

**Comment by ThomasRaoux** [comment]
Fix has been integrated so I'm closing the issue
