### ISSUE TITLE
vulkan numerics issues for HF models (regression)

### ISSUE THREAD

**Issue by powderluv** [google/iree#9554]
### What happened?

In the last few days a few of these models that passed have regressed:

https://github.com/nod-ai/SHARK/runs/6945964371?check_suite_focus=true#step:9:691

=========================== short test summary info ============================
FAILED tank/pytorch/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_pytorch_test.py::MiniLMModuleTest::test_module_dynamic_vulkan
FAILED tank/pytorch/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_pytorch_test.py::MiniLMModuleTest::test_module_static_vulkan
FAILED tank/pytorch/albert-base-v2/albert-base-v2_pytorch_test.py::AlbertModuleTest::test_module_dynamic_vulkan
FAILED tank/pytorch/bert-base-uncased/bert-base-uncased_pytorch_test.py::BertModuleTest::test_module_dynamic_vulkan
FAILED tank/pytorch/bert-base-uncased/bert-base-uncased_pytorch_test.py::BertModuleTest::test_module_static_vulkan
FAILED tank/pytorch/distilbert-base-uncased/distilbert-base-uncased_pytorch_test.py::DistilBertModuleTest::test_module_static_vulkan

### Steps to reproduce your issue

on a nod VM

```shell
git clone https://github.com/nod-ai/SHARK.git
PYTHON=python3.10 VENV_DIR=0617_venv IMPORTER=1 USE_IREE=1 ./setup_venv.sh 
source 0617_venv/bin/activate
pytest tank/pytorch/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_pytorch_test.py::MiniLMModuleTest::test_module_dynamic_vulkan
# replace with corresponding failing test
```

**Comment by powderluv** [comment]
save_temp Files are in gs://iree-shared-files/nod-perf/anush/iree_save_temps_vulkan_minilm/

**Comment by powderluv** [comment]
This test passes with https://github.com/google/iree/releases/tag/candidate-20220615.172 but fails on .175

**Comment by powderluv** [comment]
the regression happened between build 172 and 173


https://github.com/google/iree/compare/candidate-20220615.172...candidate-20220616.173

So it is likely: 
https://github.com/google/iree/commit/28bcb5534b9d2b8e04b8dc81b063554aa9118b22

**Comment by pashu123** [comment]
There is the same numeric issue problem with the bert-base-uncased model. The dumps are core-command-line.txt - https://storage.googleapis.com/shark-public/prashant/vulkan-bert/core-command-line.txt  core-input.mlir - https://storage.googleapis.com/shark-public/prashant/vulkan-bert/core-input.mlir core-output.bin - https://storage.googleapis.com/shark-public/prashant/vulkan-bert/core-output.bin

**Comment by antiagainst** [comment]
Okay this is a bug I introduced when tweaking `UnifyAliasedResourcePass` upstream. Endianness and bitcast were not properly aligned previously.. https://reviews.llvm.org/D128473 to fix this.

**Comment by antiagainst** [comment]
Closing this given https://reviews.llvm.org/D128473 was landed and no further fixes are needed. (Just need to integrate it next.)
