### ISSUE TITLE
It should be possible to accept and return tensor<i1>

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#958]
Currently, this results in a warning such as: Result #0 of function simple_mul is not a recognized public ABI type and the function may not be invokable by standard tools

(and the function will not be invokable from Python, et al)

**Comment by benvanik** [comment]
@hanhanW I believe you fixed this, correct? if so you can tag as obsolete and close

**Comment by benvanik** [comment]
This may be related to #3102 but different parts of the system (this is the python API/etc, but #3102 is the compiler internals).

**Comment by hanhanW** [comment]
Tested, I think this is fixed.

```mlir
func @compare_tensor() -> tensor<4xi1> attributes { iree.module.export } {
  %lhs = iree.unfoldable_constant dense<[1, 2, 7, 4]> : tensor<4xi32>
  %rhs = iree.unfoldable_constant dense<[5, 2, 3, 4]> : tensor<4xi32>
  %result = "mhlo.compare"(%lhs, %rhs) {comparison_direction = "EQ"} : (tensor<4xi32>, tensor<4xi32>) -> tensor<4xi1>
  return %result : tensor<4xi1>
}
```
