### ISSUE TITLE
Failing test for ROCM

### ISSUE THREAD

**Issue by nirvedhmeshram** [google/iree#9584]
```
./iree-compile -iree-mlir-to-vm-bytecode-module 
-iree-hal-target-backends=rocm iree/tests/e2e/xla_ops/compare.mlir -o compare_rocm.vmfb --iree-input-type=mhlo
```
followed by
```
./iree-check-module compare_rocm.vmfb --device=rocm
```
gives the following output 
https://gist.github.com/nirvedhmeshram/20e3b190931a2f93c741d4897f7c3c15
essentially eq comparison operation fails for 0d tensor, I have actually verfied that it works for 1d tensor.
Here are codgen dumps for the failing case
 For ROCM 
[compare_codetrace_rocm.txt](https://github.com/google/iree/files/8961466/compare_codetrace_rocm.txt)
FOR CUDA ( as a ground truth)
[compare_codetrace_cuda.txt](https://github.com/google/iree/files/8961468/compare_codetrace_cuda.txt)

From my observation I do not see any issue in codgen, there could potentially be something  off in experimental/rocm. I would appreciate any help in narrowing down this issue.

**Comment by powderluv** [comment]
Isn't this fixed ? Should we close it out ?
