### ISSUE TITLE
A number of e2e tests are failing in the OSS build

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#96]
These are not failing upstream and I have not triaged to figure out if it is a real issue or automation problem. Some e2e tests are working, so if it is automation, it is subtle.

Repro: bazel test //test/...
---
//test/e2e:cmpf.mlir.test                                                FAILED in 0.6s
  /usr/local/google/home/laurenzo/.cache/bazel/_bazel_laurenzo/aeb2f2bb7cbc4eb68307c702c2306745/execroot/iree_core/bazel-out/k8-opt/testlogs/test/e2e/cmpf.mlir.test/test.log
//test/e2e:cmpi.mlir.test                                                FAILED in 0.8s
  /usr/local/google/home/laurenzo/.cache/bazel/_bazel_laurenzo/aeb2f2bb7cbc4eb68307c702c2306745/execroot/iree_core/bazel-out/k8-opt/testlogs/test/e2e/cmpi.mlir.test/test.log
//test/e2e:extract_element.mlir.test                                     FAILED in 0.3s
  /usr/local/google/home/laurenzo/.cache/bazel/_bazel_laurenzo/aeb2f2bb7cbc4eb68307c702c2306745/execroot/iree_core/bazel-out/k8-opt/testlogs/test/e2e/extract_element.mlir.test/test.log
//test/e2e/xla:fragment_000.mlir.test                                    FAILED in 0.6s
  /usr/local/google/home/laurenzo/.cache/bazel/_bazel_laurenzo/aeb2f2bb7cbc4eb68307c702c2306745/execroot/iree_core/bazel-out/k8-opt/testlogs/test/e2e/xla/fragment_000.mlir.test/test.log
//test/e2e/xla:pad.mlir.test                                             FAILED in 0.3s
  /usr/local/google/home/laurenzo/.cache/bazel/_bazel_laurenzo/aeb2f2bb7cbc4eb68307c702c2306745/execroot/iree_core/bazel-out/k8-opt/testlogs/test/e2e/xla/pad.mlir.test/test.log
//test/e2e/xla:reverse.mlir.test                                         FAILED in 0.3s
  /usr/local/google/home/laurenzo/.cache/bazel/_bazel_laurenzo/aeb2f2bb7cbc4eb68307c702c2306745/execroot/iree_core/bazel-out/k8-opt/testlogs/test/e2e/xla/reverse.mlir.test/test.log
//test/e2e/xla:through_std.mlir.test                                     FAILED in 1.0s
  /usr/local/google/home/laurenzo/.cache/bazel/_bazel_laurenzo/aeb2f2bb7cbc4eb68307c702c2306745/execroot/iree_core/bazel-out/k8-opt/testlogs/test/e2e/xla/through_std.mlir.test/test.log
//test/e2e/xla:unidirectional_lstm.mlir.test                             FAILED in 0.6s
  /usr/local/google/home/laurenzo/.cache/bazel/_bazel_laurenzo/aeb2f2bb7cbc4eb68307c702c2306745/execroot/iree_core/bazel-out/k8-opt/testlogs/test/e2e/xla/unidirectional_lstm.mlir.test/test.log

**Comment by GMNGeoffrey** [comment]
At first look, this appears to be an issue with debug logging from run-mlir getting printed and so breaking the FileCheck CHECK-NEXT. God I do not love FileCheck for this use case...

**Comment by GMNGeoffrey** [comment]
Have a change out to fix this
