### ISSUE TITLE
Failed to link samples/simple_embedding/simple_embedding_vmvx_sync

### ISSUE THREAD

**Issue by jpienaar** [google/iree#9615]
### What happened?

```
: && /usr/bin/cc -O2 -g -DNDEBUG -lm -lpthread samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/device_vmvx_sync.c.o samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/simple_embedding.c.o -o samples/simple_embedding/simple_embedding_vmvx_sync  samples/simple_embedding/libiree_samples_simple_embedding_simple_embedding_test_bytecode_module_vmvx_c.a  runtime/src/iree/base/libiree_base_base.a  runtime/src/iree/hal/libiree_hal_hal.a  runtime/src/iree/hal/drivers/local_sync/libiree_hal_drivers_local_sync_sync_driver.a  runtime/src/iree/hal/local/libiree_hal_local_local.a  runtime/src/iree/hal/local/loaders/libiree_hal_local_loaders_vmvx_module_loader.a  runtime/src/iree/modules/hal/libiree_modules_hal_hal.a  runtime/src/iree/vm/libiree_vm_bytecode_module.a  runtime/src/iree/base/internal/libiree_base_internal_arena.a  runtime/src/iree/base/internal/libiree_base_internal_atomic_slist.a  runtime/src/iree/hal/utils/libiree_hal_utils_buffer_transfer.a  runtime/src/iree/hal/utils/libiree_hal_utils_semaphore_base.a  runtime/src/iree/hal/local/libiree_hal_local_local.a  runtime/src/iree/hal/local/libiree_hal_local_executable_environment.a  runtime/src/iree/base/internal/libiree_base_internal_cpu.a  runtime/src/iree/base/internal/libiree_base_internal_fpu_state.a  build_tools/third_party/flatcc/libflatcc_parsing.a  -lm  -lpthread  runtime/src/iree/modules/vmvx/libiree_modules_vmvx_vmvx.a  runtime/src/iree/hal/libiree_hal_hal.a  runtime/src/iree/base/internal/libiree_base_internal_path.a  runtime/src/iree/base/internal/libiree_base_internal_synchronization.a  runtime/src/iree/vm/libiree_vm_impl.a  runtime/src/iree/base/libiree_base_base.a && :
/usr/bin/ld: runtime/src/iree/base/internal/libiree_base_internal_synchronization.a(synchronization.c.o): in function `iree_mutex_try_lock':
/usr/local/google/home/jpienaar/Compiles/iree/runtime/src/iree/base/internal/synchronization.c:260: undefined reference to `pthread_mutex_trylock'
collect2: error: ld returned 1 exit status
```

### Steps to reproduce your issue

1. Checkout
2. Configure and run with cmake -GNinja -B ../iree-build/ \
                                                  -DCMAKE_INSTALL_PREFIX=../iree-build/install \
                                                  -DCMAKE_BUILD_TYPE=RelWithDebInfo
                                              .
                                            cmake --build ../iree-build/ --target install

### What component(s) does this issue relate to?

Runtime

### Version information

Git rev 0e8d8370699912c6b51889e8f7e967690102402c

**Comment by benvanik** [comment]
Can you give more information about the platform? All the bots are fine and `-lpthread` is on the command line, so I'm going to guess whatever it is you're running on doesn't have `pthread_mutex_trylock`. That's existed for quite awhile so not sure where you are missing it.

**Comment by benvanik** [comment]
This may also be flag order related - the `-lpthread` is at the start, when I feel like it may need to go later in the listing. For some reason. I hate linkers. Stella may have tracked this kind of thing down in the past.

**Comment by jpienaar** [comment]
Yes, it is weird, yesterday no issues and today I barely can get a working build. The failing command works if I move -lpthread to end. So 

/usr/bin/cc -O2 -g -DNDEBUG -lm -lpthread samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/device_vmvx_sync.c.o samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/simple_embedding.c.o -o samples/simple_embedding/simple_embedding_vmvx_sync  samples/simple_embedding/libiree_samples_simple_embedding_simple_embedding_test_bytecode_module_vmvx_c.a  runtime/src/iree/base/libiree_base_base.a  runtime/src/iree/hal/libiree_hal_hal.a  runtime/src/iree/hal/drivers/local_sync/libiree_hal_drivers_local_sync_sync_driver.a  runtime/src/iree/hal/local/libiree_hal_local_local.a  runtime/src/iree/hal/local/loaders/libiree_hal_local_loaders_vmvx_module_loader.a  runtime/src/iree/modules/hal/libiree_modules_hal_hal.a  runtime/src/iree/vm/libiree_vm_bytecode_module.a  runtime/src/iree/base/internal/libiree_base_internal_arena.a  runtime/src/iree/base/internal/libiree_base_internal_atomic_slist.a  runtime/src/iree/hal/utils/libiree_hal_utils_buffer_transfer.a  runtime/src/iree/hal/utils/libiree_hal_utils_semaphore_base.a  runtime/src/iree/hal/local/libiree_hal_local_local.a  runtime/src/iree/hal/local/libiree_hal_local_executable_environment.a  runtime/src/iree/base/internal/libiree_base_internal_cpu.a  runtime/src/iree/base/internal/libiree_base_internal_fpu_state.a  build_tools/third_party/flatcc/libflatcc_parsing.a  -lm  -lpthread  runtime/src/iree/modules/vmvx/libiree_modules_vmvx_vmvx.a  runtime/src/iree/hal/libiree_hal_hal.a  runtime/src/iree/base/internal/libiree_base_internal_path.a  runtime/src/iree/base/internal/libiree_base_internal_synchronization.a  runtime/src/iree/vm/libiree_vm_impl.a  runtime/src/iree/base/libiree_base_base.a

fails, but 

/usr/bin/cc -O2 -g -DNDEBUG -lm -lpthread samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/device_vmvx_sync.c.o samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/simple_embedding.c.o -o samples/simple_embedding/simple_embedding_vmvx_sync  samples/simple_embedding/libiree_samples_simple_embedding_simple_embedding_test_bytecode_module_vmvx_c.a  runtime/src/iree/base/libiree_base_base.a  runtime/src/iree/hal/libiree_hal_hal.a  runtime/src/iree/hal/drivers/local_sync/libiree_hal_drivers_local_sync_sync_driver.a  runtime/src/iree/hal/local/libiree_hal_local_local.a  runtime/src/iree/hal/local/loaders/libiree_hal_local_loaders_vmvx_module_loader.a  runtime/src/iree/modules/hal/libiree_modules_hal_hal.a  runtime/src/iree/vm/libiree_vm_bytecode_module.a  runtime/src/iree/base/internal/libiree_base_internal_arena.a  runtime/src/iree/base/internal/libiree_base_internal_atomic_slist.a  runtime/src/iree/hal/utils/libiree_hal_utils_buffer_transfer.a  runtime/src/iree/hal/utils/libiree_hal_utils_semaphore_base.a  runtime/src/iree/hal/local/libiree_hal_local_local.a  runtime/src/iree/hal/local/libiree_hal_local_executable_environment.a  runtime/src/iree/base/internal/libiree_base_internal_cpu.a  runtime/src/iree/base/internal/libiree_base_internal_fpu_state.a  build_tools/third_party/flatcc/libflatcc_parsing.a  -lm  -lpthread  runtime/src/iree/modules/vmvx/libiree_modules_vmvx_vmvx.a  runtime/src/iree/hal/libiree_hal_hal.a  runtime/src/iree/base/internal/libiree_base_internal_path.a  runtime/src/iree/base/internal/libiree_base_internal_synchronization.a  runtime/src/iree/vm/libiree_vm_impl.a  runtime/src/iree/base/libiree_base_base.a -lpthread

passes. So yes, flag order. But with buildbots all green this is weird, why failing for me locally.

 Linux platform (), GCC GNU 11.3.0, Ninja 1.10.2.git.kitware.jobserver-1

**Comment by benvanik** [comment]
Maybe it's gcc and we mostly build with clang? we do have a gcc build configuration but maybe it doesn't build this sample?

**Comment by jpienaar** [comment]
Good point, I normally set clang and didn't when I nuked the dirs (and potentially I messed that up earlier too when I was changing options)

**Comment by jpienaar** [comment]
Yes that was it, switching to clang resolved it.
