### ISSUE TITLE
custom op 'func' is unknown

### ISSUE THREAD

**Issue by Birch-san** [google/iree#9619]
### What happened?

This is the next bug trying to run [dalle-playground](https://github.com/saharmor/dalle-playground) on JAX/IREE.

```
Exception has occurred: CompilerToolError
Error invoking IREE compiler tool iree-compile
Diagnostics:
<stdin>:4:5: error: custom op 'func' is unknown (tried 'builtin.func' as well)
    func public @main(%arg0: tensor<i32> loc(unknown), %arg1: tensor<i32> loc(unknown)) -> tensor<i32> {
    ^


Invoked with:
 iree-compile /Users/birch/git/iree-build/compiler/bindings/python/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-llvm-embedded-linker-path=/Users/birch/git/iree-build/compiler/bindings/python/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
  File "/Users/birch/git/iree-build/compiler/bindings/python/iree/compiler/tools/binaries.py", line 196, in invoke_immediate
    raise CompilerToolError(process)
  File "/Users/birch/git/iree-build/compiler/bindings/python/iree/compiler/tools/core.py", line 277, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/Users/birch/git/dalle-playground/backend/repro.py", line 302, in <module>
    compiler.compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

### Steps to reproduce your issue

```python
from iree import compiler

CODE = """
#loc0 = loc(unknown)
module @jit_prim_fun.0 {
    func public @main(%arg0: tensor<i32> loc(unknown), %arg1: tensor<i32> loc(unknown)) -> tensor<i32> {
      %0 = mhlo.shift_right_logical %arg0, %arg1 : tensor<i32> loc(#loc1)
    return %0 : tensor<i32> loc(#loc0)
  } loc(#loc0)
} loc(#loc0)
#loc1 = loc("jit(shift_right_logical)/jit(main)/shift_right_logical"("/Users/birch/git/dalle-playground/backend/dalle/lib/python3.9/site-packages/transformers/modeling_flax_utils.py":205:1))
"""

compiler.compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

### What component(s) does this issue relate to?

MLIR, Compiler

### Version information

I reproduced this against:  
jax+jaxlib commit https://github.com/google/jax/commit/62c16da81fed05d7e0e0405ac3cf2e5a0be04573 (which I built myself locally)  
iree compiler+runtime commit https://github.com/google/iree/commit/0e8d8370699912c6b51889e8f7e967690102402c (which I built myself locally)  
dalle-playground commit https://github.com/Birch-san/dalle-playground/commit/a4b5b4ca1bc0dab8a4461c2bc306a6305fb9fe8e  
MacBook Pro (14-inch, 2021) M1 Max (2 efficiency cores + 8 perf cores + 64GB unified memory + 32 GPU cores)

### Additional context

the repository is known-good (works on JAX/XLA backend), but JAX/IREE is unproven territory.

**Comment by antiagainst** [comment]
`func` was renamed to `func.func`. You'd need to update `func` to `func.func` in `CODE`.

**Comment by jpienaar** [comment]
Yes, as Lei mentions there was a rename here. Serialized .mlir is not stable, best to use Jax python APIs where available (at least if MHLO is your target should give you much better experience).

**Comment by Birch-san** [comment]
ah thanks for diagnosing. this MLIR _was_ authored by JAX, but I'd inadvertently reverted to an older version of JAX (I'd migrated to using a virtualenv, which isolated me from the latest-JAX that I installed globally). will try again with newer JAX.
